### ISSUE TITLE
Please help to define the details for the backend

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1]

**Comment by rafalkowalski** [comment]
Maybe Django will be better than Flask ? I think that it will be better to maintain

**Comment by leto** [comment]
@rafalkowalski please explain why

**Comment by rafalkowalski** [comment]
I never used Flask, just I like the structure of django. In django We are able to create app in fast time, but if you choose a Flask it will be nice to me to learn it :)

**Comment by leto** [comment]
Please do some additional research when asking questions. Flask is inspired by Django and if you understand one, you will understand the other. Flask came second and was design by developers, based on the good ideas from Django, which was designed by journalists.
