### ISSUE TITLE
add an option to drop and recreate tables

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#10]
in each page Events, Speakers . . so on, there should be a an option to "Clear all data" which will drop that table and create a new one. 

During the dev phase, when we are changing the schema every now and then, it'll be very helpful :)

**Comment by leto** [comment]
This can be done manually by dropping and recreating the database. Also, since we are using vagrant, things will be created fresh on each new "vagrant up", so this seems unnecessary.
