### ISSUE TITLE
Implement view to create a Super Admin

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1003]

**Comment by mariobehling** [comment]
Where and how do you plan to implement this? There are edit buttons in the user menu: https://open-event.herokuapp.com/admin/users/ Maybe here?

**Comment by aditya1702** [comment]
@mariobehling I am thinking of displaying a button on the header next to the Browse Events..something like"Become a Super Admin". And as for the edit buttons I will implement them so that a super_admin can edit the status of the users to admin.(#1039)

**Comment by aditya1702** [comment]
@mariobehling should I proceed with the above implementation

**Comment by mariobehling** [comment]
@aditya1702 It would be good to have some kind of a mockup or screenshot to understand better, what you want to achieve. Users can not simply "become" super admins. It should be edited in `/admin/users/` in the option section. There is already an edit button. This button could open a simple pop-up for now with tickboxes and information on roles, e.g. see below please.

User Roles
* [ ] Verified User (has access to all user spaces and is granted roles in events according to event policies)
* [ ] Admin (has access to all functions of the system, but cannot change roles of Admins and Super Admins)
* [ ] Super Admin (has access to all functions of the system and admin area)

**Comment by aditya1702** [comment]
@mariobehling I think we can close this. The Super_Admin will be already created when the database is created initially for our app. Thus the only part left is for thesuper_admin to create more admins which I have already implemented here: #1039
