### ISSUE TITLE
Wizard: Only show "Make event live" if it is not live and rename "Update" to "Save"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1007]
"Make event live" shows up in the wizard even though it is already live.

Only show it if event is not live yet.

![screenshot from 2016-06-19 03 04 40](https://cloud.githubusercontent.com/assets/1583873/16174622/d671a02a-35ca-11e6-8bdb-4c9494475f47.png)

**Comment by mariobehling** [comment]
On a second thought: Let's follow the menu in the dashboard. If event is live, show a button "Unpublish" instead of "Make event live".

**Comment by niranjan94** [comment]
@mariobehling alright
