### ISSUE TITLE
Anonymous User: public page where everyone can see the schedule of an event

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#1009]
Parent Issue #782

`/e/ID/schedule` - the public page where everyone can see the schedule of an event.

**Comment by niranjan94** [comment]
@mariobehling this is the UI prototype

![screencapture-localhost-5000-e-1-schedule-1466334747364](https://cloud.githubusercontent.com/assets/2404372/16176983/edecd43c-363c-11e6-8e94-78ece55de4b2.png)

**Comment by mariobehling** [comment]
Very good.
