### ISSUE TITLE
Uploads not covered in migrations and upgrades

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1015]
Seems like after a number of PRs the images do not show up anymore, e.g. in Profile.
![screenshot from 2016-06-19 09 50 11](https://cloud.githubusercontent.com/assets/1583873/16176068/5e156efc-3603-11e6-87a5-ece294bc48bd.png)

**Comment by aviaryan** [comment]
@mariobehling this is a limitation of Heroku. Currently images are saved on heroku. When a new version of app is deployed on Heroku, the whole filesystem is cleared . So image files are also deleted. 
When a heroku app is re-deployed, only data on database remains, everything else is refreshed.

**Comment by mariobehling** [comment]
@aviaryan What would happen if we store files on Amazon S3?

**Comment by aviaryan** [comment]
@mariobehling That would work perfectly well. From our server, we can upload data to Amazon and store the link in our database. I guess this is how it works considering a lot of devs on the Internet seem to prefer amazon storage for their heroku apps.

**Comment by mariobehling** [comment]
@aviaryan Sounds good. It is anyways on our list to store files on S3. So, please open an issue and implement it. Let's do it :-) Please also document the process and setup in the /docs folder.

**Comment by aviaryan** [comment]
@mariobehling  I think this can be closed now
