### ISSUE TITLE
Reduce dependency on outside services to a minimum

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1017]
There are a number of services that we access for no obvious reason. Especially we get placeholder images from other sites. Why?

Please reduce dependency on other services and keep system images in a static image folder.

Please list in the documentation which outside services we still need nevertheless.

**Comment by rafalkowalski** [comment]
# Services which we use
http://ip-api.com/json/
https://maps.googleapis.com/maps/api/geocode/json?latlng=
https://api.sendgrid.com/api/mail.send.json
https://api.heroku.com/apps/open-event/releases
https://api.github.com/repos/fossasia/open-event-orga-server/commits
https://accounts.google.com/o/oauth2/auth
https://graph.facebook.com/oauth

# Have to change:

- [ ] https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css
- [ ] https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
- [ ] https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,400italic
- [ ] https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css
- [ ] https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js
- [ ] http://placehold.it/800x500
- [ ] https://colorlib.com/polygon/gentelella/css/animate.min.css
- [ ] https://placeholdit.imgix.net/~text?txtsize=33&txt=Event+Logo&w=300&h=200
- [ ] https://randomuser.me/api/portraits/men/{{ range(1, 50) | random }}.jpg
- [ ] https://cdn.rawgit.com/leafo/sticky-kit/v1.1.2/jquery.sticky-kit.min.js


## I don't know why do we need this?
https://cdnjs.cloudflare.com
https://maxcdn.bootstrapcdn.com
https://cdn.rawgit.com

**Comment by mariobehling** [comment]
Which services are still part of the deployment? Could you add the info in a Dependencies.md
https://github.com/fossasia/open-event-orga-server/tree/development/docs
or just in the Readme.md? What is best?

**Comment by rafalkowalski** [comment]
@mariobehling i think here https://github.com/fossasia/open-event-orga-server/blob/development/docs/BOWER.md it's enough explained

Currently we only based on Bower dependencies
Or i don't understand your question

**Comment by mariobehling** [comment]
Are we still using the following ones for example? Whose API keys are we using if any? Where is the info?

- http://ip-api.com/json/
- https://maps.googleapis.com/maps/api/geocode/json?latlng=
- https://api.sendgrid.com/api/mail.send.json
- https://api.heroku.com/apps/open-event/releases
- https://api.github.com/repos/fossasia/open-event-orga-server/commits
- https://accounts.google.com/o/oauth2/auth
- https://graph.facebook.com/oauth

**Comment by rafalkowalski** [comment]
ok i will add it to doc

**Comment by rafalkowalski** [comment]
@mariobehling can we close?

**Comment by mariobehling** [comment]
Thank you!
