### ISSUE TITLE
Store data on Amazon S3

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1020]
* Store uploads and other files on Amazon S3.
* When a data is uploaded to server, upload it to S3 and store links in the database. 

Related discussion #1015

**Comment by aviaryan** [comment]
Status update - I have finished the coding part and tested it with profile image upload. It is working but I haven't written the docs so I will send the PR tomorrow as I am busy rest of today.

**Comment by mariobehling** [comment]
Excellent job! Thanks for creating the documentation. Looks awesome. You can use it and publish it as a blog post as well, if you like. Please see #1049 as a follow up issue.

**Comment by aviaryan** [comment]
@mariobehling Thank you.
