### ISSUE TITLE
Two version of App Development and Production 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1024]
We need two apps on heroku 

- One will be for production(master branch) open-event.herokuapp.com
- Second for development(development branch) dev.open-event.herokuapp.com

**Comment by niranjan94** [comment]
@aviaryan @aditya1702 @shivamMg @rafalkowalski @SaptakS @mariobehling @aayusharora @championswimmer @the-dagger @mananwason 

The development branch is now at https://open-event-dev.herokuapp.com.
The master branch is now at https://open-event.herokuapp.com. 

All the existing collaborators now have access to the `open-event-dev` app too.
