### ISSUE TITLE
Connect user profiles to Google and Facebook and get details

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1035]
If a user logs in using add details and profile photo from the accounts to Open Event.

**Comment by aditya1702** [comment]
@mariobehling I updated the title of my PR  to Facebook also. Do we need anything else in this issue or can it be closed?

**Comment by mariobehling** [comment]
This is a good first step, but we need to connect the apps more permanently. At  the moment it looks like people can change their info. You can compare how twitter adds apps in the settings. Let's follow up in milestone 8 and focus on bug hunting more right now.
