### ISSUE TITLE
Files should be added in the specific feature requesting a file

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#104]
If files are added with the feature requesting a file, then I do not see the need for a files tab. Or please explain why we need it.

![screenshot from 2015-08-09 15 00 05](https://cloud.githubusercontent.com/assets/1583873/9154958/7a8395fe-3ea7-11e5-9c92-7c6253d30ecf.png)

**Comment by mariobehling** [comment]
Well, if we have a super admin, he/she could have access to all files. Maybe then yes.

**Comment by leto** [comment]
@mariobehling I am not sure how to move forward with this. What needs to happen?

**Comment by SaptakS** [comment]
I would really like to contribute on solving this issue. Can you please let me know what may be the possible solution. The solution as it appears to me vaguely is to remove the files tab.
