### ISSUE TITLE
Sessions get deleted if the event is edited.

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#1040]
In the current implementation of the event-edit functionality, all the tracks, session_types, microlocations are cleared and recreated again. 

This causes all the linked sessions to be removed as well.

**Comment by shivamMg** [comment]
@niranjan94 The current implementation is supported by dynamic forms. Like for instance you can specify any number of tracks, rooms, session types, etc in the event create/edit form. During edit-event, the server removes the older entities and creates the new ones coming from the forms. The newer entities (when saved to db) are not the same as the old ones, even if the user does not edit them, but they do not lose their link with the event. The new entities created are linked to the same event. Can you give some instructions to reproduce the bug. The sessions don't seem to lose their link.

**Comment by niranjan94** [comment]
1. Import the OTS Sample
1. Publish it
1. Goto /e/<event_id>/sessions - You'll see all the sessions with tracks
1. Now, goto /events/<event_id>/edit 
1. Don't have to change anything. Just press save. 
1. Goto /e/<event_id>/sessions - You'll see all the tracks, no sessions.
1. Goto /events/<event_id>/sessions - You'll see all the sessions, but the track field will be empty

**Comment by niranjan94** [comment]
When the tracks are recreated, their `ID`s change. But the sessions are still having the old non-existant `track_id`s stored in them

**Comment by shivamMg** [comment]
Point 4, `/events/<event_id>/edit` is giving a 500 for that event id. Attribute error for speaker form in events view. Is it working for you?

**Comment by niranjan94** [comment]
What is the event ID ?

**Comment by shivamMg** [comment]
The imported event has twelve.

**Comment by niranjan94** [comment]
Check event 1

**Comment by niranjan94** [comment]
http://open-event.herokuapp.com/e/1/sessions/ 
http://open-event.herokuapp.com/events/1/edit/

**Comment by shivamMg** [comment]
Lol, can't login with my registered id, internal server error. Can't register a new one either, internal server error there too.

**Comment by shivamMg** [comment]
Alright, it's working now, I mean the bug's reproducible. Working on it.
