### ISSUE TITLE
Implement "Use Amazon S3" in Admin Settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1049]
Follow up issue to: https://github.com/fossasia/open-event-orga-server/issues/1020

Please create a tab in the admin section at `/admin/settings/` where admins can choose their upload resource - local or S3 and enter their Amazon S3 Bucket details and reference it in the upload code.

Implement
* [x] Radio buttons to choose "Use local" or "Use Amazon S3"
* [x] Option to enter necessary Amazon S3 credentials

**Comment by aviaryan** [comment]
Since admin is a site-level role, it means that if a admin decides to use local or a specific S3 bucket for storage, it will **affect the entire site**. So why bother providing option in the UI ?
To use S3, they can set the env vars. If they don't want to use S3, they can remove the env vars. 
Am I missing something ?

**Comment by mariobehling** [comment]
Yes, it is the goal to have control for the entire site. Is there any reason it should not be?

The option in the UI will give us the possibility to confirm the status of the system without looking into the code. Admins might not have access to the code and setup in some systems. And what if Admins change? They should be able to get an overview by looking at the settings.

**Comment by aviaryan** [comment]
I agree. Thanks for the explanation.

**Comment by mariobehling** [comment]
Very good! Please add help text below or next to "Local", e.g. something along the lines "If you select Local, files will be stored as follows: images in folder /../.., audio in /../" etc.

**Comment by aviaryan** [comment]
@mariobehling OK. Will do
