### ISSUE TITLE
Please add possibility to get events from locations and filter it by phase

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1052]
#846

location='Berlin'&phase='Python'

TODO
Filtering
- [x] Location
- [x] Phase
- [x] state
- [x] start_time
- [x] end_time
- [x] privacy
- [x] type
- [x] topic

above example should returns all events from Berlin which have Python word in title or description

**Comment by aviaryan** [comment]
Filter by location has been added. See https://github.com/fossasia/open-event-orga-server/pull/964
I will add filter by phrase. 
You can see and play with available options here - http://open-event.herokuapp.com/api/v2/#!/events/get_event_list_paginated

**Comment by rafalkowalski** [comment]
@aviaryan how can i filter only events which are published?

**Comment by aviaryan** [comment]
No, not now but I will add filtering for `state` now that you mention it.

**Comment by rafalkowalski** [comment]
@aviaryan I've added above todo list what i need

**Comment by aviaryan** [comment]
@rafalkowalski Can you please give example of queries you will need from 'start_time' and 'end_time' ?

**Comment by rafalkowalski** [comment]
@aviaryan for example i need to display current published events not past events, so i need to filter it by date

**Comment by aviaryan** [comment]
@rafalkowalski Ok. I will add filter by start_time and end_time . In the meanwhile, can you review #1060, I have added all other options in it. 
Adding start_time and end_time may take some time.
