### ISSUE TITLE
Settings/Mail: Add Settings in Dropdown menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1066]
* [x] Add Settings tab in dropdown menu below "Profile"
* [x] On Settings page implement Email Notifications list as in example below

![screenshot-www meetup com 2016-06-20 16-47-50](https://cloud.githubusercontent.com/assets/1583873/16198864/c79a770a-3707-11e6-8bbd-9c172c70a6a3.png)

**Comment by SaptakS** [comment]
Settings is available for all users, right?

**Comment by mariobehling** [comment]
Yes, there are other admin settings which are unrelated to this issue.

**Comment by SaptakS** [comment]
ok.

**Comment by SaptakS** [comment]
@mariobehling this is the UI:-

![screenshot from 2016-06-24 01 32 49](https://cloud.githubusercontent.com/assets/9530293/16318369/8e114ef8-39ac-11e6-84c9-d85b9fcf12ca.png)

![screenshot from 2016-06-24 01 38 56](https://cloud.githubusercontent.com/assets/9530293/16318368/8e0aa508-39ac-11e6-8831-2e9c30ec15f1.png)

Working on the backend.

**Comment by mariobehling** [comment]
I am not sure, if the options you give are relevant. Did you check on Eventbrite and Meetup what options they give?

Secondly, please keep it simple. A normal page instead of a pop up would do and might reduce the clicks people need to do.

**Comment by SaptakS** [comment]
Ohk. Will check that.

**Comment by SaptakS** [comment]
@mariobehling I will check whether the live system works. It takes some time to build so waiting for that. After that I will proceed with the follow up issue.

Follow up issue #1204
