### ISSUE TITLE
Admin: Implement Mail Tab for info about system mails

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1067]
* [ ] List all system mails in a tab `/admin/mails/`
* [ ] Offer information about where and when mails are sent
* [ ] Show text that is sent as in example below

![screenshot from 2016-06-20 17 01 37](https://cloud.githubusercontent.com/assets/1583873/16199194/f2c3d79a-3708-11e6-84a7-b5c0ecee3de7.png)

**Comment by mariobehling** [comment]
Thank you, I have seen your PR ##1078. It looks good. However, it solves another issue not this one. You implemented: Logs to see what emails have been sent, which is #984.

In this issue: We are looking for an overview, what standard system messages exist in the system and what is the standard text. Please list which messages exist.

**Comment by aviaryan** [comment]
Oh. Sorry I got confused. 
So I will add the list of standard system messages to `admin/mails` and move the log of mails in a tab under `admin/logs`. Upon completion of #984, `admin/logs` will have 2 tabs , Mail and Activity. 
Mail will be for log of mails sent, Activity for general site activity mentioned in #984 comments. 
Does that sound right ? @mariobehling

**Comment by mariobehling** [comment]
Yes, sounds good. Thank you.
