### ISSUE TITLE
Improve top bar for small/mobile screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1081]
Currently the top bar looks like that in small resolutions:

--
![screenshot from 2016-06-21 10 48 35](https://cloud.githubusercontent.com/assets/1583873/16223520/f9add372-379d-11e6-8f49-a38ac7ed8f80.png)
--
Compare to:
![screenshot from 2016-06-21 10 49 53](https://cloud.githubusercontent.com/assets/1583873/16223524/01bd53c6-379e-11e6-91fb-f8e8d565496a.png)

Please implement a top bar, that works for small resolutions.

**Comment by SaptakS** [comment]
**Device Size: 320 X 480**
![top320](https://cloud.githubusercontent.com/assets/9530293/16256740/bcfd46fe-3871-11e6-9be3-06a94cd7ceb0.png)


**Device Size: 768 X 1024**
![top768](https://cloud.githubusercontent.com/assets/9530293/16256744/c36ef276-3871-11e6-8412-1b04d9aa4fe5.png)

**Comment by mariobehling** [comment]
Please compare other popular sites. Top bar should always stay in one line. In the smallest resolution you could take out "browse events" and move "create events" into the dropdown for example.

**Comment by SaptakS** [comment]
Ok.. Will do that..

**Comment by SaptakS** [comment]
![screenshot from 2016-06-22 14 45 42](https://cloud.githubusercontent.com/assets/9530293/16261351/d66acae6-3888-11e6-87a5-e8fdad5ece97.png)

Done.

**Comment by mariobehling** [comment]
In the current version of the live system it does not show up for me. In any case it should only show up in a small screen.

**Comment by SaptakS** [comment]
@mariobehling it gets shown at a device with width less than 640px. So if you want to see this, you need to resize below that.

![screenshot from 2016-06-22 20 00 15](https://cloud.githubusercontent.com/assets/9530293/16270540/4b428978-38b4-11e6-9b6d-2c70575a07a4.png)
![screenshot from 2016-06-22 20 02 23](https://cloud.githubusercontent.com/assets/9530293/16270541/4baccbbc-38b4-11e6-9279-c84a2a93edfa.png)
