### ISSUE TITLE
Simplify View Sessions from Event Dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1090]
We have diverse designs in different views. It starts to be too complex and increases the potential list of issues. Let's keep it simple for now therefore.

Instead of the current "View Session" page (e.g. http://open-event.herokuapp.com/events/3/sessions/165/), please change this design and just show a page in the "Create Session" design - that is not editable.

![screenshot-open-event herokuapp com 2016-06-21 13-22-38](https://cloud.githubusercontent.com/assets/1583873/16227889/c5fdb874-37b3-11e6-8a22-6edf3bdaf633.png)

Implement:
* [x] Design as in Create Session
* [x] All areas as in Create Sessions
* [ ] Edit Button on the Bottom to edit
* [x] Accept/Reject Buttons

**Comment by mariobehling** [comment]
Please include all speaker form areas here. Another nice option would be: "Choose from existing speakers" (here we should only show speakers that are registered in the specific event).

**Comment by mariobehling** [comment]
Sorry actually in this issue, we are only talking about view not edit or submit new sessions. The "choose from existing speakers" should only be implemented in the create/edit form, not here.

**Comment by niranjan94** [comment]
> Please include all speaker form areas here

@mariobehling a single event would have multiple speakers. So, should all the speakers be displayed ?

**Comment by mariobehling** [comment]
Yes, good idea. How do we display that in the form?

**Comment by niranjan94** [comment]
@mariobehling I have added option to choose from existing speaker here 
https://github.com/fossasia/open-event-orga-server/pull/1100
