### ISSUE TITLE
Create database fields and models for Ticketing System

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1095]
https://github.com/fossasia/open-event-orga-server/issues/904

Ticket

- `name`: Unique ticket name for the event.
- `description`: Optional description about the ticket.
- `quantity`: How many tickets are made available by the Organizer.
- `price`: Fixed price for this ticket (Zero for free ticket)
- `event`: Event the Ticket is associated with.
- `sales_start`: When should the ticket sale start.
- `sales_end`: When should the ticket sale end.
- `min_order`: Minimum number of tickets that are allowed for one order.
- `max_order`: Maximum number of tickets that are allowed for one order.

BookedTicket

- `ticket`: Ticket (ticket_id).
- `user`: User who booked the tickets.
- `quantity`: The number of tickets the user booked.

Edit: Add sales start and end time. Also add minimum and maximum tickets allowed per order.

* [x] Sales start & end time.
* [x] Max and Min tickets allowed per order.

Edit: 

* [x] Add type ("free", "paid", "donation")
* [x] Add currency option.

**Comment by mariobehling** [comment]
Did you check options in Eventbrite and Eventnook? Please list all options for tickets e.g. I do not see sales dates. What other options are there?

**Comment by mariobehling** [comment]
Please post a screenshot here for me from Eventbrite including all options to give everyone an idea to start with.

**Comment by shivamMg** [comment]
@mariobehling I'm implementing it like Eventbrite does. 

![](https://i.imgur.com/o9QweRa.png)

I haven't created Sales start & end fields, and tickets allowed per person. I thought of keeping it simple at first. Will submit a PR adding the same.

In regard to the type of tickets, Eventbrite splits it in three:

![](https://i.imgur.com/Gu9DSIQ.png)

Free and Priced tickets can be implemented by the above defined model (free ticket will have a price zero). Donations don't have a fixed price, so if we want to provide the user with such option, we will need an extra field (ticket type).

Apart from these, Eventbrite also gives an option to specify what currency the user will pay in (I'm little doubtful if we need it. We are going to put out support for Paypal and Stripe https://github.com/fossasia/open-event-orga-server/issues/719).

I've updated the above fields describing what each one means specifically. BookedTicket is ticket(s) bought by a user.

**Comment by mariobehling** [comment]
Yes, sounds good. We also need the currency option as the system could be deployed in different regions.

**Comment by mariobehling** [comment]
Thank you. Looks good.

> what currency the user will pay in

Yes, we need it.

We also need to let the user choose "Add Ticket URL or Use Ticketing System" as outlined in #1841

**Comment by mariobehling** [comment]
Currently the UI and feature set is still very far away to what we need, but the issue is on our list for some time now. Please follow the example of existing services closer and implement the missing features. What are the next steps?

**Comment by shivamMg** [comment]
All the missing features were added here: https://github.com/fossasia/open-event-orga-server/issues/2082
