### ISSUE TITLE
Possibility to sort data by parameter

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#11]

**Comment by leto** [comment]
flask-admin provides this natively

**Comment by leto** [comment]
You may need to define the columns you want with ```column_filter``` or similar

**Comment by leto** [comment]
@rafalkowalski let me know if you have more specific questions, i.e. specific lines of code that you wrote that are not working as you think

**Comment by rafalkowalski** [comment]
@mananwason I added filtering and sorting by parameter in URL
For example:
You can order by everyone column
http://127.0.0.1:5000/get/api/v1/events?order_by=end_time
http://127.0.0.1:5000/get/api/v1/events?order_by=name

You can order and filter 
http://127.0.0.1:5000/get/api/v1/events?order_by=end_time&id=1
http://127.0.0.1:5000/get/api/v1/events?name=aa&id=4

**Comment by rafalkowalski** [comment]
@leto  do you think is it enough?

**Comment by leto** [comment]
Yes
