### ISSUE TITLE
Modify tabs for mobile UI

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1106]
Make Tabs responsive in
- [x] `/events/`
- [x] `/events/ID/`

![session_mobile](https://cloud.githubusercontent.com/assets/9530293/16177270/affe1e58-3644-11e6-8f6d-5922a2f17ac2.png)

Presently, the tabs appear like this in Mobile.

**Comment by SaptakS** [comment]
Tabs made into accordions:

![buttons_responsive](https://cloud.githubusercontent.com/assets/9530293/16243415/c2990966-3814-11e6-8b25-feb8ab06b8cf.png)

**Comment by mariobehling** [comment]
It is a good improvement. We need to think how to keep the colors.

**Comment by SaptakS** [comment]
@mariobehling the colors are already there in the website.. It got edited while editing the screen capture.
