### ISSUE TITLE
Work to be done in the redata format server

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#111]
- [ ] Populate the sessions json http://springboard.championswimmer.in/api/v1/event/1/sponsors
- [ ] Fix the null values and enter data instead of it.
- [ ] Pointing out differences between existing server and re:data and make changes to ammend this

**Comment by mananwason** [comment]
@championswimmer @rafalkowalski Please contribute to complete this list.

**Comment by championswimmer** [comment]
I was already noting down the required API changes here

https://github.com/fossasia/open-event/issues/31

**Comment by rafalkowalski** [comment]
@mananwason on the re:data is empty http://data.re-publica.de/api/rp15/sponsors, So you can add some manually

**Comment by mananwason** [comment]
@championswimmer I'll close this then. @rafalkowalski Can't you add the existing jsons from some other event?

**Comment by rafalkowalski** [comment]
for  different events this data doesn't exist @mananwason

**Comment by mananwason** [comment]
@rafalkowalski okay.
