### ISSUE TITLE
Add Ticketing System to event creation form

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1112]
https://github.com/fossasia/open-event-orga-server/issues/904

Please follow examples of other services. Example as below.

![screenshot from 2016-07-23 19 14 22](https://cloud.githubusercontent.com/assets/1583873/17079228/de8e93bc-5109-11e6-9e26-231ec2e7ed67.png)

And..

![screenshot-www eventbrite com 2016-07-23 19-14-49](https://cloud.githubusercontent.com/assets/1583873/17079229/e34bd1bc-5109-11e6-8690-3eba65ecafda.png)

**Comment by mariobehling** [comment]
This comes later, please outline fields and details first before implementing anything. The current wizard is buggy and we should not add complexity unless we are 100% clear what we are doing. Please add this to the create event form later therefore.

**Comment by shivamMg** [comment]
:+1: We should improve existing features first. Please take look at my comment here: https://github.com/fossasia/open-event-orga-server/issues/1095#issuecomment-227800415

**Comment by shivamMg** [comment]
Missing features: https://github.com/fossasia/open-event-orga-server/issues/2082
