### ISSUE TITLE
Convert API datetime format to iso8601

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1116]
https://en.wikipedia.org/wiki/ISO_8601

Example - 2016-06-06T11:22:33+0800

To incorporate timezone in the datetime value, it should be converted to a more rich format like ISO8601.
There is a nice library for it. http://pyiso8601.readthedocs.io/en/latest/

**Comment by mariobehling** [comment]
Sounds good.

**Comment by aviaryan** [comment]
Postgres doesn't store timezone aware datetime's with the timezone but [converts them to UTC](http://www.postgresql.org/docs/8.3/interactive/datatype-datetime.html#DATATYPE-TIMEZONES) and then stores it. That being said, only option we have is to store timezone as a separate field. Now when timezone is being stored as a separate field, it is better to return local time in the API and it can be combined with timezone to return the full time. This is being done in #1091 

Btw, iso8601 uses T as a separator between date and time so it makes the dates *URL friendly* (useful for filtering in GET APIs). I will implement that in this issue. I will also keep the API **backwards compatible** to support space-separated date and time. So new format of datetime will be - 2016-06-06T11:22:33
