### ISSUE TITLE
Make widgets responsive

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1117]
![event_overview_before](https://cloud.githubusercontent.com/assets/9530293/16257418/251b5812-3876-11e6-8598-f19a71134643.png)

**Comment by mariobehling** [comment]
Please improve on scroll bars and move all tabs up. Also change colors of active tab just like in desktop version.

**Comment by SaptakS** [comment]
Moving all tabs up doesn't make sense in case of accordion. Also, unlike desktop, fitting all tabs on the top in mobile UI will make the tabs very small and difficult to click. 

I will change the color of active tab though.
