### ISSUE TITLE
Implement pagination in the API 

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#112]
Something like this  https://github.com/opendatacity/re-data/blob/master/doc/api.md#pagination

**Comment by rafalkowalski** [comment]
@championswimmer @mananwason I added pagination http://springboard.championswimmer.in/api/v1/event/1/sessions
If you want display second page you have to add additional parameter "page"
http://springboard.championswimmer.in/api/v1/event/1/sessions/page/2
Per page i displays 50 objects

**Comment by championswimmer** [comment]
Hey could you make it 20 instead of 50. Even 50 can be slow on the webapp :P 

Also, how do I know which page is the last ? 
Can you put 'count' in the response like in re:Data api ?

**Comment by rafalkowalski** [comment]
@championswimmer I will change it to 20. 

Maybe additional column page will be enought(pages)?

**Comment by championswimmer** [comment]
Yes that will be best :)
Some thing like
{
count: xxx
page: 2
total_pages: 10
sessions [ ... ]
}

That possible ?

**Comment by mananwason** [comment]
@championswimmer Why do we need these fields?

**Comment by championswimmer** [comment]
To know when to stop requesting more pages.

**Comment by mananwason** [comment]
Can't you just keep a counter for this? and in which api is this going to be included in?

**Comment by rafalkowalski** [comment]
@championswimmer @mananwason i added it
