### ISSUE TITLE
Dashboard: Show a widget sponsors in the specific event dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1136]
Follow up to https://github.com/fossasia/open-event-orga-server/issues/1131

* [x] delete sponsorship tab in dashboard UI
* [x] Show a widget sponsors at /events/ID`
* [x] Portray the most important details
* [x] Show an "Edit Sponsors" Button, that directs to "Wizard step 2"

**Comment by aditya1702** [comment]
@mariobehling Do u want like this:
![widget2](https://cloud.githubusercontent.com/assets/15054664/16275747/0d619c4c-38c9-11e6-8167-565190211b79.png)

**Comment by mariobehling** [comment]
Yes, looks good. Thank you.

**Comment by mariobehling** [comment]
Add button of sponsorship widget, let's people "add role". Please test more yourself before PRs.

**Comment by aditya1702** [comment]
@mariobehling Yes. Do you want that button to redirect to the step 2 or do you want a modal to open?

**Comment by mariobehling** [comment]
Redirect to wizard. Let's keep complexity down for the moment.

**Comment by mariobehling** [comment]
Great. Thank you!
