### ISSUE TITLE
improve pagination implementation

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#114]
Basically, if we GET `/sessions` we should get all the data

if we GET `/sessions?page=n` we get nth page. 1,2,3,4 so on. 

/sessions/page/2 isn't correct REST path 
@creativepsyco @leto  please correct me if I am wrong here,

**Comment by rafalkowalski** [comment]
Do we need display whole data?

**Comment by mananwason** [comment]
Yes @rafalkowalski The android app doesn't require the pagination, so to download the whole data at once, we need to display the whole data as well.

**Comment by rafalkowalski** [comment]
ok @mananwason  Thanks I will add it :)

**Comment by championswimmer** [comment]
Yeah basically its best if pagination is optional. Only make pages if page
parameter is given in URL.

I think you can get the URL arguments using request.args.get('page')

**Comment by mananwason** [comment]
Cool @rafalkowalski :+1:
