### ISSUE TITLE
Possible notifications area for User

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1143]
A user has to be sent many updates. Like invites to be a event roles (https://github.com/fossasia/open-event-orga-server/issues/873), invites to be a speaker. Apart from these there could be other notifications like messages from admin, information about upcoming events that the user might have bookmarked, etc.

We can create a db user notification model with `user`, `message` and `datetime` as bare required fields. To give user a notification, we can add a message in the model, and when the user loads his dashboard notifications can be fetched in chronological order.

Edit: Do the following:

* [x] Create database model according to the below schema.
* [x] Create helper functions to push notifications.
* [x] Add views (include mark-as-unread feature)
* [x] Implement it in other features (https://github.com/fossasia/open-event-orga-server/issues/873)

Edit:

* [x] Add notif icon to navbar (displaying unread notification count)

Edit:

* [ ] Ensure that the message texts show up at `/admin/mails/`

**Comment by shivamMg** [comment]
Possible columns for the notification table:

- `user`: The user the notification is for.
- `message`: Message string.
- `datetime`: The datetime the message was received by the user.
- `has_read` (bool): If the user had read the message.

**Comment by mariobehling** [comment]
Very good. Please also ensure, that the message texts show up at `/admin/mails/`

**Comment by shivamMg** [comment]
@mariobehling You mean `/admin/logs/` right? `/admin/mails/` contains message structures for different types of mails. Also, should I create another tab at `/admin/logs/`, since notifications are different from Activity and Mails.

**Comment by mariobehling** [comment]
@shivamMg Well, they are different, but we actually want to get an overview of all notifications, mails and whatever. Should we rename `admin/mails` to `admin/messages` and create subtabs `mails` and `notifications`? Please open an issue for that.

And yes, please also ensure, that all show up at `admin/logs`. Cheers.

**Comment by shivamMg** [comment]
Sub-issues were shifted here: 

https://github.com/fossasia/open-event-orga-server/issues/1328
https://github.com/fossasia/open-event-orga-server/issues/1330
