### ISSUE TITLE
Wizard issues and alternatives: Color, Loading, back and forward clicking, height changes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1157]
There are a number of open questions with the current implementation of the wizard.
* When user loads the wizard, the 1-2-3 line shows in gray for a moment
* When a certain step of the wizard is loaded the line shows the first step and the line in gray for a moment
* Clicking back and forward (a common thing that users do) does not always work with the wizard
* The height of pages changes when users click back and forward

How can we improve on such issues? Should we implement the wizard rather as a line of pages as Eventnook does it? What are ways to cover these issues? It is not expected behaviour.

**Comment by niranjan94** [comment]
All of these issues pertain to the [jQuery-Smart-Wizard](https://github.com/mstratman/jQuery-Smart-Wizard) plugin that we're using. 

> How can we improve on such issues? Should we implement the wizard rather as a line of pages as Eventnook does it? What are ways to cover these issues? It is not expected behaviour.

That's a good idea. We can remove jQuery-Smart-Wizard altogether, setup each stage as a separate path, and use pushstate and ajax to create the wizard experience. That would solve all the issues and at the same time, it'll work as a wizard and not as individual pages.

**Comment by mariobehling** [comment]
Ok, sounds great. Please create an issue, reference this issue and proceed. Closing this.
