### ISSUE TITLE
Admin Settings: Implement Option to add Keys/Access Data for Dependent services

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1159]
Currently we have services hardcoded e.g. Google Maps Api.

* [x] Please list all dependent services in `/admin/settings/`
* [x] Add the option to enter the access data/API keys here instead of hardcoding it
* [ ] Implement that all services refer to the keys entered here

See a related issue about Amazon S3 here https://github.com/fossasia/open-event-orga-server/issues/1049

**Comment by rafalkowalski** [comment]
@mariobehling can we close it?
