### ISSUE TITLE
"title" field missing in sessions array in API /speakers

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#116]
```
    "sessions": [
        {
            "id": "rp13-session-5117",
            "title": "Comic Misunderstanding – A conversation with Graham Linehan (IT Crowd)"
        },
        {
            "id": "rp13-session-5866",
            "title": "YouTube macht die Stars von heute"
        } //...
```

**Comment by championswimmer** [comment]
as available on this http://springboard.championswimmer.in/api/v1/event/1/speakers/page/1

**Comment by leto** [comment]
@championswimmer the above URL no longer works

**Comment by rafalkowalski** [comment]
@leto Please check http://openevent.championswimmer.in/api/v1/event/1/speakers/page/1 But I don't understand this issue.

**Comment by leto** [comment]
@championswimmer I am with @rafalkowalski now, can you more clearly explain what you expect to see? Thanks

**Comment by championswimmer** [comment]
Within speakers, each speaker should have a sessions array, with each
session object having a "title" column

**Comment by leto** [comment]
@championswimmer I see that some elements have ``` "sessions": [ ]``` while others list session ID's such as ```"sessions": [
        35, 
        255
      ], ```. Do we really want to fully populate session with the actually data? I don't have a strong opinion at this point.

**Comment by leto** [comment]
@creativepsyco do you have an opinion about fully populating ```sessions``` vs only giving ID's ?

**Comment by championswimmer** [comment]
just titles and ids, not the whole  session object

doing this processing on client side (loading sessions based on id,) will
mean more queries and over bandwidth.

on contrary if we send the data from the server itself it will be more
economic

**Comment by leto** [comment]
@championswimmer can you give an example of exactly how you would want the data structure such that it is very easy to parse on your side?

**Comment by championswimmer** [comment]
In the very first comment, it is in the code block given

**Comment by creativepsyco** [comment]
Returning titles and ids is completely fine however, I am assuming that in future you will probably also require other stuff like cover image, links etc which you may want to be rendered. From a display POV it makes sense but not so much from a logical standpoint. There will be data duplication and that is not desired. Further, `sessionStorage` should allow for retrieval of sessions by ids, then you can probably fetch the session details from the session storage using the id. Hence I think for the speaker API json schema we should return array of sessions ids, and that should be enough :)

**Comment by leto** [comment]
Well, I implemented it anyway (see the ```speaker_session_titles branch```) because I hadn't seen @creativepsyco's comment, which I agree with. I think it makes the job of the API consumer a bit easier and it could noticeably cut down on API request  for speakers with many sessions. That could be important when we are hosting multiple events on our production server. I do feel strongly that we should not be adding any more session data to this result, other that title and id. @championswimmer can you test out the branch and merge it if it works well for you?

**Comment by creativepsyco** [comment]
:+1: LGTM

**Comment by leto** [comment]
Closing
