### ISSUE TITLE
"track" field is null in the API JSON response data for all sessions.

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#117]
As available in http://openevent.championswimmer.in/api/v1/event/1/sessions/page/2 , the track field is null for all the sessions.

"subtitle": null, 
      "title": "Fremd gehen immer nur die anderen \u2013 Liebe und Beziehung in Zeiten der Digitalit\u00e4t", 
      "track": null

**Comment by rafalkowalski** [comment]
@SaptakS I fixed it please check

**Comment by leto** [comment]
I verified that non-null ```track``` exists at the above mentioned URL, closing.

**Comment by SaptakS** [comment]
ok..
