### ISSUE TITLE
Updating profile removes photo

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1170]
Updating profile without changing the photo removes the already existing photo.

**Comment by aditya1702** [comment]
@aviaryan Could u tell how to produce this.

**Comment by aviaryan** [comment]
1. First upload a photo for your profile. Save it.
2. Then update profile without touching the photo. Save it.
3. The photo is gone.

**Comment by shivamMg** [comment]
It's happening because `user.avatar` isn't saving anything (why do we have both user.avatar and user_detail.avatar :confused: ) This should fix it. https://github.com/fossasia/open-event-orga-server/issues/1172

**Comment by aviaryan** [comment]
Fixed
