### ISSUE TITLE
Create a list of notification emails to subscribe to

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1179]
We can get some ideas by looking at Eventbrite and Meetup, but those services do not offer the whole organizer services that we offer. Please make a list of potential email updates people could get about the event.

This is relevant for the issue, that implements notifications: https://github.com/fossasia/open-event-orga-server/issues/1066#

**Comment by SaptakS** [comment]
After seeing Eventbrite and Meetup, I think these can be the list of notifications:
- [ ] Reminder for next event
- [ ] Session acceptance/rejection
- [ ] Change in session schedule
- [ ] New paper submitted
- [ ] iCal Attachments

@rafalkowalski @mariobehling @niranjan94 @aditya1702 please suggest more if needed

**Comment by mariobehling** [comment]
@SaptakS Yes, sound good.

But, iCal attachments is a bigger thing. So, take it out for now.

Please make two categories for each event. Email notifications if you are a
* Organizer and Team
* Speakers

**Comment by SaptakS** [comment]
Ok. Working on it.

**Comment by SaptakS** [comment]
* **Organizer and Team**
- [ ] Reminder for next event
- [ ] Change in session schedule
- [ ] New paper submitted

* **Speaker**
- [ ] Session acceptance/rejection
- [ ] Change in session schedule

This list is good?

**Comment by SaptakS** [comment]
![screenshot from 2016-06-24 20 47 38](https://cloud.githubusercontent.com/assets/9530293/16342176/5b832ad6-3a4e-11e6-8cf8-217fe7cbf171.png)
 #1203

@mariobehling review.

**Comment by mariobehling** [comment]
Very good.

**Comment by SaptakS** [comment]
@mariobehling thanks. :)

**Comment by mariobehling** [comment]
We need to test it in detail on the live system, did you? When it is all working, close it. Can you confirm that organizers did receive emails and when a new paper is submitted? Does it work?

**Comment by SaptakS** [comment]
@mariobehling it is only storing the settings in DB for now. Will add the feature for sending email based on the setting.

Follow up issue: https://github.com/fossasia/open-event-orga-server/issues/1236

**Comment by mariobehling** [comment]
Ok, got it. Please implement emails in the admin settings https://github.com/fossasia/open-event-orga-server/issues/1245

**Comment by SaptakS** [comment]
Closing this issue. The remaining issues related to this are being solved in #1236
