### ISSUE TITLE
Create FOSSASIA'16 JSON set to import as an Event

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1187]
https://github.com/fossasia/open-event-scraper

Add JSON set for:

* [x] Event
* [x] Microlocations
* [x] Sessions
* [x] <del>Session Types</del> https://github.com/fossasia/open-event-orga-server/issues/1327
* [x] <del>Social Links</del> https://github.com/fossasia/open-event-orga-server/issues/1327
* [x] Speakers (fill "sessions" field according to the data in Sessions)
* [x] Sponsors
* [x] Tracks (fill "sessions" field according to the data in Sessions)

**Comment by mariobehling** [comment]
The files are in this folder now: https://github.com/fossasia/open-event/tree/master/sample

Please ensure they are in the last version and link to the files in the folder, provide version and meta data.

**Comment by aviaryan** [comment]
FOSSASIA have been added to samples folder and are updated to the latest version.
