### ISSUE TITLE
Implement backend for Admin settings

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1189]
Parent issue: #1159 and #1049 

Create a db table 'Setting' to store api keys, secret keys and other settings. All the [dependencies](https://github.com/fossasia/open-event-orga-server/blob/development/docs/DEPENDENCIES.md) can go inside it. 

1. Google Tokens (client_id, client_secret)
2. Facebook Tokens (client_id, client_secret)
3. Amazon S3 Token and setting (bucket_name, key, secret)
4. Sendgrid Token (token)
5. Flask app secret key (secret_string)

** Google maps and heroku releases API doesn't seem to require token.
** Please add something if it is missing.

**Comment by mariobehling** [comment]
Google Maps also requires some form of authentication and heroku has some data too. If they do not require a key, they require something else. Please use the settings page as a place to keep all the information of dependent services. Also list services that do not need authorization and add links to them in the help text, please.

**Comment by aviaryan** [comment]
@mariobehling If you see #1194, only one row is required in the settings table to store the system settings. We can make it so such that each change in the system setting is stored in a different row. (The newest row is the current system setting). This will be like a version control for system settings. What do you think ?

**Comment by mariobehling** [comment]
Yes, possible or would this be kept in a logs table? Please think this through in the UI as well. Where do you want to show these old entries? Probably the logs is the best place, e.g. "Changed Facebook Token change from ... to ...". Or do you have better idea?

**Comment by aviaryan** [comment]
@mariobehling 
We can show the settings history separately, maybe in the settings view itself in the right of settings form. 
The history list will have who modified the settings and when they were modified. Clicking on a history item can open a popup (modal) with the state of system settings at that point. The settings will be displayed as json. From that point, we can add fancy feature like export, set as current setting and so ..
Btw, now I feel this is better suited as a later milestone since it has no important use. What do you think ?

**Comment by mariobehling** [comment]
@aviaryan I think this is not so high priority. It settings changes show up in the logs. It is sufficient. There is not much added value in having a cool settings history. We need cool widgets in the event dashboards. So, please focus on finalizing this and let's proceed elsewhere.
