### ISSUE TITLE
Dashboard: Add info on API endpoints for event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1191]
We have the web app and Android app that can generate apps from the JSON files and should be able to do it through the API. We also want the volunteer system to get the data through the APIs.

Please 
* [x] provide API endpoints and 
* [ ] all required info on the specific event dashboard of events at `/events/ID/`
* [x] Name the tab "API" (not API Endpoints)

**Comment by shivamMg** [comment]
@mariobehling Can you give some more description on this.

**Comment by mariobehling** [comment]
Example: I am a developer and have an app to get my event data through an API. How can I get it instead of using export? What data do I need? What is the link?

**Comment by shivamMg** [comment]
@mariobehling 

> We also want the volunteer system to get the data through the APIs.

What exactly is a volunteer system? And what kind of APIs would it need?

**Comment by SaptakS** [comment]
@mariobehling I am taking this up.

**Comment by championswimmer** [comment]
I think this is already being possible. Something like this 
https://open-event.herokuapp.com/api/v2/events/4
https://open-event.herokuapp.com/api/v2/events/4/speakers
https://open-event.herokuapp.com/api/v2/events/4/microlocations
etc

I am already implementing that in the webapp generator https://github.com/fossasia/open-event-webapp/pull/409

**Comment by SaptakS** [comment]
That is what I was also saying. This should already be possible using `/api/v2` . @aayusharora and @the-dagger also agree I think.

**Comment by championswimmer** [comment]
@SaptakS @rafalkowalski 
One request

can we get `/api/v2/events/{id}/event` endpoint too ? 
that should work exactly the same as `/api/v2/events/{id}` only

**Comment by SaptakS** [comment]
@championswimmer What should this endpoint provide data about?

**Comment by championswimmer** [comment]
Same as events/id

events/2 == events/2/event

That is possible?

**Comment by shivamMg** [comment]
@championswimmer Yes it can be done. But why is it needed?

**Comment by SaptakS** [comment]
@championswimmer @mariobehling can this issue be closed?

**Comment by mariobehling** [comment]
@SaptakS Originally this was intended as a widget not a tab. Anyways I have adapted the description of the issue. Please check that all points are done and mark them as done. Then close the issue.

**Comment by SaptakS** [comment]
@mariobehling sorry for the misunderstanding. I think the second point will be covered according to the discussion in #1733 . This tab however does provide all the info related to an event but not in bulk as was discussed in #1678 . So should I mark it done for the time?

**Comment by mariobehling** [comment]
Ok, thanks. At the moment the tab is still named "API Endpoints". Please rename "API".
