### ISSUE TITLE
Display all Speakers at Manage event tables

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1206]
Display all speakers instead of number of speakers.

![screenshot from 2016-06-24 23 58 15](https://cloud.githubusercontent.com/assets/7882752/16346970/c1ceb99a-3a67-11e6-847b-7087d17d7118.png)

**Comment by niranjan94** [comment]
This is correct. As @mariobehling said in #970. No. of speakers has to be shown on the table. Not the list of speakers. 

A table should have only concise information.

**Comment by shivamMg** [comment]
Oh. OK.

**Comment by shivamMg** [comment]
Or how about listing just 4 speakers and then displaying the remaining count (a link to /events/id/speakers/).

![screenshot from 2016-06-25 00 50 18](https://cloud.githubusercontent.com/assets/7882752/16348212/d09440e2-3a6e-11e6-8cdd-da67135e4a54.png)

@niranjan94 @mariobehling What do you think?

**Comment by mariobehling** [comment]
Let's not waste time with this at the moment. Please help to test and fix issues. Did you test as an event organizer and fill out everything and then test as a speaker etc. Does everything work for you? It does not for me. Would be great, if you find bugs too.

Closing this. It is not necessary.

We have lots of issues. Please help to solve the issues we have already and halt to add more features. There is lots of stuff that is incomplete.
