### ISSUE TITLE
Internal server error on creating sponsors for an event

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1208]
Also the events page `/events/id` does not load after adding a sponsor.

**Comment by aditya1702** [comment]
@shivamMg Its working fine. How are u getting this error?

**Comment by shivamMg** [comment]
@aditya1702 You can check this on demo app.

1. Create an event
2. Goto `/events/:ID/edit/sponsors` and create a sponsor. You'll get a server error here first.
3. After that goto `/events/:ID`, you'll get a server error here too.

**Comment by aviaryan** [comment]
Fixed by #1215
