### ISSUE TITLE
Create views for Sponsor widget

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1209]
Like the Manage-Roles widget, the sponsor widget needs views to create, update and delete sponsors.

The 500 error here: https://github.com/fossasia/open-event-orga-server/issues/1208 is because there is a link to `event_sponsor.delete_view` but it has not been defined.

**Comment by aditya1702** [comment]
@shivamMg The view for delete is there in sponsors.py

**Comment by shivamMg** [comment]
@aditya1702 But there is no view named sponsors.py

**Comment by shivamMg** [comment]
OK. They were deleted in this commit: https://github.com/fossasia/open-event-orga-server/commit/b38e3bc54ce04c4f23b96e5ed6d0e30e976b29f6

But the sponsor views are needed for the sponsor widget. I'll put them back. @aditya1702 What do you think?

**Comment by aditya1702** [comment]
@shivamMg Yes! they are needed. I wrote the above comment because I had myself written the code for the delete_view in the sponsors widget. It was removed by Niranjan so he is fixing it right now.

**Comment by aditya1702** [comment]
This is fixed. Closing this
