### ISSUE TITLE
Import/Export: Import Images specified in JSON files as links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1216]
Related to Export:  #1216

Currently we do not import images of the logo, speakers, audio etc. There are specified in the JSON files that we import. 

* [x] Please implement the import of images and audio into the system as well. 
* [x] Keep a log of each import and ensure the logs show up in /admin/logs

**Comment by aviaryan** [comment]
Fixed in #1594 .
