### ISSUE TITLE
Schedule: Cannot see sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1218]
Schedule pages have errors, e.g. http://open-event.herokuapp.com/e/9/schedule/

![screenshot from 2016-06-25 12 41 30](https://cloud.githubusercontent.com/assets/1583873/16356261/3f62f60e-3ad2-11e6-81f7-0e06c5332cb0.png)

**Comment by niranjan94** [comment]
I have also manually fixed this event data. You can check http://open-event.herokuapp.com/e/9/schedule/ again.
