### ISSUE TITLE
500 error when logging in as super admin

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1219]
I get the following error when I try to log in as a super_admin:
![error](https://cloud.githubusercontent.com/assets/15054664/16357909/ca7b85a4-3b21-11e6-8103-8016acab7034.png)

**Comment by shivamMg** [comment]
@aditya1702 Can you provide steps to reproduce this.

**Comment by shivamMg** [comment]
@aditya1702 Shall I close this.
