### ISSUE TITLE
Register user only after verifying email

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1221]
Once a user registers himself during sign up, he/she should verify the email by clicking on the link sent to his/her email. I had earlier added this to the code but right now its not there.
![confirm](https://cloud.githubusercontent.com/assets/15054664/16357223/b027f3ea-3b0d-11e6-936c-1f9074f01512.png)

**Comment by mariobehling** [comment]
What is this issue about? I do not understand, why there is never a description in your issues.

**Comment by mariobehling** [comment]
There was an issue regarding this here https://github.com/fossasia/open-event-orga-server/issues/639

Please provide information, screenshots, baseURLs or whatever helps us to understand the issues you file!

**Comment by niranjan94** [comment]
@aditya1702 this is intended. We want to allow the user to use Open Event without verifying his/her email ID (some functionality is restricted). But, he/she will not be able to publish an event without verifying. (See https://github.com/fossasia/open-event-orga-server/issues/921)
