### ISSUE TITLE
Cannot Import Event

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1228]
![import_error](https://cloud.githubusercontent.com/assets/15054664/16357989/ef1781f4-3b23-11e6-8a19-52a3898acd65.png)
Description field is required to be filled for event to be imported

**Comment by aviaryan** [comment]
My guess is that it is the track description field that is giving that error here. Earlier description in track was set to not nullable so I made required=True for that field. I will fix it.

**Comment by aviaryan** [comment]
This should be fixed. Can you check ?

**Comment by aditya1702** [comment]
@aviaryan One more thing had to be fixed. I created a pull #1231

**Comment by aditya1702** [comment]
Working! :+1:
