### ISSUE TITLE
Offer organizer to send CFS Announcement Email

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1237]
Parent Issue #325

**Comment by mariobehling** [comment]
This should be usually by using external mail services, e.g. mailchimp or sendly. Let's start with our own mail implementation, that should be set up on the settings page, e g. http://open-event.herokuapp.com/admin/settings/

Issue for this is https://github.com/fossasia/open-event-orga-server/issues/1245

**Comment by mariobehling** [comment]
We might come back to that later. For now we just tell them to use other services.
