### ISSUE TITLE
Offer organizer to send out tweet for CFS

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1238]
Parent issue #325

**Comment by mariobehling** [comment]
Actually I think this is not a priority to make the system running and we can add this feature later. Let's focus on making the system run and postpone this. We need to fix bugs now rather than adding new features.

**Comment by mariobehling** [comment]
This is not a core-functionality and we can do this later. We need to focus on bugs. I am closing this issue.
