### ISSUE TITLE
Create default custom forms automatically on event create

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1242]
As a custom form is required for an event, the default custom form should be created automatically when an event is created to avoid unneccessary bugs. We can use sqlalchemy event listeners for this.

**Comment by SaptakS** [comment]
It is always created @aviaryan because `title` field for session is compulsory and disabled.. So a custom form will surely be created by default on creating an event.

**Comment by aviaryan** [comment]
@SaptakS It won't be created when event is created through API. Also as a custom form is neccessary for an event, it should be created everytime an Event() is created. That will be the safest way.
The same has been already done for user_detail when a user is created.

**Comment by SaptakS** [comment]
@aviaryan yeah, True. But when you create the custom_form by default when an Event() is created and then another custom form is created through the view, won't there be a conflict? I think it is safer if in API for event creation function you could create a default custom_form.

**Comment by aviaryan** [comment]
@SaptakS I think the current code for custom forms is already creating duplicate custom forms for an event. See #1246. I will fix it with this issue.
