### ISSUE TITLE
Admin: Settings - Add mail gateway

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1245]
We are already using mail solutions in the system. What options do we have for mailing? Please implement what standard we use in the system and offer the mail settings in the tab `admin/settings/`, e.g. http://open-event.herokuapp.com/admin/settings/

This is relevant for https://github.com/fossasia/open-event-orga-server/issues/1237

**Comment by SaptakS** [comment]
Wasn't the mail settings supposed to be for all organizer and not only the super_admin?

**Comment by SaptakS** [comment]
It is already implemented in the `admin/settings/`

The access key for Sendgrid in the settings tab is for the email. And the mail tab shows the email bodies and other details.

**Comment by SaptakS** [comment]
Since all send out emails are using Sendgrid and that is already being set up in admin/settings tab, so closing this issue.
