### ISSUE TITLE
Event Dao doesn't return any results 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1252]
#846
Use case:
marshal(EventDAO.list(location_name=location), EVENT)

**Comment by niranjan94** [comment]
@rafalkowalski what was the location name ?

**Comment by niranjan94** [comment]
The search seems to work only with the full location name. For example, if there is an event with location name as `Brussels, Belgium`, searching for location as `Belgium` doesn't give that result.

**Comment by rafalkowalski** [comment]
is there contain conditions? @niranjan94

**Comment by niranjan94** [comment]
I'm not sure. @aviaryan any idea ?

**Comment by aviaryan** [comment]
No. location_name simply compares with the location_name field in the model i.e. like `Event.query.filter_by(location_name=location_name)` . Should I make it like the `contains` match ?

**Comment by niranjan94** [comment]
@aviaryan yes please :smile: make it a contains match
