### ISSUE TITLE
We can't create event which last more then one day

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1273]
starts, ende fields in event creation wizard

**Comment by niranjan94** [comment]
@rafalkowalski it works properly

**Comment by niranjan94** [comment]
See this event http://open-event.herokuapp.com/events/34/ 
from July 08, 2016 07:00 PM to July 30, 2016 10:00 PM

**Comment by rafalkowalski** [comment]
@niranjan94 Is it normal behaviour when i chooseend date and then i will change start date automatically end date will be increment or decrement?

**Comment by niranjan94** [comment]
@rafalkowalski the end date and start date are paired together. When you change start date after changing the end date, the end date would change such that the difference b/w the start and end stays the same.

**Comment by rafalkowalski** [comment]
ok thanks
