### ISSUE TITLE
Add searching by custom date

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1282]
#846 
![screen shot 2016-06-28 at 13 38 00](https://cloud.githubusercontent.com/assets/2479753/16414019/95415114-3d35-11e6-898a-d6260fd52811.png)
#846

**Comment by mariobehling** [comment]
Please add a description in your issue. In your scrum you write date search for beginning and end. I do not see that we need it. Any event that happens on a choosen date is fine. No need to fine-grain it more.

**Comment by mariobehling** [comment]
Ok, I see what you mean after I am looking at the Eventbrite thing. Maybe just make a screenshot and add it to your issue in future.
