### ISSUE TITLE
Fix tab names in My Session

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1283]
![screenshot from 2016-06-28 00 06 02](https://cloud.githubusercontent.com/assets/9530293/16391338/4b28e266-3cc4-11e6-95d3-aa258fbc11ec.png)

Tabs are wrongly named as `Upcoming Events` instead of `Upcoming Sessions`. Also, both tabs have same name.

**Comment by mariobehling** [comment]
Well, it is not just a different name. The pages should show what they say "upcoming sessions" and "past sessions". The functions does not work simply by renaming the menu tab item. Please look more into details of things and test with more thoughts.

**Comment by SaptakS** [comment]
@mariobehling will check that out.

**Comment by SaptakS** [comment]
@mariobehling fixed in  #1335 . Please review.

**Comment by niranjan94** [comment]
It is supposed to be sessions in upcoming **events** and past **events**. See the original issue #703 opened by @mariobehling .

**Comment by niranjan94** [comment]
![screenshot-www eventbrite com 2016-06-11 10-40-20](https://cloud.githubusercontent.com/assets/1583873/15984230/78e2d87c-2fc4-11e6-8391-e86e099512c7.png)

**Comment by SaptakS** [comment]
@mariobehling should I change it back to upcoming **events** instead of upcoming **session** ?
