### ISSUE TITLE
User description should be empty not 'None' when the user hasn't provided it yet.

### ISSUE THREAD

**Issue by vivekanand1101** [fossasia/open-event-orga-server#1286]
It looks like somebody has put "None" instead of empty space. IMHO, it is better empty.
![screenshot from 2016-06-28 02 44 00](https://cloud.githubusercontent.com/assets/9530293/16396027/6ef8707e-3cda-11e6-80b3-27028f6ea3bf.png)

**Comment by SaptakS** [comment]
![screenshot from 2016-06-28 02 44 00](https://cloud.githubusercontent.com/assets/9530293/16396014/5be2ccd2-3cda-11e6-9dfe-f2e2e4db7eec.png)
