### ISSUE TITLE
Provides configuration with Api

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#13]
- Gui color - string
- conference logo - string(url to image)
- event title string
- conference email string 

Please give me some suggestions on what else should be added @championswimmer @mananwason @mariobehling @leto

**Comment by mariobehling** [comment]
@rafalkowalski Please make an outline and define milestones first here to draw the bigger steps first. https://github.com/fossasia/open-event/issues/22
