### ISSUE TITLE
Compress CSS, JS and other static files.

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-orga-server#130]
Right now, the heroku deployment is slower and a lot of css files are not correctly minified. This should probably change so that access is faster. See image below for clues on where to optimise.

![image](https://cloud.githubusercontent.com/assets/547235/11492056/03f77092-9823-11e5-8848-148055db1865.png)

**Comment by shivamMg** [comment]
@creativepsyco I've taken this on https://github.com/fossasia/open-event-orga-server/issues/191. What do you think?
