### ISSUE TITLE
Improve Design: Event Area of Front Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1301]
Please improve the event area of the front page as below.
![screenshot from 2016-06-28 12 47 42](https://cloud.githubusercontent.com/assets/1583873/16412858/bdd8341e-3d2e-11e6-9869-0dde5421dfd6.png)

Include:
- [x] 3 column layout with Event Image (4 rows)
- [x] Short form of location
- [x] Category and Event Type

**Comment by SaptakS** [comment]
@niranjan94 are you working on this? Otherwise I would like to take this up.

**Comment by niranjan94** [comment]
I'm working on this

**Comment by niranjan94** [comment]
You could take up https://github.com/fossasia/open-event-orga-server/issues/1296

**Comment by SaptakS** [comment]
Great..

**Comment by mariobehling** [comment]
Nice work so far! Please look through the tags though. There is an issue. The words do not have a space in between.

![screenshot from 2016-06-29 14 58 49](https://cloud.githubusercontent.com/assets/1583873/16452723/3297b1e0-3e0a-11e6-8878-3d07f5537f15.png)

**Comment by niranjan94** [comment]
@mariobehling thanks :smile:  ... The lack of space is intended .. Tags are generally displayed and used in [CamelCase](https://en.wikipedia.org/wiki/CamelCase) ... Eventbrite also displays tags in CamelCase.

**Comment by mariobehling** [comment]
![screenshot from 2016-08-02 09 14 06](https://cloud.githubusercontent.com/assets/1583873/17320015/a8c8c2e0-5891-11e6-83f6-bffb88648834.png)

Please compare our tagging system to Eventbrite and Improve it. "GameOrCompetition" or "HobbiesSpecialInterest" - What does Eventbrite use here?

**Comment by mariobehling** [comment]
This issue is super old now. Each tag should have their own tag page. Please follow up.

**Comment by jainaman224** [comment]
@mariobehling can you please help me what to display on each tag page. I can create page for each tag. Please help me by describing what to display on tag page and it will be great if I am allowed to work on this.

**Comment by mariobehling** [comment]
@jainaman224 Thank you. We are looking to get exactly the same implementation as eventbrite. On eventbrite there is no "ConcertorPerformance". Please compare and see how we can improve.

**Comment by jainaman224** [comment]
@mariobehling Can you please explain for my better understanding...?
I have seen eventbrite and we have dynamic routing already implemented for tags page. So, what exactly you want me to compare...? then I will work accordingly. Thank you.

**Comment by niranjan94** [comment]
@jainaman224 in eventbrite, for the tags, no conjunctions are present ... (like and, or etc) ... 

For example, **Concert Or Performance** is shown as **#ConcertPerformance** .. and **Family & Education** is shown as **#FamilyEducation** .
