### ISSUE TITLE
Add swagger API docs

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#131]
We need to add a API documentation on the server. Swagger (http://www.django-rest-framework.org/topics/documenting-your-api/) implements a dynamic self-updating one. 

I.e. once swagger is installed, it keeps a auto-updated API documentation, with sandbox support for testing the APIs. 

For flask the following are available - 
https://github.com/rantav/flask-restful-swagger
https://github.com/acoomans/flask-autodoc

**Comment by aditya1702** [comment]
@championswimmer I implemented the "@auto-doc" decorator to generate the APIs. Can we close this issue or we need something more?

**Comment by championswimmer** [comment]
can be closed.

we can discuss after ots is over, when we make changes to the server (there
can be a rehaul of how it works)
