### ISSUE TITLE
Improve top bar and start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1319]
Someone changed the size of the font on the top bar. It is way to small now. 

* [x] Please match the size.

![screenshot from 2016-06-29 14 50 55](https://cloud.githubusercontent.com/assets/1583873/16452467/f6b61f82-3e08-11e6-8cab-81cf44c6dcab.png)

The "Create Event" button on the start page also changed the looks over time. 

* [x] Please adjust is to match the looks as well.

![screenshot from 2016-06-29 14 52 48](https://cloud.githubusercontent.com/assets/1583873/16452506/2f271268-3e09-11e6-8f2e-8a92b403b6a7.png)

**Comment by SaptakS** [comment]
@mariobehling on it. Plus we need to make it responsive as well. Someone didn't add the classes to make it responsive so it is not working correctly in small devices.. Will work on this.

**Comment by SaptakS** [comment]
@mariobehling 

**medium screen resolution**
![screenshot from 2016-06-30 07 59 29 copy](https://cloud.githubusercontent.com/assets/9530293/16475161/f24a3cb2-3e99-11e6-9838-7650da145234.png)

**Small screen resolution**
![screenshot from 2016-06-30 07 59 51](https://cloud.githubusercontent.com/assets/9530293/16475163/f8296a54-3e99-11e6-90bb-32aae24e430d.png)

**Create Event Button**
![screenshot from 2016-06-30 07 59 29](https://cloud.githubusercontent.com/assets/9530293/16475177/0b4f513e-3e9a-11e6-8b47-ea3466ad9717.png)

**Comment by SaptakS** [comment]
The measurements are exactly same as that in eventbrite.

**Comment by mariobehling** [comment]
Please also fix the space between top bar and other areas. This is also in your screenshot. Not sure, why you do not see it.

![screenshot from 2016-07-01 02 29 57](https://cloud.githubusercontent.com/assets/1583873/16515369/ef58a088-3f71-11e6-87f7-c7c573840d0d.png)

**Comment by SaptakS** [comment]
> Please also fix the space between top bar and other areas.

Didn't understand which space you are talking about.

**Comment by mariobehling** [comment]
Thank you, good improvement. Still errors in some resolutions.

![screenshot from 2016-07-01 12 05 56](https://cloud.githubusercontent.com/assets/1583873/16518648/469b4df2-3f84-11e6-99ec-1b6b08580891.png)

**Comment by SaptakS** [comment]
I checked for all the standard resolutions and seem to be working fine. I will still check for other resolutions to see if there is some error.

**Comment by SaptakS** [comment]
@mariobehling done..

**Comment by mariobehling** [comment]
Good job. Hope we can reduce the number of comments and PRs necessary to solve these kind of issues in future.
