### ISSUE TITLE
Import throws Internal server error 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1323]
https://github.com/loklak/loklak_server/issues/642
Testing Data: 
[EventBriteInfo.zip](https://github.com/fossasia/open-event-orga-server/files/339362/EventBriteInfo.zip)

> Traceback (most recent call last):
> 2016-06-29T13:30:12.526450+00:00 app[web.1]: Exception on /api/v2/events/import/json [POST]
> 2016-06-29T13:30:12.526465+00:00 app[web.1]:     return self.dispatch_request(*args, **kwargs)
> 2016-06-29T13:30:12.526462+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
> 2016-06-29T13:30:12.526460+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
> 2016-06-29T13:30:12.526460+00:00 app[web.1]:     rv = self.dispatch_request()
> 2016-06-29T13:30:12.526461+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
> 2016-06-29T13:30:12.526463+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_restplus/api.py", line 309, in wrapper
> 2016-06-29T13:30:12.526464+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/views.py", line 84, in view
> 2016-06-29T13:30:12.526463+00:00 app[web.1]:     resp = resource(*args, **kwargs)
> 2016-06-29T13:30:12.526470+00:00 app[web.1]:     new_event = import_event_json(file)
> 2016-06-29T13:30:12.526470+00:00 app[web.1]:   File "/app/open_event/api/helpers/import_helpers.py", line 183, in import_event_json
> 2016-06-29T13:30:12.526466+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
> 2016-06-29T13:30:12.526467+00:00 app[web.1]:     resp = meth(*args, **kwargs)
> 2016-06-29T13:30:12.526467+00:00 app[web.1]:   File "/app/open_event/api/helpers/helpers.py", line 288, in decorated
> 2016-06-29T13:30:12.526468+00:00 app[web.1]:     return f(*args, **kwargs)
> 2016-06-29T13:30:12.526469+00:00 app[web.1]:   File "/app/open_event/api/imports.py", line 18, in post
> 2016-06-29T13:30:12.526471+00:00 app[web.1]:     raise make_error('event')
> 2016-06-29T13:30:12.526472+00:00 app[web.1]: ServerError

**Comment by aviaryan** [comment]
@rafalkowalski json files should be at the root of the zip. That EventBriteInfo.zip doesn't follow that format and so is the error.

**Comment by rafalkowalski** [comment]
@aviaryan i didn't know
