### ISSUE TITLE
Make /admin/mails -> /admin/messages

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1328]
* [x] Create separate tabs for Mails and Notifications (under `/admin/messages`)
* [x] Create `system_notifications.py` to register notifications (just like `system_mails.py`)
* [x] Implement the notifications tab (display notification structures).

Edit:

* [x] Add datatable options (Search filter and Pagination)

**Comment by mariobehling** [comment]
Please also follow the design of the other tabs and include "Show X Emails/Show X Notifications" and a "Search" bar.

**Comment by shivamMg** [comment]
@mariobehling Like mails, we can include services under notifications as well. Like:

- New Session Proposal
- Session Schedule Change
- Next Event (Event coming soon)
- Session Accept or Reject
- Invitation For Papers

What do you think? If the user already has an account, we can send notifications as well.

**Comment by mariobehling** [comment]
@shivamMg Sounds good to me. I think we are on the right track. Let's see what is the final outcome. Good step forward! Thank you.
