### ISSUE TITLE
Admin: Add logs for notifications 

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1330]
* [x] Log notifications.
* [x] Create Notifications tab under `/admin/logs` to display them.

**Comment by mariobehling** [comment]
Please post a screenshot, where logs actually show up. I do not see any logs in the tab, but there are emails in the tab. Emails should not be there as we distinguish between notifications and logs. If we do both, then there should be two different messages showing up a) in mails and b) in notifications.

**Comment by shivamMg** [comment]
The issue is complete.
