### ISSUE TITLE
'Create Account' redirects to 404

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1333]
On clicking "Create Account" button on the register page the user is redirected to a 404 page with the url : 
http://open-event.herokuapp.com/register/?next=shit

**Comment by shivamMg** [comment]
@aditya1702 Because `/shit` path doesn't exist. We do not have any view defined for it.

**Comment by aditya1702** [comment]
@shivamMg I know that. But I had earlier made it redirect to the index page. I dont know who changed it and that also to /shit!

**Comment by shivamMg** [comment]
@aditya1702 Let's just say this never happened. 


https://github.com/fossasia/open-event-orga-server/commit/b7d79dcadd4a9ce1e1966353339c221ea37e5f6b
