### ISSUE TITLE
Don't show trashed items in API

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1345]
Parent issue : #1220 

Trash has been implemented using a bool column in each table (in_trash) which is True if the item has been deleted. Currently API makes no distinction between trashed and active items. 
As trash is only for admins and not for the end-user, the API should not return trashed items and treat them as deleted.

**Comment by aditya1702** [comment]
@aviaryan could u give me the link for the document from which u referred the import/export feature

**Comment by aviaryan** [comment]
@aditya1702 Let's talk in chat. That question is not related to this issue.
