### ISSUE TITLE
Empty space in menu

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#135]
Please remove html tag if events are empty "<li class="divider"></li>" 
Current view:
![zrzut ekranu 2015-12-07 o 17 04 46](https://cloud.githubusercontent.com/assets/2479753/11632093/bcc686b2-9d05-11e5-9eef-c3e4e2a9cd11.png)

Expected Result:
![zrzut ekranu 2015-12-07 o 17 10 55](https://cloud.githubusercontent.com/assets/2479753/11632106/c9f4a332-9d05-11e5-940d-5b55c4e56c58.png)

**Comment by aditya1702** [comment]
I have solved this issue....I just want to know how to put if-else statements in the html tag

**Comment by rafalkowalski** [comment]
Cool!
