### ISSUE TITLE
Implement Sitemap Page

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1376]

**Comment by aviaryan** [comment]
@rafalkowalski sitemap.xml is already located at /sitemap.xml . Apart from that, there is a html version of sitemap that I will be creating. (https://github.com/fossasia/open-event-orga-server/issues/1318)
Is there a difference between this issue's sitemap and them ?

**Comment by mariobehling** [comment]
duplicate.
