### ISSUE TITLE
Top menu improve responsive 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1381]
![screen shot 2016-07-02 at 13 52 02](https://cloud.githubusercontent.com/assets/2479753/16540207/632fbee8-405c-11e6-8b8c-be5fb7cf0e57.png)

**Comment by SaptakS** [comment]
It shows perfectly for me in the live system.
![screenshot from 2016-07-02 20 57 48](https://cloud.githubusercontent.com/assets/9530293/16541096/c53a94ec-4097-11e6-972a-07276cdb1d0e.png)

**Comment by rafalkowalski** [comment]
Chrome version 51 doesn't work

**Comment by SaptakS** [comment]
Strangely chrome and browser treated some bootstrap elements. Fixed.
