### ISSUE TITLE
Refine REST APIs

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1390]
Currently we are using Events POST API to create Social Links, and Sessions POST API to create Session Types. This is making modification of created data (social-links and session-types) more complex. So e.g. if a social-link needs to be updated, a request to the Events PUT API is made (but the other data related to that event must be the same so it doesn't get modified). Thinking about deleting a social-link becomes more complex. To delete a particular social-link should we remove it in the event payload and then make a request at Events PUT api? (what we are doing right now) But PUT apis should be used only for updating existing resources, not deleting them. 

Same goes for session-types and sessions.

This is making us use workarounds for handling Event and Session APIs, making APIs more complex. The better way to do it would be to take out separate APIs for SocialLinks and SessionTypes under Events and Sessions respectively. This will also help us with the import/export functionality: https://github.com/fossasia/open-event-orga-server/pull/1343

Goals:

- Create Social-Links and Session-Type APIs 
 - Put Social-Links API under Event API namespace (`/events/:id/social_links`)
 - Put Session-Type API under Session API namespace (`/events/:id/sessions/types`)
- Handle import/export functionality separately.
 - Update helpers to use Social-Link and Session-Type DAOs.

**Comment by shivamMg** [comment]
I was working to include it in the PR but it's only making it complex. If we're going to do it without dedicated social-link and session-type APIs, this is the way we would be going.

> Maybe you mean /events/:id/sessions/types ?

Yes, I meant that. Updated the description.

**Comment by aviaryan** [comment]
> I was working to include it in the PR but it's only making it complex.

Yes, I agree that adding social links and session types to Event & Sessions POST/PUT API will make it very complex, not to mention bad design. If it is neccessary to make social links and session types CUD-able from the APIs, then we will have to create separate APIs. Though by neccessary I don't just mean the import function. 

*If full social links and session types API are only needed by import function, then we should not create them (the APIs) and instead just modify the import functions itself.  As I said earlier this should be a small change and will fix #1327 *

**Comment by juslee** [comment]
HTTP has another verb called DELETE. Have you considered that?

**Comment by shivamMg** [comment]
@juslee You mean having a delete endpoint for social-links (and session-types), right.
