### ISSUE TITLE
Add Copyright info for events

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1397]
https://github.com/OpenTechSummit/open-event-scraper/blob/master/out/services.json#L64

- "holder_url"
- "license"
- "license_url"
- "year"
- "logo"
- "holder"

* [x] Create db model
* [x] Update the Events API
* [ ] Remove lightbox. Implement dropdown.

**Comment by shivamMg** [comment]
@niranjan94 @mariobehling Should I create UI to add copyright info?

**Comment by mariobehling** [comment]
Yes, good to implement, but I did not think all this through yet. Some of it is clear. Please also implement:
* [ ] When someone adds an event, add the current year into the "year" in the fied in the db
* [ ] Add the organizers in the "holder" field in the db
* [ ] Holder URL, add the link to the organizer on Open Event.

**Comment by mariobehling** [comment]
@shivamMg I think for the UI implementation, there should be a very simple dropdown menu to choose the license in the first step of the wizard. Check out how flickr does it. Please open a separate issue for the UI (also need to add some info about the licenses to the DB and logos for each license).

![screenshot from 2016-07-05 00 30 06](https://cloud.githubusercontent.com/assets/1583873/16570554/c5db29f0-4247-11e6-87d1-9d378b05ea5f.png)

**Comment by shivamMg** [comment]
@mariobehling :+1: I've created it a separate issue.

**Comment by mariobehling** [comment]
People who are really in depth interested in all kinds of licences - for them it is really good to have an overview. Our users, for them they do not need so much in depth info. The name of the licences and the link to more info would be enough. A simple dropdown menu as flickr is sufficient. Please avoid the big lightbox and implement it in the flickr way.

**Comment by shivamMg** [comment]
![screenshot from 2016-07-15 13 51 19](https://cloud.githubusercontent.com/assets/7882752/16868120/8b1fa45e-4a93-11e6-87b3-7a8b0952aba9.png)

After clicking on the help icon ("?") a list would slide down. If user clicks on it again, it would slide up and hide again.

![screenshot from 2016-07-15 13 53 23](https://cloud.githubusercontent.com/assets/7882752/16868126/8f806ec0-4a93-11e6-8ba8-79a4f5074209.png)


@mariobehling will this work?
