### ISSUE TITLE
User events[GCI]

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#140]
User events exist after event after removing

![zrzut ekranu 2015-12-14 o 18 24 13](https://cloud.githubusercontent.com/assets/2479753/11788214/308fb8a4-a290-11e5-8ffb-36ec7666831c.png)

**Comment by leto** [comment]
@rafalkowalski can you describe a bit better what the bug is and what you would expect to be happening? It is not quite clear

**Comment by rafalkowalski** [comment]
@leto Sure, 
How to reproduce bug:
- run project according to documentation
- Create own user account
- Create own event
- On main page you are able to see event
- then remove it
After removing you will see a above results events without name

You have to update eventsusers table after removing events

**Comment by leto** [comment]
@rafalkowalski this seems like a good GCI task. If you add it, you can put me down as a mentor :smile:

**Comment by rafalkowalski** [comment]
@leto I'm not able to add you as a mentor. Could you add yourself ?https://codein.withgoogle.com/dashboard/tasks/5114998573498368/

**Comment by leto** [comment]
@rafalkowalski I can't seem to add myself either

**Comment by leto** [comment]
@mariobehling can you add me as a mentor to the above task? Not sure we have the permissions

**Comment by mariobehling** [comment]
@leto done.

**Comment by yasoob** [comment]
Hey @leto I am not sure how to intercept the `.delete` endpoint of Flask-Admin.

**Comment by leto** [comment]
@yassob can you describe a bit more about what you are trying to do? @rafalkowalski is also a good person to  ask

**Comment by suheb** [comment]
@rafalkowalski We should close this. Fix #183

**Comment by rafalkowalski** [comment]
Cool :)
