### ISSUE TITLE
Add input validation in Wizard

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1410]
Right now sponsors url field accepts any input. (no URL validation)
Same goes for ticket url field in Step 1. 
I suggest we should add client side input validation. We are already including bootstrap validator in our dependencies.

In this issue, I will add input validation to wizard wherever possible.

**Comment by aditya1702** [comment]
@aviaryan I could help with this issue

**Comment by niranjan94** [comment]
@aviaryan @aditya1702 I think now that the URL validators have been added, all fields of the wizard are validated if and when required. This issue could be closed.
