### ISSUE TITLE
Call for speakers

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1412]
When i filled requirements fields in form in call for speakers
I only can see details about sessions but speaker details not saved 
Name and email are empty
![screen shot 2016-07-04 at 15 43 47](https://cloud.githubusercontent.com/assets/2479753/16562704/924ec590-41fe-11e6-8045-2a3da6e6da6e.png)

**Comment by SaptakS** [comment]
I am working on it.

**Comment by SaptakS** [comment]
@rafalkowalski the speaker is shown here. However there is another issue. It is not exactly a bug. But if the speaker fills up the form with a new name but an old email id, then the name corresponding to the email id is saved. I am not sure whether this is a bug or is correct. @niranjan94 what do you think?

**Comment by SaptakS** [comment]
I think this issue can be closed? @rafalkowalski @niranjan94 ?
