### ISSUE TITLE
User should receive email notification when state of session is changed

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1413]

**Comment by SaptakS** [comment]
Working on it.

**Comment by mariobehling** [comment]
Should we give the organizer the option "Send user information about the changes?" Options -> Send Now | Cancel

Also, do we need a field with information if mails have been sent below the session info about emails sent, that only the organizer/co-organizers etc. see?

**Comment by mariobehling** [comment]
Maybe check out the feature on meetup.com. Once an organizer creates a meetup, they have the option send info now or later. Then a windo popsup to show how the message will look like and they can send it out.

**Comment by SaptakS** [comment]
Will surely check that out.

**Comment by SaptakS** [comment]
@mariobehling does this involve only changing from Draft to Publish? I think a email should also be sent to the speaker, when his Session is accepted or rejected.

And as of the implementation, we can open a lightbox on clicking the state change buttons. In the lightbox, we can have a field with a default message, that he may edit. And a Send|Cancel button.

What do you think?

**Comment by mariobehling** [comment]
Yes, good idea, but please also give the option "send later" and show it visually in the session overview list, if an acceptance/rejected email as been sent or not.

**Comment by SaptakS** [comment]
I think its already shown whether a session is accepted/rejected. Can you provide a link about which list you are talking about?

**Comment by mariobehling** [comment]
> whether a session is accepted/rejected

Not, whether a session is accepted: Where an email has been sent out or not.

**Comment by mariobehling** [comment]
Where can I see if an acceptance/rejected email has been sent out?
e.g. here? http://open-event-dev.herokuapp.com/events/3/sessions/

![screenshot from 2016-07-20 18 17 45](https://cloud.githubusercontent.com/assets/1583873/16994176/8bdeea1e-4ea6-11e6-94bd-9d3694fc9e3c.png)

**Comment by SaptakS** [comment]
Ok.. I thought about the session being accepted/rejected. Sorry.. Yeah.. Will implement that as well.. Not a problem.
