### ISSUE TITLE
Add Copyright info to event wizard

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1423]
parent issue: https://github.com/fossasia/open-event-orga-server/issues/1397

Cover the following points:

* [x] When someone adds an event, add the current year into the "year" in the fied in the db
* [x] Add the organizers in the "holder" field in the db
* [x] Holder URL, add the link to the organizer on Open Event. 

https://github.com/fossasia/open-event-orga-server/issues/1397#issuecomment-230360369

**Comment by shivamMg** [comment]
![screenshot from 2016-07-06 14 05 17](https://cloud.githubusercontent.com/assets/7882752/16612118/eb181e76-4382-11e6-8dc0-2586655cf81d.png)

![screenshot from 2016-07-06 14 06 25](https://cloud.githubusercontent.com/assets/7882752/16612127/f40be094-4382-11e6-91c3-b72294c124f9.png)

**Comment by shivamMg** [comment]
@mariobehling ^ is what it would like. The "?" help button will open up a modal that displays the licence name its logo and a link to the licence deed (e.g. https://creativecommons.org/licenses/by/4.0/). I've also added brief description about the licenses (taken from here https://creativecommons.org/licenses/). I've added the two as an example. I'll add others shown in the comment here: https://github.com/fossasia/open-event-orga-server/issues/1397#issuecomment-230360369

**Comment by mariobehling** [comment]
Unfortunately, you did not understand. We need to keep complexity down as much as possible for the user:
* [ ] We do not need a field "Year" as the in the -- DB -- we can just enter the actual year. There is no need to fill it out by the user
* [ ] As described, but not implement: Add the organizers in the "holder" field in the -- db -- No need to add a field for it to fill out!
* [ ]  We also do not need "COPYRIGHT HOLDER URL". Please in the -- DB -- enter the URL to the "organizer" of the public event pages
* [ ] Please provide a screenshot and sample event link where all the info shows up including the Copyright info with the suitable images e.g. Creative Commons image and link to license info
