### ISSUE TITLE
Event creation problem in session tracks, rooms

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1426]
Reproduce:
Add few tracks without name
Click turn off sessions, tracks, rooms button
Then click save  

So you can't save event without filling above tracks names because they are required. 
![screen shot 2016-07-05 at 09 39 28](https://cloud.githubusercontent.com/assets/2479753/16577273/6e67a7fa-4294-11e6-8f59-43e61c9a0619.png)
![screen shot 2016-07-05 at 09 39 35](https://cloud.githubusercontent.com/assets/2479753/16577274/71585a54-4294-11e6-85fc-34dfa8c01ae2.png)

**Comment by niranjan94** [comment]
@rafalkowalski if you turn off sessions, tracks and rooms, you're able to save. I just now tried it.

- Add few tracks without name
- Click turn off sessions, tracks, rooms button (that is, I have turned it off. )
- Then click save

**Comment by niranjan94** [comment]
See http://open-event.herokuapp.com/events/53/
