### ISSUE TITLE
Test POST API with minimum payload

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1435]
We should write testcases where POST APIs of events, microlocations etc are tested with minimum payloads meaning only those fields which are required are set in the payload. 
This will help finding bugs. Many of the recent bugs I see are because of this.

**Comment by mariobehling** [comment]
Please help me to understand. The minimum info defined in the UI to make an event life is: name, and date. How is that different in the APIs?

Apart from testing with minimum payload, we also need to test with maximum payload and check that changes are saved. What are your thoughts?

**Comment by aviaryan** [comment]
> Please help me to understand. The minimum info defined in the UI to make an event life is: name, and date. How is that different in the APIs?

The required fields in UI is same as that in API.

> Apart from testing with minimum payload, we also need to test with maximum payload and check that changes are saved. What are your thoughts?

API with maximum payload is already being tested. 
Recently we saw a lot of bugs because some optional fields where missing in the payload . (like 'copyright' in Event payload, closing_datetime in Event payload etc) . So I am writing tests for minimum payload. 
I have found almost 4-5 bugs already due to these tests.
