### ISSUE TITLE
Connect with Instagram

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1444]
#831 

- [x] connect with instagram
- [x] get images
- [ ] save images

**Comment by mariobehling** [comment]
Where do we need this? Screenshot? Why do we need to implement this now? We need a production ready system. This is a non-essential feature and we have bugs to solve.

**Comment by aviaryan** [comment]
Connecting with Instagram gives error. (PS - I know work on this issue has been stopped right now)

Url - 
https://www.instagram.com/oauth/authorize/?response_type=code&client_id=None&redirect_uri=http://open-event-dev.herokuapp.com/iCallback&state=AsDLkpqLNDbmrYq8HjjJmVvG8Uwf5S&access_type=offline

Text - 
```
{"code": 400, "error_type": "OAuthException", "error_message": "Invalid Client ID"}
```

**Comment by mariobehling** [comment]
This is not a core feature and currently no more integration is needed. Let's focus on closing bugs.
