### ISSUE TITLE
Import/Export needs to add all images (not embed them from external services)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1449]
Currently we offer the import and export of images and include a link to the image. There are limits to this approach. If we import an image link to another website, the site might not allow us to show lots of images and block us. You can see this at event 55 in the system (http://open-event.herokuapp.com/e/55/).

Importing an event, should actually import all the images and import and export files should have all images in the actual image folder.

On the other hand we still want our Android app and Web app to be able to download updates from the website and we want to define a URL to do that.

How should we deal with this?

I think we could solve it this way: We add the images into the export/import file and also define API end points in one of the JSON files (maybe events.JSON) and hence the Android app will know where to get the files.

**Comment by aviaryan** [comment]
Sounds good. We can create a folder named "images" in the zip. 
At the root it can have event-level data like logo.png, background.png etc. Then there can be folders inside it for sponsors and speakers. Those folders will have images related to sponsors and speakers respectively. 

> On the other hand we still want our Android app and Web app to be able to download updates from the website and we want to define a URL to do that.

I don't understand what here is meant by "updates" . Aren't the web and android apps supposed to use th e APIs to get data from server. So if something in an event is updated, its GET API data will be updated.

**Comment by mariobehling** [comment]
> Aren't the web and android apps supposed to use the APIs to get data from server. So if something in an event is updated, its GET API data will be updated.

The Android app can use the API, but for the web app it is not sure. So, let's proceed that way and include the pictures in the zip itself. As other parts of the project (apps, and event parser) depend on this, it is very high priority. Please proceed asap.

**Comment by aviaryan** [comment]
I will start working on this using Celery for background upload/download jobs. I plan to first do the import of images part and then the export part.
