### ISSUE TITLE
Invalid URL for 'audio'

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1454]
During import, "audio" field in sessions.json is being validated for a URL, but is specified as a path in samples. A solution could be to not derive Upload field class from Uri class. Instead a Path field can be defined. 

Edit: The "country" and "organisation" fields in Speakers API have been specified required, but the OTS speakers sample has many fields as empty strings. We can specify them as "Not available" in the sample set.

**Comment by aviaryan** [comment]
> During import, "audio" field in sessions.json is being validated for a URL, but is specified as a path in samples. A solution could be to not derive Upload field class from Uri class. Instead a Path field can be defined.

Upload field supports paths but the 'path' should start with a '/' i.e. relative to the root of the server. (There is no meaning of relative to folder on the server anyway)
Currently OTS json has paths like "audio/5063.mp3" . Converting them to "/audio/5063.mp3" should fix this issue. 

> Edit: The "country" and "organisation" fields in Speakers API have been specified required, but the OTS speakers sample has many fields as empty strings. We can specify them as "Not available" in the sample set.

:+1:

**Comment by shivamMg** [comment]
@aviaryan The issue with Audio file urls is not getting solved by prepending the slash "/". They being validated as URLs. I think it is better to create separate validator for Upload field (and not derive it from URL). The strings will always have an extension, right? `/path/filename.ext`

**Comment by aviaryan** [comment]
> The strings (for uploads) will always have an extension, right? /path/filename.ext

No. not necessary. On S3, the files are stored without extension. (to prevent duplicacy, Content-Disposition header is used to return file with correct extension).

**Comment by shivamMg** [comment]
OK, will work accordingly.

**Comment by aviaryan** [comment]
> @aviaryan The issue with Audio file urls is not getting solved by prepending the slash "/". They being validated as URLs. I think it is better to create separate validator for Upload field (and not derive it from URL).

Not sure if that should happen or not. Well other thing that can fix this is converting audio urls from "audio/5063.mp3" to "https://raw.github.com/OpenTec...../audio/5063" i.e. full direct link on github server.

**Comment by shivamMg** [comment]
Much better :+1: 

All audio files are stored here: https://github.com/OpenTechSummit/2016.opentechsummit.net/tree/gh-pages/programm/audio

I'll link to them instead.

**Comment by mariobehling** [comment]
@shivamMg @aviaryan This is not the desired solution as it makes the service dependent on outside services. Everything needs to be stored on our server and in a standard way for each event. Do not just copy the folder structure of the zip. Think this through yourself!

@aviaryan 21 days ago I added an issue in Milestone 6 about this. Unfortunately, you did not follow up yet. Two days ago I added priority high. I now added priority "Urgent". What can I do to bring your attention to this issue? https://github.com/fossasia/open-event-orga-server/issues/1050 If you need help, please ask, but please start to think this through. The question how to store files is a core functionality.

**Comment by aviaryan** [comment]
> @shivamMg @aviaryan This is not the desired solution as it makes the service dependent on outside services. Everything needs to be stored on our server and in a standard way for each event. Do not just copy the folder structure of the zip. Think this through yourself!

Currently no files are copied from import zip. Incase that direct links are added in the json files of import, we can make it so such that our server downloads the files from the links and stores them on our server. If the user decides to store images, audio etc in the import zip file itself, then we can still upload those data on our server. Both will be possible after the following issue is done. (I am working on it now that celery has been added)
https://github.com/fossasia/open-event-orga-server/issues/1449
So direct links in import json will not be a problem as they will be downloaded by our server. We can also switch off this option (if needed) and rather than direct links, only accept relative links (i.e. link with file in the zip).

**Comment by mariobehling** [comment]
@aviaryan Thanks for pointing this out. We also need to look at a bigger picture here. Let's say we have hundreds and thousands of events. Please propose a way all this data is stored and get feedback from everyone involved: #1050

**Comment by aviaryan** [comment]
@mariobehling 
Ok. Sorry for the delay in doing that issue. 
Will research on the following topics today and provide feedback. 
- Best practises for storing large amount of files in S3
- Using S3 as storage for large-scale projects, best practises

**Comment by aviaryan** [comment]
> Currently no files are copied from import zip. In case that direct links are added in the json files of import, we can make it so such that our server downloads the files from the links and stores them on our server. If the user decides to store images, audio etc in the import zip file itself, then we can still upload those data on our server. Both will be possible after the following issue is done. (I am working on it now that celery has been added)
#1449
So direct links in import json will not be a problem as they will be downloaded by our server.

This has been implemented now. Hence closing.
