### ISSUE TITLE
Testing various parts of Orga Server

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1457]
As we can see, a number of issues related to editing form elements and updation in database is coming up. So, it is good to have a list of things that we need to get tested. We need to write automated tests for all these as well as this can act as a guideline for human testers.

Here is a list of things we need to test for creating and editing :-
- [ ] Event Wizard [Step - 1]
- [ ] Sponsors [Event Wizard Step -2]
- [ ] Session Type [Event Wizard Step -3]
- [ ] Tracks [Event Wizard Step -3]
- [ ] Microlocations [Event Wizard Step -3]
- [ ] Call for Speakers [Event Wizard Step -4]
- [ ] Custom Forms [Event Wizard Step -5]
- [ ] Session Form [Organizer]
- [ ] Speaker Form [Organizer]
- [ ] Session Form [Guest Speaker]
- [ ] Speaker Form [Guest Speaker]

We need to also check effect of updating one form element on other informations :- 
- [ ] Session and Speaker information on updating Custom Forms in Event Wizard Step-5
- [ ] Session and Speaker information on Updating Session Types, Tracks, Microlocation in Event Wizard Step - 3

**Comment by SaptakS** [comment]
These are only some that I felt relevant, feel free to add to this list..

**Comment by mariobehling** [comment]
Please create a test protocol and file bugs. Do you have any participants of your outreach events who can help with this?

**Comment by SaptakS** [comment]
@mariobehling this issue was created as a guideline for anyone who wanted to test the entire application so that they know exactly where to search for.

I have asked some developers her for testing. But as of now no one has filed any bugs. I am not sure what to do about this issue.

**Comment by niranjan94** [comment]
This could be taken up at #2881
