### ISSUE TITLE
Search a given event for a speaker

### ISSUE THREAD

**Issue by leto** [fossasia/open-event-orga-server#146]
Given an event ID X and a string S, search through all speakers at event X and return speaker data about all speakers who have a name matching S. 

A JSON array should be returned

**Comment by leto** [comment]
This was already completed by @aditya1702, closing

**Comment by yasoob** [comment]
Hey @leto Can you also close all the instances for [this task](https://codein.withgoogle.com/tasks/5148923479982080/?sp-is_beginner=False) as well?

**Comment by leto** [comment]
@yasoob I am unable to close tasks

**Comment by yasoob** [comment]
Okay @leto  :+1:
