### ISSUE TITLE
Make floor for rooms compulsory

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1461]
Floors for rooms need to be compulsory. For now, it gives internal error. Will be adding form validation.

**Comment by niranjan94** [comment]
@SaptakS no. Floors for room must be optional. See #866.

**Comment by SaptakS** [comment]
But the DB scheme and everywhere else floor is taken as a required field. Previously when that issue was solved, floor wasn't even being saved. It was just a dummy input which wasn't being used at all to be honest. And floor is compulsory only if you add microlocations, not always which I think makes sense. What do you think @mariobehling ?

**Comment by SaptakS** [comment]
@mariobehling what is your opinion?

**Comment by mariobehling** [comment]
I do not think we need floors. Many events do not have floors. Optional please. Please ensure, there is no error if there is no floor, then close this issue.

**Comment by SaptakS** [comment]
Ok.. will get it done.
