### ISSUE TITLE
Add Organizer URL to Event

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1469]
* [x] Add it in the Event model.
* [x] Update forms to include the field.
* [x] https://github.com/fossasia/open-event-orga-server/issues/1423

Edit: Shift copying of Organizer data to Copyright info to front-end.

If the user keeps the Copyright Holder and Holder URL fields empty, then the Organizer Name and Organizer URL are copied to them. This is done at the back-end, so even if the user would like to keep them empty he won't be able to. A better solution could be to shift it to front-end. So if the user enters the Organizer name and url, the data is immediately copied to the respective Copyright fields.

**Comment by mariobehling** [comment]
A website of the organizer can already be set in the "social links" section. Just like in an address book, e.g. gmail contacts, there is a section where URLs can be defined.

So, if an organizer defines a field "Website" this becomes the "Organizer URL".

If an organizer does not define that field, then the "organizer URL" stays empty and there is no link.

-> Take out this field and keep the UI to a minimum that only includes fields that make sense.
