### ISSUE TITLE
Do not flash "Email sent to user" if no user exists

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1474]
![bug](https://cloud.githubusercontent.com/assets/15054664/16686177/f5c3a12c-452d-11e6-96bb-6fa1cebed46d.png)

**Comment by shivamMg** [comment]
@aditya1702 Is this after sending Event-Role invite to user?

**Comment by aditya1702** [comment]
@shivamMg Yes

**Comment by shivamMg** [comment]
@aditya1702 The email is sent to people who are not registered as users on our system. People who are registered as users are sent notifications. https://github.com/fossasia/open-event-orga-server/issues/873

But the "User doesn't exist" dialog should not pop up.

**Comment by aditya1702** [comment]
@shivamMg I had not created any user with the email - 'adityavyas17@gmail.com'. So you mean to say that in this case the email should be sent even if the user is not created, right?

**Comment by shivamMg** [comment]
@aditya1702 Yes. Someone who has not created an account at our platform will get an email (with a modified signup link). While those who do have an account will get a notification.
