### ISSUE TITLE
UI issue. search input box not working correctly for small screen devices 

### ISSUE THREAD

**Issue by yDeepak1889** [fossasia/open-event-orga-server#1493]
![input box issue](https://cloud.githubusercontent.com/assets/13899661/16707509/887ba968-45ee-11e6-911d-6825900c629a.png)

In the above image i have written many characters in input box but they  all are not visible,  like certain amount of input box is not visible to user.

**Comment by SaptakS** [comment]
@yDeepak1889 would you like to solve this?

**Comment by yDeepak1889** [comment]
I'll try :)

**Comment by SaptakS** [comment]
Fixed.
