### ISSUE TITLE
Adding a new sponsor with logo does not work

### ISSUE THREAD

**Issue by leto** [fossasia/open-event-orga-server#150]
To reproduce:

* Make sure you have the latest commit on master with the `static/sponsor_log` directory
* Go to http://0.0.0.0:8001/admin/event/1/sponsor/new
* Create a new sponsor with an uploaded image
* It will seem to work, but there will be no sponsor row in the UI. Your logs will show this:

```
ERROR:root:DB Exception! (psycopg2.ProgrammingError) can't adapt type 'FileStorage' [SQL: 'INSERT INTO sponsors (name, url, logo, event_id) VALUES (%(name)s, %(url)s, %(logo)s, %(event_id)s) RETURNING sponsors.id'] [parameters: {'event_id': u'1', 'url': u'asfd', 'name': u'fuck fuck', 'logo': <FileStorage: u'1970595_10152735183272501_456061550_n.jpg' ('image/jpeg')>}]
10.0.2.2 - - [18/Dec/2015 02:23:40] "POST /admin/event/1/sponsor/new HTTP/1.1" 302 -
```

NOTE: The file does actually get saved correctly into the `static/sponsor_logo` directory

**Comment by aditya1702** [comment]
Well, I think its because that particular event does not have the permission. When I run it locally on my computer it's displaying the image in the UI
![screen shot 2015-12-18 at 22 51 10](https://cloud.githubusercontent.com/assets/15054664/11902725/f6acfcd0-a5d9-11e5-94c9-cbecd40d0a36.png)

**Comment by leto** [comment]
@rafalkowalski @creativepsyco can y'all try to create a sponsor with logo and let us know if it works?

**Comment by leto** [comment]
I tried using a small 14K PNG as a logo (previously it was a large JPG) and I still get the same error:

```
ERROR:root:DB Exception! (psycopg2.ProgrammingError) can't adapt type 'FileStorage' [SQL: 'INSERT INTO sponsors (name, url, logo, event_id) VALUES (%(name)s, %(url)s, %(logo)s, %(event_id)s) RETURNING sponsors.id'] [parameters: {'event_id': u'1', 'url': u'localhost', 'name': u'BESSEL', 'logo': <FileStorage: u'bessel.png' ('image/png')>}]
```

**Comment by creativepsyco** [comment]
Nope it doesnt work.

**Comment by creativepsyco** [comment]
Ok fixed. file field was being assigned to a string type.

**Comment by aditya1702** [comment]
Ohh!I must have forgotten to change it in my initial commits!

**Comment by creativepsyco** [comment]
The same error was present for speaker as well. So it was a generic problem.

**Comment by aditya1702** [comment]
Yaaa..I saw that.Next time I will commit properly:)
