### ISSUE TITLE
Sent out Email Info missing in Admin Logs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1501]
According to the logs page in the admin area, emails were sent out, but it does not show up where the emails have been sent to.

![screenshot from 2016-07-09 18 03 38](https://cloud.githubusercontent.com/assets/1583873/16708803/a178dc90-45ff-11e6-8141-80dcb1c8a199.png)

**Comment by SaptakS** [comment]
@mariobehling @rafalkowalski fixed this. When sessions were created, empty string was being sent for invitation email, which caused such email notification. I have added the check for empty email notification in #1554 . However it will be effective only after merging on session created from now and all the entries made before with empty email id will still be there in DB.

**Comment by rafalkowalski** [comment]
@SaptakS can we close it?
