### ISSUE TITLE
Show nosetest logs

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1508]
https://pypi.python.org/pypi/nose-htmloutput this is something that can be used to generate html files for nosetest reports during the build and shown in admin space.

**Comment by niranjan94** [comment]
Why would we need to display nosetest output in the admin panel ? The instance on heroku will always be the one in which all the tests have passed. (Heroku deployment will not occur otherwise)

**Comment by rafalkowalski** [comment]
I think it's not necessary travis is enough

**Comment by SaptakS** [comment]
@mariobehling and I were thinking that it would be easier for the organizer to see the results of the tests in an HTML page. This is done by many organizations such as jQuery on their project where they show the result of the build in an HTML page, for better viewing.

That is what I think. @mariobehling @rafalkowalski @niranjan94 what do you think?

**Comment by mariobehling** [comment]
@rafalkowalski @niranjan94 html output would be good to have a list of tests that are performed. Specifically, we are also interested to see tests, that do not exist and are not performed.

**Comment by niranjan94** [comment]
We'll handle this is a different more specific issue. We already have HTML output for Robot tests.
