### ISSUE TITLE
Issues in Event View Page

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1511]
- [x] Email is always "test@example.com".~~It should be either the organizer or else we need email field in event creation.~~ Delete this field.
- [x] ~~Organized by is never shown but in `events/` we see that creator is the organizer.~~

**Comment by SaptakS** [comment]
@mariobehling @niranjan94 what do you suggest for the first point? Should we add an email field in event creation?

**Comment by mariobehling** [comment]
Example link/screenshot?

**Comment by SaptakS** [comment]
http://open-event-dev.herokuapp.com/e/50/

![screenshot from 2016-07-10 06 30 14](https://cloud.githubusercontent.com/assets/9530293/16711117/7044c6e8-4668-11e6-8a10-0d4cc30a9ae6.png)
