### ISSUE TITLE
Session not saved from Display View

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1537]
Saving session from display view(for example: http://open-event-dev.herokuapp.com/events/61/sessions/439/) doesn't work. @niranjan94 @mariobehling Should we be able to save session from display view as well?

**Comment by niranjan94** [comment]
Or we could show the edit view for both.

**Comment by SaptakS** [comment]
@mariobehling what do you think should be done?

**Comment by mariobehling** [comment]
@niranjan94 Yes, let's keep it simple, but there are actually some differences how things work from an organizer perspective and a speaker perspective. Let's keep it simple for now though and just use the edit view for both for now.

**Comment by mariobehling** [comment]
@SaptakS Please implement this as an overlay lightbox just like the original submission form. Please also make this into one column. The two column UI is distracting. One column please.

**Comment by SaptakS** [comment]
@mariobehling overlay lightbox only for the details view or the edit view as well?

**Comment by mariobehling** [comment]
Details view = edit view. Both overlay.

**Comment by mariobehling** [comment]
One column layout for both.

**Comment by SaptakS** [comment]
@mariobehling will get it done right away.. :+1:
