### ISSUE TITLE
Document deployment of server on Webhosting application without SSH access

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1547]
Some webhosters offer hosting of Python application, but they do not offer SSH access. How can a user install the application there? Please document this.

**Comment by aviaryan** [comment]
@mariobehling Can you give me an example of such webhost ? I am not able to find any. I think most of no-ssh ftp-only webhost support PHP only.

**Comment by mariobehling** [comment]
Check out Hetzner please, one of the biggest providers in Europe: https://www.hetzner.de/ot/hosting/produktmatrix/webhosting-produktmatrix

**Comment by niranjan94** [comment]
I don't think this would be possible. Especially if there is no SSH access either. We'll re-visit this when needed.
