### ISSUE TITLE
Make first wizard step 1 into "one column" layout

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1555]
Please make the style more similar to Eventbrite into one column.

**Comment by mariobehling** [comment]
Please make the design closer to Eventbrite. Create subissues if necessary.

Especially regarding:
* [ ] location and when a map shows up (This might require a subissue. The problem with calling Google Maps will be that as soon as we have a few users, we will have to pay. So better implement it in the way Eventbrite does).
* [ ] adding image
* [ ] make the same style as with background image below for the logo
* [ ] Add sections "Tickets" and move Ticket URL into this section

**Comment by mariobehling** [comment]
Good progress. Please also
* [ ] Move column to center
* [ ] Move "next, save, make live" to bottom right hand of the actual column (not the page)
* [ ] Move event license to very last point in section "Additional Details" and rename to "License of Event Data and Content"

**Comment by SaptakS** [comment]
Ok. Working on it.
