### ISSUE TITLE
Add search box for easier selection of location

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-orga-server#156]
Right I have to manually enter the latitude and longitude of the where the event is taking place, i can drag the pointer on the map, however if there is a way to easily select location by providing a text box (Which is already there -- See the textbox with `Singapore`) and adjust the map location accordingly. 

![image](https://cloud.githubusercontent.com/assets/547235/11919520/7baaa916-a790-11e5-9768-57f67af6fb79.png)

**Comment by aditya1702** [comment]
@creativepsyco I have added the search enhancement to the map in create event.Will you please look at it:)

**Comment by creativepsyco** [comment]
I will let @leto look into it :)

**Comment by leto** [comment]
This was merged recently. Hopefully it made @creativepsyco happy
