### ISSUE TITLE
Implement system pages editor or link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1562]
We already defined links for the system pages, e.g. about page. In the admin section at `/admin/pages` implement a submenu with the system pages. 
Offer a choice
* [x] a) "Enter a link here" or alternatively 
* [x] b) Add a text here (provide a rich-text editor for admins)

The following pages need to be created:
![screenshot from 2016-07-11 16 52 29](https://cloud.githubusercontent.com/assets/1583873/16735080/094c511a-4788-11e6-832e-dc2942eed3ae.png)

![screenshot from 2016-07-11 16 53 24](https://cloud.githubusercontent.com/assets/1583873/16735084/0cfc047c-4788-11e6-9357-a0c82f967056.png)

**Comment by rafalkowalski** [comment]
if i have a problem i will ask you

**Comment by mariobehling** [comment]
Please make the pages lightbox very wide, maybe 95% of window. There is no reason to keep the area so small.

**Comment by mariobehling** [comment]
![screenshot from 2016-07-14 01 09 17](https://cloud.githubusercontent.com/assets/1583873/16822815/9c126056-495f-11e6-8479-0965d63d8106.png)
