### ISSUE TITLE
Implement "Tracks" view and "Rooms" view for schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1564]
In some events tracks are in one room, but at other events sessions of the same track take place in different rooms. A nice way to show this is in different views. For event schedules, please implement
* [x] track views and
* [x] room views
* [x] add two simple buttons on top top right of the schedule

![screenshot from 2016-07-11 17 29 40](https://cloud.githubusercontent.com/assets/1583873/16736620/0b5dd72a-478e-11e6-93a7-6c9a07312d46.png)

**Comment by niranjan94** [comment]
@mariobehling What we have now is a _Rooms view_. So, for _Tracks view_, if we group the sessions by tracks instead of rooms, there will be overlaps since multiple sessions of a track may occur simultaneously.

**Comment by niranjan94** [comment]
Or, can I, for _Tracks View_, make the UI similar to this (with tracks instead of rooms) for desktop and mobile ?

![capture](https://cloud.githubusercontent.com/assets/2404372/16775530/abb7ae44-487e-11e6-9664-ad25129a825e.PNG)

Tracks view in a timeline such as what is already there would result in overlaps

**Comment by mariobehling** [comment]
Actually your implementation is better for mobile, but as a matter of fact we already have this in a different design in the "sessions view". So, here it was more expected to just sort this instead of rooms in tracks.

There are issues in the rooms display though as well. Cannot see the sessions if the time is too short. How does shdlr.com solve this? What is your idea?

**Comment by niranjan94** [comment]
@mariobehling I'll check out shdlr.com and see if we can implement it in a better way

**Comment by niranjan94** [comment]
Two things I noticed on shdlr.com.

1. They do not have a track view. Instead, the sessions are colored according to the tracks. (sessions in the same track, have the same color) 
2. The sessions have a minimum duration of 15 mins. This prevents the height of the sessions from being too small. 

I feel these two points are pretty valid and practical. we could do the same.

**Comment by championswimmer** [comment]
:+1: Niranjan,

Coloring per track is best in my opinion too, and @mariobehling and
@aayusharora and I had agreed on the same too earlier on Gitter.

**Comment by mariobehling** [comment]
@niranjan94 

1. About colors: We are defining the track colors in the wizard already. However, I realized there is some different functionality when I click in the scheduler and I could change the color by clicking several times. Maybe look into it. 
* [ ] So, the colors of sessions should be according to what is defined for the track in the wizard.

2. Track view should be same as room view, except that sessions are sorted according to tracks. 
* [ ] So, please here the calendar kind of style as well.

3. Actually "Sessions" is also a view of s schedule. 
* [ ] So, could you add a button "Session View" next to Rooms and Tracks View, please?

4. As mentioned above, in shdlr.com is is easier to see the session. Please
* [ ] increase the height of rows as a first step, so more data shows up.
* [ ] Open another issue and propose more improvements e.g. to show more info including location/room -> expansion of session row on click

**Comment by niranjan94** [comment]
@mariobehling 

> Actually "Sessions" is also a view of s schedule. So, could you add a button "Session View" next to Rooms and Tracks View, please? 

So, here, you mean the same view that is at `/e/<event_id>/sessions/` right ? ([Link](http://open-event-dev.herokuapp.com/e/9/sessions/))

> Track view should be same as room view, except that sessions are sorted according to tracks.

The timeline/calendar cannot be sorted by tracks correctly due to the fact that there maybe sessions within the same track that occur simultaneously. This will cause an overlap in the timeline. 

I have completed the rest.

**Comment by mariobehling** [comment]
> So, here, you mean the same view that is at /e/<event_id>/sessions/ right ?

Yes

> The timeline/calendar cannot be sorted by tracks correctly due to the fact that there maybe sessions within the same track that occur simultaneously. This will cause an overlap in the timeline. So, we should try to make a different UI for that.

Good point. I have seen column split for simultaneous things. Let's refine that later and do other issues first then.

Please close this issue after the sessions link is finished.
