### ISSUE TITLE
Implement missing icons of social networks

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1565]
Some social networks do not show icons in the public event page yet. Please support more social networks. See example below.

![screenshot from 2016-07-11 18 01 21](https://cloud.githubusercontent.com/assets/1583873/16737471/cc66c550-4791-11e6-99d9-5261b4b4fb80.png)

**Comment by aditya1702** [comment]
@mariobehling By supporting more social networks do you mean the functionality also or for now only the icons?

**Comment by shivamMg** [comment]
@aditya1702 Only the icons.

**Comment by mariobehling** [comment]
Very good. Please also add icons for other social networks we have not covered yet.

Also add an icon for websites and blogs.

**Comment by aditya1702** [comment]
@mariobehling Ok
