### ISSUE TITLE
Some events return empty array in sessions and speakers even though data exists

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#1572]
Case in point 

http://open-event-dev.herokuapp.com/e/9/ 

http://open-event-dev.herokuapp.com/api/v2/events/15/sessions
http://open-event-dev.herokuapp.com/api/v2/events/15/speakers

**Comment by championswimmer** [comment]
@shivamMg @aviaryan @SaptakS 
I need to be able to get full event data (sessions, speakers everything) via the API to test generator of webapp with server APIs

**Comment by the-dagger** [comment]
We will be needing this for the Android app too.

**Comment by shivamMg** [comment]
@championswimmer OK, I think I got it. It's because in_trash attribute for models has been defined as None, while it should be False by default. Give me some time.

**Comment by shivamMg** [comment]
@championswimmer OK, I've solved it here:https://github.com/fossasia/open-event-orga-server/pull/1574. But the existing data still has models defined with in_trash = None. I'm changing it now.

**Comment by shivamMg** [comment]
@championswimmer Done. The undeleted sessions and speakers should be visible now.
