### ISSUE TITLE
Propose and implement a mobile version of the schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1575]
How to get this schedule on small resolutions and mobile devices?

![screenshot from 2016-07-11 22 46 59](https://cloud.githubusercontent.com/assets/1583873/16746192/81ace468-47b9-11e6-86c8-6db563bbf399.png)

**Comment by niranjan94** [comment]
For a mobile version of it, the rooms page of the webapp seems to be perfect. 
http://open-event-generator.herokuapp.com/live/preview/rooms.html We can use that for the mobile version and the full table-style schedule if the screen size is large enough.

**Comment by SaptakS** [comment]
@niranjan94 seems cool. But we would lose the functionalities of the Scheduler such as resizing and re-editing, right? Though I think its ok if those are not there for mobile devices.

**Comment by niranjan94** [comment]
Resizing and drag-drop is anyway not practical for a mobile device. We can give an edit button like we already have where they can use a time picker and a drop down to change time and room in mobile view.

**Comment by mariobehling** [comment]
@niranjan94 Mobile devices include also pads, that are bigger than phones.

The web app version would introduce another design component. We already have so many different designs everywhere and I will follow up on this with issues (just thought it is not the highest priority, e.g. your popup system messages are different to everywhere else on the system).

So, what we need now is some design consistency. We have a list of sessions already in "session view". 

I do not know a perfect solution here, but following the web app and introducing more styles is not a good way.
