### ISSUE TITLE
Rewrite tests for APIs

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1586]
@aviaryan I'm implementing permissions for APIs https://github.com/fossasia/open-event-orga-server/issues/1517

But this is resulting in a lot of failing tests. This is because many of the api tests create events/services using helper functions instead of making a POST request. So user does not get permissions for updating services. Plus many tests include making GET request to fetch data while they don't have the permission to read it.

I'll will have to rewrite tests so they create events/services only through the APIs.

**Comment by aviaryan** [comment]
@shivamMg Ok. Please do what is required.
