### ISSUE TITLE
Responsive model for Tabs

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1598]
We need to decide on a responsive tab design. Does anyone have any suggestion for tabs in small devices.. The model right now doesn't work very good.

**Comment by mariobehling** [comment]
Not sure, why this got closed. Testers tell me that the tabs throughout the application are not always responsive. Please provide a list of tabs you have solved and which commit. There is no commit linked to this issue.

**Comment by SaptakS** [comment]
@mariobehling Sorry. I must have closed this issue by mistake.

**Comment by SaptakS** [comment]
@mariobehling  in the event dashboards, the tabs are implemented in a responsive accordion format but it is not a very good UI. And I have done some research but I couldn't find a suitable solution to make tabs responsive. 

@niranjan94 @aditya1702 @rafalkowalski any suggestions?

**Comment by niranjan94** [comment]
@SaptakS could tabs be made into a good old simple drop down menu on smaller screens ? (with the selected tab visible and the rest coming up as a drop down)

**Comment by SaptakS** [comment]
@niranjan94 I was thinking of a similar idea. Just making it into a dropdown, so that one can select and then we mark that part as active.

But I am expecting someone from codeheat to solve this.

**Comment by niranjan94** [comment]
@SaptakS ... cool :+1: ... I think we could unassign long pending issues so that codeheat guys can take it up

**Comment by SaptakS** [comment]
@niranjan94 cool

**Comment by sehgalayush1** [comment]
@SaptakS I would like to work on this issue if it is ok.

**Comment by sainiak009** [comment]
I was interested in this issue, and discussed it too but again did the same mistake of not commenting here earlier. If possible please review my PR and merge it.

**Comment by SaptakS** [comment]
This feature needs to be implemented at all places where there is tab and not only in the events dashboard. @sainiak009 @sehgalayush1 please look into it.

**Comment by sainiak009** [comment]
@SaptakS Okay. I will do it.

**Comment by SaptakS** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/9530293/19754395/e1a348b0-9c2a-11e6-9394-eed1e74e0d4c.png)

The Tabs in admin dashboard are still not responsive.
