### ISSUE TITLE
Show information only if available

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1609]
Show information which are available only in `/e/ID/`

For example in http://open-event-dev.herokuapp.com/e/61/#organizer , there is no organizer information but the option for organizer is still shown.

**Comment by mariobehling** [comment]
Which information available where?

Some more explanation and screenshots or so which specific area you are talking about would be really helpful.

**Comment by SaptakS** [comment]
Sorry. Updated the description..

This is what I propose. If there is no organizer info, there won't be an organizer option shown in the page:
![screenshot from 2016-07-14 04 05 37](https://cloud.githubusercontent.com/assets/9530293/16822176/5a638ce8-4978-11e6-9456-9456644f5b69.png)

**Comment by mariobehling** [comment]
Well if there is no specific organizer info, the info should be taken from the profile of the organizer. There is definitely a person who sets up the event. This person will be the organizer. We need to think it through how we implement this.

But here in your screenshot I see, that there is no sponsor defined. So, if there is no sponsor the field should not show up.

**Comment by SaptakS** [comment]
Ok.. I will make that modification as well.. So only the informations present should show the fields, right? Will get that done right away.

**Comment by SaptakS** [comment]
@mariobehling modified to show only fields which are defined.
