### ISSUE TITLE
Sessions without tracks not shown in Event Preview

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1613]
Sessions without tracks not shown in `/e/ID/sessions/`

For example sessions are there in http://open-event-dev.herokuapp.com/events/61/sessions/ but no sessions in http://open-event-dev.herokuapp.com/e/61/sessions/

**Comment by mariobehling** [comment]
Where exactly? Screenshot? Schedule, session list? Where?

It would be really good if you add details in the description of your issues.

**Comment by SaptakS** [comment]
@mariobehling sorry. Updated the description now.

**Comment by mariobehling** [comment]
It is unclear if this is a bug. Most sessions in this list are pending and I cannot see, if a session is listed in the scheduler, cause the scheduler is not working at the moment. Not sure, what is your proposal. Maybe you could describe the expected behavior before you implement sth.

**Comment by SaptakS** [comment]
The problem is many of the times a session doesn't have a track so it is not shown in the preview. So I was thinking of making another option in the session page as "Other" for example which will have the list of all the sessions without tracks. Else I think track needs to be made compulsory.

![screenshot from 2016-07-14 03 32 12](https://cloud.githubusercontent.com/assets/9530293/16821390/a571c182-4973-11e6-82e5-1d3c7d471807.png)

And I will check the scheduler as well. But this is independent of the scheduler I think.
