### ISSUE TITLE
Scheduler not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1615]
Tested with different events. Check out example here http://open-event-dev.herokuapp.com/events/61/scheduler/

Pretty urgent as it prevents us from testing lots of other features as well.

![screenshot from 2016-07-13 23 38 26](https://cloud.githubusercontent.com/assets/1583873/16820749/ee907b86-4952-11e6-9111-d138ed7f1c9e.png)

**Comment by mariobehling** [comment]
Important to understand this issue: https://github.com/fossasia/open-event-orga-server/issues/1613#issuecomment-232487969

**Comment by SaptakS** [comment]
I am on it.
