### ISSUE TITLE
How can we search events by location?

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1628]
Every of us know that we have different names of location in countries. Every country have own naming convention. How can we find events by locations? 

For example Polska and Poland should return the same events

**Comment by niranjan94** [comment]
Why not use latitude and longitude ? That's not gonna change with language. We already have lat/long of all events. When a user enters a location name for searching, geocode that name to latitude and longitude, and use that to filter the events ...

**Comment by aditya1702** [comment]
@rafalkowalski  I too agree with niranjan. Latitude and longitude can be used

**Comment by rafalkowalski** [comment]
The simplest solutions are the best! :+1: @niranjan94
