### ISSUE TITLE
Add local images to the OTS sample set

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1642]
Ability to import images and other media from the zip was added here https://github.com/fossasia/open-event-orga-server/pull/1594

The OTS sample set should include its images locally and the OTS json files should link to the local images.

**Comment by mariobehling** [comment]
Please take the images from the OpenTechSummit https://github.com/OpenTechSummit/2016.opentechsummit.net/tree/gh-pages/programm

There are all here already and I hope we can do this quickly.

**Comment by aviaryan** [comment]
@mariobehling Ok. will proceed.

**Comment by mariobehling** [comment]
What about the JSON files that are not needed anymore? Which ones are integrated?

**Comment by aviaryan** [comment]
If you are referring to https://github.com/fossasia/open-event-orga-server/issues/1327, then currently all json files are needed. After sub-apis were created for social links and session types, no decision was made on whether to remove the json files or not. See https://github.com/fossasia/open-event-orga-server/pull/1343#issuecomment-230527099
So currently all json files are integrated.

**Comment by mariobehling** [comment]
@aviaryan Please delete un-needed JSON files, that offer duplicate data. Which ones are those? We are keeping samples here now https://github.com/fossasia/open-event
