### ISSUE TITLE
When to show location and map?

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1646]
In event creation wizard step-1 we have a location and map. But the problem with calling Google Maps will be that as soon as we have a few users, we will have to pay. So we can do this:
- [x] Allow users to use google autocomplete location
- [x] Allow users to fillup address manually
- [x] Checkbox to show/hide map on event page.

Parent Issue: #1555

**Comment by SaptakS** [comment]
@mariobehling @niranjan94 @rafalkowalski should we put a checkbox for whether to show map in events page for that event? Eventbrite does something similar. It has a checkbox which you can check or uncheck depending on whether you want to show map in events page.

**Comment by mariobehling** [comment]
@SaptakS Please make the style closer to Eventbrite. Currently it is not clear "Geolocation" does not work, the map does not show up.

http://open-event-dev.herokuapp.com/events/81/edit/

It is not clear, what "Geolocation" mean. Users do not understand.

**Comment by mariobehling** [comment]
![screenshot from 2016-07-16 22 08 19](https://cloud.githubusercontent.com/assets/1583873/16896905/0ecda27e-4ba2-11e6-9cb7-9011674631fd.png)

**Comment by mariobehling** [comment]
Please use "Enter Address" instead of "Fill Address Form".

**Comment by mariobehling** [comment]
Event location currently does not get centered on map.

![screenshot from 2016-07-18 14 57 51](https://cloud.githubusercontent.com/assets/1583873/16915504/1f0e1c8e-4cf8-11e6-85c9-ac07e915a244.png)

**Comment by SaptakS** [comment]
I will check and do the necessary changes.

**Comment by mariobehling** [comment]
The first two line "Address" and "Address 2" should be separated just as the other lines

**Comment by SaptakS** [comment]
Ok.. They were both street address so I felt I should do that.. I will separate them.

**Comment by mariobehling** [comment]
Looks good. When fields are extended "to Enter Address" autocomplete does not seem to work anymore.

Please also enable map as default.

**Comment by SaptakS** [comment]
@mariobehling it doesn't work in eventbrite as well. Reason being the implementation is in such a way that we can bind the autocomplete maps to a particular input field to work it correctly. Making autocomplete in all the input fields is not recommended. The functioning works in a way where we request from the location and we get a response back from google map in form of address component.  So when we enter the address, this field is updated on change. So getting autocomplete to work with "Enter Address" is problem. I think thats the reason eventbrite doesn't do it as well.

**Comment by SaptakS** [comment]
I will still have a look and see if something can be done for autocomplete.

**Comment by mariobehling** [comment]
Good job. Thank you.

**Comment by SaptakS** [comment]
:smiley:

**Comment by kokoye2007** [comment]
Not Working with search or manual point on Maps
