### ISSUE TITLE
Table in list of all events goes out of the wrapper

### ISSUE THREAD

**Issue by shiftsayan** [fossasia/open-event-orga-server#165]
<img width="1280" alt="screen shot 2016-01-05 at 4 23 20 pm" src="https://cloud.githubusercontent.com/assets/8451336/12113453/d5687f7a-b3c8-11e5-9ca5-fd1d83e2ef7f.png">

The problem is even worse on smaller screens.

<img width="1280" alt="screen shot 2016-01-05 at 4 25 45 pm" src="https://cloud.githubusercontent.com/assets/8451336/12113486/131609aa-b3c9-11e5-8759-b4d06aeff7a7.png">

**Comment by aditya1702** [comment]
@shiftsayan Its not happening with me. Did you clone the most recent update of this repo?Could you tell more about this bug

**Comment by shiftsayan** [comment]
I am using the demo version in the readme file.
Log in -> List of all events

**Comment by aditya1702** [comment]
@shiftsayan clone the repo and run the app on the web server. It will work fine.

**Comment by shiftsayan** [comment]
So that means that the demo version has an issue to be fixed?

**Comment by aditya1702** [comment]
I think so yes @shiftsayan

**Comment by aviaryan** [comment]
> So that means that the demo version has an issue to be fixed?

I was testing the most recent version of the app locally and it also has the same problem.
