### ISSUE TITLE
Sponsor Id doesnt decrement

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#166]
When a new sponsor is created it is displayed in the table. However when you delete it and then again create a new sponsor the sponsor Id will not be same.It gets incremented although the the same sponsor Id as the 
![screen shot 2016-01-05 at 20 23 59](https://cloud.githubusercontent.com/assets/15054664/12118107/ba78d74c-b3ea-11e5-82c8-37e476f9b380.png)
previous one should have been assigned to it.

**Comment by creativepsyco** [comment]
I believe the ids should auto increment. It shouldn't reuse ids because you never know which ID has been used where.

**Comment by leto** [comment]
@aditya1702 @creativepsyco is correct. The id's are only ever used once. Even if we know it is logically the same thing, internally it assigns it a new id

**Comment by aditya1702** [comment]
@leto ok
