### ISSUE TITLE
Add a versions GET API in Event

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1663]
Parent #1702 

Versions GET API will basically have the last update date of an API.
Example - https://github.com/fossasia/open-event/blob/master/otsJson/event/1/version

This can be useful for the android app as they can decide whether to refresh data from the server or not. 

@shivamMg @mariobehling views ??

**Comment by shivamMg** [comment]
@aviaryan :+1: Would be a nice feature.

**Comment by aviaryan** [comment]
@mariobehling @shivamMg Do we still plan to add version information to Event API now that E-Tag has been done ? #1749 
Following the discussions at #1702, I think we have planned on keeping both (versions and E-Tag) but need to confirm so that I can start working on this issue. 
I plan to add `versions` information in the Event GET API as is being reflected by https://github.com/fossasia/open-event/pull/41 .

**Comment by mariobehling** [comment]
Ok, on a note about our discussions: I am starting to loose track of the discussion across multiple issues. The best practices outlined was always to create smaller issues, that can be solved within a day and followed up easily. So, let's try to go back to this. We can have parent issues that help to understand the bigger picture. Please help to make it easier.

Regarding the question about E-Tag and Event-API, I think the version info in the event API is important when we create JSON files for import/export. So, yes we still need it.

In howfar do we need to document this? Please do the necessary.
