### ISSUE TITLE
Change mail and notifications into one admin page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1665]
The way mail and notifications currently work does not seem to be suitable for all cases. We still need to find out what message should be a mail or notification and when messages should be both.

The easiest way to adapt this is to control this in the admin message settings at https://open-event-dev.herokuapp.com/admin/messages/

* [x] Please merge both subtabs (mails and notifications) and 
* [x] offer three checkboxes in the last column 
   * [x] a) for mail
   * [x] b) for notifications
   * [x] c) a checkbox "User Control", which defines if the user can switch off the mail message in his settings
* [x] If both checkboxes in a row are activated for a message, the message should show up in both ways and the user gets an email. 
* [x] Please implement that message either show up or not (depending on the admin settings) in the mail settings of the user

**Comment by SaptakS** [comment]
So, if "User Control" is not checked, the user cannot change the options for that action in mail settings, right?

**Comment by SaptakS** [comment]
![screenshot from 2016-07-16 09 45 39](https://cloud.githubusercontent.com/assets/9530293/16895576/1d35478a-4b99-11e6-96f9-6843ec164f73.png)

@mariobehling can you please review the UI?

**Comment by mariobehling** [comment]
Excellent! Thank you

**Comment by SaptakS** [comment]
@mariobehling I will have to put the backend as well. Its just the UI right now. I will get it done by tomorrow... :+1:

**Comment by SaptakS** [comment]
- [ ] Font Size should be smaller
- [ ] Update Settings on bottom right

**Comment by mariobehling** [comment]
Please see my last comment in this issue as well https://github.com/fossasia/open-event-orga-server/issues/1820#issuecomment-235999834
