### ISSUE TITLE
Some sessions are not in a track

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#1668]
In this response many sessions do not have track object

http://open-event-dev.herokuapp.com/api/v2/events/9/sessions

Questions : 
Is it valid for this to happen ? (If not, please accept this as bug, and solve)
If it is valid, then how do I group such a session ?

In the admin dashboard, is it possible to create Sessions which do not belong to a track  ?

**Comment by SaptakS** [comment]
@championswimmer I have already fixed this issue. #1619 

However, the old events that were already created didn't have this constraint and thus you find some sessions are not in any track.
