### ISSUE TITLE
Add key to Array of object in existing json output to follow re:Data

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#1683]
We need to add key to the array of objects to follow the re:data conventions. The existing output is not parseable with libraries we are using as well.  We need to change it from 
``` 
[  
   {  
      "audio":null,
      "comments":null,
      "end_time":"2016-05-05 08:00:00",
      "id":1,
      "language":null,
      "long_abstract":"",
      "short_abstract":"",
      "signup_url":null,
      "slides":null,
      "start_time":"2016-05-05 07:30:00",
      "state":"accepted",
      "subtitle":null,
      "title":"Fantastische Hardware Bauen",
      "track":{},
      "video":"https://www.youtube.com/channel/UCJoKp-gG2t7lH5_hiKp95yA"
   }
]
```
to 

```
{  
   "sessions":[  
      {  
         "audio":null,
         "comments":null,
         "end_time":"2016-05-05 08:00:00",
         "id":1,
         "language":null,
         "long_abstract":"",
         "short_abstract":"",
         "signup_url":null,
         "slides":null,
         "start_time":"2016-05-05 07:30:00",
         "state":"accepted",
         "subtitle":null,
         "title":"Fantastische Hardware Bauen",
         "track":{  

         },
         "video":"https://www.youtube.com/channel/UCJoKp-gG2t7lH5_hiKp95yA"
      }
   ]
}
```

Please treat this as high priority as we need to start integrating client apps with the orga server and that requires changing the parsers on the client side.

**Comment by niranjan94** [comment]
@mananwason would you need a key only for array responses or should the key be there for single row responses too ? (Like when retrieving a single session/event)

**Comment by mananwason** [comment]
No @niranjan94, I just need a key to access the array, so the format I have added above should work.
```
{  
   "sessions":[  
      {  
         "audio":null,
         "comments":null,
         "end_time":"2016-05-05 08:00:00",
         "id":1,
         "language":null,
         "long_abstract":"",
         "short_abstract":"",
         "signup_url":null,
         "slides":null,
         "start_time":"2016-05-05 07:30:00",
         "state":"accepted",
         "subtitle":null,
         "title":"Fantastische Hardware Bauen",
         "track":{  

         },
         "video":"https://www.youtube.com/channel/UCJoKp-gG2t7lH5_hiKp95yA"
      },
{  
         "audio":null,
         "comments":null,
         "end_time":"2016-05-05 08:00:00",
         "id":1,
         "language":null,
         "long_abstract":"",
         "short_abstract":"",
         "signup_url":null,
         "slides":null,
         "start_time":"2016-05-05 07:30:00",
         "state":"accepted",
         "subtitle":null,
         "title":"Fantastische Hardware Bauen",
         "track":{  

         },
         "video":"https://www.youtube.com/channel/UCJoKp-gG2t7lH5_hiKp95yA"
      }
   ]
}
```

**Comment by shivamMg** [comment]
@mananwason Is this the re:data api: http://data.re-publica.de/doc/api.html

it doesn't seem to have keys.

**Comment by niranjan94** [comment]
In fact to make your current parser work without keys, 

for example, with the events, 
Instead of having a List of `Event` inside `EventResponseList`, make `EventResponseList` extend `List<Event>` ... That way gson won't expect a key, it'll directly parse the json into a list of events.

**Comment by mananwason** [comment]
@shivamMg yes this is the api format. I wonder why they have changed it to this format. The link to sample json that I gave yesterday was from the earlier format they followed. But anyways, we can close this for now then.

@niranjan94 Yes I know how to parse this format but was not sure if this should be the format for our api's or not. 
P.s. We need to have a list of ``` Event ```  inside the ``` EventResponseList``` because gson can't understand that the json is an array. Instead if I just remove the ```@SerializedName``` annotation, it will decode everything.
