### ISSUE TITLE
Remove similar values from Session types in fossasia16 sample set

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1686]
many session types are of the same name and length.

**Comment by mariobehling** [comment]
Samples are here now https://github.com/fossasia/open-event/tree/master/sample

**Comment by shivamMg** [comment]
@mariobehling I solved it with the PR at open-event repo. Earlier the session types had multiple objects with the same name and length: https://github.com/fossasia/open-event-orga-server/blob/b26ca51c2738d5aaaa4cb35533de37bc7300729f/samples/fossasia16/session_types.json

I removed the redundant objects: https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/session_types.json
