### ISSUE TITLE
Event details page are different in code of conduct page

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1693]
Menu on the left side is different
![adipisci velit open event coc](https://cloud.githubusercontent.com/assets/2479753/16901331/a284006e-4c40-11e6-977c-ef70d585ff10.png)
![adipisci velit open event](https://cloud.githubusercontent.com/assets/2479753/16901335/a8bc583c-4c40-11e6-8546-b21fbd30e5ba.png)

http://open-event-dev.herokuapp.com/e/63/
http://open-event-dev.herokuapp.com/e/63/coc/

**Comment by SaptakS** [comment]
I will fix this.

**Comment by rafalkowalski** [comment]
Why ? I'm working on this
