### ISSUE TITLE
Refactoring event settings form 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#17]

**Comment by mariobehling** [comment]
@rafalkowalski Could you please add more details to issues? What are you actually planning to do? Please add all issues and features https://github.com/fossasia/open-event/issues/22 to this repo and assign a milestone.

**Comment by rafalkowalski** [comment]
I'm going to improve ConfigView class, It looks very ugly
https://github.com/fossasia/open-event-orga-server/commit/ec9d0e58b28203b7081c832fb05178aff5704caf

Besides I wanna add a wtforms validation to fields like(email, logo, title, color).
Currently validation doesn't works
