### ISSUE TITLE
Broken preview for file-uploads

### ISSUE THREAD

**Issue by yasoob** [fossasia/open-event-orga-server#170]
Broken preview for file-uploads. Steps to reproduce:

- Open http://open-event.herokuapp.com/admin/event/upload
- Upload a file which is not an image
- Broken preview in the `Min` column 

Fix:
- Do not try to provide a preview for files which are not of an `image` type.

**Comment by suheb** [comment]
@rafalkowalski @leto @creativepsyco @championswimmer @aditya1702 
Hey guys, what's the expected behavior here?
In my latest commit, I just show the preview depending upon whether it's an image file or not. But both this and #176 can also be fixed if we only allow image files to be uploaded.

**Comment by leto** [comment]
I don't see a use case for uploading files that are not images. Can anybody else? Maybe @mariobehling has some thoughts

**Comment by creativepsyco** [comment]
So we can either restrict uploading or provide the preview image ourselves in case it is broken (similar to FB/GitHub providing a default profile in case you are missing one).

**Comment by aditya1702** [comment]
@leto I agree with @creativepsyco .We can use a default image that gets displayed in absence of an image.

**Comment by yasoob** [comment]
We can only allow uploading `.docx`, `pdf` and image files. I don't think there is any need for any other files apart from these.

**Comment by suheb** [comment]
Looking at the current design, it seems file uploading was intended for images only. For instance, the url ``` /pic/file_name ``` and the preview column in the table.
Let me know how to move forward with this.

**Comment by leto** [comment]
@suheb Let's do pictures only for now, because that was the intention. We should accept .jpg, .jpeg, .gif and .png

**Comment by suheb** [comment]
@leto Done, see my pull request.

**Comment by suheb** [comment]
@yasoob You can close this issue. Fix #177
