### ISSUE TITLE
Accept/Decline Button missing in Notifications

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1703]
At the moment invitations can be accepted by clicking on the message. This is an unexpected behaviour.

Please implement and accept and decline button.

![screenshot from 2016-07-18 01 24 29](https://cloud.githubusercontent.com/assets/7882752/16902794/f2d8bb90-4c86-11e6-997b-d1c2f6cfc8b1.png)

**Comment by shivamMg** [comment]
- Add views to decline invites.

**Comment by shivamMg** [comment]
@mariobehling I've implemented it for Role invite [pr](https://github.com/fossasia/open-event-orga-server/pull/1721). Shall I do the same for Submit-Papers?

**Comment by mariobehling** [comment]
@shivamMg Submit papers should should not show "accept/decline" but a button "View Call for Speakers" (which links to the public CfS page) and "Submit" which links to the form to submit a session.
