### ISSUE TITLE
Upload button doesn't show file name when image is uploaded

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1714]
![upload](https://cloud.githubusercontent.com/assets/2479753/16919550/6d79a002-4d0a-11e6-81ac-bf5919bc312d.png)

**Comment by SaptakS** [comment]
@rafalkowalski which image upload is this related to? I think we can make all image uploads like the one in Event Step-1. @mariobehling @niranjan94 what do you think?

**Comment by mariobehling** [comment]
@rafalkowalski It is not the first time, we are asking for a description, links and screenshot in issues. Your issues are often hard to understand. Could you provide all required information please?

**Comment by SaptakS** [comment]
@rafalkowalski I think in this issue, it is better that when someone uploads the image, show the image directly in the placeholder. Something similar to the way its done for logo in Event Step-1 or in Facebook. [This](https://github.com/fossasia/open-event-orga-server/blob/development/app/templates/gentelella/admin/event/wizard/step-1.html#L638) might be of help.
