### ISSUE TITLE
API Endpoint to show event related data

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1733]
Provide data for events using a query string parameter to tell what all data is required.

Examples:

`/api/v2/events/<event_id>/` - will display basic event info (what we already have right now)
`/api/v2/events/<event_id>/?include=sessions` - will include all the sessions along with the basic event data.
`/api/v2/events/<event_id>/?include=sessions,speakers` - will include all the sessions and speakers info along with the basic event data.
`/api/v2/events/<event_id>/?include=tracks` - will include all the tracks info along with the basic event data.

**Comment by mariobehling** [comment]
Also add this info in a dashboard tab and make it configurable as described in this issue: https://github.com/fossasia/open-event-orga-server/issues/1739
