### ISSUE TITLE
Profile: Improve Page Details

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1735]
* [x] "Full name" -> "Full Name"
* [x] "Details about user:" -> "Details about User:"
* [x] Rename Contact to Phone and ensure only phone number can be entered
![screenshot from 2016-07-19 16 28 27](https://cloud.githubusercontent.com/assets/1583873/16953613/fcb3cdb0-4dcd-11e6-9c7c-4ac4ebae25aa.png)

**Comment by SaptakS** [comment]
By only phone number, do you mean a pattern. I don't know any other way of verifying a phone number. But then again, patterns may also vary from country to country, right? So a little confused what to do. Any ideas?

**Comment by SaptakS** [comment]
Also the links on left overlap with the form on right.
![screenshot from 2016-07-20 03 49 24](https://cloud.githubusercontent.com/assets/9530293/16968542/2a2db4f4-4e2d-11e6-91b5-a9beea94e1cd.png)
Should I change links like facebook, twitter, mail to icons?

**Comment by mariobehling** [comment]
Only allow characters: +-0123456789()

**Comment by mariobehling** [comment]
Icons is good to, if there is time to do it.

**Comment by SaptakS** [comment]
I will change to icons.. It should take only a moment..

**Comment by mariobehling** [comment]
* [ ] Facebook and Twitter do not accept URLs without "www" and without http:// . If http is not added it should be added automatically by the system

**Comment by SaptakS** [comment]
@mariobehling Should we rather provide them a placeholder with `https://www.facebook.com/` so that they need to just add their username. They would also be able to input the full link. What do you think?

**Comment by mariobehling** [comment]
yes good idea.
