### ISSUE TITLE
Wizard step 1 name: Organizer showing up even though field is deactivated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1736]
Organizer field was activated and then deactivated in wizard step 1. Expected behaviour is that the info and organizer link in the event page does not show up anymore, but it still does.

Compare: https://open-event-dev.herokuapp.com/e/85/

![screenshot from 2016-07-19 16 47 04](https://cloud.githubusercontent.com/assets/1583873/16954311/b48ebdc6-4dd0-11e6-92d5-c4fed2c39d70.png)

**Comment by SaptakS** [comment]
I will check this our asap.
