### ISSUE TITLE
Simplifying Wizard steps 3, 4, 5

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1740]
Currently we offer options to turn on or off options 3 and 4 in the wizard. There are some dependencies that are difficult to handle and explain though, e.g. if sessions are switched on, but no speaker submission is possible (there is no button in the public event page) if call for speakers is switched off currently.

What is the solution for this? I see the only solution is to combine wizard points 3+4+5. 

If you have a better solution, please propose it. If not, please combine the three steps and implement the necessary changes in the dashboard check list.

**Comment by niranjan94** [comment]
We could have it such that, if step-3 is turned off, step-4 and 5 will be disabled.

**Comment by mariobehling** [comment]
Yes, but there is more to it, e.g. maybe people want to turn off tracks, but still want speakers to submit. I am not 100% clear about this and the easiest to simplify seems like to merge the points. Also 3 and 4 are not super long. So, that should be ok.

**Comment by mariobehling** [comment]
Please improve the styling of the top bar as well:

![screenshot from 2016-07-23 19 50 54](https://cloud.githubusercontent.com/assets/1583873/17079379/fdf5812a-510e-11e6-93a4-dc2f0fc0e349.png)

**Comment by mariobehling** [comment]
Rename point 3 to "Sessions and Speakers", please.

**Comment by mariobehling** [comment]
Good job, but button still has issues.

![screenshot from 2016-07-23 21 43 20](https://cloud.githubusercontent.com/assets/1583873/17079911/8985549a-511e-11e6-96c7-eb00168e463f.png)

**Comment by niranjan94** [comment]
Will correct it.
