### ISSUE TITLE
Add ETag based caching for PUT APIs

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1757]
Support for GET APIs is being worked on: https://github.com/fossasia/open-event-orga-server/pull/1749

- Add support for PUT APIs.

**Comment by niranjan94** [comment]
Why would you wanna adding caching support for PUT APIs ? Generally, POST, PUT, DELETE APIs will never have caching since they are CUD operations.

**Comment by shivamMg** [comment]
@niranjan94 I was trying to implement conditional PUT requests for concurrency control. Here's a gist: Suppose you create a track with the following data:

```json
{
  "color": "green",
  "track_image_url": "http://website.com/item.ext",
  "description": "string",
  "name": "string",
  "location": "string"
}
```

You (the client) cache this data after it's returned. Now another client saw this resource and made a PUT request to update it. Around the same time you make a PUT request thinking that the server contains your cached data, the update done by another client would now be lost. ETags can help solve this problem. Here, you can read more if you like: http://fideloper.com/etags-and-optimistic-concurrency-control 

But it's becoming more complex (similar thing has to be done for DELETE APIs) and I don't know if I should continue it :confused:

**Comment by shivamMg** [comment]
Ok I'm dropping this for now. It seems to have little benefits. The server would have to do a database fetch for the resource for every PUT and DELETE request to calculate the ETag. The Webapp and android app don't seem to have a requirement such as this. If it's needed later I'll implement it.
