### ISSUE TITLE
Implement a different way to show progress in Import/Export jobs

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1758]
https://github.com/fossasia/open-event-orga-server/issues/1500#issuecomment-232501877

Import/Export jobs can take some time and user should be able to do other things in that scenario. 
As pointed by @mariobehling in #1500, 

> @aviaryan It is all a good idea, but I see that you put out a lightbox window while you generate the export and therefore the user has to wait until it is finished?
I do not think this is a good solution.
Please propose a better solution, e.g. we can have a progress bar in the event table somewhere and when it is finished there is a download link. In the meantime the user can also go to other pages and check later, if the download has finished.
Where is the best place to have this progress bar and download link in the table?

One solution I see is to send an email to user with the download link/event link when their export/import job have been completed. The lightbox (popup) can give the message to the user "Email will be sent to you when this is done". Then the user will have the choice whether to close the lightbox or not. If they close it, they can do other tasks and will still get notified through email.

**Comment by mariobehling** [comment]
@aviaryan Close the lightbox on start export and show a progress bar. See how mailchimp does it.

**Comment by mariobehling** [comment]
Step 1: After clicking what is exported, the "Export Page" can show an export in progress

![screenshot from 2016-07-20 09 00 33](https://cloud.githubusercontent.com/assets/1583873/16977806/a249a076-4e58-11e6-8551-b21f02ef3673.png)

Step 2: As soon as the export is finished and ready for download
* [ ] a) Send out an email
* [ ] b) Show export button on export page

![screenshot from 2016-07-20 09 01 18](https://cloud.githubusercontent.com/assets/1583873/16977830/cad9fa72-4e58-11e6-8841-ae55ca68ebc7.png)

(Compare to mailchimp)

**Comment by mariobehling** [comment]
Here how the email looks like at mailchimp:
![screenshot from 2016-07-20 10 22 37](https://cloud.githubusercontent.com/assets/1583873/16979893/f0c66e18-4e63-11e6-9d61-ca43c743f99e.png)
