### ISSUE TITLE
XSS+Phishing attack

### ISSUE THREAD

**Issue by yasoob** [fossasia/open-event-orga-server#176]
Issue
--------

- Create a file named `test.html` with the following content:

```
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h5>You have hacked</h5>
<script type="text/javascript">window.location.replace('http://yasoob.me')</script>
</body>
</html>
```

- Upload it by going to the [Upload Page](http://localhost:8001/admin/event/upload)
- Open [the Uploaded file](http://localhost:8001/pic/test.html).
- You will be redirected to the website of the uploaders choice. In this case my homepage

The issue is that the uploaded files are globally accessible. Event if I logout I can open [the file](http://localhost:8001/pic/test.html). This allows me to share the file with my colleagues who will click on the link thinking that the domain is legitimate. After that you can redirect them to a fake website.

Solution:
-----------

The files uploaded by a specific user should be uploaded into a separate folder and should only be accessible by that specific user (there should be access restrictions). Or else add `content-disposition` header and make files downloadable by default when opened directly, instead of readable online. :+1:

**Comment by suheb** [comment]
@yasoob You can close this issue. Fix #177
