### ISSUE TITLE
Configure Codacy to follow snake_case convention

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1768]
Looks like a number of error messages from codacy for pull requests come up because we use snake_case convention. Please check how to configure codacy to follow this.

**Comment by SaptakS** [comment]
I have updated the codacy configuration to include snake_case and allow function/method names to be of a maximum length of 50. [ `"[a-z_][a-z0-9_]{2,50}$"` ]

You can see that the naming convention error no more appears in https://github.com/fossasia/open-event-orga-server/pull/1767
