### ISSUE TITLE
Multiple version data being stored for each update in database

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1769]
For each update of an event (wheter in sessions or speakers or tracks etc), the old version data of event is being duplicated and stored with the column increment as a new field.
This should not happen and only one row with latest version information should be stored for an event.

This screenshot will help to understand what I mean to say - 
![duplicate_versions](https://cloud.githubusercontent.com/assets/4047597/17013560/f2ffcd44-4f3c-11e6-8662-feff593cc796.png)

**Comment by mariobehling** [comment]
@aviaryan We have a feature "revisions" which requires that we store some data.

![screenshot from 2016-07-21 09 22 50](https://cloud.githubusercontent.com/assets/1583873/17014414/cbbb2b4c-4f24-11e6-9edb-db5000443fd8.png)


@niranjan94 Please give input and your opinion to the issue here.

**Comment by aviaryan** [comment]
@mariobehling Yes I know. Just to be clear, not storing previous version information will not have any impact on the revisions feature. (I just tested it)
Let's see what @niranjan94 thinks about it .

**Comment by niranjan94** [comment]
I agree with @aviaryan ... This will not affect the revisions functionality... Storing only the latest version number should do.
