### ISSUE TITLE
Update sample event files to latest version

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1786]
Currently, we have some sample event files at https://github.com/fossasia/open-event/tree/master/sample . It seems like some data is not updated yet. 

* [x] Please update the files to the latest version and include version information.
* [x] Test the files by uploading them to the Orga Server
* [x] Export the events from Orga Server and compare if there are differences -> Ensure that files stay the same after import/export

**Comment by mariobehling** [comment]
In the API list, did we include all APIs that are relevant? I see more APIs in the example exports e.g. https://github.com/fossasia/open-event/tree/master/sample/EhealthAfrica

All these APIs are present on the API export page in the orga system, but some of them seem to be bundled together. For example we can find the session_type APIs in the list of Session APIs. 

But why are not they bundled together in the export file?

**Comment by aviaryan** [comment]
> All these APIs are present on the API export page in the orga system, but some of them seem to be bundled together. For example we can find the session_type APIs in the list of Session APIs.
But why are not they bundled together in the export file?

There are 2 ways I see to bundle the session_types file in the sessions.json . 

1. Use separate keys/fields for sessions and session_types in sessions.json . 

Example, in sessions.json - 
```
{
  "sessions": []
  "session_types": []
}
```

**Issue** - This will make the samples very inconsistent with the API and the app-generator and the web-app will have to adjust. So I think we should avoid it.

2. Extract from the sessions data

Example - 
Same as current (without session_types.json). 
We will then extract the session type data from the sessions dictionary. 

**Issue** - Suppose some session_types have been defined for an event which are still not referenced in any session. In that case, when the event is exported, those session types won't be in sessions.json and so will not be imported later. Thus data loss will happen. 

---

The current implementation has no such con. Each file in the import/export zip corresponds to a Database table. It perfectly reflects the API and doesn't have any issues with data loss.

**Comment by mariobehling** [comment]
Ok, good. The whole issue is - we are unclear what is the right file event file. There are 10 sample JSON files in Ehealth Africa, whereas there are 9 in the FOSSASIA sample file. And there are 6 options in the API access, e.g. http://open-event-dev.herokuapp.com/events/85/export/. So, what is missing here and why? Apparently custom forms, which is not a problem, but where is there documentation somewhere, and information why things are done in one or the other way? There were discussions on issues, but you cannot expect everyone to make a deep search into issues. So, the app folks are wondering about this. Could you add some info into the docs folder, please?

**Comment by aviaryan** [comment]
> There are 10 sample JSON files in Ehealth Africa, whereas there are 9 in the FOSSASIA sample file

FOSSASIA sample has 9 because custom_forms.json is missing there.

---

@mariobehling Yes. I too was thinking that a documentation is missing for the import/export feature. I will start working on one now. #1827

**Comment by aviaryan** [comment]
@mariobehling I have updated all 3 samples to the latest version and ensured that they are working. Also I have ensured that files stay the same after import/export. So maybe this can be closed now.

**Comment by mariobehling** [comment]
Ok, great. Thanks.
