### ISSUE TITLE
Accept rating for talk

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-orga-server#179]
System should allow accepting rating & feedback for a session that has become over. 

See issue https://github.com/fossasia/open-event-webapp/issues/106

**Comment by mananwason** [comment]
@rafalkowalski Are you free to work with me on this?

**Comment by SaptakS** [comment]
I would like to assist.

**Comment by creativepsyco** [comment]
This requires some backend work + client.

**Comment by SaptakS** [comment]
I have prior experience in flask and Django. So, wanted to give it a try..

**Comment by creativepsyco** [comment]
yup go ahead. i reckon there will be an authentication mechanism which for simple reasons for now can just be the email of the person.

So:
```bash
POST - "/sessions/:id/reviews" 
body - { 
"email" : "me@example.org",
"rating": 4.0, // can be from 1.0 to 5.0
"comment": "Lorem Ipsum"
}

RESPONSE:
200 OK

GET - "/sessions/:id/reviews"
Response - "
{
"reviews": [{
          "email" : "me@example.org",
          "rating": 4.0, 
         "comment": "Lorem Ipsum"
         },
        // More reviews
        ],
"average": 3.5
"total": 100
// More paging stuff
}
"
```

Some comments:
* We can only fetch the reviews when the person is looking at the session, it doesn't sync
* we can choose to have reviews anonymous (Not review email)
* The client will login from various different sources (Github, Google, Facebook, etc.) and get the email address of the person. This way we don't have to verify the email ourselves.

Hope that helps.

**Comment by aditya1702** [comment]
@creativepsyco  I too would like to help in this

**Comment by mananwason** [comment]
Great @aditya1702. Go ahead !!

**Comment by aayusharora** [comment]
@mananwason ,I would like to work for the client side in it.

**Comment by mananwason** [comment]
@SaptakS @aditya1702 Progress?

**Comment by aditya1702** [comment]
@mananwason had my exams.Just finished.I have started working and will let you know of any progress:)

**Comment by mananwason** [comment]
Great :+1:

**Comment by SaptakS** [comment]
@mananwason  @creativepsyco please check the PR #186 . I have made the necessary functions as suggested by @creativepsyco
