### ISSUE TITLE
Ensure all event data / fields in wizard are covered in APIs and Export JSON

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1798]
We constantly changed the fields and data in the wizard. Some fields like topic do not seem to be covered in the JSON and API.

* [x] Make a list of all fields
* [x] Mark which fields are not covered yet
* [x] Propose where to add the missing fields in APIs and JSON

**Comment by shivamMg** [comment]
@mariobehling Topic and sub-topic fields are covered in the APIs and json sample sets. The Sub-topic field and some other fields were not covered in the API docs however:

Events API: `sub_topic`, `searchable_location_name`, `timezone`, `privacy`, `code_of_conduct`, `copyright`, `call_for_papers`.

Speakers API: `short_biography`, `long_biography`, `mobile`, `website`.

Here's PR covering the same: https://github.com/fossasia/open-event-orga-server/pull/2104

The Ticketing system is available at the wizard but not as an API as discussed here: https://github.com/fossasia/open-event-orga-server/issues/904#issuecomment-236425195
