### ISSUE TITLE
Generate Hash for API authentication

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1806]
- [ ] Assign different API requests to different Roles.
- [ ] Generate Hash/ Secrets according to this roles. 

The idea is using the hash with proper role we can check who can get what level of permission in the API. For example, if someone wants to use only GET request, then he needs to get hash only for that. If he wants access for POST, PUT request then the hash should control that. 

@aviaryan @niranjan94 @mariobehling  I think this is a good idea for monitoring the permission level. What do you think?

**Comment by aviaryan** [comment]
> For example, if someone wants to use only GET request, then he needs to get hash only for that.

@SaptakS Sorry but I don't get why will this be useful.
