### ISSUE TITLE
Mailing access/feature for apps

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1807]
We need to find a way so that the webapp and android app can use the mailing system of the server. 
* I think we can implement the mailing feature along with the API requests. So suppose if there is a POST request for new session, we send the new session mail. 
* However we need to think about the user control settings for the mail.

@niranjan94 @aviaryan @rafalkowalski @mariobehling what are your thoughts?

**Comment by SaptakS** [comment]
@mariobehling the mailing system is already intact with the API. And as of user control, I am not sure how to give user control to the web and android app and what it is supposed to do. Because I don't think we should give user control system to the web and android app to control what happens in server. Can you please clarify?

@championswimmer @mananwason can you share your views on this?

**Comment by mariobehling** [comment]
No, we do not give access to web/Android apps. We give access to the app generators. The idea is that the app generators are placed in a folder of the server and can access features of the system through an internal API, e.g. they trigger an email to inform users, that the app build is finished. Instead of having the generators send out the email, we can add a system mail to our list, that gets triggered.

**Comment by SaptakS** [comment]
@mariobehling generators implement features through the APIs. And the APIs anyhow send emails in case of the actions. So I think this is already resolved as such.

**Comment by mariobehling** [comment]
> And the APIs anyhow send emails in case of the actions. 

How does this work? There are two ways: 1. Generators are stand alone applications with their own email gateways. 2. Generators are plugged in to the orga server. 

In case 2. they should use the email infrastructure of the system. Is this so?

**Comment by SaptakS** [comment]
Yes. In case of 2, they use the email infrastructure of the system. If they want to implement separately they can do that too. But by default it uses the email infrastructure of the orga server.

**Comment by mariobehling** [comment]
Ok, thanks for confirming. Closing it then.
