### ISSUE TITLE
Can there be events without tracks. Logically there is always one track

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1811]
If we switch off tracks, what happens?

* Is there still a schedule?
* So, basically no tracks means there is just one track correct?
* But if there is one track, then should we keep this option "tracks" and take out the option to switch it off?
* What about concerts and other events that do not have other event parts?

I am unclear if we should have the option to switch on/off the event wizard option in step 3.

**Comment by niranjan94** [comment]
> Is there still a schedule?

Yes. there is a schedule. All sessions will be in a single track

> So, basically no tracks means there is just one track correct?

Correct. Main track.

> But if there is one track, then should we keep this option "tracks" and take out the option to switch it off? 

Hmm ... That would be better I guess. 

> What about concerts and other events that do not have other event parts?

I'm not sure about that ... Maybe we can have such that each can be individually switched on/off ? But that would make the form more complex

**Comment by niranjan94** [comment]
Good idea... Will do it right away...
