### ISSUE TITLE
Is it logic to offer switch on/off call for speakers?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1812]
Switching on/off call for speakers, still gives the option of forms. But there is no link in that case on the public page. However, organizers could still fill in speakers themselves.

What is the logic actually? Should we offer to switch on/off Call for Speakers at all?

Should we just offer a button "Call for papers is public/not public"?

**Comment by niranjan94** [comment]
We could make the switch as public/not public

**Comment by mariobehling** [comment]
Ok, sounds good. Then please implement as follows:
* [ ] Take out switch on/off on top of Call for Speakers
* [ ] Add heading "Call for Speakers" (just like in bottom area)
* [ ] Add public/private check switch below "starts/ends" in one line
* [ ] We should also have a link for private submissions then. What do you think?
   * [ ] Best would be to implement a hashkey like http://open-event-dev.herokuapp.com/e/85/cfp/<hash>
   * [ ] Add a line "Private Submission" with a link box like http://open-event-dev.herokuapp.com/e/85/cfp/<hash>
   * [ ] Add help text like the following or similar "Share this link to get private submission independently of open/closed Call for Speakers at any time".

**Comment by niranjan94** [comment]
Will do
