### ISSUE TITLE
Wizard step 3 name: Track option disappeared in forms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1813]
The track option does not show up in forms anymore. We had a dedicated logic to show the track option or not. If we just keep tracks always, we could simplify this and always have the track option in the forms list. Described here https://github.com/fossasia/open-event-orga-server/issues/1811

If we keep the logic as is, then the track should sometimes show up and sometimes not.

At the moment it never shows up.

![screenshot from 2016-07-23 20 26 41](https://cloud.githubusercontent.com/assets/1583873/17079549/0b53410e-5114-11e6-91d3-268278fa4566.png)

**Comment by SaptakS** [comment]
@mariobehling this change was done by me. Since you said that a session must compulsorily have a track always, so I felt giving an option doesn't make any sense. So I removed it and made it compulsory always.

**Comment by mariobehling** [comment]
Ok, makes sense, but in that case, the track option needs to show up nevertheless and it needs to be made enabled and required without the option to change it. Just like title on the top.

![screenshot from 2016-07-23 22 45 49](https://cloud.githubusercontent.com/assets/1583873/17080223/69f6053a-5127-11e6-941b-cc2c3d019e06.png)

**Comment by SaptakS** [comment]
Ok.. Will make that change..
