### ISSUE TITLE
If Email Updates are off ensure admin emails are still sent out

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1820]
There are number of emails, that cannot be switched off. The administrator has the option to switch off the user control. Please test and ensure listings that do not have user control enabled are still sent out.

![screenshot from 2016-07-24 11 01 20](https://cloud.githubusercontent.com/assets/1583873/17082903/36920c7c-518e-11e6-9ec1-998ad838eb07.png)

**Comment by SaptakS** [comment]
I will check that out.

**Comment by mariobehling** [comment]
@SaptakS The emails for registration, lost password and system mails are not showing up anymore in the message list. Why not? https://open-event-dev.herokuapp.com/admin/messages/

**Comment by mariobehling** [comment]
Please ensure all mails - messages - and notification that are sent out or shown by the system show up. But, do not show the buttons to switch off or enable user control. Cheers.
