### ISSUE TITLE
Make FOSSASIA 16 sample importable

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1821]
Parent #1786 

Current FOSSASIA16 sample fails on import. Make it importable.

**Comment by mariobehling** [comment]
Well, we should bring up the FOSSASIA sample to the latest version. Please answer the question in https://github.com/fossasia/open-event-orga-server/issues/1786#issuecomment-234731001

**Comment by aviaryan** [comment]
@mariobehling Yes. I am just doing that.
