### ISSUE TITLE
API/Import/Export: How complete is it?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1825]
In a perfect world, we could export an event and import it again and we would have all the data required. However, if we export private data and add the info elsewhere people might be unhappy. But, we could also leave this to the user.

Please document in this issue: What information is not getting exported and imported or covered in the public APIs, e.g how about email addresses etc. of speakers?

**Comment by aviaryan** [comment]
> However, if we export private data and add the info elsewhere people might be unhappy. But, we could also leave this to the user.

What if we encrypt certain fields. Like in the json, we can export the email, phone etc fields of speakers json encrypted. We don't need to encrypt each and every field. 
When exporting, a key can be asked from the user and using that key, private fields will be encrypted.
When importing, the same key can be asked back from the user to decrypt. 

> Please document in this issue: What information is not getting exported and imported or covered in the public APIs, e.g how about email addresses etc. of speakers?

Right now almost every field is being covered in the public APIs. I agree we need to restrict some data from appearing in the public APIs. Should I create an issue for it ?

**Comment by mariobehling** [comment]
> What if we encrypt certain fields. 

Let's leave this discussion for later.

> Right now almost every field is being covered in the public APIs.

Yes, please create a dedicated issue. Thank you.

**Comment by aviaryan** [comment]
> What information is not getting exported and imported or covered in the public APIs

[ ] Call for Papers Data
[ ] Ticket information

@shivamMg are there more things missing ?

**Comment by mariobehling** [comment]
What about code of conduct?

**Comment by aviaryan** [comment]
code of conduct is included in Event API (event.json).

**Comment by shivamMg** [comment]
@aviaryan Looked at the other models, CallForPapers and Event Tickets seem to be the only ones not covered.
