### ISSUE TITLE
Implement Ticketing on Event Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1839]
Please add a ticketing area on the event page, if organizers add tickets to his event.

![screenshot from 2016-07-24 17 48 58](https://cloud.githubusercontent.com/assets/1583873/17084776/18d196ec-51c7-11e6-9fe8-cb1558852987.png)

**Comment by niranjan94** [comment]
@mariobehling any suggestions for improving this ?

![capture](https://cloud.githubusercontent.com/assets/2404372/17106615/9946df52-52a9-11e6-93eb-6cca91d39f83.PNG)

**Comment by mariobehling** [comment]
Nice. Looks good. Thank you.
