### ISSUE TITLE
Images are not preserved between heroku deployments

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-orga-server#184]
Currently images are not preserved during heroku deployments because its filesystem wipes all file data.

We need to allow wherever we allow file upload to accept URLs for images, files etc.

**Comment by rafalkowalski** [comment]
@creativepsyco Could you check if branch https://github.com/fossasia/open-event-orga-server/tree/issue-184 resolves this issue?

**Comment by creativepsyco** [comment]
Yep no need to store images when we can just store them as urls.

**Comment by creativepsyco** [comment]
Fixed via 45771fd
