### ISSUE TITLE
Make areas in all three steps in Wizard the same width.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1840]
![screenshot from 2016-07-24 17 58 10](https://cloud.githubusercontent.com/assets/1583873/17084816/72d5f2f4-51c8-11e6-929e-9558328e3f65.png)

* [x] Slightly increase width in step 1
* [x] Decrease width of sponsor are in step 2
   * [x] Move area "description" below other areas
* [x] Step 3: Decrease width to match others
   * [x] Make Tracks, Microlocation, and Sessions Types below each other (like in small resolutions)
   * [x] Make "Collect Session Details" and "Collect Speaker Details" below each other (like in small resolutions)

**Comment by niranjan94** [comment]
@mariobehling 

> Make Tracks, Microlocation, and Sessions Types below each other (like in small resolutions)
> Make "Collect Session Details" and "Collect Speaker Details" below each other (like in small resolutions)

It will look too wide if we make then display one below the other

**Comment by mariobehling** [comment]
Please compare to wizard step 1. There are similar elements in one row. You do not need to make it full width, but it is easier for the user to have everything below each other. 

![screenshot from 2016-07-25 15 53 12](https://cloud.githubusercontent.com/assets/1583873/17103720/085cf77a-5280-11e6-82c7-c161a2f66c71.png)

**Comment by niranjan94** [comment]
Alright :+1:  I'll do it like that

**Comment by mariobehling** [comment]
There is a small error in step 2, where there are two horizontal lines on top of each other.

![screenshot from 2016-07-25 17 34 11](https://cloud.githubusercontent.com/assets/1583873/17107109/24de9648-528e-11e6-9c7c-ae49ce6487e7.png)
