### ISSUE TITLE
Wizard Step 1: Let user choose Add Ticket URL or Use Ticketing System

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1841]
If ticketing is enabled, there is now only the choice to use the ticket system. Expected behaviour is;
* [x] If Ticketing module is not enabled offer "Add Ticket URL"
* [ ] If Ticketing module is enabled offer "Switch button":
   * [ ] Button moved to Left: Add Ticket URL
   * [ ] Button moved to Right: Use Ticketing System

**Comment by aditya1702** [comment]
@mariobehling #1674 is also related to this right?

**Comment by mariobehling** [comment]
Yes, thanks. We can also add the tag "Ticketing" to all related issues. Cheers.

**Comment by aditya1702** [comment]
@mariobehling In the above description can we use individual buttons. For example if ticketing module is enabled then we present the user with two options: Either add own ticket url or choose our ticketing system
![2](https://cloud.githubusercontent.com/assets/15054664/17085591/e5005fa0-51f9-11e6-96da-51b50bbb0eee.png)
Just like the above image

**Comment by mariobehling** [comment]
A button like the below one is more suitable and will help to have less elemenst on the screen. Less cluttering therefore.

![screenshot from 2016-07-24 20 44 09](https://cloud.githubusercontent.com/assets/1583873/17085718/7150014c-51df-11e6-9ec6-62ecf19f0fe7.png)

**Comment by aditya1702** [comment]
@mariobehling Ok

**Comment by niranjan94** [comment]
@aditya1702 are you working on this ?

**Comment by aditya1702** [comment]
@niranjan94 Yes
