### ISSUE TITLE
Email system not working

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1843]
#1820

**Comment by SaptakS** [comment]
@mariobehling @aditya1702 @niranjan94 I am not sure but I think none of the emails are being sent. Is this something related to the API token for sendgrid? Could you help me out in this please?

**Comment by niranjan94** [comment]
Yes. Looks like none of the emails are being sent. But I can see that a proper request is being made to sendgrid. Is the token wrong ? Or did we run out of emails ?

**Comment by aditya1702** [comment]
@SaptakS @niranjan94 Can we obtain another sendgrid key?

**Comment by SaptakS** [comment]
@niranjan94 @aditya1702 I tried out in my local system as well with a different token. But it's the same result. I hope mine token didn't run out as well. I think maybe we should try using a new token.

**Comment by SaptakS** [comment]
It was a problem with the sendgrid api token. I have added a new token. I guess we ran out.
