### ISSUE TITLE
Ticketing and Payment Service Research and Proposal

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1848]
What are the next steps to a working ticketing system? Please research how Eventbrite or product services like Wordpress Woocommerce implement payment and product features.

We already have the basic outline, but in order to make this work for organizers we need things like
* accounting features, including receipts with a receipt number
* possibility to charge tax (in some countries a must)
* implement a 3% charge for paid tickets to be paid to the open event service (paypal or stripe) and send out an invoice at the end of the months, which has to be paid until the 15th of the month
* reminders if invoices have not been paid
* send receipts to people who buy tickets
* implement paypal and stripe
* and more

Propose implementations and open issues.

**Comment by niranjan94** [comment]
@mariobehling I have a few doubts regarding this

> reminders if invoices have not been paid 

Don't users have to pay to generate an invoice ? 

> implement a 3% charge for paid tickets to be paid to the open event service (paypal or stripe) and send out an invoice at the end of the months, which has to be paid until the 15th of the month

This 3% charge, we would be automatically adding to the ticket price on each transaction right ? So, what does "_which has to be paid until the 15th of the month_" mean here ?

**Comment by mariobehling** [comment]
@niranjan94 This is just following exactly what Eventnook and Eventbrite are doing. Please try to find the relevant docu on Eventbrite.

**Comment by niranjan94** [comment]
Majority of the features in this parent issue has been completed. Remaining is taken up in #2025. hence I'm closing this now.
