### ISSUE TITLE
Propose and implement a better event url handling

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1850]
Currently we give events a number that is incrementing and we use this number in the URL. The problem with this is, that we release the info about how many events are on the system and it is easy to guess URLs.

Please propose and implement a better URL handling of events.

**Comment by niranjan94** [comment]
@mariobehling we could have a UUID field in the event table and we could retrieve event by that instead of the ID. So, we'll get unpredictable URLs like,

`/e/de305d54-75b4-431b-adb2-eb6b9e546014/`

**Comment by mariobehling** [comment]
@niranjan94 Nice. Can we keep this to 8 digits?

**Comment by niranjan94** [comment]
@mariobehling  UUIDs are generally 32-characters. 
So, I'll think of a shorter alternative and implement it. :+1:
