### ISSUE TITLE
SERVER_NAME in app.config should be generic

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1852]
Right now the `SERVER_NAME` in app.config is set to "open-event-dev.hrokuapp.com" because of which if the code is hosted in any other domain, it is unable to recognize the URL and gives 404.

I think we can set the value using environment variable.

**Comment by aviaryan** [comment]
We can use `request.url_root` in a `before_first_request` function to set this value dynamically.
