### ISSUE TITLE
Page not found on every page 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1855]
Vagrant enviroment 
- [x] find where bug occurs
https://github.com/fossasia/open-event-orga-server/commit/2cb7b930bf65ab7a8ebcb3ffcdb0c887cde08c3a
- [ ] solve bug

**Comment by SaptakS** [comment]
@rafalkowalski issue already reported: #1852 

The easiest way is to set the config value to your own hosted IP.. @aditya1702 is already looking into it I think. So closing this issue.
