### ISSUE TITLE
Test System with thousands of dummy entries

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1861]
In order to understand how the system will perform on a bigger scale we need to test the system in more depth. One way is to generate thousands of dummy entries and test the performance in a dedicated set up (not the automatic deployment on the Heroku server). 

In the admin section that shows events http://open-event-dev.herokuapp.com/admin/events/ it seems like the system is slowing down more than before with even a few entries. What will happen when we have even more entries? What about lots of registered users etc?

Please outline your experience in regards to performance in a test system with a large number of entries and try to find suitable benchmarks to test the speed and resource usage. 

Propose ways to improve performance.

**Comment by aditya1702** [comment]
@mariobehling I have found some ways to display the profiling and coverage of the code. I think it will be usefull for analysing our server 
http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvi-debugging-testing-and-profiling

**Comment by mariobehling** [comment]
Please document how you are checking performance in a Test.md or something.
