### ISSUE TITLE
Improve/Fix Sessions Overview in Admin Section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1867]
The overview in the admin section at http://open-event-dev.herokuapp.com/admin/sessions/ has some issues. Please do the following:

* [x] Speaker/s who submitted session
* [x] Add date of submission
* [x] Take out "Organizer" column

![screenshot from 2016-07-25 21 24 23](https://cloud.githubusercontent.com/assets/1583873/17114295/928690ea-52ae-11e6-98f6-e4dacd7cc106.png)

**Comment by rafalkowalski** [comment]
@mariobehling do you need "who submitted session" column? I ask because I don't understand first point.

**Comment by mariobehling** [comment]
Speakers = Person who submitted session or could be several people who submitted a session.

I do not see this issue done. Where is the info in the columns? If it has not been collected previously one sample should be there to show it is working.

**Comment by mariobehling** [comment]
Server does not have a sample. Column Who submitted is same as "Speaker". Does not make sense to have the same column twice.
