### ISSUE TITLE
API keys for write operations

### ISSUE THREAD

**Issue by leto** [fossasia/open-event-orga-server#187]
This issue was prompted by #186 and @creativepsyco's comment about the need for a shared secret between frontend and backend.

What we need for the mobile/web apps to have a login feature where people give their email/password and then that hits /api/v1/authenticate, which returns the API key if the password is correct. Then to do a write operation the mobile/web apps give that API key as an HTTP header (or some other agreed upon way) when doing write operations. This way allows the backend to check if a given user has the permissions to write to a resource, i.e. one user should not be able to update the review given by another user.

I have most of the code for the /api/v1/authenticate from a previous project, which is the easy part. We will need UI in all the mobile/web apps for creating an account (which also means writing /api/v1/create_account) as well as UI for signing in (which hits /authenticate). We will also need UI for resetting a password with an accompanying API method.

I would love to hear comments from @creativepsyco so we can coordinate things on the frontend (him) and the backend (me) to make this all work.

**Comment by SaptakS** [comment]
I am working on the review functionality. For the time being it isn't authenticating anything, which I accept is wrong. Would love to work on this authentication.

**Comment by aditya1702** [comment]
@leto @creativepsyco do we strictly have to use API keys or can we use other authentication ways also...like OAuth1 , OAuth2 ...?
