### ISSUE TITLE
Restrict GET API output to other users

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1870]
https://github.com/fossasia/open-event-orga-server/issues/1825#issuecomment-235013731

Right now, every data is available in the public GET APIs. This is good but there are certain fields like speaker's email, contact etc which are best kept private i.e. not accessible to users not part of that event. 
Here is the list of fields I found.

1. speaker - email, mobile

**Comment by mariobehling** [comment]
How can we limit access to it? What comes to my mind:
a) API needs an additional hashkey to also put out this data
b) On the export section of events we should have an option to "Include export of private (email, phone numbers, address etc.) in files."

**Comment by aviaryan** [comment]
> a) API needs an additional hashkey to also put out this data

Assuming that only event personnel (organizers, mods etc) should have access to private data, we won't need to do that. There is a way to do it automatically by the API. 

> b) On the export section of events we should have an option to "Include export of private (email, phone numbers, address etc.) in files."

Will exporting event **without** *private data* make sense ? I say this because when the export is further imported, some data will be missing.

**Comment by mariobehling** [comment]
> Will exporting event without private data make sense ?

The use case is: I have an Open Event system on provider A, but I want to move it to provider B. Just like wordpress posts (including all author data with emails) I want to be able to move it completely. I do not want to enter all the emails of speakers again. I want to export the whole data set.
