### ISSUE TITLE
Add "Microservices" to Admin/Settings and other minor changes in Admin section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1875]
Please implement the following:

* [x] Add all relevant data about integrating the app generators (e.g. internal API keys) to a subpage "Microservices" at http://open-event-dev.herokuapp.com/admin/settings/
* [x] Rename "System Links" to "System Tokens"
* [x] At http://open-event-dev.herokuapp.com/admin/settings/ keep subtab 1. System Tokens 2. Microservices
* [x] Create tab "Content" at `admin/content' and move as subtabs: "Social Links" and "Pages"
* [x] Rename "Permission" to "Permissions"
* [x] In all Admin Tabs rename "Update" to "Save" and move "Save" button to bottom right of areas. Also ensure it has same size and style in all tabs.
* [x] Adjust `/admin/modules/` to the style of other pages including font size, boldness or normal, height and style of heading

**Comment by rafalkowalski** [comment]
@mariobehling Can you tell me if I understand you correctly? Can you check below screenshots?

![pages open event](https://cloud.githubusercontent.com/assets/2479753/17188172/4225ae6c-543c-11e6-822f-4cce06bd5503.png)

![microservices open event](https://cloud.githubusercontent.com/assets/2479753/17188040/df23dc8a-543b-11e6-9450-b4859ff717f0.png)

![s_links open event](https://cloud.githubusercontent.com/assets/2479753/17188121/2080df48-543c-11e6-8a1f-8ed26757eb70.png)

**Comment by mariobehling** [comment]
Sorry for unclear issue. I updated the description. Please go through it point by point and rename "System Links" to "System Tokens".

Put Pages and Social Links in one tab with subtabs (not system links).

**Comment by rafalkowalski** [comment]
thanks

**Comment by mariobehling** [comment]
Content page not displaying info on click on "content".

Please test more in detail.

![screenshot from 2016-07-28 21 32 53](https://cloud.githubusercontent.com/assets/1583873/17226722/07b45182-550b-11e6-8c0f-c4b3512c64b8.png)

**Comment by mariobehling** [comment]
Same with Settings: https://open-event-dev.herokuapp.com/admin/settings/

**Comment by rafalkowalski** [comment]
> Add all relevant data about integrating the app generators (e.g. internal API keys) to a subpage "Microservices" at http://open-event-dev.herokuapp.com/admin/settings/

@championswimmer @mananwason Can you provide me which fields do i need to connect with android app and web app?

**Comment by mananwason** [comment]
@rafalkowalski Right now we have an api for the generator but it's using any api keys for now. Let us make the server use this api and generate the apk's. I think this should be the goal, right @mariobehling

**Comment by rafalkowalski** [comment]
@niranjan94 @mananwason @mariobehling @championswimmer What do you think to add a widget, which allow us to generate android app or web app in http://open-event-dev.herokuapp.com/events/96/. We need two buttons "Generate andorid app" and second generate web app

**Comment by mariobehling** [comment]
* [ ] In all Admin Tabs rename "Update" to "Save" and move "Save" button to bottom right of areas. Also ensure it has same size and style in all tabs.

This is still not done in all tabs and should not be marked as done.

**Comment by mariobehling** [comment]
> What do you think to add a widget, which allow us to generate android app or web app in http://open-event-dev.herokuapp.com/events/96/. We need two buttons "Generate andorid app" and second generate web app

This is unrelated to this issue and should be discussed in dedicated issues.

**Comment by rafalkowalski** [comment]
@mariobehling so to microservices tab i will add only links to this pages, because Android and web app don't require any special keys.
