### ISSUE TITLE
Add missing URL in speaker.json

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-orga-server#1877]
The link to speaker's photos are missing in the FOSSASIA16 samples.
[https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/speakers](https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/speakers)
The `photo` field is empty.
Same goes for some of the entries in here
[https://github.com/fossasia/open-event/blob/master/sample/OTS16/speakers](https://github.com/fossasia/open-event/blob/master/sample/OTS16/speakers)

**Comment by mariobehling** [comment]
As you have all the info to fix this quickly, please help to fix it.

**Comment by aayusharora** [comment]
@mariobehling eleven images are null in https://github.com/OpenTechSummit/2016.opentechsummit.net/blob/gh-pages/programm/json/speakers.json . I am in need of spreadsheet with link fixes so that I can run the parser again to have correct jsons.

**Comment by mariobehling** [comment]
@aayusharora You never lost your access to the OpenTechSummit speakers Google doc.

**Comment by mariobehling** [comment]
If the pictures are not available anymore, please implement a generic image.

**Comment by aayusharora** [comment]
@mariobehling ok thanks

**Comment by the-dagger** [comment]
This is fixed in the samples I believe.
