### ISSUE TITLE
Add api endpoint to get dates for the event.

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#1878]
@shivamMg @niranjan94 We need an endpoint to get all the dates of an event. Processing it while downloading sessions takes a massive hit on the performance of the app. We should do it on the server itself. 
When showing the schedule in the app, we need sessions sorted by dates, so I first tried processing dates and getting sessions by these dates, app was freezing due to the db operations. Then I tried with this dates endpoint, it seems to work.

But the best way would be to have an endpoint that gives sessions according to date as well or else something like https://github.com/fossasia/open-event/blob/master/testapi/event/1/eventDates should be okay as well.

Let me know what do you think @mariobehling @shivamMg @niranjan94

**Comment by aviaryan** [comment]
> When showing the schedule in the app, we need sessions sorted by dates, ...........
But the best way would be to have an endpoint that gives sessions according to date as well 

Do you mean that you need an endpoint that returns sessions sorted by their datetime values (like in ascending order or descending order). If that's the case, we can just add some query params to the sessions GET API to do so. Example - 

```
/api/v2/events/1/sessions?order_by=start_time&sort_direction=desc
```

**Comment by mananwason** [comment]
So I don't think this will work. What can work is if you add an endpoint which shows all the dates of an event like done [here](https://github.com/fossasia/open-event/blob/master/testapi/event/1/eventDates) and add query parameters to query sessions by date.

**Comment by aviaryan** [comment]
> What can work is if you add an endpoint which shows all the dates of an event like done here 

Won't the dates of an event be equal to all dates between "event start time" to "event end time" ? Or am I missing something ?

> add query parameters to query sessions by date.

Yes we can add query params like start_time_gt , start_time_lt , end_time_gt , end_time_lt for that. The same has been done in Event GET API. That will suffice your need.

**Comment by mananwason** [comment]
> Won't the dates of an event be equal to all dates between "event start time" to "event end time" ?Or am I missing something ?

Didn't think about this. This should work.

> Yes we can add query params like start_time_gt , start_time_lt , end_time_gt , end_time_lt for that.The same has been done in Event GET API. That will suffice your need.

Awesome 👍

**Comment by mananwason** [comment]
@niranjan94 Is this implemented now?

**Comment by niranjan94** [comment]
@mananwason Sorry ... that was accidental ... On mobile

**Comment by mananwason** [comment]
Np :)

**Comment by aviaryan** [comment]
I am implementing it.

**Comment by mananwason** [comment]
If this is complete, please close the issue @aviaryan. Thanks

**Comment by aviaryan** [comment]
@mananwason It's closed.

**Comment by mananwason** [comment]
@aviaryan Can you tell me how I can access the api's with these query parameters? For example how do we get sessions in the order they occur.

**Comment by aviaryan** [comment]
> For example how do we get sessions in the order they occur.

@mananwason Sorry, that hasn't been implemented. I guess I didn't think that was needed after we agreed to implement https://github.com/fossasia/open-event-orga-server/issues/1878#issuecomment-235225737. I will implement it ASAP and send a PR. I will open a new issue for it that *cleary* states what is to be done. 

---

@mananwason Other query params to filter sessions by start and end time have been implemented. 
Eg > `http://localhost:5000/api/v2/events/1/sessions?end_time_lt=2016-05-05T08%3A00%3A00`
You can see the same in Swagger UI.  http://open-event-dev.herokuapp.com/api/v2/#!/sessions/get_session_list

**Comment by mananwason** [comment]
@aviaryan Thanks. According to what you said in https://github.com/fossasia/open-event-orga-server/issues/1878#issuecomment-235220335, there was a usage of ```sort_direction```  as well. It would be required by me.

**Comment by mananwason** [comment]
@aviaryan Is this working now?

**Comment by aviaryan** [comment]
@mananwason Yes. See PR https://github.com/fossasia/open-event-orga-server/pull/2100

**Comment by mananwason** [comment]
Great @aviaryan. Thanks 👍

**Comment by shivamMg** [comment]
@mananwason @aviaryan Shall I close this now?

**Comment by mananwason** [comment]
Yes @shivamMg. Closing
