### ISSUE TITLE
Links not working on Event View page

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#1889]
Following links give 404 error:

- [x] `http://open-event-dev.herokuapp.com/e/9/sessions/`
- [x] `http://open-event-dev.herokuapp.com/e/9/scheduler/`

@niranjan94 I think this occurs because of the on/off switch in the Step-3 of event wizard. Can you please check?

**Comment by niranjan94** [comment]
Yes. It's because of that. Once step-3 is turned on, it works. See now.

**Comment by SaptakS** [comment]
So that shouldn't be happening, right? If there are sessions, why is step-3 turned off? I am not sure that this isn't a bug. I think if there are sessions already present, then it should be turned on by default? What do you think? @niranjan94

**Comment by niranjan94** [comment]
This isn't a bug. That event was old import. Before this feature was implemented. So the flag has a null value in the database

**Comment by SaptakS** [comment]
Ok. Great.
