### ISSUE TITLE
Ticketing: Accounting and statistics for Admins

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#1899]
Parent issue: #1848. 

We could have the following features for admins

- [ ] Statistics of the ticket sales and revenue 
- [ ] Finance logs that show all the transactions. Along with the option to view the receipt that was sent to the user. 
- [ ] The ability to refund a transaction. ( @mariobehling should this be allowed ? ) 

By statistics, I mean something like this along with numerical statistics display.

![capture](https://cloud.githubusercontent.com/assets/2404372/17179041/5d40037a-5435-11e6-86a9-7234bb35ba25.PNG)

@mariobehling anything more to be added to this ? (this is just for the admin)

**Comment by mariobehling** [comment]
@niranjan94 This is lower priority until we actually have the ticketing system working perfectly. It is enough to show a simple list of ticket sales. But at first we really need a simple process working.
