### ISSUE TITLE
Ticketing: Implement ticketing flow

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#1913]
Parent #1848.

---

- [x] Add a ticketing view for users to choose and buy tickets (#1839)
- [x] When a users presses 'Order Now`, show a summary screen with the total ticket amount (plus Open Event fees added to it). Allow user 10 minutes to complete the registration after which the temporary reservation will be released
- [x] User must fill up details of the buyer (himself/herself) and the information about each ticket holder (this can turned on/off when the ticketing details are entered by the organizer) (name, email, phone). 
- [x] Once that is filled up, handover the user to PayPal or stripe to complete the payment. Once the payment confirmation is received from PayPal or stripe, send the user his/her invoice. 

---

- [ ] If the user started the process and exited it without paying, send him/her a gentle reminder via email that tickets are still available and he can buy them now (if the tickets are available).

**Comment by niranjan94** [comment]
@mariobehling this is based on EventBrite's flow. I think this would be suitable for us too.

**Comment by mariobehling** [comment]
@niranjan94 Very good. Eventbrite offers either "add additional fees to ticket price" (common in US) or "absorb ticket fees" (common in Europe/most of Asia).

They give this choice to the user. Just implement "absorb ticket fees" first and the other option in another issue later. Let's make the flow work first.

Thanks.

**Comment by aditya1702** [comment]
@mariobehling Eventbrite offers multiple tickets for an event. We should also allow users to add multiple tickets to an event.

**Comment by niranjan94** [comment]
@mariobehling this is the order summary page. The page where the user is taken to, before handing over to Paypal or stripe.

![screencapture-localhost-5000-orders-abc-1469725521215](https://cloud.githubusercontent.com/assets/2404372/17221984/baa81d70-5513-11e6-9fe6-5df1dc64c2d3.png)

**Comment by niranjan94** [comment]
This stripe test card can be used to test out the payment flow.

**Credit card number:** `4242424242424242`
**Type:** `Visa`
**CVV:** `123`
**Expiry:** `12/22`

**Comment by mariobehling** [comment]
Well-done!
