### ISSUE TITLE
500 error if not ticket price is set

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1931]
Right now the ticket_price gets set to '' if its not given any value. But since ticket_price is an integer the string cannot be stored in an integer column. Hence we make the ticket_price option compulsory. That is if anyone chooses the paid option he/she will not be able to save the event without setting the ticket_price.

**Comment by mariobehling** [comment]
What is the description? What is the proposed solution?

**Comment by aditya1702** [comment]
@mariobehling Sorry about no description. I have given my views above
