### ISSUE TITLE
Heroku- 500 Internal Server Error (Error in Post deploy scripts)

### ISSUE THREAD

**Issue by phoenix1796** [fossasia/open-event-orga-server#1940]
The official heroku app seems to have an Internal error

Also , when I was trying to deploy the server to heroku , there seemed to be a problem in post-deploy scripts which may be the cause of the internal error in the official heroku app

EDIT : 
@mariobehling 
@rafalkowalski 
If possible , I'd like to help resolve this issue since , we need to start using this application for our event asap.
The Post deploy scripts ran for 5-6 minutes but , after that it showed an error (like in the second ss.)
Screenshots :
![screenshot from 2016-07-30 09-56-11](https://cloud.githubusercontent.com/assets/9111802/17268114/51d82292-563d-11e6-837a-b3abbb1efdbb.png)
![screenshot from 2016-07-30 10-03-43](https://cloud.githubusercontent.com/assets/9111802/17268117/59919400-563d-11e6-8c3b-1aa2529f6b9a.png)

**Comment by mariobehling** [comment]
@phoenix1796 Please describe/post the error in the post-deploy scripts and the info of the internal error in the heroku app.

**Comment by rafalkowalski** [comment]
@phoenix1796 I'm not able to reproduce this bug can you provide some logs?

**Comment by phoenix1796** [comment]
Although , I think there is nothing wrong in the build , but just in case ,
`Build Log :
 !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.

			Detected buildpacks: Python,Node.js

			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order

-----> Python app detected

-----> Installing python-2.7.11

-----> Noticed cffi. Bootstrapping libffi.

     $ pip install -r requirements.txt

       Collecting Flask==0.11.1 (from -r requirements/common.txt (line 1))

         Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)

       Collecting Flask-WTF==0.12 (from -r requirements/common.txt (line 2))

         Downloading Flask_WTF-0.12-py2-none-any.whl

       Collecting Flask-Script==2.0.5 (from -r requirements/common.txt (line 3))

         Downloading Flask-Script-2.0.5.tar.gz (42kB)

       Collecting Flask-SQLAlchemy==2.1 (from -r requirements/common.txt (line 4))

         Downloading Flask-SQLAlchemy-2.1.tar.gz (95kB)

       Collecting Flask-Migrate==1.8.0 (from -r requirements/common.txt (line 5))

         Downloading Flask-Migrate-1.8.0.tar.gz

       Collecting Flask-Admin==1.4.2 (from -r requirements/common.txt (line 6))

         Downloading Flask-Admin-1.4.2.tar.gz (922kB)

       Collecting Flask-Autodoc==0.1.2 (from -r requirements/common.txt (line 7))

         Downloading Flask-Autodoc-0.1.2.tar.gz

       Collecting Flask-Login==0.3.2 (from -r requirements/common.txt (line 8))

         Downloading Flask-Login-0.3.2.tar.gz

       Collecting Flask-Scrypt==0.1.3.6 (from -r requirements/common.txt (line 9))

         Downloading Flask-Scrypt-0.1.3.6.tar.gz

       Collecting Flask-Cors==2.1.2 (from -r requirements/common.txt (line 10))

         Downloading Flask-Cors-2.1.2.tar.gz

       Collecting flask-restplus==0.9.2 (from -r requirements/common.txt (line 11))

         Downloading flask_restplus-0.9.2-py2.py3-none-any.whl (903kB)

       Collecting Flask-JWT==0.3.2 (from -r requirements/common.txt (line 12))

         Downloading Flask-JWT-0.3.2.tar.gz

       Collecting requests-oauthlib==0.6.1 (from -r requirements/common.txt (line 13))

         Downloading requests_oauthlib-0.6.1-py2.py3-none-any.whl

       Collecting boto==2.41.0 (from -r requirements/common.txt (line 14))

         Downloading boto-2.41.0-py2.py3-none-any.whl (1.3MB)

       Collecting icalendar==3.10 (from -r requirements/common.txt (line 15))

         Downloading icalendar-3.10.tar.gz (67kB)

       Collecting requests==2.10.0 (from -r requirements/common.txt (line 16))

         Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)

       Collecting WTForms-Components==0.10.0 (from -r requirements/common.txt (line 17))

         Downloading WTForms-Components-0.10.0.tar.gz

       Collecting WTForms==2.1 (from -r requirements/common.txt (line 18))

         Downloading WTForms-2.1.zip (553kB)

       Collecting colour==0.1.2 (from -r requirements/common.txt (line 19))

         Downloading colour-0.1.2.tar.gz

       Collecting psycopg2==2.6.2 (from -r requirements/common.txt (line 20))

         Downloading psycopg2-2.6.2.tar.gz (376kB)

       Collecting xlrd==1.0.0 (from -r requirements/common.txt (line 21))

         Downloading xlrd-1.0.0.tar.gz (2.6MB)

       Collecting mock==2.0.0 (from -r requirements/common.txt (line 22))

         Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)

       Collecting SQLAlchemy-Utils==0.32.7 (from -r requirements/common.txt (line 23))

         Downloading SQLAlchemy-Utils-0.32.7.tar.gz (116kB)

       Collecting cryptography==1.4 (from -r requirements/common.txt (line 24))

         Downloading cryptography-1.4.tar.gz (399kB)

       Collecting itsdangerous==0.24 (from -r requirements/common.txt (line 25))

         Downloading itsdangerous-0.24.tar.gz (46kB)

       Collecting humanize==0.5.1 (from -r requirements/common.txt (line 26))

         Downloading humanize-0.5.1.tar.gz

       Collecting geoip2 (from -r requirements/common.txt (line 27))

         Downloading geoip2-2.4.0-py2.py3-none-any.whl

       Collecting Flask-HTMLmin (from -r requirements/common.txt (line 28))

         Downloading Flask-HTMLmin-1.2.tar.gz

       Collecting pytz (from -r requirements/common.txt (line 29))

         Downloading pytz-2016.6.1-py2.py3-none-any.whl (481kB)

       Collecting SQLAlchemy-Continuum (from -r requirements/common.txt (line 30))

         Downloading SQLAlchemy-Continuum-1.2.4.tar.gz (73kB)

       Collecting diff-match-patch (from -r requirements/common.txt (line 31))

         Downloading diff-match-patch-20121119.tar.gz (54kB)

       Collecting arrow (from -r requirements/common.txt (line 32))

         Downloading arrow-0.8.0.tar.gz (81kB)

       Collecting unidecode (from -r requirements/common.txt (line 33))

         Downloading Unidecode-0.04.19.tar.gz (204kB)

       Collecting unicode-slugify (from -r requirements/common.txt (line 34))

         Downloading unicode-slugify-0.1.3.tar.gz

       Collecting bleach (from -r requirements/common.txt (line 35))

         Downloading bleach-1.4.3-py2-none-any.whl

       Collecting celery==3.1.23 (from -r requirements/common.txt (line 36))

         Downloading celery-3.1.23-py2.py3-none-any.whl (520kB)

       Collecting redis==2.10.3 (from -r requirements/common.txt (line 37))

         Downloading redis-2.10.3.tar.gz (86kB)

       Collecting apscheduler==3.0.1 (from -r requirements/common.txt (line 38))

         Downloading APScheduler-3.0.1-py2.py3-none-any.whl (47kB)

       Collecting gunicorn==19.6.0 (from -r requirements/prod.txt (line 3))

         Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB)

       Collecting Fabric==1.11.1 (from -r requirements/prod.txt (line 4))

         Downloading Fabric-1.11.1-py2-none-any.whl (91kB)

       Collecting Werkzeug>=0.7 (from Flask==0.11.1->-r requirements/common.txt (line 1))

         Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)

       Collecting Jinja2>=2.4 (from Flask==0.11.1->-r requirements/common.txt (line 1))

         Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)

       Collecting click>=2.0 (from Flask==0.11.1->-r requirements/common.txt (line 1))

         Downloading click-6.6.tar.gz (283kB)

       Collecting SQLAlchemy>=0.7 (from Flask-SQLAlchemy==2.1->-r requirements/common.txt (line 4))

         Downloading SQLAlchemy-1.0.14.tar.gz (4.8MB)

       Collecting alembic>=0.6 (from Flask-Migrate==1.8.0->-r requirements/common.txt (line 5))

         Downloading alembic-0.8.7.tar.gz (968kB)

       Collecting scrypt (from Flask-Scrypt==0.1.3.6->-r requirements/common.txt (line 9))

         Downloading scrypt-0.7.1.tar.gz

       Collecting Six (from Flask-Cors==2.1.2->-r requirements/common.txt (line 10))

         Downloading six-1.10.0-py2.py3-none-any.whl

       Collecting aniso8601>=0.82 (from flask-restplus==0.9.2->-r requirements/common.txt (line 11))

         Downloading aniso8601-1.1.0.tar.gz (49kB)

       Collecting jsonschema (from flask-restplus==0.9.2->-r requirements/common.txt (line 11))

         Downloading jsonschema-2.5.1-py2.py3-none-any.whl

       Collecting PyJWT<1.5.0,>=1.4.0 (from Flask-JWT==0.3.2->-r requirements/common.txt (line 12))

         Downloading PyJWT-1.4.1-py2.py3-none-any.whl

       Collecting oauthlib>=0.6.2 (from requests-oauthlib==0.6.1->-r requirements/common.txt (line 13))

         Downloading oauthlib-1.1.2.tar.gz (111kB)

       Collecting python-dateutil (from icalendar==3.10->-r requirements/common.txt (line 15))

         Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)

       Collecting validators>=0.5.0 (from WTForms-Components==0.10.0->-r requirements/common.txt (line 17))

         Downloading validators-0.10.3.tar.gz

       Collecting intervals>=0.6.0 (from WTForms-Components==0.10.0->-r requirements/common.txt (line 17))

         Downloading intervals-0.8.0.tar.gz

       Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->-r requirements/common.txt (line 22))

         Downloading funcsigs-1.0.2-py2.py3-none-any.whl

       Collecting pbr>=0.11 (from mock==2.0.0->-r requirements/common.txt (line 22))

         Downloading pbr-1.10.0-py2.py3-none-any.whl (96kB)

       Collecting idna>=2.0 (from cryptography==1.4->-r requirements/common.txt (line 24))

         Downloading idna-2.1-py2.py3-none-any.whl (54kB)

       Collecting pyasn1>=0.1.8 (from cryptography==1.4->-r requirements/common.txt (line 24))

         Downloading pyasn1-0.1.9-py2.py3-none-any.whl

       Collecting enum34 (from cryptography==1.4->-r requirements/common.txt (line 24))

         Downloading enum34-1.1.6-py2-none-any.whl

       Collecting ipaddress (from cryptography==1.4->-r requirements/common.txt (line 24))

         Downloading ipaddress-1.0.16-py27-none-any.whl

       Collecting cffi>=1.4.1 (from cryptography==1.4->-r requirements/common.txt (line 24))

         Downloading cffi-1.7.0-cp27-cp27m-manylinux1_x86_64.whl (386kB)

       Collecting maxminddb>=1.2.1 (from geoip2->-r requirements/common.txt (line 27))

         Downloading maxminddb-1.2.1.tar.gz (1.3MB)

       Collecting htmlmin (from Flask-HTMLmin->-r requirements/common.txt (line 28))

         Downloading htmlmin-0.1.10.tar.gz

       Collecting html5lib<0.99999999,>=0.999 (from bleach->-r requirements/common.txt (line 35))

         Downloading html5lib-0.9999999.tar.gz (889kB)

       Collecting billiard<3.4,>=3.3.0.23 (from celery==3.1.23->-r requirements/common.txt (line 36))

         Downloading billiard-3.3.0.23.tar.gz (151kB)

       Collecting kombu<3.1,>=3.0.34 (from celery==3.1.23->-r requirements/common.txt (line 36))

         Downloading kombu-3.0.35-py2.py3-none-any.whl (240kB)

       Collecting tzlocal (from apscheduler==3.0.1->-r requirements/common.txt (line 38))

         Downloading tzlocal-1.2.2.tar.gz

       Collecting futures; python_version < "3.2" (from apscheduler==3.0.1->-r requirements/common.txt (line 38))

         Downloading futures-3.0.5-py2-none-any.whl

       Collecting paramiko<2.0,>=1.10 (from Fabric==1.11.1->-r requirements/prod.txt (line 4))

         Downloading paramiko-1.17.2-py2.py3-none-any.whl (172kB)

       Collecting MarkupSafe (from Jinja2>=2.4->Flask==0.11.1->-r requirements/common.txt (line 1))

         Downloading MarkupSafe-0.23.tar.gz

       Collecting Mako (from alembic>=0.6->Flask-Migrate==1.8.0->-r requirements/common.txt (line 5))

         Downloading Mako-1.0.4.tar.gz (574kB)

       Collecting python-editor>=0.3 (from alembic>=0.6->Flask-Migrate==1.8.0->-r requirements/common.txt (line 5))

         Downloading python-editor-1.0.1.tar.gz

       Collecting functools32; python_version == "2.7" (from jsonschema->flask-restplus==0.9.2->-r requirements/common.txt (line 11))

         Downloading functools32-3.2.3-2.zip

       Collecting decorator>=3.4.0 (from validators>=0.5.0->WTForms-Components==0.10.0->-r requirements/common.txt (line 17))

         Downloading decorator-4.0.10-py2.py3-none-any.whl

       Collecting infinity>=0.1.3 (from intervals>=0.6.0->WTForms-Components==0.10.0->-r requirements/common.txt (line 17))

         Downloading infinity-1.4.tar.gz

       Collecting pycparser (from cffi>=1.4.1->cryptography==1.4->-r requirements/common.txt (line 24))

         Downloading pycparser-2.14.tar.gz (223kB)

       Collecting anyjson>=0.3.3 (from kombu<3.1,>=3.0.34->celery==3.1.23->-r requirements/common.txt (line 36))

         Downloading anyjson-0.3.3.tar.gz

       Collecting amqp<2.0,>=1.4.9 (from kombu<3.1,>=3.0.34->celery==3.1.23->-r requirements/common.txt (line 36))

         Downloading amqp-1.4.9-py2.py3-none-any.whl (51kB)

       Collecting ecdsa<2.0,>=0.11 (from paramiko<2.0,>=1.10->Fabric==1.11.1->-r requirements/prod.txt (line 4))

         Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB)

       Collecting pycrypto!=2.4,<3.0,>=2.1 (from paramiko<2.0,>=1.10->Fabric==1.11.1->-r requirements/prod.txt (line 4))

         Downloading pycrypto-2.6.1.tar.gz (446kB)

       Installing collected packages: itsdangerous, Werkzeug, MarkupSafe, Jinja2, click, Flask, WTForms, Flask-WTF, Flask-Script, SQLAlchemy, Flask-SQLAlchemy, Mako, python-editor, alembic, Flask-Migrate, Flask-Admin, Flask-Autodoc, Flask-Login, scrypt, Flask-Scrypt, Six, Flask-Cors, pytz, python-dateutil, aniso8601, functools32, jsonschema, flask-restplus, PyJWT, Flask-JWT, oauthlib, requests, requests-oauthlib, boto, icalendar, decorator, validators, infinity, intervals, WTForms-Components, colour, psycopg2, xlrd, funcsigs, pbr, mock, SQLAlchemy-Utils, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, humanize, maxminddb, geoip2, htmlmin, Flask-HTMLmin, SQLAlchemy-Continuum, diff-match-patch, arrow, unidecode, unicode-slugify, html5lib, bleach, billiard, anyjson, amqp, kombu, celery, redis, tzlocal, futures, apscheduler, gunicorn, ecdsa, pycrypto, paramiko, Fabric

         Running setup.py install for itsdangerous: started

           Running setup.py install for itsdangerous: finished with status 'done'

         Running setup.py install for MarkupSafe: started

           Running setup.py install for MarkupSafe: finished with status 'done'

         Running setup.py install for click: started

           Running setup.py install for click: finished with status 'done'

         Running setup.py install for WTForms: started

           Running setup.py install for WTForms: finished with status 'done'

         Running setup.py install for Flask-Script: started

           Running setup.py install for Flask-Script: finished with status 'done'

         Running setup.py install for SQLAlchemy: started

           Running setup.py install for SQLAlchemy: finished with status 'done'

         Running setup.py install for Flask-SQLAlchemy: started

           Running setup.py install for Flask-SQLAlchemy: finished with status 'done'

         Running setup.py install for Mako: started

           Running setup.py install for Mako: finished with status 'done'

         Running setup.py install for python-editor: started

           Running setup.py install for python-editor: finished with status 'done'

         Running setup.py install for alembic: started

           Running setup.py install for alembic: finished with status 'done'

         Running setup.py install for Flask-Migrate: started

           Running setup.py install for Flask-Migrate: finished with status 'done'

         Running setup.py install for Flask-Admin: started

           Running setup.py install for Flask-Admin: finished with status 'done'

         Running setup.py install for Flask-Autodoc: started

           Running setup.py install for Flask-Autodoc: finished with status 'done'

         Running setup.py install for Flask-Login: started

           Running setup.py install for Flask-Login: finished with status 'done'

         Running setup.py install for scrypt: started

           Running setup.py install for scrypt: finished with status 'done'

         Running setup.py install for Flask-Scrypt: started

           Running setup.py install for Flask-Scrypt: finished with status 'done'

         Running setup.py install for Flask-Cors: started

           Running setup.py install for Flask-Cors: finished with status 'done'

         Running setup.py install for aniso8601: started

           Running setup.py install for aniso8601: finished with status 'done'

         Running setup.py install for functools32: started

           Running setup.py install for functools32: finished with status 'done'

         Running setup.py install for Flask-JWT: started

           Running setup.py install for Flask-JWT: finished with status 'done'

         Running setup.py install for oauthlib: started

           Running setup.py install for oauthlib: finished with status 'done'

         Running setup.py install for icalendar: started

           Running setup.py install for icalendar: finished with status 'done'

         Running setup.py install for validators: started

           Running setup.py install for validators: finished with status 'done'

         Running setup.py install for infinity: started

           Running setup.py install for infinity: finished with status 'done'

         Running setup.py install for intervals: started

           Running setup.py install for intervals: finished with status 'done'

         Running setup.py install for WTForms-Components: started

           Running setup.py install for WTForms-Components: finished with status 'done'

         Running setup.py install for colour: started

           Running setup.py install for colour: finished with status 'done'

         Running setup.py install for psycopg2: started

           Running setup.py install for psycopg2: finished with status 'done'

         Running setup.py install for xlrd: started

           Running setup.py install for xlrd: finished with status 'done'

         Running setup.py install for SQLAlchemy-Utils: started

           Running setup.py install for SQLAlchemy-Utils: finished with status 'done'

         Running setup.py install for pycparser: started

           Running setup.py install for pycparser: finished with status 'done'

         Running setup.py install for cryptography: started

           Running setup.py install for cryptography: finished with status 'done'

         Running setup.py install for humanize: started

           Running setup.py install for humanize: finished with status 'done'

         Running setup.py install for maxminddb: started

           Running setup.py install for maxminddb: finished with status 'done'

         Running setup.py install for htmlmin: started

           Running setup.py install for htmlmin: finished with status 'done'

         Running setup.py install for Flask-HTMLmin: started

           Running setup.py install for Flask-HTMLmin: finished with status 'done'

         Running setup.py install for SQLAlchemy-Continuum: started

           Running setup.py install for SQLAlchemy-Continuum: finished with status 'done'

         Running setup.py install for diff-match-patch: started

           Running setup.py install for diff-match-patch: finished with status 'done'

         Running setup.py install for arrow: started

           Running setup.py install for arrow: finished with status 'done'

         Running setup.py install for unidecode: started

           Running setup.py install for unidecode: finished with status 'done'

         Running setup.py install for unicode-slugify: started

           Running setup.py install for unicode-slugify: finished with status 'done'

         Running setup.py install for html5lib: started

           Running setup.py install for html5lib: finished with status 'done'

         Running setup.py install for billiard: started

           Running setup.py install for billiard: finished with status 'done'

         Running setup.py install for anyjson: started

           Running setup.py install for anyjson: finished with status 'done'

         Running setup.py install for redis: started

           Running setup.py install for redis: finished with status 'done'

         Running setup.py install for tzlocal: started

           Running setup.py install for tzlocal: finished with status 'done'

         Running setup.py install for pycrypto: started

           Running setup.py install for pycrypto: finished with status 'done'

       Successfully installed Fabric-1.11.1 Flask-0.11.1 Flask-Admin-1.4.2 Flask-Autodoc-0.1.2 Flask-Cors-2.1.2 Flask-HTMLmin-1.2 Flask-JWT-0.3.2 Flask-Login-0.3.2 Flask-Migrate-1.8.0 Flask-SQLAlchemy-2.1 Flask-Script-2.0.5 Flask-Scrypt-0.1.3.6 Flask-WTF-0.12 Jinja2-2.8 Mako-1.0.4 MarkupSafe-0.23 PyJWT-1.4.1 SQLAlchemy-1.0.14 SQLAlchemy-Continuum-1.2.4 SQLAlchemy-Utils-0.32.7 Six-1.10.0 WTForms-2.1 WTForms-Components-0.10.0 Werkzeug-0.11.10 alembic-0.8.7 amqp-1.4.9 aniso8601-1.1.0 anyjson-0.3.3 apscheduler-3.0.1 arrow-0.8.0 billiard-3.3.0.23 bleach-1.4.3 boto-2.41.0 celery-3.1.23 cffi-1.7.0 click-6.6 colour-0.1.2 cryptography-1.4 decorator-4.0.10 diff-match-patch-20121119 ecdsa-0.13 enum34-1.1.6 flask-restplus-0.9.2 funcsigs-1.0.2 functools32-3.2.3.post2 futures-3.0.5 geoip2-2.4.0 gunicorn-19.6.0 html5lib-0.9999999 htmlmin-0.1.10 humanize-0.5.1 icalendar-3.10 idna-2.1 infinity-1.4 intervals-0.8.0 ipaddress-1.0.16 itsdangerous-0.24 jsonschema-2.5.1 kombu-3.0.35 maxminddb-1.2.1 mock-2.0.0 oauthlib-1.1.2 paramiko-1.17.2 pbr-1.10.0 psycopg2-2.6.2 pyasn1-0.1.9 pycparser-2.14 pycrypto-2.6.1 python-dateutil-2.5.3 python-editor-1.0.1 pytz-2016.6.1 redis-2.10.3 requests-2.10.0 requests-oauthlib-0.6.1 scrypt-0.7.1 tzlocal-1.2.2 unicode-slugify-0.1.3 unidecode-0.4.19 validators-0.10.3 xlrd-1.0.0

-----> Discovering process types

       Procfile declares types -> migrate, web

-----> Compressing...

       Done: 55M

-----> Launching...

       Released v5

       https://hacktrec.herokuapp.com/ deployed to Heroku
`

**Comment by phoenix1796** [comment]
This is what i get when trying to access the url on the original open-event-server repo
![screenshot from 2016-07-30 10-14-10](https://cloud.githubusercontent.com/assets/9111802/17268145/657f06b6-563e-11e6-8f6d-402dff013a40.png)

**Comment by aviaryan** [comment]
@phoenix1796 For now, use http://open-event-dev.herokuapp.com/ . It's more updated and it works.
I will look into the case of open-event herokuapp .

**Comment by phoenix1796** [comment]
@aviaryan , you might wanna take a look at initialize.py as it looks like it expects some input(but heroku can't provide input) and it is a part of the post deploy procedure.

**Comment by aviaryan** [comment]
@phoenix1796 @rafalkowalski Fixed the 500 error on open-event. 
Now there is a 404 error. That is because of some issue which has already been fixed in development branch. 

@phoenix1796 Therefore I recommend test deploying the development branch, atleast for now. Follow the heroku instructions (docs/HEROKU.md). I have updated them at #1949

**Comment by phoenix1796** [comment]
@aviaryan , I think you misunderstood , i was talking about deploying the app through the heroku button itself and not the CLI setup ,
@mariobehling ,
@rafalkowalski 
#1955 
I have added the steps that were put in docs/heroku.md into the app.json so as to have a smoother setup experience for anyone :smiley: :+1:

**Comment by phoenix1796** [comment]
Pull Request #1955 merged with inputs from @niranjan94 
Issue Resolved.
Also @aviaryan thank you for fixing and pointing me to the heroku docs :+1:
