### ISSUE TITLE
Limit notifications shown by dropdown list at Navbar

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#1951]
Notification titles listed at Navbar dropdown should be limited to 5 or 6. Long message list disturbs page view.

![screenshot from 2016-07-30 15 07 37](https://cloud.githubusercontent.com/assets/7882752/17269492/618f75bc-5667-11e6-8d57-f7b97dda80d0.png)

**Comment by mariobehling** [comment]
Good job! Thank you.
