### ISSUE TITLE
Make state field in Event API a ChoiceField

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1965]
It should accept only one of the following values - 

```
Draft, Published, Completed, Call for papers
```

Default value should be "Draft".

**Comment by mariobehling** [comment]
Actually what is the difference between Call for Speakers and Published?

**Comment by mariobehling** [comment]
I think there doe not need to be a state "Call for Speakers".

**Comment by aviaryan** [comment]
> I think there doe not need to be a state "Call for Speakers".

@mariobehling Yes, I agree. Will remove Call for Speakers (Call for papers) from the event state .
