### ISSUE TITLE
As a subpage of the ticket tab on the specific event dashboard add "orders" and "attendees"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1978]
An example of an order page is below

![screenshot from 2016-07-31 19 15 19](https://cloud.githubusercontent.com/assets/1583873/17278056/4456341c-5753-11e6-99fb-f38717abadca.png)

An example of an attendee page:

![screenshot from 2016-07-31 19 17 24](https://cloud.githubusercontent.com/assets/1583873/17278063/740f2d9e-5753-11e6-974d-39c93d50f413.png)

**Comment by niranjan94** [comment]
@mariobehling In the attendee page, how would I display in a single person has bought multiple tickets ?  Should I display multiple entries with the same person's name ?

**Comment by mariobehling** [comment]
Here is a sample how it could look like.

![screenshot from 2016-08-01 13 15 03](https://cloud.githubusercontent.com/assets/1583873/17292638/c27c0b4e-57eb-11e6-9509-fbad0d8bd573.png)
