### ISSUE TITLE
Implement an "Add order" page for organizers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1979]
On the ticket tab on the specific event dashboard, please add a button "Add Order", that directs to a page, where organizers can enter tickets themselves as below:

![screenshot from 2016-07-31 19 18 11](https://cloud.githubusercontent.com/assets/1583873/17278077/b0696782-5753-11e6-8049-eca84af8190f.png)

**Comment by niranjan94** [comment]
@mariobehling so the organizer would be taken through the payment process too ?

**Comment by mariobehling** [comment]
The organizer has the option to either enter all payment options as well or choose additionally "Free Order" in the dropdown menu.

In order to be able to choose "Free Order" the organizer needs to "hard-set" the total item cost to 0.00. See below, please.

![screenshot from 2016-08-01 13 33 17](https://cloud.githubusercontent.com/assets/1583873/17292881/f58661fa-57ec-11e6-9dfe-1d22f2fe4b6d.png)
