### ISSUE TITLE
Add tab "System Role Permissions" and a permissions table in Admin section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1990]
The next steps to develop Open Event will require a more fine-grained way to control permissions in the system. We have two kinds of roles a) event roles and b) system roles. Currently there is no listing of permissions of system roles.

At https://open-event-dev.herokuapp.com/admin/permissions/ 
* [x] Create tab "Event Role Permissions"
  * [x] Add role "Attendee" (someone who got a ticket)
* [x] Create a tab "System Role Permissions"
  * [x] Add a table with a list of features
  * [x] Add Role "Anonymous User" (for unregistered users)
  * [x] Add Role "Unverified User" (for registered users, who added their email, but have not confirmed it yet)
  * [x] Add Role "Verified User" (for registered users, who have confirmed their email)
  * [x] Add Role "Sales"
  * [x] Add Role "Admin"
  * [x] Add Role "Super Admin"

**Comment by aviaryan** [comment]
@mariobehling What will be the list of permissions for System Roles ? Here is what I can think of. 

1. Add other admins
2. Modify system settings (includes /admin/settings/ , /admin/messages/, pages and other settings)
3. View logs/reports 

Should I divide "modify system settings" permission into parts or keep it together ?

**Comment by shivamMg** [comment]
@aviaryan You can keep it like Event-Role permissions table. Keep Roles at the leftmost column and other row headers describing the permission. The Permissions can contain permissions to access `super_admin` pages.

**Comment by mariobehling** [comment]
@shivamMg @aviaryan 

Thanks.

> The Permissions can contain permissions to access super_admin pages.

We need even more fine-grained permissions for the admin pages - for each tab.

Think of a "Sales Role" role that can only access the "Sales Tab" for example.

**Comment by shivamMg** [comment]
@mariobehling OK, I'll work on it and give an update here.

**Comment by mariobehling** [comment]
Regarding the table of system roles, please follow the design of the event roles and put "Save" on the bottom right (as in all other admin areas).

**Comment by mariobehling** [comment]
Please also set up the table for user permissions in the same style. Avoid to create a different logic in each new area.

**Comment by mariobehling** [comment]
@shivamMg Please provide screenshots and info how you intend to solve this issue. Please look at existing systems how they deal with permissions. This issue is not only about access to panels. It is about much more. Could you please have a look how Drupal deals with this permissions as an example, please? 

How does the permissions systems look like at Drupal?

**Comment by shivamMg** [comment]
@mariobehling Ok, I'll checkout how drupal does it.

**Comment by shivamMg** [comment]
@mariobehling I read about the drupal permissions and user roles. It allows you to create custom Roles and then lets admins assign the user roles: https://www.drupal.org/node/1803614

I brought this up before in another [issue](https://github.com/fossasia/open-event-orga-server/issues/1901#issuecomment-236349291), although it was related to custom Event-Roles. Shall I implement it for System Roles?

**Comment by mariobehling** [comment]
> Shall I implement it for System Roles?

Yes, please. 

As a first step, please implement the listing/table in the way that drupal does it. It is easier to see what are the permissions.

**Comment by mariobehling** [comment]
Instead of this:

![screenshot from 2016-08-27 08 55 36](https://cloud.githubusercontent.com/assets/1583873/18025766/0da8b926-6c34-11e6-847d-da3f9b7aa40a.png)

Please follow the way Drupal makes this table.

**Comment by niranjan94** [comment]
this issue actually seems to be resolved.
