### ISSUE TITLE
Documents required for running event system

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1991]
In order to make the system wholly functional we also need to get documents up including
- [x] Imprint
- [x] Terms and references that comply with laws
- [x] Copyright Information
- [ ] Documentation - How it works (https://github.com/fossasia/support.eventyay.com/issues)
- [ ] Documentation - FAQ (https://github.com/fossasia/support.eventyay.com/issues)
- [x] Privacy info
- [x] Cookies Info
- [ ] Developers Page

**Comment by bradstimpson** [comment]
Hi Folks, I can help out here.  What document has the highest priority?

**Comment by mariobehling** [comment]
Hi, there is no special priority. Any help is welcome. Thank you!

**Comment by SaptakS** [comment]
@bradstimpson are you still working on this issue?

**Comment by niranjan94** [comment]
Documentation can be added at https://github.com/fossasia/support.eventyay.com/issues.
