### ISSUE TITLE
Test "Copy Event"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1996]
If an event is copied only data to create a new event like all wizard info should be copied. Information like sessions and schedule should not be copied. Please test this thoroughly and file relevant issues if necessary.

**Comment by SaptakS** [comment]
@mariobehling only wizard information is copied. No information except the one provided in the wizard is copied. I will test once whether all the wizard information are copied correctly. But right now no other information is copied.
