### ISSUE TITLE
Create schema

### ISSUE THREAD

**Issue by leto** [fossasia/open-event-orga-server#2]
Create a database schema in a ```models.py``` file which is a representation of the re-data event schema

**Comment by rafalkowalski** [comment]
I created database schema in a models.py, but we need to define columns for Speaker and Session table.

**Comment by leto** [comment]
@rafalkowalski this is a great start! Keep up the good work. Do you have any questions about how to represent the redata schema in SQL? I haven't looked at every detail, so there may be some "fun parts" :smiling_imp:

**Comment by championswimmer** [comment]
The schema I have begun with is not exactly 100% re-data compliant right
now. Trying to keep it simple initially.
Fewer nestings in the json and fewer endpoints for now.
I have taken cues from their API though.

**Comment by leto** [comment]
@championswimmer that is fine. Iterative improvements on simple beginnings is a great plan.

**Comment by championswimmer** [comment]
@rafalkowalski 
I finished the database schema :) 

https://github.com/fossasia/open-event/blob/master/DATABASE.md

**Comment by leto** [comment]
:+1:, closing

**Comment by rafalkowalski** [comment]
Great! I will add it to models.py.  @championswimmer  Could you change in DataBase.md Columns timestart - start_time
timeend -> end_time
loclat -> latitude
loclang -> longitude
locname -> location_name? 

It was not readable for me.

**Comment by rafalkowalski** [comment]
@championswimmer I added the missing models. You can see it here: 
https://github.com/fossasia/open-event-orga-server/commit/5fd7570cfaebbf8d9f1daf0ccc291bbf04790c68

**Comment by championswimmer** [comment]
@rafalkowalski feel free to change the names of columns on DATABASE.md if
you wish to make them more readable.

**Comment by rafalkowalski** [comment]
ok thanks :)
