### ISSUE TITLE
Do not show "Mark Read" Button for "See all notifications"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2015]
See below:

![screenshot from 2016-08-02 20 26 17](https://cloud.githubusercontent.com/assets/1583873/17340204/7ffd56c4-58ef-11e6-9fd4-eb17b3a59ab9.png)

**Comment by shivamMg** [comment]
@mariobehling It's "Mark all read" button so the user doesn't have to click on mark-read buttons for individual notifications. Or perhaps I should make it look different?

**Comment by mariobehling** [comment]
Yes, got it. Cheers.
