### ISSUE TITLE
Create a subtab "Image Options" in Admin/Settings, implement central config location and display options in subtab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2019]
In a subtab "image options" in https://open-event-dev.herokuapp.com/admin/settings/ we can later implement detailed image settings. As a first step list the hardcoded image settings of the different areas with pixel width and height, resolution and compression and define a central place where all image configs are stored.

* [ ] Define and implement place of image config

Display info for config on subtab image options including:
* [ ] Front page event images
* [x] Speaker images on event page 
* [x] Event image in MySessions https://open-event-dev.herokuapp.com/events/mysessions/
* [x] Speaker Images in event dashboard e.g. https://open-event-dev.herokuapp.com/events/85/speakers/
* [ ] Any other location where images are appearing

**Comment by mariobehling** [comment]
Looking at the current implementation at http://open-event-dev.herokuapp.com/admin/settings/, I am unclear if these are maximum widths and if there is any ratio implementation. Are images cropped etc?

Please also sort the subtabs in a logic order e.g. System Tokens, Microservices, Image Configurations, Payment Gateways, Ticket Fees

**Comment by mariobehling** [comment]
There are also a number of pages with images of other sizes missing and while all pages in the admin section have a green save button on the bottom right, it is different here.

I think I mentioned it before: Please look how other systems are doing it, e.g. Wordpress and Drupal.

There are different "category" sizes of images, e.g. Thumbnail, Medium Size, Large Size. If more different sizes are needed e.g. in Drupal you can define your specific custom size. A size that I see we need additionally is for example "Icon".

The strategy would be  to list which pages use "Thumbnails" and then make the thumbnail size configurable.

I see you are missing pages like event pages as well and config pages that have very small icons.

Looking at how you got things doing it seems you did not have investigate how others are doing things. In Wordpress you would see the following though, which would already get us moving forward.

![screenshot from 2016-08-18 17 19 00](https://cloud.githubusercontent.com/assets/1583873/17779545/546ffb4e-6568-11e6-86e8-c552dfe60c56.png)

**Comment by SaptakS** [comment]
@mariobehling  I was also thinking of doing something similar because my implementation would have required saving too many copies of the image. I will get it done asap. Thanks for clearing the concept.

**Comment by mariobehling** [comment]
Thank you. Good step forward!

Please also add all other pages that have images now. What comes to my mind:
* [ ] Profile Image and Speaker Image: The option here should only allow one pixel parameter as height = width
* [ ] Logo in Wizard Step 1
* [ ] Background Image: This one cannot be configured here, but please add the info on the standard height/width on this page

What happens if people upload an image that has a resolution of e.g. 300px? 
* [ ] Have you implemented to  scale that down?

**Comment by mariobehling** [comment]
I just realize that you added the option "Full Size". Actually full size currently means that we have huge images on the site. 
* [ ] We should only keep full size in the system in order to generate other images.
* [ ] Instead of Full Size, please give the option "Large Size"

How to deal with different image sizes:
* [ ] If image is larger than our maximum dimensions scale it down
* [ ] If image is smaller than our maximum dimension do not do anything

**Comment by SaptakS** [comment]
@mariobehling how do I implement Profile image size and logo size. I believe that they do not match any of the 3 options (large, thumbnail, icon). So should I specify separate inputs for them?
And by background image which image do you mean? I am not clear about this. 

As of the resolution and size, I am already scaling down if its more than maximum and not doing anything if its less than maximum. That backend is already implemented for large and thumbnail. I am implementing for the icon.

**Comment by mariobehling** [comment]
@SaptakS Yes, profile and speaker image have their own size. Also here height = width.

**Comment by mariobehling** [comment]
Current implementation results in generation of huge images, e.g. I uploaded a jpg image that has 34KB. Result is a 1.3MB png image is generated. Test at: http://open-event-dev.herokuapp.com/e/29d7c209/

Did you test the current implementation?

Also please specify aspect ration if it is fixed, e.g. heigh 500 and width 200 - is that the aspect ratio? If yes, the aspect ratio should be fixed if sizes are changed.

**Comment by SaptakS** [comment]
The aspect ratio is fixed. And I tested the current implementation as well. Resolution and size wise its reduced.

But what I just noticed is when I upload a 150Kb image, the full size image after cropping is saved as around 2 MB.. Which is then resized and there are 3 images one of 1.2MB, one of 200kb and one of 10kb. I am not sure why a 150 KB image is saved as 2MB.... @niranjan94 can you please tell? Anything to do with croppie or something?

**Comment by niranjan94** [comment]
@SaptakS yes. Croppie upscales all the images which might explain the increase in size. Try tweaking the croppie settings.

**Comment by mariobehling** [comment]
@SaptakS Please try sample settings in Gimp and see what happens. Also read up on the difference between jpg and png. You are converting images from jpg to png and this is one of the major factors here.

Jpg is good for large multi colored images. PNGs these days might sometimes deliver better quality, but the size gets much bigger. PNGs are good for images with less colors and with lots of settings loose less quality (but look at the size). Also Android accepts pngs as logo only. 

* [ ] For the large background images jpg will be the much better option. Even if the original image is png, it will probably be more efficient to convert all copied images to jpg.

* [ ] For the logo you might have to tweak and look. It should propobly be ok to keep png or jpg and just reduce the size if necessary. I recommend to keep the format and reduce the size to what we need e.g. 250 in width or something similar.

And are you sticking to converting all displayed images to the ideal screen image resolution for the web, which is 72 pixels per inch?

* [ ] As the config options have a big influence is there any way to make them visible in the image configurations?

**Comment by SaptakS** [comment]
@mariobehling I understand the difference between jpg and png. But it is  not the reason which causes so much upscaling. It is the coppie plugin which we are using that is causing this. The croppie plugin upscales it a lot.. I will do the modifications for the file formats. But then, we need to check croppie as well for the sizing. @niranjan94 can you help me with this?

**Comment by SaptakS** [comment]
> And are you sticking to converting all displayed images to the ideal screen image resolution for the web, which is 72 pixels per inch?

@mariobehling yes I am using the 72 pixels per inch resolution. 

> As the config options have a big influence, is there any way to make them visible in the image configurations?

I don't understand what you mean by making visible in image configuration.

**Comment by mariobehling** [comment]
@SaptakS Same resolution of jpg to png conversion increases the size of a file a lot. The plugin is the cause, but it does matter which file type you choose.

**Comment by SaptakS** [comment]
@mariobehling the format change is not something which is done during resize either. It happens while cropping and saving as well. So it has nothing to do with resizing of image. I have opened a separate issue for this image upscaling https://github.com/fossasia/open-event-orga-server/issues/2346. Can we follow it up there?

**Comment by mariobehling** [comment]
@SaptakS Please tick all * [ ] points in all comments that are solved.

Also, please ensure the aspect ratio is taken into account in all images as mentioned here: https://github.com/fossasia/open-event-orga-server/issues/2019#issuecomment-241279507

Please ensure all configurations only allow the correct aspect ratio. For example, please reflect the following in the configurations:
* [ ] What is the aspect ratio of the large image on the front page. 
* [ ] What is the aspect ratio of the thumbnails
* [ ] What is the aspect ratio of the icons

**Comment by mariobehling** [comment]
@SaptakS You marked the questions as solved.
> What is the aspect ratio of the large image on the front page.
> What is the aspect ratio of the thumbnails
> What is the aspect ratio of the icons

Where is it solved? What is the aspect ratio? Where is the info in the UI?

The UI is also missing profile speaker info and the info for logo info.

![screenshot from 2016-08-24 10 12 11] https://cloud.githubusercontent.com/assets/1583873/17923362/24e026d0-69e4-11e6-955b-e3c52910f45b.png)

Surely, there could be different implementations for the same issue, but there needs to be some kind of logic implementation that covers the topic (here all issues, all areas, different configurations, aspect ratio, information in help text) of the issue at hand. As the image issues already take several weeks this is probably a blocker now.

Looking at the number of small details that are missing, I believe you need to do more research to solve these issues. There is no point in micro-involving other devs in each detailed question of the issue.

We understand your difficulties with Internet connectivity etc. but in the end at GSoC there needs to be an outcome that works. I wish I would know how to help you to finish it more quickly, but it seems you simply need to look at implementations of other systems. The implementation of a solution for this issue topic can follow standard implementations and there is no need to come up with something absolutely new. I believe there has been enough time to do the necessary research and time for implementation. I hope you can get it done covering the use cases.

**Comment by SaptakS** [comment]
> The UI is also missing profile speaker info and the info for logo info.

![screenshot from 2016-08-24 14 37 52](https://cloud.githubusercontent.com/assets/9530293/17924962/88368b9c-6a08-11e6-8151-d35356e6dbfe.png)

@mariobehling already logo and profile UI are there in the text field.

The default aspect ratio is the width:height mentioned. I will implement the option of forcing or not forcing aspect ratios.

**Comment by mariobehling** [comment]
Posted this screenshot earlier as a reference:

![screenshot from 2016-08-24 10 12 11] (https://cloud.githubusercontent.com/assets/1583873/17923362/24e026d0-69e4-11e6-955b-e3c52910f45b.png)

The expected view in the settings page is to have
a) an overview of all image styles
b) an overview of all pages with images and the info of the position of the image (as some pages have several images)
c) the ratio and resolution info (and help text what is the standard size of the area)
d) other config info as outlined earlier

The profile/speaker image is unclear and missing here, e.g. we have a speaker images in the public page here: http://open-event-dev.herokuapp.com/e/e3e305b0/

![screenshot from 2016-08-24 11 46 19](https://cloud.githubusercontent.com/assets/1583873/17926300/b8ac1476-69f0-11e6-8805-2aa404e99a49.png)

We also have speaker images in the table here:

![screenshot from 2016-08-24 11 47 46](https://cloud.githubusercontent.com/assets/1583873/17926312/c270a63e-69f0-11e6-935d-683bace52ac5.png)

**Comment by mariobehling** [comment]
Currently, aspect ratio is not maintained. If the user clicks the option and changes the ratio, the other part does not change. If you are unsure how this should work look at wordpress.

![screenshot from 2016-08-26 22 20 24](https://cloud.githubusercontent.com/assets/1583873/18019236/6b157bf2-6bdb-11e6-9e58-c68c7e8f293e.png)

**Comment by mariobehling** [comment]
* [ ] What is the actual size of the areas? E.g. Thumbnail size 500px? What is the size of the speaker images area? That should be the standard.

* [ ] Also the image quality should be set to something like 80% or so on standard

![screenshot from 2016-08-26 22 23 05](https://cloud.githubusercontent.com/assets/1583873/18019336/de7aaec8-6bdb-11e6-934b-a4b989a066c2.png)

**Comment by SaptakS** [comment]
@mariobehling yes I know that it doesn't change in the UI... Will have to implement using javascript. But it is maintained in the background... I will make the change in the UI as well..

**Comment by mariobehling** [comment]
Ok, good. 
* [ ] So, please add a help text then below for each image, e.g. "Standard size of the available area is ??px x ??px"

**Comment by SaptakS** [comment]
Ok. Will do that.

**Comment by mariobehling** [comment]
* [ ] Please set the standard to maintain aspect ratio -> "tick" as well. Thank you.

**Comment by SaptakS** [comment]
> Please set the standard to maintain aspect ratio -> "tick" as well.

I didn't understand what this means.

**Comment by mariobehling** [comment]
>> Please set the standard to maintain aspect ratio -> "tick" as well.

> I didn't understand what this means.

It looks like after installation the is no -  ✓- for maintain aspect ratio. Please ensure it is set to yes.

**Comment by SaptakS** [comment]
Ok.. Got it..

**Comment by SaptakS** [comment]
@mariobehling I think this issue can be closed.
