### ISSUE TITLE
Propose and implement flow of organizers to make monthly payments of service fees

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2025]
Let's assume our ticketing has a monthly payment fee of 2.5%. 
* [x] Then we need to sent out an email on the first day of each month with the percentage of the income generated by the organizer with a two week period for the organizer to pay. 
* [x] If the money has not been received by the 15th of the month, we need to send out another email as a reminder.
* [x] For invoicing we should use the payment gateways of paypal and stripe. The gateway/API info should be entered in subtab "Payment Gateways" in `admin/settings`

Please propose and implement a flow to make this happen.

**Comment by niranjan94** [comment]
> Then we need to sent out an email on the first day of each month with the percentage of the income generated by the organizer with a two week period for the organizer to pay.

That wouldn't be an issue. We already have a scheduler in place for After Event emails and auto trash delete.

>  If the money has not been received by the 15th of the month, we need to send out another email as a reminder.

What do we do if an organizer does not pay at all ? 

>  For invoicing we should use the payment gateways of paypal and stripe. The gateway/API info should be entered in subtab "Payment Gateways" in admin/settings

Right now, I have already added Stripe there. Will add paypal too.

**Comment by mariobehling** [comment]
> What do we do if an organizer does not pay at all ?

If an organizer does not pay by the 22nd of a month, we need to block their account.

My idea is: The organizer can still login, but the organizer only has access to the profile and we limit access to the site - no access to events, no access to tickets booked - nothing. Only access to the payment page.

**Comment by niranjan94** [comment]
@mariobehling the `2.5%` is per transaction or per ticket ?

**Comment by mariobehling** [comment]
Per ticket, except for tickets where the maximum is defined differently.
