### ISSUE TITLE
Unnecessary padding for "See all notifications" block at Home page

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#2030]
![screenshot from 2016-08-03 11 00 33](https://cloud.githubusercontent.com/assets/7882752/17354865/db5b1054-5969-11e6-9074-7c1f7154bdc8.png)

This occurs only at homepage, it could be CSS class conflicts.

**Comment by mariobehling** [comment]
Could we make the "Read all" like Facebook? Move it to the top of the area and just use a simple style?

![screenshot from 2016-08-03 08 38 43](https://cloud.githubusercontent.com/assets/1583873/17356152/f870fcb2-5955-11e6-9061-832071cda4a7.png)

**Comment by mariobehling** [comment]
There is no need to show "Show all notifications" twice. No need for the bottom one. It is enough if "Notifications" is mentioned on the top.
