### ISSUE TITLE
Propose a system for help pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2036]
What is the best system for help pages? We need:
- A site that is easy to maintain. 
- Needs to be able to keep pictures
- Easy to update by non tech people
- Nice to have thing is if the user can type something in a search box and get suggestions. 
- Good would be if we could simply host it on Github Pages, but if not possible then it is also ok.

See an example here: http://help.eventnook.com

**Comment by shivamMg** [comment]
We can create our own system, integrated with our own site and put it out at `open-event.com/support`. We can provide a front-end editor for people to add and edit support-articles. The authentication and authorization system can be taken from the organizer server itself. We'll let only the Staff members (Admins and Super Admins) create and edit articles. OR we can create another site-wide role, like `guide_editor` that is only allowed to post and edit articles at the guide. The text editor must have support for rendering images (like the wordpress visual editor). 

Another way to do it, could be using [Pelican](http://docs.getpelican.com/en/3.6.3/). It's a static site generator, mostly used for writing blogs. The content is (generally) written in simple Markdown files and is rendered by Pelican as a website. You can look at http://osuosl.org, it's written in pelican (https://github.com/osuosl/osuosl-pelican). Of course this requires the editor to have knowledge of markdown. Also, I think a separate repo would be required.

Regarding search we can put all our support/help related material under a path (e.g. orga-server.com/support) or a sub-domain like eventnook does. We can then use Google Custom Search. We can also use flask extension to provide search functionality. [Flask-WhooshAlchemy](https://pythonhosted.org/Flask-WhooshAlchemy/) seems to be one. If we go with Pelican, there are some search engine plugins that can be integrated with it.

**Comment by sainiak009** [comment]
@niranjan94 @mariobehling I would like start working on it. My queries are : 

- As suggested by @shivamMg Either we can have our own support system integrated with this project or we can have a separate support system. ? 
-Text Editor can be a simple one with support for rendering images or It can be a markdown editor ?.
- Can we use Google Custom Search or [Flask-WhooshAlchemy](https://pythonhosted.org/Flask-WhooshAlchemy/) ?

**Comment by niranjan94** [comment]
- I'm not sure. I think one integrated with this project ? 
- We could use a simple WYSIWYG Rich text editor like [summernote](http://summernote.org/) 
- WhooshAlchemy looks cool ... 

@mariobehling your views ?

**Comment by mariobehling** [comment]
>  I think one integrated with this project ?

Preferably a solution hosted separately, e.g. at "support.eventyay.com". Features required:
* simple search
* possibly a system that can be hosted on github pages
* easily translatable

What documentation generators are suitable? Any suggestions?

**Comment by sainiak009** [comment]
@niranjan94 @mariobehling : [Nikola](http://nikola.readthedocs.io/en/latest/) and [Pelican](http://docs.getpelican.com/en/3.6.3/) Both seems to be popular for static site generation but I will suggest using Nikola as it is more user-friendly, Nikola's default theme is Bootstrap which we are also using. It supports reStructured, Markdown, plain HTML etc, Github deployment can be done by just a command line. [Plugin](https://plugins.getnikola.com/#localsearch) for search functionality is already there and It is easily translatable too. What are your views ?

**Comment by mariobehling** [comment]
@sainiak009 Thanks for looking into it. Nikola and Pelican both do not use their system for their own documentation. So, in that area they are unfortunately not convincing.

**Comment by sainiak009** [comment]
@mariobehling NIkola uses It's system for it's documentation. Here is the [link](https://getnikola.com/)
Nikola just place It's latest docs at readthedocs but all documentation of nikola can be found [Here](https://getnikola.com/) too.

**Comment by sainiak009** [comment]
@niranjan94 What are your views and suggestions ?

**Comment by niranjan94** [comment]
I guess we're going with Jekyll. Meets all our requirements. 

According to https://github.com/fossasia/support.eventyay.com

So this can be closed.
