### ISSUE TITLE
Ticketing: Width of ticket sales box too small

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2042]
Please see below

![bildschirmfoto 2016-08-04 um 00 20 31](https://cloud.githubusercontent.com/assets/1583873/17384024/7592447a-59d9-11e6-9481-a4fa317c6137.png)

**Comment by mariobehling** [comment]
Ticket box still squeezed and not mobile ready. @SaptakS How should the mobile version look like?

![screenshot from 2016-08-13 11 34 39](https://cloud.githubusercontent.com/assets/1583873/17642514/0d57f698-614a-11e6-84d4-32a5d89cb74b.png)

On smaller screens

![screenshot from 2016-08-13 07 07 14](https://cloud.githubusercontent.com/assets/1583873/17642515/14938558-614a-11e6-8159-4e41777bbe78.png)

**Comment by SaptakS** [comment]
@mariobehling will check on the mobile version.
