### ISSUE TITLE
Confirm before removing ticket at Wizard

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#2044]
* [x] Don't remove the ticket immediately. Ask for confirmation from the user, he could have entered data for the ticket.

![screenshot from 2016-08-01 11 13 39](https://cloud.githubusercontent.com/assets/7882752/17389130/095022c8-5a1f-11e6-8a31-35b6cb46c47d.png)

Edit: Also cover the points below:

**Comment by mariobehling** [comment]
Please implement it as follows:
* [ ] Tickets that have been booked or sold already cannot be deleted.
* [ ] It should be possible to make tickets invisible. So they cannot be sold anymore.
