### ISSUE TITLE
Take out export event button from admin->events

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2059]
Export has been shifted to `/events/ID/export` so take out export option from the admin -> events list.  (/admin/events/)
It doesn't work anyway. 

![export_event_admin](https://cloud.githubusercontent.com/assets/4047597/17411658/c78e22f4-5a96-11e6-8b46-8b02935cd9e8.png)

**Comment by mariobehling** [comment]
Why? It is useful for admins, who want to export several events.

**Comment by mariobehling** [comment]
It was not shifted. The goal is to have it at both places. If it does not work then this is the bug: That it does not work. Actually we need mass export and mass import, but there are so many issues, that this is not a priority. However, please do not take out this option from the admin menu.

**Comment by aviaryan** [comment]
@mariobehling Okay then should I redirect admin to `/events/ID/export` page when they click on that button ? Because exporting is not simple as downloading. It requires some configurations (whether to keep images, audio etc) and can take lots of time to generate the download.

**Comment by mariobehling** [comment]
Yes, true. I did not think of that anymore. We need to implement another process, but we might not have enough time for this during GSoC. Let me open a separate issue with a detailed description later and we check if we can get it done. Especially mass export is interesting here. Closing this then. Cheers!
