### ISSUE TITLE
Google Maps or OpenStreetMaps. Single provider to be used throughout the project.

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#209]
The **New Event** creation form uses Google Maps and the **Microlocation** creation form uses OpenStreetMaps. I think we should choose a single provider and make sure all the maps across the project uses the same provider for consistency. 

My vote is for **Google Maps** :sweat_smile: . But if we're all able to come to a consensus on a provider, I'll be happy to make the required changes and send in a PR.

**Comment by aditya1702** [comment]
@niranjan94  I used Google Maps in order to improve the Search funtionality which is better than the one provided by Openstreet maps. So the Google Maps one will be used.

**Comment by leto** [comment]
@mariobehling what are your feelings on this? I know that some FOSS people have issue with Google Maps and would only want to use OSM, perhaps even if they couldn't use the search functionality.

Should we support only one or make it some kind of config parameter which to use? There may be less functionality if people choose OSM.

Give Mario a few days to answer, at least. I am sure he is extremely busy with the conference right now

**Comment by aditya1702** [comment]
@mariobehling Here we are using the google maps for creating an event and the OSM map for the microlocation page. As @leto  asked , what needs to be done?
