### ISSUE TITLE
500 error on save Admin Modules

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#2090]

**Comment by aditya1702** [comment]
@shivamMg If u try to save the module settings without making any change then it will give an error. Am I right? Or is this another error?

**Comment by shivamMg** [comment]
@aditya1702 Yes it's the same one.

**Comment by mariobehling** [comment]
@shivamMg Please provide description and info in issues. So, we don't have to guess what is the exact case.
