### ISSUE TITLE
Automatically import data (name, user profile photo, phone) from connected FB and Twitter accounts

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2095]
When users login the first time with a user get access to user data of social networks and add their name and other data to their profile. Include:
* [x] Name
   - [x] facebook
   - [x] twitter
* [x] Profile Photo
   - [x] facebook
   - [x] twitter
* [ ] Mobile if relevant
   - [ ] facebook
   - [ ] twitter
* [x] Only fill in info, if it has not been filled in before (Do not overwrite!)
   - [x] facebook
   - [x] twitter

**Comment by rafalkowalski** [comment]
Facebook and twitter API don't provide phone number.
