### ISSUE TITLE
View improvements

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#21]
This bug occurs when we have a lot of data in columns.
It's visible on the below image
![zrzut ekranu 2015-05-26 o 10 42 56](https://cloud.githubusercontent.com/assets/2479753/7808531/316b0c10-0394-11e5-92ba-15d586193ee9.png)

**Comment by rafalkowalski** [comment]
I will show only the columns required

**Comment by rafalkowalski** [comment]
I fixed it

**Comment by mananwason** [comment]
Instead you could limit the width of the column, so that all columns are displayed.

**Comment by rafalkowalski** [comment]
Nice idea @mananwason. I forgot about it :D

**Comment by mananwason** [comment]
Sure :D

**Comment by rafalkowalski** [comment]
In this commit https://github.com/fossasia/open-event-orga-server/commit/1469b3f583ae790515c14cc715e0d0e62a96ed7d , I've written column formatter
