### ISSUE TITLE
Integrate the webapp generator microservice

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#2107]
Hi guys, 
You can add the webapp generator as a microservice to the admin dashboard, so that organisers can generate a static website for their events. All you have to do is use this REST API
https://github.com/fossasia/open-event-webapp/blob/development/docs/REST_API.md 

Host: http://opev-webgen-dev.herokuapp.com 
Endpoint: /generate [POST] 

Parameters: 
**name** : name of app/event (the website will be generated with this name or a slug of it)
**email**: email of organiser. We will send email containing link to download the website on this email id
**datasource**: set this to `eventapi` when integrating to orga-server
**apiendpoint**: api of the event, eg: `https://open-event-dev.herokuapp.com/api/v2/events/9` 

Send data as json or urlencoded. **not** as multi-part form-data.

**Comment by mariobehling** [comment]
@championswimmer @rafalkowalski How would the UI look like to integrate it? Is the event data transferred automatically to the app? What is the flow?

**Comment by rafalkowalski** [comment]
Based on event data from orga-server we can generate web app. 
Flow:

- Click button "Generate Web App" in Apps widget(Event details page)

- If app is generated button "Generate Web App" will be not visible, but we can see a link to preview web App  and possibility to download web App

**Comment by championswimmer** [comment]
@rafalkowalski 

Send a post request to the following endpoint - 

http://opev-webgen-dev.herokuapp.com/generate

Urlencoded body of post request - 
```
email: rafalkowalski@gmail.com
name: MyAwesomeWebapp
datasource: eventapi
apiendpoint: https://raw.githubusercontent.com/fossasia/open-event/master/sample/FOSSASIA16
```

or 

```
email: rafalkowalski@gmail.com
name: MyAwesomeWebapp
datasource: eventapi
apiendpoint: https://open-event-dev.herokuapp.com/api/v2/events/9
```

**Comment by the-dagger** [comment]
@rafalkowalski The steps outlined here are almost the same for Android Generator as well.
Let me know if you face any problem with it :)
