### ISSUE TITLE
Wizard step 1: Improve design of event image/logo section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2118]
The current design was good to get started, but it would be good to move on to a design more similar to existing services.

Current:
![screenshot from 2016-08-08 20 28 22](https://cloud.githubusercontent.com/assets/1583873/17491184/d8d7bcb0-5da6-11e6-8639-bc09c29b5fd3.png)

Desired:
![screenshot from 2016-08-08 20 27 24](https://cloud.githubusercontent.com/assets/1583873/17491190/ddc73764-5da6-11e6-9a71-ff7de821bc4c.png)

**Comment by rafalkowalski** [comment]
@mariobehling it would be nice to have drag and drop feature

**Comment by mariobehling** [comment]
@rafalkowalski Would be nice, but one thing at a time. It is sufficient if we improve the design as a first step.
