### ISSUE TITLE
Remove closing_datetime field from Event model and API

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2119]
[Gitter discussion](https://gitter.im/fossasia/open-event-orga-server?at=57a78b2d48422f8b49771740)

I think that the `closing_datetime` field is not being used anymore. I guess it was added for CFS but then the start and end time were included in CFS model, so this was discontinued. 

##### Why I think it is not being used

I searched `closing_datetime` in the project and found mainly 3 uses. 

1. admin/event/details/steps/draft.html template
2. admin/event/roles/steps/draft.html template
3. save_closing_date(self, event_id) function

All three of them are only defined and not being used. 

Can anyone please confirm .?

**Comment by niranjan94** [comment]
@aviaryan yes. It's unused. It can be removed.

**Comment by aviaryan** [comment]
@niranjan94 ok. thanks for confirming.
