### ISSUE TITLE
What are the currencies that we're going to support ?

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2141]
![capture](https://cloud.githubusercontent.com/assets/2404372/17565571/99c99e5c-5f55-11e6-9a07-a593ed834233.PNG)

Since we're providing two payment Gateways, we'll have to make sure all the currencies that we provide are supported in both the payment gateways. 

The Forex column represents the supported currencies in various Forex APIs. (as we'll need to convert to display the sales on an event-wise basis and for charging the fee)

@mariobehling please share your thoughts regarding this.

**Comment by mariobehling** [comment]
@niranjan94 Thanks for pointing this out. My suggestion: If a currency is not supported by Paypal or Stripe still offer the currency, but deactivate/hide the option for the payment gateway. We want to use this system in India and everywhere.

This implementation would also be useful for the future as we could implement payment gateways for specific currencies. There are payment gateways that are widely used but only available in certain countries.

**Comment by niranjan94** [comment]
> If a currency is not supported by Paypal or Stripe still offer the currency, but deactivate/hide the option for the payment gateway. 

Cool. Will implement the same.
