### ISSUE TITLE
Add Facebook Open Graph and Twitter Cards integration

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#2145]
http://ogp.me
https://dev.twitter.com/cards/overview

Adding these would help us specify what media and text should be shown when an Event URL is shared on Facebook and Twitter. For instance when sharing: https://open-event-dev.herokuapp.com/e/64e50648 on facebook, it should show the Event background image and a brief Event description. Something like this (an eventbrite event): 

![screenshot from 2016-08-11 09 51 44](https://cloud.githubusercontent.com/assets/7882752/17578650/4366bb22-5fa9-11e6-8856-d47cdf60aecf.png)

https://open-event-dev.herokuapp.com/e/64e50648 displays this:

![screenshot from 2016-08-11 09 45 09](https://cloud.githubusercontent.com/assets/7882752/17578660/66d6b06c-5fa9-11e6-9379-de5953965035.png)

* [x] Add Facebook Open Graph Tags
* [ ] Add Twitter Card Tags

**Comment by essank** [comment]
It's look interesting, can help you with it?

**Comment by niranjan94** [comment]
Sure @essank... You can take this issue up. :)

**Comment by niranjan94** [comment]
@essank are you working on the project as a part of [code heat](http://codeheat.org) ?

**Comment by essank** [comment]
@niranjan94 no as Hacktoberfest

**Comment by sainiak009** [comment]
If no one is working on it please assign this issue to me, I want to work on it.

**Comment by niranjan94** [comment]
@sainiak009... @essank is already working on it.

**Comment by essank** [comment]
@niranjan94 this URL:  https://open-event-dev.herokuapp.com/e/64e50648
 it's not working

**Comment by niranjan94** [comment]
@essank probably the event is no longer there. Try a different URL. Like https://open-event-dev.herokuapp.com/e/1cbbfe21/ for example

**Comment by shivamMg** [comment]
@essank The Open Graph tags have already been added. You only need to add Twitter card tags.

**Comment by essank** [comment]
@shivamMg ok I'll

**Comment by shubham-padia** [comment]
@shivamMg Looks like this issue has been idle for sometime. Can i take this up :smile: ?
