### ISSUE TITLE
If ticketing system is used store "ticket URL" of open event server in DB and export/API-access throug URL to server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2159]
If we use the ticketing system, there is no event URL saved in the DB. And therefore if we export the info in the JSON or offer access through the API there is no ticketing link. We need this ticketing link for the generators.

* [x] Implement to store ticket URL on server if ticketing system is used
* [x] Ensure ticket URL is exported and offered through API

**Comment by niranjan94** [comment]
@mariobehling the ticketing URL should be accessible only if the event is Published right ?

**Comment by mariobehling** [comment]
>  the ticketing URL should be accessible only if the event is Published right ?

Yes, good point.
