### ISSUE TITLE
Export speaker images with their full names

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2169]
https://github.com/fossasia/open-event/issues/61#issuecomment-239312104

> Another point is that I see photos are not saved according to names of speakers in the speaker folder for example and there is also an svg file in the speaker folder. Could you export the files as -SpeakergivennameSpeakerfamilyname.png/jpg, please? Please open a dedicated issue.

Since ID of an object is also important when exporting, I propose to export speaker images as 
`ID_FirstnameLastname.ext` . Eg > `2_MarioBehling.jpg` . Also there can be cases where names of 2 speakers are same. This implementation will cover that as well. 
@mariobehling What do you think ?

**Comment by mariobehling** [comment]
Ok, but please add the ID at the end e.g. HongPhucDang_2.ext. Cheers.

Please change this also in the open event sample files. Check that you do not overwrite changes that others have made, please.
