### ISSUE TITLE
Implement analytics plugins and add tab in admin settings section for configuration

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2172]
In order to add analytics capabilities to the server we need key and/or code options for each page. Please implement the following:
* [x] Support for Google Analytics
* [ ] Support for Piwik
* [x] Add keys/config options as a **subtab** "Analytics" in `admin/settings/`

![screenshot from 2016-08-12 11 53 00](https://cloud.githubusercontent.com/assets/1583873/17619129/b52d8238-6083-11e6-9d0a-cf36a0e47a30.png)

**Comment by mariobehling** [comment]
Analytics ID seems to be hard-coded. There is an un-known ID in the code as below.

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58955678-3', 'auto');
  ga('send', 'pageview');

**Comment by SaptakS** [comment]
@mariobehling I am already working on it..

**Comment by mariobehling** [comment]
The user is already clear that he/she is in the settings tabe. Please keep the names short as we will be lacking tab space:
Analytics Configurations -> Analytics

Same would be good with images
Image Configurations -> Images

**Comment by SaptakS** [comment]
@mariobehling as I understand to use Piwik we need to install it first and then use it. Can you please guide me about it? I haven't really used Piwik before.

**Comment by mariobehling** [comment]
Let's postpone this then. Thank you.

**Comment by mariobehling** [comment]
Closing this and will open an issue for Piwik when time has come.
