### ISSUE TITLE
Event role Attendee can see going events at /events, also shown in roles

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2186]
Attendee is able to access the event they have bought the tickets for at /events . 

Also they are shown in the roles list. (I (Avi Aryan) am just an attendee in the following event)

![attendee_roles](https://cloud.githubusercontent.com/assets/4047597/17635947/e09d9baa-60f7-11e6-852c-7289c9dff027.png)

**Comment by mariobehling** [comment]
This issue is also related to https://github.com/fossasia/open-event-orga-server/issues/1990 . Please help to solve this broader issue and enhance control and correct role control.
