### ISSUE TITLE
Change background_url to background_image in event API

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2188]
https://github.com/fossasia/open-event/issues/61

> There is a line "background_url": "/images/background.jpg". This line should be moved above "logo" and renamed "background_image".

The term background_image is more consistent.

**Comment by mariobehling** [comment]
Some open questions remain. Please follow up on comment here: https://github.com/fossasia/open-event/issues/61#issuecomment-242040749

**Comment by aviaryan** [comment]
@mariobehling I think this can be closed now.
