### ISSUE TITLE
Internal Server Error when ordering more than one tickets

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2200]
Internal Server Error when multiple tickets are chosen. (Does not happen when the quantity is changed ... happens only different tickets are selected)

**Comment by aditya1702** [comment]
@niranjan94 Could u tell how to produce this error

**Comment by niranjan94** [comment]
@aditya1702 

1. Goto https://open-event-dev.herokuapp.com/e/47778752/ 
2. Select **Supporter Offer - paid** any quantity
3. Select **Keynote Entry - paid** any quantity
4. Press Order now

**Comment by niranjan94** [comment]
This seems to have been resolved now. Weird. No error or crash.
