### ISSUE TITLE
Export json files without unicode escaping

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2227]
Currently json files in export feature are exported in such a way that unicode chars are escaped. 
See json below for example. (see \u00e9 part) 

```json
{
        "name": "Marco A. Guti\u00e9rrez", 
        "organisation": "Robolab, University of Extremadura, Spain", 
        "photo": "/images/speakers/MarcoA.Guti\u00e9rrez_130.jpg", 
}
```

We can export files in such a way that real unicode chars are printed instead of escaped ones. @mariobehling What do you think ?
I did some research and don't think it has any disadvantages.

**Comment by mariobehling** [comment]
@aviaryan Yes, very good and it would also help to keep it human readable. Thank you.
