### ISSUE TITLE
Add to super admin settings field with email

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#2230]
Email field is neccessary to define, because we don't won't to hardcode email in code

**Comment by souravsingh** [comment]
I would like to take a stab at the issue.

**Comment by SaptakS** [comment]
@souravsingh awesome.

**Comment by niranjan94** [comment]
@souravsingh are you working on the project as a part of [code heat](http://codeheat.org) ?

**Comment by souravsingh** [comment]
@niranjan94 I  am not doing the project as part of code heat. I just want to contribute to FOSSASIA.

**Comment by niranjan94** [comment]
@souravsingh are you still working on this project ? If not, let me know so that I can assign this to someone else
