### ISSUE TITLE
Evaluate, propose and implement set up of robot framework with Selenium

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2233]
[Robot Framework](http://robotframework.org/) is a generic test automation framework for acceptance testing and acceptance test-driven development (ATDD). It has easy-to-use tabular test data syntax and it utilizes the keyword-driven testing approach.

As we have a lot of test cases it seems suitable to automate them with the Robot Framework and possibly with [Selenium](http://www.seleniumhq.org/).

Please propose an and implement a way, best as integrated tests and document how test cases could be added.

**Comment by rafalkowalski** [comment]
Selenium is nice  but we need to improve it -a problem occurs when selenium tries to open browser in vagrant - it can't open. So we should use selenium in a headless state(read an article) [link] (http://www.installationpage.com/selenium/how-to-run-selenium-headless-firefox-in-ubuntu/)

**Comment by mariobehling** [comment]
@rafalkowalski What about setup on Vanilla system (https://github.com/fossasia/open-event-orga-server/issues/1548)? Vagrant is not the only way it should be possible to install the application. If it is installed in other way are these issues persistent? Does it work in the headless state then as well? I do not have experience with this. Who has got input?

**Comment by rafalkowalski** [comment]
@mariobehling I've mentioned Vagrant as an example. i think that if we run it on Vagrant it should work on the other system as well

**Comment by mariobehling** [comment]
Thank you!
