### ISSUE TITLE
clarity on 'timezone' field in API

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#2234]
Hi, 

I wanted a bit of clarity on the `timezone` parameter in sessions and event endpoint.

Does `timezone: PST` mean   

- [ ] event is in PST timezone, all `start_times` and `end_times` of sessions and event are in `UTC`
- [x] event is in PST timezone, all `start_times` and `end_times` of sessions and event are in `PST`

Please let me know

**Comment by rafalkowalski** [comment]
@niranjan94 
I think timezone is in UTC 
>  event is in PST timezone, all start_times and end_times of sessions and event are in UTC

**Comment by niranjan94** [comment]
event is in PST timezone, all `start_times` and `end_times` of sessions and event are in PST

**Comment by championswimmer** [comment]
Wait a sec

Take a look at the following 
```
{
        "audio": null, 
        "comments": "", 
        "end_time": "2016-03-18T02:00:00", 
        "id": 1, 
        "language": null, 
        "long_abstract": "Welcome to the 8th year of FOSSASIA. A friendly community of Open Technologists meets at the Science Centre Singapore.", 
        "microlocation": {
            "id": 1, 
            "name": "Dalton Hall"
        }, 
        "session_type": {
            "id": 1, 
            "length": 0.3, 
            "name": "Welcome"
        }, 
        "short_abstract": "Short Abstract for the event", 
        "signup_url": null, 
        "slides": null, 
        "speakers": [
            {
                "id": 1, 
                "name": "Hong Phuc Dang", 
                "organisation": "FOSSASIA"
            }
        ], 
        "start_time": "2016-03-18T01:30:00", 
        "state": "accepted", 
        "subtitle": null, 
        "timezone": "SGT", 
        "title": "Grand Opening", 
        "track": {
            "id": 1, 
            "name": "OpenTech and IoT"
        }, 
        "video": null
}
```

This means event start time is `2016-03-18T01:30:00` (in UTC).
timezone is `SGT` (singapore time), means, event is hosted in Singapore Time zone. 

That means when displaying, I want
`2016-03-18T01:30:00 UTC in SGT`
which means, I will display
`2016-03-18, 09:30 AM` 

am I correct in assuming all of this ? 
@niranjan94 @mariobehling @rafalkowalski please confirm

**Comment by niranjan94** [comment]
No. The datetime provided in the json is already in the correct timezone. It is not in UTC.

**Comment by championswimmer** [comment]
@niranjan94 no it is not. opening was at 9:30 am not 1:30 am, ofcourse

**Comment by niranjan94** [comment]
@championswimmer that's not right. It's supposed to have the time in the correct timezone. I'll check right now/.

**Comment by niranjan94** [comment]
@championswimmer I think the issue is specific to that event. have a look at this event which I just created right now 

https://open-event-dev.herokuapp.com/api/v2/events/139

The start_time is `2016-10-12T09:00:00`
The end_time is `2016-10-12T18:00:00`
The timezone is `Asia/Kolkata`

**Comment by championswimmer** [comment]
@niranjan94 ok I'll fix the issue in the jsons then
