### ISSUE TITLE
Use local system to store temporary event images

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#2249]
To fix https://github.com/fossasia/open-event-orga-server/issues/2193 I updated the code to download images from AWS if required. The temporary images can be stored just locally instead. It would result in faster implementation since image from elsewhere is not being downloaded.

**Comment by mariobehling** [comment]
I am not clear how/if this would impact running the system on Heroku.

Where could you document this?

**Comment by shivamMg** [comment]
It's regarding the immediate upload of images at the Wizard: https://github.com/fossasia/open-event-orga-server/issues/2050. For create event the images had to be stored in a temporary place, and if the user creates the event the images could be grabbed from the temporary place. If the storage was set to local, getting the uploaded image after the user creates an event was easy since it was on the local file system (in a local directory). But when working with AWS, the uploaded images were stored in the AWS bucket and if the user created the event, the image was first downloaded from there, which took time. My suggestion is to always store these images in the local file system. Since it only needs a temporary place, it really doesn't matter if it's not in the AWS bucket. Downloading image from the AWS bucket to the server will no longer be required. I don't think it would require any documentation, it should be obvious from the code what is being done.
