### ISSUE TITLE
Admin: Sorting of time/dates not correct

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2254]
The sorting of time and dates in admin tables where this is relevant are not correct, e.g. in the users section if I sort according to "member since" the top result is "10 days ago". People who have just registered yesterday appear on a lower point in the list.

Please fix this on all admin tabs and tables.

![screenshot from 2016-08-17 09 35 05](https://cloud.githubusercontent.com/assets/1583873/17728157/2d79afc2-645e-11e6-9c82-ac2c7e66edd4.png)

**Comment by mariobehling** [comment]
Well, it should be implemented in a way that the displayed time format is irrelevant. There should be a unix timestamp or something that is used to sort data. cause as we translate the UI to other languages and there will be different time formats displayed. The way you want to implement it would mean that it could be wrong again.

**Comment by rafalkowalski** [comment]
@mariobehling do you mean for example "1471546321"?

**Comment by mariobehling** [comment]
Of course the UI should stay the same as it is now. The sorting should be correct. So, do not display 1471546321.
