### ISSUE TITLE
I'm an admin but i don't have an access to admin page 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#2268]
https://open-event-dev.herokuapp.com/admin/
![forbidden 403 open event](https://cloud.githubusercontent.com/assets/2479753/17769658/eca843e6-6539-11e6-90fd-437f8079c156.png)

**Comment by shivamMg** [comment]
@rafalkowalski My previous PR required running `populate_db.py` on the server. It included a change to the panel permission name. I've run it, it should be working now.
