### ISSUE TITLE
Proper documentation to run orga-server locally is missing

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2271]
There is no step-by-step documentation for running the app locally. One generally has to consult install.sh, run.sh or any other script in order to figure out the steps. I personally used install.sh to get the server running when I started contributing to this project.
We should create a RUNNING.md in docs/ folder which lists the key steps in proper order required to run the orga-server on one's computer. 

Related #2253

**Comment by mariobehling** [comment]
Please rename doc to "INSTALLATION_LOCAL.md".

**Comment by mariobehling** [comment]
Please also rename other installation docs to "INSTALLATION_-SERVICEHERE-.md".
