### ISSUE TITLE
Admin Dashboard: Activity logs should show "All Activities"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2276]
It looks like mails sent outs are not shown in the main activity tab anymore on http://open-event-dev.herokuapp.com/admin/reports/. They only show up in the mail activity tab.

![screenshot from 2016-08-18 19 10 29](https://cloud.githubusercontent.com/assets/1583873/17783283/aa1e1d5a-6577-11e6-99c1-7a14b43d5a18.png)

**Comment by rafalkowalski** [comment]
@mariobehling Can you check if is it working?

**Comment by mariobehling** [comment]
Yes, great. Thanks.
