### ISSUE TITLE
Disable the Submit button until the image is uploaded 

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#2280]
![screenshot from 2016-08-19 00 02 17](https://cloud.githubusercontent.com/assets/7882752/17786002/92c96bfe-65a0-11e6-9373-e8d71d59534c.png)

**Comment by mariobehling** [comment]
It would be better to allow submitting and ensure the submission is only "completed" until the image has been uploaded. This was the original implementation as well. The difference now is, that the upload of the image could be finished event before the event gets submitted.

**Comment by shivamMg** [comment]
>  the upload of the image could be finished event before the event gets submitted

Yes the image is uploaded immediately and is not sent through the form (on clicking submit). But issue is more about the upload time for the image. It would take time to upload the image from the client to the server, and the user must not submit the form during this time.

**Comment by SaptakS** [comment]
@mariobehling I agree with @shivamMg on this. Disabling the save button is a better option while uploading an image.
