### ISSUE TITLE
"Account Information" in Settings not working

### ISSUE THREAD

**Issue by obnoxious23** [fossasia/open-event-orga-server#2301]
On https://open-event-dev.herokuapp.com/settings/ the link to "Account Information" is not working, loops back to https://open-event-dev.herokuapp.com/settings/contact-info/

Additionally I get an error message in the browser console:
`The connection to wss://open-event-dev.herokuapp.com/socket.io/?EIO=3&transport=websocket&sid=715083fdc99e4394853bef2a8f204f8d was interrupted while the page was loading.`

**Comment by mariobehling** [comment]
@obnoxious23 We have not defined what information goes into the Account Information yet. What are your ideas?

**Comment by obnoxious23** [comment]
No idea ;-).  But either put something in or remove it. Let's leave the issue open until we made a final decision.

**Comment by nikhilrayaprolu** [comment]
@obnoxious23 @niranjan94 any updates regarding this discussion.
If something is finalised I would like to work on this

**Comment by nikhilrayaprolu** [comment]
@obnoxious23 @niranjan94 @mariobehling  so what shall we do with account info tab? what all fields are needed to be implemented in it?
