### ISSUE TITLE
Add all system images to system image settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2308]
Currently a number of images do not show up in the settings at http://open-event-dev.herokuapp.com/admin/content/

Please add images like:
- [x] Top left logo
- [x] Speaker placeholder image
- [x] Profile placeholder image
- [x] Speaker placeholder icon image
- [x] Profile placeholder icon image
- [x] Any other images

Also add:
- [x] A helper text detailing the required standard pixel width/height

The tasks to be completed in this issue are:
- [x] Implement upload/view functionality for all the above mentioned images at `/admin/content/`
- [x] Make sure the application references to the upload images throughout.

**Comment by amitkumarj441** [comment]
@mariobehling I'm willing to take up this issue. Can I add these images?

**Comment by niranjan94** [comment]
@amitkumarj441 you can go ahead :)

**Comment by amitkumarj441** [comment]
@niranjan94 Thanks for your prompt response! Where I can initiate PRs for these images?

**Comment by niranjan94** [comment]
@amitkumarj441 over here https://github.com/fossasia/open-event-orga-server/pulls just like any other PR for this project.

**Comment by niranjan94** [comment]
@amitkumarj441 also, please see `/admin/content/` to know what is expected

**Comment by amitkumarj441** [comment]
Thanks @niranjan94 ! I'll soon initiate some PRs in content!

**Comment by niranjan94** [comment]
@amitkumarj441 what is the progress on this issue ?

**Comment by amitkumarj441** [comment]
Sorry @niranjan94 for late reply!

You haven't updated this issue, we already discussed about this issue.
Please update this issue, so that I can able to make some PRs!

**Comment by niranjan94** [comment]
@amitkumarj441 done. Please proceed.

**Comment by shubham-padia** [comment]
@niranjan94 @mariobehling Can i work on this issue ?
 
I've roughly implemented the points 

> Implement upload/view functionality for all the above mentioned images at /admin/content/

and

> Please add images like

I can start working on 

> Make sure the application references to the upload images throughout.

if i get a go ahead.
Thank You.

**Comment by niranjan94** [comment]
@shubham-padia yes. You can proceed.

**Comment by niranjan94** [comment]
@shubham-padia what's the progress on this issue ?

**Comment by shubham-padia** [comment]
@niranjan94 #2516 has been merged, only testing on the point 

> Make sure the application references to the upload images throughout.

Remains to make sure there aren't any discrepancies .
A third eye would be helpful in testing that :smiley:

**Comment by amitkumarj441** [comment]
@niranjan94 Apologies for the delay! Please let me know if their is anything pending!

**Comment by niranjan94** [comment]
@shubham-padia good work with the progress. But there are a few things I noticed. 

1. [ ] Top left logo is missing
2. [ ] The user placeholder displayed is too big and out of proportions 

![screenshot from 2016-11-08 18 06 41](https://cloud.githubusercontent.com/assets/2404372/20099441/7ef6148c-a5de-11e6-86fd-210488d042b9.png)

3. [ ] The upload dialog box is not displaying the correct dimensions required for the profile placeholder image. The image is too large for a profile image placeholder.
 
![screenshot from 2016-11-08 18 07 11](https://cloud.githubusercontent.com/assets/2404372/20099464/92474eca-a5de-11e6-89ff-fb697e00c993.png)

@amitkumarj441 yourself and @shubham-padia could collaborate on this together.

**Comment by shubham-padia** [comment]
@niranjan94 about 

> Top left logo is missing

Is there a provision for providing the top left logo, because currently it is hardcoded as follows 
![screenshot from 2016-11-08 18-27-22](https://cloud.githubusercontent.com/assets/13910561/20099976/2549cc3c-a5e1-11e6-9891-3981b92b28c3.png)

**Comment by niranjan94** [comment]
@shubham-padia you'll have to make it such that the user can upload a logo image ... The text that is there now is just temporary

**Comment by shubham-padia** [comment]
@niranjan94 can you please update the status of this issue. I believe that discrepancies mentioned in https://github.com/fossasia/open-event-orga-server/issues/2308#issuecomment-259126378 have been solved in #2533 . Thanks !!

**Comment by niranjan94** [comment]
@shubham-padia `Top left logo is missing` is still unsolved

**Comment by shubham-padia** [comment]
@niranjan94 Can we close this :smiley: ?

**Comment by niranjan94** [comment]
Yep. We can close this ! Good job ! :smile:
