### ISSUE TITLE
Implement instructions for offline payments

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2323]
Currently there are options in wizard step 1 for offline payments, but the are instructions are missing.

* [x] Please implement instructions that expand on activation of option as shown below.

![screenshot from 2016-08-20 15 51 31](https://cloud.githubusercontent.com/assets/1583873/17831627/50f0f248-66ee-11e6-83a6-09104a4c4393.png)

* [x] Offer example for cheque payment as shown below.

![screenshot from 2016-08-20 15 52 27](https://cloud.githubusercontent.com/assets/1583873/17831631/664190bc-66ee-11e6-90b1-b72d26030cef.png)

* [x] Offer to example for bank transfer as shown below.

![screenshot from 2016-08-20 15 51 59](https://cloud.githubusercontent.com/assets/1583873/17831637/8355ac92-66ee-11e6-85ec-9401e60cb9e1.png)

* [ ] On the registration page show offline payment instructions when chosen as in example below.

![screenshot-www eventnook com 2016-08-20 15-57-16](https://cloud.githubusercontent.com/assets/1583873/17831658/12ea980e-66ef-11e6-9c8a-050b5772959a.png)

**Comment by aditya1702** [comment]
@niranjan94 Can I help u with this if u dont mind :) ?

**Comment by niranjan94** [comment]
@aditya1702 sure :) .. Which part of this would you like to do ?

**Comment by aditya1702** [comment]
@niranjan94 I will start working on the first point
