### ISSUE TITLE
Internal server error in events super admin panel

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#2334]
ProgrammingError: (psycopg2.ProgrammingError) column settings.analytics_key does not exist
settings.sendgrid_key AS settings_sendgrid_key, settings.a...

**Comment by mananwason** [comment]
@rafalkowalski The server is down right now as well.

**Comment by mariobehling** [comment]
@rafalkowalski Please follow up here as this is the last commit: https://github.com/fossasia/open-event-orga-server/pull/2333
