### ISSUE TITLE
User icon coming from external service

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2335]
It looks like the user icon comes from Google instead from our own service.

![screenshot from 2016-08-21 22 12 15](https://cloud.githubusercontent.com/assets/1583873/17844371/f6ad398a-6838-11e6-9fd5-2a15f13fa9a8.png)

![screenshot from 2016-08-21 22 11 35](https://cloud.githubusercontent.com/assets/1583873/17846907/80b3004e-684b-11e6-8be0-87a385e512f0.png)

**Comment by mariobehling** [comment]
Sorry, but I still see images are downloaded from Google after the merge.

**Comment by aviaryan** [comment]
@mariobehling I just signed in using g+ and the photo is indeed being download to our server. Maybe in you case, it was an old profile. Here is the link I got for my profile image. 

https://opevbucketname.s3.amazonaws.com/users/7/avatar/anZYamExbX/1472539024.83.jpg

**Comment by niranjan94** [comment]
@mariobehling could this issue be closed ?

**Comment by mariobehling** [comment]
Sure.
