### ISSUE TITLE
http://open-event.herokuapp.com/ is a 404

### ISSUE THREAD

**Issue by leto** [fossasia/open-event-orga-server#2341]
This is linked to from README.md

**Comment by mariobehling** [comment]
Thank you. It was a temporary glitch. It is solved.

**Comment by mariobehling** [comment]
Oh looks like the master is not working again while the dev is working http://open-event-dev.herokuapp.com

**Comment by mariobehling** [comment]
Working now :-)

Thanks @niranjan94
