### ISSUE TITLE
Uploading Image increases the size of image

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2346]
[Issue Comment](https://github.com/fossasia/open-event-orga-server/issues/2019#issuecomment-241283072)
https://github.com/fossasia/open-event-orga-server/issues/2306

- [ ] Croppie Upscales Images
- [ ] All images saved in png. JPG to PNG conversion upscales images 

For JPG to PNG conversion, this is what is suggested by @mariobehling :

* [ ] For the large background images jpg will be the much better option. Even if the original image is png, it will probably be more efficient to convert all copied images to jpg.

* [ ] For the logo you might have to tweak and look. It should propobly be ok to keep png or jpg and just reduce the size if necessary. I recommend to keep the format and reduce the size to what we need e.g. 250 in width or something similar.

* [ ] As the config options have a big influence, is there any way to make them visible in the image configurations?

To solve these 2 issues, this issue needs to be solved first. @niranjan94 any idea how to do?

**Comment by niranjan94** [comment]
@SaptakS you could use pillow to first convert the image into jpg. Compensate for the upscaling done by Croppie. Then use the quality parameter of jpg to reduce the file size while maintaining a good quality. I think pillow should be able to do it. I'm not familiar with pillow so I don't know the exact methods.
