### ISSUE TITLE
Set SERVER_NAME in Docker 

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2353]
SERVER_NAME environment variable has been added which specifies the domain name the app is hosted on. docker-compose.yml should allow to set that variable. Also the docs should be updated to take this into account.

**Comment by rafalkowalski** [comment]
@aviaryan can you do it also for Vagrant?

**Comment by aviaryan** [comment]
@rafalkowalski Sorry I am not sure how/where to do it.
