### ISSUE TITLE
After import speakers are shown as pending

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2370]
Should we have the info pending/accepted/rejected?

![screenshot from 2016-08-24 11 35 10](https://cloud.githubusercontent.com/assets/1583873/17925871/f6af71ca-69ee-11e6-87d0-92a5f50505d4.png)

**Comment by aviaryan** [comment]
I have already fixed the issue at https://github.com/fossasia/open-event/pull/80 but have not updated it on the server. 
I have updated it now. Now they don't show as Pending. 

> Should we have the info pending/accepted/rejected?

This info in speakers page shows the status of their proposed sessions. I think we should show it as that will provide the organizer more information about a speaker when looking at the list.
