### ISSUE TITLE
Propose attendees/ticketing API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2385]
With the orga app and the implementation of API endpoints in this PR https://github.com/fossasia/open-event-orga-server/pull/2379 we have the first steps to an attendee API. In how far would that overlap with a ticketing API?

What is the best way to implement this and keep it generic? Do we need two APIs - Attendees and Ticketing or would that be handled in one API?

Also related to https://github.com/fossasia/open-event-orga-server/issues/904

**Comment by niranjan94** [comment]
#### Ticketing API
- [ ] Retrieving the list of available tickets
- [ ] Placing an order
- [ ] Retrieving information about an Order/Payment

#### Attendee API

- [x] Retrieving the list of attendees
- [x] Retrieving information about a particular Attendee
- [x] Check in/Check out of an attendee

@mariobehling So, I don't think we have any overlap.
