### ISSUE TITLE
fix: deleting an event gives error

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#240]
How to produce the error:
1. Create an Event
2. Create a sponsor for that event
3. Now try to delete that event.It will give an Internal Server Error.
This will happen when an event has either a sponsor, session, microlocation ,tracks etc...
It will work successfully if only an event is created. Basically this happens because of the ForeignKey constraint on the sponsor,session ,microlocation,etc... objects which prevent the event from deleting.

**Comment by leto** [comment]
This makes it plainly clear that we need API tests, which would hopefully catch something like this.

**Comment by SaptakS** [comment]
Yes. We do need to write automated tests for the API to ensure that the code doesn't break.
