### ISSUE TITLE
Add background icon, thumbnail, large to Event API

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2407]
https://github.com/fossasia/open-event-orga-server/issues/2403#issuecomment-243029766

> @SaptakS : @aviaryan according to @the-dagger the fields large, thumbnail, icon fields are not present in the API/Import/Export part which are the new resized and re-scaled images. Could you please check that?

**Comment by sainiak009** [comment]
I would like to work on this issue. I have explored event model and export api. I think I got the issue in export api and added required fields in marshaling. I am working on import now and it will be better if anyone can tell me which files I should look for resolving it.

Please assign me for this issue.

**Comment by sainiak009** [comment]
Please review my pull request.
