### ISSUE TITLE
All api endpoints return the same data 

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2423]
The orga-server api needs to return an Array of speakers when called something like this : http://open-event-dev.herokuapp.com/api/v2/events/179?include=sessions,microlocations,tracks,speakers,sponsors,tickets/speakers, but right now it does not return an array , and data from the api always remain same , no matter what the link is, 

e.g http://open-event-dev.herokuapp.com/api/v2/events/179?include=sessions,microlocations,tracks,speakers,sponsors,tickets/speakers and http://open-event-dev.herokuapp.com/api/v2/events/179?include=sessions,microlocations,tracks,speakers,sponsors,tickets/sessions
are providing the same data right now.

After having a look at the data, it seems that all of the event data ( including the speakers, sessions array etc) is returned for all api calls

**Comment by aviaryan** [comment]
@shubham-padia There is nothing wrong. 

> The orga-server api needs to return an Array of speakers when called something like this : http://open-event-dev.herokuapp.com/api/v2/events/179?include=sessions,microlocations,tracks,speakers,sponsors,tickets/speakers,

To get an array of speakers you do http://open-event-dev.herokuapp.com/api/v2/events/179/speakers

----

URLs like the one you have posted above ( http://open-event-dev.herokuapp.com/api/v2/events/179?include=sessions,microlocations,tracks,speakers,sponsors,tickets/speakers ) are getting into the Event API and so the return is like that. If you want Event API information along with array of speakers, you do 

http://open-event-dev.herokuapp.com/api/v2/events/179?include=speakers

Hope it is clear. Let me know if you have doubts.

**Comment by shubham-padia** [comment]
@aviaryan Thank you very much :smile: . The buttons to include sessions, speakers, etc at the export page on the orga-server got me confused and i thought that the link :
http://open-event-dev.herokuapp.com/api/v2/events/179?include=sessions,microlocations,tracks,speakers,sponsors,tickets/speakers
has to be provided to the webapp.
