### ISSUE TITLE
Content type of images stored in AmazonS3 bucket is `application/octet-stream`

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2424]
e.g.
https://opevbucketname.s3.amazonaws.com/events/179/speakers/1263/photo/MFhNSk9yRU/HansBakker_111.jpg has the content type `application/octet-stream` instead of `image/jpeg`.

Following is the response header for the specified file:

```
Accept-Ranges →bytes
Content-Disposition →attachment; filename=HansBakker_111.jpg
Content-Length →56060
Content-Type →application/octet-stream
Date →Fri, 09 Sep 2016 10:51:06 GMT
ETag →"964b1d839a9261fb0b159e960ceb4cf9"
Last-Modified →Tue, 06 Sep 2016 05:06:23 GMT
Server →AmazonS3
x-amz-id-2 →1GnO0Ta1e+qUE96Qgjm5ZyfyuhMetjc7vfX8UWEsE4fkZRBAuGx9gQwozidTroDVO/SU3BusCZs=
x-amz-request-id →ACF274542E950116
```

**Comment by aviaryan** [comment]
@shubham-padia Are you aware of a reliable way to extract the content type information from a file in Python ? To fix this issue, we will have to set Content-Type header when uploading the file to S3 using boto. This [answer on SO](http://stackoverflow.com/a/33445129/2295672) makes it clear. 
The only question that remains is how to get the Content-Type. 

Uploaded files can be of many types like `pptx, pdf, jpg, png, mp4, mkv, mpg, ogg, mp3, m4a ` etc..

**Comment by shubham-padia** [comment]
@aviaryan  Maybe this : https://github.com/ahupp/python-magic can do the required task.

**Comment by shubham-padia** [comment]
@aviaryan Apologies for the delay, currently busy with my exams right now :sweat_smile:  .
Please review #2440.
