### ISSUE TITLE
Placeholder images for subtopics not shown.

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2425]
Placeholder images for subtopics are not shown in event thumbnails in the home page.
![screenshot from 2016-09-12 14 02 27](https://cloud.githubusercontent.com/assets/9530293/18429548/a56ad2c0-78f1-11e6-9b6c-10c6a07b7ec3.png)

**Comment by IamAdiSri** [comment]
Can you explain this issue? Which image exactly is it that's missing?

**Comment by SaptakS** [comment]
@IamAdiSri as you can see in the above event, the subtopic/topic mentioned is Auto, Boat and Air. In [system images page](http://open-event-dev.herokuapp.com/admin/content/) we have specified the images default for particular topics and subtopics. So the image particular for this subtopic/topic should be shown.

**Comment by IamAdiSri** [comment]
Thanks. I was able to recreate the bug. I would like to try to solve this; how should I go about doing so?

**Comment by SaptakS** [comment]
@IamAdiSri you need to go to the folder `templates/gentelella/index.html` and fix the jinja2 if condition for the `<img>` tag. That should fix the error. Just play around with it.

**Comment by IamAdiSri** [comment]
I believe I've Identified the erroneous block of code. Will try to debug now. Can this issue be assigned to me?

**Comment by sainiak009** [comment]
I have resolved the issue.

@SaptakS Please review my pull request : #2441 

Screenshot:
![screenshot 26](https://cloud.githubusercontent.com/assets/13566432/18898036/861f8a70-854c-11e6-864e-19ffbd0bbdbb.png)

**Comment by IamAdiSri** [comment]
I've created a pull request with the fix for this bug at #2442

**Comment by SaptakS** [comment]
@IamAdiSri thanks for the fix. Next time please also provide a screenshot of the outsome of your fix. That helps everyone to review better. Thanks.

**Comment by IamAdiSri** [comment]
@SaptakS Sure thing. Thanks.
