### ISSUE TITLE
chore: set up travis-ci

### ISSUE THREAD

**Issue by juslee** [fossasia/open-event-orga-server#243]
Require setting up of travis ci

**Comment by aviaryan** [comment]
@rafalkowalski Isn't the code incompatible with Python 3 (because of print statements). If so, it would be better to remove python 3 from .travis.yml and let's just concentrate on python 2.6 and **2.7** for now.

**Comment by aviaryan** [comment]
@juslee I have managed to get travis CI out of build error. Build is working fine now. 
On the other hand, 7 tests are failing both locally and on travis cloud but that can be fixed. 
Here is the log https://travis-ci.org/aviaryan/open-event-orga-server/builds/123264147
I will open a PR with the changes.
