### ISSUE TITLE
Increase space between map and adress

### ISSUE THREAD

**Issue by jainaman224** [fossasia/open-event-orga-server#2434]
I think there should be some space between map and address.

![screenshot from 2016-09-22 17-56-01](https://cloud.githubusercontent.com/assets/13117482/18754183/64cae1da-8105-11e6-920a-1f83d6d46a8c.png)

**Comment by jainaman224** [comment]
@mariobehling please provide your feedback.
How does it look now...?
![ss](https://cloud.githubusercontent.com/assets/13117482/18809588/46d0b634-829d-11e6-9bed-77002c807d90.png)

**Comment by mariobehling** [comment]
Thank you. nice.
