### ISSUE TITLE
Shift from Dockerfile to Docker Compose

### ISSUE THREAD

**Issue by DengYiping** [fossasia/open-event-orga-server#2436]
I have implement Dockerfile during GCI, and I believe it is time for us to switch to Docker Compose. Docker Compose will separate the database and the container, and this application will be more maintainable. 

I certainly can do that, but as a mentor of Codeheat, I think it is better to leave this task to Codeheat participants. And if this task is pending for a long time, I will do it by myself.

It should be a straight forward task:
- Modify Dockerfile and remove the database setup
- Add docker-compose file, expose the port, link with database

**Comment by aviaryan** [comment]
It has been removed. Please check. I migrated Dockerfile to Docker compose in this GSOC.

**Comment by amitkumarj441** [comment]
@DengYiping I just exposed the port in docker compose file and added the Postgres volume.

**Comment by DengYiping** [comment]
It’s fine, I didn’t see there is a docker-compose file @amitkumarj441

**Comment by amitkumarj441** [comment]
@DengYiping Please have a look into the docker-compose file [77f7dd2](https://github.com/fossasia/open-event-orga-server/commit/77f7dd2380dec51d0b277b84bdd3bec51c3cb4f1)
