### ISSUE TITLE
Set up event server on Google Cloud and document it

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2439]
Please add documentation how to set up the server on Google Cloud here:
https://github.com/fossasia/open-event-orga-server/blob/development/docs/INSTALLATION_GOOGLE.md

**Comment by addiittya2006** [comment]
Google Cloud Platform offers multiple options for Deploying a Web App like App Engine, Compute Engine and Container Engine too.
What kind of a Deployment are we looking for here as Deploying on Compute Engine would be pretty much similar to Deploying on an AWS EC2 Instance?

**Comment by aviaryan** [comment]
Google Container Engine looks to be the most appropriate choice here but using Compute Engine should also work. You can use whatever you prefer. As you say that Compute Engine will be pretty much similar to EC2, it's best that we first start with Compute Engine and then later we can try deploying with Container Engine.

**Comment by essank** [comment]
@mariobehling if no one take it, I would like to help with it

**Comment by mariobehling** [comment]
Ok, great. Please also accept my invite to the codeheat team and we will be able to assign you. Cheers.

**Comment by addiittya2006** [comment]
I have successfully deployed it on GCE, as soon as I prepare a guide, I will send a PR

**Comment by aviaryan** [comment]
@addiittya2006 Did you use Docker ? Can you share the url so that we can test ?

**Comment by addiittya2006** [comment]
Yes, I did use Docker, The Deployment was Successful as supposed but I am still not able to get it fully done. Looking into it.

**Comment by addiittya2006** [comment]
Got this working at http://104.155.189.188/

**Comment by jig08** [comment]
@addiittya2006 Cool, sent a PR referencing this issue ?

**Comment by addiittya2006** [comment]
Soon.

**Comment by amitkumarj441** [comment]
Seems this issue is almost resolved, @aviaryan Let me know if I can assist this issue anyway.
