### ISSUE TITLE
Port project to Python 3

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2447]
https://github.com/fossasia/open-event-orga-server/issues/2433#issuecomment-250423863

> we have to port Open Event to Python 3 because PSF has declared that it would withdraw all support for Python 2 in less than 1000 days. Though I agree that it is not a High:Priority Task now but finally we will have to port it to Python 3.

Python 2 will soon approach its end of life and that can be a huge problem for our application. On the other hand, porting to Python 3 shouldn't require much changes as not much syntax has changed from 2 to 3 ([see a list of changes](http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html)). 
Also Python 3 by default supports Unicode strings and this can help mitigate a lot of unicode-text related issues. Overall, upgrading to Python 3 looks like a good decision. 

In this issue, please work on porting the application to Py 3.

Also update the Python references in the following (please add to list if something is missing).
- [ ] Travis
- [ ] Dockerfile
- [ ] Documentations

**Comment by mariobehling** [comment]
We can do this later. We need a version to release now.

**Comment by mariobehling** [comment]
Closing this. Can be reopened when time has come.
