### ISSUE TITLE
Deleting event record results in server error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2451]
After user has deleted event, it should be possible that an admin deletes the record completely in the admin section under "deleted events", e.g. http://open-event-dev.herokuapp.com/admin/events/

Deleting the event here results in a server error currently.

![screenshot from 2016-10-04 14 50 45](https://cloud.githubusercontent.com/assets/1583873/19074746/faa68de0-8a41-11e6-99af-a96792e0fc22.png)

**Comment by nikhilrayaprolu** [comment]
@mariobehling I would like to work upon this but I see that I don't have admin access to check with the issue.

**Comment by SaptakS** [comment]
@nikhilbalyan you can set it up in your local system and go through the admin panel.

**Comment by shubham-padia** [comment]
@mariobehling I was not able to recreate the issue, and the records are deleted successfully without error in the admin panel. Please recheck if the isuue still persists.

Screenshots : 
![screenshot from 2016-10-07 15-38-20](https://cloud.githubusercontent.com/assets/13910561/19188007/8a22915a-8cac-11e6-82fb-700bf20a4dfa.png)


![screenshot from 2016-10-07 15-38-26](https://cloud.githubusercontent.com/assets/13910561/19187983/74183e00-8cac-11e6-8808-148cfedd315b.png)

**Comment by IamAdiSri** [comment]
Tried to recreate the issue and I too have found that permanent deletion of records by the admin does work. There were no errors thrown.

**Comment by mariobehling** [comment]
Good job. Thank you.
