### ISSUE TITLE
Admin: Under tab "Sales" show subtab sales "By Marketer" and "By Discount Code"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2452]
In order to get event sales going we are planning to give discount codes to marketers, who then get a discount for event organizers and at the same time get a share of the income.

Please implement subtabs "By Marketer" and "By Discount Code" in the sales tab therefore, e.g. here
http://open-event-dev.herokuapp.com/admin/sales/

![screenshot from 2016-10-04 14 54 25](https://cloud.githubusercontent.com/assets/1583873/19074989/3788fb98-8a43-11e6-8693-e18682008774.png)

**Comment by sainiak009** [comment]
@niranjan94 Please assign this task to me.
