### ISSUE TITLE
Option removed from dropdown in mobile screen after clicking

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2456]
All the tabs in dashboard have now been converted to dropdowns ([PR](https://github.com/fossasia/open-event-orga-server/pull/2446)). However, on clicking one of the options in the dropdown, the option disappears from the dropdown in http://open-event-dev.herokuapp.com/events/

To reproduce this issue, follow these steps:

1. Go to http://open-event-dev.herokuapp.com/events/
![screenshot from 2016-10-07 11-54-16](https://cloud.githubusercontent.com/assets/9530293/19180631/07e2a990-8c85-11e6-8101-4ae23cdc6750.png)

2. Click on "Draft"
3. The "Draft" option now is no longer in the options even on visiting other options.
![screenshot from 2016-10-07 11-54-23](https://cloud.githubusercontent.com/assets/9530293/19180634/0f3b1e48-8c85-11e6-9d20-231abafff0c7.png)
![screenshot from 2016-10-07 11-54-27](https://cloud.githubusercontent.com/assets/9530293/19180636/0f70ce6c-8c85-11e6-86c1-6148b4aeea17.png)

**Comment by sainiak009** [comment]
@SaptakS correcting it now.

**Comment by sainiak009** [comment]
@SaptakS Bug resolved, review my pull request #2457
