### ISSUE TITLE
Requesting help

### ISSUE THREAD

**Issue by abhishek1995s** [fossasia/open-event-orga-server#2464]
I am late to this project.Can some one please tell me what all are the things to be completed in this project so that i could contribute to it. I am good in back end web development

**Comment by niranjan94** [comment]
Please use the GitHub issue tracker only for reporting bugs, or feature proposals or any other technical discussions related to the project. Questions like this can be asked over at the Gitter channel (https://gitter.im/fossasia/open-event-orga-server). 

As for a list of things to be completed, you can just browse the existing issues at https://github.com/fossasia/open-event-orga-server/issues/.

**Comment by abhishek1995s** [comment]
I am sorry
Thank u
