### ISSUE TITLE
Simplify the local installation (for developement)

### ISSUE THREAD

**Issue by hongquan** [fossasia/open-event-orga-server#2465]
Hi

I tried to setup the development environment, following _docs/INSTALLATION_LOCAL.md_ and found it is overcomplicated. Here is my proposal:

#### Database

We tell developer to create database user `open_event_user` and specify a lengthy 
```
DATABASE_URL=postgresql://open_event_user:start@127.0.0.1:5432/test
```
Can we instead just tell developer to create Postgres user with the same name as OS-login user. If my OS-login user is, for example, _quan_, I just need to create Postgres user _quan_, and then, the DATABASE_URL will be simple like: 
```
DATABASE_URL=postgresql:///test
``` 
(given _test_ is the database name). Postgres allows to skip password when a OS user logins to Postgres under the same username.

#### Redis

Why we need to install and run redis in non-standard way:

```
bash run_redis.sh
redis-3.2.1/src/redis-server &
```

Redis is provided in official distro repo. For Ubuntu, we just need to:

```
sudo apt install redis-server
```

#### Celery

Why do we have to run Celery like this

```
export INTEGRATE_SOCKETIO=false
celery worker -A app.celery &
unset INTEGRATE_SOCKETIO
```
Using `&` to push the process to background is not good. Developer will forget that he/she is running `celery` and he/shee may be confused seeing some log output appear in the console all of a sudden. How about just running `celery` like this:

```
INTEGRATE_SOCKETIO=false celery worker -A app.celery
```

The envvar `INTEGRATE_SOCKETIO` then only exists for `celery` and won't conflict other processes.

**Comment by mariobehling** [comment]
@hongquan Sounds excellent. Please make a PR to update the local installation readme.

**Comment by SaptakS** [comment]
@hongquan one of the reasons for writing the redis installation as :

```
bash run_redis.sh
redis-3.2.1/src/redis-server &
```
 It makes the thing OS independent. There can be linux distros which don't have redis-server in their official distro. Though I do agree with the `&` part to some extent and myself never use it.

Rest seems good to me.

**Comment by hongquan** [comment]
> There can be linux distros which don't have redis-server in their official distro

Can you estimate how many percent of that case? Should we favor a small number of distro which doesn't have official package for Redis, or favor a majority which do?

For the command to install Redis, we can give example for the 2 most popular distro family, Debian (with `apt`), and Fedora (with `dnf`). For other distro like Arch, Gentoo, their users are already geek enough to know how to install Redis, we don't need to worry for them.

**Comment by SaptakS** [comment]
@hongquan well an extra line copy-paste never hurts, so we wrote that because it anyhow gives a generalized way.  Otherwise I agree with your point but since it doesn't reduce the task much as it involves simple copy-paste, so we thought of sticking with it.

**Comment by hongquan** [comment]
After simplifying, the commands are also copy-paste. But by using the standard way, the developer won't make his/her system messy, and it will be consistent with other projects he/she involves. You can imagine that after taking part in some projects, the developer ends up having several instances of Redis in his/her machine, one is installed with distro tool, can be restarted easily (with `sudo service redis-server restart`), can be checked with log easily (via `journalctl -u redis-server`) in case Redis suddenly doesn't work, and one is installed by your proposal, which he/she doesn't know how to control and debug.
