### ISSUE TITLE
allow cross origin request on heroku

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#25]
I am not sure if heroku will allow it or not, but the webapp cannot access the heroku becuase CORS is blocked on your heroku container. 

@rafalkowalski can it be done ?

**Comment by rafalkowalski** [comment]
Could you give me an error?

**Comment by championswimmer** [comment]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
remote resource at
http://glacial-earth-2730.herokuapp.com/get/api/v1/sessions. This can be
fixed by moving the resource to the same domain or enabling CORS.

**Comment by championswimmer** [comment]
I think this should be the appropriate resource to fix this problem

http://stackoverflow.com/questions/25594893/how-to-enable-cors-in-flask-and-heroku

**Comment by rafalkowalski** [comment]
I fixed it, Could you check it?

**Comment by championswimmer** [comment]
Works ! Awesome !

You can check http://fossasia.github.io/open-event-webapp/

Just shows the 'descriptions' of sessions right now. I am working on
showing the rest of the data and formatting :)

**Comment by rafalkowalski** [comment]
@championswimmer Great!

**Comment by leto** [comment]
Great work! This is exactly what the mentors want to see :+1:

**Comment by championswimmer** [comment]
Ok, CORS is causing problem on the DigitalOcean server too :P 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://springboard.championswimmer.in/api/v1/event/3. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

**Comment by rafalkowalski** [comment]
curl -GET http://springboard.championswimmer.in/api/v1/event/1 it's working
via curl, could you reproduce it ?  @championswimmer

**Comment by championswimmer** [comment]
cURL works, yes. But to show in webapp, it needs cross origin requests to
be enabled .

**Comment by rafalkowalski** [comment]
ok thanks, Could you check on heroku server? http://open-event.herokuapp.com/api/v1/event/6
I will investigate it

**Comment by championswimmer** [comment]
I have fixed it by adding the header through Apache virtualhost control.

**Comment by championswimmer** [comment]
I have fixed it by adding the header through Apache virtualhost control.

**Comment by rafalkowalski** [comment]
great thanks :) @championswimmer
