### ISSUE TITLE
Only the first confirmation email can verify user

### ISSUE THREAD

**Issue by benjah1** [fossasia/open-event-orga-server#2501]
Version: 84a0a7d

The link in the resend confirmation email isn't same as the first confirmation email.

Test case,
1. Create a new user, without verifying this account.
2. As this unverified new user, go to `Manage Events` page, and resend the confirmation.
3. Check email again. Now try verify the account with the latest confirmation email.

As a result, I get a 404 page.

**Comment by benjah1** [comment]
After looking into the code, I find out there is a bigger security problem. 

First confirmation email can 'always' verify user, because it uses the plain password.
The resend confirmation email may fail, if the encrypted contain '/'.

**Comment by mariobehling** [comment]
@benjah1 Thanks for looking into this. What are your ideas to fix this? Could you help with it?
