### ISSUE TITLE
refactor: reduce lint issues 

### ISSUE THREAD

**Issue by juslee** [fossasia/open-event-orga-server#252]
Reduce the lint issues to < 100 issues. Both on codacy and codeclimate.

**Comment by SaptakS** [comment]
Files in migrations/version folder are to be ignored. They are generated automatically by Flask.

**Comment by aviaryan** [comment]
Most of the files in `open_event/static/admin` are js and css library files and we should ignore them too. There constitute a high amount of issues. 
In codacy, to ignore them, one (the admin) can go to settings->Ignored Files.
Ignoring files in codeclimate can be done by [adding the paths](https://docs.codeclimate.com/docs/excluding-files-and-folders) to `exclude_paths`

**Comment by shivamMg** [comment]
To add to aviaryan, only two static files should be checked for linting issues:

- `open_event/static/admin/css/open-event.css`
- `open_event/static/admin/js/map.js`

Rest all can be ignored.
