### ISSUE TITLE
Logs showing email sent, but does not seem to be sent

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2537]
Emails do not seem to be sent, but show up as sent in logs on eventyay.

![screenshot from 2016-11-12 12 01 21](https://cloud.githubusercontent.com/assets/1583873/20235544/e1af237c-a8cf-11e6-8b8d-b59d83cb4a8f.png)

**Comment by SaptakS** [comment]
Closing this issue as solving #2552 solves this.
