### ISSUE TITLE
Left sidebar and footer bar not showing entries after update

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2538]
Expected behaviour: Footer and sidebars should have info after updates.

![screenshot from 2016-11-12 12 03 21](https://cloud.githubusercontent.com/assets/1583873/20235564/5364aaaa-a8d0-11e6-8d05-d0c096ab10fe.png)

![screenshot from 2016-11-12 12 04 28](https://cloud.githubusercontent.com/assets/1583873/20235565/58177208-a8d0-11e6-97fa-37b88d80f853.png)

**Comment by niranjan94** [comment]
This was due to incomplete data in the database after #2497. It has been resolved.
