### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#254]
Therefore that our interface is not user friendly, we need to choose a library which help us to implement better UI 
Few proposal:

http://startbootstrap.com/template-categories/popular/
http://flatfull.com/themes/materil/angular/#/app/dashboard
http://byrushan.com/projects/ma/1-5-2/jquery/

Give your proposals if you know some frameworks

**Comment by SaptakS** [comment]
@rafalkowalski I think the 2nd template is quite good. Also, I think its code is openly available in github. So, it would be a nice choice.

Few other templates:
http://www.codecovers.eu/materialadmin/dashboards/dashboard
http://www.xtendify.com/en/product/preview/1010-mdladmin-lite-starter-admin-for-google-material-design-lite?type=Frontoffice
http://blog.creative-tim.com/web-design/21-free-dashboard-templates/

**Comment by aditya1702** [comment]
@rafalkowalski  the third template seems nice. Also the template suggested by @SaptakS http://www.codecovers.eu/materialadmin/dashboards/dashboard 
seems interesting.

**Comment by juslee** [comment]
I like these 2:

http://www.codecovers.eu/materialadmin/dashboards/dashboard
http://flatfull.com/themes/materil/html/

Choose 1 and we'll stick to it for both webapp, android, and orga-server.

**Comment by rafalkowalski** [comment]
@juslee Good idea

**Comment by aditya1702** [comment]
@juslee @rafalkowalski how about the first one
http://www.codecovers.eu/materialadmin/dashboards/dashboard

**Comment by niranjan94** [comment]
Most the of the ones discussed above seem to be premium templates. I came across this free one which is really good. 

**Source:** [github.com/puikinsh/gentelella](https://github.com/puikinsh/gentelella)
**Demo:** [colorlib.com/polygon/gentelella/](https://colorlib.com/polygon/gentelella/index.html)

![Gentelella Bootstrap Admin Template](https://cdn.colorlib.com/wp/wp-content/uploads/sites/2/gentelella-admin-template-preview.jpg "Gentelella Theme Browser Preview")

**Comment by leto** [comment]
Howdy,

I really like this admin template, +1

Duke

On Sun, Apr 24, 2016 at 6:11 AM, Niranjan Rajendran <
notifications@github.com> wrote:

> Most the of the ones discussed above seem to be premium templates. I came
> across this free one which is really good.
>
> *Source:* github.com/puikinsh/gentelella
> *Demo:* colorlib.com/polygon/gentelella/
> <https://colorlib.com/polygon/gentelella/index.html>
>
> [image: Gentelella Bootstrap Admin Template]
> <https://camo.githubusercontent.com/0fc2018c171a0d6e721ad421391c006f316eee03/68747470733a2f2f63646e2e636f6c6f726c69622e636f6d2f77702f77702d636f6e74656e742f75706c6f6164732f73697465732f322f67656e74656c656c6c612d61646d696e2d74656d706c6174652d707265766965772e6a7067>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fossasia/open-event-orga-server/issues/254#issuecomment-213954343>
>



-- 
Jonathan "Duke" Leto <duke@leto.net>
Leto Labs LLC http://letolabs.com
209.691.DUKE http://duke.leto.net
@dukeleto http://linkedin.leto.net https://github.com/leto

**Comment by batraabhishek** [comment]
+1 for the theme suggested by @niranjan94

**Comment by juslee** [comment]
http://www.codecovers.eu/materialadmin/dashboards/dashboard
Pros: material design, has all the components we need (form-wizard, calendar, dynamic tables, etc)
Cons: cost $20 bucks, can't be used for open source projects I reckon

https://github.com/puikinsh/gentelella
Pros: bootstrap 3, has all the components we need
Cons: not material design

TBH, gentelella seems to be the best choice right now. Unless someone can find something just as good that is open sourced and using material design, we will go with gentelella.

**Comment by juslee** [comment]
Accepted Gentelella - https://github.com/puikinsh/gentelella
