### ISSUE TITLE
When adding sponsors information of first sponsor gets copied to second sponsor

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2540]
Expected behaviour: Sponsorship info should be empty.

![screenshot from 2016-11-12 12 15 01](https://cloud.githubusercontent.com/assets/1583873/20235622/c3ddad26-a8d1-11e6-822e-7b6c3b08b252.png)

**Comment by SaptakS** [comment]
I will look into this.

**Comment by magdalenesuo** [comment]
Can I work on this?
