### ISSUE TITLE
Upload of sponsorship images apparently not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2541]
Added sponsorship images do not show up in the public page or on the dashboard.

Please ensure:
* [x] Images are uploaded

Resolving this issue, please also:
* [ ] Implement a preview in the upload section (step 2 of wizard) similar to the image upload in wizard step 1

![screenshot from 2016-11-12 12 20 47](https://cloud.githubusercontent.com/assets/1583873/20235656/dad98918-a8d2-11e6-8306-b5099569dbb9.png)

**Comment by SaptakS** [comment]
I will look into this.

**Comment by SaptakS** [comment]
@niranjan94 the preview system hasn't been added. I will add that and close this issue.
