### ISSUE TITLE
User who booked a ticket is not directed to top of page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2544]
The user should be viewing the top of the next page after he/she bought a ticket.

![screenshot from 2016-11-12 12 35 43](https://cloud.githubusercontent.com/assets/1583873/20235713/a310d2aa-a8d4-11e6-913f-0e6d2ea832b3.png)

**Comment by niranjan94** [comment]
@rafalkowalski are you working on this or can I take this up?
