### ISSUE TITLE
Not receiving ticket email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2546]
After buying tickets user does not receive ticket email even though option is set accordingly in admin email settings.

![screenshot from 2016-11-12 14 08 06](https://cloud.githubusercontent.com/assets/1583873/20236049/79c39c72-a8e1-11e6-8de7-52943694786e.png)

**Comment by SaptakS** [comment]
Closing this issue as solving #2552 solves this.
