### ISSUE TITLE
Adding image to speakers form erroneous

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2547]
1. There is a setting "max 1MB" which does not show an error message when a larger photo is chosen. Expected: Show error message "Please choose a photo that is maximum 1MB large."

2. Trying to add a photo is not always possible. Expected: It should work like in wizard step 1.

![screenshot from 2016-11-12 14 17 40](https://cloud.githubusercontent.com/assets/1583873/20236093/0b0f2cb8-a8e3-11e6-8bab-3a4b373025b1.png)

**Comment by mariobehling** [comment]
It seems like some form interaction takes place "behind" the lightbox overlay.

**Comment by SaptakS** [comment]
> There is a setting "max 1MB" which does not show an error message when a larger photo is chosen. Expected: Show error message "Please choose a photo that is maximum 1MB large."

I will look into this.

> Trying to add a photo is not always possible. Expected: It should work like in wizard step 1.

I didn't get what do you mean by not always possible.

> It seems like some form interaction takes place "behind" the lightbox overlay.

Yes. The image is first uploaded temporarily so that a preview can be shown.

**Comment by mariobehling** [comment]
>> Expected: It should work like in wizard step 1.

> I didn't get what do you mean by not always possible.

Sometimes it works, sometimes not. In most cases it does not work for me. There should be a scaling function and flow like the photo upload in the event wizard.

>> It seems like some form interaction takes place "behind" the lightbox overlay.

> Yes. The image is first uploaded temporarily so that a preview can be shown.

The photo is behind the lighbox - it is hidden. The user cannot see. The dialogs also happen behind the box - invisible.

**Comment by SaptakS** [comment]
@mariobehling I will check this out.

**Comment by SaptakS** [comment]
@mariobehling the problem is happening because of nested modals for the cropping feature. If we remove the cropping feature the bug would be solved. I think we can remove the cropping feature for the time...

**Comment by mariobehling** [comment]
@SaptakS Thanks for the explanation. Unfortunately the cropping feature is kind of basic here. Speakers often have images that do not fit well into the design and we need to be sure, that the images are in square format. How to get a fix and keep the feature?

**Comment by SaptakS** [comment]
I will try to fix this tonight.
