### ISSUE TITLE
Email sending options

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2552]
Sendgrid email often runs out of limit. We have 2 options:

* Get a premium sendgrid account
* Other alternative

This would solve all the erroneous email related issues like #2546 #2537

**Comment by niranjan94** [comment]
We can provide two options in the super admin settings page.

1. SMTP
2. Sendgrid

As far as eventyay is concerned, we may need a premium sendgrid account since we don't have a mail service for eventyay.com yet.
