### ISSUE TITLE
Confirm mail sending fail

### ISSUE THREAD

**Issue by tonghuix** [fossasia/open-event-orga-server#2560]
I register a event at  https://open-event-dev.herokuapp.com/e/edca532e/

And it is fail to live because of confirm mail sending fail.

**Comment by SaptakS** [comment]
Can you please tell your event_id? So that I can check??

**Comment by SaptakS** [comment]
@tonghuix, I am unable to reproduce this error. Can you please tell a way to reproduce this? Or can you please tell the event_id of the event you registered?

**Comment by niranjan94** [comment]
@tonghuix new tokens have been added. Email sending should work now.

**Comment by tonghuix** [comment]
Thank you very much! It is coming alive now https://open-event-dev.herokuapp.com/e/edca532e/
