### ISSUE TITLE
Event delete button does not work

### ISSUE THREAD

**Issue by jarifibrahim** [fossasia/open-event-orga-server#2561]
The delete button on the following page does not work
http://open-event-dev.herokuapp.com/events/

This is what I get after clicking on the delete button

![screenshot from 2016-11-16 22-47-44](https://cloud.githubusercontent.com/assets/12949454/20357669/d4a40cba-ac4e-11e6-95dd-d06aeb95c216.png)

**Comment by SaptakS** [comment]
I think it does get deleted but due to some DB query it still gets shown. @jarifibrahim would you like to fix this issue?

**Comment by jarifibrahim** [comment]
@SaptakS Definitely. Any suggestions on where I should look?

**Comment by SaptakS** [comment]
Check event.py in views folder and see how it is fetching data for that page. I think it will have some function in datagetter.py file inside helper folder.

**Comment by SaptakS** [comment]
@niranjan94 you tagged the wrong issue in your PR. :)

**Comment by niranjan94** [comment]
@SaptakS oh ... Sorry ... my bad :sweat_smile:

**Comment by jarifibrahim** [comment]
@SaptakS I am not able to reproduce the bug locally. I believe http://open-event-dev.herokuapp.com has some older version of the web app.

**Comment by SaptakS** [comment]
@jarifibrahim  [ http://open-event-dev.herokuapp.com](http://open-event-dev.herokuapp.com) is automatically deployed from the development branch. So in case it happens in the link it has to happen in your system as well. And I checked in my local system, the error is still there.
