### ISSUE TITLE
[Proposal] Indonesian translation

### ISSUE THREAD

**Issue by Lidilidian** [fossasia/open-event-orga-server#2574]
I am interested in the project open-event and want to contribute to translate into Indonesian, I see in this repository there are two languages, namely English and German (there are .po and .mo file german language), for that, can I add a Indonesian to this project ?

**Comment by mariobehling** [comment]
Yes, great. Thank you.

**Comment by Lidilidian** [comment]
which one should i use for translate template app/translation/message.pot or de/LC_MESSAGES/message.po ?

**Comment by jayvdb** [comment]
@mariobehling , I recommend using weblate for translations, using their free host mentioned at https://weblate.org/en/hosting/#free , by filling in the form at https://hosted.weblate.org/hosting/ .

After a little setup, all translations are automatically merged into the repo, however it is also possible to adjust the translation files using PRs, and these will be pushed into the weblate site as well. (this is unlike Pootle, and any other service I am aware of, which doesnt integrate with GitHub nicely. Mozilla's Pontoon is the next best, but PRs are discouraged as they do not yet have a good strategy for handling conflicts between weblate and the web service.)

**Comment by mariobehling** [comment]
@jayvdb Thank you very much. I did not know weblate. Looks very neat. I asked for project hosting. Let's see, if they accept. Cheers.

**Comment by niranjan94** [comment]
Base translations for this language have been added.

If you would like to contribute to translation of Open Event, you need to [register on this server](https://hosted.weblate.org/accounts/register/).

Once you have activated your account just proceed to the [translation section](https://hosted.weblate.org/projects/open-event/).
