### ISSUE TITLE
Import not working on Kubernetes deployment

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2594]
The file upload for import is not working on Kubernetes deployment. (but works locally and on heroku)

**Comment by niranjan94** [comment]
**Reason:**
Celery and gunicorn are running in two separate containers. The file upload is stored on a temporarily folder inside gunicorn's container. That folder is obviously not accessible from the celery container.

**Solution:**
Setup a persistent store that can be simultaneously accessed by multiple pods. Hence, we need to use an NFS persistent store.

**Comment by mariobehling** [comment]
Will this solution still enable us to scale up and down containers and resources required.. depending on the number of users etc?

**Comment by niranjan94** [comment]
@mariobehling yes. The persistent store will also be scalable.
