### ISSUE TITLE
Logo not being displayed

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#260]
![screenshot from 2016-04-25 12 30 55](https://cloud.githubusercontent.com/assets/15054664/14776131/fe7ec502-0ae1-11e6-8bcc-d898f00f295d.png)
The Logo created in Sponsor is not being shown in the Table although the url is entered in the form
![screenshot from 2016-04-25 12 32 17](https://cloud.githubusercontent.com/assets/15054664/14776152/1e0b70be-0ae2-11e6-8fa5-e136f2167b62.png)

**Comment by aditya1702** [comment]
@rafalkowalski Cant we have an upload button which helps the event users to upload and display Logo in the table?

**Comment by aditya1702** [comment]
@mariobehling @juslee Could we have an image upload button to save images to a folder?

**Comment by aviaryan** [comment]
This issue seems to be fixed now. The logo is displayed when the URL is correct. 
![screenshot from 2016-05-09 12 20 09](https://cloud.githubusercontent.com/assets/4047597/15105578/7133a154-15e0-11e6-9b68-7c359054d9bb.png)
I have added URL validators to the form and opened PR #281

**Comment by aviaryan** [comment]
> The Logo created in Sponsor is not being shown in the Table although the url is entered in the form

I guess the template is handing it as `<img src="{{ logo_url }}">` . That maybe the reason nothing is displayed.
