### ISSUE TITLE
Implement Withdraw proposal feature for speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2603]
Currently we do not have a withdraw proposal option for speakers.

**Comment by niranjan94** [comment]
@mariobehling when a speaker _withdraws_ his proposal, should it be deleted or reverted back to the draft state ?

**Comment by niranjan94** [comment]
I have implemented it such that,

When a speaker withdraws a proposal, it gets deleted. (soft delete).

If the speaker wishes to make the proposal a draft again, he can already do it by pressing edit proposal -> save as draft.
