### ISSUE TITLE
Clean up python dependencies

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2605]
We have loads of python dependencies of which a few are totally unused and can be removed or replaced with a few lines of python code instead of an external dep. 

**Tasks:**
- [x] Find the dependencies that are unused and remove them (#2689)
- [ ] If any dependency is just used for a very small function or purpose which could be replaced with vanilla python, replace the dependency

**Comment by nikhilrayaprolu** [comment]
@niranjan94 I would like to work on this issue . can you please point the file  where the dependencies are mentioned.

**Comment by niranjan94** [comment]
@nikhilrayaprolu inside the `requirements` folder (https://github.com/fossasia/open-event-orga-server/tree/development/requirements)

**Comment by nikhilrayaprolu** [comment]
@niranjan94 out of all those requirements can you sort out those which can be removed. I will work on those requirements and find alternative python codes to replace them

**Comment by niranjan94** [comment]
@nikhilrayaprolu well ... that what this issue is about... I have updated the issue description.

**Comment by mamakancha** [comment]
I would like to get this issue assigned

**Comment by niranjan94** [comment]
@mamakancha  ... You can proceed :)

**Comment by mamakancha** [comment]
@niranjan94 Hi. Can I get a starting point? As in I am not able to understand how to go about solving this issue.

**Comment by niranjan94** [comment]
We have all the dependencies for this project listed inside the `requirements` folder (https://github.com/fossasia/open-event-orga-server/tree/development/requirements). 

But there maybe some dependencies that are unused. Or some dependencies that can be easily replaced by just a few lines of python code instead of big external dependency. 

You'll have to go through all the dependencies and figure out which are used and which aren't and remove the ones that are not used.

If any dependencies can be replaced by a few lines, replace them and remove the dependency.
