### ISSUE TITLE
Remove API v1 endpoints

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2606]
The endpoints in question: https://open-event-dev.herokuapp.com/documentation 

These endpoints where from the previous version of Open Event and we have gone a long way from there with a lot of changes to the aim of this project. And in my opinion, I feel we don't need to maintain the v1 endpoints any more. 

@mariobehling @SaptakS @aviaryan @rafalkowalski your opinon ?

**Comment by mariobehling** [comment]
Totally agree. Please clean up anything from v1. It was a prototype that helped us to progress, but the code is no longer needed.

**Comment by aviaryan** [comment]
Agreed. API v1 is not needed and should|can be removed now. I see there is a `/calendar` API there so maybe we will need to move it to v2.
