### ISSUE TITLE
Bug: Multiple accounts using the same email(Google+ and Facebook Login) 

### ISSUE THREAD

**Issue by Tandoori-Momos** [fossasia/open-event-orga-server#2608]
**Bug:** Multiple accounts can be made with the same email by an user using their Google+ and Facebook account which have the same email.

**For Example:** The two profiles (Top: Google+ - Bottom: Facebook) are different yet they share a common email address. 

![bug](https://cloud.githubusercontent.com/assets/22882925/20699064/52a70eb0-b62b-11e6-9bf4-a48b3651f70a.PNG)
![bug2](https://cloud.githubusercontent.com/assets/22882925/20699069/56a79d04-b62b-11e6-9678-66b0052dcec9.PNG)

**Comment by niranjan94** [comment]
@Tandoori-Momos I believe the underlying account is the same ... Only the profile picture changes
