### ISSUE TITLE
Signing up new account with Gmail

### ISSUE THREAD

**Issue by Wermarter** [fossasia/open-event-orga-server#2609]
@GoogleCodeIn
New password can be entered anyhow (even an one-letter password is acceptable)
![buggy](https://cloud.githubusercontent.com/assets/16450814/20713183/da0ffddc-b679-11e6-8e72-7967814f3004.png)

**Comment by niranjan94** [comment]
@Wermarter if you check the registration page (https://open-event-dev.herokuapp.com/register/) you'll see that the min characters required is 6. Login page doesn't require that check.

**Comment by Wermarter** [comment]
Sorry for the unclear image but what I mean is when you login with an unregistered email, the create password page doesn't have the check. 
![buggy](https://cloud.githubusercontent.com/assets/16450814/20716366/8d0bc038-b684-11e6-8655-186fe003997d.png)
