### ISSUE TITLE
Confirmation mail unable to send on Gmail accounts

### ISSUE THREAD

**Issue by animeshsinghweb** [fossasia/open-event-orga-server#2610]
I had recently created an account on the dev site at heroku, but I noticed there is some bug for sending **confirmation** mail link on gmail accounts. I tried resenting the code, **checked** over my spams and yet I hadn't received the mail. My email account is f4.animesh@gmail.com on the event dev site, and due to non confirmation I was unable to publish the demo event.

Is there anything seriously wrong with the code responsible for triggering confirmation mail or is it problem with heroku/gmail? #GoogleCodeIn16

Thanks.

**Comment by niranjan94** [comment]
@animeshsinghweb no issue with the code as far as I know. Could be the mail settings. Thanks for the bug report :)

**Comment by animeshsinghweb** [comment]
Is it with gmail account basically? I hadn't enquired any error in receiveing such mails from any other sites. Should I try other email providers like yahoo or Yandex?
Thanks.

**Comment by niranjan94** [comment]
@animeshsinghweb not from your side. I meant the server's mail configuration. I'll take a look

**Comment by niranjan94** [comment]
@animeshsinghweb this has been fixed. It was due to an incorrect sendgrid token used on the server.
