### ISSUE TITLE
Sponsored Links URL input area is too short

### ISSUE THREAD

**Issue by animeshsinghweb** [fossasia/open-event-orga-server#2611]
![img_1428](https://cloud.githubusercontent.com/assets/16618931/20715039/e2ecc6ac-b673-11e6-8ebc-0307e709253b.PNG)

The input box for sponsors URL is too short on Tab devices (in my case from iPad) and also I guess there is no initiative used to ensure that it is a valid URL and it can be used to ruin databases by malicious codes. 

Don't you think that the input box should be big enough at least for people to check the domain is not mistyped, maybe only for non PC devices?

Thanks. #GoogleCodeIn16

**Comment by vedantrathore** [comment]
Can I take up on this issue?
and also how would we check for a malicious code like in case of SQLInjection or XSS?

**Comment by niranjan94** [comment]
> Can I take up on this issue?

Yes. you can. this issue has been assigned to you :)

> and also how would we check for a malicious code like in case of SQLInjection or XSS?

1. **XSS** 
All the fields which are rendered as HTML are passed through a HTML Sanitizer (which remove all but a few allowed HTML tags) before being stored to the database. The rest of the fields are automatically escaped by jinja when rendering.

The sanitizer: https://github.com/fossasia/open-event-orga-server/blob/development/app/helpers/versioning.py#L27

2. **SQL Injection**
We are using SQL-Alchemy's query builder and ORM and not using Raw SQL Statements anywhere. Hence, SQL-Alchemy handles escaping of input to prevent SQL Injection.

**Comment by vedantrathore** [comment]
@niranjan94 so I just need to check for the responsiveness of the url input area right? no need to check for malicious code?

**Comment by SaptakS** [comment]
@vedantrathore, yes the responsiveness and also the size of text box. Also you can put a pattern check to check for http:// or https:// else show an error.
