### ISSUE TITLE
Improve readability on public event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2639]
The heading and dates are difficult to read. Please check how to improve, e.g. change to bold or experiment how this can be improved.

![screenshot from 2016-12-06 15-23-03](https://cloud.githubusercontent.com/assets/1583873/20918165/2be0eab0-bbc8-11e6-88b0-ca55c9bf4ee7.png)

**Comment by niranjan94** [comment]
![screenshot from 2016-12-06 15 09 02](https://cloud.githubusercontent.com/assets/2404372/20920433/f983e826-bbc5-11e6-8764-00cf321f77f4.png)

@mariobehling 
I think this looks better. Removed the gradient and increased the font weight of the datetime and location.

**Comment by mariobehling** [comment]
Ok, let's try this out.
