### ISSUE TITLE
Top bar on session page using a lot of space

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2640]
If there are many tracks at large events the top bar on the sessions page takes up a lot of space, e.g. for FOSDEM.

Please propose a better way to show tracks on the top bar and reduce the height. Compare: https://eventyay.com/e/18252ab6/sessions/

**Comment by aayushsanghavi** [comment]
A horizontally scrolling navbar can be of use here. Something like this - 
![screenshot from 2016-12-06 23 06 39](https://cloud.githubusercontent.com/assets/19590302/20936478/be135180-bc08-11e6-8771-ed22523bc29b.png)

**Comment by niranjan94** [comment]
@aayushsanghavi would you like to work on this ?

**Comment by SaptakS** [comment]
@niranjan94 @mariobehling @aayushsanghavi I think a better implementation would be that whenever there is an overflow, we either a put a previous and next button on both side, or we have a "View More" tab which is a dropdown from where we can select the remaining. What do you think?

**Comment by shubham-padia** [comment]
@mariobehling @SaptakS @niranjan94 What do you think about this kind of approach. The current session and a fixed no. of sessions after that will be displayed in the navbar, for more session the user has to expand the navbar. If this seems okay, inform me so I can make a PR for the same.

![image](https://media.giphy.com/media/W6SoPDSYfhbEY/giphy.gif)

**Comment by SaptakS** [comment]
@shubham-padia LGTM

**Comment by mariobehling** [comment]
@shubham-padia This is a nice implementation. Do you have a sample link, please for testing?

I also wonder how we can increase the number of tracks shows? E.g. decrease distance between lines and widen display area. 

It would be good if users could see as many tracks as possible without having to make any interaction. I am reopening this issue therefore.

**Comment by mariobehling** [comment]
Ok, I see the link on the eventyay system already works, but I am having issues 

* [ ] I cannot get it to work on small resolutions
* [ ] The top bar only appears when the page is moved to the top
* [ ] the bar sometimes moves to the top of the browser window on Chrome.
![screenshot from 2016-12-26 11-02-21](https://cloud.githubusercontent.com/assets/1583873/21480226/48c89b6c-cb5b-11e6-8d3d-987cdc199a96.png)

**Comment by shubham-padia** [comment]
@mariobehling I'll provide a fix decreasing distance b/w lines and making the navigation compact and point no.2 of above comment.
Regarding small resolutions, the implementation seems to be functional on my device, I've attached the relevant screenshots.

![selection_027](https://cloud.githubusercontent.com/assets/13910561/21481479/07249642-cb8e-11e6-9e0a-489a3ce9cfbe.png)

**Comment by mariobehling** [comment]
@shubham-padia Thank you. Much appreciated.

In your screenshot I see, that the left half of the screen is white. Please open an issue to fix the mobile display, if it is out of scope of this issue. Cheers.
