### ISSUE TITLE
Design issues on session, schedule, CfS page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2641]
* [ ] On the event page the left sidebar stays there when the user scrolls down. Please implement this on the other pages as well, e.g. https://eventyay.com/e/18252ab6/schedule/
   * [ ] sessions page
   * [ ] schedule page
   * [ ] call for speakers page 
* [ ] The tracks view on schedule page does not show colors of session (https://eventyay.com/e/18252ab6/schedule/)
* [ ] The call for speaker page needs to include the year in the date format: Compare https://eventyay.com/e/18252ab6/cfs/

**Comment by aayushsanghavi** [comment]
I'd like to take it. I understood the first and third point.
For the second one I didn't understand what is to be done. Which colors of session? What is to be shown in colors of session? Could you please elaborate on these and explain what exactly is supposed to be done.

**Comment by mariobehling** [comment]
@aayushsanghavi The colors of sessions/tracks are defined in the JSON files. The session page has the correct colors of sessions, but on the tracks page all sessions have the same color. Each session should have the color that is according to the track. Also compare to the web app output of the fossasia summit: http://fossasia.github.io/open-event-webapp/tracks.html

**Comment by niranjan94** [comment]
@aayushsanghavi what's the progress on this issue ?

**Comment by aayushsanghavi** [comment]
Wasn't in town for over a week. And I tried a couple times but I am facing issues setting up the project.

**Comment by aayushsanghavi** [comment]
I tried a lot but for some reason I can't set up the project on my local environment. It is causing a delay already. So I suggest, you assign the issue to someone else. Sorry!

**Comment by Marauderer97** [comment]
@mariobehling  @niranjan94 Can I work on this?

**Comment by niranjan94** [comment]
@Marauderer97 yes. you can work on this ...

**Comment by Marauderer97** [comment]
@niranjan94 I have been working on the second issue(Tracks view not showing colours of session), and I think the reason it doesn't work is the data received using the api,in line 
https://github.com/fossasia/open-event-orga-server/blob/development/app/static/js/admin/event/scheduler.js#L873
 doesnot contain the colour of the session just the id and the title, and hence updateColor() in scheduler.js,  never works.What can I do next?

**Comment by SaptakS** [comment]
@Marauderer97 the session data should have a track id, if color of track is not present, you can pull track data using the track id and get the color. @niranjan94 what do you think?

**Comment by niranjan94** [comment]
@SaptakS you're right. 

@Marauderer97 you can either do what @SaptakS suggested or you can edit the API such that color is also provided. (I think it's just a one line edit)

**Comment by Marauderer97** [comment]
@niranjan94  @SaptakS I am trying to edit the api, but it looks like the color is already provided..
![screen1](https://cloud.githubusercontent.com/assets/20185076/21561651/6cd17fbe-ce95-11e6-9db0-769432610a63.png)
But when I print the track object on the console. As of now, I have been able to give each track the same color that the session gets in the Rooms view using the updateColor function defined in the scheduler.js file
![image](https://cloud.githubusercontent.com/assets/20185076/21561676/d9f09f58-ce95-11e6-8c3a-b68081afb89f.png)
updateColor  function link: https://github.com/fossasia/open-event-orga-server/blob/development/app/static/js/admin/event/scheduler.js#L251

**Comment by niranjan94** [comment]
@Marauderer97 you're looking at the wrong file :) .. See https://github.com/fossasia/open-event-orga-server/blob/development/app/api/sessions.py#L32

**Comment by Marauderer97** [comment]
@niranjan94 Thanks! Task 2 and 3 done. In the first task, in the main page the console displays nav-bar having  is_stuck class, but the same nav-bar in other pages like cfs, sessions page, schedule page the class doesnot appear, though the same nav-bar is present, and all the css files are linked. I am not very  familiar with jQuery-sticky-kit, how should I go about this?
