### ISSUE TITLE
Change open event sample session length format

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2644]
In the scheduler and publicly available schedule short sessions are not showing up properly. Compare: https://eventyay.com/events/5/scheduler/

![screenshot from 2016-12-06 16-00-01](https://cloud.githubusercontent.com/assets/1583873/20919202/35f6dee2-bbcd-11e6-9bee-11cd521447e1.png)

**Comment by niranjan94** [comment]
@mariobehling it's because the session timings seem to be overlapping. Which is not supposed to happen.

**Comment by Marauderer97** [comment]
Hello, I would like to work on this.. only I cannot see what exactly needs to be done.. could some one please elaborate? Where is the length attribute being displayed?

**Comment by niranjan94** [comment]
> Would it be better to implement this in a time format? Like: 00:30

Sorry @mariobehling I noticed this comment only now. Currently session length is stored as a `float` in the database. That's the reason it's being displayed as `0.3` in the samples.

I think it would be better if we change it to like `00:30` (just like how it is displayed on the event wizard - step 3)

**Comment by niranjan94** [comment]
@Marauderer97 

- The session type model has to be changed such that length is considered as a string instead of a float. (be sure to generate the required migrations too).
- The API definition for session type has to be changed such that length is considered as a string instead of a float. (event better would be a custom type with validation).
- All samples at `fossasia/open-event` have to be modified accordingly.

**Comment by Marauderer97** [comment]
@niranjan94  Hello, sorry for the delay, the installations was giving me problems, fixed it finally, I have done the first two steps, but what does all samples at fossasia/open-event refer to exactly?

**Comment by niranjan94** [comment]
@Marauderer97 these are the samples https://github.com/fossasia/open-event/

**Comment by Marauderer97** [comment]
@niranjan94 Understood, thanks for patiently elaborating, so does that mean, i make two PRs, one here and one to fossasia/open-event?
