### ISSUE TITLE
Start page: Longer addresses change height of box and break styling

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2649]
Some addresses of event locations are longer requiring two lines on the overview page. This results in a different height of the box on the start page and breaks the style.

Please change the styling to ensure all boxes are displayed in rows.

![screenshot from 2016-12-07 07-46-10](https://cloud.githubusercontent.com/assets/1583873/20950288/7780420c-bc51-11e6-8d2a-13a3269bdf78.png)

**Comment by SaptakS** [comment]
@magdalenesuo thanks for the pull request.
