### ISSUE TITLE
Setup the server on IBM Bluemix and document it

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2652]
Parent issue: #1548

_Add one-click deployment button to set up the system, if possible_

**Comment by gureks** [comment]
Hi 
Please assign it to me. 
I went through #2269 thoroughly to understand what the issue wants. 
Is there anything else you wish to elaborate?

**Comment by niranjan94** [comment]
@gureks any progress on this front ? :)

**Comment by niranjan94** [comment]
@gureks ?
