### ISSUE TITLE
Enhance standard image entries

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2657]
- [ ] Link to the original image/License
- [ ] App/helpers/static.py, there seem to be 3 entries missing

**Comment by PolBaladas** [comment]
Okay!

**Comment by PolBaladas** [comment]
There were actually 4 entries missing

**Comment by PolBaladas** [comment]
Entries problem is fixed. I am aware that these pictures are held by a Creative Commons Zero (CC0) license as specified in https://www.pexels.com/photo-license/.
Where shall we mention it?

**Comment by PolBaladas** [comment]
Hey @mariobehling i think this is done! Shall this be closed?
