### ISSUE TITLE
Track number of people going to a particular event.

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-orga-server#2673]
@the-dagger assign me this. This feature will help users know about the popularity of the session through the number of people going to the event.

**Comment by the-dagger** [comment]
You can proceed and work on this. :+1:

**Comment by SaptakS** [comment]
@rohanagarwal94 @the-dagger this is not exactly a high priority feature right now... So I would prefer you help us solve the bugs rather than implementing a completely new feature which might be helpful but isn't necessary right now. @mariobehling @niranjan94 views?

**Comment by mariobehling** [comment]
@rohanagarwal94 Right now we need to get the app more stable before we include new features. I adding the tag "After-Release" to incorporate this after the first Release. Right now we are in Alpha Release phase.
