### ISSUE TITLE
Implement eventbrite scrapper as module in the server

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2674]
Scrapper: https://github.com/fossasia/event-collect/blob/master/platforms/scrape_eventbrite.py

Implement the scrapper code from the event-collect repo as a module in the server so that it can be called for scrapping.

**Comment by shubham-padia** [comment]
@niranjan94 I would like to work on this. Can I work on this ?

**Comment by niranjan94** [comment]
@shubham-padia I'm happy to know that you're interested on this :) .. But let's first get open-event-orga server out of alpha stage by fixing the bugs ... It would be really great if you could assist us there :D .. You can take this up once we're out of alpha ...

**Comment by shubham-padia** [comment]
@niranjan94 sure.

**Comment by mariobehling** [comment]
Out of scope looking at the progress we have been making. Closing it therefore.
