### ISSUE TITLE
Implement the query-server as a microservice 

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2675]
We need to have the ability to connect to a query server deployment and query for events.

Query server: https://github.com/fossasia/query-server

**Comment by nikhilrayaprolu** [comment]
@niranjan94 I would like to work upon this. can you please elaborate on this issue

**Comment by niranjan94** [comment]
@nikhilrayaprolu As you can see at https://github.com/fossasia/query-server ... we have a query server that returns the list of results from google or other search engine based on a query which we send to it ... So, when a user searches for an event in open-event orga server, we'll also send that query to the query server and get the results and pass on those results to site-specific scrappers ... (like an event brite scrapper (#2674) for eventbrite results) and get the event ... import it into open-event and show the events too in the search results. ...

**Comment by niranjan94** [comment]
This issue is dependent on the https://github.com/fossasia/query-server being completed and hosted somewhere like heroku or something ... So, this would take a while

**Comment by niranjan94** [comment]
@nikhilrayaprolu  nice to see that you're interested in this :)  .. But let's first get open-event-orga server out of alpha stage by fixing the bugs ... It would be really great if you could assist us there :D .. You can take this up once we're out of alpha ...

**Comment by bhaveshAn** [comment]
Is this issue still active? Then I would like to work on this issue.

**Comment by niranjan94** [comment]
@bhaveshAn the issue is active. But not required at this stage of the project.

**Comment by mariobehling** [comment]
Let's focus on getting the core functionalities to work. Anything else is out of scope for the time being. Closing it therefore. We can come back to it, when we have the core working, which might take a while.

**Comment by bhaveshAn** [comment]
@mariobehling Please tag/ping me whenever there is the need of this feature, as I am well versed with `query-server`
