### ISSUE TITLE
Error in placeholder upload 

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2677]
I was getting an error when uploading an image in placeholders `OSError: [Errno 2] No such file or directory: '/home/shubham/github/orga2/static/uploads/temp/temp/' ` or `OSError: [Errno 17] File exists: '/home/shubham/github/orga2/static/uploads/temp/' `.
I've fixed the problem in the code, but can someone please double check if the error exists or not ?

**Comment by niranjan94** [comment]
Could you make a PR with your fix ?

**Comment by shubham-padia** [comment]
closed via #2678
