### ISSUE TITLE
Return the user to the same tab in all pages that contain tabs.

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2690]
After performing any actions like delete return the user to the same tab instead of taking him/her to the first tab.

Has to be done in the following pages

- [ ] - `/admin/events/`
- [ ] - `/admin/sessions/`
- [ ] - `/admin/users/`
- [ ] - `/admin/permissions/`
- [ ] - `/admin/settings/`
- [ ] - `/events/`
- [ ] - `/mytickets/`
- [ ] - `/events/mysessions/`

It has already been done in
- [x] - `/admin/reports/`
- [x] - `/admin/content/`

**Comment by niranjan94** [comment]
@SaptakS issue description has been updated

**Comment by SaptakS** [comment]
@niranjan94 noticed. :+1:

**Comment by nikhilrayaprolu** [comment]
I have tested this by deleting the events ,sessions ,users in 
-/admin/events/
- /admin/sessions/
- /admin/users/
looks like everything works fine
@niranjan94 @SaptakS

**Comment by niranjan94** [comment]
@nikhilrayaprolu everything 'works' fine ... But not very user-friendly is it :wink: .. Each time the user has to go back to the tab he was on before ...

**Comment by nikhilrayaprolu** [comment]
but at these addresses
-/admin/settings/
- /events/
It is getting redirect to the same url but to different tab(for instance if we delete a drafted event , it is being redirected to live events tab ,since we dont have a specific url assigned for each tab .
One way we could do this is to implement url query parameters for each tab and read the query parameter by parsing the url each time

**Comment by niranjan94** [comment]
Correct ... But no need to make it too complex by have query params and passing them. See how it has been implemented in 

- `/admin/reports/`
- `/admin/content/`

**Comment by nikhilrayaprolu** [comment]
@niranjan94 a href to '#tab-name' is used in those pages. So how were you informing the browser to that tab in a response from backend(views) ?

**Comment by niranjan94** [comment]
@nikhilrayaprolu the backend we just gave a redirect to the user's previous page URL ...

**Comment by nikhilrayaprolu** [comment]
@niranjan94 can you please point out the line number in views where you have explicitly used this functionality.

**Comment by shubham-padia** [comment]
@SaptakS Can I work on this issue ?

**Comment by niranjan94** [comment]
@nikhilrayaprolu there is no specific point. It is just like any other page. The user is sent back to the previous url.

**Comment by SaptakS** [comment]
@shubham-padia I think @nikhilrayaprolu is working in it.

**Comment by nikhilrayaprolu** [comment]
@shubham-padia you can proceed with this issue. I am working on another issue right now.
