### ISSUE TITLE
Internal server error when clicking any tags in the home page

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2691]
Internal server error on clicking the tags (like #Conference #ScienceAnTechnology ) in the home page under each event.

**Comment by nikhilrayaprolu** [comment]
@niranjan94 looks like this bug is only with category tags,
since there is a line `testandremove('category')` at https://github.com/fossasia/open-event-orga-server/blob/development/app/views/home.py#L244
removing the line works well with the tag

**Comment by niranjan94** [comment]
Please find out why that method is causing an error ...

**Comment by nikhilrayaprolu** [comment]
Issue is with `request.args.get(key).lower() == request.args.get("query").lower():`
where both objects doesn't a method lower() on them.
@niranjan94

**Comment by niranjan94** [comment]
@nikhilrayaprolu Not exactly `request.args.get(key)` returns a `string` which has the method `lower()` (https://docs.python.org/2/library/string.html#string.lower)

**Comment by nikhilrayaprolu** [comment]
@niranjan94 the issue is with `request.args.get("query").lower():` . we dont have any parameter named "query" so this is returning None
