### ISSUE TITLE
Js error in search page when the background image of any event in the result does not exist

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2692]
Eg: https://eventyay.com/explore/world/events/

```
vue.js:523 [Vue warn]: Error when rendering component <event-box>: 
vue.js:2963 Uncaught TypeError: Cannot read property 'split' of null
    at VueComponent.locationName (event-box-component.js:25)
    at Watcher.get (vue.js:1656)
    at Watcher.evaluate (vue.js:1764)
    at Proxy.computedGetter (vue.js:1955)
    at Proxy.eval (eval at makeFunction (vue.js:8238), <anonymous>:2:548)
    at VueComponent.Vue._render (vue.js:2954)
    at VueComponent.<anonymous> (vue.js:2191)
    at Watcher.get (vue.js:1656)
    at new Watcher (vue.js:1648)
    at VueComponent.Vue._mount (vue.js:2190)
```

**Comment by nikhilrayaprolu** [comment]
@niranjan94 can I work on this issue?
and is there any sample event that I could import for reproducing this error?

**Comment by niranjan94** [comment]
No import necessary. Just create a new event yourself.

**Comment by nikhilrayaprolu** [comment]
looks like this is an error when the event has no location name. but I could see that for publishing an event a location name is made  mandatory, hence we wont break this issue. if its really required a condition at https://github.com/fossasia/open-event-orga-server/blob/development/app/static/js/admin/guest/explore/event-box-component.js#L25 may work.

**Comment by niranjan94** [comment]
But that doesn't mean we should be fixing this issue ... Now because of one flawed event, the entire search page doesn't work. We need to ensure that irrespective of what data is coming in (empty/filled) our functionality doesn't break like this ...
