### ISSUE TITLE
UI bugs in /profile/

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2693]
![screenshot from 2016-12-22 21 17 04](https://cloud.githubusercontent.com/assets/2404372/21431494/8364dfe0-c88d-11e6-9c74-279ec2daede6.png)

- [ ] Profile picture upload icon mis-aligned
- [ ] Page title missing

**Comment by SaptakS** [comment]
> Profile picture upload icon mis-aligned

How?

**Comment by niranjan94** [comment]
@SaptakS 

> How?

I do not know how. But it's not in the center like everywhere else.

**Comment by magdalenesuo** [comment]
I would like to work on this issue?

**Comment by niranjan94** [comment]
@magdalenesuo sure ... You can proceed. please set up the server locally and see if you're able to reproduce the issue

**Comment by magdalenesuo** [comment]
@niranjan94 Yes, I have done that. working on the issue now :)
