### ISSUE TITLE
Internal server error when rejecting/accepting session with email

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2696]
Reject URL: `/events/<event_id>/sessions/<session_id>/reject/`
Accept URL: `/events/<event_id>/sessions/<session_id>/accept/`

**Comment by nikhilrayaprolu** [comment]
@niranjan94 It is working well at http://open-event-dev.herokuapp.com/events/255/sessions/7172/accept/
 at the development server
