### ISSUE TITLE
Deleting of sessions belonging to a different event works by just changing the session ID

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2697]
Eg:
`https://eventyay.com/events/5/sessions/<session_id>/trash`

The session ID can be incremented thereby deleting sessions of any event irrespective of whether you own the event or not,.

**Comment by nikhilrayaprolu** [comment]
@niranjan94 can I work on this issue.
is it fine to add @can_access to the function in sessions view https://github.com/fossasia/open-event-orga-server/blob/master/app/views/users/sessions.py#L180

**Comment by niranjan94** [comment]
Not exactly ... `@can_access` right now checks only if the user can edit the event ... the session ID is never tested

**Comment by nikhilrayaprolu** [comment]
so does that mean checking if the session id belongs to event and then deleting is fine along with @can_access decorator?
or shall we make a new decorator where we check whether the user has access for the session?

**Comment by niranjan94** [comment]
@nikhilrayaprolu I'm already working on this issue ... We have other similar security issues, so looking at fixing them in a unified manner :)
