### ISSUE TITLE
bower error while installing using vagrant

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/open-event-orga-server#2698]
while installing with vagrant I faced an issue with bower , where it is instructing us to install using --allow-root flag.
One way we could remove this error is manually typing bower install after 'vagrant ssh' 
or 
giving the --allow-root flag to the command in /scripts/install.sh
or
execute the command by exiting from root user mode to user vagrant
![screenshot from 2016-12-23 13-42-33](https://cloud.githubusercontent.com/assets/15216503/21449758/94529c50-c916-11e6-9d59-2bdc9731250b.png)

**Comment by niranjan94** [comment]
Thanks :)
Could you add the `--allow-root` flag to `/scripts/install.sh` and make a PR ?

**Comment by nikhilrayaprolu** [comment]
closing this issue ,as the pull request is merged.
