### ISSUE TITLE
Internal Server Error for Profile in case of image uploaded

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2701]
If profile has an image uploaded, you get an internal server error at `/profile/`

**Comment by magdalenesuo** [comment]
@SaptakS On upload, I got no "internal server error". However, on reloading the page, the image gets removed.

**Comment by SaptakS** [comment]
@magdalenesuo thanks for pointing that out. I will have to recheck the image upload code for profile.
