### ISSUE TITLE
Cannot add old events information

### ISSUE THREAD

**Issue by tarsdev** [fossasia/open-event-orga-server#2712]
In eventyay we cannot add old important events that took place, only upcoming events can be added. This feature must be given so that we can check history of old events.

**Comment by SaptakS** [comment]
> we cannot add old important events that took place, only upcoming events can be added. 

@tarsdev you can add old event by import functionality. We think if the event has already occured, it is better to be imported and no one will reproduce the entire event information from scratch and nor is it possible in some cases for example the tickets. So the old events getting created without import function is unlikely. 

> Also same event can be added twice so this must be solved!

I don't understand this issue. Each event has a unique event id. So once they are publicised they can be shared using the particular links. Even if we restrict using the event name, someone can create an event with similar name that will make it appear to be same. What do you have in your mind?

@niranjan94 want to add something?

**Comment by niranjan94** [comment]
@SaptakS you seem to have covered everything ... 

> Also same event can be added twice so this must be solved!

yep. i don't understand this one either

**Comment by mariobehling** [comment]
@SaptakS @niranjan94 Eventyay should work as a database of old events where people can see what happened in the past. To enable users to add this info through the UI would increase the outreach of the system. We also have this as a task in GCI.
