### ISSUE TITLE
Links and Social Media Section Does Not Work

### ISSUE THREAD

**Issue by GabrielLee22** [fossasia/open-event-orga-server#2713]
Tried to add External Link/Twitter/Facebook links to the event page, but links do not show up at the right hand side of the event page as before.

**Comment by GabrielLee22** [comment]
Here's a screenshot showing the area where the links are supposed to be:

![screenshot](https://cloud.githubusercontent.com/assets/9492662/21467893/9931f078-ca37-11e6-8510-4aa673c2a620.PNG)

Tried many times to add the links again and again but was unsuccessful. The social media section on previously created events appears to be working fine though; just that I am now unable to add social media links to newly created events.

**Comment by niranjan94** [comment]
@GabrielLee22 thanks for report :)
