### ISSUE TITLE
Should we remove the default location 'United States' for search function?

### ISSUE THREAD

**Issue by GabrielLee22** [fossasia/open-event-orga-server#2714]
Just wondering whether it would be a good idea to remove the default location 'United States' for the search function. 

![search](https://cloud.githubusercontent.com/assets/9492662/21467936/2a5eb670-ca39-11e6-862d-432549c1184a.PNG)

Personally, I feel that it would be better not to have a default location for the search function, so that users can filter through the list of events themselves.

**Comment by GabrielLee22** [comment]
This is especially relevant with regards to the search bar at the top, where users cannot specify a country but can only search for the event. For example, if I were to type 'fossasia singapore' into the search field at the top, the results displayed will still only be for events in the United States - and not Singapore. Screenshot below shows this: 

![fossasia](https://cloud.githubusercontent.com/assets/9492662/21468141/4ca7c4c2-ca40-11e6-8661-88a2d86b30f0.PNG)

**Comment by niranjan94** [comment]
Actually ... The default location is supposed to be user's country based on his/her IP ... If it is always US, then it is a bug. Could you fix it ?

**Comment by niranjan94** [comment]
@GabrielLee22 why was this issue closed ?

**Comment by GabrielLee22** [comment]
Created a new issue which explicitly states the problem faced - so that there will not be any confusion regarding the "default location" I mentioned earlier - see issue #2722
