### ISSUE TITLE
No action being called on uploading a placeholder

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/open-event-orga-server#2720]
when a new place holder is replaced in admin/content there is no information about whether the image is uploaded or not except a json response in the console.
also closing the modal doesn't change the placeholder in the content view untill we refresh the page
A redirection to the page along with new image would look good.
![screenshot from 2016-12-25 18-57-11](https://cloud.githubusercontent.com/assets/15216503/21471322/5534c132-cad4-11e6-8634-d29782981c1e.png)

**Comment by niranjan94** [comment]
@nikhilrayaprolu would you be interested in fixing this?

**Comment by nikhilrayaprolu** [comment]
@niranjan94 sure I will work on this

**Comment by niranjan94** [comment]
Cool. :D
