### ISSUE TITLE
Search Function: Location incorrect based on user's IP address

### ISSUE THREAD

**Issue by GabrielLee22** [fossasia/open-event-orga-server#2722]
Following up from issue #2714 - the search function does not accurately reflect the country a user is in based on his or her IP address. For instance, I was shown search results for the United States instead of Singapore - although I live in Singapore.

![2a5eb670-ca39-11e6-862d-432549c1184a](https://cloud.githubusercontent.com/assets/9492662/21472359/7ce2cdd2-cb10-11e6-9026-7323e593ba82.PNG)

**Comment by niranjan94** [comment]
@shubham-padia we're not using app engine. And extensions written with C work on eventyay

**Comment by niranjan94** [comment]
I believe the problem exists with the Nginx Ingress Controller. It has to be configured such that the client Ip is visible to the final web service in some form.

**Comment by shubham-padia** [comment]
@niranjan94  Ohh...sorry, I always thought eventyay ran on app engine :smile:

**Comment by niranjan94** [comment]
@shubham-padia Nope. We use [Kubernetes](http://kubernetes.io/) ... Do check it out :smile: It's awesome ! 

Our configuration files are at https://github.com/fossasia/open-event-orga-server/tree/development/kubernetes

**Comment by Abhi2424shek** [comment]
Guys I have a suggestion we could integrate the geo locator which is a project of FOSSASIA currently for this, the project is at: github.com/fossasia/geo_locator it currently works for the gci16 site only we could improve it's reach. Suggestions please @niranjan94

**Comment by niranjan94** [comment]
@Abhi2424shek I don't think that could be used here ... And this issue is related the wrong IP address of the user being passed on to the app

**Comment by Abhi2424shek** [comment]
Hah @niranjan94 i interpreted it the other way, reading through.

**Comment by niranjan94** [comment]
Finally resolved by 8922ce1b5336213a65436500738660f04c59c34e :)
