### ISSUE TITLE
Addresses Break Style on Explore Page

### ISSUE THREAD

**Issue by GabrielLee22** [fossasia/open-event-orga-server#2723]
Similar to issue #2716 and pull request #2719 - but this time it occurs on the explore page. 

![screenshot](https://cloud.githubusercontent.com/assets/9492662/21472372/8099803c-cb11-11e6-863e-a184e4c7ff1a.PNG)

**Comment by shubham-padia** [comment]
@niranjan94 can I work on this ?

**Comment by niranjan94** [comment]
@shubham-padia sure :)
