### ISSUE TITLE
Cannot Select Dates Before December 26 2016 

### ISSUE THREAD

**Issue by GabrielLee22** [fossasia/open-event-orga-server#2724]
On the 'Create an Event' page, I cannot seem to add dates prior to the date which I am accessing the site. In other words, if today's date is 26th December 2016, I cannot add any dates before 26th December 2016 for my (past) event, and I can only add dates after 26th December 2016. 

![date](https://cloud.githubusercontent.com/assets/9492662/21472454/18749654-cb16-11e6-874a-0e836995efe1.PNG)

This change seems crucial if we want eventyay to be a database of past events, as Mario has previously mentioned. Btw, I am a 15 year old student participating in Google Code-in and a beginner to open-source, so apologies if my issue is not relevant/or incorrect. But still, will keep trying to point out any possible issues the site may have :)

**Comment by niranjan94** [comment]
@GabrielLee22... Already reported and fixed here #2721... Thanks anyway 😄
