### ISSUE TITLE
Is There A Way to Change the Duration of an Event in Scheduler?

### ISSUE THREAD

**Issue by GabrielLee22** [fossasia/open-event-orga-server#2725]
On the Scheduler page, the duration of each talk has been pre-set to 15 minutes. But I cannot seem to change the duration of each talk. This is because some talks may be slightly longer, or shorter, and being able to change the duration of each talk seems ideal. 

![scheduler](https://cloud.githubusercontent.com/assets/9492662/21472486/1b268752-cb18-11e6-89c0-907f6568b91c.PNG)

**Comment by niranjan94** [comment]
Yes... You can do that by resizing the boxes... Hover your mouse pointer over the bottom edge of a box :)
