### ISSUE TITLE
Cannot import FOSSASIA 16 sample file

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2728]
Currently FOSSASIA 16 sample file fails on Heroku deployment. 

Error Message "File session_types, ID 1, 'length' should be a String"

![screenshot from 2016-12-26 10-56-01](https://cloud.githubusercontent.com/assets/1583873/21480080/2bae0e6e-cb5a-11e6-9451-d21d46bb28e6.png)

**Comment by mariobehling** [comment]
After merging to the latest version of the samples and trying again, the server gives me an "internal error".

![screenshot from 2016-12-26 13-01-36](https://cloud.githubusercontent.com/assets/1583873/21481745/8b2c81c0-cb6b-11e6-964e-98d0b5b7be12.png)

**Comment by Marauderer97** [comment]
@mariobehling in open-event-orga-server I changed length in session-type to a string, and so I made the corresponding changes in open-event's sample files too(and created new zip files). But I get Internal Server Error too, what do you think the issue is?

**Comment by niranjan94** [comment]
@mariobehling will check this

**Comment by niranjan94** [comment]
@mariobehling the zip structure was incorrect. Fixed it in 
https://github.com/fossasia/open-event/commit/798fde999916a82079bfa5f602b3570f4d79523c
