### ISSUE TITLE
Add icon for Linkedin and External Links if user adds it

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2735]
A number of services are shown with their social media icons. Linkedin and External Links icons are currently missing. Please add them.

![screenshot from 2016-12-26 15-50-08](https://cloud.githubusercontent.com/assets/1583873/21483490/23d7b8c4-cb83-11e6-903c-f2ae30955447.png)

**Comment by magdalenesuo** [comment]
Can work on this?

**Comment by SaptakS** [comment]
@magdalenesuo yes, sure.
