### ISSUE TITLE
Missing Sessions associated with a Track in API?

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#274]
Every Track has Sessions associated with it (`/admin/event/:event_id/track/new`). But our API endpoint for track does not list them https://github.com/fossasia/open-event/blob/master/API.md#tracks.

A track should list its sessions (at least IDs and titles):

```json
{
  "tracks": [
    {
      "id": 1,
      "name": "Linux",
      "description": "All things to talk about Linux",
      "track_image_url": "http://www.menucool.com/slider/jsImgSlider/images/image-slider-2.jpg",
      "sessions": [
       {"id": 2, "title": "Session two"},
       {"id": 4, "title": "Session Four"}
       ]
    },
    ...
  ]
}
```

@leto Should I use the above schema (listing IDs and titles for Sessions) or just keep it like it is for Speakers (https://github.com/fossasia/open-event/blob/master/API.md#speakers), list only the IDs.

**Comment by aditya1702** [comment]
@leto I think it would be nice if the session names are also displayed rather than just their ids.What do you say?

**Comment by leto** [comment]
Yes, titles and id's for sessions sound good. What if there are hundreds of sessions? Will the sessions be paginated?

**Comment by shivamMg** [comment]
@leto @aditya1702 ...a different discussion than above.

Suppose there are two sessions: Session1 and Session2, and there are two tracks: Track1 and Track2.

I'm adding Session1 and Session2 as sessions for Track1. Now I edit Track2 (which previously didn't have any sessions) and add Session1 & Session2 to it. This makes Track1 to lose both sessions. This shouldn't be the case. If a session has been associated with a track, other tracks should not be allowed to use that session.

The correct way to implement this is to let a session select a track, instead of letting a track select multiple sessions.

To reflect it in forms, the session form should have a select-one-track field, instead of the track form having a select-multiple-sessions field. This also makes our forms more coherent with the API.

**Comment by leto** [comment]
@shivamMg agreed, sessions should have zero or one tracks associated to it, instead of tracks having multiple sessions

**Comment by shivamMg** [comment]
@leto Then I think I'll implement this before solving the above API issue.

**Comment by shivamMg** [comment]
@leto Fix for track-session: https://github.com/fossasia/open-event-orga-server/pull/282

**Comment by shivamMg** [comment]
@leto About the track API issue, I just checked the Speakers API, it already serializes sessions as a list with `id`s and `title`s, and not just a list with integer ids like it's written in the [spec](https://github.com/fossasia/open-event/blob/master/API.md#speakers). Seems like it hasn't been updated, I've submitted a PR with the correct spec [link](https://github.com/fossasia/open-event/pull/36).

**Comment by shivamMg** [comment]
Also, I put up some thoughts into the pagination requirement for sessions list in Speakers and Tracks API (and the speakers list in Session API). 

> What if there are hundreds of sessions? Will the sessions be paginated?

I think it might not be needed because even if there are many sessions it is unlikely that a single session will have many speakers, or a single speaker will be associated with a large number of sessions.
