### ISSUE TITLE
'External Event URL' field  not shown on event create in public page

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#2741]
If I fill in directly the external event URL it is not shown but if I add a social link and fill it, then it is shown..

filled data:
https://cloud.githubusercontent.com/assets/20799954/21501567/e84a3056-cc6e-11e6-910c-514e6768bb46.png

output:
https://cloud.githubusercontent.com/assets/20799954/21501565/e74a55c8-cc6e-11e6-902b-dc99a58379d1.png

**Comment by SaptakS** [comment]
I think event_url is not getting saved in the Database at all since there is no code in the backend. @magdalenesuo can you add that?
