### ISSUE TITLE
SAWarning: The IN-predicate on "ticket.Id" was invoked with an empty sequence.

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2748]
I am getting this error on creating an event in my local system:

![screenshot from 2016-12-28 21-00-16](https://cloud.githubusercontent.com/assets/9530293/21525075/c096329e-cd40-11e6-852f-0f3e410537f3.png)

**Comment by niranjan94** [comment]
@SaptakS it's just a warning right ? Does it break functionality ?

**Comment by SaptakS** [comment]
@niranjan94 it gives 404 on publishing event. See the POST request below. It gives error to save event.

**Comment by niranjan94** [comment]
`404` ?! That isn't due to the warning .... Something else seems to be causing it here ,.,

**Comment by niranjan94** [comment]
@SaptakS found it. Due to https://github.com/fossasia/open-event-orga-server/pull/2706. will fix
