### ISSUE TITLE
'External Event URL' link shows on page even when no link is given as input.

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#2749]
https://cloud.githubusercontent.com/assets/20799954/21525255/0b2c4202-cd42-11e6-92cf-15bb5bf0dba0.png

**Comment by SaptakS** [comment]
@magdalenesuo you want to solve this?

**Comment by magdalenesuo** [comment]
@SaptakS Yes. Already solved XD sending PR
