### ISSUE TITLE
Custom roles functionality broken

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2754]
As seen below, I created a custom role superman with access to modules,reports and messages panels.
![selection_035](https://cloud.githubusercontent.com/assets/13910561/21529947/2ede1560-cd63-11e6-8c30-676caf1c2571.png)

I assigned the custom role to a different user.
![selection_034](https://cloud.githubusercontent.com/assets/13910561/21529948/2ee1f3f6-cd63-11e6-800e-c8d3c8e0a832.png)

But the user is still not able to access the specified panels.
![selection_036](https://cloud.githubusercontent.com/assets/13910561/21529949/2f9b9176-cd63-11e6-826d-c384b3f4b75f.png)

Steps to recreate the issue:
- Create a custom role
- Assign that role to a different user
- After assigning, try to access the respective assigned panels from the different user account

**Comment by niranjan94** [comment]
@shubham-padia could you clearly explain this issue ? 

(In future, don't just add screenshots with a generic title .. Give a description :) )

**Comment by shubham-padia** [comment]
@niranjan94 Updated the description.
