### ISSUE TITLE
No link for user with custom roles to access their designated tabs.

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2756]
- [ ] Add link to the first-found accessible tab in dropdown menu
- [x] Show only those tabs to which user has access to ( #2673 )

![selection_039](https://cloud.githubusercontent.com/assets/13910561/21530290/a5febbe8-cd65-11e6-8b04-b66a43599285.png)

**Comment by shubham-padia** [comment]
We can list all the admin tabs he/she has access to, in the profile dropdown (the one with logout option)  menu itself.
@niranjan94 @SaptakS Your views ?

**Comment by niranjan94** [comment]
@shubham-padia no. Let there be a link to /admin/ provided there. Let's keep that drop down simple and clean.

**Comment by shubham-padia** [comment]
@niranjan94 Agreed. But a link to `/admin/` will give the user access denied as the user does not have access to all tabs. Alternatively we could give a link to one of the tabs user has access to.
e.g If the user has access to `reports`,`modules` and `sales`, we cound give a link to `/admin/reports/` in the dropdown, but then the user would have to click all the other tabs(refer below point) visible to him to make sure which tabs he has access to.

Also, as seen below, even though the user has access to limited no. of admin tabs, he sees all the other tabs as an option. Is this the expected behaviour or should changes be made to this too.
![selection_040](https://cloud.githubusercontent.com/assets/13910561/21541264/fc278002-cdda-11e6-9a77-0c1502e0edbf.png)

**Comment by niranjan94** [comment]
Or we could have a basic landing page which shows all the tabs that the user has access to along with some very basic information from `/admin/` for those who do not have access to `/admin/`. 

Let's try to keep the dropdown clean and minimal.

**Comment by shubham-padia** [comment]
@niranjan94 Yeah, that sounds good. 
Also about 

> some very basic information from /admin/

What should be included in that particularly?
