### ISSUE TITLE
issue in social websites

### ISSUE THREAD

**Issue by kshitijsingla** [fossasia/open-event-orga-server#2762]
Social website section is not appearing and while editing the links dissapear after saving.

**Comment by SaptakS** [comment]
@kshitijsingla can you elaborate? Seems to work fine for me:

Social section
------------------
![screenshot from 2016-12-29 18-16-34](https://cloud.githubusercontent.com/assets/9530293/21544210/2ac518d0-cdf3-11e6-822d-7bd8310d024a.png)


Editing social link
----------------------
![screenshot from 2016-12-29 18-17-01](https://cloud.githubusercontent.com/assets/9530293/21544213/369a35c8-cdf3-11e6-9023-d79538b6261d.png)

**Comment by kshitijsingla** [comment]
i did the same and saved.But when we open again its not working.It will vanish(the address)  and there is no output.I don't if it's happening only with me.

**Comment by niranjan94** [comment]
@kshitijsingla what address did you type ? If the address you typed is invalid, it will not be saved.

**Comment by mariobehling** [comment]
Having the same issue: When I type in an URL into "External Event URL" on Chromium browser freezes and the page shows an error message. Also cannot copy/paste event URL: http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=48946

![screenshot from 2016-12-29 14-53-49](https://cloud.githubusercontent.com/assets/1583873/21545297/d33c2110-cdd6-11e6-88d5-6513ec00248f.png)

**Comment by kshitijsingla** [comment]
![screenshot from 2016-12-29 19-37-37](https://cloud.githubusercontent.com/assets/24763978/21545602/e6a3a25a-cdfe-11e6-9563-c5a1dbb6067e.png)
i write here the link   AND THEN
![again](https://cloud.githubusercontent.com/assets/24763978/21545609/f91448d6-cdfe-11e6-8bf7-56f7d6f50184.png) AND I CAME HERE BUT FOUND NOTHING BECAUSE 
![nothing](https://cloud.githubusercontent.com/assets/24763978/21545650/4365b32a-cdff-11e6-981b-53cf81c17e74.png)

**Comment by SaptakS** [comment]
@kshitijsingla this happens in eventyay.com because it serves on the master branch and this issue was already fixed. It will start working once we merge development branch in master.

**Comment by kshitijsingla** [comment]
please let us know when its done.Thnx.
