### ISSUE TITLE
Adding addresses does not show up on map

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2764]
A number of addresses entered do not show up on the map (but they show up on the Google Maps site itself), e.g. Indian Institute of Technology Roorkee, Roorkee, Uttarakhand, India.

Also clicking on the extended address fields does not let users enter addresses.

![screenshot from 2016-12-29 14-47-04](https://cloud.githubusercontent.com/assets/1583873/21545201/dc1953b2-cdd5-11e6-9858-fdb5dbc08c4a.png)

**Comment by niranjan94** [comment]
Will check it out now

**Comment by niranjan94** [comment]
> A number of addresses entered do not show up on the map (but they show up on the Google Maps site itself), e.g. Indian Institute of Technology Roorkee, Roorkee, Uttarakhand, India.

@mariobehling the geocoding API itself returns zero results for that search. You can try searching for
`Indian Institute of Technology Roorkee, Roorkee, Uttarakhand, India` here https://developers.google.com/maps/documentation/javascript/examples/geocoding-simple at the official geocoding sample provided by google.

**Comment by SaptakS** [comment]
@mariobehling @niranjan94 a possible solution would then be to search for the closest like `Roorkee, Uttarakhand, India`. But I agree with @niranjan94 . It doesn't show up in geocoding.

**Comment by shubham-padia** [comment]
@mariobehling Any updates on this?

> A number of addresses entered do not show up on the map
The above comments seem to fix the issue

>  clicking on the extended address fields does not let users enter addresses.
Works as of right now ( on open event dev heroku)

Thanks.

**Comment by mariobehling** [comment]
Ok, great.
