### ISSUE TITLE
Editing and removing social links doesn't work

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2767]
Once I have created an event with suppose a facebook link, then I edit the event and remove the facebook link, the facebook link still stays and is not removed.

**Comment by magdalenesuo** [comment]
I think I'd like to try solve this.

**Comment by magdalenesuo** [comment]
I'd like to try and solve this

**Comment by SaptakS** [comment]
@magdalenesuo sure. go ahead
