### ISSUE TITLE
Anyone with access to users panel can assign others as admins

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2769]
[Roles.md](https://github.com/fossasia/open-event-orga-server/blob/development/docs/ROLES.md#site-specific-roles-staff) states that 

> Only the Super Admin can assign users as Admins.

Currently if the super-admin gives one of the users access to the `/admin/users` panel , the user can assign himself/herself or any other user as an admin by clicking on the edit icon under the options column.We can remove the edit icon if the person is not a super admin.

Same applies for the permissions tab,but IMO it should be left unchanged because:
the sole purpose of permissions tab is for role management,so if the super admin gives access of permissions tabs to a user, he/she will be doing it regardless of the consequences.

@SaptakS @niranjan94 Your views ?

**Comment by niranjan94** [comment]
> We can remove the edit icon if the person is not a super admin. 

Yes. Please do that. 

> Same applies for the permissions tab,but IMO it should be left unchanged because: the sole purpose of permissions tab is for role management,so if the super admin gives access of permissions tabs to a user, he/she will be doing it regardless of the consequences.

I agree with you

**Comment by shubham-padia** [comment]
Closed via #2772
