### ISSUE TITLE
Privacy/security: Admins can change personal details of any user

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2777]
Admins on clicking on the eye icon shown below on the users panel can view the personal details of any user and even edit them.
@niranjan94 @mariobehling @SaptakS Should this be allowed ?

![selection_046](https://cloud.githubusercontent.com/assets/13910561/21564097/492aa440-ceaf-11e6-8a43-7b6d1f950fce.png)
 
Steps to recreate:
- click on the specified eye button on any other use
- change name or any other details of the user
- save changes

**Comment by shubham-padia** [comment]
@mariobehling your views on this?

**Comment by SaptakS** [comment]
@shubham-padia I feel editing shouldn't be allowed.

**Comment by shubham-padia** [comment]
@SaptakS   I'll make relevant changes so that only the profile can be viewed and exciting is disabled.

**Comment by mariobehling** [comment]
Admins: This is a very small group. These are the people who run the system. Of course they are able to see and edit any user. This is just the same as in standard CMS like Drupal and Wordpress.

As the current behavior is the desired behavior, I am closing the issue.
