### ISSUE TITLE
Images not displayed from sponsors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2778]
![screenshot from 2016-12-30 17-04-21](https://cloud.githubusercontent.com/assets/1583873/21568116/154531ec-ceb2-11e6-9592-4eaa6227da3e.png)

Please compare: https://eventyay.com/e/ecc2001a

**Comment by mariobehling** [comment]
Going back to the editing tab for sponsors, shows "Google" on each sponsor list.

![screenshot from 2016-12-30 17-08-04](https://cloud.githubusercontent.com/assets/1583873/21568178/9c030e98-ceb2-11e6-9358-d89de46517fb.png)

**Comment by mariobehling** [comment]
As images get entered and the user proceeds to the next step, there is actually an error message on the bottom.

![screenshot from 2016-12-31 12-33-57](https://cloud.githubusercontent.com/assets/1583873/21577278/88503378-cf55-11e6-84e7-7bb07106fb87.png)

**Comment by SaptakS** [comment]
@mariobehling this is what I get on visiting the link [https://eventyay.com/e/ecc2001a](https://eventyay.com/e/ecc2001a):
![screenshot from 2017-01-03 20-30-13](https://cloud.githubusercontent.com/assets/9530293/21611606/87700974-d1f3-11e6-8fdf-27471e69f25b.png)

Am I missing something?

**Comment by mariobehling** [comment]
@SaptakS It was a long process to get these images on the site as a showcase. I had to enter the same image several times.

Please set up an event and add several sponsor images. Then save the event and go back to enter other sponsor images and repeat the process. You will encounter a number of issues and fails to save the data.

**Comment by SaptakS** [comment]
@mariobehling ok. I will check it more.

**Comment by SaptakS** [comment]
@mariobehling the problem is there is an error in saving. If you notice the snackbar, it is often giving an error for image upload and saving. But the thing is while editing, the wizard proceeds to next step and then gives error for the last step in snackbar, which is why it goes unnoticed. I am checking both of this errors. Will fix them.
