### ISSUE TITLE
Add more fileds to "Collect Speaker Details" on Wizard Step 3

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2782]
Please offer the collection of the following as well:
* [ ] City
* [ ] Sponsorship Required

**Comment by magdalenesuo** [comment]
Please assign me this as well

**Comment by SaptakS** [comment]
Yeah sure you can

**Comment by SaptakS** [comment]
Yeah sure you can

**Comment by magdalenesuo** [comment]
@mariobehling Should the 'sponsorship required' field be filled in by the user itself?

**Comment by mariobehling** [comment]
@magdalenesuo Yes, this should be a field with a paragraph, where the user can enter text.
