### ISSUE TITLE
Add levels of required expertise to list of "collect session details"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2784]
Many events have "Level" as an option for submissions of speaker proposals.

Please implement "Levels" in the API and offer this option in "collect session details" in the wizard step 3.

Levels needed are:
* Beginner
* Intermediate
* Advanced
* Other

**Comment by magdalenesuo** [comment]
Since I m looking into #2782, and this similar can I complete this along with it?

**Comment by SaptakS** [comment]
Ok... While you are at it, please also look at #2785 if you can... Thanks...

**Comment by magdalenesuo** [comment]
@SaptakS okay, sure. :)

**Comment by magdalenesuo** [comment]
@mariobehling Shouldn't the 'level' field be in session form and not in speaker form?

**Comment by mariobehling** [comment]
@magdalenesuo Yes, correct. It is correct in the heading, but was wrong in the description. Just corrected it. @SaptakS @niranjan94 This also needs to go into the API.

**Comment by SaptakS** [comment]
@mariobehling will look into that.
