### ISSUE TITLE
Some organizers would like to know how speakers know about their event - offer option in wizard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2786]
Some speaker submission forms have the question "Where did you hear about our event?" in their form. Please add this field as an option in wizard step 3.

**Comment by magdalenesuo** [comment]
I've worked on similar issue. Please let me work on this

**Comment by magdalenesuo** [comment]
@mariobehling should I put in dropdown menu to select from: 'friend', 'social media', 'website', 'other', etc? And give a space to fill in if 'other'?

**Comment by mariobehling** [comment]
Yes, sounds good. Thank you.
