### ISSUE TITLE
Do not add empty sponsor links on public event page if no link is defined

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2789]
Some organizers might not define links of sponsors. Currently there is an empty link set on the public event page.

Expected: No links to anywhere, if no sponsor links are defined.

![screenshot from 2016-12-31 12-41-43](https://cloud.githubusercontent.com/assets/1583873/21577308/a23b311a-cf56-11e6-987d-7e1ef2be6796.png)

**Comment by Marauderer97** [comment]
@mariobehling  I would like to work on this
