### ISSUE TITLE
Sponsorship details not saved or displayed properly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2790]
There are some issues with the sponsorship wizard:

* [x] Going back an forth between wizard steps results in sponsors not being saved
* [x] The order of sponsors sometimes changes after saving them
* [x] The sponsor levels are not made use of - sponsors are not displayed according to their level
* [x] The type information e.g. Gold is not saved in the form
* [x] The description is not displayed in the alt tag and therefore does not show up on scroll over the images

![screenshot from 2016-12-31 13-12-17](https://cloud.githubusercontent.com/assets/1583873/21577448/2516ad54-cf5b-11e6-8498-865da06dd6bc.png)

**Comment by rohithasrk** [comment]
@mariobehling : I'd like to work on this. Can you please help me with the files I'd need to look into?

**Comment by niranjan94** [comment]
@rohithasrk You can work on this :) try browsing through the code base. Start at the event creation wizard.

**Comment by SaptakS** [comment]
> The description is not displayed in the alt tag and therefore does not show up on scroll over the images

@mariobehling do you want me to show the description in form of tooltip? But then description having all the formatting doesn't make sense.

**Comment by mariobehling** [comment]
@SaptakS We are collecting the description with formatting. So, we can later add a "sponsors page", but this is lower priority. Still, the way it is, is good then. Tooltip sounds good for now, but the priority is to get the sorting right for now.

I will open another issue as I have some ideas how to improve this whole section. The first step before we make more substantial changes - is to make the current system work. Right now it does not. So, order and levels...

**Comment by SaptakS** [comment]
@mariobehling have implemented the sorting based on the level. Please check #2872

**Comment by SaptakS** [comment]
> The order of sponsors sometimes changes after saving them

The last edited sponsor gets shown at the last. Though this is a weird phenomenon but now since sorting is done based on level, the ordering inside a single level may change after editing but it will still be sorted based on levels.
