### ISSUE TITLE
Speaker submissions not saving full data set

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2792]
I activated all fields for the sample speaker submissions at https://eventyay.com/e/ecc2001a/cfs/new/

Unfortunately the following data is not saved or displayed when the speaker edits the proposal:
* [ ] COMMENTS
* [ ] LANGUAGE
* [ ] SLIDES
* [ ] VIDEO
* [ ] AUDIO
* [ ] SPEAKER AVATAR IMAGE
* [ ] LONG BIOGRAPHY
* [ ] MOBILE 
* [ ] FACEBOOK 
* [ ] TWITTER 
* [ ] GITHUB 
* [ ] LINKEDIN

**Comment by shubham-padia** [comment]
I would like to try this

**Comment by SaptakS** [comment]
@shubham-padia I think it's best to start this issue after #2782 #2784 and #2785 are solved.. Once they are solved I think you can start with this one. Please try and pick some other issue

**Comment by shubham-padia** [comment]
@SaptakS Sure

**Comment by magdalenesuo** [comment]
@shubham-padia Shubham, are you still working on this issue? If not, I would like to work on this, because I just finished similar issues..

**Comment by shubham-padia** [comment]
@magdalenesuo Yeah, I've started on this since the above issues were solved today :smiley:
