### ISSUE TITLE
Connecting with Facebook does not save credentials in profile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2793]
The Facebook credentials do not get saved in the account.

![screenshot from 2016-12-31 15-34-22](https://cloud.githubusercontent.com/assets/1583873/21577966/bb868d78-cf6e-11e6-9c6a-ead40412110a.png)

**Comment by shubham-padia** [comment]
Weird :confused: , works good on open-event-dev.herokuapp.com.
Sign in with facebook also doesn't work on eventyay.
It may happen that this is a problem with the fb-app set up for eventyay.
