### ISSUE TITLE
Improve Accepting/Rejecting Speaker Sessions with Email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2796]
When an organizer accepts or rejects the speaker session there is an option to send out an email. Please enhance this feature as follows:

* [x] After the organizer clicks the symbol "accept or reject with mail" open a pop up lightbox with the email
* [x] Make the email subject and content editable
* [x] Add the buttons "Accept and Send Mail" or "Reject and Send Mail" to the button
* [x] Also add a "Cancel" button

![screenshot from 2016-12-31 15-49-12](https://cloud.githubusercontent.com/assets/1583873/21578020/18e89086-cf71-11e6-9af6-c04c2c12141b.png)

**Comment by nikhilrayaprolu** [comment]
@mariobehling what is the minimum setup I could do to work with this(like setting up an smtp server) ?
does running  the python builtin smtp server works?
"sudo python -m smtpd -n -c DebuggingServer localhost:25" if so how should I configure it?
I think I figured out how to work with this issue

**Comment by niranjan94** [comment]
@nikhilrayaprolu you do not need any of that :) .. All you need is a gmail account. Configure the gmail smtp settings at `/admin/settings/` .

**Comment by nikhilrayaprolu** [comment]
I have tried configuring the settings ,ended up with errors`
ERROR/MainProcess] Task send.email.post.smtp[a58e3232-ffe2-42d0-ad53-03dc4dc6b980] raised unexpected: KeyError('encryption',)`

![screenshot from 2017-01-08 02-07-25](https://cloud.githubusercontent.com/assets/15216503/21744990/3d791dfe-d547-11e6-99b2-506621ef6dae.png)

what might be causing the problem?the above image shows my settings

**Comment by niranjan94** [comment]
@nikhilrayaprolu thanks :) Have been fixed at #2869

**Comment by nikhilrayaprolu** [comment]
@niranjan94 @mariobehling can I know a route where lightbox has been implemented in openevent .so that I could follow the same pattern.

**Comment by niranjan94** [comment]
@nikhilrayaprolu we have modal windows in the event wizard, the home page for showing the share link etc ..
