### ISSUE TITLE
Do not call Stripe API for free tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2798]
When ordering a free ticket the Stripe API put out a pop up. Avoid any API calls of payment services for free tickets.

![screenshot from 2016-12-31 16-33-46](https://cloud.githubusercontent.com/assets/1583873/21578178/0ad0d214-cf77-11e6-9505-a61cd4943e4d.png)

**Comment by shubham-padia** [comment]
I would like to try to solve this.

**Comment by SaptakS** [comment]
@shubham-padia sure go ahead.
