### ISSUE TITLE
Add email confirmation message "Email has been sent.." to ticketing confirmation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2799]
If a user orders a ticket, there is a confirmation page.

Please add a message on top "An email with the ticket has also been sent to your email account."

![screenshot from 2016-12-31 16-36-17](https://cloud.githubusercontent.com/assets/1583873/21578197/739afdec-cf77-11e6-9a63-a5802cc95e9b.png)

**Comment by magdalenesuo** [comment]
Can I work on this?
