### ISSUE TITLE
Ticket buyer does not receive email with ticket

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2800]
After buying a ticket as an anonymous user, the user receives an email "Welcome to eventyay.. Your account has been created".

Expected behavior would be:

**1) The buyer receives an email with the ticket attached.**

After buying a ticket as an anonmyous user, the user should receive an email:

"Your ticket to event ..."

"Hi, this is your registration confirmation for .... on ... (date)...

The event is organized by ... (organizer)...

Log in to manage your orders at http://eventyay.com.

**2) The buyer receives the registration email**

The registration email "Welcome to eventyay" as of now.

**Comment by arpitn30** [comment]
I'll check out

**Comment by arpitn30** [comment]
Is the email system working on Heroku Deployed development branch??

**Comment by Marauderer97** [comment]
@mariobehling Can I work on this?

**Comment by arpitn30** [comment]
@Marauderer97 Are you still working on this issue? I'd like to try this one

**Comment by Marauderer97** [comment]
@arpitn30 Yes I am. Facing an issue with setting up the mail service as of now.

**Comment by shubham-padia** [comment]
@Marauderer97 If you are facing an issue with setting up the mail service, please take up another issue for now, so that we can move faster towards a beta release. There are many other open issue unrelated to mail. Thank you. :smile:
