### ISSUE TITLE
Add progress upload bar and list uploaded items in Call for Speakers form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2801]
The call for speakers form can have upload buttons for slides, video and audio. Currently it does not show that an item is uploaded and it does not show the upload progress. Please implement the following:

* [x] Show upload progress
* [ ] Add "Add More" - Enable upload of several items
* [x] Offer delete functionality
* [x] List uploaded files in the form (currently they are not shown)

![screenshot from 2016-12-31 16-56-27](https://cloud.githubusercontent.com/assets/1583873/21578284/91d1c37e-cf7a-11e6-83e7-a7185ed13c87.png)

**Comment by nikhilrayaprolu** [comment]
@mariobehling I would like to work on this issue.

**Comment by hoangvanthien** [comment]
@nikhilrayaprolu I also want to discover on this issue. :)

**Comment by nikhilrayaprolu** [comment]
@mariobehling I dont find any implementation regarding video and audio as shown in your image in openeventdev heroku server. Is it recently implemented which isn't updated yet? 
![screenshot from 2017-01-05 20-24-08](https://cloud.githubusercontent.com/assets/15216503/21684885/6faa192c-d385-11e6-8852-bbc7624d2526.png)

**Comment by niranjan94** [comment]
@nikhilrayaprolu it's custom form field. It'll be displayed only when it is turned on in the custom forms settings

**Comment by nikhilrayaprolu** [comment]
@niranjan94 where can I turn on it?

**Comment by niranjan94** [comment]
Step 3 of the event creation wizard

**Comment by hoangvanthien** [comment]
@niranjan94 When the upload buttons are clicked, which scripts will be run? Can you give the link to that files?

**Comment by nikhilrayaprolu** [comment]
@niranjan94 @mariobehling I see that as and when the submit button is clicked ,the files are being uploaded now  along with form data.

- so a way to show upload progress is by uploading the documents immediately when they are selected(something as done by gmail while sending mail)(upload for each individual file can be shown).here we have to implement  back end functions which handle the uploads.


- or other way is doing the upload when the submit is done (similar to the present structure) but show the progress of upload  (show progress of the whole as one process) In this way code may not change much only extention to the present structure is tracking how much data is passed to the backend
or any suggestions by you? which one would be better

**Comment by SaptakS** [comment]
@nikhilrayaprolu do the first one. Use ajax and do it like it is done for images.

**Comment by SaptakS** [comment]
@nikhilrayaprolu what is the status of this???

**Comment by shubham-padia** [comment]
@mariobehling @niranjan94 @SaptakS What are your opinions about using this plugin: https://blueimp.github.io/jQuery-File-Upload/.

**Comment by niranjan94** [comment]
@shubham-padia we don't need another plugin for this. Our js files are already going out of control. We'll just still with jQuery's ajax and get the progress from there.

**Comment by shubham-padia** [comment]
+1, I'll start work on it tonight.

**Comment by niranjan94** [comment]
API work will continue in #3590
`frontend` tag added. Appropriate issue will be created on frontend repo and linked to this.
