### ISSUE TITLE
Propose and implement speaker profiles

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2802]
The goal of this feature is, to allow speakers to have different description and bios for different events.

A speaker can save their profile, copy and edit it.

The profile page at https://eventyay.com/profile/ should show the following:
* [ ] A standard profile (withh all possible form fields)
* [ ] A dropdown menu for specific event profiles (with the available form fields of that event)

**Comment by arpitn30** [comment]
I'd like to work on this

**Comment by niranjan94** [comment]
@arpitn30 good to know that you're interested :) ... But as you can see this issue is labeled as `later` which means, we're first looking to solve the bugs in the system first. So, browse through the issues available and help us fix the bugs soon :)

**Comment by niranjan94** [comment]
API work will continue in #3591
`frontend` tag added. This issue will be cloned to the frontend repo.
