### ISSUE TITLE
Implement Apps similar to twitter applications page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2803]
Connected apps are not currently implement in a clear way, e.g. Google does not show up anywhere as a connected app.

Please create a tab "Applications" in the settings list at https://eventyay.com/settings/ similar to twitter and move the connected accounts from "Profile" here.

![screenshot from 2016-12-31 21-18-38](https://cloud.githubusercontent.com/assets/1583873/21579106/bfa95572-cf9e-11e6-9d4b-2c56970b43e7.png)

Change the display as connected (instead of a link display like on the profile).

Ensure the connections for the following show up:
* [ ] Facebook
* [ ] Google
* [ ] Twitter
* [ ] Instagram

![screenshot from 2016-12-31 20-49-04](https://cloud.githubusercontent.com/assets/1583873/21579052/e9a39d14-cf9a-11e6-89c1-555add656ff9.png)

**Comment by gaeun** [comment]
@mariobehling Can I work on this please?

**Comment by Elgayar** [comment]
@mariobehling @gaeun Has this issue been solved?

**Comment by gaeun** [comment]
@Elgayar Yeah, refer to PR #2803. I just have to fix Travis errors.

**Comment by mariobehling** [comment]
Thanks for the last PR. The issue is not solved entirely yet. So help is welcome. Also see my comments here, please: https://github.com/fossasia/open-event-orga-server/pull/2839#issuecomment-271061446

**Comment by arpitn30** [comment]
I fixed the "Facebook does not show up" bug, should a put up a pull request or solve other bugs too before doing so?

**Comment by mariobehling** [comment]
@arpitn30 Please make a PR and mention that it "partly fixes" the issue.

**Comment by poush** [comment]
Also, I think we need to add a check as well where fields of those platforms will not be shown for which app token and secret in admin setting isn't set

**Comment by niranjan94** [comment]
@poush we already have an OAuth implementation in the server. (we use it for login now). Please reuse the existing implementation and not add more libraries.

**Comment by poush** [comment]
@mariobehling @niranjan94 Are we looking to store the tokens as well to perform any actions like giving option user/organizer to post on their page automatically?

**Comment by poush** [comment]
@mariobehling Are we expecting experience similar to this below
![screenflow](https://cloud.githubusercontent.com/assets/1812082/26278407/9d387716-3db7-11e7-8b39-46e026dd0926.gif)

**Comment by niranjan94** [comment]
@poush
