### ISSUE TITLE
Event Ticket time start on local PC time instead of Time of Event location

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2805]
After the user entered the ticket, the ticket time starting the sales is automatically chosen - as the current time.

The time displayed is the current ticket time of the time zone. If the timezone of the user/PC is different to the timezone of the event, the ticket time still shows the PC timezone.

Expected behavior: Show the timezone of the event and make all ticket sales according to the event timezone.

![screenshot from 2016-12-31 22-19-44](https://cloud.githubusercontent.com/assets/1583873/21579287/9288d848-cfa7-11e6-9d1f-95c161a0723d.png)

**Comment by shubham-padia** [comment]
I'd like to work on this.
