### ISSUE TITLE
Errors showing ticketing info 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2806]
The ticketing box has the following issues:

* [ ] It shows "the ticket sales will start.." even though the ticket sales start time is in the past
* [ ] It does not show a box to choose multiples tickets

![screenshot from 2016-12-31 22-23-32](https://cloud.githubusercontent.com/assets/1583873/21579296/f338725c-cfa7-11e6-9f75-2af8330e07a2.png)

**Comment by shubham-padia** [comment]
I would like to work on this.

**Comment by shubham-padia** [comment]
Solved via #2822
