### ISSUE TITLE
Ticket price and Paypal email not saved

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2807]
Cannot save ticket price and paypal email.

![screenshot from 2016-12-31 22-28-05](https://cloud.githubusercontent.com/assets/1583873/21579307/8519c374-cfa8-11e6-92c8-0fcd8260a41c.png)

**Comment by Marauderer97** [comment]
@mariobehling I would like to work on this

**Comment by Marauderer97** [comment]
@mariobehling Was able to replicate the error, 1 clarification though, this happens only when i want to edit an existing event. Initially the ticket price and the email get stored, but if I try to add them after an event is already created, it reports "Error saving changes"

**Comment by mariobehling** [comment]
@Marauderer97 Yes, it is probably the same. Thank you.
