### ISSUE TITLE
Form conflicts entereing address and not possible to move location point

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2810]
When a user enters an address into the first field and then tries to enter additional info into other address fields the first fields gets deleted.

Expected: It should be possible to enter full addresses and move the location point on the map.

![screenshot from 2017-01-01 13-51-08](https://cloud.githubusercontent.com/assets/1583873/21581240/98e56e54-d029-11e6-9590-2dd0b967945e.png)

**Comment by gaeun** [comment]
This works well on https://open-event-dev.herokuapp.com but not on https://eventyay.com/. Should this still be fixed?

**Comment by niranjan94** [comment]
@gaeun ... If it works well on open-event-dev it's enough ... eventyay is deployed from the master branch. So, when the master is updated, eventyay will also be fixed

**Comment by satwikkansal** [comment]
@niranjan94 I'm facing the same issue while using `eventlet` server in my local machine. Whenever I start typing into the addition info fields, everything resets. Any idea how to resolve this?

**Comment by PARAG00991** [comment]
I'd like to work on this.

**Comment by eMBee** [comment]
where do i report that aparently the master is still not updated because moving the event location does not work there now? or is that a regression?
