### ISSUE TITLE
Image proportions incorrect on front page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2812]
The uploaded images are not scaled and cropped correctly. Instead it appears that they are stretched.

![screenshot from 2017-01-01 14-04-38](https://cloud.githubusercontent.com/assets/1583873/21581278/5dc2a8c6-d02b-11e6-84d8-103c8b16a5d0.png)

**Comment by SaptakS** [comment]
@mariobehling I have fixed the aspect ratio code. This should fix the issue. Previously irrespective of the aspect ratio, the image was being resized to 500 X 200 which resulted in stretching. #2838
