### ISSUE TITLE
Changes in ticketing cause error and do not get saved

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2813]
Changes in ticketing result in error message and do not get saved, e.g. date ticket sales ends.

![screenshot from 2017-01-01 14-07-46](https://cloud.githubusercontent.com/assets/1583873/21581282/c77b4a2a-d02b-11e6-9052-17a892e8c219.png)

**Comment by Marauderer97** [comment]
@mariobehling I'll try working on this, it is an extension of issue 2807

**Comment by mariobehling** [comment]
Re-opening: The last merge to master deployed the system to the eventyay site. Paypal email still does not get save in the create event wizard.
