### ISSUE TITLE
Discount Codes not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2815]
* [x] Applying a discount code results in a message "The promotional code entered is valid. No offer has been applied to this order."
* [x] Trying to edit a discount codes shows that parameters have not been saved including
   * [x] Percent
   * [x] All other options
* [x] For "Amount" it is only possible to enter full numbers. Please ensure e.g. amounts like 5.95 USD can be entered.

![screenshot from 2017-01-01 14-30-43](https://cloud.githubusercontent.com/assets/1583873/21581347/42173b56-d02f-11e6-876f-0210ab2b6309.png)

**Comment by nikhilrayaprolu** [comment]
@mariobehling for the third task. I think adding a drop down to select currency type would work?

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this.

**Comment by mariobehling** [comment]
@CosmicCoder96 Let's do this task as first come, first claim, ok? But there are many other tasks. Please feel free to claim any other issue. Thank you.

**Comment by CosmicCoder96** [comment]
@mariobehling Of course.Thank you.

**Comment by nikhilrayaprolu** [comment]
@mariobehling it looks like nothing has been implemented for the discount functionality.
https://github.com/fossasia/open-event-orga-server/blob/development/app/helpers/ticketing.py#L209
I am working on this issue by creating functionality for giving discounts

**Comment by mariobehling** [comment]
@niranjan94 Please provide input, if any. Thank you.

**Comment by niranjan94** [comment]
@mariobehling the PR #2840 looks good to me. But needs fixing since travis is failing

**Comment by niranjan94** [comment]
And yes. Looks like discounts were never added to the code that calculates the order amount. :sweat:

**Comment by mariobehling** [comment]
Thanks. Please test this more in detail. Found some things on a quick look:

* [ ] deleting items in "amount" shows error on "Amount" and "Percentage"
* [ ] ticks or crosses overlap on form field
* [ ] If one field has an error all fields show an error

![screenshot from 2017-01-07 05-21-54](https://cloud.githubusercontent.com/assets/1583873/21739364/7ec773b8-d499-11e6-91d4-748fb20fcaee.png)

* [ ] Cannot see my "max" or "min" number - display is hidden

![screenshot from 2017-01-07 05-22-32](https://cloud.githubusercontent.com/assets/1583873/21739368/8f40292e-d499-11e6-8343-6def970fdbb7.png)

* [ ] Any date or time I enter, it is not possible to see it, e.g. show "0" on date always

![screenshot from 2017-01-07 05-25-14](https://cloud.githubusercontent.com/assets/1583873/21739380/c38ee4c2-d499-11e6-81eb-330e9cde8824.png)

**Comment by Abhi2424shek** [comment]
I think @mariobehling add this to the issue body helps a lot, it's just a thought!

**Comment by nikhilrayaprolu** [comment]
@mariobehling I will work on this today and update.

**Comment by vishalburri** [comment]
This looks like a beginner bug .. can i work on this ..

**Comment by nikhilrayaprolu** [comment]
@vishalburri ok you can proceed on this. I would suggest you to look at boostrap validator library

**Comment by magdalenesuo** [comment]
I would like to work on this if no one else is working on it.
