### ISSUE TITLE
Search field no longer defined according to IP location

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2816]
It seems the search is now always "United States" instead of offering the search according to location of the user defined by the IP.

![screenshot from 2017-01-01 15-13-56](https://cloud.githubusercontent.com/assets/1583873/21581530/169c2bac-d035-11e6-93f8-2f39528d5cf1.png)

**Comment by Abhi2424shek** [comment]
Why don't we add a drop down which defaults to the current location using the geo api? The geo api gives more accurate country results than IP address. Besides we have our own geolocation project!

**Comment by shubham-padia** [comment]
@mariobehling Issue exists on: #2722 .
