### ISSUE TITLE
Improve language listings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2817]
Please change as follows:
* [x] reduce space between languages to show more languages in one space
* [x] For Chinese only show a) Chinese (Simplified) and b) Chinese (Traditional)

**Comment by magdalenesuo** [comment]
@mariobehling I'd like to do this

**Comment by SaptakS** [comment]
@magdalenesuo sure... go ahead...

**Comment by mariobehling** [comment]
Please avoid deleting existing translations.

Chinese (Taiwan) = Traditional Chinese
Chinese (China) = Simplified Chinese

The idea of this issue was not to get rid of any versions, but to unify versions.

Please do not use anything else except "Traditional Chinese" and "Simplified Chinese" and move existing translation to the relevant version.

**Comment by mariobehling** [comment]
I would not want to open a specific issue, cause I think it is maybe clear:
* Please sort languages alphabetically in list
