### ISSUE TITLE
Pre-filled event dates should be one month in future

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2819]
The pre-filled event dates used to be in the future and are currently showing "the current date".

Please re-implement the future pre-fill.

Show event dates one month in advance and ensure start time is before end time.

![screenshot from 2017-01-02 00-00-02](https://cloud.githubusercontent.com/assets/1583873/21583381/95d62f5a-d07e-11e6-8a69-1c3191f3b1bb.png)

Testing at this moment it shows start time before end time.

![screenshot from 2017-01-02 00-01-45](https://cloud.githubusercontent.com/assets/1583873/21583385/b38e82c2-d07e-11e6-9ed7-e4da181782d3.png)

**Comment by Marauderer97** [comment]
@mariobehling the end time has been set to 22:00 default, what do you think the end time should be if the current time(which the start time is set to) is later than 22:00?

**Comment by mariobehling** [comment]
> I think, setting the start time to a default (of say 10:00 )instead of current time can be a solution to this.
Sounds good. But: 1 month in the future of the current date.

> the end time has been set to 22:00 default
If the pre-filled start time is 10 AM, the end time should be something like 5PM.
