### ISSUE TITLE
Add fields in speaker-session in API

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2824]
Speaker Form
- [ ] City
- [ ] Sponsorship Required
- [ ] Speaking Experience
- [ ] WHERE DID YOU HEAR ABOUT OUR EVENT?

Session Form
- [ ] Level of Session

API version for issue #2782 #2784 #2785 #2786

**Comment by satwikkansal** [comment]
@aviaryan @SaptakS Shall I work on this issue?

**Comment by aviaryan** [comment]
@satwikkansal Yes, please proceed.

**Comment by aviaryan** [comment]
@SaptakS 
Is there a need to add these fields to Speakers API? IMO we should add them for completeness. 
If not, then maybe this issue can be closed.

**Comment by SaptakS** [comment]
@aviaryan I think the speaker fields should be added for completeness.

**Comment by aviaryan** [comment]
@SaptakS ok, will do it. I will also write some tests for them.
