### ISSUE TITLE
The inputs of the event's location aren't working well

### ISSUE THREAD

**Issue by Heredroky** [fossasia/open-event-orga-server#2836]
When I try to write something on event's location inputs, they don't work properly. If it should work like that, then I will close this issue, but if it is a bug, it has to be solved.

![giphy 1](https://cloud.githubusercontent.com/assets/15079370/21623202/4e1e262a-d1cf-11e6-8572-75c039664a1f.gif)

**Comment by gaeun** [comment]
I think this is redundant with #2810...

**Comment by niranjan94** [comment]
Closing in favor of #2810
