### ISSUE TITLE
Configure Coveralls and CircleCI

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#284]
Configure coveralls to exclude check on site-packages. e.g. In [this](https://coveralls.io/builds/6142318) build it is checking coverage for code outside our repo.

Configure CircleCI. It is running our tests with `python manage.py test` (incorrect command) while it should be running nosetests. e.g. [here](https://circleci.com/gh/fossasia/open-event-orga-server/2#tests).

**Comment by aviaryan** [comment]
I will try fixing the CircleCI build :smile:

**Comment by aviaryan** [comment]
CircleCI Fixed #286

**Comment by aviaryan** [comment]
Now working on coveralls fix :smile:

**Comment by aviaryan** [comment]
Coveralls fixed #287

**Comment by juslee** [comment]
Removed CircleCI in favour for TravisCI instead.
