### ISSUE TITLE
Free tier orders and discount should show up on order summary

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2846]
Adding a ticket as an event organizer does not show "free tier" info on the order summary.

Expected: Above total number line, there should be a line in the table "free ticket" -50 USD. (or whatever the ticket cost would have been)

![screenshot from 2017-01-07 05-51-21](https://cloud.githubusercontent.com/assets/1583873/21739557/15f728d8-d49e-11e6-8887-a8d915e8f0d4.png)

**Comment by shubham-padia** [comment]
I'd like to work on this

**Comment by shubham-padia** [comment]
> there should be a line in the table "free ticket" -50 USD

I'm assuming free ticket here refers to a discount code. Please correct me if I'm wrong :)
