### ISSUE TITLE
Design bugs

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/open-event-orga-server#2848]
There are a lot of design flows i encountered on a quick look feel free to post more, here are the issues, and tick the check boxes after each one is resolved:

- [ ] Buttons sitting very close in create event page:
![screenshot_2017-01-07-10-38-50-113_com android chrome](https://cloud.githubusercontent.com/assets/8947010/21739644/c69b1816-d4c6-11e6-96bf-8264520b2283.png)

- [ ] Apply discount button overlaps on mobile:
![screenshot_2017-01-07-10-38-09-738_com android chrome](https://cloud.githubusercontent.com/assets/8947010/21739645/d201092c-d4c6-11e6-9801-7a0eef2eb098.png)

- [ ] Loader not aligned to center in create an event page:
![screenshot_2017-01-07-10-37-09-936_com android chrome](https://cloud.githubusercontent.com/assets/8947010/21739646/e0ace1d0-d4c6-11e6-849c-7198d7cbae6d.png)

- [ ] Text not aligned to center in my tickets page:

- [ ] Call for speakers button overlaps:
![screenshot_2017-01-07-10-36-09-757_com android chrome](https://cloud.githubusercontent.com/assets/8947010/21739650/f54cd348-d4c6-11e6-8b5e-5c98cdcd9b7e.png)

- [ ] ~~About page in the site is empty:~~  Show default text in system pages, e.g. [About Page](open-event-dev.herokuapp.com/about/)
![screenshot_2017-01-07-10-02-35-870_com android chrome](https://cloud.githubusercontent.com/assets/8947010/21739651/fd7248aa-d4c6-11e6-8403-531750767a53.png)

- [ ] Icons in ticket details fields group flows out:
![screenshot_2017-01-07-10-38-00-200_com android chrome](https://cloud.githubusercontent.com/assets/8947010/21739653/0589d404-d4c7-11e6-9974-571ee52b6981.png)

Happy coding

**Comment by magdalenesuo** [comment]
I'd like to solve this

**Comment by SaptakS** [comment]
@abhi2424shek tell me one thing. Why is text not aligned to centre in ticket an issue? Don't you think that was done by choice?

**Comment by Abhi2424shek** [comment]
It's on two pages

**Comment by SaptakS** [comment]
> It's on two pages

Can you provide links?

**Comment by Abhi2424shek** [comment]
@SaptakS https://open-event-dev.herokuapp.com/mytickets/ and https://open-event-dev.herokuapp.com/events/create/ please remember to login first !

**Comment by SaptakS** [comment]
> please remember to login first !

@Abhi2424shek I think this was my GSoC project and being one of the maintainers and upstream contributors of this project I think I know in which page I need to login first. Thanks for reminding me however... 

And the left alignment was chosen during designing. It's not a bug. Please do proper research before creating an issue or commenting on it. I think you haven't gone through the pages properly and seen the entire project properly. Both the pages have Left Alignment by choice. So not being center aligned isn't a bug. 

Next time please go through properly every page before commenting and creating issue. 

Thanks. Happy Contribution.

**Comment by Abhi2424shek** [comment]
@SaptakS I never mentioned to annoy you.

> And the left alignment was chosen during designing. It's not a bug. Please do proper research before creating an issue or commenting on it. I think you haven't gone through the pages properly and seen the entire project properly. Both the pages have Left Alignment by choice. So not being center aligned isn't a bug.

But I felt that center text was good and never imposed my proposals. I mentioned sir it was opened for improvements. You could have proved it wrong :) sir, I am always pen for suggestions and is the same for each things I create.

> Next time please go through properly every page before commenting and creating issue.

I would however go further in next time ;)

Thanks for your help sir :)
Happy coding ;)
