### ISSUE TITLE
Design messed up for error pages

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#2849]
![screenshot from 2017-01-07 12-39-05](https://cloud.githubusercontent.com/assets/20799954/21740175/18fb07be-d4d7-11e6-9e6e-43f32585132a.png)

- [ ] Lines should not overlap the message

- [ ] Make it responsive

**Comment by arpitn30** [comment]
What do you mean by responsive?

**Comment by arpitn30** [comment]
Can I work on this?

**Comment by Abhi2424shek** [comment]
@arpitn30 responsive design is a design policy which keeps all kinds of screen resolutions in mind there are various approaches to do so just google for it.

**Comment by SaptakS** [comment]
@arpitn30 I think @magdalenesuo is already working on this. It is better that everyone doesn't work on same issue because there are a lot of issues pending anyways.

**Comment by arpitn30** [comment]
Oh Okay, I'll look for a different issue then
