### ISSUE TITLE
Not being redirected to "404 not found" page when an arbitrary URL is entered

### ISSUE THREAD

**Issue by arpitn30** [fossasia/open-event-orga-server#2850]
While any arbitrary url is entered after https://eventyay.com/* or http://open-event-dev.herokuapp.com/*, it just shows a blank page instead of being redirected to the 404 error page.

**Comment by Abhi2424shek** [comment]
Can you add some description including the current results, the expected ones and hints on how to reproduce the issue and relevant screen shots or links pls

**Comment by SaptakS** [comment]
@arpitn30 you can work on this if you want.

**Comment by arpitn30** [comment]
Yeah Okay, I'll work on it.
