### ISSUE TITLE
Only show "Fee" column if there is a fee

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2851]
Currently the fee column in the tickets also shows up, if there is no fee defined. There is also the info "paid" of "free".

Expected:

* [ ] Please only show the fee column if the organizer adds a fee.
* [ ] Take out "paid" or "free" behind the ticket name. This information is redundant.

![screenshot from 2017-01-07 11-39-34](https://cloud.githubusercontent.com/assets/1583873/21741167/4b9eae90-d4ce-11e6-95c7-de6a0f65f940.png)

**Comment by Heredroky** [comment]
@mariobehling I want to work on this

**Comment by Heredroky** [comment]
I want to work on this

**Comment by niranjan94** [comment]
@Heredroky you can proceed

**Comment by Heredroky** [comment]
@niranjan94 @mariobehling When I am creating an event, I can't add tickets, do you know how can I add tickets ?
![screen shot 2017-01-07 at 2 25 51 pm](https://cloud.githubusercontent.com/assets/15079370/21744524/4c59ac92-d4e5-11e6-88a7-01a76110b457.png)

**Comment by mariobehling** [comment]
Switch on the module in the admin section.

**Comment by Heredroky** [comment]
@mariobehling 
![screen shot 2017-01-07 at 3 24 28 pm](https://cloud.githubusercontent.com/assets/15079370/21744905/6cce81f2-d4ed-11e6-89b6-72721a76d471.png)

**Comment by Heredroky** [comment]
@mariobehling How can I access to the admin section?

**Comment by SaptakS** [comment]
@Heredroky setup the environment in your local system. Then you can put in your super admin details and also access the admin section. You can't access admin section in deployed version because you don't have permission.

**Comment by Heredroky** [comment]
@SaptakS @mariobehling How can I add fee to a ticket?

**Comment by hpdang** [comment]
For this issue, please Remove redundant text & column as showed below, @Heredroky if you are not sure what to do, please let other take care of this and you try something else. Thank you. 
![eventyay tickets](https://cloud.githubusercontent.com/assets/1658742/21781136/75a7a96c-d6ae-11e6-8726-007a268600e8.png)

**Comment by Heredroky** [comment]
@hpdang I already did that, but now I want to add fee to the tickets to test the changes I made

**Comment by mariobehling** [comment]
@hpdang Thanks for clarifying.

I think there is another problem here as well. The fee feature "absorb or pass on" is not anymore in the ticketing system. It must have gotten lost at some point.

This is how it looks like at eventbrite:

![screenshot from 2017-01-09 21-11-55](https://cloud.githubusercontent.com/assets/1583873/21781664/c4f1bcf4-d6b0-11e6-903c-bdf9e167bed9.png)

**Comment by Heredroky** [comment]
@mariobehling Hmm, then I am going to make a PR, and you can check my changes 😄 .
But I have a problem with deploying the app to heroku or the other services that are in the docs, and the problem is that I don't have a credit card

**Comment by Heredroky** [comment]
@mariobehling My trial on Bluemix is already finished, and when I try to create a Redis instance, it asks for a CC verification :/
