### ISSUE TITLE
Let users control order of tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2853]
The tickets currently show up in the order entered by the user. The organizer might want another order though.

Please implement a way to change the order of the tickets in the ticket column, e.g. implement up and down arrows.

![screenshot from 2017-01-07 11-54-05](https://cloud.githubusercontent.com/assets/1583873/21741263/2e705876-d4d0-11e6-9096-b08bd70a88a2.png)

**Comment by SaptakS** [comment]
@mariobehling which route should we implement this feature?? I mean while entering ticket details or when tickets shown in event dashboard?

**Comment by mariobehling** [comment]
@SaptakS In the event wizard step 1, please.

**Comment by mariobehling** [comment]
@SaptakS I am getting feedback from different organizers that this has high priority for them. Would be great if this could be tackled soon.

**Comment by SaptakS** [comment]
@mariobehling okay. I will look into this ASAP after completing the other issues in hand.

**Comment by mariobehling** [comment]
Unfortunately the ticket sort order does not work on eventyay on the public page.

**Comment by SaptakS** [comment]
I checked on eventyay. It is working absolutely fine. Here are the screenshots:
![screenshot from 2017-04-27 09-09-23](https://cloud.githubusercontent.com/assets/9530293/25467009/6b4cbc94-2b29-11e7-9779-2495abe25f4b.png)
![screenshot from 2017-04-27 09-09-26](https://cloud.githubusercontent.com/assets/9530293/25467010/6b518918-2b29-11e7-853d-df252a215204.png)

Ticket 3 was at the end. Then it was reordered to take it above Ticket 2. And it works absolutely fine in public page as well. @mariobehling can you please check again?

**Comment by niranjan94** [comment]
Can be fixed in #3548
