### ISSUE TITLE
Hidden Ticket visible in ticket list

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2854]
The hidden ticket option allows organizers to hide tickets on the public form.

Even though activated the a hidden ticket still shows up on the public form currently.

![screenshot from 2017-01-07 11-58-07](https://cloud.githubusercontent.com/assets/1583873/21741276/bb4f8a5a-d4d0-11e6-8b86-8adf498008b3.png)

**Comment by shubham-padia** [comment]
I'd like to work on this.
