### ISSUE TITLE
hide password while setting the smtp settings

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/open-event-orga-server#2862]
![screenshot from 2017-01-07 23-55-02](https://cloud.githubusercontent.com/assets/15216503/21744057/cc17f214-d534-11e6-8b4d-33febba8ed32.png)

hiding the password field would be better at /admin/settings/ ,since many users prefer having the password field hided
we could implement a small (show password) button beside the input field for user convenience.

this feature could be extended to other modules for client secrets too

**Comment by Bhargavasomu** [comment]
I would like to work on this issue. Please assign it to me
