### ISSUE TITLE
Implement "Apply" Promotional Code on event site itself

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2863]
Our promotional code/discount gets applied only after the user advances to the next page.

Expected: 
* [x] There should be an "Apply" button on the right hand side of the promotion field (when it is expanded).
![screenshot from 2017-01-07 19-33-17](https://cloud.githubusercontent.com/assets/1583873/21744213/9ed3ba18-d511-11e6-9eef-06cb652f6cdf.png)

* [ ] After the user hits "Apply":
    * [ ] Display below the ticket type the applied discount, e.g. Discounted 50%
    * [ ] Display the new (discounted) ticket price in the price column and the old ticket price crossed

Compare:

![screenshot from 2017-01-07 19-41-23](https://cloud.githubusercontent.com/assets/1583873/21744210/93941abc-d511-11e6-987c-002254742874.png)

**Comment by shubham-padia** [comment]
I'd like to work on this

**Comment by mariobehling** [comment]
Implementation of this issue is not complete. When the discount code is applied the user should see the ticket cost striked through and the discounted cost. Please compare to screenshot.

![screenshot from 2017-01-07 19-41-23](https://cloud.githubusercontent.com/assets/1583873/21744210/93941abc-d511-11e6-987c-002254742874.png)

**Comment by shubham-padia** [comment]
:+1:

**Comment by hpdang** [comment]
hi guys, can someone take care of this please?

**Comment by shubham-padia** [comment]
@hpdang sorry for the delay, been busy with academics lately, will take it up tonight and fix it.
