### ISSUE TITLE
Implement "Create Access Codes"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2864]
We already have the feature of "hidden tickets", but there is currently no way to share hidden tickets with someone.

Please implement Access Codes in the ticket tab below "Discount Codes". Take inspiration from eventbrite, e.g. here: https://www.youtube.com/watch?v=c2qeZMJBCbg

![screenshot from 2017-01-07 19-52-15](https://cloud.githubusercontent.com/assets/1583873/21744315/20946af6-d513-11e6-8ca0-1c93df9fbc78.png)

**Comment by satwikkansal** [comment]
@mariobehling I'd like to be assigned to this issue.

**Comment by satwikkansal** [comment]
@mariobehling I'm working on it. I had a question though, How is the buyer supposed to discover the ticket? I mean where should he/she enter the Access code to reveal the tickets.

**Comment by mariobehling** [comment]
@satwikkansal The access code should be entered into the same field as the promotional code. After it is applied, additional tickets should show up in this. This only make sense if the organizer makes certain tickets only available through an access code, which he/she should.

![screenshot from 2017-01-09 22-25-07](https://cloud.githubusercontent.com/assets/1583873/21784130/98e0bf52-d6ba-11e6-897e-18c057dc2410.png)

A questions comes up here; What if an organizer defines the same code for a discount and and access code? Well in that case the access should be granted as well as the discount.

**Comment by satwikkansal** [comment]
Okay.. I'm working on it :)

**Comment by magdalenesuo** [comment]
Can I work on this if no is?

**Comment by satwikkansal** [comment]
@magdalenesuo You can, I'm stuck with my exams this week :(

**Comment by mariobehling** [comment]
@satwikkansal The access code feature has been added to the master deployment on eventyay now. Just tested it, but unfortunately an error message comes up. Issue is filed here: https://github.com/fossasia/open-event-orga-server/issues/2972

Could you help, please?
