### ISSUE TITLE
Footer bar not vertically centered in area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2877]
After recent changes the footer bar is not anymore vertically centered. Expected: Imprint and other info is centered in the middle between the two lines above/below.

![screenshot from 2017-01-08 23-09-15](https://cloud.githubusercontent.com/assets/1583873/21753987/cf4e2d7c-d5f7-11e6-955f-cea6fdba7fe5.png)

**Comment by PARAG00991** [comment]
I'd like to work on this issue.

**Comment by niranjan94** [comment]
@PARAG00991 proceed :)

**Comment by PARAG00991** [comment]
@mariobehling @niranjan94  I don't see any of the footer options when I run locally like the ones @mariobehling mentioned above (imprint, T&C and so).
![footer_error](https://cloud.githubusercontent.com/assets/8044561/21758711/4de19f22-d664-11e6-9d84-a347dadc5f6a.png)
Could you tell me how to get them?

**Comment by niranjan94** [comment]
@PARAG00991 you need to goto the admin settings and add the system pages
