### ISSUE TITLE
Show actually paid ticket price in view Attendees section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2879]
The view attendees section of event organizers has a column with the ticket price. Please show the real price paid here (e.g. if people are using discounts) instead of the normal ticket price.

![screenshot from 2017-01-09 00-01-33](https://cloud.githubusercontent.com/assets/1583873/21754389/24d5569c-d5ff-11e6-8ecc-921c2647ab29.png)

**Comment by PARAG00991** [comment]
I'd like to work on this issue.

**Comment by niranjan94** [comment]
@PARAG00991 you can proceed working on this once you're done with #2877

**Comment by magdalenesuo** [comment]
I'm doing 2878 and this is also fixed by a similar change, I'd like to do this aswell and fix this in the same PR...

**Comment by SaptakS** [comment]
@magdalenesuo @niranjan I think there is a ambiguity we should clear first about this 2 issues:
https://github.com/fossasia/open-event-orga-server/issues/2878#issuecomment-271377070

After that @magdalenesuo feel free to work. Since you are working on #2878 the same code should fix both the issues.

**Comment by mariobehling** [comment]
I think the questions have been cleared up. Please proceed. Cheers.
