### ISSUE TITLE
Move license info from sidebar to bottom of content area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2880]
The license information is currently on the sidebar. 
![screenshot from 2017-01-09 09-25-34](https://cloud.githubusercontent.com/assets/1583873/21760635/d7919d9c-d64d-11e6-9f3b-f7a546e40752.png)

Please move it to the bottom of the content area of the event below "Getting Here".

![screenshot from 2017-01-09 09-27-10](https://cloud.githubusercontent.com/assets/1583873/21760648/ed4bb640-d64d-11e6-926f-f8d2ee10583f.png)

**Comment by magdalenesuo** [comment]
I'd like to work on this
