### ISSUE TITLE
Authentication Issues with Signing In

### ISSUE THREAD

**Issue by pipix51** [fossasia/open-event-orga-server#2882]
If I sign in with Google+ or Facebook errors are thrown and I see errors such as invalid_client. I set the webpage up using the one-click Heroku depoly button- could that have contributed to the problem?
![screenshot 47](https://cloud.githubusercontent.com/assets/19341222/21764882/5f82d322-d6a0-11e6-8df0-b3276d48ddb0.png)
![screenshot 48](https://cloud.githubusercontent.com/assets/19341222/21764883/5f8587c0-d6a0-11e6-850b-fd2e62bdeb7e.png)

**Comment by niranjan94** [comment]
@pipix51 that is because you have not correctly configured the keys for facebook, google etc at `/admin/settings`
