### ISSUE TITLE
Ticket page - remove redundant text & column 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-orga-server#2883]
Ticket Page: https://eventyay.com/e/45da88b7

Please remove (attached screenshot) 
- Column Fee
- the word '- paid' after each ticket type. 

![eventyay tickets](https://cloud.githubusercontent.com/assets/1658742/21767010/f102c1ce-d671-11e6-86ae-9895d2b60e42.png)

**Comment by adarsh-ideal** [comment]
I would like to work on this.

**Comment by SaptakS** [comment]
@hpdang I think this is the same issue as this: https://github.com/fossasia/open-event-orga-server/issues/2851

Please check and close. Thanks.

**Comment by hpdang** [comment]
thanks @SaptakS, closing this
