### ISSUE TITLE
Installation guide for macOS

### ISSUE THREAD

**Issue by RajuKoushik** [fossasia/open-event-orga-server#2885]
As many developers use the macOS for development, it would be really great if there is an installation guide for the installation.

**Comment by RajuKoushik** [comment]
Can I work on this issue ?

**Comment by aviaryan** [comment]
👍 That would be a great addition I think. We can include side-by-side mac osx instructions in the [INSTALLATION.md](https://github.com/aviaryan/open-event-orga-server/blob/development/docs/INSTALLATION.md) where applicable. What do you think? @SaptakS @niranjan94

**Comment by niranjan94** [comment]
@RajuKoushik go ahead

**Comment by aviaryan** [comment]
PR #2888
