### ISSUE TITLE
Add absorb or pass on fees to the ticketing system

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2894]
Open Event has a fee system, that can be defined in the admin section. See screenshot:

![screenshot from 2017-01-09 21-17-01](https://cloud.githubusercontent.com/assets/1583873/21781732/167f717e-d6b1-11e6-81cf-f04edaf0fc8b.png)

Please implement "absorb fee" or "pass on fees" in the ticketing system similar to other systems.

![screenshot from 2017-01-09 21-11-55](https://cloud.githubusercontent.com/assets/1583873/21781777/35300ca0-d6b1-11e6-878d-54fe833a317e.png)

If fees are absorbed, do not show them in the ticketing sales as described here: https://github.com/fossasia/open-event-orga-server/issues/2851

**Comment by shubham-padia** [comment]
I'd like to start working on this once other PRs with db model changes open right now are merged.

Also for clarification - 
- `absorb fees` - no fees to be taken
- `pass on fees` -  take fee according to defined fee value.

**Comment by mariobehling** [comment]
"absorb fees" - fees go into the ticket price
*pass on" - fees go on top of the ticket price

The fees are defined in the admin section at "settings" and depend on the country. Also add the actual fee info into the UI. Best is: Just have a look at eventbrite how they do it, please.
