### ISSUE TITLE
Add a registration form for attendees

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2897]
The current registration only covers basic details. Other event ticketing systems have the option to define custom fields. Please take inspiration from the following screenshot and research how others are handling custom forms. Then implement the form and add a link in the event setup checklist on the event dashboard.

This is a parent issue. Please open sub-issues for this feature.

![screenshot from 2017-01-10 05-23-44](https://cloud.githubusercontent.com/assets/1583873/21793875/8911d292-d6f5-11e6-9749-d83550541101.png)

* [ ] Implement a simple form https://github.com/fossasia/open-event-orga-server/issues/3153
* [ ] Add a customized form builder

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling I really want to contribute for this issue . (Little guidance would be appreciated).

**Comment by SaptakS** [comment]
@Himanshi-Khandelwal sure.. Go Ahead... You can check into how custom forms are implemented for sessions and speakers in open-event... The approach will be similar...

@mariobehling do we keep the design also like in custom_forms? That way there will be a consistency in design. Or should we make it like eventnook does?

**Comment by Himanshi-Khandelwal** [comment]
where to create this custom form ? Is it where user creates an account there?

**Comment by SaptakS** [comment]
@Himanshi-Khandelwal the custom form is there while creating an event.

**Comment by Himanshi-Khandelwal** [comment]
@SaptakS while creating the form , (first name , last name and email ) is not there as given in the screenshot . or is it that I have to change the create event page in this way?

**Comment by Himanshi-Khandelwal** [comment]
@SaptakS  @mariobehling  ok I got it how and where  to create these custom forms . how to start doing this . A little guidance needed.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling @SaptakS exactly same form is to be created as given in the screenshot?

**Comment by mariobehling** [comment]
@Himanshi-Khandelwal Yes, but the design according to ours. The functionality is important. You can try out these kind of forms at eventnook and evenbrite to get a better idea.
