### ISSUE TITLE
Cannot save changes in profile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2898]
Trying to save any changes in the profile result in an error page.

![screenshot from 2017-01-10 06-25-43](https://cloud.githubusercontent.com/assets/1583873/21794781/ba2e31ba-d6fd-11e6-866c-38778ff3b878.png)

**Comment by aviaryan** [comment]
I will have a look at it.

**Comment by mariobehling** [comment]
This issue is not entirely solved. The fix still has issues:
When the user uploads a photo and saves it, any text that is in the "description" is deleted. On the other hand if the user goes to another page and returns to the profile and then changes anything in the "description" field the images disappears after the change is "Updated".

Expected: Image and test should be saved.

**Comment by SaptakS** [comment]
@mariobehling checking
