### ISSUE TITLE
Increase width of ticketing form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2902]
The ticket sales form is breaking lines for long ticket names, but there is still some space left in the area.

Please increase the width of the form. Ensure it does not look too squeezed though.

![screenshot from 2017-01-10 11-31-59](https://cloud.githubusercontent.com/assets/1583873/21803068/b8daad2c-d728-11e6-8fbd-20c1f48f93ba.png)

**Comment by mariobehling** [comment]
The whole area should be expanded. After the change the final row is not aligned anymore. Please help to finalize this. Thank you.

![screenshot from 2017-01-11 03-26-02](https://cloud.githubusercontent.com/assets/1583873/21832783/d376f9bc-d7ad-11e6-876e-66716be0eb92.png)

**Comment by Rohanhacker** [comment]
how about this ? is it acceptable ? 
![screenshot from 2017-01-11 08-43-13](https://cloud.githubusercontent.com/assets/9512969/21834289/064d7ea2-d7da-11e6-8739-880c78024c28.png)

**Comment by Rohanhacker** [comment]
is it acceptable ?
![screenshot from 2017-01-11 09-25-04](https://cloud.githubusercontent.com/assets/9512969/21835123/80e23aee-d7e0-11e6-8eee-9d1a65beb27c.png)

**Comment by mariobehling** [comment]
Please keep the last column in one row as before.

![screenshot from 2017-01-11 05-05-35](https://cloud.githubusercontent.com/assets/1583873/21835240/b439e57e-d7bb-11e6-997f-99b7bd4c2518.png)

**Comment by mariobehling** [comment]
"Enter Promotional Code" and "Order Now" are too much moved to the right in comparison to other areas. Please implement similar to original table. The main goal is to make the area wider.

**Comment by RajuKoushik** [comment]
Can i work on this ?

**Comment by niranjan94** [comment]
I think @Rohanhacker is already working on it ... Let's see

**Comment by SaptakS** [comment]
@Rohanhacker are you working on this?? what is the progress??

**Comment by Rohanhacker** [comment]
@SaptakS i am super busy this week. Anyone can feel free to send PRS otherwise I'll continue to work on this after friday.

**Comment by RajuKoushik** [comment]
So should I proceed fixing this issue ?

**Comment by SaptakS** [comment]
@RajuKoushik yeah sure.

**Comment by RajuKoushik** [comment]
@aviaryan  @SaptakS  I am finding it difficult to locate the the directory for buying a ticket after creating an event. Could you please help me figuring it out ?

**Comment by SaptakS** [comment]
@RajuKoushik, you can find the files in `templates/gentellela/public/event/` . In the website you can access it in `/e/<event_identifier>/`

**Comment by SaptakS** [comment]
@RajuKoushik you are working on this, right?

**Comment by RajuKoushik** [comment]
Yes @SaptakS
