### ISSUE TITLE
Inconsistency of Design Layout of Buttons

### ISSUE THREAD

**Issue by RajuKoushik** [fossasia/open-event-orga-server#2907]
Inconsistency of the dimensions of the buttons on the 'register' page.
![screen shot 2017-01-10 at 7 17 54 pm](https://cloud.githubusercontent.com/assets/10185323/21808486/8c9cef54-d769-11e6-8e28-77b6b77fd036.png)

**Comment by RajuKoushik** [comment]
Fixed the issue and sent a PR.

**Comment by magdalenesuo** [comment]
@SaptakS  and @niranjan94 I think this issue has been fixed.
