### ISSUE TITLE
No Flash message showing on clicking save button

### ISSUE THREAD

**Issue by PARAG00991** [fossasia/open-event-orga-server#2908]
When admin clicks on the save button after making changes in admin `modules` and **social links** section in admin `content`, flash message doesn't display showing `Changes Saved Successfully` or something like that.

**Comment by PARAG00991** [comment]
I'd like to work on this.

**Comment by niranjan94** [comment]
@PARAG00991 sure ... Go on

**Comment by RajuKoushik** [comment]
Can I work on this if the work has not been started ?

**Comment by PARAG00991** [comment]
@RajuKoushik I'm working on it.

**Comment by RajuKoushik** [comment]
Sure :)
