### ISSUE TITLE
Admin sales section: Navbar absent on fees, fees status, discount code, create discount code section

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2916]
![selection_063](https://cloud.githubusercontent.com/assets/13910561/21829119/58fd4198-d7ba-11e6-9eed-0f7092fa08a3.png)

**Comment by mariobehling** [comment]
I am unclear about this issue as it seems to cover a lot of different things. Please also consider, it is not always the best choice to give too many options. Keep it simple for now. It also decreases the areas we have to maintain and test continuously.

OK - Sorting by Fees seems like a nice thing to have
X  - Fee status - it means if fees are absorbed or passed on. I think it is not relevant for the sales people. It is only relevant for organizers.
X - Sales By Discount Code. This data is mainly interesting for the specific event organizer, but not for the admin. The organizers do not have access to the admin section at all. Therefore there is no need to have one more section here about this.
X - "Discount Code" - What do you want to show here? A list of discount codes. I do not think this is relevant for sales.

**Comment by shubham-padia** [comment]
I think there is a misunderstanding here. This issue does not cover the things mentioned in the above comment. These sections were already existing before the issue. 

This is a simple issue about the missing tab navbar on the top of these poor existing sections.

Before:
![selection_063](https://cloud.githubusercontent.com/assets/13910561/21829119/58fd4198-d7ba-11e6-9eed-0f7092fa08a3.png)

After:
![selection_064](https://cloud.githubusercontent.com/assets/13910561/21829182/b9cdd6c2-d7ba-11e6-973c-e40f368578ca.png)

**Comment by shubham-padia** [comment]
A sperate issue can be opened about the issues mentioned in the above comment.
