### ISSUE TITLE
Sections required in admin sales tab

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2919]
From @mariobehling 's comment at https://github.com/fossasia/open-event-orga-server/issues/2916#issuecomment-271759687

> I am unclear about this issue as it seems to cover a lot of different things. Please also consider, it is not always the best choice to give too many options. Keep it simple for now. It also decreases the areas we have to maintain and test continuously.

OK - Sorting by Fees seems like a nice thing to have
X - Fee status - it means if fees are absorbed or passed on. I think it is not relevant for the sales people. It is only relevant for organizers.
X - Sales By Discount Code. This data is mainly interesting for the specific event organizer, but not for the admin. The organizers do not have access to the admin section at all. Therefore there is no need to have one more section here about this.
X - "Discount Code" - What do you want to show here? A list of discount codes. I do not think this is relevant for sales.

**Comment by shubham-padia** [comment]
`Fee status` allows the sales admin to look through all the invoices, which seems important to the sales admin, renaming it to something like `All Invoices` would be good.

`Discount Code` section allows the sales admin to create discount codes, but in the current implementation, discount codes are created and maintained by the event organiser, so this seems redundant.

**Comment by mariobehling** [comment]
@shubham-padia Thanks for the clarification. I agree invoices is a good idea. Could you simply call it "invoices", please?

Also agree, that Discount Codes is not needed in this section at the moment. 

Please proceed with "Invoices". Cheers.

**Comment by shubham-padia** [comment]
@niranjan94 @SaptakS Should I comment out the relevant code (in the `views`) for now or should the code be removed. Also IMO the relevant template files should not be deleted for now. Please give you suggestions.

**Comment by niranjan94** [comment]
@shubham-padia comment out for now. Let the code stay. Will review this later.
