### ISSUE TITLE
refactor: remove local prism.js/css dependency

### ISSUE THREAD

**Issue by juslee** [fossasia/open-event-orga-server#292]
remove open_event/static/admin/js/prism.js and static/admin/css/prism.css in favour for bower libs.

used in open_event/templates/admin/permissions/permission.html

**Comment by aditya1702** [comment]
@juslee Didnt exacly understand. Do I have to remove the old files and replace them with the bower generated ones? On running 'bower install' new prism.js and prism.css files are created in the static/admin/lib/prism/ folder. Do u mean to use those?

**Comment by aditya1702** [comment]
@juslee could you tell exactly what is wanted here?

**Comment by juslee** [comment]
Yes. Remove prism.css and .js from the repo. Any reference to prism needs to be updated.
