### ISSUE TITLE
Implement option to get orders information of own events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2933]
In "Settings" please add an option for own events to get email updates. Whenever the user creates a new event implement "get email updates" as a standard.

Implement as follows:
* [ ] Subscribe Order Alert
Subscribe me for an order alert email (receive a notification email when there is an order)

![screenshot from 2017-01-12 20-56-55](https://cloud.githubusercontent.com/assets/1583873/21906197/97e78cfa-d90a-11e6-8ba6-0a8815d5c70e.png)

* [ ] Also ensure co-organizers also get this update when they are added to the event (but not other roles)

**Comment by RajuKoushik** [comment]
@mariobehling  Can I work on this issue ?

**Comment by niranjan94** [comment]
@RajuKoushik sure. Proceed

**Comment by shubham-padia** [comment]
@RajuKoushik Are you currently working on this ? . If not I would like to proceed with the issue.

**Comment by RajuKoushik** [comment]
@shubham-padia You can proceed with it. Due to an unforeseen situation I am occupied with something else.
