### ISSUE TITLE
UI bugs in Attendees Page

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#2934]
These are some of the UI bugs that need to be fixed in Attendees Page `/events/<event-id>/tickets/attendees/`

- [ ] Placed label is shown in red. -> Change it to blue like in orders page.
- [ ] Order by whom is not shown.
- [ ] Order URL is wrong.
- ~~Only Placed and Completed orders shown.~~ Not an UI issue. So will be solved in #2936 
- [ ] The Actions not shown for Completed orders.

@magdalenesuo please fix these issues. Thanks.

**Comment by SaptakS** [comment]
@mariobehling a little digging into this issue led me to find that ticket holders info is saved only if the order is placed or completed. This logic seems to be correct because if one doesn't reach either of the state, then the details of attendees can't be attained. In that case I feel the "pending" and "expired" tabs shouldn't be there in Attendees page. @niranjan94 @magdalenesuo views?

**Comment by mariobehling** [comment]
@SaptakS Yes, this is one way to see it. However, in that case we could also take out "pending" in "Orders".

Actually it is possible to get the attendee information if the user has entered them already or the user was logged in, when he/she started the process. The only difference is: The user has not paid yet.

So, if the user has entered all data, but has not paid, we actually have all the data in pending, but the order is not finished.

-> So, what we should save is all the attendee data. If the user has only started the order, but not added any attendee information we should just keep the link to the order and not show anything in the field or just "None" or similar.

**Comment by SaptakS** [comment]
> it is possible to get the attendee information if the user has entered them already or the user was logged in, when he/she started the process.

We do have the user who started the order but not the details of the all the attendees in that order, i.e. if there are multiple tickets in that order. This already does get save.

> If the user has only started the order, but not added any attendee information we should just keep the link to the order and not show anything in the field or just "None" or similar.

This is a possible way of showing but we can show only the order and order status information. That would be fine?

If the user has entered the attendee data and pressed pay now, but not completed payment procedure or if only partial attendee data was added, then what should be the flow? Should we save the data of attendees when all the attendee data is added and proceeded for payment? I will make a separate issue to handle this implementation.

**Comment by mariobehling** [comment]
> If the user has entered the attendee data and pressed pay now, but not completed payment procedure or if only partial attendee data was added, then what should be the flow? Should we save the data of attendees when all the attendee data is added and proceeded for payment? I will make a separate issue to handle this implementation.

Yes, sounds good to me.

**Comment by SaptakS** [comment]
The above discussion will be resolved in #2936
