### ISSUE TITLE
Add tagline to home page and as option in admin settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2940]
The home page currently shows up on search engine at "eventyay - Home"

Please add a tagline to the home page and ensure the title in the meta information shows up as:
eventyay - Event Management and Ticketing

Please add the option about the tagline in the admin settings below "App Name".

![screenshot from 2017-01-13 14-26-02](https://cloud.githubusercontent.com/assets/1583873/21931534/3f9b8078-d99c-11e6-8ee7-fca88718940f.png)

**Comment by magdalenesuo** [comment]
I'd like to try this, please
