### ISSUE TITLE
Take out Disqus from documentation site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2952]
Disqus was integrated into the documentation site, but actually we do not really need it. Please take it out. No need for comments.

![screenshot from 2017-01-14 18-04-05](https://cloud.githubusercontent.com/assets/1583873/21956539/ea5ae00c-da83-11e6-9c52-878545e61b84.png)

**Comment by aviaryan** [comment]
Working on it now.
