### ISSUE TITLE
Improve structure, add info and enhance layout of documentation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2953]
Ideas for improvements:
* [ ] Move "About" and "Contact" to dev branch docs folder and generate it from there
* [ ] Add Readme.md as start page and ensure the links to the subfolders are working
* [ ] In API.md add a link to the Swagger API docs in the subfolder
* [ ] Define a way to add pages into the documentation structure (a mini how to for the documentation)
* [ ] Propose the implementation of a documentation search
* [ ] Should we have a sidebar or top menu for the main items?

**Comment by Marauderer97** [comment]
@mariobehling I would like to help with this.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling I want to work on this. A little guidance would be appreciated.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling I want to work on this. A little guidance would be appreciated.

**Comment by mariobehling** [comment]
Thanks. @niranjan94 already set up branch for http://dev.eventyay.com. Let's follow up opening specific issues to improve this.

**Comment by mariobehling** [comment]
Ahh sorry, saw that this is implemented, but actually this issue is not finished yet. The documentation is generated by a script. Please check at the dev site and see how you could improve these points mentioned in the issue.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling how can I contribute for this?
