### ISSUE TITLE
How to structure documentation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2957]
We have 3 main projects repository. If we want to keep the documentation in each project repo, how could we give users access to a common developers documentation website?

An idea would be to do the following:
http://dev.eventyay.com - overview of projects
http://dev.eventyay.com/server/ - documentation of server project
http://dev.eventyay.com/droidgen/ - documentation of Android generator
http://dev.eventyay.com/webgen/ - documentation of Web app generator
http://dev.eventyay.com/orgapp/ - organizer app

How can this be implemented using different repositories and GitHub pages?

**Comment by aviaryan** [comment]
One way this seems possible is by using a travis build task that clones each repo, structures the files and then pushes them to the github pages branch. 
We will need to have the script in the master branches of all repos and whenever a doc in any repo is updated, the whole website will be updated. 
We can use the gh-pages of [open-event repo](https://github.com/fossasia/open-event) for hosting generated docs as it is the centre of the open-event project. Or we can create a new repo for eventyay dev docs and use it for hosting generated docs. 

However, this task is complex so if anyone finds an easier solution, we should use that instead. I looked on the Internet but didn't find any solution so I thought of this method. 
@mariobehling views?

**Comment by mariobehling** [comment]
@aviaryan Yes, I also had a similar idea, but was hoping someone comes up with something better here.

**Comment by aviaryan** [comment]
@mariobehling After some discussion at https://github.com/loklak/loklak_server/issues/1003, I think we have a good idea on how to solve these types of problems. 
Therefore should I proceed to work on this issue? 

**One question**: Since the docs are hosted at eventyay domain, should I assume that docs are needed to be built from master and not development?
