### ISSUE TITLE
Miscellaneous bugs in ticketing section

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#2965]
- Payment currency is hard-coded at some places
- Label and ticket holder box overlap
![selection_078](https://cloud.githubusercontent.com/assets/13910561/22032287/d3ccff18-dd09-11e6-8c5e-ce1675564949.png)

**Comment by SaptakS** [comment]
* The label and ticket holder box overlap was done consciously by me. :sweat_smile: @niranjan94 comments.
