### ISSUE TITLE
Feature to make users admin no longer available for superadmins

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2971]
The feature to make users an admin seems to be lost for super admins. Super admins can only add sales and marketers.

**Comment by shubham-padia** [comment]
@mariobehling Currently working for me. Can you recheck, please? Thanks !!
![selection_083](https://cloud.githubusercontent.com/assets/13910561/22084387/f9d2aa22-ddf5-11e6-987a-6fea4bece47e.png)

**Comment by mariobehling** [comment]
Yes, there it is. Thank you!
