### ISSUE TITLE
Access codes not working - giving error "Promotional Code not valid"

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-orga-server#2972]
After the organizer has set up an access code and new attendees make an order with this access code, the error message comes up "The promotional code entered is not valid. No offer has been applied to this order."

Expected: User can make an order of the hidden ticket.

![screenshot from 2017-01-18 22 26 48](https://cloud.githubusercontent.com/assets/1658742/22083694/7dada852-ddcd-11e6-885e-b8fb98c64274.png)

**Comment by mariobehling** [comment]
The logic that needs to be implemented is:
a) If an "Access Code" exists, it should allow the order and display "You access code is applied an your and you can make this order now."
b) If a "Discount Code" exists" the system should act as of now.
c) If an "Access Code" and a "Discount Code" with the same name exists, both Access Code and Discount Code should be applied to tickets and the relevant messages displayed.

**Comment by magdalenesuo** [comment]
@mariobehling @hpdang I'll look into it.

**Comment by SaptakS** [comment]
@magdalenesuo the discount calculation in the pre_payment_page has again been broken. Please fix that also. Thanks.

**Comment by hpdang** [comment]
still have some errors, please check https://github.com/fossasia/open-event-orga-server/issues/2990
