### ISSUE TITLE
Overview of ticket income shows incorrect number

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2978]
Comparing numbers in the ticket sales of organizers and in the admin ticket dashboard shows different numbers. Numbers in the specific event ticket dashboard are correct.

![screenshot from 2017-01-19 13-26-05](https://cloud.githubusercontent.com/assets/1583873/22106840/fd61506c-de4a-11e6-9676-721528644717.png)

**Comment by magdalenesuo** [comment]
I'll do this

**Comment by mariobehling** [comment]
The numbers in the subtab in the admin sales section still do not add up correctly. Please see example below in screenshot.

![screenshot from 2017-01-28 02-33-53](https://cloud.githubusercontent.com/assets/1583873/22393141/51130ae4-e502-11e6-8ec5-6f8f99e9b8a3.png)
