### ISSUE TITLE
Enhance admin sales tab with date and links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2980]
In the tables of the admin sales tab please enhance as follows:
* [ ] add event dates in the second column
* [ ] in first column make event name itself link to the specific event dashboard and add in brackets "(View Live Site)"

![screenshot from 2017-01-19 13-35-22](https://cloud.githubusercontent.com/assets/1583873/22107206/d4e02652-de4c-11e6-9a90-f9b44e9197ee.png)

**Comment by magdalenesuo** [comment]
Can I work on this, please?
