### ISSUE TITLE
Admin Sales Tab: Implement additional filters

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2981]
Please implement additional filters for the sales admin tab. Probably a dropbdown menu with cross boxes is suitable or make another suggestion.

Implement as follows with:
* [ ] Filter to only show Live, Past, or Draft events
* [ ] Filter to only show events with paid tickets

![screenshot from 2017-01-19 13-45-50](https://cloud.githubusercontent.com/assets/1583873/22107410/ed80fc6c-de4d-11e6-8a2f-34001fc59a2c.png)

**Comment by sainiak009** [comment]
@mariobehling I want to work on this. Please assign this task to me.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling  @sainiak009 anyone working on this issue?

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling @niranjan94 are these filters to be shown inside the Showing all records dropdown box?

**Comment by niranjan94** [comment]
Yes. There... Or if you think any other place would be more efficient and practical feel free to suggest it here... :)

**Comment by niranjan94** [comment]
Linked to related API Issue.
`frontend` tag added. Issue will be re-created on frontend repo.
