### ISSUE TITLE
Implement discount/access code link to show hidden tickets and discounts

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2982]
Other ticketing platforms offer to access discount tickets or tickets available with access code through a direct link. Please implement the same here. An example of the event link here:
1. Normal event link: https://eventyay.com/e/45da88b7
2. Event link with access and/or discount code "railsgirls": https://eventyay.com/e/45da88b7?code=railsgirls

Please add the link to copy just above the save button.
* [ ] Implement it on the create discount page
* [ ] Implement it on the create access code page

![screenshot from 2017-01-19 14-30-20](https://cloud.githubusercontent.com/assets/1583873/22108699/ab3a48b6-de54-11e6-87f5-c734a7ab4c6f.png)

**Comment by magdalenesuo** [comment]
I'll do this
