### ISSUE TITLE
Auto delete pending orders after 72 hours

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2985]
Currently pending orders seem to be kept in the system forever. Please delete pending orders and pending attendees automatically after 72 hours.

![screenshot from 2017-01-19 17-08-56](https://cloud.githubusercontent.com/assets/1583873/22114524/19d1df86-de6a-11e6-81a6-8a58e861004b.png)

**Comment by SaptakS** [comment]
Do we change it to "Expired" ? And what about the "Expired"? Should we let them stay?

**Comment by mariobehling** [comment]
> Do we change it to "Expired"

Yes, good idea.

**Comment by shubham-padia** [comment]
@SaptakS Are you currently working on this, if not i'd like to take this up.

**Comment by SaptakS** [comment]
@shubham-padia you can continue on this after completing https://github.com/fossasia/open-event-orga-server/pull/3026 if I don't solve it by then. :smiley:
