### ISSUE TITLE
Implement Cancel and Delete order

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2986]
Currently orders cannot be cancelled or deleted by the organizer. Please implement a cancel and delete action from the ticket dashboard.

* [ ] Cancel means the ticket stays in the dashboard but shows up as canceled and in this case all generated ticket QR codes should become invalid.
* [ ] Delete means all tickets of the order are canceled and the tickets and orders is deleted from the organizer dashboard, but stays in a status "deleted" on the admin dashboard
* [ ] Auto-delete "Deleted Tickets" after 30 days from the admin dashboard.

![screenshot from 2017-01-19 17-14-55](https://cloud.githubusercontent.com/assets/1583873/22114923/5a3a52be-de6b-11e6-9739-293a4332143c.png)

**Comment by shubham-padia** [comment]
I'd like to work on this.

**Comment by mariobehling** [comment]
The goal is to get something like this:

![screenshot from 2017-01-19 23-09-13](https://cloud.githubusercontent.com/assets/1583873/22127534/8b216d46-de9c-11e6-9f38-f9a97a86d0a8.png)

**Comment by shubham-padia** [comment]
Cancel confirmation form and cancel mail should be send only on completed orders, in other cases the form should not appear, am i Interpreting this right?
