### ISSUE TITLE
Cannot edit ticket details

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2994]
The editing of tickets is blocked with the info "Orders have been placed". As a matter of fact orders have not been placed. There are possibly pending orders though. However as filed in an issue elsewhere pending orders do not seem to expire. In any case they should not block the editing of tickets.

Expected:
* [ ] It should be possible to edit and delete tickets, that do not have "completed orders".
* [ ] It should also be possible to edit the ticket name at any time even when tickets were sold already

![screenshot from 2017-01-19 22-32-36](https://cloud.githubusercontent.com/assets/1583873/22126547/660990be-de98-11e6-905e-8e9577c40a2c.png)

**Comment by SaptakS** [comment]
@mariobehling right now the limitation is that there is pending orders. If expired orders, you can edit but for pending orders you can't. You want to allow edit for all case except "completed orders". How about a order is in "pending" state, someone is about to make payment when you make the changes. So he sees $5 ticket thinks cool and buys but you change it to $15 when he actually buys. How do we handle such situations then?

**Comment by mariobehling** [comment]
@SaptakS Firstly pending orders right now, never seem to expire and I see pending orders that are 19 days old in one event.

> How about a order is in "pending" state, someone is about to make payment when you make the changes. So he sees $5 ticket thinks cool and buys but you change it to $15 when he actually buys. 

This could happen, but then how often is this case actually happen? There could just be a quick message "We are sorry, but ticket sale was not successful. The ticket is no longer available. Please check for other options."

Right now we have the issue, that tickets with small errors are piling up in e.g. the FOSSASIA event and we cannot edit, change or delete anything that is wrong even though there are no orders. So, easiest for now: Allow changes, except for the change of the rate.

Do not allow "Deletion" if there are tickets sold (Completed), but still allow changes (except rate).

**Comment by SaptakS** [comment]
Ok. I will look into this. Also I will look into the auto expiring issue for tickets. Solving both together will do the trick I feel.
