### ISSUE TITLE
Implement "User Links" in User Admin dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2995]
In the admin dashboard `/admin/users/` implement a column "User Links" behind the "Event Roles" column with the following links:

* [ ] Link to User's Tickets
* [ ] Link to User's Sessions
* [ ] Link to User's Events
* [ ] Link to User's Settings

**Comment by Princu7** [comment]
@mariobehling I will try to solve this issue.

**Comment by Princu7** [comment]
@SaptakS @niranjan94 @mariobehling I have implemented the mentioned points. The server is live at 
http://ancient-thicket-44821.herokuapp.com
Please check the required routes. If anything is missing or incorrect, please mention it for correction. 
Admin Credentials:
email-id   :   princu7@gmail.com
password :  fossasia

**Comment by niranjan94** [comment]
@Princu7 please open a PR too.

**Comment by Princu7** [comment]
@niranjan94 Done. Please review and suggest improvements. Thanks!!!
