### ISSUE TITLE
Implement form to cancel ticket

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2997]
The ticket dashboard of events should offer a link to cancel tickets as described here https://github.com/fossasia/open-event-orga-server/issues/2996. Please implement a form with this feature similar to the one in the screenshot below.

![screenshot from 2017-01-19 23-09-13](https://cloud.githubusercontent.com/assets/1583873/22127534/8b216d46-de9c-11e6-9f38-f9a97a86d0a8.png)

**Comment by arpitn30** [comment]
This looks like an easy one for a beginner, I'd like to work on this if that's not a problem

**Comment by SaptakS** [comment]
@mariobehling what is the difference between this cancel and the cancellation in #2986 ?

**Comment by mariobehling** [comment]
Yes, this is a duplicate. Thanks.
