### ISSUE TITLE
Implement "Resend Confirmation" form in the ticketing dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2998]
At points users will contact organizers, that they have not received their ticket. Please implement a form to "Resend Confirmation" similar to screenshot below. This action item will be linked from the ticketing dashboard and should be part of that dashboard keeping the menu on the left.

This is a subissue to https://github.com/fossasia/open-event-orga-server/issues/2996

![screenshot from 2017-01-19 23-07-39](https://cloud.githubusercontent.com/assets/1583873/22127614/eb78563c-de9c-11e6-9cf1-b3365594f7b3.png)

**Comment by yasirunilan** [comment]
@mariobehling  can I work on this?

**Comment by mariobehling** [comment]
@yasirunilan sure. Go ahead.  Thanks

**Comment by yasirunilan** [comment]
@mariobehling just to be clear the this should be a seperate page right?
And also do I need to implement the menu as metioned in #2996 to link it to this particular page?

**Comment by mariobehling** [comment]
@yasirunilan Yes, both issues are related.

Yes, this would be a separate page (like in screenshot above), that shows the ticket data just like when the user orders a ticket.
