### ISSUE TITLE
Show "completed orders" and "attendees with completed orders" in ticketing dashboard first

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2999]
The ticketing dashboard currently shows "All" orders and "All" attendees first including the ones with orders pending or expired. Please move the "All" button to the very right of the button row and show "Completed" Orders/Attendees first when the users opens the tab.

![screenshot from 2017-01-19 23-03-50](https://cloud.githubusercontent.com/assets/1583873/22127910/631ae7f8-de9e-11e6-8516-e53f18da9ba9.png)

**Comment by Princu7** [comment]
@mariobehling I would like to try to fix this issue. Thanks!!

**Comment by Princu7** [comment]
Please close this issue.

**Comment by SaptakS** [comment]
#3008 fixes it. Thanks @Princu7

**Comment by mariobehling** [comment]
Unfortunately this issue is not solved entirely yet. Clicking on "orders" and "attendees" shows the tab "completed tickets", but the content below still shows all tickets. Expected: The opening tab should only show the tickets that are actually completed.

![screenshot from 2017-01-25 01-07-48](https://cloud.githubusercontent.com/assets/1583873/22272555/16e0bccc-e29b-11e6-9ed6-6ff38af13893.png)

**Comment by magdalenesuo** [comment]
I'd like to work on this if no one is.

**Comment by Princu7** [comment]
I am sorry I didn't see this through. @magdalenesuo I am currently working on another issue. You can work on it if you like. Thanks!!

**Comment by magdalenesuo** [comment]
@Princu7 okay great :)

**Comment by mariobehling** [comment]
It still does not work entirely. If the user clicks on the left side bar, the first view does not show the tickets sorted.

![screenshot from 2017-02-06 09-22-18](https://cloud.githubusercontent.com/assets/1583873/22639384/1f8436e4-ec4e-11e6-9def-b35b2b20bc64.png)

If the user clicks on "orders" in the bar, the table is empty even though tickets have been sold.

![screenshot from 2017-02-06 09-25-14](https://cloud.githubusercontent.com/assets/1583873/22639411/401b1698-ec4e-11e6-9b55-6d992eebeef5.png)

**Comment by poush** [comment]
I'm working on this.

**Comment by magdalenesuo** [comment]
@poush Hey there. The issue was because of a typo. I've fixed it. Maybe you can help with the other issues/bugs.
