### ISSUE TITLE
Tracks data Displayed in speakers and sessions

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#30]
![image](https://cloud.githubusercontent.com/assets/10570249/7954199/e04ab562-09ea-11e5-86c3-63d6e7e02f21.png)
![image](https://cloud.githubusercontent.com/assets/10570249/7954206/eccbf8a0-09ea-11e5-9640-a105ff830354.png)

**Comment by mariobehling** [comment]
@mananwason How can be displayed as text instead of an image?

**Comment by mananwason** [comment]
Yes @mariobehling I didn't think of that. I'll edit it.

**Comment by rafalkowalski** [comment]
I fixed it
