### ISSUE TITLE
test: add more tests for 'CustomDateSessionValidate'

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#300]
- Add more tests for `CustomDateSessionValidate`. Start and End times for an Event Session should always be inside the Event date range. There could be three cases for validationerror:
  - Session start time outside Event time
  - Session end time outside Event time
  - Both of them outside Event time 
- Remove `test_event_start_time_smaller_than_end_time` test from `test_validations.py`. There are no conditions on start time smaller than end time. No assertions are being made in the test.

**Comment by leto** [comment]
One more validationerror case:

Session start_time == end_time

**Comment by leto** [comment]
And end_time < start_time, too

**Comment by shivamMg** [comment]
@leto Will add a test to check equality :+1: . Test for End time < start time is already included.
