### ISSUE TITLE
Wizard Step 2 Sponsors: Using red delete button deletes last sponsor in list instead of sponsor in row

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3000]
Using red delete button deletes last sponsor in list instead of sponsor in row.

Expected: The sponsor which is next to the delete button should be deleted.
![screenshot from 2017-01-20 04-04-38](https://cloud.githubusercontent.com/assets/1583873/22134224/c0ddca00-dec5-11e6-9172-fb67f8309926.png)

**Comment by anukul** [comment]
Hi, where do I find this button?
I installed Open Event orga server on an AWS EC2 instance using the instructions [here].(https://github.com/fossasia/open-event-orga-server/blob/development/docs/installation/aws.md)
But all I see is:

![image](https://cloud.githubusercontent.com/assets/5358644/22152348/7518c57e-df48-11e6-887e-a0d9538932cc.png)

**Comment by anukul** [comment]
Hi, I think it deletes the sponsor next to which the Remove button is located.
I followed the instructions [here](https://github.com/fossasia/open-event-orga-server/blob/development/docs/installation/aws.md) and set it up.

Here's a gif: https://github.com/anukul/anukul.github.io/blob/master/output.gif

**Comment by niranjan94** [comment]
@mariobehling I have to agree with anukul. This issue seems non-existent. 

Please see the following screencast. 
https://webmshare.com/BOo61

**Comment by mariobehling** [comment]
@niranjan94 Ok, it was probably solved as part of another issue then. Thanks for following up!

**Comment by SaptakS** [comment]
The issue is not resolved.

**Comment by niranjan94** [comment]
@SaptakS on it.

**Comment by mariobehling** [comment]
Thank you!
