### ISSUE TITLE
Discount code logic: fees excluded from discount

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3007]
Currently fees are being excluded from percentage discounts:
e.g even if the discount is 100%, the user still has to pay the fee.
![selection_087](https://cloud.githubusercontent.com/assets/13910561/22168635/f772d802-df93-11e6-9168-fc993bf0d845.png)

**Comment by SaptakS** [comment]
@shubham-padia the logic needs to be corrected in all the pages including event dashboard, pre payment order form, admin/sales tab. Please take care of that as well.
