### ISSUE TITLE
OAuth Authorization error. Please try again later.

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#3023]
I've tried to create an account on eventyay.com but it threw an error 

```OAuth Authorization error. Please try again later.```

**Comment by mariobehling** [comment]
@rafalkowalski Cannot confirm this. I just tried. It all works for me? Or did you use another way through Google/Facebook? How did you get that. Cheers. Closing it. Please re-open, if it does not work for you still.
