### ISSUE TITLE
On specific event dashboard show number of sold and available tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3039]
1. Currently the specific event dashboard only shows a green progress bar of ticket sales, e.g. https://eventyay.com/events/6/. Please implement the following alternative:

* [ ] Show a list of all tickets with bullet points, e.g. Business Ticket, Sponsor Ticket, Community Ticket etc.
* [ ] Show number of sold tickets/number of available tickets, e.g. 18/200
* [ ] Ensure only sold tickets that are "Completed" are shown

![screenshot from 2017-01-27 18-30-16](https://cloud.githubusercontent.com/assets/1583873/22380766/f8ad5e74-e4be-11e6-95bf-d51a72057fa4.png)

2. On the admin event dashboard:

* [ ]  implement the same as above.

**Comment by Princu7** [comment]
@mariobehling Can I try this issue?

**Comment by niranjan94** [comment]
@Princu7 please proceed :)
