### ISSUE TITLE
Enable to use access code and discount code together

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3046]
If the user generates an access code, it is not possible to apply a discount code as well. Please implement as follows:
* [ ] Allow to enter a discount code on a page that has an access code applied
* [ ] Allow the combination of access + discount code links (manually for now) e.g. `/e/47582707/?acode=VIP&dcode=888`

**Comment by Jatinbalodhi96** [comment]
Hi @mariobehling I was looking to contribute to open-event-orga-server, so can i work on this issue if not assigned to anyone?

Thanks
Jatin

**Comment by mariobehling** [comment]
@Jatinbalodhi96 Sure go ahead. Thanks!

**Comment by Jatinbalodhi96** [comment]
I have setup up the whole server on my local machine but I didn't set up "Flask-SocketIO development" and while creating a test event i am getting an notification error : **"An error occurred while saving. Please try again later ...DISMISS
![1](https://cloud.githubusercontent.com/assets/10434201/22404019/574b3566-e64d-11e6-8773-4d8f53d928b8.png) 
"**
so is this error because i didn't setup flask-socket io or something else?
Please help
Thanks

**Comment by Jatinbalodhi96** [comment]
Its working now, but can you tell me why we need to generate an access code or what is its requirement?

Thanks

**Comment by Jatinbalodhi96** [comment]
@mariobehling do we required to add a input box for access_code input like we have for discount_code on the event details page?

**Comment by mariobehling** [comment]
@Jatinbalodhi96 The best would be if we can use the same field. This could work like that: The user clicks a link with an access code and then adds a discount.

If the user only has the code it works like that a) The user types in the access code and gets the tickets with access code and b) the user types in the discount code and also gets the discount on the tickets.

There could be two fields, but we need to ensure we do not clutter the UI too much and the above would work well enough.

**Comment by Jatinbalodhi96** [comment]
Thanks @mariobehling, okay i will look into it.

**Comment by mariobehling** [comment]
> access_code and discount_code included in url

No.

But: access_code and discount_code included in one URL should work.

**Comment by niranjan94** [comment]
@mariobehling is this necessary asap at this point. ? If not, I can keep this only for the new frontend and close it here.

**Comment by SaptakS** [comment]
Closing this here. @niranjan94 please implement this in the new frontend. Thanks.
