### ISSUE TITLE
Only show sessions when schedule has been published

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3054]
There are issues with the public sessions page:
* [ ] Sessions that have not a time show up at the beginning of the program
* [ ] The session page shows up even though the schedule has not been published

![screenshot from 2017-01-28 19-13-05](https://cloud.githubusercontent.com/assets/1583873/22398703/0bc9dd78-e58e-11e6-923f-a84edc55f6f5.png)

**Comment by mariobehling** [comment]
It seems like the change also affected, that the speakers do not show up on the page anymore.

**Comment by SaptakS** [comment]
@mariobehling without the sessions, showing the speakers seemed meaningless. So I asked @magdalenesuo to show only speakers for whose session has been scheduled in her PR. https://github.com/fossasia/open-event-orga-server/pull/3068#pullrequestreview-18998572
