### ISSUE TITLE
Enhance Form for Call of Speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3069]
The form to answer the call for speakers needs to be improved to be fully usable, e.g. if a speaker wants to submit two proposals it is currently not possible. Therefore, please implement the following:

* [ ] When the user clicks "Submit Proposal" on Call for Speakers page open a pop up with the following options a) Register as a Speaker and b) Propose Session
* [ ] Split forms for Speakers and Registration into separate forms
* [ ] If speaker has already filled in a session form offer option: "Add Another Session"

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling is the pop up - a modal form pop up with the options a) Register as a Speaker and b) Propose Session?

**Comment by magdalenesuo** [comment]
@mariobehling Should I go about this way?
![screenshot from 2017-02-13 06-42-37](https://cloud.githubusercontent.com/assets/20799954/22868103/047f7c22-f1b8-11e6-976a-2ab9d080ed76.png)

**Case 1: Only Speaker Form (Register As Speaker)**
![screenshot from 2017-02-13 06-42-47](https://cloud.githubusercontent.com/assets/20799954/22868113/22391db8-f1b8-11e6-9e57-e7c8fc5442c3.png)

**Case 2: Only Session Form (Propose Session)**
![screenshot from 2017-02-13 06-43-34](https://cloud.githubusercontent.com/assets/20799954/22868115/26ab8dea-f1b8-11e6-8c6c-6e8654c6831a.png)

**Case 3: Both Session and Speaker Form (Propose Session and add speaker)**
![screenshot from 2017-02-13 06-44-29](https://cloud.githubusercontent.com/assets/20799954/22868119/2babd4a8-f1b8-11e6-92e4-f9cc2f43c358.png)

**Comment by mariobehling** [comment]
Yes, the first screenshot is going into the right direction. Let' do as follows:
* [ ] Show "Add Speaker Information" (if the speaker information is complete show green tick, if all required fields are filled in show a relevant [orange exclamation mark](https://farm2.staticflickr.com/1149/1070601182_0fe532a667.jpg), if it is empty and missing required fields show a gray incomplete symbol or something similar)
* [ ] below that show 
   * a) Existing Session Proposal
![screenshot from 2017-02-13 08-57-52](https://cloud.githubusercontent.com/assets/1583873/22875378/abb6d914-f1cb-11e6-893b-da3f6c561752.png)
   * and b) "Add Session Proposal"
* [ ] Use the same way as for "Add Speaker Information" (green tick, orange exclamation mark, gray incomplete symbol)

**Comment by mariobehling** [comment]
I think it has not been clear enough. We only need the buttons:
* Register as a Speaker
* Propose Session

The colors and info on existing sessions has not been implemented. So this issue should have not been closed.

**Comment by mariobehling** [comment]
If the speaker's form has not been filled in completely, it should not be possible that the user submits a session. But: The user can save it as a draft. There should be a "draft" button in the sessions form. The "submit" button needs to be grayed out. If the user scrolls over the gray button, show a tool tip "You need to complete the speakers form before you can submit a session."

**Comment by mariobehling** [comment]
The logic for event organizers also allows, that if event organizers add a session the speaker is not obligatory. It means: If the organizer adds a session he/she can still submit the session even if the speaker field is empty.

In that case there will be sessions without any speaker associated with it, that is fine then - if they have been entered by the organizer. 

This case came up for breaks for example, which should not have anyone associated.
