### ISSUE TITLE
Speakers Dashboard: Show 50 speakers as standard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3073]
Currently the speakers dashboard shows 10 speakers in the standard view. Please change the standard view to 50 speakers.

![screenshot from 2017-01-30 09-56-04](https://cloud.githubusercontent.com/assets/1583873/22417059/7f5697f0-e6d2-11e6-8042-1d0a7926b637.png)

**Comment by Princu7** [comment]
I am on it :)
