### ISSUE TITLE
Autofill option for ticket buyer 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-orga-server#3078]
if I want to buy a ticket for myself only, I still have to fill in my name and email twice. Is it possible to implement an autofill mode? 

![autorefill](https://cloud.githubusercontent.com/assets/1658742/22419249/dd24d41e-e6dc-11e6-8a10-4ddfcdc6e851.png)

**Comment by CosmicCoder96** [comment]
@hpdang I would like to work on this.
