### ISSUE TITLE
bug: generate_icalender_track view crashing

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#308]
Also the endpoint is `/api/v1/track/<int:track_id>/export/iCal`
It should be `/api/v1/event/<int:event_id>/tracks/<int:track_id>/export/iCal` as a track is inside event.

**Comment by championswimmer** [comment]
As general convention of rest apis, we should keep ical in all small
instead of camelcase

**Comment by aviaryan** [comment]
> As general convention of rest apis, we should keep ical in all small instead of camelcase

:+1:
