### ISSUE TITLE
Mail reports and mail sent outs not working in a number of cases

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3081]
The mail sent outs are erroneous in a number of cases. Please have a look in the logs and solve mail issues (https://eventyay.com/admin/reports/#!mail-logs).

![screenshot from 2017-01-30 11-31-42](https://cloud.githubusercontent.com/assets/1583873/22419892/d0087a3a-e6df-11e6-87ab-0d0980cd6443.png)

**Comment by shubham-padia** [comment]
Seems working fine, please reopen if the issue still persists along with steps to recreate the issue.
