### ISSUE TITLE
Add speakers fields to API/JSON

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3089]
There have been recent additions to the form in the speakers form. Please check all fields in the create event wizard step 3 and ensure they are covered in the API and JSON.

Implement the missing fields in the API.

![screenshot from 2017-01-30 15-39-15](https://cloud.githubusercontent.com/assets/1583873/22427155/53bc1da6-e702-11e6-9f49-d26e2045a158.png)

**Comment by vaishnavit** [comment]
I want to work on this. Can you please assign this to me?

**Comment by niranjan94** [comment]
@vaishnavit drop in a comment here once you have setup the server locally, then the issue will be assigned to you :smile:

**Comment by vaishnavit** [comment]
@niranjan94 I am running server locally now. Can you please assign.

**Comment by niranjan94** [comment]
@vaishnavit you can proceed.
