### ISSUE TITLE
Event Dashboard: Adjust column width, event info/functions and add event logo

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3091]
The event dashboard is using a very basic style and should be enhanced. The main idea of the event rows is a) to provide a link to the event itself and b) to give an overview.

To make it easier for the user according to these goals, please implement the following:

* [x] Add Event logo in a large rectangle on the left of the event and the event name below
* [x] Adjust the column widths to use the space more efficiently
* [x] Reduce the width of the last column

![screenshot from 2017-01-30 20-16-37](https://cloud.githubusercontent.com/assets/1583873/22437825/d79d181a-e729-11e6-8f57-63fee037121f.png)

**Comment by indranil-tiwary** [comment]
Hey, I'm interested in solving this issue under your guidance. Can you please clarify about the event logo. Is it beside the name column?

**Comment by Himanshi-Khandelwal** [comment]
Solved this and created PR.
![screenshot from 2017-02-10 00 26 31](https://cloud.githubusercontent.com/assets/17119462/22798365/ac6b78ca-ef27-11e6-8325-816ae3e27177.png)

**Comment by Himanshi-Khandelwal** [comment]
I apologize for this and  will take care in future.

**Comment by mariobehling** [comment]
Implementation has issues:
* [ ] Logos scaled wrongly. Ratio is not correct
* [ ] Ticket column is too small now

![screenshot from 2017-02-25 23-21-02](https://cloud.githubusercontent.com/assets/1583873/23332230/33e52e1e-fbb1-11e6-8230-9e8214bb9b4f.png)

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling Is this ok ? 
![screenshot from 2017-02-26 20 00 06](https://cloud.githubusercontent.com/assets/17119462/23340546/41e5bdd2-fc5e-11e6-9299-fcb59aab9576.png)

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling @niranjan94   is it ok ?  ![screenshot from 2017-02-26 20 00 06](https://cloud.githubusercontent.com/assets/17119462/23362973/4217c6ae-fd1e-11e6-9009-8f2ba95a2458.png)

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal the logo still seems to be distorted. Please maintain aspect ratio.

And yes, a new PR will need to be made.

**Comment by mariobehling** [comment]
Any update on this issue? Would be great to see logos in their correct scale.
