### ISSUE TITLE
Event Dashboard: Add security step before deleting event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3092]
The event dashboard offers the functionality to delete an event in the last row of the table. As some events hold a lot of data this step is relatively "dangerous" for the user. Therefore please implement the deletion process as follows.

When the user clicks the delection button please open a box with the following
   * [ ] Add the question: "Are you sure you want to delete this event?"
   * [ ] "Please type the name of the event into the below box" (Offer a text box here)
   * [ ] Show two buttons a) "Cancel" and b) "Delete Event (this cannot be undone)"
   * [ ] Before user has typed in the event name show the deletion button somehow grayed and inactive
   * [ ] After the user has typed in the event name correctly show the deletion button in red and active

This flow is similar to when a user deletes a repository in Github. Please compare the flow there.

**Comment by CosmicCoder96** [comment]
@mariobehling Can I work on this?

**Comment by CosmicCoder96** [comment]
@mariobehling Can I work on this ?
