### ISSUE TITLE
Array of speakers and microlocations in session.json

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#31]
@rafalkowalski For speakers and microlocations in session please remove the names and make it an array of id's only.

**Comment by championswimmer** [comment]
Yes, let's do it this way for everything then. Wherever objects are cross
referenced, lets only use array of id.

**Comment by rafalkowalski** [comment]
ok :+1:

**Comment by mananwason** [comment]
Yup That's the plan @championswimmer .

**Comment by mananwason** [comment]
@rafalkowalski

**Comment by rafalkowalski** [comment]
@mananwason Could you show me where is a problem?

**Comment by mananwason** [comment]
```{
sessions: [
{
abstract: "This is so awesome",
description: "Awesomeness on its peak",
end_time: "2015-06-20T17:00:00",
id: 1,
level: "100",
microlocation: 1,
speakers: [
1,
2
],
start_time: "2015-06-11T16:16:00",
subtitle: "Awesome",
title: "Super Awesome",
track: null,
type: "Awesome Type"
}
]
}```

**Comment by mananwason** [comment]
![image](https://cloud.githubusercontent.com/assets/10570249/7980219/683c259a-0ac3-11e5-950b-79044f51bf71.png)
Here microlocation should be an array

**Comment by rafalkowalski** [comment]
@mananwason @championswimmer i think not, because Session have one microlocation.So you don't need array.

**Comment by mananwason** [comment]
Oh yes @rafalkowalski my mistake, I confused sessions with tracks idealogy. Sorry :smile:
