### ISSUE TITLE
Event Draft state

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#310]
Project Issue: #306 
Intended URL: /admin/events/new/

**Wizard (Step 1) - Default**
Form consists of:
   - Name of event (Title) *
   - e.g. FOSSASIA 2016
   - Description
   - Location -> a map 
   - Start Date/End Date
   - Background image
   - Logo
   - Event URL - automatically generated by event ID and optional editable 
   - e.g. /events/123456

**Wizard Step (2) - Sessions**

- Type of session : Length of session -> Organizer can define type of session of their own.
e.g. Lightning Talks : 5 minutes

**Wizard Step (3) - Tracks**

- Track -> Organizer can define tracks.
e.g. Track 1 : #bbeeff [color picker]

**Wizard Step (4) - Social (Optional)**
Organizer can add social links like YouTube, Github, Twitter, Facebook, Flickr, Google+ to show them later on webapp.
Organizer clicks on button “Done” or “Finished”
The event is saved in draft version.

- [ ] wizard step(1)
- [x] wizard step(2)
- [ ] wizard step(3)
- [ ] wizard step(4)

**Comment by mariobehling** [comment]
Closing this issue as this is already defined in https://github.com/fossasia/open-event-orga-server/issues/324
