### ISSUE TITLE
Public Event Page: Placeholders image for Speakers without Picture not showing up on Firefox

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3101]
On Firefox the placeholder image for speakers without a picture does not show up.

![screenshot from 2017-01-31 18-40-53](https://cloud.githubusercontent.com/assets/1583873/22477115/29672d00-e7e5-11e6-9ba7-08c15eef733d.png)

**Comment by SaptakS** [comment]
![screenshot from 2017-02-02 15-09-13](https://cloud.githubusercontent.com/assets/9530293/22544152/9cfaaa38-e959-11e6-9c5b-5f084346b304.png)


Working fine for me.

**Comment by mariobehling** [comment]
Great!
