### ISSUE TITLE
Enhance orders and attendees tab with search and filter

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3106]
Currently the orders and attendee in the ticket dashboard does not offer a search and filter function. Please implement the following on these two pages:

* [ ] Add search field on the very right behind the dropdown for the number of displayed entries
* [ ] Add a filter for date search
* [ ] Add a filter to show specific tickets
![screenshot from 2017-01-31 21-53-54](https://cloud.githubusercontent.com/assets/1583873/22484149/64285804-e800-11e6-9a3c-c4d1dbdeb55c.png)

![screenshot from 2017-01-31 21-58-07](https://cloud.githubusercontent.com/assets/1583873/22484175/7eadf530-e800-11e6-9284-90a8490d241d.png)

**Comment by Princu7** [comment]
I would like to add this feature. Thanks

**Comment by Princu7** [comment]
This issue has been solved. Please close it. Thanks!!

**Comment by niranjan94** [comment]
@Princu7 

Make sure your PR's description contains GitHub's special keyword references that automatically close the related issue when the PR is merged. (More info at https://github.com/blog/1506-closing-issues-via-pull-requests )

**Comment by mariobehling** [comment]
Ok, so the filters are there now. Thanks! But, applying the filters does not work yet. It does not show the results. Re-opening the ticket therefore.

**Comment by Princu7** [comment]
@mariobehling It seemed to work before when I made the PR. No problem. I will again have a look at it. Thanks. :)

**Comment by mariobehling** [comment]
Thank you. @hpdang Just tested it as well. Not working for her neither.
