### ISSUE TITLE
Avoid double spaces and lines for ticket info in organizer and admin dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3107]
The list of tickets uses a lot of space, because of double line spaces. 

* [ ] Please avoid double spaces and 
* [ ] implement list without bullet points on personal event dashboard `/events/` and admin dashboard `/admin/event`

![screenshot from 2017-02-01 08-37-07](https://cloud.githubusercontent.com/assets/1583873/22498727/6624ec9e-e85a-11e6-9cdd-49d371510e96.png)

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this.

**Comment by niranjan94** [comment]
@CosmicCoder96 please proceed

**Comment by mariobehling** [comment]
Not sure why, but double lines are back.

![screenshot from 2017-02-11 22-43-12](https://cloud.githubusercontent.com/assets/1583873/22857761/a251c332-f0ab-11e6-92f6-5f9c80de4eaa.png)

**Comment by CosmicCoder96** [comment]
@mariobehling
I believe the problem with the double line was when bullet points were there, there used to be a double line in the same ticket's name.
For instance if the ticket name is really long, it will break into multiple lines all with multiple spacings.

This blank line was left intentionally for better readability on smaller screens or when the window is minimized. Like in this case, having no line spaces at all, led to a congested view.

![image](https://cloud.githubusercontent.com/assets/17252805/22857826/3ab35e20-f0d3-11e6-9e4c-a4388126e9b4.png)

**Comment by mariobehling** [comment]
Thanks.

It is ok to have everything closer together here. Please do not add a space in between. This was one point in the issue. If an organizer has 15 ticket types (which is a usual case, including speaker and exhibitor passes for example), then the line gets too long otherwise. In a table we want to have things in one view. Please implement it without spaces. Thanks

**Comment by CosmicCoder96** [comment]
@mariobehling Just a suggestion. Does the idea of using ellipses for multi-line ticket names sounds good? and the full name can be displayed in a tool-tip.

**Comment by CosmicCoder96** [comment]
@mariobehling 
Thanks.  I have made a PR for the same.
