### ISSUE TITLE
Public Event Page: Add icon for website below speaker image

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3108]
Currently there are links to social networks below the speaker image. Please also add an icon for the website and add the icon, if the speaker has specified a website, e.g. compare: https://eventyay.com/e/45da88b7/

![screenshot from 2017-02-01 09-57-02](https://cloud.githubusercontent.com/assets/1583873/22500513/0799ccca-e865-11e6-8d62-1b145cbbe7dd.png)

**Comment by Himanshi-Khandelwal** [comment]
I m on it :)
