### ISSUE TITLE
Admin Panel: Show detailed user numbers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3110]
In the admin panel there is a widget with a table "System Roles". Please improve as follows:

* [ ] Add Row "Unverified User"
* [ ] On the last row show "Total No. of Users"

![screenshot from 2017-02-01 11-25-18](https://cloud.githubusercontent.com/assets/1583873/22503343/99f8450e-e871-11e6-8f22-59ba0537ea2c.png)

**Comment by Himanshi-Khandelwal** [comment]
I am on it :)

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling  @SaptakS  @niranjan94 who can be called as an unverified user? 
(out of number_live_events , number_draft_events , number_past_events , organizers ,  co_organizers ,  track_organizers ,   attendees , accepted_sessions ,  rejected_sessions.)

or some other field is to be created?

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling  @SaptakS  @niranjan94  difficulty in finding  unverified user count .Please help

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling @niranjan94 @SaptakS  issue solved !! 
![screenshot from 2017-02-03 12 24 25](https://cloud.githubusercontent.com/assets/17119462/22582289/f410c958-ea0b-11e6-9a4b-9cc51965a874.png)

**Comment by Abhi2424shek** [comment]
@Himanshi-Khandelwal PR? #?

**Comment by Himanshi-Khandelwal** [comment]
this issue is solved !! and the PR is merged ..
