### ISSUE TITLE
Specify from "Name" for emails in admin dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3113]
The system emails that are sent out from eventyay currently show "info" as the name. Please implement a field in the email settings to specify a "Name" so when people get an email from the system this name shows up in their inbox.

![screenshot from 2017-02-01 12-49-24](https://cloud.githubusercontent.com/assets/1583873/22505728/4c3c80ee-e87d-11e6-922f-c470e4c1a6e6.png)

**Comment by CosmicCoder96** [comment]
I am working on this.
