### ISSUE TITLE
Speakers image rendered quality not sufficient

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3115]
Many speakers images are not rendered in a sufficient quality. The challenge is: Some speaker upload very high quality images while others upload smaller images. What is the best setting?

![screenshot from 2017-02-01 15-00-16](https://cloud.githubusercontent.com/assets/1583873/22509670/5a344684-e88f-11e6-9b3a-50552ba8bd2d.png)

**Comment by niranjan94** [comment]
@mariobehling ... actually all speakers who upload pics before https://github.com/fossasia/open-event-orga-server/pull/3100 are shown in a bad quality

**Comment by niranjan94** [comment]
I'll see if I can regenerate the correct images in backend

**Comment by niranjan94** [comment]
@mariobehling the images have been re-generated. Now everything is proper.
