### ISSUE TITLE
Clarify "Deleted Tickets" - where do they come from

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3116]
The dashboard of our event shows a high number of "Deleted Tickets". 

Where do they come from?

Why should they be in the organizers dashboard?

I think we might need a section for these tickets in the admin dashboard, not the organizer dashboard.

![screenshot from 2017-02-01 15-09-29](https://cloud.githubusercontent.com/assets/1583873/22510299/b9f0997c-e891-11e6-9830-6715195ece32.png)

**Comment by shubham-padia** [comment]
> Where do they come from?

These come from the automatically deleted pending/expired orders

> Why should they be in the organizers dashboard?

They cannot be accessed from the organizer dashboard. Only the count is shown currently for the user, The count can be removed if it does not help from the organiser's point of view.

> I think we might need a section for these tickets in the admin dashboard

Yes, this should be definitely implemented.

**Comment by mariobehling** [comment]
Ok, I am trying to understand what is useful for the organizer.

I think we should not move expired orders to deleted. This is not logic, cause nobody deleted the orders.

**Comment by shubham-padia** [comment]
This was done as discussed in #2985 and #3035 .
`Expired orders` are the orders in which the 10 minute limit for transaction is exceeded.

**Comment by mariobehling** [comment]
I think old pending orders should become "expired", but the "expired" ones should not prevent the editing of tickets in the wizard.

I am also still not clear about "deleted orders". Maybe we should not event allow deleted orders, but only allow canceling of orders. In this case canceled orders should neither prevent the editing of tickets (if there are no active tickets).

**Comment by shubham-padia** [comment]
> but the "expired" ones should not prevent the editing of tickets in the wizard.
 canceled orders should neither prevent the editing of tickets

Ahh.. got it. We can disable editing of tickets only if completed orders have been placed for the ticket

> Maybe we should not event allow deleted orders, but only allow cancelling of orders. 

Yes, that can be done, but we have to then decide which category of orders should be permanently deleted after a certain time frame. Currently, only the orders moved to `deleted orders` get deleted after 30 days. If none of the orders are permanently deleted, a huge number of unnnecessary orders will pile up over time

**Comment by mariobehling** [comment]
> Ahh.. got it. We can disable editing of tickets only if completed orders have been placed for the ticket
:+1: 

> Maybe we should not event allow deleted orders, but only allow cancelling of orders.

>> Yes, that can be done, but we have to then decide which category of orders should be permanently deleted after a certain time frame. 

I think no problem if they pile up or is it? As long as they do not show up right away in the UI and would block the editing of tickets, they can stay in the system.

**Comment by shubham-padia** [comment]
> I think no problem if they pile up or is it? As long as they do not show up right away in the UI and would block the editing of tickets, they can stay in the system.

Okay, let's not delete records permanently for now, if more data piles up in future and affects query time, we can delete the data at that time.

**Comment by Abhi2424shek** [comment]
@mariobehling fixed by @shubham-padia
