### ISSUE TITLE
Call for Speakers not open even though time to open is specified

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3117]
The call for papers does not open according to the time specified. Possibly it uses the server timezone instead of the event timezone.

![screenshot from 2017-02-01 15-45-26](https://cloud.githubusercontent.com/assets/1583873/22511329/9f26fd4e-e895-11e6-90a5-6c2ecbbb045e.png)

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this.

**Comment by niranjan94** [comment]
Please proceed
