### ISSUE TITLE
Do not show "Absorb Fees" in Free Tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3118]
Free Tickets do not have a cost in the system. Therefore do not show the option "Absorb Fees" in free tickets.

![screenshot from 2017-02-01 15-53-33](https://cloud.githubusercontent.com/assets/1583873/22511672/ae3d2ad2-e896-11e6-9d34-4867382cd83d.png)

**Comment by yasirunilan** [comment]
Can I work on this?

**Comment by niranjan94** [comment]
Sure @yasirunilan ... you can work on this once you're done with #3123

**Comment by yasirunilan** [comment]
@niranjan94  can I work on this first and move to #3123 ?

**Comment by niranjan94** [comment]
Sure ...
