### ISSUE TITLE
Add widget "tickets" to event dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3123]
Show a widget with basic ticketing info in the dashboard of event at `/events/event-id` including:
* List of tickets with available and sold tickets
* Number of overall sold tickets
* Number of orders
* Sales

**Comment by yasirunilan** [comment]
@mariobehling You mean to add the widget to the Overview tab under /events/event-id  which have the general info?

**Comment by mariobehling** [comment]
> add the widget to the Overview tab under /events/event-id which have the general info

@yasirunilan Yes, correct.

**Comment by yasirunilan** [comment]
Thanks @mariobehling  I will start working on this

**Comment by yasirunilan** [comment]
I created the UI prototype first, is the requirement is like this?
[
![screenshot from 2017-02-04 01 59 53](https://cloud.githubusercontent.com/assets/9814784/22617597/eec2f06c-ea7d-11e6-9662-e5886536ad7a.png)
](url)

**Comment by yasirunilan** [comment]
I created a UI prototype, is this the requirement ?
![screenshot from 2017-02-04 01 59 53](https://cloud.githubusercontent.com/assets/9814784/22617603/1d0c1084-ea7e-11e6-8af4-eac8c374fec7.png)

**Comment by yasirunilan** [comment]
any feedback for this one?

**Comment by niranjan94** [comment]
-Align the columns.
-Add the total sold to the first table as a footer below the sold column. 
-Add a total.l Available to the same footer. 
- and sales should be a amount. Show the amount in a formatted way(comma separated digit groupinh)  with the proper currency symbol.

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 I would like to work on this and complete it. are these changes made by @yasirunilan in the development branch ?

**Comment by yasirunilan** [comment]
I'm still working on this @Himanshi-Khandelwal

**Comment by Himanshi-Khandelwal** [comment]
:+1:

**Comment by LuD1161** [comment]
@niranjan94 @mariobehling 
Does it suffice ? 
Or something else should also be added to the info .

![ticket](https://cloud.githubusercontent.com/assets/17861054/26248625/b8f13b02-3cc0-11e7-9383-003d4a39c32a.png)
