### ISSUE TITLE
Allow editing of tickets if no completed/placed order has been placed for it

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3126]
Currently editing of preexisting tickets is not allowed even if there is a single pending/expired order for it. Allow editing if no completed/placed orders have been placed for the said ticket

**Comment by SaptakS** [comment]
This issue was already fixed in https://github.com/fossasia/open-event-orga-server/pull/3014

**Comment by SaptakS** [comment]
@shubham-padia I am not getting this issue. I created a new event that has a pending order. And the tickets are editable. http://open-event-dev.herokuapp.com/events/338/ Check.

**Comment by shubham-padia** [comment]
@SaptakS Thanks. Noticed it now.
