### ISSUE TITLE
Session submission and last changed date shows event date instead of submission/last changed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3137]
In the speakers info tab the dates shown for session submission and last changed date show the event date instead of the actual submission time/date.

![screenshot from 2017-02-02 22-25-45](https://cloud.githubusercontent.com/assets/1583873/22569157/b7549e10-e996-11e6-9c09-cd8a6bd36090.png)

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this.

**Comment by niranjan94** [comment]
@CosmicCoder96 you can work on this once you're done with #3107
