### ISSUE TITLE
Tables with scroll bars in small resolutions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3138]
We are using some tables in a number of pages, e.g. `/events/`. In smaller resolutions these tables result in scrollbars within pages.

Please implement a solution without -internal- scroll bars.

This issue is also related to: https://github.com/fossasia/open-event-orga-server/issues/3059

![screenshot from 2017-02-02 22-45-04](https://cloud.githubusercontent.com/assets/1583873/22569896/97d2a840-e999-11e6-98f5-2be64018e07a.png)

**Comment by SaptakS** [comment]
@mariobehling this was the solution we unanimously decided for tables in smaller resolution. Moreover I don't think this is a bug. This is a well discussed and decided plan that we implemented. There is no other way to make tables responsive. We discussed things like showing accordion and stuff but they all create lots of problem with dependencies. So I feel scroll in smaller resolution is the best solution as of now. @niranjan94 your views?

**Comment by SaptakS** [comment]
@niranjan94 @magdalenesuo check the comment [here](https://github.com/fossasia/open-event-orga-server/issues/3059#issuecomment-277097355) and tell your views... Do you think we should move to accordion for smaller screens?? Because I don't see any way of showing an entire table without scroll in smaller screens??? @mariobehling any suggestions???

**Comment by mariobehling** [comment]
@SaptakS To go for tables allowed us to get started and focus on the features itself. Genetella is an admin theme originally. So, it is not always the best solution. However, in this issue it would out of scope to decide on the next steps in the design evolution, but I hope we can get a more evolutionarr solution here for the moment. 

1. It would be good to go through the tables and improve the distribution of columns. This would already help to avoid internal scroll bars.

2. Rather than having scroll bars within the page, the scroll bars should appear for the whole page. Right now one issue is, as a user the last columns suddenly disappear and I do not event see that there is a scroll bar on the lower end of the page. So, please implement this not as a table with a scroll bar inside the page, but rather as a page that gets a scroll bar if the resolution is too small.

Does this make sense?

**Comment by SaptakS** [comment]
> page that gets a scroll bar if the resolution is too small.

The problem with this is the top navbars looks weird then since the entire page will have a horizontal scroll but the width of the top navbar and other parts will remain same. So it might look weird. We need to find out something so that it doesn't break other designs as well.

**Comment by mariobehling** [comment]
> We need to find out something so that it doesn't break other designs as well.

Sure. Maybe there is no perfect solution for the moment, but as long as there are no internal scroll bars, it would be a step in a good direction.

**Comment by poush** [comment]
I would like to give it a shot. I think I can provide a simple solution with internal scroll bar

**Comment by poush** [comment]
<img width="902" alt="screen shot 2017-02-10 at 10 42 21 pm" src="https://cloud.githubusercontent.com/assets/1812082/22836398/3b3353d8-efe2-11e6-9f86-e10b4c5aa48d.png">

A scroll bar at this place can be placed easily on overflow.

**Comment by mariobehling** [comment]
@poush Thank you, but the goal is to have no internal scroll bars. Cheers.

**Comment by mariobehling** [comment]
> we can provide a breakpoint where one column can be removed

Very nice idea. This could work out, as we still have the filters. Excellent!

**Comment by mariobehling** [comment]
Actually, in fact we could get rid of the column "Order Status" completely and integrate it in the "Order Column" that you show.

**Comment by poush** [comment]
Alright then, I will make a PR for this.

**Comment by SaptakS** [comment]
The PR fixes this problem for only orders table... But I believe this problem is there in all tables..

**Comment by poush** [comment]
I will make these changes on all other table too.

**Comment by mariobehling** [comment]
Please reduce the width of "#" and "Qty" in all ticket order/attendee tables as well. Thank you.

**Comment by poush** [comment]
Attendee and Orders page have been fixed.

@mariobehling  @SaptakS @niranjan94 Can you suggest something for My Events page? Can we hide one or two column on reducing screen size?

First look tells me that width can be reduced through "Public Url" column.

**Comment by mariobehling** [comment]
Last column can probably also be reduced.

**Comment by niranjan94** [comment]
To be handled in `frontend`. Issue will be re-created on the frontend repo. No progress here anyway.
