### ISSUE TITLE
Unable to approve a session with email notification to speaker 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-orga-server#3144]
When speaker submits his/her talks, it will go to Pending. Admin can review and 1) Approve without email or 2) Approve with email. 

Function **Approve with Email** doesn't work for me. Whenever I clicked, the screen froze (see attachment), the speaker also didn't receive any email. 

![emailconfirmation](https://cloud.githubusercontent.com/assets/1658742/22617552/6e735faa-eac8-11e6-88d7-bb0b479dd3b1.png)

**Comment by SaptakS** [comment]
@hpdang I agree with @magdalenesuo in #3171 . I do get a modal but it leads to an error. Are you still getting this error??
