### ISSUE TITLE
Simplify "Add Microlocations" in Scheduler

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3161]
There are a number of fields in the "Add Microlocations.
![screenshot from 2017-02-07 10-53-00](https://cloud.githubusercontent.com/assets/1583873/22689324/b161e808-ed30-11e6-96b5-56e5b8350859.png)

Please simplify this as follows:

* [ ] Change "Name" to "Room Name"
* [ ] Move "Floor" to second position and make it optional
* [ ] Make Longitude/Latitude optional
* [ ] The bottom option for "Room" does not appear anywhere and therefore can be taken out apparently

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this.

**Comment by niranjan94** [comment]
You can work on this once you're done with #3117
