### ISSUE TITLE
'Approve/Reject session with email' does not work.  

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#3171]
In reference to #3144 
'Approve session with email' leads to an error page after clicking send mail button on the email message popup:
![screenshot from 2017-02-09 22-03-23](https://cloud.githubusercontent.com/assets/20799954/22793297/78cdf89c-ef15-11e6-9be8-cda497cfc44c.png)
![screenshot from 2017-02-09 22-03-34](https://cloud.githubusercontent.com/assets/20799954/22793337/93a0c316-ef15-11e6-9404-54b5ec35362c.png)

'Reject session with email' button does not work

**Comment by mariobehling** [comment]
This feature was not working for me since then. Currently accepting speakers with email just shows a layover lightbox without email options.
