### ISSUE TITLE
Deleting ticket not executed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3188]
After the user deletes a ticket, it is not shown anymore and when the user continues and saves it it shows as successfully done. However going back to the editing of the event shows: the ticket is still there. It also shows up on "Access Code" creation if it is a hidden ticket.

Expected: If no purchase has been made, tickets it should be possible to delete a ticket successfully.

![screenshot from 2017-02-11 23-23-33](https://cloud.githubusercontent.com/assets/1583873/22857984/7171ec00-f0b1-11e6-8723-7147c6d61ca5.png)

**Comment by poush** [comment]
I'm on this.
