### ISSUE TITLE
Scheduler showing undefined available time in rooms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3192]
The publisher currently shows available times from 9AM to 5PM on the test event. These times are no-where defined though. There can be a feature request, where we define these times, but currently it is unclear where the time range is defined. On the first day of activities it could be that the user defines 9AM as the event start time, but if it takes place over three days, it is not defined what time it starts and ends on the second day.

What is the best approach here? Until the start and end times for each day are not defined should we just show 24 hours per day except for the start day and end day, when the time is defined in the event wizard step 1?

**Comment by niranjan94** [comment]
`frontend` tag added.
Issue will be re-created on the frontend repo. Discussion can continue there.
