### ISSUE TITLE
Add Login/SignUp for speakers if not logged in

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#3193]
If the user is not logged in and clicks on "Submit Proposal" below call for speakers, show a message "Please login to submit your proposal and show a screen option "Login or Signup".

**Comment by mariobehling** [comment]
The login option should appear here when clicking on the button here:

![screenshot from 2017-02-12 21-28-41](https://cloud.githubusercontent.com/assets/1583873/22865725/4d791c88-f16a-11e6-8391-64f5bd0631be.png)
