### ISSUE TITLE
Co-organizer cannot change/save event data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3195]
At the OSCAL event the co-organizer wants to add (save) items, e.g. track in wizard step 3 - receives "error cannot save", but also other items cannot be saved.

Please give event editing rights to co-organizers.

**Comment by mariobehling** [comment]
Tried editing the eventroles in Admin, but "Save" button does not work.

![screenshot from 2017-02-13 12-17-48](https://cloud.githubusercontent.com/assets/1583873/22881389/80b01472-f1e6-11e6-8059-aec18bfa8e7c.png)

**Comment by LuD1161** [comment]
@mariobehling 
Shouldn't we first give permission to Co-organizer 
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/17861054/23987257/b2ffbbf0-0a4e-11e7-9a35-39bced5af7be.gif)

**The save button is working in my case, suggest ways to recreate the issue , maybe I'm doing it wrong**

**Comment by shubham-padia** [comment]
Working as of now, please reopen the issue along with steps to recreate it .
