### ISSUE TITLE
Scheduler: Show Unscheduled Sessions in assigned track colors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3198]
Currently the track colors of sessions only appear once they are added into the schedule. Please show colors of sessions also when they are unscheduled on the left hand-side.

![screenshot from 2017-02-13 16-18-11](https://cloud.githubusercontent.com/assets/1583873/22889082/3a8bc582-f208-11e6-8a5b-d7f276e83f4b.png)

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this.

**Comment by mariobehling** [comment]
![screenshot from 2017-02-18 18-31-31](https://cloud.githubusercontent.com/assets/1583873/23092548/1d2b1938-f600-11e6-967b-e7e6b07498f3.png)

This is not working for existing sessions. After upgrade on Master colors are still not showing.

**Comment by niranjan94** [comment]
![screenshot from 2017-02-18 19 50 35](https://cloud.githubusercontent.com/assets/2404372/23093841/8bd35b26-f613-11e6-8f19-bacb38d8d3da.png)

@mariobehling it works for me. Try clearing browser cache.

**Comment by mariobehling** [comment]
Thanks, yes it is working now. I wonder if Google Cloud sometimes has some server caching mechanism, cause I used forced refresh which usually overrides local caches.

**Comment by niranjan94** [comment]
@mariobehling we'll have to implement an asset pipeline for this project with static assets minifications and cache busting ... I think that could be a mini task for gsoc 17

**Comment by mariobehling** [comment]
@niranjan94 Ok. Please open an issue here. If someone is interested this can be defined as a parent issue. Cheers.

**Comment by niranjan94** [comment]
@mariobehling I'll open up a detailed issue.
