### ISSUE TITLE
Return 404 status code in API when event doesn't exist

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#320]
When an event doesn't exist, all the api requests for it should have 404 as status code. Currently it returns 200.

```
http http://localhost:5000/api/v1/event/79329/sessions
HTTP/1.0 200 OK
Content-Length: 20
Content-Type: application/json
Date: Mon, 16 May 2016 06:37:28 GMT
Server: Werkzeug/0.11.7 Python/2.7.10

{
    "sessions": []
}
```

**Comment by shivamMg** [comment]
@aviaryan I think it's better to return an empty array like it does right now. And return 404 when accessing a non-existing session. Although, this has not been implemented yet, meaning you cannot retrieve a particular session. I've discussed this in an [issue](https://github.com/fossasia/open-event-orga-server/issues/336). Feedback is appreciated :smile:

**Comment by aviaryan** [comment]
> I think it's better to return an empty array like it does right now. And return 404 when accessing a non-existing session.

I agree.

> Although, this has not been implemented yet, meaning you cannot retrieve a particular session.

There is an endpoint for something like that. `@app.route('/api/v1/event/sessions/<int:session_id>', methods=['GET'])`

**Comment by aviaryan** [comment]
Opened PR #322

**Comment by shivamMg** [comment]
> There is an endpoint for something like that. 
> `@app.route('/api/v1/event/sessions/<int:session_id>', methods=['GET'])`

Mmm.. I completely missed that. I was searching for something like `/event/:event_id/sessions/:session_id`.

**Comment by championswimmer** [comment]
Return error 5xx with message "Event id invalid" maybe?

**Comment by shivamMg** [comment]
@championswimmer Simply saying that the event does not exist and returning a 404 would be better. See the get method for TodoDAO in the flask-restplus [example](http://flask-restplus.readthedocs.io/en/stable/example.html).

**Comment by aviaryan** [comment]
I agree with @shivamMg . That would be the best. StackExchange top rated answers too point the same. 
http://programmers.stackexchange.com/questions/203492/when-to-use-http-status-code-404-in-an-api
http://stackoverflow.com/questions/9930695/rest-api-404-bad-uri-or-missing-resource

**Comment by leto** [comment]
I agree that if you are asking for a list of "sessions" (or something else) and none exist, return a 200 with an empty array. The query succeeded and the answer is nothing.

If the API call is looking for a specific entity and it doesn't exist, a 404 is more appropriate. 5xx status codes are only for server-side errors and not finding something isn't quite a server-side error.

**Comment by aviaryan** [comment]
> If the API call is looking for a specific entity and it doesn't exist, a 404 is more appropriate.

In this case, what should be the data returned - 
The string "X doesn't exist"
or
empty dict "{}" or empty list "[]" 

@leto @shivamMg . I will update PR #322 according to that. Currently it returns empty dict or list.

**Comment by shivamMg** [comment]
@aviaryan You can return a 404 with a message like:

```
{
    "error": "X does not exist"
}
```

That's how [restplus](http://flask-restplus.readthedocs.io/en/stable/errors.html) does it.
