### ISSUE TITLE
User who accepts invitation as co-organizer from the notifications panel receives 404 page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3200]
![screenshot from 2017-02-13 23-20-20](https://cloud.githubusercontent.com/assets/1583873/22906050/14d6b226-f243-11e6-85bc-381b2fee92b3.png)

Clicking "Accept" on the notifications page after an invitation to an event as a co-organizer leads to a 404 page.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling I tried this , but there was no 404 error. It easily redirected me to the next page.
![screenshot from 2017-02-15 11 35 23](https://cloud.githubusercontent.com/assets/17119462/22962485/088a12ca-f373-11e6-9e5f-36ea76033200.png)
![screenshot from 2017-02-15 11 35 59](https://cloud.githubusercontent.com/assets/17119462/22962487/0f2f32d6-f373-11e6-9d1b-4c48579904f4.png)

**Comment by poush** [comment]
@mariobehling There is no such issue here too. There is only one possible case to 404 and that is when you re-accept the already accepted invitation.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling instead of 404 error there should be a modal appearing that "You have already accepted the invite".

**Comment by shubham-padia** [comment]
Seems working fine, please reopen if the issue still persists along with steps to recreate the issue.
