### ISSUE TITLE
We seem to be having some issues on our side. Inconvenience is regretted. We'll fix this as soon as possible.

### ISSUE THREAD

**Issue by akashtalole** [fossasia/open-event-orga-server#3203]
I installed on Ubuntu 15.10. When open page 127.0.0.1:5000 it gives error. AttributeError: 'Response' object has no attribute 'set_data'

**Comment by niranjan94** [comment]
Please use the gitter channel (https://gitter.im/fossasia/open-event-orga-server) for installation assistance
