### ISSUE TITLE
Tab implementation needs to be improved

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3210]
Either the tab implementation needs to be improved or an alternative implementation needs to be found for the [kubernetes server logs page in Admin section](https://eventyay.com/admin/reports/#!server-logs)

![screenshot from 2017-02-18 14-17-37](https://cloud.githubusercontent.com/assets/9530293/23091853/76d8b53c-f5e5-11e6-9ca6-ea56e7cccce6.png)

**Comment by niranjan94** [comment]
Will be handled in the `frontend`
