### ISSUE TITLE
Improve `Number of Sessions` in Event Dashboard in General Info Dashboard

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3212]
How it looks:

![screenshot from 2017-02-18 15-55-13](https://cloud.githubusercontent.com/assets/9530293/23092505/cbb70d94-f5f2-11e6-8555-9a1071228d91.png)

How it should look:

![screenshot from 2017-02-18 15-48-53](https://cloud.githubusercontent.com/assets/9530293/23092507/d296c956-f5f2-11e6-9f49-d26b106a68f2.png)

**Comment by rahuldecoded** [comment]
Can I fix this bug? @SaptakS

**Comment by Himanshi-Khandelwal** [comment]
I will like to work on this.
