### ISSUE TITLE
Scheduler: Search results showing up twice when changing the date

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3214]
When the user does a search e.g. "Python" on one date and then clicks another date and performs the same search, the search results are showing the same sessions twice. If the search is performed again, the search is showing up three times and more times for more searches.

![screenshot from 2017-02-18 18-42-46](https://cloud.githubusercontent.com/assets/1583873/23092645/34dbe222-f602-11e6-8827-59fb893405a1.png)

**Comment by poush** [comment]
Working on this.

**Comment by mariobehling** [comment]
Actually it looks like any search results in the duplication of sessions.

![screenshot from 2017-02-18 22-40-35](https://cloud.githubusercontent.com/assets/1583873/23093971/5b35ba50-f62b-11e6-8e97-f464fe82c2f1.png)
