### ISSUE TITLE
Cannot move session to drag and drop location when calendar is off-screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3217]
If an event has a lot of sessions, some sessions are below the actual drag and drop calendar. It is not possible to drag the sessions to the calendar that are outside the viewable calendar.

Expected: User should be able to drag and drop a session.

![screenshot from 2017-02-18 22-33-37](https://cloud.githubusercontent.com/assets/1583873/23093941/a7a41216-f62a-11e6-9a47-d7a2e21e16dd.png)

**Comment by poush** [comment]
Working on this.

**Comment by poush** [comment]
This can be closed by #3219
