### ISSUE TITLE
Events showing in location "P" on bottom bar and search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3221]
A number of search results are showing events for the search "P". And it is showing Singapore results as well.

![screenshot from 2017-02-19 07-04-44](https://cloud.githubusercontent.com/assets/1583873/23097568/b8c4eb3c-f671-11e6-8a32-51d1ceb7d2ed.png)

Also on the page bottom it shows "P". The location of the OpenTechSumit is Potsdam actually.
![screenshot from 2017-02-19 07-03-16](https://cloud.githubusercontent.com/assets/1583873/23097566/a8c15a36-f671-11e6-84fe-2cfd87b67daa.png)

**Comment by sj29-innovate** [comment]
Hello @mariobehling .
I would like to work on this issue.

**Comment by niranjan94** [comment]
@sj29-innovate you can proceed if you have set up the server locally on your PC

**Comment by LuD1161** [comment]
@niranjan94 @mariobehling 
SInce no work has been done as of now , I would like to work on this.
Also what exactly do you think it should be displaying , when looking for **'P'** , should it be showing events with the name **P** or should it show events in the **location P** ?

**Comment by SaptakS** [comment]
@mariobehling this error happens because of the response from google maps based on the latitude and longitude of the event. Right now the response received for the latitude and longitude for the specific key we are using for Potsdam is P, so it is showing P. And in search you will see that if it's just a single character, then it matches all events. I am trying to find a workaround.

**Comment by mariobehling** [comment]
Unfortunately this issue is not solved in way that is required. Instead of cities there are now addresses.
![screenshot from 2017-05-16 15-00-28](https://cloud.githubusercontent.com/assets/1583873/26107123/7ea24a7e-3a48-11e7-8cbb-885cd340293e.png)

**Comment by SaptakS** [comment]
@mariobehling looking into it right away.
