### ISSUE TITLE
Faulty tool tips on unscheduled sessions in  scheduler 

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#3222]
This is how the tool tip looks on a scheduled session. 
![image](https://cloud.githubusercontent.com/assets/17252805/23097819/dd54477a-f664-11e6-9133-cb83def10c65.png)

However once a scheduled session is unscheduled , it appears in this form, where it is not supposed to appear. Only the sessions which have been unscheduled after being scheduled seem to behave like this. 
![image](https://cloud.githubusercontent.com/assets/17252805/23097825/10138aea-f665-11e6-9c96-8d560b4182fa.png)

I would like to work on this.

**Comment by niranjan94** [comment]
@CosmicCoder96 please proceed
