### ISSUE TITLE
Scheduler: Dragged and dropped session not saved or shows up on another day

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3223]
Issues being encountered with the scheduler are that, either:
* sessions are not saved and when the scheduler is re-opened they are unscheduled
* sessions are saved, but if the user clicks right away on another day, they are showing up on another day

![screenshot from 2017-02-20 11-49-22](https://cloud.githubusercontent.com/assets/1583873/23111341/f5736a8a-f762-11e6-9434-fb286e00ea67.png)

**Comment by poush** [comment]
@mariobehling could not able to reproduce it here.

**Comment by shubham-padia** [comment]
@SaptakS @mariobehling regarding  first point, are you getting a message "Error occurred while saving the changes" ?
A reason for this ( atleast for me ) was that initially when accepting proposals i did not have some fields enabled as "required" in the custom form for sessions. e.g when accepting proposals initially, in my case, slides was not required, but I changed it to required afterwards.
Can you please check if its the same issue by going to edit mode of the session which is not getting saved and checking if any of the required fields are empty ?

**Comment by mariobehling** [comment]
@shubham-padia It was not the case with me and in the last two days I did not encounter the issue. The behavior you are stating here is another issue.
