### ISSUE TITLE
Changes of colors not getting saved in event wizard step 3

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3224]
If a user changes the colors in event wizard they are not being saved. It will display the previously auto-assigned colors.

![screenshot from 2017-02-20 15-33-17](https://cloud.githubusercontent.com/assets/1583873/23115769/09d1eb68-f782-11e6-9fb3-7a5c13c8c93a.png)

**Comment by poush** [comment]
Working on this.

**Comment by mariobehling** [comment]
If the user goes into the field and edits the color code and then saves it, it is working most of the time. However, if the user chooses the color dropper it does not save the color code.

**Comment by poush** [comment]
The issue was related to event triggering of input fields after color picking. 
@mariobehling @niranjan94 Please see #3230
