### ISSUE TITLE
Sessions Dashboard: Show rejected sessions in red

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3225]
Rejected sessions currently have the same orange background color as pending sessions. Please change the background color of rejected sessions to red.

![screenshot from 2017-02-20 17-41-23](https://cloud.githubusercontent.com/assets/1583873/23119733/5af4a820-f794-11e6-93a5-b2c4948d519e.png)

**Comment by Himanshi-Khandelwal** [comment]
I will like to fix this. Please assign this to me.

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal please proceed
