### ISSUE TITLE
Scheduler Timeslots limited

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3226]
The timeslots in an event that happens over several days are limited to the end time of the last day.

Expected: Show the complete timespan available.

(In future we can define the available timespace for each day, but this is a feature, that we can implement later.)

![screenshot from 2017-02-21 09-51-00](https://cloud.githubusercontent.com/assets/1583873/23147943/c3971230-f81d-11e6-8898-84016ecacec7.png)

**Comment by SaptakS** [comment]
It was previously decided that a session would happen over a single day. We will need to add this feature then because this feature isn't even present.

**Comment by poush** [comment]
Yes, Here in my installation, I'm getting complete timeline of the day ( till 23:45 ) in the calendar

**Comment by niranjan94** [comment]
`frontend` tag added.
Will be re-created on the frontend repo.
