### ISSUE TITLE
Implement session to be "unscheduled" in system and API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3229]
After sessions are accepted they currently get a time assigned that is the start time of the event.

Please implement sessions to have no time assigned.

Use case is: We want to show unscheduled session in the system in the next steps. So, there should not be a wrong time.

Currently also the API shows the time of sessions even though they have not been scheduled.

**Comment by poush** [comment]
@niranjan94 Currently our "start_time" column is non nullable so there should be some data in it. I think there are two possible solutions for this, first one is to make this column nullable and second one is to make our application such that if sessions is not scheduled then show null in "start_time"

**Comment by shubham-padia** [comment]
solved by #3450
