### ISSUE TITLE
Missing information in Rest API for fossasia summit

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-orga-server#3240]
The Speaker data in the api is missing some attributes for some speakers in https://eventyay.com/api/v1/events/6.

- `"session_type" = null` for some speakers [fossasia/open-event-webapp#1069](https://github.com/fossasia/open-event-webapp/issues/1069)

- Multiple speakers listed as `speaker1 and speaker2` as a single speaker . [fossasia/open-event-webapp#1065](https://github.com/fossasia/open-event-webapp/issues/1065)

@niranjan94 @SaptakS Please help.

**Comment by niranjan94** [comment]
@geekyd neither of this is an issue with the server
1. Session type. If a session is not assigned to a session type, you get a null. it's the organizers responsibility to assign session types to sessions.

2. The speakers. I checked the raw data in the system. The speaker information itself has the name like that. Looks like that was the text entered in by the speaker. Again ... It the organizers responsibility here to see for such inputs.

**Comment by geekyd** [comment]
@niranjan94 Thanks for the clearance.
But can't we restrict the organiser to add multiple names in speaker field in the orga-server itself?

**Comment by niranjan94** [comment]
@geekyd the speaker information is added by the person who is submitting the proposal ...  And don't think we can properly differentiate b/w multiple speakers names and a correct firstname lastname
