### ISSUE TITLE
Allow parallel sessions in one location on scheduler

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3243]
Currently the schedule does not allow overlapping sessions. If we want to use the scheduler for exhibitions at events it should be possible to show several exhibitions in one location. Please implement this.

![screenshot from 2017-02-24 22-36-21](https://cloud.githubusercontent.com/assets/1583873/23307354/20c4b3ec-fae2-11e6-96f4-9c5457846dfa.png)

**Comment by niranjan94** [comment]
`frontend` tag added.
Will be re-created on the frontend repo.
