### ISSUE TITLE
Enhance process when organizer adds new sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3244]
Currently when the organizer adds a new sessions, the organizers needs to fill out the complete speaker and session information, please enhance the process as follows:

1. If the organizer clicks on "Create Session" 
  * [ ] Show a pop up "Choose an existing speaker for this session or add a new speaker"
  * [ ] Provide a menu for the organizer to choose from the existing speaker list 
  * [ ] Show a button "Create New Speaker", which directs the organizer to the New Speaker Form

![screenshot from 2017-02-24 22-50-16](https://cloud.githubusercontent.com/assets/1583873/23307755/a13a4324-fae3-11e6-9fd8-bf119838ce40.png)

2. If the organizer wants to create a new speaker:
  * [ ] Do not show the complete form of session and speaker anymore, but only show speaker information to fill in.

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this. 
@niranjan94 The issue is taking some time so can I work on this while I'm on it ?

**Comment by niranjan94** [comment]
@CosmicCoder96 it's better if we work on High Priority issues first

**Comment by Himanshi-Khandelwal** [comment]
I would like to try this.

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal it would be great if you could help on high priority issues https://github.com/fossasia/open-event-orga-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22Priority%3A+High%22

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 ok I will . All are assigned except two in higher priority list . I will have a look at the rest two ones.

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal you could also have a look at all the issues tagged as bugs https://github.com/fossasia/open-event-orga-server/issues?q=is%3Aissue+is%3Aopen+label%3Abug

**Comment by niranjan94** [comment]
`frontend` tag added.
Issue will be re-created on the frontend repo.
