### ISSUE TITLE
Unclear Level values for Sponsors in FOSSASIA SUMMIT end point

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-orga-server#3245]
- API end point https://eventyay.com/api/v1/events/6

-  The api end point provides unclear level information. Please make sure that the `platinum` level numbers should be low as `level 1` followed by gold , silver and others.
The webapp maps the api `level` number with the `priority order` to show the sponsor images.
Issue https://github.com/fossasia/open-event-webapp/issues/1068

**Comment by mariobehling** [comment]
> numbers should be low as level 1 followed by gold , silver and others.

@aayusharora This is not the way the system works. A) Organizers can define what is the name of their sponsorship levels. B) The ranking of the levels is decided by numbers, that can be set by the organizers, e.g. if "5" is the highest number, then 5 is the highest level. If "-3" is the lowest level number, then it is listed last.

**Comment by aayusharora** [comment]
@mariobehling ` Organizers can define what is the name of their sponsorship levels.`
    Yes, the webapp is configured with this.
 ` The ranking of the levels is decided by numbers, that can be set by the organizers, `
   Ok thanks for remembering, We have to handle this part on webapp. Currently,  it arranges sponsors according to values ranging from 1 to 5.
Closing this and forwarding discussions here  fossasia/open-event-webapp#1068
