### ISSUE TITLE
Events Dashboard: Live, Draft, Past events overview table not consistent anymore

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3252]
All views of Live, Draft and Past events should be consistent. They are not anymore currently, e.g. Draft page is showing a table that does not occupy 100% of the space.

![screenshot from 2017-02-25 23-59-59](https://cloud.githubusercontent.com/assets/1583873/23332564/b3da4564-fbb6-11e6-9545-eef205d4a5b2.png)

**Comment by cepradeep** [comment]
I'm working on this.
