### ISSUE TITLE
Display all tracks and take out expansion feature

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3253]
The expansion feature of the tracks **menu** on the public schedule and session page is not helping users. Users should be able to see all relevant tracks right away. At the same time, please reduce the space between track.

Implement as follows:

* Show all tracks 
* Keep space above and next to tracks with reasonable padding, but ensure that the tracks menu does not take up too much screen space

![screenshot from 2017-02-26 01-03-38](https://cloud.githubusercontent.com/assets/1583873/23333070/131baa3c-fbc0-11e6-802f-c56a02ed4f29.png)

**Comment by Achint08** [comment]
I would like to work on this. :)

**Comment by niranjan94** [comment]
@Achint08 please proceed once you're done with #3278

**Comment by shubham-padia** [comment]
@mariobehling @niranjan94 more padding was there to ensure that two track names do not mix up, a solution to that would be borders as implemented below. 
![selection_144](https://cloud.githubusercontent.com/assets/13910561/24458059/7c56f5a2-14b5-11e7-98ab-e24cbdbe1e88.png)

**Comment by niranjan94** [comment]
@shubham-padia this one looks nicer ... especially if you make the border color grey.

**Comment by Achint08** [comment]
Sorry I couldn't continue with the issue.

**Comment by mariobehling** [comment]
@shubham-padia @Achint08 Could you make the design similar to the web app, please?
