### ISSUE TITLE
Tracks Page does not show additional info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3259]
Sessions on the tracks page are supposed to show additional info on clicking on the specific session (similar to web app and sessions view). Currently the area does not expand on clicking it.

![screenshot from 2017-02-26 15-00-30](https://cloud.githubusercontent.com/assets/1583873/23338266/c753ccac-fc40-11e6-9f53-779db90f2f4a.png)

**Comment by mariobehling** [comment]
Issue is not solved entirely yet. Please implement in similar way to Webapp:

1. Not expanded version

![screenshot from 2017-03-05 19-03-16](https://cloud.githubusercontent.com/assets/1583873/23586737/889870da-01d6-11e7-851d-3f487a66ab33.png)

2. Expanded version

![screenshot from 2017-03-05 19-03-40](https://cloud.githubusercontent.com/assets/1583873/23586738/91d374ba-01d6-11e7-976a-30cc5cf7b2f0.png)

**Comment by Princu7** [comment]
I can try to solve this issue if @SaptakS is not currently working on this issue :)

**Comment by mariobehling** [comment]
@Princu7 I think @SaptakS has other open issues and already solved the expansion part. So, please go ahead.

**Comment by SaptakS** [comment]
@Princu7 the expansion part is already done. All you need to do is arrange and put all the relevant information on expanding.

**Comment by Princu7** [comment]
@saptakS Okay. I will try to fill in the rest of the work. Thanks!!

**Comment by Princu7** [comment]
@SaptakS @niranjan94  I am able to access most of the required properties of the speaker though `sessionRefObject.session.speakers` object in the `scheduler.js` file. It contains fields like `name`, `Organization` but doesn't contain the other required fields like `short_biography` and `photo`. Please guide how can I access those fields or from where I can populate them. Thanks!!

**Comment by mariobehling** [comment]
@Princu7 About speaker info, please have a look at the implementation of featured speakers,e.g. https://eventyay.com/e/45da88b7/#feat-speakers.

**Comment by Princu7** [comment]
@mariobehling Thanks. Featured speakers pages directly use the event object passed to it. The schedule page requests data from the API itself. The other info fields of speakers like `short_biography` and `photo` were not defined in the object returned from the API and hence were not present. Adding them to the API should correct the problem :)

**Comment by mariobehling** [comment]
@Princu7 Ok, got it. Though, I wonder I think that should be in the API. 

Would be great, if we could already progress on the other areas. So, we could feature this at the FOSSASIA Summit.

Please open an issue with the details what is missing in the API. Thanks.

**Comment by Princu7** [comment]
@mariobehling @SaptakS The issue has already been solved via a different pull request #3278 :) I have done some work on this issue. Here is a prototype that I made
http://ancient-thicket-44821.herokuapp.com/e/624953ec/schedule/
Please review and suggest. Thanks!!

**Comment by SaptakS** [comment]
@Princu7 looks good. Just put the names beside the speaker image, and use `speaker.small` instead of `speaker.photo`. After that please send a PR so I can check the code. Thanks.

**Comment by Princu7** [comment]
@SaptakS I am sorry. Could you please clarify more on the `speaker.small` point? There seems to be no such field defined in the `api/sessions.py` file. Also, I have opened a request #3336 regarding this issue. Please review it and suggest improvements. Also, in case, speaker doesn't have any image, how do I show a default image?

**Comment by SaptakS** [comment]
@princu7 we need to add small and other image sizes to the api in that case. I think there I already an issue related to adding missing fields in api. In dashboard version you will see that there are 3 image sizes in which speaks image is resized and used accordingly.

In case speaker image isn't there, onerror() function will automatically show placeholder img
