### ISSUE TITLE
Add "Breaks & Activities" in Wizard Step 3 and Scheduler

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3263]
Many events have breaks and activity announcements. These breaks are not necessarily part of a track. Breaks are also recurring. So, in the current flow, we would need to add a number of sessions for coffee breaks so they appear in the schedule. These sessions would also need a speaker. There should be a better way.

Therefore please implement the following:

* [ ] In the create event wizard step 3, after "Session Types" add a section "Breaks & Activities".

![screenshot from 2017-02-26 18-33-59](https://cloud.githubusercontent.com/assets/1583873/23338964/cfe80b14-fc52-11e6-8a14-f09827ac4ad8.png)

* [ ] In this section add a list of standard breaks with times and color choice, that can be edited
   * [ ] Breakfast - 00.30
   * [ ] Coffee and Tea Break - 00:15
   * [ ] Lunch - 01:00
   * [ ] Dinner - 01:00

![screenshot from 2017-02-26 18-43-28](https://cloud.githubusercontent.com/assets/1583873/23339014/fbffe450-fc53-11e6-829e-7699aacd653b.png)

* [ ] In the scheduler create a new section "Breaks & Activities" below the usual session and show the breaks here.
   * [ ] The difference to normal sessions is, that once the user drags and drops a "Break or Activity" the list is refilled with the activity

![screenshot from 2017-02-26 18-47-59](https://cloud.githubusercontent.com/assets/1583873/23339043/83572094-fc54-11e6-860a-2f5f13f1e525.png)

**Comment by sainiak009** [comment]
@niranjan94 @SaptakS I would like to work on this.

**Comment by niranjan94** [comment]
@sainiak009 this is an enhancement. There are more higher priority issue that require attention. Please work one of them.

**Comment by niranjan94** [comment]
`frontend` tag added. 
Issue will be re-created on the frontend repo.
