### ISSUE TITLE
Public Schedule Page/Session Page: Do not show right sidebar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3264]
The right sidebar on the schedule pages reduces the space for the actual schedule.

Please take out the right sidebar on the following pages and expand the schedule/session area to make use of the additional space:
* [x] the public schedule page (and subpages)
* [x] the public session page

![screenshot from 2017-02-26 19-05-12](https://cloud.githubusercontent.com/assets/1583873/23339148/be142a72-fc56-11e6-9d41-45efccdcb1d6.png)

**Comment by Achint08** [comment]
I want to work on this
