### ISSUE TITLE
Schedule: On click show more info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3270]
On clicking on the schedule sessions currently only limited information is displayed. Please show more info here:
* Start time and End time
* Short abstract (up to 500 characters)
* Speaker info (up to 500 characters)

 ![screenshot from 2017-02-27 01-00-24](https://cloud.githubusercontent.com/assets/1583873/23344507/b1af5eac-fcb8-11e6-9939-746e1e3cfcad.png)

**Comment by Achint08** [comment]
I want to work on this. :)

**Comment by niranjan94** [comment]
@Achint08 please proceed
