### ISSUE TITLE
Email option to send email to speaker not working as expected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3271]
There is an email option with a blue button and a mail sign on the accepted sessions, e.g. https://eventyay.com/events/6/sessions/

Currently there is no email window that opens, when the user clicks on the button.

![screenshot from 2017-02-27 17-01-00](https://cloud.githubusercontent.com/assets/1583873/23354971/7c2a0ad8-fd0e-11e6-80e6-c1fd3b891ed8.png)

Expected behavior is: An email windows opens, where the user can send a message to the speaker.

**Comment by sainiak009** [comment]
I would like to work on this issue.

**Comment by sainiak009** [comment]
@niranjan94 Please review my pull request #3284 for this issue.
