### ISSUE TITLE
Name missing in ticket email and invoice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3272]
A recent changed resulted in the name of buyers of tickets not being displayed anymore in the ticket email and orders.

![screenshot from 2017-02-27 19-32-34](https://cloud.githubusercontent.com/assets/1583873/23359936/a2df3ee0-fd23-11e6-9217-6d5998f1f650.png)

**Comment by sainiak009** [comment]
Please assign this to me.I am working on this.

**Comment by sainiak009** [comment]
@mariobehling Please review #3276

**Comment by sainiak009** [comment]
@mariobehling @niranjan94 This issue is resolved.

**Comment by niranjan94** [comment]
@sainiak009 please add proper keywords in your PR description such that issues are closed automatically when merging PR. 

https://github.com/blog/1506-closing-issues-via-pull-requests

And please don't put issue number in your commit message.
