### ISSUE TITLE
Add pop out feature and icon for lightbox of schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3273]
The pop out feature to open a lightbox is a common element in many applications e.g. in Gmail.

![screenshot from 2017-02-27 22-03-32](https://cloud.githubusercontent.com/assets/1583873/23364143/be4b31ba-fd38-11e6-80fd-0e198dd3c2be.png)

Add the icon to access this feature to the schedule on the right-hand side next to "Session View".

Open the schedule in a lightbox with white background and a closing icon again next to "Session View" to the top right to "pop in" the window.

![screenshot from 2017-02-27 22-05-26](https://cloud.githubusercontent.com/assets/1583873/23364250/430df86a-fd39-11e6-8f6a-6b577b633dc8.png)

**Comment by uttu357** [comment]
I would like to work on this issue.. :)

**Comment by niranjan94** [comment]
@uttu357 please proceed ...

**Comment by mariobehling** [comment]
@uttu357 Can we make this lightbox make use of 100% of this window, please?

![screenshot from 2017-03-06 22-47-03](https://cloud.githubusercontent.com/assets/1583873/23614760/07f9fe28-02bf-11e7-88c0-c69dc7eed213.png)
