### ISSUE TITLE
Free Order directs organizer to Paypal payment page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3274]
The free order of paid tickets directs organizer to Paypal and requires organizer to fill in paypal fields (but actually it still shows the ticket as booked without payment at Paypal).

Expected: Do not send organizer to Paypal and show ticket as booked.

![screenshot from 2017-02-28 00-25-39](https://cloud.githubusercontent.com/assets/1583873/23369585/d4a8e40c-fd4c-11e6-9fc9-053aadba5ce6.png)

**Comment by LuD1161** [comment]
I was trying to solve this issue but didn't get the option to make a paid ticket on the local server.
This is what I get on my local server :
![paid-option](https://cloud.githubusercontent.com/assets/17861054/23521120/be48f338-ffa3-11e6-9dfe-a379e94c7ccd.png)

**Comment by shubham-padia** [comment]
Unable to recreate the issue, seems working fine, please reopen if the issue still persists along with steps to recreate the issue.
