### ISSUE TITLE
Unscheduled, pending and rejected sessions show up as part of the schedule in the API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3277]
1. Pending sessions show up in the API and get rendered as part of the schedule by external e.g. Web App Generator apps.

2. If the user accepts sessions and then changes the status to rejected, the sessions will still show up in the API and be displayed on the program if external (e.g. Web App Generator) renders the event.

3. If the event is unscheduled it will just show up on the start time of the event.

4. Speakers with rejected and pending are showing up in the API and are displayed when rendering apps. It is correct that speakers should show up when their session is accepted but still unscheduled, but they should not show up for rejected and pending sessions.

Expected: Unscheduled, pending and rejected sessions should not be included in the API or the API should define the status "null" or "unscheduled" so the sessions are not rendered into the schedule.

**Comment by mariobehling** [comment]
I think defining status of sessions in the API would be best and leave room for more improvements in the future. It would also enable us to solve the issue of the web app quickly.

**Comment by geekyd** [comment]
@niranjan94 @SaptakS Need your help in solving the issue for the web-app.

**Comment by LuD1161** [comment]
@geekyd 
Can I work on this /

**Comment by rctay** [comment]
Looking through scheduler.js, it seems "unscheduled" isn't represented in the sessions model, it's just marked as so based on not having a microlocation or (DOM) position. https://github.com/fossasia/open-event-orga-server/blob/development/app/static/js/events/scheduler.js#L221 Is my understanding right, @niranjan94  ?

**Comment by shubham-padia** [comment]
If the microlocation field of the session is null, the session is unscheduled. The details about the state i.e pending, etc. can be found from the `state` field n the api. Refer to https://eventyay.com/api/v1/#!/sessions/get_session for more info. Closing this.
