### ISSUE TITLE
Tracks Schedule View: Add Tracks List and Search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3279]
The tracks bar of the web app generator offers a tracks list and search. Please implement the same in the server app. Compare to e.g. http://2017.fossasia.org/tracks.html

![screenshot from 2017-03-01 22-11-15](https://cloud.githubusercontent.com/assets/1583873/23463389/3aad0eb0-fecc-11e6-8755-2596e6c4bece.png)

**Comment by SaptakS** [comment]
@mariobehling search is already implemented in https://github.com/fossasia/open-event-orga-server/pull/3481 . And the track list is already implemented in the sessions view. You want a similar one in the tracks view also, am I correct?
