### ISSUE TITLE
Change sessions min time from 15 minutes to 3 minutes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3282]
The session time in the scheduler is minimum 15 minutes. Actually we have sessions that are shorter. Please give organizers the option to scale down the time up to 3 minutes in the scheduler.

**Comment by Himanshi-Khandelwal** [comment]
in this do I need to change time from 15 to 3 min? or give this right to the organiser to do so?

**Comment by niranjan94** [comment]
The organizer should have the ability to change minimum time unit on scheduler to any duration b/w 15 mins and 3 mins.
