### ISSUE TITLE
Links in the featured speaker description are rendered as icons 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3289]
Links in the speaker description should be shown as in the description text.

![screenshot from 2017-03-03 14-36-36](https://cloud.githubusercontent.com/assets/1583873/23540874/eca5faf2-001e-11e7-8ecc-74fcc986cf6b.png)

**Comment by LuD1161** [comment]
I am working on this

**Comment by LuD1161** [comment]
@mariobehling ![solved_with_some_issues](https://cloud.githubusercontent.com/assets/17861054/23735294/ae58819e-04aa-11e7-88a3-dfd5a85d67fc.png)
Is this good ?

**Comment by mariobehling** [comment]
@LuD1161 I think you did not understand the issue. Links that are not Linkedin, Twitter etc. are rendered as Linkedin icons in the speakers description. This is not desired.

![screenshot from 2017-03-09 13-57-23](https://cloud.githubusercontent.com/assets/1583873/23737830/6daa8658-04d0-11e7-9a31-b1ded62394cf.png)

**Comment by LuD1161** [comment]
@mariobehling 
I still don't get what issue do you want to solve ?
Cause I don't get any such icons in the speaker's description
![what_icons](https://cloud.githubusercontent.com/assets/17861054/23740538/0d289f46-04ca-11e7-9bad-c4c6acdb70ef.png)

And this is the website screenshot : ( I don't see any icons here too )
![screenshot_20170309-130816](https://cloud.githubusercontent.com/assets/17861054/23740569/2e1bb8aa-04ca-11e7-84b0-3c18e45eae2a.png)

Please do explain as to where do I need to look to find the issue .

**Comment by niranjan94** [comment]
@LuD1161 try add a linkedin link as text in a speaker description .

**Comment by LuD1161** [comment]
@niranjan94 
See the bottom , I added the LinkedIn url ( at the bottom you can see the link ) in the short description  cause the long description isn't being visible on my system. 
I am still not able to reproduce the issue ...

![Uploading linkedIn.png…]()

**Comment by SaptakS** [comment]
@mariobehling seems okay to me

![screenshot from 2017-03-10 17-11-07](https://cloud.githubusercontent.com/assets/9530293/23795011/62eebc68-05b9-11e7-8464-a527c37dc1df.png)

**Comment by mariobehling** [comment]
Ok, thanks.
