### ISSUE TITLE
Internal Speaker Images are saved as very big png

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3298]
On the organizers and submission pages of speakers images are saved as png. These png are sometimes several MB big. Please ensure a more efficient and smaller storage.

Most speakers will submit an image as jpg. Why is it converted?

![screenshot from 2017-03-05 10-47-50](https://cloud.githubusercontent.com/assets/1583873/23584089/8a810bb8-0191-11e7-93e6-60f70ccac8a6.png)

**Comment by SaptakS** [comment]
https://github.com/fossasia/open-event-orga-server/issues/3300#issuecomment-284263761
