### ISSUE TITLE
Public Schedule/Calendar View: Increase the size of the font and make it bold

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3309]
The text of the calendar view is often difficult to read as it is small. Please:
* increase the size of the font
* make it bold

![screenshot from 2017-03-06 22-36-13](https://cloud.githubusercontent.com/assets/1583873/23614348/929b4ac0-02bd-11e7-9af3-eae14de17628.png)

**Comment by CosmicCoder96** [comment]
@mariobehling I would work on this.

**Comment by LuD1161** [comment]
@mariobehling 
Is this good ?
![image](https://cloud.githubusercontent.com/assets/17861054/23821068/1409389a-064e-11e7-88e9-1c282232029b.png)

Or should it be larger ( current font is 15px earlier it was 11px )

**Comment by poush** [comment]
@LuD1161 Looks like @CosmicCoder96 is already working on this issue. You can work on other open issues.

**Comment by mariobehling** [comment]
Good progress, but we need to ensure, that the 10 minute slots can display 3 lines of text.

![screenshot from 2017-03-12 10-25-20](https://cloud.githubusercontent.com/assets/1583873/23828503/90784cc0-070e-11e7-98f8-a5548f77bf03.png)

Please do the following to solve this:
* ensure text padding to the right of the session box is same as to the left indent of text
* decrease space between lines, e.g. Single line spacing

**Comment by mariobehling** [comment]
Please also ensure three dots "..." only appear when the whole space is used.

![screenshot from 2017-03-12 10-31-06](https://cloud.githubusercontent.com/assets/1583873/23828522/1856c9aa-070f-11e7-91b8-2cb06be895c4.png)
