### ISSUE TITLE
The demo version is down

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#331]
http://open-event.herokuapp.com/admin/ 

![screenshot from 2016-05-17 15 18 50](https://cloud.githubusercontent.com/assets/1327050/15318208/b13ea79a-1c42-11e6-8275-4b926dc24ae0.png)

**Comment by championswimmer** [comment]
Deploying to heroku is not working either 
![screenshot from 2016-05-17 15 21 57](https://cloud.githubusercontent.com/assets/1327050/15318333/4239a402-1c43-11e6-9b1e-afadfe3b0b5e.png)

**Comment by aviaryan** [comment]
@championswimmer Can you provide logs from heroku ?

**Comment by aviaryan** [comment]
I opened issue #332 on improving the Heroku documentation. With that, I will also make sure that the instructions in the guide work. So this issue will also be taken care of. :smile:

**Comment by aviaryan** [comment]
Fixed it finally ! https://open-event-test.herokuapp.com 
PR #333
