### ISSUE TITLE
Public Schedule: Offer search box in top menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3310]
The organizer front end offers a search bar for sessions and speakers. The public schedule is missing that. Please offer a search bar in front of the rooms view button (on the left of the button).

![screenshot from 2017-03-06 23-02-39](https://cloud.githubusercontent.com/assets/1583873/23615385/30aacd32-02c1-11e7-923a-2dd010bdc864.png)

**Comment by LuD1161** [comment]
@mariobehling 
Are you talking about this ?

![scheduler](https://cloud.githubusercontent.com/assets/17861054/23986858/559ff382-0a4c-11e7-82f6-90224cac0219.png)
![sessions](https://cloud.githubusercontent.com/assets/17861054/23986859/55c714d0-0a4c-11e7-88b4-559a0357f1ff.png)
![speakers](https://cloud.githubusercontent.com/assets/17861054/23986860/55e4c2e6-0a4c-11e7-934b-8743f555f973.png)

**Comment by Himanshi-Khandelwal** [comment]
@LuD1161 I am about to complete this issue.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling is this ok ? 
![screenshot from 2017-03-16 18 51 49](https://cloud.githubusercontent.com/assets/17119462/23998008/ad736d14-0a79-11e7-9e63-9b1eadf0a787.png)

**Comment by rctay** [comment]
Do you have it on a branch? So we can have a look.

**Comment by Himanshi-Khandelwal** [comment]
I am currently doing the backend part of it. When done will make a PR?

**Comment by rctay** [comment]
Sure. Are you reusing the code used for sessions/speakers on admin/organiser view? I think we can't and it's going to be a bit tricky because of the time bars.

**Comment by Himanshi-Khandelwal** [comment]
I'll check and will make the appropriate changes. Is frontend part OK?

**Comment by Himanshi-Khandelwal** [comment]
@rctay  I am implementing the search through javascript .Is this oK? but facing a bit problem.
