### ISSUE TITLE
Public Schedule cannot scroll session in pop-out view and decrease space after paragraphs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3315]
* Cannot scroll calendar with expanded session info in pop-out view. Only page scrolling, but not the session view itself.

![screenshot from 2017-03-07 09-48-20](https://cloud.githubusercontent.com/assets/1583873/23638226/40ea25c6-031b-11e7-9292-73ead46c8ab1.png)

* Decrease space after "About Speaker" and "Session" paragraphs.

![screenshot from 2017-03-07 09-46-04](https://cloud.githubusercontent.com/assets/1583873/23638247/5ac2d236-031b-11e7-849c-350c5fb81d16.png)

**Comment by LuD1161** [comment]
@mariobehling 
Working on this

**Comment by mariobehling** [comment]
> However I don't get the first issue...cause I am able to scroll 

Scroll with the expanded info and keep the cursor over the expanded area. Not possible here atm. 
And when I scroll over other area, the expanded area stays in the place and the background moves only.
