### ISSUE TITLE
Public Pop-out schedule: Do not include "timings" on bottom area and don't show scroll bar on bottom if no scroll

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3316]
The bottom area of the public schedule shows a scroll bar even if there is not enough content to scroll. Please avoid this.

The area below the scroll bar also shows the timings e.g. Singapore. Please take out the timings from the pop-out menu (only show it in the no pop-out version).

![screenshot from 2017-03-07 12-11-28](https://cloud.githubusercontent.com/assets/1583873/23641548/8eccfcdc-032f-11e7-84b2-1bba48877db3.png)

**Comment by poush** [comment]
@mariobehling Please see If #3324  resolves the issue for scrollbar.
