### ISSUE TITLE
Schedule Calendar View: Show calendar only 15 minutes after last session

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3318]
As the session info is not showing over the surrounding areas, please reduce the time of the schedule shown after the last session.

Only show the schedule until "15 minutes after the last session".

**Comment by mariobehling** [comment]
It seems like the implementation still shows sessions until 45mins after the end of the last session.

![screenshot from 2017-03-12 10-52-57](https://cloud.githubusercontent.com/assets/1583873/23828605/2aec3016-0712-11e7-9ac6-1da1428c18ac.png)

**Comment by SaptakS** [comment]
@mariobehling seems okay to me.
![screenshot from 2017-03-12 12-20-39](https://cloud.githubusercontent.com/assets/9530293/23829673/64fcb15c-071e-11e7-979e-fbb4614971d4.png)

Can you please clear cache and check maybe?

**Comment by mariobehling** [comment]
![screenshot from 2017-03-12 15-28-15](https://cloud.githubusercontent.com/assets/1583873/23830049/ec140682-073b-11e7-84aa-f8f7747b2fb9.png)

The iterations on the schedule time on the left column are in 10 minutes. They should be in 15 minute steps. The schedule become very long now.

Of course we have to look at the size of the font, but that is another issue. 15 minute iterations, if possible.

**Comment by SaptakS** [comment]
@mariobehling I told you that in 15 minute iteration if a session is only 5 minutes long then it becomes very thin and almost not visible. So I made it into 10 minutes iteration.

**Comment by mariobehling** [comment]
Yes, exactly. 5 minute tracks are very seldom and it is ok to have them in one line e.g. 5 min break.

**Comment by SaptakS** [comment]
So, you recommend to increase the time iteration to 15minutes?? That would make any session below 10 minutes difficult to read or understand.

**Comment by mariobehling** [comment]
> So, you recommend to increase the time iteration to 15minutes??

Yes.

> That would make any session below 10 minutes difficult to read or understand.
That is another issue. We should have the sessions aligned to the top instead of the middle and consider how to adapt the font -> in another issue.

Not sure, how to make it more clear: The schedule like at FOSSASIA is too long.

This is a continuation of a thread we had on chat and this thread is getting a bit too long for me now.

Again: The long schedule does not work on screen and print. We need to adapt the font and alignment after this is shortened -> in another issue. Issue by issue..

**Comment by mariobehling** [comment]
@SaptakS This is also related to https://github.com/fossasia/open-event-orga-server/issues/3309#issuecomment-285916779

**Comment by SaptakS** [comment]
@mariobehling got it. Fix coming up soon. :)

**Comment by mariobehling** [comment]
Actually I am starting to get confused. We are mixing up to issues here now. 

Issue a) Scale on the left column.
* Expected: It should be 15 minutes intervals. 

Issue b) Space after last session is longer.
* Expected it should be 15 min space below (or one iteration). Also in your screenshot, the last session ends at 17.15 and the schedule ends at 17.40 (to 18.00). So, just one "big row/iteration of mins" below is fine. No need to use so much empty space below now (You already solved the issue to ensure the expansion shows up over all other "layers".).

**Comment by SaptakS** [comment]
@mariobehling please check the https://github.com/fossasia/open-event-orga-server/pull/3373
