### ISSUE TITLE
Public Event Page: Background image ratio

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3319]
It seems the ratio of the background image is a bit distorted. Can you confirm?

e.g. https://eventyay.com/e/45da88b7/

![screenshot from 2017-03-07 12-43-50](https://cloud.githubusercontent.com/assets/1583873/23642277/618d5258-0334-11e7-9718-29ced6291e0b.png)

**Comment by SaptakS** [comment]
The code seems absolutely fine. https://github.com/fossasia/open-event-orga-server/pull/2838 I had corrected the code. So the code is fine.

**Comment by mariobehling** [comment]
Is the image maybe scaled wrongly or is it the issue of the html on that page? Do you see that there is a scaling issue by looking at it?

**Comment by SaptakS** [comment]
I think it is an issue with the html. This looks ok, right?

![screenshot from 2017-03-09 14-24-31](https://cloud.githubusercontent.com/assets/9530293/23746347/9d027dc8-04e1-11e7-85cb-e2015befe2a2.png)
