### ISSUE TITLE
Improve Heroku deploy docs

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#332]
The heroku deploy docs (https://github.com/fossasia/open-event-orga-server/blob/master/docs/HowtoDeploytoHeroku.md) don't mention anything about creating a database and setting DATABASE_URL to it. Without that step, the deployed app won't function. 
Also nothing is mentioned about database migrations on server.

**Comment by aditya1702** [comment]
@aviaryan I have already rearranged the files and opened a PR for the docs. If you may allow I could assign this to myself. Moreover the database migration instructions are mentioned in the VAGRANT.md ..Here is the link https://github.com/fossasia/open-event-orga-server/pull/305/files

**Comment by aviaryan** [comment]
@aditya1702 By migration, I meant migration on a running heroku server. BTW, I have changed a lot in the heroku file. See PR #333 for that. Let us see what @juslee @leto think about the changes, then we can work on conflict issues. Anyways, we can always update one PR after the other is merged.

**Comment by aditya1702** [comment]
@aviaryan Ok :+1:
