### ISSUE TITLE
Schedule: Track view on mobile - expansion not possible and not using full width

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3323]
Track view of the schedule on mobile has two issues:
* cannot see detailed info of track by tapping on the area on mobile
* track view is not using full width of screen on mobile

**Comment by shubham-padia** [comment]
@mariobehling Point one seems to be a vendor specific issue. Mine worked fine for chrome in android. Can you please specify the OS and the browser to recreate the issue.

**Comment by mariobehling** [comment]
Chrome 56 on Android 4.4.2.

Still not working. Just tried last version.

**Comment by SaptakS** [comment]
Working fine. Closing the issue.
