### ISSUE TITLE
Inactive Promo Code still working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3331]
There is the option of making promo codes inactive in the table view. If the user does it, the code shows "inactive" in the table, but actually on the ticket page the promo code still works.

At the moment the only option is to delete the promo code.

![screenshot from 2017-03-08 00-45-36](https://cloud.githubusercontent.com/assets/1583873/23667414/baf852de-0398-11e7-97ed-8487406588bb.png)

**Comment by poush** [comment]
I would like to work on this.
