### ISSUE TITLE
Show discount code in Orders and Attendee Overview and offer Filtered Search for Discounts

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3332]
Right now, it is not possible to see all attendees who have used a certain discount code. 

* [ ] Please add a discount code in the orders and attendee table as shown below.

![screenshot from 2017-03-08 11-25-39](https://cloud.githubusercontent.com/assets/1583873/23688914/33c8193e-03f2-11e7-84f6-f986dc3154c1.png)

* [ ] Also offer a filtered search for discounts on the dedicated area for searches.

![screenshot from 2017-03-08 11-24-28](https://cloud.githubusercontent.com/assets/1583873/23688941/67a97f86-03f2-11e7-92d4-39d5efd923ff.png)

Expanded:

![screenshot from 2017-03-08 11-29-52](https://cloud.githubusercontent.com/assets/1583873/23688968/94e3440a-03f2-11e7-80fe-a8b9b08a1c08.png)

**Comment by LuD1161** [comment]
Working on it

**Comment by LuD1161** [comment]
@mariobehling 
Should it be like this ?
Right now I have only finished the first part of the issue , working on the filter part.
![first_part](https://cloud.githubusercontent.com/assets/17861054/23744420/287a3178-04da-11e7-83a3-7b71b4feba72.png)

**Comment by mariobehling** [comment]
Instead of "Free" Show the actual discount code, e.g. "PROMOCODE2016" or whatever the discount code is.

**Comment by LuD1161** [comment]
@mariobehling 
"Free" is the discount code :)

**Comment by mariobehling** [comment]
@LuD1161 Ok, looks good then. Please make a PR.
