### ISSUE TITLE
Schedule: How can we get a PDF print out version from the browser

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3335]
The browser does not generate a proper pdf print-out version of the calendar schedule. 

https://eventyay.com/e/45da88b7/schedule/

Please implement a pdf.

**Comment by cepradeep** [comment]
One option is to add `@media print` CSS styles, but I'm not sure how much improvement this will fetch us. It's worth a try, though.

**Comment by rctay** [comment]
See #3398.

**Comment by mariobehling** [comment]
Still pending full implementation.

**Comment by niranjan94** [comment]
@mariobehling then it can be taken forward in issue #3615

No need to have two open issues for the same bug.

**Comment by mariobehling** [comment]
Ok, sorry. Let me be more clear. As css was mentioned in this issue, let's follow up on the pdf version that requires a specific css in this issue. Made the title clearer for this.
