### ISSUE TITLE
Installation not working on Fedora

### ISSUE THREAD

**Issue by cepradeep** [fossasia/open-event-orga-server#3337]
**WHAT:**

On Fedora 25, when installing the dependencies with `pip install -r requirements.txt`, the installation of `librabbitmq` fails with the following error:

```
clib/librabbitmq/amqp_socket.c: In function ‘amqp_login_inner’:
  clib/librabbitmq/amqp_socket.c:1195:28: error: ‘AMQ_PLATFORM’ undeclared (first use in this function)
           amqp_cstring_bytes(AMQ_PLATFORM);
                              ^~~~~~~~~~~~
  clib/librabbitmq/amqp_socket.c:1195:28: note: each undeclared identifier is reported only once for each function it appears in
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for librabbitmq
  Running setup.py clean for librabbitmq
Failed to build librabbitmq

```
You can find a more detailed version of the output in [this text-dump](https://paste.opensuse.org/view/simple/22524203).

**HOW TO REPRODUCE:**

On any Fedora system, navigate to the root of the project, and run `pip install -r requirements.txt`.

**PROPOSED SOLUTION:**

This seems like an issue with version `1.6.1` of `librabbitmq` on Fedora. Switching to `1.5.1` leads to a successful install. Possible solutions:

 - Edit `requirements/common.txt` to use the working version:
    ```
    librabbitmq==1.5.1
    ```

 - Add a new Fedora-specific `requirements-fedora.txt` file with this change.

 - Or simply,
    ```
    pip install librabbitmq==1.5.1
    ```

**ALSO SEE:**

https://github.com/fossasia/open-event-orga-server/pull/2443

**Comment by SaptakS** [comment]
So pip install librabbitmq==1.6.1 doesn't work in fedora 25??

**Comment by SaptakS** [comment]
I think I made the modification... For 1.5.1...

**Comment by cepradeep** [comment]
No, it doesn't. I spent all of today chasing down various options before finding your PR#2443 referenced here: https://github.com/celery/librabbitmq/issues/61. I think your change was overwritten by a later commit.

I think adding a `requirements-fedora.txt` file and noting this in the install docs is the better way forward, unless someone has noticed a critical clash between these two versions. That way, non-Feodra people can continue using the latest version. What do you think?

I'd be happy to work on this for my first patch! :)

**Comment by SaptakS** [comment]
I think fixing it to 1.5.1 is a better solution. I believe that if it isn't working in fedora it might fail in rhel and other OS as well.

**Comment by cepradeep** [comment]
Okay, I'm on it!

It's worth noting that we've to be careful about not over-writing these changes, since most developers ought to be at `1.6.1` now.
