### ISSUE TITLE
Public Schedule add event name and move some info to bottom

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3339]
On the top area please add the name of the event in front of "Schedule".

Also move "Published on..", e.g.  (Published on March 01, 2017) to the bottom without brackets.

![screenshot from 2017-03-09 14-18-01](https://cloud.githubusercontent.com/assets/1583873/23738451/f4477772-04d3-11e7-93c3-12e546405b03.png)

**Comment by LuD1161** [comment]
@mariobehling 
Is this good ?
![scheduler](https://cloud.githubusercontent.com/assets/17861054/23781616/aa455b3e-0574-11e7-9beb-0f97fe2712e3.png)

**Comment by mariobehling** [comment]
Yes, very good.

Please also move "Published on.." to the same line as "All timings...". Keep it on the left side and get rid of the "( )" brackets.

**Comment by LuD1161** [comment]
Making a PR with the a new branch and a new forked repo ...
The previous one was all messed up
Hope this is what is needed..

![image](https://cloud.githubusercontent.com/assets/17861054/23787630/f27216c6-0598-11e7-9640-f62e6cae1df9.png)
