### ISSUE TITLE
Swagger spec for existing GET API endpoints

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#334]
I've created the swagger spec for existing APIs. The demo heroku app doesn't seem to be working right now, so I've set the host as 127.0.0.1:8001. You can test it with your local installation here: http://editor.swagger.io/#/?import=https://gist.githubusercontent.com/shivamMg/dacada0b45585bcd9cd0fbe4a722eddf/raw/ddb8af9f34a5ca163c4e49b5c14ee0d4db342fe0/swagger.yaml

<del>I haven't created a PR yet. Where should I create it? here or at the [Open Event](https://github.com/fossasia/open-event) repo.</del> Forget it. New discussion [here](https://github.com/fossasia/open-event-orga-server/issues/336).

**Comment by rafalkowalski** [comment]
Please add PUT and POST, DELETE methods

**Comment by shivamMg** [comment]
@rafalkowalski Wanted to have a discussion before that. [Feedback appreciated](https://github.com/fossasia/open-event-orga-server/issues/336).
