### ISSUE TITLE
Feature Status ( Each Track being mapped to a color in JSON )

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-orga-server#3353]
@mariobehling 
Hey! 
Is each Track mapped to a color in the server? 
I am asking this in reference to the open-event-android app as I would like to implement the UI in the app vis-à-vis to how the color is set in the server.

Thanks!

**Comment by niranjan94** [comment]
@shreyasnbhat yes. Each track has a color. You can check the API Docs at https://eventyay.com/api/v1/

**Comment by shreyasnbhat** [comment]
@niranjan94 Thanks!
Just a suggestion!
I think a better way to keep the color attribute is a hex code instead of a name like "green".
It would reduce the app-side code drastically.

@mariobehling
@niranjan94
Thoughts?

**Comment by niranjan94** [comment]
@shreyasnbhat the color code is a hex. Please see the API output

**Comment by niranjan94** [comment]
@shreyasnbhat FYI https://eventyay.com/api/v1/events/6/tracks

**Comment by shreyasnbhat** [comment]
@niranjan94 My bad didn't see that.
