### ISSUE TITLE
HTML in sponsor description breaks event page text

### ISSUE THREAD

**Issue by cepradeep** [fossasia/open-event-orga-server#3354]
**WHAT:**

In the second step of event creation, if rich text (with underlying HTML) is pasted into the sponsor description field, then the tooltips and text on the event page break after the event is live.

__HOW TO REPRODUCE:__

 - Go to the 'Sponsors' step of creating a new event. Enable sponsors.
 - Go to http://loripsum.net, copy a paragraph of the text and paste it into the 'Description' field.
 - Proceed and publish the event.
 - Visit the event page to see broken tooltips and text layout.

**SCREENSHOT:**

![orga-10mar](https://cloud.githubusercontent.com/assets/6213734/23805594/8a6ee332-05e4-11e7-9356-dea6239fef8a.png)

**Comment by LuD1161** [comment]
@cepradeep 
I don't get any broken tooltip and text layout.
My Output is :
![image](https://cloud.githubusercontent.com/assets/17861054/23820689/6b892f76-0644-11e7-88b1-4d578eb63abb.png)

And my http://loripsum.net configuration is :

![image](https://cloud.githubusercontent.com/assets/17861054/23820693/8a392106-0644-11e7-9331-ef4fbb3e45c8.png)


I think I may be missing something , do suggest a way to recreate the issue

**Comment by niranjan94** [comment]
@LuD1161 looks like your local repo is behind the `dev` ... From your screenshots, I can see that tooltips are not rendering HTML. BUt HTML rendering in tooltips was added in https://github.com/fossasia/open-event-orga-server/pull/3349

**Comment by LuD1161** [comment]
@niranjan94 I have updated the repo , thanks for pointing that out.
But still am unable to recreate the issue.
This is what I get
![image](https://cloud.githubusercontent.com/assets/17861054/23821160/0174979a-0650-11e7-99c9-91fd24ded3b9.png)

**Comment by SaptakS** [comment]
@cepradeep I think you copy pasted instead of pasting it as text. Because when I write the entire thing down as a text it works fine but on copy-pasting there is an error because of some double quotes in the html of the loremipsum text html. Copy-pasting would copy the entire styling as well and not only the text which might be causing the problem. Please confirm.

**Comment by cepradeep** [comment]
@LuD1161 @SaptakS I confirm that the issue is with double quotes in the HTML. Since there is a fair chance that people are going to copy-paste, what do you guys think is the best way to handle this?

**Comment by cepradeep** [comment]
> But still am unable to recreate the issue.

@LuD1161 Did you try creating an event _after_ you pulled the latest changes? Here's one I created just now: http://open-event-dev.herokuapp.com/e/c1d05195/

Here's a better way of reproducing the bug:

 - Go to http://summernote.org/ and type something in the editor.
 - Select the text and give it a highlight color (it's the icon that says `A`).
 - Copy the text and paste it into the Description field of a sponsor.
 - Publish event and visit event page.
