### ISSUE TITLE
Setting rejected talk to Accepted, but it does not show up in scheduler

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3355]
After I set a rejected talk to accepted it does not show up in the scheduler.

![screenshot from 2017-03-11 02-43-32](https://cloud.githubusercontent.com/assets/1583873/23808395/a740cbe0-0604-11e7-9ec6-7c20d929f293.png)

**Comment by CosmicCoder96** [comment]
@mariobehling working on this.
