### ISSUE TITLE
Time Limit Exceeded dialog appears while trying to buy ticket.

### ISSUE THREAD

**Issue by betterclever** [fossasia/open-event-orga-server#3356]
Step to reproduce:
- Login on https://open-event-dev.herokuapp.com/
- Try buying tickets for event betterclever-test-event.

Actual behaviour: The Time Limit Exceeded dialog appears immediately and it is impossible to buy ticket.

Expected behaviour: The Dialog should appear at end of timer.

Relevant Screenshots: 

![](https://files.gitter.im/fossasia/open-event-orga-app/C9C9/Screenshot-from-2017-03-11-05-52-59.png)

**Comment by niranjan94** [comment]
It works .. See -> https://open-event-dev.herokuapp.com/orders/2d69431a-08fa-4d19-8564-d9d07a6caf4a/view 

Tried on multiple browsers and accounts. Works.
