### ISSUE TITLE
Ticket is generated and sold without taking ticket holder name, email details.

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-server#3358]
Order is placed with these empty fields and tickets are generated and sold.

![screenshot 12](https://cloud.githubusercontent.com/assets/13533840/23812166/4e026282-05ff-11e7-9558-c1d268b5c5f7.png)

The JSON response for such attendees is coming as-
```
{
	"id": 359,
	"order": {
		"id": 242,
		"identifier": "7ca7b854-57d2-4399-b3b3-68a3bee8b92f",
		"paid_via": "free",
		"amount": 0.0,
		"invoice_number": "O1489178012-242",
		"status": "completed",
		"completed_at": "2017-03-10T20:33:43",
		"payment_mode": null
	},
	"email": "",
	"lastname": "",
	"firstname": "",
	"ticket": {
		"id": 187,
		"price": 0.0,
		"description": "",
		"type": "free",
		"quantity": 100,
		"name": "My Ticket"
	},
	"checked_in": false
}
```

**Comment by CosmicCoder96** [comment]
@niranjan94  I am working on this

**Comment by mejariamol** [comment]
@CosmicCoder96 @niranjan94 please see the screenshots attached.

On pressing submit button with empty fields, processing button is shown with response 400 bad request . And ticket is not generated. But on refreshing same page ticket confirmation page appears. 

![screenshot 14](https://cloud.githubusercontent.com/assets/13533840/23843281/c9a33870-07e0-11e7-9094-472173f191b1.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/13533840/23843280/c9a2e640-07e0-11e7-94f2-9eeddcf38004.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/13533840/23843282/c9a7a8e2-07e0-11e7-9f7a-95b4f967273b.png)

**Comment by CosmicCoder96** [comment]
@mejarimol 
The error code is deliberate. Regarding refresh .. I will look into it.
