### ISSUE TITLE
Create a screencast showing the main features of the Open Event server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3361]
Please create a screencast taking 3 minutes with the main features of the app. Include:

* Login
* Creating an event including sponsors, tracks and sessions and call for speakers
* Submitting a session as a speaker
* Accepting sessions 
* Adding different sessions to the schedule
* Showing the public page and schedule
* at the end show the GitHub page of the project
* do not show any subtitles

If you cannot do this in 3 minutes, consider speeding up the video. Ensure it is still visible.

**Comment by virresh** [comment]
@mariobehling, Can this screencast be a gif or has to be a video ?
And in case of a video, does it have to be one without audio ?

**Comment by mariobehling** [comment]
You can make it with or without audio, but it needs to be a video as gif would be too long and too big.

**Comment by poush** [comment]
@virresh I think if you are able to make gif then the video should not be the issue.

**Comment by virresh** [comment]
@poush , @mariobehling  I would like to go ahead and make a screencast hopefully soon.
Though I am not sure how do I make a PR or get reviews on the screencast. Shall I upload the video on some hosting website (probably youtube) and embed the link in readme ?
