### ISSUE TITLE
Ticket Attendees Page: Discount and ticket if 0.00 info not displayed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3363]
The ticket overview attendees page does not display:
* discount codes
* ticket cost if 0.00 show "Free"

![screenshot from 2017-03-12 01-29-43](https://cloud.githubusercontent.com/assets/1583873/23825379/a3aaea78-06c3-11e7-87a4-46264686a83a.png)

**Comment by LuD1161** [comment]
@mariobehling 
I forgot to update in the attendees page , while solving issue #3332 . Will do it soon.

**Comment by LuD1161** [comment]
@mariobehling 
I got this :
![image](https://cloud.githubusercontent.com/assets/17861054/23962312/af1fcf0a-09d3-11e7-95fc-709e79846696.png)

But I have some doubts regarding code :
In the file '**app/views/users/ticket_sales.py**'
*if len(order.ticket_holders) == 0:*
what is this order.ticket_holders ?
