### ISSUE TITLE
Tickets show sold out even though capacity was increased

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3366]
A few days ago the organizers increased the capacity of tickets. Now they show up as sold out even though the capacity is not reached.

![screenshot from 2017-03-12 09-58-38](https://cloud.githubusercontent.com/assets/1583873/23828388/ce9a1f78-070a-11e7-93d0-524c30318981.png)

Shows sold out.

![screenshot from 2017-03-12 10-01-21](https://cloud.githubusercontent.com/assets/1583873/23828392/e1f56ec4-070a-11e7-9468-6eee1f818808.png)

**Comment by poush** [comment]
Would like to work on this.
