### ISSUE TITLE
Write tests for API views

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#337]
Almost the whole of open_event/views/views.py which comprises of API methods is untested. 
We need to write tests to cover the same.

**Comment by aviaryan** [comment]
Since API v2 has been made using flask-restplus and merged to master, we would be working on it. 
So @juslee , should this issue be closed ?

**Comment by shivamMg** [comment]
@aviaryan I'm closing this issue. We will most probably be removing version 1 APIs after webapp and android client stop using them.

**Comment by mariobehling** [comment]
Web and Android app should not be using APIs at this point of time. At the moment these apps should be build by using sample JSON files of events.

**Comment by shivamMg** [comment]
@mariobehling I named the newer APIs as version 2 only to avoid conflicts with version 1. After version 2 apis are complete we can remove v1 and rename v2 to v1.
