### ISSUE TITLE
Schedule Calendar Version: Remove unused column next to rooms columns

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3374]
There is a kind of empty column on the right hand side of rooms, which is not holding any information. Please end the table after last room and do not show a column with no information.

![screenshot from 2017-03-12 15-11-32](https://cloud.githubusercontent.com/assets/9530293/23830688/8f16feee-0736-11e7-9a62-fe37e0f9fc2e.png)

**Comment by LuD1161** [comment]
@mariobehling 
Do you suggest something like this ?
![image](https://cloud.githubusercontent.com/assets/17861054/23991936/1722dc5e-0a61-11e7-84c0-4f83ef996c26.png)

**Comment by SaptakS** [comment]
@LuD1161 looks good. Can you please send a PR?

**Comment by LuD1161** [comment]
@SaptakS 
Will make it soon

**Comment by SaptakS** [comment]
@LuD1161 are you still working on this?
