### ISSUE TITLE
Increase resolution of exported schedule as png to 300px

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3375]
The resolution of exported schedule pngs is good for screens, but for print outs it is not high enough. Please increase the resolution to 300px.

**Comment by SaptakS** [comment]
@mariobehling what I have found out is that for html to png conversion, the technique used everywhere is converting the div to a canvas and on rendering, we save the canvas to a blob. This blob by default saves a png with 96dpi resolution. We can save it in jpg as well but there is no way of changing the resolution. As far as I can see. 

So the two options that I have found is:
* Divide the entire timeline into smaller parts of fixed size for which 96dpi is good and downloading one by one.
* Save as pdf

@niranjan94 or if anyone has a better solution please tell me.

**Comment by mariobehling** [comment]
@SaptakS Surely pdf would be the best, but in what size? In the past the pdf export was implemented because it was faster to do. Can you get the pdf export done before the event?

**Comment by SaptakS** [comment]
Let me check. I think I can.
