### ISSUE TITLE
Public Schedule: Do not show bottom scrollbar if there is nothing to scroll

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3377]
There is a scroll bar area on the bottom of the public schedule even if there is only one room and nothing to scroll to.

Expected: Do only show scroll bar if there is something to scroll to.

![image](https://cloud.githubusercontent.com/assets/17861054/23787777/a0fb8574-0599-11e7-9d69-bb7cbdd7943e.png)

**Comment by geekyd** [comment]
@mariobehling I would like to fix this.

**Comment by geekyd** [comment]
@mariobehling @SaptakS @niranjan94 Please check the screenshots of the solution.

**When nothing to scroll**
![screen shot 2017-03-13 at 3 00 41 pm](https://cloud.githubusercontent.com/assets/12807846/23848603/11e5fdc6-07fe-11e7-8a51-02a777ea0f86.png)

**When there is something to scroll**
![screen shot 2017-03-13 at 3 01 05 pm](https://cloud.githubusercontent.com/assets/12807846/23848604/11efba64-07fe-11e7-985c-abb03b3adddf.png)

**Comment by mariobehling** [comment]
@geekyd Actually it is an easier flow if you just make a PR instead of asking for some details, that I think are probably obvious. In any case if things are not ok, they can still be discussed in the PR. Especially for small things - just make a PR directly instead of asking too much about opinions. --> Yes, correct: There should not be a search bar if there is nothing to scroll. Thanks.

**Comment by geekyd** [comment]
@mariobehling I will keep it in mind. Thank you for the feedback.
