### ISSUE TITLE
Relative ID for sessions, speakers and other things

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#338]
Currently sessions, speakers, tracks and eveything else have an absolute id. That is, if the first session is created in an event with id 234, it may well have the id 10234. If that's the case, then the url to get that session will be `events/234/sessions/10234` (see #336) which ideally should have been `events/234/sessions/1` . 
Same goes for speaker, languages, microlocation, sponsors and other things. 
As all of these things are inside an event, there ID should be relative to it. 
I currently don't know a good way to fix this problem so I am not sure whether this idea is worth pondering or not.

@juslee @leto @shivamMg your views ??

**Comment by juslee** [comment]
Explained in #336

**Comment by aviaryan** [comment]
> Reason: in the db, you just need to make sure the session table has the event id reference. Session ID is the primary key. If session id is relative, it will require more checking in code to determine if session id is part of the event. And there isn't any point to have a separate primary key and session id.

I was thinking the same. The main hurdle in doing this is lack of an efficient solution.

**Comment by aviaryan** [comment]
Since we are going with absolute id's , closing this issue now. It can be reopened if needed.
