### ISSUE TITLE
Exported public schedule has partly transparent background

### ISSUE THREAD

**Issue by poush** [fossasia/open-event-orga-server#3381]
The background should be completely white.
<img width="981" alt="screen shot 2017-03-12 at 11 38 23 pm" src="https://cloud.githubusercontent.com/assets/1812082/23834471/0d6382c2-077d-11e7-87a3-3330af1bde82.png">
<img width="930" alt="screen shot 2017-03-12 at 11 38 33 pm" src="https://cloud.githubusercontent.com/assets/1812082/23834472/0dad31c4-077d-11e7-8852-0394f1dfb79e.png">

**Comment by Himanshi-Khandelwal** [comment]
@poush please attach a screenshot with this.

**Comment by poush** [comment]
Added to main post

**Comment by Himanshi-Khandelwal** [comment]
I would like to work on this.

**Comment by Himanshi-Khandelwal** [comment]
@poush  are you talking about this export (while clicking in export as png)?
![screenshot from 2017-03-13 00 11 54](https://cloud.githubusercontent.com/assets/17119462/23834763/c4c6a44a-0781-11e7-96f0-d4aa5c74d337.png)

**Comment by poush** [comment]
No you are looking into organiser section but the issue is from public schedule. When you export the png using that download button, the exported image as you can see above has transparent background for button above schedule.

**Comment by Himanshi-Khandelwal** [comment]
@poush can you please exactly tell me where is that , when I am trying to download it is giving some internal error

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal you're looking at the wrong place. This is inside Scheduler.

**Comment by Himanshi-Khandelwal** [comment]
@poush right? 
![timeline](https://cloud.githubusercontent.com/assets/17119462/23943013/1c9ee470-0994-11e7-87be-7a11399698c3.png)

**Comment by SaptakS** [comment]
@niranjan94 please create a corresponding issue in frontend repo in case the issue still exists. Closing here
