### ISSUE TITLE
Public Calendar Schedule: Add line break if room name is longer than cell

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3383]
On the table of the schedule, if the room name is longer than the width of the cell, parts of the name are hidden or overlapping. Please ensure there are automatic line breaks in this case, e.g. here: https://eventyay.com/e/45da88b7/schedule/

![screenshot from 2017-03-13 11-03-11](https://cloud.githubusercontent.com/assets/1583873/23840060/23ed3244-07dd-11e7-81c5-c9d66b4b8f79.png)

**Comment by cepradeep** [comment]
Some padding on the sides would be nice too. The following is hard to read:

![screenshot from 2017-03-13 16-15-10](https://cloud.githubusercontent.com/assets/6213734/23850782/e23953f8-0806-11e7-8e49-fb9321c172f1.png)

**Comment by RajuKoushik** [comment]
Can I work on this ?

**Comment by mariobehling** [comment]
Please go ahead.
