### ISSUE TITLE
User cannot change email address without adding mobile phone number

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3386]
User cannot change email address without adding mobile phone number. It should be possible to simply change the email address.

![screenshot from 2017-03-14 11-05-02](https://cloud.githubusercontent.com/assets/1583873/23884216/6b7ecb80-08a6-11e7-907b-b76c34b8557d.png)

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling  this means I need to remove the compulsion of adding the mobile number . Is that what you mean?

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling This issue is solved.
