### ISSUE TITLE
Speaker editing form uses large image files for "second" speaker

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3391]
If the organizer or speaker edits the session form, there is the option of choosing additionals speakers. This form shows a list of registered speakers and there profile picture - in a large image file even though the area is very small. Please use a thumbnail image in that area.

![screenshot from 2017-03-15 00-12-08](https://cloud.githubusercontent.com/assets/1583873/23910269/0d309fea-0914-11e7-864a-312b43609023.png)

**Comment by LuD1161** [comment]
@mariobehling 
I am working on this

**Comment by LuD1161** [comment]
Done .
The new image is shown on the left side.
![image](https://cloud.githubusercontent.com/assets/17861054/23988511/867e38d0-0a54-11e7-8add-ff89a51f7bec.png)
