### ISSUE TITLE
Resending ticket confirmation as an organizer shows "ticket bought in notifications"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3393]
Resending a notification for a ticket order results in notifications "Ticket bought by -organizer email-"

There should not be a ticket notification, because no new ticket was bought.

![screenshot from 2017-03-15 11-19-58](https://cloud.githubusercontent.com/assets/1583873/23932210/a17be7a6-0971-11e7-8840-94ccc112ba26.png)

**Comment by LuD1161** [comment]
@mariobehling 
I am working on this
