### ISSUE TITLE
option to select event should come before adding sessions, tracks, micrlocations

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#34]
when we go to http://open-event.herokuapp.com/admin/session/ we should have to select which event we want to add session to first, then add details of the session, 

right now the event selector is at the bottom.

or maybe on that page http://open-event.herokuapp.com/admin/session/ we can show a list of events, and organiser selects event, then goes to page http://open-event.herokuapp.com/admin/session/<eventid> where he gets table of sessions specific to that event.

**Comment by rafalkowalski** [comment]
@championswimmer @mananwason we could apply switching between events as it is at Frab. 
http://frab-test.herokuapp.com/en/conferences/new
In the  top right corner you could switch conference.Therefore if you want add session, it will be added to current event. What do you think about it?

**Comment by mariobehling** [comment]
Sounds good to me.

**Comment by championswimmer** [comment]
Sounds perfect to me as well. makes sense :)

**Comment by mananwason** [comment]
Sounds nice. So, there will be no event column now in the sessions or somewhere else right?

**Comment by championswimmer** [comment]
What about speakers then ? 
A speaker might speak at multiple events, and multiple sessions at one event. 

Right now only one event is attached to a speaker. 

How can we work this out ?

**Comment by championswimmer** [comment]
In the sessions field of speakers maybe we use this format : [eventid]/[sessionid] or eventid_sessionid

like "sessions": [ "1/2", 1/4", "3/9"]

for a speaker who is conducting session 2 and 4 at event 1, and session 9 at event 3

**Comment by mananwason** [comment]
So sessions are being managed in the current version itself and it would be nice to keep speakers separate for different events.

**Comment by mananwason** [comment]
No please keep it separate for different events. We need to keep the data download as minimum as possible and getting speaker info for a different event is useless

**Comment by rafalkowalski** [comment]
@mananwason @championswimmer @mariobehling 
Summary:
1. Prepare view where we could switching between events
Main menu:    
   - Switch event
       Sub menu:
       - Event 1
       - Event 2
       - Create Event 

![zrzut ekranu 2015-06-06 o 10 34 45](https://cloud.githubusercontent.com/assets/2479753/8018978/b47e2384-0c37-11e5-9c3c-c35d23ba9c4f.png)

2. Speakers should belongs to few Events
3. Change Urls format to  [ "1/2", "1/4", "3/9"] => [eventid]/[sessionid]

**Comment by mananwason** [comment]
@rafalkowalski Instead of this what about if you display events after the login page where user can select the event that concerns him and then go to the page where he can add speakers, sponsors etc.
We should keep the data as less as possible, while seeing that we don't miss anything crucial as well.

**Comment by rafalkowalski** [comment]
@mananwason @mariobehling I think my option will be more useful, because i don't need create new view. Additionally i would like to inform user about current event. In frab after login page shows form where you could create event.

**Comment by mananwason** [comment]
I just thought that what I suggested would be a little less cumbersome, making it easier to select events for the user. Let's take everyone's take on it. @mariobehling @leto @creativepsyco @championswimmer

**Comment by rafalkowalski** [comment]
OK @mananwason

**Comment by championswimmer** [comment]
I like this method https://github.com/fossasia/open-event-orga-server/issues/34#issuecomment-109553088

**Comment by championswimmer** [comment]
in the JSON API, can you make it that when I GET on /event/2/speakers I get only speakers who have sessions in event 2, and not get any speakers who are in other events ?

**Comment by rafalkowalski** [comment]
https://github.com/fossasia/open-event-orga-server/issues/37
