### ISSUE TITLE
Start Page/Event Page Placeholder Images missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3412]
At Open Event we had defined start page and event page images as placeholders in case the user does not upload an image. At the moment no placeholder images show up.

Expected: Topic suitable but neutral placeholder images show up.

![screenshot from 2017-03-20 10-03-10](https://cloud.githubusercontent.com/assets/1583873/24087061/ad37a42c-0d54-11e7-93c1-1f413197c2d6.png)

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling  this happens when event type is not chosen and hence event sub-topic and all .So, is that so , we have to put an image by itself (means 1 image is fixed for all types of events if user has not uploaded the image)

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal yes. Please have a default placeholder image.

**Comment by Himanshi-Khandelwal** [comment]
I would like to work on this.

**Comment by mariobehling** [comment]
The feature to show placeholder images is already implemented and you should check the admin UI as well.

**Comment by Himanshi-Khandelwal** [comment]
solved!!!!

**Comment by Himanshi-Khandelwal** [comment]
But , I solved this....and was about to make PR.

**Comment by SaptakS** [comment]
Solved in #3432
