### ISSUE TITLE
documentation: Broken Command for local installation of the server dependencies

### ISSUE THREAD

**Issue by virresh** [fossasia/open-event-orga-server#3413]
In the instructions for installation of the App locally, there's the command 
```
sudo apt-git install redis-server
```
under step 7.

It should use 

```
sudo apt-get install redis-server
```

The documentation file is here :
https://github.com/fossasia/open-event-orga-server/blob/development/docs/installation/local.md

**Comment by niranjan94** [comment]
@virresh thanks. please make a PR with the fix and reference to this issue.

**Comment by virresh** [comment]
@niranjan94, made the PR. I don't know what to do next. Also please review.
Thanks :-)
