### ISSUE TITLE
Exported csv of Attendees - name of file not suitable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3417]
The exported csv file of attendees has a name that is not suitable: e.g. Attendees-FOSSASIA Summit_06-Dec-2016_09_40_01.csv Please export the file using the event name only.

**Comment by geekyd** [comment]
@mariobehling I will fix this :)

**Comment by geekyd** [comment]
@mariobehling @SaptakS @niranjan94 The name of pdf file also seems to be with the name convention like Attendees-FOSSASIA Summit_06-Dec-2016_09_40_01.pdf should I change it too?

**Comment by SaptakS** [comment]
Yes

**Comment by geekyd** [comment]
@SaptakS please close this. sorry about the trouble I forgot to give a reference of PR in the description. Thanks
