### ISSUE TITLE
Cannot submit session (server error) and no option to submit speaker details for OpenTechSummit

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3427]
The call for speakers of the OpenTechSummit does not allow the submission of speaker details and submission of sessions results in error message.

![screenshot from 2017-03-24 18-27-05](https://cloud.githubusercontent.com/assets/1583873/24314351/e2f48c88-10bf-11e7-863a-edb10b75eeac.png)

**Comment by mariobehling** [comment]
![screenshot from 2017-03-25 07-35-20](https://cloud.githubusercontent.com/assets/1583873/24321551/b4aa12bc-112d-11e7-99b4-139ee67cbb0f.png)

Issue still persists. I neither get the option - the button for adding speaker details.

**Comment by mariobehling** [comment]
After this merge the session proposal form includes the speaker submission form. We had changed this before. The goal is that one speaker can submit several sessions and does not have to fill out speakers info several times - but only one time.

**Comment by SaptakS** [comment]
The session proposal form in case the speaker is not registered always included the speaker submission form and has nothing to do with this merge. What we made before was if the user is registered as a speaker then the speaker and session forms were separate. The speaker doesn't have to fill out the speakers info several times even now. Only once per event. I will implement that the user has to register only once and not for all events.

**Comment by mariobehling** [comment]
@SaptakS Please follow the implementation of frab (and other systems) and keep this separate. Only show a "Submit" button after the speaker form has been submitted. Before that show "save as draft".

**Comment by magdalenesuo** [comment]
@mariobehling  How about adding a "Edit Speaker details" button? After the speaker registers? Along side the "Add Session Proposal" button. Because the guests cannot recheck their submitted details. @SaptakS  comment

**Comment by SaptakS** [comment]
@magdalenesuo makes sense. I will put an edit button in both the mysession page and also in cfs so as to give a better U/X and maintain the same logic in both pages.

**Comment by SaptakS** [comment]
@magdalenesuo please make an issue and assign it to me. Thanks.
