### ISSUE TITLE
"Unscheduled Sessions" tab in mysessions page

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3430]
The unscheduled session either appear on the upcoming sessions or past sessions based on the starting date of the event which is wrong. Please make a separate "Unscheduled Sessions" tab for showing all unscheduled sessions.

**Comment by mariobehling** [comment]
There is no need for that. The tabs depend on the event dates. Let's focus on the bugs and follow up on more features later.
