### ISSUE TITLE
Cannot access events on heruku build

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-orga-server#3458]
Currently if the user creates a new event or tries to manage the created events leads to  internal error page instead of opening admin panel.

**Reproducing the case**

- Create a new event and publish it

OR

- Click on manage events.

- Click on the name of the event.

**Screenshot**
![screen shot 2017-04-07 at 12 11 31 am](https://cloud.githubusercontent.com/assets/12807846/24770222/cefa6e16-1b26-11e7-92ac-4d0528c8a59c.png)

**Comment by mariobehling** [comment]
Working for me. Please re-open if problem reoccurs.
