### ISSUE TITLE
Ensure that the API follows JSON-API schema

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3459]
Parent issue: #3457

Currently, the API doesn't follow any standard schema. Ensure it follows the [json-api](http://jsonapi.org) schema

Any of the following libraries can be used: 
http://jsonapi.org/implementations/#server-libraries-python

**Comment by shubham-padia** [comment]
@niranjan94 Since we're using `flask-restplus` which is using swagger docs. I think it is compliant with the [OpenApi](http://swagger.io/specification/) specification (previously known as swagger specification). `flask-restplus` is also listed on http://swagger.io/open-source-integrations/ .

**Comment by niranjan94** [comment]
@shubham-padia swagger spec is a spec for describing an API and its documentation. Wheras JSON-API spec is a specification for all the response objects, relationships, paths and is widely compatible with a lot of clients.

**Comment by enigmaeth** [comment]
How do I get started with this?  
I read the docs at http://jsonapi.org/format/ and took an overview of Flask-REST-JSONAPI from the list of the libraries above.

**Comment by niranjan94** [comment]
@enigmaeth  Since this is gonna be a major change to the current API, the first step would be to propose how you're planning to implement it, here ... So, that all can know what is happening and can suggest improvements

**Comment by niranjan94** [comment]
@shubham-padia @SaptakS @enigmaeth @poush @LuD1161 @magdalenesuo 

Please research and this and give in your ideas here.

**Comment by shubham-padia** [comment]
[flask-rest-jsonapi](https://github.com/miLibris/flask-rest-jsonapi) seems like the best choice out of the given libraries and has better out of the box support for json-api. Also according to some [testaments](https://twitter.com/bonsaistudio/status/863358681462837248), it perfectly couples with emberjs.

**Comment by niranjan94** [comment]
@shubham-padia that looks like a great library ! 😄 

These are the primary things that we require:
- Proper relationship definitions
- Sorting
- Filtering
- Pagination

Looks like Flask-REST-JSONAPI has all of them. Let's keep this mind. We'll see what the rest of them come up.

**Comment by shubham-padia** [comment]
@niranjan94 I'm having second thoughts about the library. I missed out `Flask-restless` as it wasn't listed in the implementations link, but it also supports jsonapi spec. Flask-restless has a detailed documentation and has been widely used. Can you have a look at it and provide some feedback from it.
https://github.com/jfinkels/flask-restless 
https://flask-restless.readthedocs.org/

**Comment by niranjan94** [comment]
How well does it support relationship definitions as per json api
specifications?

**Comment by niranjan94** [comment]
I don't seem to be able to find anything about relationships in the docs. Also, is there sorting support out of the box?

**Comment by shubham-padia** [comment]
> I don't seem to be able to find anything about relationships in the docs

Yes. Seems so, lets leave it then.

**Comment by niranjan94** [comment]
@shubham-padia cool. The please proceed with Flask-REST-JSONAPI
