### ISSUE TITLE
Add endpoint to get event summary

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3461]
Parent issue #3459
To be done after #3645

We need a way to get summary of an event. Which includes but not limited to the following:
- Tickets sold and total (grouped by ticket type)
- Number of sessions
- Number of attendees
- Proposal count (grouped by status)

**Comment by LuD1161** [comment]
@niranjan94 
What all do I need to look at which involves solving this ?
where should I start ?

**Comment by niranjan94** [comment]
@LuD1161 please wait on all API related issues until the introductory session this weekend get's over. There's a lot of planning required on this front.

In the mean time, there are over 70 _other_ issues/bugs that can be solved. Please work on one of them for now.

**Comment by LuD1161** [comment]
@niranjan94 
Ok :+1: 
Thanks

**Comment by LuD1161** [comment]
@niranjan94 
Should I proceed with this ?

**Comment by SaptakS** [comment]
@shubham-padia @niranjan94 I think analytics endpoint mostly does this? Can you confirm and close?

**Comment by shubham-padia** [comment]
Yep
