### ISSUE TITLE
Implement Sales API

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3463]
Parent issue #3459
To be done after #3645

We don't have a way to get the current stats of the ticket sales via the API. Everything that is available in the frontend will need to be accessible via an API which includes but not limited to 
- Filtering based on status (#2981)
- Based on tickets (#2981)

**Comment by SaptakS** [comment]
This has been implemented here: https://github.com/fossasia/open-event-orga-server/pull/4297
