### ISSUE TITLE
Implement Notifications API

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3466]
Parent issue #3459
To be done after #3645

Implement notifications API to do the following
- Send system-wide notification
- Get current notifications of a user
- Mark notification as read (or mark all as read)
- Send emails to a user/email ID (custom payload support and existing template support)
- Trigger push-notification on client apps (android, webapp, organizer app)
- Update/view user notification preferences (more info #3062)

This is a parent issue. Sub-issues can be created.

**Comment by enigmaeth** [comment]
@niranjan94  Should I proceed with this? What will be the required endpoints?

**Comment by niranjan94** [comment]
@enigmaeth like I said the base of the API structure is still being added. (#3683, #3687, #3679, #3641, #3686) and there are important discussion regarding that going on too (Like #3686, #3641). 

But you don't seem to be part of any of those discussions. We should be working as a team. Not solving individual issues in an isolated manner. Please provide your inputs too at #3641 and also try to help with other issues present. 

I will be creating and assigning issues for everyone shortly regarding APIs.

And there is also a wiki page that @shubham-padia created about the API here -> https://github.com/fossasia/open-event-orga-server/wiki/Getting-started-with-flask-rest-jsonapi . I hope you have gone through it.

**Comment by enigmaeth** [comment]
I have already gone through all the PRs you have mentioned and the wiki doc. I looked at the code that has been written for the user login( api/users.py changed according to the new API specs format). My question here was to discuss what all endpoints we will have here, just as you have mentioned in this [comment](https://github.com/fossasia/open-event-orga-server/issues/3670#issuecomment-304208681). This issue also says that child issues have to be created.

That you will create and assign issues answers my question. Thanks.
(Please don't think that I am not following up anyhow with the team.)

**Comment by niranjan94** [comment]
To start with, the notifications API will have the following basic CRUD endpoints
- `GET /v1/notifications` - Get all notification
- `POST /v1/notifications` - Create a notification. (email(s) would be triggered. This would also trigger push notifications if and when necessary in the mobile apps)
- `GET /v1/notifications/<notification_id>` - Get a single notification
- `PATCH /v1/notifications/<notification_id>` - Update a single notification (though I don't see a practical use for this, we'll have it) 
- `DELETE /v1/notifications/<notification_id>` - Delete a single notification

**Comment by enigmaeth** [comment]
Basic Notification API completed in #3704.

**Comment by SaptakS** [comment]
Closing since the basic implementation is done.
