### ISSUE TITLE
Implement elasticsearch for Indexing and search of events

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3467]
Implement [elasticsearch](https://github.com/elastic/elasticsearch) so that we can index and search large number of events easily and efficiently. 

Required:
- Adding of event to the elasticsearch index on creation
- Updating of event in the elasticsearch index on edit
- Deleting of event from elasticsearch index when the event is deleted
- Search API to search using elasticsearch
- Experiment on the fuzziness value and choose appropriately. 

This is a parent issue. Sub-issues can be created.

**Comment by aviaryan** [comment]
Some questions:

* Who will use the ElasticSearch server ? The API server or the client apps.
* What is the advantage of using ElasticSearch when we can already use our backend server to do these tasks? I know it will be more fast but is that it.

**Comment by niranjan94** [comment]
- The API server will use the elasticsearch. (for example, if we use the open event api to search for event, the api server will communicate with elastic search and get the data)
- Speed is what we need at this point. Especially when we have thousands or more events. And also, this would allow us to use Kibana or some tool like that in future to make sense of our search index and data for providing better results to the user. Why re-invent the wheel and implement an in-house system when we already have a proven system ?

**Comment by niranjan94** [comment]
Also, when eventyay starts getting as many events as eventbrite or something, we can easily scale the platform up by creating multiple shards of elasticsearch and provide quick results to the users irrespective of the number of events or the number of users we have.
