### ISSUE TITLE
My Sessions Page: Do not show "Withdraw Proposal" once event is over

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3471]
Speaker should not be able to withdraw a proposal once the event is over.

![screenshot from 2017-04-08 15-15-08](https://cloud.githubusercontent.com/assets/1583873/24829215/56d2d238-1c44-11e7-9c73-d3475ec7d584.png)

**Comment by Himanshi-Khandelwal** [comment]
I will like to work on this.

**Comment by niranjan94** [comment]
@Himanshi-Khandelwal please proceed
