### ISSUE TITLE
Upload Background Image and logo

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#348]
Do we need to upload a background image and logo or link from another service will be enough?

@juslee @aditya1702 @aviaryan

**Comment by aviaryan** [comment]
I'll go with **links from other services** as storing data on our server can be tricky. We may need to use external AWS space or Digital Ocean for the same.
One thing I would like to suggest is to give a link in those type of forms to image hosting services like Imgur or [PostImage](http://postimage.org/). This will make things convenient for many people.

**Comment by aditya1702** [comment]
@rafalkowalski I too think links will be better. Earlier we had tried out storing the images in a folder via an 'Upload' button but it wasnt getting stored on the Heroku server. If the storage can be done easily then we can go for upload otherwise link is better.

**Comment by rafalkowalski** [comment]
Thanks guys :) @mariobehling what do you think?
