### ISSUE TITLE
Link for Video/Slides/Audio missing - Implement option a) Upload or b) Link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3492]
Currently the link for video, slides, audio cannot be provided as only an upload option is available in the sessions form. 

Please provide an option either link or upload.

![screenshot from 2017-04-14 14-05-25](https://cloud.githubusercontent.com/assets/1583873/25042857/b2d80162-211b-11e7-9032-376a505150c0.png)

**Comment by poush** [comment]
I'm Working on it.

**Comment by poush** [comment]
@mariobehling @niranjan94 @SaptakS Can you assign me to this issue ( Since it is required as mentioned in Guidelines )
