### ISSUE TITLE
Switching buttons on and off results in data loss

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3495]
When an organizer switches key buttons on or off all data is gone. Expected: When the organizers switches the button on again, the data should be there again, e.g.
* Ticket module on wizard step 1
* Sponsors button wizard step 2
* Sessions and Speakers wizard step 3

Secondly, switching buttons on and off in step 3 results in "all sessions" that have been submitted being deleted. Expected: Sessions should still be there, but they cannot be in the specific tracks anymore. Actually the speaker submissions are still there, but the sessions are gone. Please ensure the sessions are staying in the system in any case.

![screenshot from 2017-04-14 18-05-06](https://cloud.githubusercontent.com/assets/1583873/25048709/144df7cc-213e-11e7-956e-2d65ca7e3395.png)

**Comment by shubham-padia** [comment]
@niranjan94 @SaptakS please assign this to me.
