### ISSUE TITLE
My Sessions: Show all session information on main page without subpages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3499]
The my sessions pages has sub pages of sessions at events. The additional "click" is not needed. Expected: We can show all relevant information on the my sessions page, e.g. at https://eventyay.com/events/mysessions/

Please create one section for each event and show the information for each sessions within the "event box" on the my sessions page instead of showing it on sub pages.

![screenshot from 2017-04-15 18-42-29](https://cloud.githubusercontent.com/assets/1583873/25065210/973baa62-220b-11e7-9d03-176443f877c4.png)
Integrate the info of single sessions in the "my sessions" page directly.

**Comment by Himanshi-Khandelwal** [comment]
is this what is required ?
![screenshot from 2017-04-16 16 16 30](https://cloud.githubusercontent.com/assets/17119462/25070590/576385d0-22c0-11e7-9a63-e19d52f3c269.png)

**Comment by mariobehling** [comment]
Please sort all sessions of one event below each other. So all sessions in a list instead of next to each other.

Only offer one "Edit Speaker Details" per event.

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling will "withdraw sessions" option won't be provided ?

**Comment by mariobehling** [comment]
> withdraw sessions" option won't be provided

yes

**Comment by Himanshi-Khandelwal** [comment]
file:///home/himanshi/Pictures/Screenshot%20from%202017-05-09%2015:46:44.png
is this ok?

**Comment by Himanshi-Khandelwal** [comment]
file:///home/himanshi/Pictures/Screenshot%20from%202017-05-09%2015:46:44.png
is this ok?

**Comment by Himanshi-Khandelwal** [comment]
is that what is required?
http://www.filetolink.com/afd42a52f5

**Comment by niranjan94** [comment]
`frontend` tag added. 
Issue will be re-created on the frontend repo.
