### ISSUE TITLE
Make background_image field in Event API nested

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#3518]
@niranjan94 said (https://github.com/fossasia/open-event-orga-server/pull/3514#issuecomment-295222321): 

While we are at it .. Can we put these fields `thumbnail`, `large` and `background_image` into a nested object ? 

Something like,
```json
{
    ... other event object keys ...

    "background_image": {
             "thumbnail_image_url": "url for that",
             "large_image_url": "url for that",
             "original_image_url": "url for that"
    }
}
```
If there is no background image available `background_image` will be `null`

**Comment by poush** [comment]
I'm working on it.

**Comment by niranjan94** [comment]
@poush any progress on this ? Assigning this to milestone 2

**Comment by poush** [comment]
@niranjan94 Just one concern, as mentioned by @SaptakS in its PR, Is it a good idea to work on it when we are going to create new API format from scratch?

**Comment by niranjan94** [comment]
Yep. @poush . We'll do that.
