### ISSUE TITLE
Set up monitoring for eventyay deployment

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3524]
The site on Eventyay.com was offline today due to internal server error. Please propose and implement a solution for monitoring where a set of people get an email automatically when the site has issues.

**Comment by aviaryan** [comment]
We can use a known free service such as [Uptime Robot](https://uptimerobot.com) for this. 
It checks the website every 5 minutes and notifies the concerned if there is a problem. The notification medium can be anything from SMS, Email, Twitter, Slack or a webhook.

**Comment by geekyd** [comment]
We can have a project to monitoring all the applications including open-event(eventyay) of the organisation, it will report us whenever any website is having issues. Building the monitoring system might take time, so we can use free services till we build it. I would love to hear your opinion. Thanks

**Comment by poush** [comment]
There are many ways to implement this. One option could be to add the script in orga server which will be called by our Scheduler every minute or 5. If the main website is not resolving it will send a mail to provided mail IDs or to the admin email ID in orga server. This is easy to implement since we will be directly using the email service of orga server and all other people using orga server project can make use of it.

**Comment by niranjan94** [comment]
One long-term solution would be to use something like [Prometheus](https://prometheus.io/). Which could be running on an isolated pod monitoring every other pod/service in the cluster.

The advantages of Prometheus include but not limited to:
- Supports Kubernetes ( ❤️ )
- Open Sourced ! (Yayy 🎉 )
- Has loads of ways to alert people (including good old email)
- Many big players including DigitalOcean, docker, soundcloud use it. So, it's not a new kid either.

**Comment by hongquan** [comment]
We should have a bug collecting system, like [Sentry](https://github.com/getsentry/sentry). It will collect debug information at the time the error occurred, for us to have idea what is wrong.

Example from one of the projects I took part in:

![selection_157](https://cloud.githubusercontent.com/assets/314607/26447801/75a3efe4-4174-11e7-9996-a88d9d94d1f0.png)

**Comment by niranjan94** [comment]
Nice one @hongquan . We could maybe use the self-hosted version of sentry (Using [Sentry On-Premise](https://github.com/getsentry/onpremise) _which I assume is free ?_) and use it for all our apps.

**Comment by hongquan** [comment]
Yes. We seems to already have enough infrastructure from Google Cloud, let's take advantage of it.

**Comment by shubham-padia** [comment]
@niranjan94 Helm charts for sentry are also available on https://kubeapps.com/charts/stable/sentry. Would that help a bit. Or should we go with `Sentry On-Premise`
P.S I've tested the free tier sentry.io on my local instance and it works like a charm :)

**Comment by niranjan94** [comment]
There are a limits in the free tier. Especially the one user limit is problematic for us. On premise setup would give us more freedom. I'll open issues for sentry integration into the server in the next milestone. (will add Kubernetes config for it before that)

**Comment by shubham-padia** [comment]
> There are a limits in the free tier. Especially the one user limit is problematic for us

Yeah, knew that, just mentioned that sentry works fine :) 

> Helm charts for sentry are also available on https://kubeapps.com/charts/stable/sentry

Also can you have a look at this once please :smile:, from what I understand it will ease the setup on kubernetes

**Comment by niranjan94** [comment]
We now have a sentry instance for monitoring and error reporting across all eventyay apps. For cluster monitoring, stackdriver is being used.
