### ISSUE TITLE
Ticket options are not shown on event page if sale start date is today

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-server#3526]
Ticketing option is not shown on the event page if the sales start date of the ticket is today.

Expected: Ticket option should be shown on the event page if the sale start time is before now.

**Comment by SaptakS** [comment]
@mejariamol would you like to work on this issue?

**Comment by mejariamol** [comment]
@SaptakS yes, I will work on this.

**Comment by mejariamol** [comment]
@niranjan94 @SaptakS which time zone will server use to check sale start time ??

**Comment by niranjan94** [comment]
Internally ... We use UTC ... But we should take into consideration the event's timezone while calculating ticket sales start and end

**Comment by mejariamol** [comment]
Can't we switch now to **unix time** while storing date time to server.. and converting it to local while showing..?? that will be easier right..?

**Comment by mejariamol** [comment]
never mind.. we can do the same with UTC  :)

**Comment by mejariamol** [comment]
@SaptakS @niranjan94 It is working correctly according to UTC.. I was putting local time for ticket sale start.. that was making issue..
But I think we should take input time from user in local time zone.. and convert it to UTC internally.. That will avoid such issues in the future.. what do you think??

**Comment by mejariamol** [comment]
@niranjan94 It is working correctly for date time input in UTC..
Just wanna be clear about these things..

1. Are we taking date time input from user in UTC or in selected local time zone?

2. And in which form we are storing date time on database ,, UTC or local time zone??

**Comment by niranjan94** [comment]
1. The user picks a date and time and selects the timezone it is in.
2. It is stored in the database as a _naive datetime_ and the timezone is stored in a separate field. 

> A naive datetime is a datetime that doesn't know its own timezone. It could be in UTC, it could be in US/Eastern, but it doesn't know. All it knows is which date and time that it has.

**Comment by shubham-padia** [comment]
@mejariamol Can you please provide steps to recreate this issue, i.e the example data that you filled. I set my timezone to US, and added a ticket which had its start time automatically set according to US. And I was able to access the tickets immediately.

**Comment by mejariamol** [comment]
@shubham-padia 

1. choose timezone which is +HHMM to your local timezone .. for example if you are in Asia/Kolkata time zone which is UTC+0530  then choose Pacific/Nauru which is UTC+1200.. 

2. now select sale start time one hour prior to current time in the chosen timezone i.e., UTC+1200..
