### ISSUE TITLE
Remove eventlet dependency

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3528]
We are using eventlet only in notifications to make it real time which isn't essential right now. Eventlet breaks the docker integration and hence the kubernetes deployment. https://github.com/eventlet/eventlet/issues/401.

Since it is not essential to our system, we can remove the dependency on eventlet. Otherwise this breaks the eventyay deployment.

**Comment by niranjan94** [comment]
We can re-implement web-sockets later when we have more use for them.

**Comment by temoto** [comment]
Please try new eventlet version. Hopefully it fixes this problem

`pip install https://github.com/eventlet/eventlet/archive/b756447bab51046dfc6f1e0e299cc997ab343701.zip`

**Comment by SaptakS** [comment]
Thanks @temoto for the fix. We have changed the architecture of the project some what so I am not sure we will be needing eventlet anymore but will surely check out. 🍪
