### ISSUE TITLE
Missing migration for removing `creator_id` field

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3532]

**Comment by SaptakS** [comment]
Can you please elaborate this issue? I am not sure what you mean by this. Is this `creator_id` something that should be removed? But according to your comment [here](https://github.com/fossasia/open-event-orga-server/pull/3527#discussion_r112831396), you are saying this column doesn't exist at the moment.

**Comment by shubham-padia** [comment]
@SaptakS According to @aviaryan 's comment here: https://github.com/fossasia/open-event-orga-server/pull/3527#discussion_r112831502 , the `creator_id` field was removed from the model but no migration file was generated for it.

**Comment by shubham-padia** [comment]
@SaptakS Yep.
