### ISSUE TITLE
Create a real world sample of a past event including sponsors, tracks, call for papers, speakers and sessions etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3544]
Please test the system and its flow and create a sample event using a real world event e.g. a past FOSDEM event, Linux conference etc. on eventyay and post the link to the public event here.

Please ensure you are using all features of the event. The event sample should be as complete as possible. Create a real world sample event that includes:
* organizers info
* social media
* code of conduct
* sponsors
* tracks
* call for papers
* speakers with images
* sessions
* create the real schedule of the event

@shreyasnbhat @rohanagarwal94 @Shailesh351 @arpitdec5 @mahikaw @geekyd @harshitagupta30 @anu-007 @sumedh123 @CosmicCoder96 @utkarshnath @Ronak-59 @mejariamol @iamareebjamal @LuD1161 @magdalenesuo @poush @enigmaeth @shubham-padia @Princu7 @SaptakS

**Comment by enigmaeth** [comment]
I have created an event [here](https://eventyay.com/e/9bad906e/). Please comment your email so that I can add you as co-organiser. 

I published the schedule but the schedule page shows a 404 error. I can share the raw schedule in an excel sheet.

**Comment by mariobehling** [comment]
@enigmaeth 

> I published the schedule but the schedule page shows a 404 error. I can share the raw schedule in an excel sheet.

Please submit an issue. The goal of this issue is that you find bugs. 

Did you understand the other goals of this issue

> sample event using a real world event

We want some sample events here with lots of data, e.g. tons of speakers to see if things work. It seems like you created a fake event, that does not help in that goal.

**Comment by enigmaeth** [comment]
@mariobehling 
> We want some sample events here with lots of data, e.g. tons of speakers to see if things work. It seems like you created a fake event, that does not help in that goal.

The event I am creating is based on a fest that happened recently. There were many tracks and sessions and speakers, so that event serves the purpose of testing( it is incomplete on eventyay as of now though) .
By real world event do you mean that I should create something like an actual upcoming event?
