### ISSUE TITLE
Public Schedule: Scroll fix of the sidebar

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3546]
The sidebar position and top values get updated weirdly. You can check it out here: https://eventyay.com/e/45da88b7/schedule/

**Comment by poush** [comment]
Looks like it is working till certain height. I tried testing it on small height than full screen and it worked well but at full screen issue start showing on.

**Comment by SaptakS** [comment]
@poush yes. You are right. Are you working on this issue?
