### ISSUE TITLE
Make API requests and responses timezone aware

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3549]
For example, the call for speakers response right now is 
```
{
      "announcement": "",
      "privacy": "public",
      "start_date": "2017-03-31T16:00:00",
      "end_date": "2017-03-31T17:00:00",
      "timezone": "Europe/Rome"
}
```

Instead, ensure the timezone is part of the start_date and end_date. Ensure [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format is followed. (Eg. `2017-04-27T00:27:49+00:00`) 

Ensure this is done for all date time responses throughout the app.

---

Same to be followed while making requests. For example, right now, for filtering events by date `end_time_gt` and `end_time_lt` params accept date in the format `2017-04-27T00:27:49` without any timezone information. Make it such that, the request should also follow the [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) spec. (Eg. `2017-04-27T00:27:49+00:00`)

Sub-issues can be created if necessary.

**Comment by mejariamol** [comment]
@niranjan94 I will work on this.

**Comment by niranjan94** [comment]
@mejariamol sure. Proceed

**Comment by mejariamol** [comment]
@niranjan94 Without making any changes in the database fields. right?

**Comment by poush** [comment]
@mejariamol If I'm right database is already using timestamp data type which by default stores the time zone as well

**Comment by niranjan94** [comment]
@poush not exactly. We store timezone as a separate field in the database.
Any timezone information that is part of the date is discarded and the date
time stored in the db is considered to be timezone-naive
