### ISSUE TITLE
GET APIs with flask-restplus | Create APIs 

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#355]
Cover all point discussed at https://github.com/fossasia/open-event-orga-server/issues/336

Create a separate app. Register as a separate Blueprint (api_v2 for now).

Create APIs for all the services:

- Sessions
- Events
- Sponsors
- Tracks
- Speakers
- Microlocations
- Levels
- Languages
- Formats

Create all of these as separate namespaces in separate files, and add all of them in `api` in `__init__.py`.

Exclude complex list and nested fields in the API models (e.g. `speakers` field in sessions) (for now).

Create API helper functions like:

- `get_object_list`
- `get_object_or_404`
- `get_list_or_404`

that make retrieval of Model objects from queryset easy (and raise http exceptions where necessary).

**Comment by championswimmer** [comment]
Let's create a standalone API-viewer repository ? I used swagger-ui and made this https://github.com/championswimmer/openevent-api (which is live on http://championswimmer.in/openevent-api)

**Comment by shivamMg** [comment]
@championswimmer We might not need it. flask-restplus automatically documents the APIs corresponding to the API models https://flask-restplus.readthedocs.io/en/stable/swagger.html

I've created the GET APIs at [add/restplus-get-api](https://github.com/shivamMg/open-event-orga-server/tree/add/restplus-get-api) branch in my repo. If you want to clone, you can get the Swagger docs at http://127.0.0.1:8001/api/v2/ and the Swagger config at http://127.0.0.1:8001/api/v2/swagger.json. I'll write tests, document work and push soon.

Weird, right? The entire point of Swagger is to document spec before writing actual code, and with restplus we are doing it after we write code. Spec we are following: https://github.com/fossasia/open-event-orga-server/issues/336

**Comment by juslee** [comment]
Nope. Swagger is meant to be generating the doc spec after you write code. It seems to be the preferred way now in the dev world. Code is the source of truth. @shivamMg
