### ISSUE TITLE
Events without CfS show up in Call for Speakers area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3551]
Recent changes broke the display of events on the front page. Events without CfS now show up in Call for Speakers area on front page. 

![screenshot from 2017-04-28 10-17-47](https://cloud.githubusercontent.com/assets/1583873/25520427/1ee8d7ba-2bfc-11e7-9e86-ddc66e30b92b.png)

**Comment by niranjan94** [comment]
Already resolved by #3547
