### ISSUE TITLE
Editing social links results in errors or does not save data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3552]
Trying https://eventyay.com/admin/content/#!social-links results in bad gateway error.

![screenshot from 2017-04-28 10-53-28](https://cloud.githubusercontent.com/assets/1583873/25521726/09845408-2c01-11e7-993f-1a273cdecdab.png)

**Comment by niranjan94** [comment]
@mariobehling works for me. Could you confirm?

**Comment by mariobehling** [comment]
Ok, does not result in bad gateway, but now it does not save any changes, e.g. adding https://www.facebook.com/eventyay/

**Comment by niranjan94** [comment]
@mariobehling I just added facebook.

**Comment by mariobehling** [comment]
What is the issue? Why is it working with you?

**Comment by niranjan94** [comment]
@mariobehling I used the superadmin account. Which account had you used ?

**Comment by mariobehling** [comment]
Same. I tried again adding Youtube and was logged out twice now.

Third time worked. I am puzzled.

**Comment by niranjan94** [comment]
Hmm ... weird. Then this is a bug and needs to be investigated.

**Comment by SaptakS** [comment]
@mariobehling @niranjan94  works for me as well. No error whatsoever. I checked the code as well. No error. Can you please confirm?
