### ISSUE TITLE
Wizard Step 3 - Session Colors: Show preview and automatically choose black or white font color

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3554]
Currently we only have standard font color white or black in the list and calendar views of the schedule.

The font color should be chosen automatically depending on the contrast. Please implement the following:
* behind each line implement a preview area with the background and automatically chosen font color a) black or b) white
* implement the font color in the schedule view
* add the font color choice to the API and JSON

![screenshot from 2017-04-28 11-19-12](https://cloud.githubusercontent.com/assets/1583873/25522800/884b8a6a-2c04-11e7-9acb-9e011fbd9f97.png)
Show a small preview on the right here.

There is a slack discussion on this feature here http://stackoverflow.com/questions/1855884/determine-font-color-based-on-background-color/1855903

**Comment by elioqoshi** [comment]
Thanks! This is very important I believe as it's a big accessibility issue right now.

**Comment by mejariamol** [comment]
I will work on this.

**Comment by niranjan94** [comment]
@mejariamol please proceed

**Comment by niranjan94** [comment]
@mariobehling I don't think the font color should be sent via the API. The track color is the primary data and that is all we should send. How that data is going to be used and how it is going to be displayed (I mean what font color to use, etc) should be decided by the respective frontends.

**Comment by mariobehling** [comment]
@niranjan94 The font-color depends on the background color. We don't want to re-implement the same functionality in each client. If we decide that the respective frontend does not need to follow that, it is ok. But right now we should not re-implement things several times and ask users to enter the same info again on the web app generator and android app generator. The idea is also to have a more consistent color usage across the apps. 

Again the font color needs to be set as it will not be visible if the contrast to the background color is not strong enough and we want the user to decide when he/she creates the event. We don't want the user to have to enter the same info over and over again and we are not ready to implement some kind of automatism in the app generators.

**Comment by mejariamol** [comment]
@niranjan94 @mariobehling See if this is fine.. I did front-end part only..

![screenshot from 2017-05-02 12-26-59](https://cloud.githubusercontent.com/assets/13533840/25607478/592e34ca-2f34-11e7-867e-09eb13d959e6.png)

**Comment by mariobehling** [comment]
Thanks. I assume the color wheel is not affected by the changes. Please samples to middle of row. Looking forward to the back-end implementation.
