### ISSUE TITLE
Propose and implement calendar view as full width in different resolutions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3555]
The calendar view is not full-width in all resolutions, which would be desired. The issue also happened in the open event web app. It was solved in two commits. Please compare:
* https://github.com/fossasia/open-event-webapp/pull/1246
* https://github.com/fossasia/open-event-webapp/pull/1257

![screenshot from 2017-05-01 17-08-01](https://cloud.githubusercontent.com/assets/1583873/25583225/3524e4c8-2e91-11e7-9ad9-6360ae6b04eb.png)

**Comment by geekyd** [comment]
@mariobehling I'm working on this issue

**Comment by SaptakS** [comment]
@niranjan94 I think this is an issue for frontend repo.

**Comment by niranjan94** [comment]
`frontend` tag added. 
Issue will be re-created on the frontend repo when appropriate.
