### ISSUE TITLE
Schedule: Show more info from inside of sessions box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3556]
When user clicks currently more info is shown below the session. It would be more suitable to show more info directly below the session text within the box of the session (similar to open event web app).

![screenshot from 2017-05-01 17-14-32](https://cloud.githubusercontent.com/assets/1583873/25583386/d72fd0e8-2e91-11e7-95ad-6c35fe2f756f.png)

**Comment by LuD1161** [comment]
@mariobehling 
Any suggestions as to how this can be done , any real life implementation you can suggest for me to look into ? ( although I am searching , this myself it would be easier if I get a suggestion straightaway cause I am not much into designing myself )

**Comment by LuD1161** [comment]
@mariobehling 
Can you suggest something or somewhere I can look at ( cause I'm not very good at designing issues but surely can learn from some examples , maybe even real life implementations can help ).
Thanks

**Comment by shubham-padia** [comment]
@LuD1161 as mentioned in the issue, the implementation had to be done similar to open event webapp. Have a look at this sample site https://fossasia.github.io/open-event-webapp/schedule.html for more info.

**Comment by SaptakS** [comment]
@niranjan94 I think this is an issue to be handled in the frontend repo. That is if it comes up there. What do you think?

**Comment by niranjan94** [comment]
`frontend` tag added.
Issue will be re-created on the fronted repo when appropriate.
