### ISSUE TITLE
Propose and implement solution for Full HD screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3557]
The images and views on the site are optimized for mobile and relatively small screen views. They do not look very well on full HD. Users are asking to increase the px per inch to 300dpi. This could increase the size of image and with many speakers it could increase the loading times for mobile users. What options do we have?

**Comment by niranjan94** [comment]
This discussion can continue on the `frontend` repo.
issue will be re-created.
