### ISSUE TITLE
Speakers: Name missing even though it is required

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3560]
The name is always a required field for speakers. Apparently it is marked as such but if the name is still missing the submission is still possible. Please ensure the name the named needs to be entered always also in Drafts.

![screenshot from 2017-05-03 11-27-30](https://cloud.githubusercontent.com/assets/1583873/25655024/b57a080c-2ff3-11e7-8cdd-61baebebd6f5.png)

**Comment by SaptakS** [comment]
@mariobehling this happens when someone submits a paper from CFS page. Since the speaker and session forms have been separated, so if the speaker is not registered and he saves a session as draft, then there is no speaker name associated with that session.

**Comment by mariobehling** [comment]
It looks like the process is not clear for speakers. We need to think about how to make this clearer. Speakers seems to think they already submitted.

**Comment by SaptakS** [comment]
@mariobehling So what if we make it necessary to register as a speaker before submitting a session to an event. I think that will make things clearer.

**Comment by mariobehling** [comment]
I want to look at how things are done with https://frab.cccv.de. Here it is very clear. What is the difference to us? Let's follow their approach more clearly.

**Comment by SaptakS** [comment]
@mariobehling atleast what I see they ask the user to register first and then allow session submission, one after the other. This is what I had proposed. But then we decided to keep the two things completely separate and not compulsory. If we don't make it compulsory for the speaker to register before submitting session, there is no way we can get speaker's information such as names.

If you want to keep the things separate and non compulsory like it is now, what we can do is in event dashboard we only show sessions that have speaker information associated with it.

@niranjan94 what do you think?

**Comment by niranjan94** [comment]
I think the first option is better. Speakers needs to create an account to submit a CFS Proposal. That makes sense. And I guess that is what frab is also doing.

**Comment by niranjan94** [comment]
@mariobehling this is Frab's implementation. We had a similar implementation in open event too at one point.

![screen shot 2017-05-03 at 4 13 22 pm](https://cloud.githubusercontent.com/assets/2404372/25657443/86cfda36-301b-11e7-8f26-4acd798dc2af.png)

**Comment by SaptakS** [comment]
@niranjan94 agreed... Infact the previous flow of eventyay was somewhat like this only. Just that the speaker and session forms were combined into a single one. I guess we should allow session submission only once speaker is registered for the event.

**Comment by mariobehling** [comment]
@SaptakS They differentiate between a) signing up and b) adding info for a session proposal (they call it event). So in our case, that would mean users have access to the system. Then if they want to apply for an event, they need to add their personal information first. If you mean that, sounds good.

As our system is also a ticketing system our sign up flow needs to be open for both and is slightly different to frab.

So how do we implement this? An idea:
1. People sign up.
2. People click "Submit Proposal"
3. They see the pop-up with the buttons "Add Speaker Details" and "Propose a Session"
4. Then "Propose a Session" is grayed out as long as the speaker has not filled in his/her details?

**Comment by SaptakS** [comment]
@mariobehling that is exactly what I was proposing.

**Comment by mariobehling** [comment]
Ok, sounds good. Maybe change "Register as a Speaker" to "Speaker Details".

By the way, existing sessions currently don't show up here. I am opening an issue.
