### ISSUE TITLE
Speakers: Implement "Export" speakers and sessions as csv for organizers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3561]
Organizers sometimes want to work on details and get a list of all emails of speakers. Please implement a button "export" speakers and sessions as csv
a) on the speakers tab
b) on the session tab
In both ares the buttons export the same document that should include all information of sessions and speakers as csv.

**Comment by LuD1161** [comment]
Will implement it tomorrow , similar to [this pull request ](https://github.com/fossasia/open-event-orga-server/pull/3390) of the issue #3246

**Comment by mariobehling** [comment]
@LuD1161 I am unassigning as there is no update on this. Would be great to get this feature actually.

**Comment by niranjan94** [comment]
@mariobehling actually ... there is progress. But looks like @LuD1161 hasn't linked the PR to this properly. I have linked now.

**Comment by niranjan94** [comment]
@LuD1161 please follow the best practices at http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ 

It is very important that you do.

**Comment by LuD1161** [comment]
@mariobehling @niranjan94 
Will follow best practices and make sure that it gets merged as soon as possible.
All the technical work has been done , will correct the squashing error today.
