### ISSUE TITLE
Event Proposal: Existing sessions not showing up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3562]
A session was added for a speaker by an organizer through the "Create Session" form. It does not show up as an existing session in the event proposal form linked from the Call for speakers.
![screenshot from 2017-05-03 12-48-27](https://cloud.githubusercontent.com/assets/1583873/25657827/08115ed8-3000-11e7-807b-daacc7d5ccae.png)

The session does show up on "My Sessions" and in sessions tab.
![screenshot from 2017-05-03 12-57-43](https://cloud.githubusercontent.com/assets/1583873/25657842/1ca0a73c-3000-11e7-964a-0d6d7aa9ee59.png)

Expected: Show existing session on the pop-up that appears from the call for speakers page.

**Comment by SaptakS** [comment]
I am looking into it...

**Comment by SaptakS** [comment]
@mariobehling I am unable to reproduce this issue. Works fine for me. Can you please tell me what exactly was done to reproduce this error?

**Comment by SaptakS** [comment]
These are the screenshots:

![screenshot from 2017-05-07 19-52-30](https://cloud.githubusercontent.com/assets/9530293/25781973/dd705d66-335e-11e7-812e-d0493f084515.png)
![screenshot from 2017-05-07 19-52-38](https://cloud.githubusercontent.com/assets/9530293/25781974/ddd373d8-335e-11e7-95fc-647fe6b98c9b.png)
