### ISSUE TITLE
Cannot sign in with Facebook Oath Error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3563]
Trying to sign up with Facebook not possible.

Getting "OAuth Authorization error. Please try again later."

![screenshot from 2017-05-03 13-06-24](https://cloud.githubusercontent.com/assets/1583873/25658150/b32eda38-3001-11e7-8755-4cb25f38ea92.png)

**Comment by Nitish18** [comment]
Hi,
can I work on this issue if no one is assigned this bug ??

**Comment by niranjan94** [comment]
@Nitish18 sure,

**Comment by niranjan94** [comment]
@Nitish18 any progress on this ?

**Comment by Nitish18** [comment]
hi niranjan,
I think i got the problem. I'll complete it by today and will send you a PR
by today's night.

**Comment by poush** [comment]
@Nitish18 If you haven't started or fixed it yet. You can leave it. Actually, this issue is solved in the process of solving  #2803.

**Comment by poush** [comment]
@niranjan94 Please assign me this as well.
