### ISSUE TITLE
Register as speaker: Broken javascript form field validation

### ISSUE THREAD

**Issue by roschaefer** [fossasia/open-event-orga-server#3566]
1. When I try to register as speaker as described in #3565 
2. and I don't fill in the short biography,
3. and I click 'Save'

Nothing happens.

My javascript console tells me:
```
An invalid form control with name='short_biography' is not focusable.
```

**Comment by poush** [comment]
@roschaefer I'm not able to reproduce it here. No such message on my chrome and safari consoles. Can you please tell me the browser and OS you are using. Also after the recent bug fix, you will be able to register as a speaker without any errors.

**Comment by roschaefer** [comment]
```
➜  ~ chromium --version
Chromium 58.0.3029.96 
➜  ~ uname -a
Linux l540 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux

```

**Comment by roschaefer** [comment]
Ok, I couldn't reproduce it myself:

After #3565 is resolved, I'm am now logged in and created a session proposal. When I visited the session proposal for the first time and clicked on "Edit speaker" details, my speaker details were empty (strange, where have they gone?). I enter the form fields, leave out 'short biography' and click on 'Save'. The speaker details were successfully updated.

I think this can be closed.

Minor fix: If short biography is not required, don't put an asterisk on it to avoid confusion.
