### ISSUE TITLE
QR code on generated ticket PDF cannot be scanned due to black background

### ISSUE THREAD

**Issue by icedwater** [fossasia/open-event-orga-server#3576]
It is not possible to scan the ticket QR code from the generated ticket PDF as the black background prevents the code from being detected. Compare the scans from the original location and the transposed location in the attachment.

A proposed solution is to shift the position of the generated QR code down so that it does not overlap; in additon, a guideline for designing the ticket template could be included that accounts for generated QR codes.

I will send a pull request as soon as I figure out how and where to make the changes, but if someone could do it first, that would be much appreciated.

[Test-Ticket.pdf](https://github.com/fossasia/open-event-orga-server/files/985796/Test-Ticket.pdf)

**Comment by poush** [comment]
<img width="980" alt="screen shot 2017-05-09 at 9 02 18 pm" src="https://cloud.githubusercontent.com/assets/1812082/25858996/d5db160c-34fa-11e7-8455-76eb37697ce1.png">

@icedwater see this image. I think this will work.

**Comment by icedwater** [comment]
@poush indeed. Now I need to find or build the app to scan that code.

**Comment by poush** [comment]
@niranjan94 Can you please assign me and add UI tag on this issue.
