### ISSUE TITLE
Wrong Password in DATABASE_URL in basic.md lead to authentication error

### ISSUE THREAD

**Issue by RamolaWeb** [fossasia/open-event-orga-server#3582]
Currently the DATABASE_URL in the basic.md file provided for generic installation is having a wrong password which must be set to "test" as provided while creating the user in the postgres sql instead of the "start" provided which lead to authentication error while executing manage.py file.

**Comment by shubham-padia** [comment]
@RamolaWeb Do you want to send a PR for this ?

**Comment by RamolaWeb** [comment]
@shubham-padia  I will send PR please have a review
