### ISSUE TITLE
Internal server error on attempt to import the data

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-orga-server#3585]
I tried to create an event using the zip file of FOSSASIA 2016 already present in the open-event repo but internal server error occurs.

![screenshot 111](https://cloud.githubusercontent.com/assets/22588035/26032569/2099a264-38b4-11e7-94c6-7e5803ef50e0.png)

**Comment by enigmaeth** [comment]
@heysadboy Are you working on this issue? 
I am also working so you might help if you want :smile:

**Comment by mejariamol** [comment]
@enigmaeth what is the progress on this? please let me know as you are done with this so I can follow up with #3580

**Comment by niranjan94** [comment]
@mejariamol I don't see any relation to this and your PR #3580. All others PRs are passing travis properly. You please check you PR again. This is **not** a blocker for your PR.

**Comment by niranjan94** [comment]
@enigmaeth any progress on this ? This was assigned to Milestone 2. But I see no progress on this front.

**Comment by enigmaeth** [comment]
I used some checkpoints and the error is with the celery task execution.
The task was created without any issue.
As for milestone 2, I solved two issues and got this assigned as no one
else was assigned. I think this issue can be fixed by tomorrow.
