### ISSUE TITLE
Error exporting attendees as csv

### ISSUE THREAD

**Issue by kirstin** [fossasia/open-event-orga-server#3588]
When trying to export the list of attendees as CSV, eventyay reports an internal server error.

The url visited is: https://eventyay.com/events/<event_no>/tickets/attendees/csv

Exporting as PDF Document works.

**Comment by SaptakS** [comment]
@mariobehling @niranjan94 this doesn't seem to be any code related problem, but something related to the deployment or storage.

**Comment by SaptakS** [comment]
@mariobehling @niranjan94 this is an error given only when the number of attendees is large. I think there is some timeout error.

**Comment by SaptakS** [comment]
I think we can use signals here as well and put a celery task to prevent timeout. @niranjan94 @shubham-padia opinion?

**Comment by shubham-padia** [comment]
@SaptakS Sounds good.
