### ISSUE TITLE
Implement support for multiple media files in Sessions API

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3590]
Parent issue #3459
To be done after #3645

Currently we support one of each slides, video and audio. We need to be able to add multiple media files.

**Comment by SaptakS** [comment]
One can use the file API to assure the same result. [Open Event Frontend](https://github.com/fossasia/open-event-frontend) will do a file by file upload and take care of a better UX to show file wise progress. @niranjan94 please create a relevant issue in the frontend repo. Closing it here.
