### ISSUE TITLE
Implement Speakers API with multiple Profile support

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3591]
Parent issue #3459
To be done after #3645

The goal of this feature is, to allow speakers to have different description and bios for different events.

A speaker should be able to save their profile, copy and edit it.

All of the profiles would be linked to a single user. The user would select the appropriate profile when he/she is signing up for an event.

**Comment by SaptakS** [comment]
I think with the present speaker API and relationships and using javascript in frontend this can already be attained. Closing.
