### ISSUE TITLE
Exporting Event Schedule as PNG not working as expected

### ISSUE THREAD

**Issue by kirstin** [fossasia/open-event-orga-server#3594]
When trying to export the Schedule as PNG, the resulting file is not what I expected it to be.  
I expected the whole schedule to be on this one PNG. However, the PNG contains, what is visible in the "schedule window" at the time of pressing the "Export to PNG" button.  

Please see attached examples.

![otsschedule_2](https://cloud.githubusercontent.com/assets/564775/26063195/954b02d6-398d-11e7-9dac-aaa051b4d540.png)
![otsschedule_3](https://cloud.githubusercontent.com/assets/564775/26063206/9a37817a-398d-11e7-92fe-4907b8bc49a4.png)
![otsschedule](https://cloud.githubusercontent.com/assets/564775/26063207/9a3e8c54-398d-11e7-8add-d28eaf507726.png)

**Comment by LuD1161** [comment]
@kirstin 
It is the same bug as in of [**PNG Export from Full Screen Schedule not showing whole schedule issues#3367**](https://github.com/fossasia/open-event-orga-server/issues/3367).

Working on this issue.
It gives partial png when schedule is full screen .
However when it's not enlarged to cover the full screen it's working fine.

**Comment by magdalenesuo** [comment]
Closing. Fixed in #3660
