### ISSUE TITLE
All days should appear on the scheduler

### ISSUE THREAD

**Issue by NinaNC** [fossasia/open-event-orga-server#3597]
Hi all,

Our event is seven days long and when I went to the scheduler, it showed only one day.  Now that I submitted a test talk, it works fine. But it would improve the user experience to show all the days before talks have been submitted.

Keep up the good work!

**Comment by SaptakS** [comment]
@NinaNC this part has now been moved to the [Open Event Frontend](https://github.com/fossasia/open-event-frontend) repo since we are decoupling our architecture. @niranjan94 can you please create relevant issues in the frontend repo if this issue still persists? Thanks. Closing here.
