### ISSUE TITLE
Info about current user[gsoc2016-branch]

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#360]
- [x] Name should be display on the right corner with avatar
- [x] Possibility to log out 
- [x] Add Simple profile settings in openevent.com/admin/profile
      - name
      - social links
      -   email
      -   basic info
      -   avatar

**Comment by SaptakS** [comment]
https://github.com/fossasia/open-event-orga-server/pull/388

Fixes:

- [x] Name should be display on the right corner with avatar
- [x] Possibility to log out 
- [ ] Add Simple profile settings in openevent.com/admin/profile
      - name
      - social links
      -   email
      -   basic info
      -   avatar

**Comment by rafalkowalski** [comment]
#profile doesn't work on the latest changes

**Comment by SaptakS** [comment]
What do you mean by #profile??

**Comment by SaptakS** [comment]
@rafalkowalski can you confirm whether this is fixed on your side? It works fine in my system.
