### ISSUE TITLE
When ordering a ticket it shows "Email resent" in notifications

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3602]
"Email resent" in notifications should be "email sent". It also appears several times instead of one time.
![screenshot from 2017-05-17 07-03-56](https://cloud.githubusercontent.com/assets/1583873/26139237/5a481212-3acf-11e7-948c-c79e826b1a65.png)

**Comment by mejariamol** [comment]
@mariobehling @niranjan94 Yes, I too had noticed that. Notifications didn't get read until click on mark as read button. Hence it appears several times.

Expected: Once the notifications comes in the viewport of the list it should get read itself. What do you think..?  Mark as read option can be given on notifications page to mark notifications read collectively.

This should be implemented in front end too.
