### ISSUE TITLE
Implement sending emails after session submission, ticket purchase, etc via signals

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3608]
**I'm submitting a ...**  (check one with "x")
- feature request

**Current behavior:**
Sending emails after session submission, ticket purchase, etc is done via a function call.

**Expected behavior:**
Send emails after session submission, ticket purchase, etc with the help of signals

**Steps to reproduce:**

none

**Related code:**
none

**Other information:**

none

**Comment by LuD1161** [comment]
@shubham-padia @niranjan94 
Should I create a signal like this and connect it with the respective functions .
Something like this ---

[https://github.com/fossasia/open-event-orga-server/blob/development/app/helpers/notification_email_triggers.py#L46](https://github.com/fossasia/open-event-orga-server/blob/development/app/helpers/notification_email_triggers.py#L46)
```
    # Send notification
        if speaker.user:
            send_notif_session_accept_reject(speaker.user, session.title, state, link)
```
### To

```
    # Send notification
        if speaker.user:
                  speaker_signals.signal('session_accept_or_reject')      
```


[https://github.com/fossasia/open-event-orga-server/blob/development/app/helpers/helpers.py#L579](https://github.com/fossasia/open-event-orga-server/blob/development/app/helpers/helpers.py#L579)
```
@speaker_signals.connect
def send_notif_session_accept_reject(user, session_name, acceptance, link):
        message_settings = MessageSettings.query.filter_by(action=NOTIF_SESSION_ACCEPT_REJECT).first()
```


or do you suggest something different ?

**Comment by shubham-padia** [comment]
@LuD1161 Sorry for not mentioning this in the issue itself, but refactoring this right now when most of the calls will be from the UI views itself, is not beneficial. This will be addressed later upon when the nextgen api has been populated a little bit more.

**Comment by shubham-padia** [comment]
no longer relevant
