### ISSUE TITLE
Export of CSV of speakers and sessions shows error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3620]
The export of the CSV on the speakers and session dashboard tab results in an error message.
![screenshot from 2017-05-19 23-21-24](https://cloud.githubusercontent.com/assets/1583873/26267377/0eb76ae2-3cea-11e7-9e92-0feabcd18dbc.png)

**Comment by LuD1161** [comment]
@mariobehling 
I tried this here : [Trial Event](https://eventyay.com/events/185/sessions/) 


### Output 

#### CSV file
![CSV file](https://cloud.githubusercontent.com/assets/17861054/26274270/a35ea36c-3d63-11e7-80a7-51a6e74f1213.png)

#### Sessions page
![image](https://cloud.githubusercontent.com/assets/17861054/26274271/acc5340c-3d63-11e7-87bd-3d756c658ba0.png)


I may have missed this , can you provide any steps to reproduce it.

**Comment by niranjan94** [comment]
@LuD1161 the issue mainly occurs when there are a large number of sessions and speakers. 

Please test your implementation with the fossasia 2016 sample.

**Comment by niranjan94** [comment]
@LuD1161 what's the progress on this ?

**Comment by LuD1161** [comment]
@niranjan94 
Can't proceed with this **as there is an error in import** which is mentioned in [issue#3585](https://github.com/fossasia/open-event-orga-server/issues/3585) **( Internal server error on attempt to import the data )**.
So , I can't work on large data datasets like fossasia 2016 sample , however it's working fine on smaller events.

**Comment by niranjan94** [comment]
@LuD1161 that is not a valid reason. There are always other ways to create additional data. You can even write a simple script that can use the local api to create 1000s of records.

**Comment by niranjan94** [comment]
#3585 is **not** a blocker to this issue.

**Comment by LuD1161** [comment]
@niranjan94 
Didn't thought of it.
I will do it rightaway.

**Comment by mariobehling** [comment]
@LuD1161 What is the progress? OpenTechSummit is tomorrow.

**Comment by LuD1161** [comment]
@mariobehling 
Currently working on **PNG Export from Full Screen Schedule not showing whole schedule**( [issue#3367](https://github.com/fossasia/open-event-orga-server/issues/3367) ) 

Found the root cause of the problem , still trying to find a way to fix it.
Soon will catch up with this.

**Comment by SaptakS** [comment]
@niranjan94 this seems similar to the attendee export issue. I would like to take this up.

**Comment by niranjan94** [comment]
@SaptakS please proceed
