### ISSUE TITLE
Schedule Not Found

### ISSUE THREAD

**Issue by LuD1161** [fossasia/open-event-orga-server#3623]
**I'm submitting a ...**  
- [x] bug report

**Current behavior:**
I am getting an error not found when I try to access the schedule of an event :

![image](https://cloud.githubusercontent.com/assets/17861054/26274292/943e89c8-3d64-11e7-88eb-49b094e91ebf.png)

**Expected behavior:**
The schedule should be displayed .

**Steps to reproduce:**
* Create an event 
* Add sessions to it and assign speakers to it 
* In the **Scheduler tab**  assign sessions to the microlocations you have created.

**Other information:**
This is the screenshot of my **scheduler tab**.
![image](https://cloud.githubusercontent.com/assets/17861054/26274323/066586a0-3d65-11e7-89ba-0ed3bc70c6c0.png)

**System information:** 
I am facing this on eventyay.com as well as on my local setup.

```
OS : Linux
```

```
Python 2.7.13
```

**Comment by shubham-padia** [comment]
@LuD1161 Please crop your screenshots in future to avoid unnecessary details.

**Comment by mejariamol** [comment]
@LuD1161 check the status of the sessions. `accepted` sessions are only shown in schedule.

@niranjan94 why only accepted sessions are shown in the schedule. what if session is confirmed? please check this code. https://github.com/fossasia/open-event-orga-server/blob/development/app/views/public/event_detail.py#L58

when all the sessions are confirmed, `get_count(DataGetter.get_sessions(event.id))` return 0, hence giving 404 error
```
@event_detail.route('/<identifier>/schedule/')
def display_event_schedule(identifier):
    ...
    accepted_sessions_count = get_count(DataGetter.get_sessions(event.id))
    ...
    if accepted_sessions_count == 0 or not event.schedule_published_on:
        abort(404)
```
default state is `accepted` in `get_sessions`
```
@staticmethod
    def get_sessions(event_id, state='accepted'):
        ...
```

**Comment by LuD1161** [comment]
I think we should change show sessions which are in either of the two states confirmed ,accepted.
That should suffice .

@niranjan94 @mejariamol 

 what do you suggest ?

**Comment by niranjan94** [comment]
@LuD1161 agreed. Both states should be displayed

**Comment by niranjan94** [comment]
@LuD1161 what's the progress on that ? This seemingly simple issue has been open for the past two days. Ideally we want to close all issues in a day.

**Comment by LuD1161** [comment]
@niranjan94 
Done.

**Comment by niranjan94** [comment]
@LuD1161 where is the PR ? No issue is done without a linked PR.
