### ISSUE TITLE
Setup flask-rest-jsonapi on the nextgen branch.

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3640]
Please open sub-issues to this parent issue to implement flask-rest-jsonapi on the nextgen branch.

**Comment by niranjan94** [comment]
These are the very basic requirements to get started on this.

- JSON-API Specification to be followed
- Re-use existing JWT Authentication
- API will be located at `/v1` (eg. `https://api.eventyay.com/v1`)
- All dates (in responses, payload, filtering) should follow ISO 8601 with timezone information (Eg. `2017-05-22T09:12:44+00:00`)
