### ISSUE TITLE
API documentation implementation for the nextgen API 

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3641]
Parent issue #3640

Currently we use swagger for documenting our API (Can be seen at https://eventyay.com/api/v1/). The important question now are:
- Can swagger be used when we move to `flask-rest-jsonapi` ?
- Is there an alternative to swagger that would work better for our new API architecture ?

Please add in your thoughts here.

**Comment by shubham-padia** [comment]
[Api-Blueprint](https://apiblueprint.org/) is worth a consideration, the thing that powers apiary. here is an example jsonapi using Api-Blueprint. Here's an example api doc : http://docs.accountjsonapi.apiary.io/#introduction/query-parameter. But all of the documentation has to be written manually.
If anybody can find a way or library that automtaes the documentaion process, it'd be really great.

**Comment by LuD1161** [comment]
I agree with @shubham-padia , Api-Blueprint is good ( apart from the fact that we have to manually create the documentation, but I didn't find any automated tools either ).
I haven't created a documentation earlier but after some finding I came across [apiDoc](http://apidocjs.com/) . 
**It creates a documentation from the API annotations in the source code.**

Something like this :

```
/**
 * @api {get} /user/:id Request User information
 * @apiName GetUser
 * @apiGroup User
 *
 * @apiParam {Number} id Users unique ID.
 *
 * @apiSuccess {String} firstname Firstname of the User.
 * @apiSuccess {String} lastname  Lastname of the User.
 */
```
As stated on their website :
- Generates documentation from multiline comments in python
- Other filters and templates can be used

However , it's just what I found . I haven't used it and can't be sure of the difficulties it may pose in the long run. 

[Api-blueprint](https://apiblueprint.org/) is much used , however maybe we can test it.

**Comment by niranjan94** [comment]
@enigmaeth @poush @SaptakS @magdalenesuo please add in your ideas/suggestions

**Comment by SaptakS** [comment]
@niranjan94 @shubham-padia I think we can still use [flask-swagger](https://github.com/gangverk/flask-swagger) since we would only need to make the yaml file. I don't see a point of writing docs manually.  And it seems to work fine with flask rest jsonapi.

**Comment by magdalenesuo** [comment]
@niranjan94 @shubham-padia @SaptakS how about this? https://github.com/acoomans/flask-autodoc

**Comment by enigmaeth** [comment]
@SaptakS  I think that we won't be able to use swagger with flask-rest-jsonapi. Please take a look at this issue : https://github.com/miLibris/flask-rest-jsonapi/issues/12

**Comment by poush** [comment]
This [flask-autodoc]( https://github.com/acoomans/flask-autodoc) looks like a nice option. Although I think Api-Blueprint option will be good if can create some generator. This generator will read API files and create doc file from the endpoints for API-Blueprint (this can be the part of deploy process). Apart from the modules mentioned above, I found one [phinxcontrib.autohttp.flask](https://pythonhosted.org/sphinxcontrib-httpdomain/#module-sphinxcontrib.autohttp.flask).

**Comment by shubham-padia** [comment]
There is only one automated documentation tool available for marshmallow and that supports only the open api spec (formerly known as swagger spec): https://github.com/marshmallow-code/apispec.
So we have only manual doc tools at our hand.
[flask-autodoc]( https://github.com/acoomans/flask-autodoc) and  [phinxcontrib.autohttp.flask](https://pythonhosted.org/sphinxcontrib-httpdomain/#module-sphinxcontrib.autohttp.flask) go out of the picture as they don't support testing the endpoints from the documentation itself.

So we are left with 3 tools to decide from, all of which are manual :
- Apidoc (https://github.com/apidoc/apidoc)
- Api-Blueprint (https://apiblueprint.org/) 
- flask-swagger (https://github.com/gangverk/flask-swagger)

@fossasia/open-event-server-devs Opinions on this ??

**Comment by shubham-padia** [comment]
My opinion:
- Apidoc (widely used, but from as far as I can tell requires different plugins for different spec, not sure about this though)
- Api blueprint (Widely used and supports json-api spec)
- flask-swagger (Less used in comparison to above two, and would prefer to remain as far as possible from openapi f.k.a swagger spec)

I'd say we go with Api blueprint.

**Comment by SaptakS** [comment]
But then what is the advantage of using API blueprint since most of the work is manual? Shouldn't we give preference to flask-swagger in that case? I would say flask swagger since it makes most of the things automated and is specifically designed for flask, so it works better with flask. I couldn't find many example of API Blueprint being used with flask. @shubham-padia can you give some example projects where it is used?

**Comment by shubham-padia** [comment]
Api blueprint provides as much automation as flask-swagger provides,in earlier by automation i meant detecting all fields automatically from marshmallow schema objects, and apparently no doc generator supports that atm for jsonapi spec now. WE have to manually write the fields in flask-swagger and api blueprint both.

Here's the example docs for jsonapi spec: http://docs.accountjsonapi.apiary.io/#introduction/query-parameter

**Comment by SaptakS** [comment]
@shubham-padia got it. But I still don't get many flask projects using API Blueprint for docs. While flask-swagger is used in many flask projects. So why not go with flask-swagger? Does it not support json-api-spec?

**Comment by shubham-padia** [comment]
No. Not officially, it supports open-api spec fka swagger

**Comment by shubham-padia** [comment]
And api blueprint is not framework agnostic and I'm sure lots of flask applications use api blueprint for their documentation considering it is so widely used. We can even use apiary.io with its rich text editor with online preview.

**Comment by niranjan94** [comment]
I feel we should go with API Blueprint. It's widely used and it's API framework agnostic. Looks very well maintained too. flask-swagger is primarily meant for the open api spec which I don't think plays well with jsonapi spec especially with the relations and everything. 

So, we'll go with API Blueprint. 

And work needs to get started ASAP on this. We need this by the end of this week so the the frontend devs can start implementing it.

**Comment by niranjan94** [comment]
Work to be continued in #3732
