### ISSUE TITLE
Merge user and user_detail table and maintain data integrity

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3644]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Currently the user and user_detail have on 1-1 relationship with user_id acting as the primary key in both tables.

**Expected behavior:**

Should be a single table

**Steps to reproduce:**

Create the database.

**Comment by shubham-padia** [comment]
`user` is a reserved is postgresql, also rename it to users.

**Comment by niranjan94** [comment]
@shubham-padia wasn't user->users rename part of the db refactor ?

**Comment by shubham-padia** [comment]
@niranjan94 Must have been missed during the changes, it was hard to keep track of every single change.

**Comment by shubham-padia** [comment]
closed via #3650
