### ISSUE TITLE
Implement the Scheduler UI interface's base into the Server

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#365]
Implement the primitive interface of the Scheduler UI as discussed here at #349 into the Server UI so that we can start working on it. 

Demo: https://oes-testbed.codezero.xyz/scheduling/ 

The base interface should contain:
- Drag and drop sessions into tracks
- Graphically resize sessions to change timings.

**Comment by niranjan94** [comment]
@rafalkowalski @juslee Where should the scheduler be located ? 
I don't think it should be part of the event wizard. The scheduler should a separate tool under each event.

**Comment by rafalkowalski** [comment]
it's in our user stories, am I wrong? @niranjan94 @juslee 
we will show this part when event will have scheduling state

**Comment by niranjan94** [comment]
@rafalkowalski yes. It's there in the user story. Okay.. I'll put as per the user story for now.

**Comment by rafalkowalski** [comment]
if you have better idea please inform us :)

**Comment by niranjan94** [comment]
@rafalkowalski It actually looks good as it is :wink: . 

![screenshot 47](https://cloud.githubusercontent.com/assets/2404372/15501691/72460d46-21cc-11e6-9e39-34ac8e7aeb72.png)
