### ISSUE TITLE
Read environment variables from file

### ISSUE THREAD

**Issue by hongquan** [fossasia/open-event-orga-server#3651]
I found that our project uses some environment variables to maintain different configuration for different deployment. But for local development, developers have to run many `export` commands. It is not convenient (we human are lazy).

My suggestion is to write down those variables in _.env_, let it ignored by Git, and use [envparse](https://github.com/rconradharris/envparse) to parse the file.

**Comment by niranjan94** [comment]
@hongquan agreed. This will make new developers on-boarding a bit easier. Thanks for the suggestion :)

**Comment by hongquan** [comment]
In the #3661, you didn't take advantage of _envparse_ feature. This is for example your config code:

```python
socketio_integration =  env.str('INTEGRATE_SOCKETIO', default=False)
INTEGRATE_SOCKETIO = bool(socketio_integration == 'true')
```

But it should be:

```python
INTEGRATE_SOCKETIO = env.bool('INTEGRATE_SOCKETIO', default=False)
```

Be aware that you have some inconsistent data type:

```python
SERVER_NAME = env.str('SERVER_NAME', default=None)
```
with `env.str`, you are expecting a string, but you default value is `NoneType`, instead of string.

One more thing, value of environment variable is originally string, you don't need to _cast_ its type with `env.str`. Just doing 
```python
SERVER_NAME = env('SERVER_NAME', default='')
```
is enough.

**Comment by magdalenesuo** [comment]
@hongquan Oh I see. I didn't know about that, thank you. I'll change it.
