### ISSUE TITLE
3rd party authentication with client apps

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#367]
@rafalkowalski @aditya1702 @shivamMg @aviaryan 
We want to have a system where the client app at startup shows 3rd party auth options. 
On successful authentication, 
* [ ] Credentials are sent to the server using POST
* [ ] Server replies with a unique token which will be included in every request by the clients.

We need to work side by side on this issue. Please give your views and suggestions.

**Comment by aviaryan** [comment]
> Server replies with a unique token which will be included in every request by the clients.

Why every request ? If I get it right, client means the web and android app. So far, the only feature I know which will require authentication is session reviews. 

---

I wanted to do something like that and have written it in my proposal ([Drive Link](https://drive.google.com/open?id=1xwoWwsr9QY_TcJX7CeyQaJxAiC1G83TPlUCOWRqoM9s)) - 

> c. For authentication, I plan to use Google. The client­side application (web, android) will 
get access token and will send it over to server for cross verification. From the server, 
we can fetch more information about the user from Google’s API. I find these links 
useful. Client side ­​https://goo.gl/R256jK​ . Server side ­​https://goo.gl/9a74Xe​
d. Similarly Facebook can be used as an authentication middleman too. Aslike Google, the 
client­side application will get access token and post it over to the server for verification 
and identification. The following official documentation link describes this. 
https://goo.gl/8fdGPj 
e. I will extract email from Facebook/Google profile and store it in database to make sure 
that only one review is created by a user for a session/event. 
f. If I get time, I will implement feature to add reviews through the open event server’s web 
interface. Users can login in with Facebook or Google and review a session or event 
there itself. 

Auth services of Facebook and Google return {Full Name, Email} so we can create a model with 
{Full Name, Email, AuthProvider, **RandomHash**} .
Once identity of a user is verified by the orga server, then he will be a given a random hash which he can use for adding reviews. 
If he is to sign-in from another client app and his identity is again validated by the server, the existing *random_hash* will be returned back to use. This way he can stay login'd from various client apps simultaneously. 

What do you guys think ?

There is a flowchart I drew for google authentication. 
![reviewsauth 3](https://cloud.githubusercontent.com/assets/4047597/15491035/6065ac04-218a-11e6-8bbd-2b37268ffa7d.png)

**Comment by aditya1702** [comment]
@mananwason @aviaryan I have already implemented this in my PR. Check here:https://github.com/fossasia/open-event-orga-server/pull/323

**Comment by aviaryan** [comment]
@aditya1702 Great. I didn't knew you had added facebook authentication too. :smile:  That will surely save a lot of work.

**Comment by leto** [comment]
@aviaryan @aditya1702 just to clarify, we will want to include these tokens in any API call that creates/edits/writes to something. Right now it seems like session reviews is the only API call that requires that, but we may add others. For instance, if we want to have an API method for logging out, the user should give us their auth_token for that, or else anybody could logout anybody else.

**Comment by mariobehling** [comment]
This functionality is already on the feature list of Rafal.
