### ISSUE TITLE
Implement api endpoints for `users` model

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3670]
Parent issue #3459
To be done after #3645

**Comment by niranjan94** [comment]
Required endpoints for now:
- `GET /v1/users` - Get users - should support filtering, sorting and pagination
- `POST /v1/users` - Create user
- `GET /v1/users/<user_id>` - Get a single user
- `PATCH /v1/users/<user_id>` - Update a single user
- `DELETE /v1/users/<user_id>` - Delete a single user

**Comment by shubham-padia** [comment]
closed via #3679 .
