### ISSUE TITLE
Add Map

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#368]
#310 

Map should be added and position from map should be saved to event

**Comment by aditya1702** [comment]
@rafalkowalski @SaptakS Do we need latitude and longitude fields on the event form?

**Comment by rafalkowalski** [comment]
i think only location will be enough

**Comment by rafalkowalski** [comment]
TODO #310 
- [ ] Add possibility to save location name to database, longitude and latitude
- [ ] Remove button GO! it's ugly we need a changing listener if you put Singapore location automatically location should be changed on the map
- [ ] Move Map on the right
