### ISSUE TITLE
Propose and implement methods to verify user email

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3685]
~~- GET/PATCH/DELETE `/users/me`~~
- Endpoint to verify email (please don't follow the current implementation, first propose a standard implementation being used widely)

**Comment by niranjan94** [comment]
@shubham-padia the `/users/me` endpoint is not required. The logged in user id is already part of the JWT token payload. Requests can be made using that that to `/users/<user_id>` itself.

**Comment by shubham-padia** [comment]
@niranjan94 +1.

**Comment by LuD1161** [comment]
@shubham-padia @niranjan94 
Why not use token verification like all other systems ?
One endpoint with GET parameters containing tokens .

Two proposed methods for the implementation : 

1. **Database Checking** : The endpoint checks for the token in the database
2. **Calculating email** : Generate token based on **HMAC(email+current_time+secret_token)** as mentioned [here](https://pymotw.com/2/hmac/). Thus **no need of extra database calls** and creating new columns just for storing a time-expiring token ( of no further use ).

I myself prefer going with the  **Calculating email**.

**Comment by LuD1161** [comment]
@shubham-padia @niranjan94 
Why not use token verification like all other systems ?
One endpoint with GET parameters containing tokens .

Two proposed methods for the implementation : 

1. **Database Checking** : The endpoint checks for the token in the database
2. **Calculating email** : Generate token based on **HMAC(email+current_time+secret_token)** as mentioned [here](https://pymotw.com/2/hmac/). Thus **no need of extra database calls** and creating new columns just for storing a time-expiring token ( of no further use ).

I myself prefer going with  **Calculating email**.

**Comment by niranjan94** [comment]
@LuD1161 by implementation ... what is meant is the complete email verification flow along with endpoints.. What we need is something like this.

**Endpoint:**
The end-point required would be something like:

- `POST /users/<user-id>/verify-email` - The payload would be the token. The response can be a simple `200` for a success or `401` or something for invalid token

**Flow:**
- When ever a user is registered via the user registration endpoint, an email would be sent to the user from the API server with a link. `<frontend-url>/email/verify?token=<the token>`. Note that the token should be URL safe. (The frontend URL should be stored as a setting. Configurable. Default should be the naked domain of the API Server. (eg. if api server is at `api.eventyay.com`, frontend should be assumed to be at `eventyay.com`)
- When the user checks his email and clicks on the link, he is taken to the frontend page which gets the token and makes an API request to the token verification endpoint and handles the UI accordingly.

**Comment by poush** [comment]
@niranjan94 Can it be just ```/users/<user-id>/verify``` Since we have only email to verify user accounts. And the end point is meant to verify the user and the key type can be changed in future, maybe we get an option to verify with mobile.

**Comment by niranjan94** [comment]
@poush yep. Sounds good. `verify-email` was just an example ;)

**Comment by niranjan94** [comment]
@poush are you working on this ?

**Comment by poush** [comment]
No, not yet. But yeah can work on it after https://github.com/fossasia/open-event-orga-server/issues/3813

**Comment by niranjan94** [comment]
@poush assigning this to Milestone 9. Please ensure this is done asap.
