### ISSUE TITLE
New User registration through api.eventyay.com doesn't work

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3689]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Right now, user registration doesn't work through api.eventyay.com. It gives an internal server error. Also, when tried from local deployment, the user is created, but trying to log in gives wrong credential.

**Steps to reproduce:**

* Go to https://api.eventyay.com/register/ and try to register

**Comment by shubham-padia** [comment]
closed via #3691
