### ISSUE TITLE
Add microloaction api endpoints along with proper relationships and permissions

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3697]
Sessions api will also be needed for this, create a basic one with only the required fields, other fields will be populated in other issue.(Please do not add any other fields, it will be done in other issue only, PR will be rejected if you do otherwise)

**Comment by magdalenesuo** [comment]
@shubham-padia I think there is no issue in going ahead with this even before the completion of #3693. Since we will be only defining the basic relationship of microlocations with the events and sessions.
I don't think there is a need for us to wait for the populating the events api.

**Comment by shubham-padia** [comment]
Yes. Updated the description. Thanks.
