### ISSUE TITLE
Two 'Price' fields in TicketSchema and wrong schema entered for 'event' field in TicketSchema

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#3705]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Comment by shubham-padia** [comment]
closed via #3706
