### ISSUE TITLE
Refactor duplicate endpoints.

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3712]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Right now there are some duplicate endpoints that have arisen. Need to check and refactor them to avoid same endpoints refering to different views.

**Comment by magdalenesuo** [comment]
@SaptakS @shubham-padia Lets do this after most of the basic APIs are done?

**Comment by SaptakS** [comment]
@magdalenesuo I agree with you because there might come up more refactoring issues. So better we do it after all APIs are done in a basic format.

**Comment by poush** [comment]
Along with this, we also need to update the related endpoints. Generally they are using `id` as keys in endpoints while they should be in format `model_id` like `event_id`, `session_id`, etc. This needs to be fixed so that proper utilization of these can be done in different methods.

**Comment by niranjan94** [comment]
@poush this is done or is anything pending here ?

**Comment by shubham-padia** [comment]
This seems to be done
