### ISSUE TITLE
Implement event-invoice api with proper permissions and relationships

### ISSUE THREAD

**Issue by enigmaeth** [fossasia/open-event-orga-server#3720]

**Comment by niranjan94** [comment]
Please propose this API structure here before proceeding.

**Comment by enigmaeth** [comment]
@niranjan94 I have implemented the basic APIs [here](https://github.com/enigmaeth/open-event-orga-server/commit/6c6551f447669a014625aa617a330bb01da093b5).

The endpoints implemented are:

`/event_invoices/<int:id>/user` : user from invoice
`/event_invoices/<int:id>/event` : event from invoice

`/events/<int:event_id>/event_invoices` : get invoices for one event
`/users/<int:user_id>/event_invoices` : get invoices for one user

`/event-invoices` : all event-invoices( for super-admin, permission to be implemented)

`/event_invoices/<int:id>` : invoice detail from invoice id

`/users/<int:id>/relationships/event_invoices` : relationships b/w user and an event-invoice
`/events/<int:id>/relationships/event_invoices` : relationships b/w event and an event-invoice
`/event_invoices/<int:id>/relationships/user` : relationships b/w event-invoice and a user
`/event_invoices/<int:id>/relationships/event` : relationships b/w event-invoice and an event

Please help me with how to add other functions now. From what I have understood by API structure is how we are going to implement functions of InvoicingManager class, right?

**Comment by enigmaeth** [comment]
@SaptakS @shubham-padia @poush Please comment your suggestions.
