### ISSUE TITLE
Implement image-size api with proper permissions and relationships

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#3722]

**Comment by LuD1161** [comment]
@magdalenesuo 
Should I proceed with this ?

**Comment by magdalenesuo** [comment]
@LuD1161 I've already started working on this. maybe checkout some other issues? Or you can open issues and work on it, most of the API implementation issues haven't been opened yet.

**Comment by shubham-padia** [comment]
closed via #3725
