### ISSUE TITLE
Implement speakers api with proper permissions and relationships

### ISSUE THREAD

**Issue by LuD1161** [fossasia/open-event-orga-server#3727]
Proposed API structure :

`/speakers/` : get all speakers
`/speakers/<int:event_id>` : get speakers for one event

**Comment by niranjan94** [comment]
@LuD1161 this is not how JSON-API Spec compatible APIs are implemented. Why haven't you read about it yet ? Please read up on the JSON-API Specification. 

These are the endpoints needed should be like this. (the below list may not be complete. But you get the idea)
/speakers/int:id/event
/events/int:event_id/speakers
/events/int:id/relationships/speakers
/speakers/int:speaker_id/sessions
/sessions/int:id/relationships/speakers
/speakers
/speakers/int:id
/speakers/int:id/relationships/event

**Comment by LuD1161** [comment]
@niranjan94 
Thanks for the descriptive info.
It's not that I haven't read about JSON-API specification. I was going to implement relationships and other details. I forgot to mention **more** at the end.
I hadn't thought of all the endpoints till then so didn't mention it.
Will add other endpoints as I progress.
Thanks.

**Comment by SaptakS** [comment]
Isn't this the same issue as #3591? @niranjan94 @LuD1161

**Comment by niranjan94** [comment]
@enigmaeth most of this has already been done by @LuD1161 . You can find the code over here in this branch (https://github.com/fossasia/open-event-orga-server/tree/speakers-api). Please work on that branch. 

You can see what is left out in the comments over at #3771 .

**Comment by enigmaeth** [comment]
@niranjan94 @SaptakS @shubham-padia 

Please take a look at details for Speakers API. Please correct if I am wrong at any point.

From #3771, I got the following: 
- One user can be related to multiple speaker profiles. 
- One session is related to one speaker. And one speaker is related to one session. (Conflicting endpoints, please confirm)

## Proposed Endpoints:

- `speakers/<int:id>` : To get details of one speaker profile by id

- `speakers/<int:id>/session` : Get the details of session where this speaker profile is speaking
- `speakers/<int:id>/event` : Get the details of event where this speaker profile is speaking
- `speakers/<int:id>/user` : Get the details of user with which this speaker profile is associated

- `events/<int:event_id/identifier>` : To post the details and to get list of speakers for an event
- `sessions/<int:session_id>/speaker` : Detail of speaker of that session
- `users/<int:user_id>/speakers` : List of speaker profiles associated with that user

Plus the corresponding relationship endpoints.

Do these look good? Suggestions please!

**Comment by niranjan94** [comment]
> One user can be related to multiple speaker profiles.

Correct.

> One session is related to one speaker. And one speaker is related to one
session.

No. This should be many to many. One session can have many speakers. One
speaker can have many sessions.

**Comment by arp95** [comment]
also guys i cam across an event where a session can belong to multiple tracks. are we going to handle such a case?

**Comment by niranjan94** [comment]
Nope. I guess you're talking about FBF8. Those weren't actually tracks.
There were more like categories/topics/tags.

As far as tracks go, one session can only belong to one track. That's what
a track is.

We may support categories/topics/tags like that FBF8 in future. But no
plans for that at this point.

**Comment by arp95** [comment]
actually i was talking about the google io case.
Link: https://events.google.com/io/schedule/?section=may-17&sid=5f387420-d89d-46d4-b5af-f740e59a52cb

in this case the session belonged to the firebase and cloud track.
yeah sure no problem. i just came across so notified you guys,

**Comment by enigmaeth** [comment]
@SaptakS @niranjan94 @shubham-padia 

We have
`events/id/speakers` endpoint for get and post
`speakers/id` : get details, patch, delete

about the other endpoints, I think that providing post is a bad idea as we don't want to add speakers there, rather we just want to add relationships, so only get seemed logical to me for:
`sessions/id/speakers`
`users/id/speakers`

[Here](https://github.com/enigmaeth/open-event-test/commit/22665cdc63ce2a86091662a80f9b41321ad30275)'s the commit with the endpoints implemented from my [comment](https://github.com/fossasia/open-event-orga-server/issues/3727#issuecomment-313217374) above

**Comment by niranjan94** [comment]
We need the following. 

- `GET/POST /v1/events/<identifier>/speakers` - Get/Create a speaker(s) related to event. 
- `GET/PATCH/DELETE /v1/speakers/<id>`
- `GET/POST /v1/speakers/<id>/sessions` - Get/Create a session(s) related to speaker. 
- `GET/POST /v1/sessions/<id>/speakers` - Get/Create a speaker(s) related to session. 
- `GET/POST /v1/users/<id>/speakers` - Get/Create a speaker(s) related to user. 
- `GET /v1/speakers/<id>/user` - Get user linked to speakers

Relationships can be adding in the `PATCH /v1/speakers/<id>` request itself anytime. (See http://jsonapi.org/format/#crud-updating-resource-relationships )
