### ISSUE TITLE
Implement API Blueprint for documenting the nextgen API

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3732]
Follow up to discussion on #3641

We will be using Api-Blueprint (https://apiblueprint.org/). This issue is a high priority one. Needs to be done by the end of this week.

**Comment by niranjan94** [comment]
Just a reminder. @magdalenesuo @poush this is part of Milestone 5. Needs to be done this. As the FE (Frontend) will be needing this once they start working on the API from monday.

**Comment by SaptakS** [comment]
I am closing this issue since from now every PR for implementing a new API should also include the documentation for it.
