### ISSUE TITLE
Migrate all data in datetime fields to `time-stamp with timezone`

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3739]
Currently all of the datetime fields store time as a timestamp without timezone. Migrate all data in datetime fields to `time-stamp with timezone` according to the timezone field.

- We should first start storing date time with proper timezone in the db itself. Right now, all our date time fields are of the data type timestamp without time zone. Needs to be changed to timestamp with time zone.
- The timezone db column in the events table is only for storing the name of the timezone. (since different names can have the same UTC offset). The actual offset information should be taken from and used from the date time fields.
- This applies to all tables and all date time fields. events, sessions, tickets, and everything else. Included created at and deleted at. For internal fields (like created at and deleted at), we should use utc. This is important because the frontend will be localising all dates and times based on user's preferences. Included deleted at and created at.

**Comment by shubham-padia** [comment]
@niranjan94 
suppose created_at in some table is `2017-04-16 01:07:15.66815`, after migration it changes to `2017-04-16 06:37:15.66815+05:30`. As you can see the time has changed from 01:07 to 06:37, the offset (i.e `05:30` ) will always remain according to the server timezone. So in fact, the date is interpreted as utc, but the offset is according to server timezone. This is the default behaviour of `AT TIME ZONE` as seen here:https://www.postgresql.org/docs/9.2/static/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT . Is this acceptable?

**Comment by niranjan94** [comment]
@shubham-padia this is completely acceptable ... As long as the offset info is part of the date time it's alright

**Comment by shubham-padia** [comment]
@niranjan94 
 I'm trying to execute a query
```sql
ALTER TABLE call_for_papers ALTER COLUMN start_date  TYPE TIMESTAMP WITH TIME ZONE USING start_date AT TIME ZONE timezone
```
Where timezone is a column but AT TIME ZONE wants a string there, https://www.postgresql.org/docs/9.2/static/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT
Would you happen to know if there's a possible workaround about this in RAW sql ?

**Comment by niranjan94** [comment]
@shubham-padia Hmm ... I don't think so. Since it's a table wide alter statement. 
What you could do is, first update all timestamps to UTC with the old field type itself. 

Then run
```sql
ALTER TABLE call_for_papers ALTER COLUMN start_date  TYPE TIMESTAMP WITH TIME ZONE USING start_date AT TIME ZONE 'UTC'
```

**Comment by shubham-padia** [comment]
@niranjan94 
>  first update all timestamps to UTC with the old field type itself.
But it will require using `AT TIME ZONE` or am i missing something

**Comment by niranjan94** [comment]
@shubham-padia convert date time to UTC and store it in the old field itself. Since that field is, without timezone, it should technically strip the timezone info and just store date and time. But the time would be in UTC. Now, you can just run

```
ALTER TABLE call_for_papers ALTER COLUMN start_date  TYPE TIMESTAMP WITH TIME ZONE USING start_date AT TIME ZONE 'UTC'
```
