### ISSUE TITLE
Add support to download ticket pdf and view tickets purchased by user

### ISSUE THREAD

**Issue by poush** [fossasia/open-event-orga-server#3740]
Add support in existing tickets API to download pdf tickets and permission decorators to view tickets purchased by user.

Parent Issue #3468

**Comment by niranjan94** [comment]
Once a ticket has been purchased, the pdf of the ticket should be generated and stored in the preferred storage (cloud or local). The URL to the ticket can be stored in db. We need two types of tickets
- A pdf will all the tickets (url will be attached to the event invoice (#3720) . Would be accessible only by the person who made the purchase)
- A pdf with just the ticket of that specific ticket holder. (Each ticket holder would have this and also get an email with this.)

**Comment by poush** [comment]
The part with ticket_holder and event_invoice (invoice_pdf_url) has been done. The other part will be done after Orders API on order_invoice API
