### ISSUE TITLE
bug: aspect ratio of event logo on eventyay.com front page wrong

### ISSUE THREAD

**Issue by jospoortvliet** [fossasia/open-event-orga-server#3747]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Current behavior:**
Showing aspect ratio of Nextcloud logo badly on eventyay.com

![screenshot_20170608_104604](https://user-images.githubusercontent.com/551757/26919959-c08e61ce-4c37-11e7-9510-09c3f3bcbbe6.png)

*Expected behavior:**
Respect aspect ratio

**Comment by shubham-padia** [comment]
@enigmaeth Can you handle this, should be a quick fix

**Comment by jospoortvliet** [comment]
Nice, team, thanks!

**Comment by shubham-padia** [comment]
@niranjan94 @SaptakS Can you please help merging the current development into master so that this gets displayed on eventyay :) .
