### ISSUE TITLE
bug: can't add links to the description

### ISSUE THREAD

**Issue by jospoortvliet** [fossasia/open-event-orga-server#3748]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Current behavior:**
Create a conference description on the very first 'edit' page. Insert a link. click next. Finish, close.

The link does not show up on the event page and has disappeared when you edit again.

**Expected behavior:**
The link shows up in the description and doesn't disappear.

**Steps to reproduce:**
fails to work every time in Nextcloud conf description.

**Comment by enigmaeth** [comment]
@jospoortvliet  Do you mean these? 
![image](https://user-images.githubusercontent.com/14938154/27175670-861eaf3e-51dd-11e7-99a1-1c3ad0fb801f.png)

They seem to be working fine for me.
Let me know if I am mistaken!

**Comment by jospoortvliet** [comment]
No, I mean in the description itself. You can add a link but it will disappear, so I now had to put in the link in plain text. See this screenshot:
![spectacle i21582](https://user-images.githubusercontent.com/551757/27277856-f64dc1f0-54df-11e7-90f0-d7c98e9f5291.png)

**Comment by jospoortvliet** [comment]
The blue text "conference information page" I just linkified using the insert link button in the toolbar, but clicking next next save won't save it ;-)

Hence the plain text link behind it, as that WILL be preserved.

**Comment by SaptakS** [comment]
@jospoortvliet will check into it to see what is causing this problem.

**Comment by SaptakS** [comment]
@jospoortvliet this is resolved as far as API is concerned. @niranjan94 can you please take care of this in [Open Event Frontend](https://github.com/fossasia/open-event-frontend)? Closing it here. 

@jospoortvliet this will be resolved in the next production release. Thanks for pointing out.
