### ISSUE TITLE
Dasherize all fields in the api 

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3753]
- Dasherize all fields as shown in http://marshmallow-jsonapi.readthedocs.io/en/latest/quickstart.html#inflection
- Cleanup unused dependencies.

**Comment by niranjan94** [comment]
Would this apply to relationships too?

**Comment by niranjan94** [comment]
@shubham-padia

**Comment by niranjan94** [comment]
Also ensure the URLs are also dasherized as per http://jsonapi.org/recommendations/#naming

**Comment by shubham-padia** [comment]
Okay, will make changes accordingly in #3754

**Comment by shubham-padia** [comment]
closed via #3754
