### ISSUE TITLE
Use marshmallow url fields wherever necessary

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3756]
Apparently, all of us (the devs) have not marshmallow url field, http://marshmallow.readthedocs.io/en/latest/api_reference.html#module-marshmallow.fields

Use that.

**Comment by niranjan94** [comment]
@shubham-padia not just URLs, ensure all fields use the correct type.

**Comment by shubham-padia** [comment]
closed via #3757
