### ISSUE TITLE
Rename call for papers to an data friendly name

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3758]
Currently the table and api refer to it as `Call for papers`. But it isn't actually a call for _papers_. Throughout the UI it is called Call for speakers. And that is what it is. 

Now, we could call is call for speakers. 
But, again here arises an issue when naming resources. 
- Call for speakers - though sounds plural, it should actually be a single resource
- So now what will we be call a list of call for speakers. ? English says we should call it 'Calls for speakers'. But API clients that take care of the naming for us don't exactly obey that. And we'll be having the API as `calls-for-speakers` and in some places a relationship as `call-for-speakers`. 
- So, we need a name that is both data friendly and at the same time makes sense. 

I suggest `speakers-calls`. So we can use both singular and plural forms of it without any confusion and change of meaning. 

@fossasia/open-event-server-devs your opinion ?

**Comment by SaptakS** [comment]
Sounds good to me.

**Comment by shubham-padia** [comment]
Sounds good.

**Comment by enigmaeth** [comment]
@niranjan94 @SaptakS @shubham-padia 
What should `event-cfs` be renamed to?
It has occurrences in `app/helpers/` and `app/old_api`.

**Comment by niranjan94** [comment]
What is event-cfs ?
Ignore occurrences in `app/old_api`

**Comment by enigmaeth** [comment]
@niranjan94 
It is in `data.py` [here](https://github.com/fossasia/open-event-orga-server/blob/nextgen/app/helpers/data.py#L300).

Also what about occurences in `app/templates`?

**Comment by niranjan94** [comment]
@enigmaeth that's just a template reference. Please wait until #3766 is done.

**Comment by SaptakS** [comment]
@niranjan94 @enigmaeth I think changing it in the models and api files is enough. We really don't need to change it in (or be concerned with) helpers files, since they will anyways be remade when and how needed by API.

**Comment by enigmaeth** [comment]
@SaptakS @niranjan94 Should I make the PR with changes in API and models? Or we wait till the new interface is done( #3766)?

**Comment by niranjan94** [comment]
@enigmaeth please wait until #3766 is done.

**Comment by SaptakS** [comment]
@niranjan94 @enigmaeth I think now it is safe to do this issue.

**Comment by mariobehling** [comment]
The usual term is "Call for Speakers". In order to optimize for SEO probably "call-for-speakers" would be good.

**Comment by niranjan94** [comment]
@mariobehling this is only for internal reference to handle singular and plural resources better. User facing is still 'call for speakers'. So no issue with SEO

**Comment by enigmaeth** [comment]
Closed via #3799.
