### ISSUE TITLE
Remove timezone field from call for speakers model and API

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3759]
Call for speakers will use the timezone of the event.

**Comment by shubham-padia** [comment]
@niranjan94 Should this be done after #3739 , considering old data that is already using the timezone field. 
Or is it not that necessary, as at the time of nextgen switch, it does not matter if the cfs times for closed events has changed?

**Comment by niranjan94** [comment]
@shubham-padia yep. Do be done after #3739. 

As for the old data, I checked and found out everyone just uses the event timezone (since that is autoselected in the wizard anyway). So, wouldn't be an issue.
