### ISSUE TITLE
Add Missing fields in Ticket API, rename fields of Tax api and models, fix field in microlocation API

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#3762]
Ticket API: [(comment)](https://github.com/fossasia/open-event-orga-server/pull/3690#pullrequestreview-43149016)
   Missing fields-

- sales_starts_at
- sales_ends_at
- tags
- is_hidden

Tax API: [(comment)](https://github.com/fossasia/open-event-orga-server/pull/3745#pullrequestreview-43147843)
- tax_name --> name
- tax_rate --> rate
- is_invoice_sent --> should_send_invoice

Microlocation API: [(comment)](https://github.com/fossasia/open-event-orga-server/pull/3710/files)
- fix endpoint relationship to `sessions` instead of `session` and possibly all other models
- import event

**Comment by niranjan94** [comment]
> fix endpoint relationship to sessions instead of session

@magdalenesuo also could check all other models to make sure it fine everywhere ?

**Comment by magdalenesuo** [comment]
@niranjan94 hello, for ticket_tag, should I make a separate Api for this too?

**Comment by niranjan94** [comment]
@magdalenesuo yes. That would be better. We need the ability to pick tickets by tag too in future.

**Comment by magdalenesuo** [comment]
@niranjan94 Should I submit the API in the same PR or continue in a different issue?

**Comment by niranjan94** [comment]
new PR

**Comment by magdalenesuo** [comment]
Closing, will continue in #3788 3788
