### ISSUE TITLE
Disable existing UI and create a simple CRUD interface using Flask-Admin

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3766]
Nextgen branch is under going a lot of refactor related to database fields and doesn't make sense to continue to maintain the old frontend anymore in the nextgen branch. 

Please _disable_ the old frontend and create a very simple basic CRUD interface to all the models using [Flask-Admin](https://flask-admin.readthedocs.io/en/latest/). (No customisation needed. Just the out-of-box CRUD interface provided by the library should do )

**Comment by shubham-padia** [comment]
@niranjan94 Should I delete the old templates and views or move them elsewhere ?

**Comment by poush** [comment]
@shubham-padia Can we archive them to some folder like ```old_api``` ? Those views might be helpful when creating any complex logic in APIs.

**Comment by shubham-padia** [comment]
@poush Okay.
@niranjan94 Only login, without register, forgot password, etc should be okay right ?

**Comment by niranjan94** [comment]
Yep.

**Comment by niranjan94** [comment]
@shubham-padia as poush pointed out, create a directory called as `vintage` and move the old_api folder into it (call it as api), move the old templates, views, helpers, bower.json, package.json also into it. 

Then for the Flask-admin interface, just use the default bootstrap 3 styles (loaded via the bootstrap CDN. Flask-admin already does that by default I guess)

**Comment by shubham-padia** [comment]
closed via #3786
