### ISSUE TITLE
Relationship missing between Session and Event

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3779]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

There should be a relationship between session and event. Sessions always belong to a particular event.

**Comment by shubham-padia** [comment]
closed via #3794
