### ISSUE TITLE
[Discussion] Best way to implement permission system for APIs

### ISSUE THREAD

**Issue by poush** [fossasia/open-event-orga-server#3787]
Currently, the decorators are created to filter the permissions according to kwargs but that will not be good as different views/routes will use same decorators but will have different ```kwargs``` id ( like event_id, or just id in some case ) 

There should be some better way to implement the permission system. flask-rest-jsonapi provides a permission manager system to implement same. http://flask-rest-jsonapi.readthedocs.io/en/latest/permission.html

Here for each request, the custom ```permission_manager``` will be called to which we can provide custom kwargs as well. This will allow us to easily set custom rules as well.

Also, I tried implementing it for one view. There will be one refactor required. 
The API initialization code will be moved to separate module like ```app\api\bootstrap.py```
so that ```api``` initialized module can be included in APIs(required to use as decorator) files and routes will remain there at ```__init__.py``` importing the module ```api``` from ```app\api\bootstrap.py```

Please suggest if we should move into it or not.

**Comment by niranjan94** [comment]
@fossasia/open-event-server-devs please give in your comments here

**Comment by shubham-padia** [comment]
@poush Looks good, but since the documentation is sparse, cannot say how this will play out. What we can do is implement it for jwt_required, is_admin, is_super_admin in the first PR  for this, see how that turns out and move forward. What do you say ?

**Comment by poush** [comment]
Seems Good. We can see how implementation goes with our need in APIs.
