### ISSUE TITLE
Fix API Doc POST response to 201 instead of 200 and add 'type' field for Image_size in api doc

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#3789]
- Please correct API Doc POST response to 201 instead of 200
- Add 'type' field for Image_size in api doc
- Change image_size descriptions: 'full-aspect (string)','icon-aspect (string)', 'thumbnail-aspect (string)', 'string' to Boolean.

**Comment by poush** [comment]
Completed via #3796
