### ISSUE TITLE
RESTplus APIs 

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#379]
RESTplus GET APIs have been created [link](https://github.com/fossasia/open-event-orga-server/pull/373). I've created a separate blueprint instead of putting it inside the views module. The blueprint is registered as API version2 (for now, so it doesn't conflict with api.v1). You can get the Swagger docs at [127.0.0.1:8001/api/v2](http://127.0.0.1:8001/api/v2/) and the corresponding swagger config at [127.0.0.1:8001/api/v2/swagger.json](http://127.0.0.1:8001/api/v2/swagger.json).

Regarding the discussion about what should be the correct status codes for responses: Taking Track for example:

`/api/v2/events/2/tracks`: If event does not exist, it will return a 404. If event exists, a list of tracks with 200 is returned. If tracks for the event do not exist, an empty list is returned.

`/api/v2/events/2/tracks/4`: Same goes for this. If any of the two ids do not exist for the respective models, a 404 is returned. But if both the ids exist and the track id is not associated with that event id (track belongs to different event), a 400 Bad Request is returned with the message: "Object does not belong to event" [code](https://github.com/fossasia/open-event-orga-server/blob/0f57cc5832e925351d4a5c573670effaa6a5a3da/open_event/api/helpers.py#L42) (pardon the grammar). I've added tests for the same.

I've created a separate module for api tests, it will help group them. Some work still needs to be done. Like the response messages for errors, that just includes a message. The api helper functions can also be improved.

**Comment by aviaryan** [comment]
Great work @shivamMg .. flask-restplus is awesome .

> Like the response messages for errors, that just includes a message

What exactly more needs to be done here ?

**Comment by shivamMg** [comment]
@aviaryan Right now the error response just contains a message. We can make a custom error message structure with more fields. I've explained it here: https://github.com/fossasia/open-event-orga-server/issues/391
