### ISSUE TITLE
Enhance user model/api

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3795]
**Rename fields:**

- [ ] `avatar` -> `avatar_url`
- [ ] `firstname` -> `first_name`
- [ ] `lastname` -> `last_name`
- [ ] `facebook` -> `facebook_url`
- [ ] `twitter` -> `twitter_url`
- [ ] `instagram` -> `instagram_url`
- [ ] `google` -> `google_plus_url`
- [ ] `thumbnail` -> `thumbnail_image_url`
- [ ] `small` -> `small_image_url`
- [ ] `icon` -> `icon_image_url`
- [ ] `avatar` -> `original_image_url`

**Remove fields:**

- [ ] `avatar_uploaded` -> remove. no use. 
- [ ] `signup_at` -> remove. `created_at` provides the same data.

**Handle image resizing and save:**

When ever `original_image_url` changes (ignore any changes to `small_image_url`, `thumbnail_image_url`, `icon_image_url`), download, resize it appropriately, upload it back to the storage and update `small_image_url`, `thumbnail_image_url`, `icon_image_url` fields with the new URLs

**Comment by SaptakS** [comment]
@niranjan94 I think the handling image resizing will be done in #3738

**Comment by niranjan94** [comment]
From #3738

> When you process the data, if that URL has changed from what was before, do what you have to do to the image. Download from the URL. Process it. Store in different sizes. Get the new URLs for the different sizes. Add that info to the other image url fields.

This should be handled individually in each model/api

**Comment by poush** [comment]
Closed via #3812
