### ISSUE TITLE
Ensure basic endpoints are accessible without authentication

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3802]
### Event-related endpoints

- [x] Getting a list of events & details about a single event
- [x] Getting a list of sessions of an event and the details about a single session
- [x] Getting a list of microlocations of an event and the details about a single microlocation
- [x] Getting a list of tracks of an event and the details about a single track
- ~Getting a list of speakers of an event and the details about a single speaker~ [ Edited by Piyush: This need to be done separately since speakers API isn't ready yet ]
- [x] Getting a list of tickets of an event and the details about a single tickets
- [x] Getting call for speakers info of an event
- [x] Getting copyright info of an event

### Other endpoints
- [x] Getting settings (all fields except all client IDs, access tokens, secrets, passwords, email settings). But note, `stripe-publishable-key` is required.
- [x] Getting pages list & detail

**Comment by poush** [comment]
I think requires the permission manager to be completed before this.

**Comment by niranjan94** [comment]
@poush updated the description

**Comment by niranjan94** [comment]
@poush what is the progres on this ?

**Comment by poush** [comment]
Almost complete. Just need to check some end points. Also, since sessions API isn't implemented yet so that part is left.

**Comment by poush** [comment]
Cool, so we have now `has-PR` label :D

**Comment by niranjan94** [comment]
@poush looks like this hasn't been done for event relationships ? 

Eg. like `https://api.eventyay.com/v1/events/1/microlocations`

**Comment by niranjan94** [comment]
@poush any updates ?

**Comment by shubham-padia** [comment]
`sponsors` api still remaining as pointed out by @Princu7

**Comment by Shailesh351** [comment]
https://api.eventyay.com/v1/events/69/social-links
https://api.eventyay.com/v1/events/69/session-types
https://api.eventyay.com/v1/events/69/event-type
https://api.eventyay.com/v1/events/69/discount-codes
https://api.eventyay.com/v1/events/69/relationships/speakers-call

https://api.eventyay.com/v1/sessions/2823/session-type

This requests also requires authentication. Fix it also.

**Comment by niranjan94** [comment]
discount codes will need authentication and accessible only to event admins. We don't want someone just enumerating all the discount codes in the system and using them. 

For discount codes, we'll need two new endpoints with only JWT check.
`/v1/events/<id>/discount-codes/<discount-code>`
`/v1/discount-codes/<discount-code>`

For the rest of the endpoints, 
`/v1/events/<id>/discount-codes/*` - accessible only to event admin
`/v1/discount-codes` - accessible only to super admin
`/v1/discount-codes/<id>` - if type=ticket, accessible only to event admin. If type=event, accessible only to super admin

**Comment by poush** [comment]
@niranjan94 
aren't these two endpoints are same 
/v1/events/<id>/discount-codes/<discount-code>
/v1/discount-codes/<discount-code>

Since DiscountCode model is associated with events therefore we can easily check for the permission without the need of event_id in url

**Comment by niranjan94** [comment]
@poush there are two different kinds of discount codes sharing the same model. See https://github.com/fossasia/open-event-orga-server/issues/3911

**Comment by poush** [comment]
@niranjan94 Please see if I'm correct here,

For only super admin we will have routes

DiscountList
=>  /v1/discount-codes [GET]
=> /v1/discount-codes [POST]

DiscountDetail
=> /v1/discount-codes/<id> ( with type=event)

**Comment by poush** [comment]
@niranjan94 Please see if I'm correct here,

For only super admin we will have routes

DiscountList
=>  /v1/discount-codes [GET]
=> /v1/discount-codes [POST]

DiscountDetail
=> /v1/discount-codes/<id> ( with type=event) [GET, PATCH, DELETE]

For Event Admin and super admin

DiscountList
=> /v1/events/<id>/discount-codes [GET and POST]

Discount Detail
=> /v1/discount-codes/<id> (type=ticket)  [GET, PATCH, DELETE]

For everyone logged in 

DiscountDetail
=> /v1/discount-codes/<discount-code>

Also what I am trying to say in the case of
```
/v1/events/<id>/discount-codes/<discount-code>
/v1/discount-codes/<discount-code>
```
is that both uses <discount-code> for same method which is not allowed in JSON API

**Comment by niranjan94** [comment]
> is that both uses < discount-code > for same method which is not allowed in JSON API

They both refer to the same resource right ?

**Comment by poush** [comment]
Yes, to DiscountDetail

**Comment by niranjan94** [comment]
So ... what's the confusion here ?

**Comment by poush** [comment]
I cannot use < discount-code > in two endpoints points to same resource.

```
File "/Users/Agrawal/projects/open_source/open-event-orga-server/ENV/lib/python2.7/site-packages/werkzeug/routing.py", line 202, in parse_rule
    raise ValueError('variable name %r used twice.' % variable)
ValueError: variable name 'discount_code' used twice.
```

**Comment by niranjan94** [comment]
Change the variable name to id 😅  .. Please don't take the endpoint vars I give literally ... It's just for reference

**Comment by niranjan94** [comment]
This really did not require such a long discussion

**Comment by poush** [comment]
@niranjan94 Before working on DiscountCodes API permissions as you described #3911 has to be completed. I have partial code ready here and will complete it as soon #3911 get done

**Comment by Princu7** [comment]
Hi. Thanks for implementing the Speakers API :) It seems that the basic endpoints like for getting information regarding the speakers of an event are not working without the access token. I tried a call to this URL: http://open-event-api.herokuapp.com/v1/events/69/speakers
Please see to it. Thanks!!
