### ISSUE TITLE
Enhance event model/api

### ISSUE THREAD

**Issue by poush** [fossasia/open-event-orga-server#3807]
**Rename fields in model:**

- [x] `logo` => `logo_url`
- [x] `thumbnail` => `thumbnail_image_url`
- [x] `large` => `large_image_url`
- [x] `icon` => `icon_image_url`

**Add/Change fields in api:**
- [x] `thumbnail_image_url` => read_only
- [x] `large_image_url` => read_only
- [x]  `icon_image_url` => read_only
and add
- [x] `original_image_url`

**Handle image resizing and save:**

Whenever original_image_url changes then download it, resize it appropriately, upload it back to the storage and update `large_image_url`, `thumbnail_image_url`, `icon_image_url` fields with the new URLs.

**Comment by niranjan94** [comment]
@poush also add a new field called as `original_image_url` 

Whenever original_image_url changes then download it, resize it appropriately, upload it back to the storage and update `large_image_url`, `thumbnail_image_url`, `icon_image_url` fields with the new URLs. 

Be sure to do the resizing as per the image size setting

**Comment by poush** [comment]
`original_image_url` isn't similar to `large_image_url` or we will enlarge the original image for large_image ? Also `original_image_url` will be added to API as well right?

**Comment by niranjan94** [comment]
large, thumbnail and icon image have fixed sizes defined by the admin. If original image is smaller, it is expanded.

**Comment by niranjan94** [comment]
Yes. Original_image_url will be added to api. And in api ensure, large_image_url, thumbnail_image_url, icon_image_url are read-only

**Comment by poush** [comment]
Closed via #3814
