### ISSUE TITLE
Allow event identifier to be used in the place of ID throughout all API Endpoints

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3808]
In some places, we still have only endpoints right `/events/<int:event_id>/speakers` but we also need `/events/<event_identifer>/speakers`. Ensure anywhere there is `<int:event_id>` in the endpoint, there is also an endpoint that accepts identifier.

**Comment by niranjan94** [comment]
@enigmaeth there has been no PR for this issue yet. What's the progress ? This was a part of last week's milestone.

**Comment by enigmaeth** [comment]
I am working on it. I will make a PR very soon. Sorry for the delay.

**Comment by enigmaeth** [comment]
@niranjan94  I have added event_identifier along with event_id [here](https://github.com/enigmaeth/open-event-orga-server/commit/858833826b3d8235a5723aa2b6818c24698b4d42). 
Some endpoints like event_invoice are using event_id in list and and they already have event/<identifier> implemented for them. Should I change those to event_identifier? ( So wherever we have event_id, we will have event_identifier)?

**Comment by niranjan94** [comment]
@enigmaeth yes. we need to have both. If in anyplace we're using event ID, we should also be able to use event identifier.
