### ISSUE TITLE
Dragging error in Schedule UI

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#381]
If the session is dragged to the left beyond the calendar, the session is translated.
![screenshot from 2016-05-24 17 36 16](https://cloud.githubusercontent.com/assets/9530293/15503279/bd645f3a-21d6-11e6-95b2-720973582b91.png)

As we can see the session lies in an awkward position. We need to prevent this.

**Comment by niranjan94** [comment]
On it.

**Comment by SaptakS** [comment]
@niranjan94 though I am unable to drag it entirely out of the calendar but I can still drag it half-way through..
![screenshot from 2016-05-25 02 22 20](https://cloud.githubusercontent.com/assets/9530293/15519487/4fca97d4-221f-11e6-9197-feedef6400ce.png)

**Comment by niranjan94** [comment]
@SaptakS Sorry ... I missed a commit in the PR :sweat_smile: .
