### ISSUE TITLE
Implement validation across all existing apis

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3810]
Parent issue: #3765 
Implement validation from http://marshmallow.readthedocs.io/en/latest/quickstart.html#validation

**Comment by shubham-padia** [comment]
@SaptakS @magdalenesuo @niranjan94 
In cfs model, there is a field named `privacy`, what all values can it accept, 
every value in my db is currently set to 'public'

**Comment by niranjan94** [comment]
It can accept private or public.

**Comment by shubham-padia** [comment]
Is there any other possibility in the future, for another privacy type ?
Otherwise I'm making it boolean.
Same for discount_codes -> type which accepts 'percent' or 'amount' two values.
And any other I encounter further.

**Comment by niranjan94** [comment]
Keep it a string for now please. Both of them.

**Comment by shubham-padia** [comment]
Okay

**Comment by shubham-padia** [comment]
closed via #3819
