### ISSUE TITLE
Image saving and resizing for individual APIs

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3813]
#3738 ensures we have an endpoint where we can upload temporarily the images and send the temp URL link while POST or PATCH to an API for example events, users. The APIs need to now save the image from the temporary url, resize the images to different sizes and store the urls in db.

~To be done after #3738~ (Edit by @niranjan94)

**Comment by poush** [comment]
Related issues to understand how it will work:
#3807 
#3795

**Comment by niranjan94** [comment]
> To be done after #3738 

Need not be done after that. Can be done in parallel.

**Comment by SaptakS** [comment]
> Need not be done after that. Can be done in parallel.

It can be done taking any image url as parameter for testing.
