### ISSUE TITLE
Implement dredd for API testing and documentation validation.

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3825]
## [Dredd](https://github.com/apiaryio/dredd)

> Dredd is a language-agnostic command-line tool for validating API description document against backend implementation of the API.

Implement dredd for the nextgen branch and configure it with travis to run for every PR and cause test-fails if the dredd test fails.

**Comment by shubham-padia** [comment]
@niranjan94 Just to get this clear, the user has to setup another database for testing and mention it's url in an env variable like `TEST_DB_URL`, right ?

**Comment by niranjan94** [comment]
Yep. That would be preferred.

**Comment by shubham-padia** [comment]
Will be trying [factoryboy](https://factoryboy.readthedocs.io/en/latest/introduction.html) for db fixtures, please comment if you feel this is not beneficial.

**Comment by niranjan94** [comment]
That's nice. I think we could even replace the insanely long model
constructors with this and have more leaner and cleaner model files.
