### ISSUE TITLE
Implement TicketFees API with permissions

### ISSUE THREAD

**Issue by LuD1161** [fossasia/open-event-orga-server#3826]
API for model `TicketFees`.

Endpoints : 
**To get all the ticket-fees** : `/v1/ticket-fees`
**To get a ticket-fees by id** : `/v1/ticket-fees/<int:id>`

Parent [issue#3640](https://github.com/fossasia/open-event-orga-server/issues/3640)

**Comment by niranjan94** [comment]
@LuD1161 please add a description. Add a list of proposed endpoints etc. This is not the way to propose something. And also, the issue template is there just for this reason. Why would you ignore it ?

**Comment by niranjan94** [comment]
@LuD1161 please add _all_ the endpoints (including direct and relationships). Also, work on this _after_ #3771 and #3820

**Comment by LuD1161** [comment]
@niranjan94
Sure.
