### ISSUE TITLE
POST and PATCH not working in events, sessions and some other APIs

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3847]
**I'm submitting a ...**  (check one with "x")
- [x] bug report

**Current behavior:**

When PATCH an event it shows 
```
{
    "errors": [
        {
            "status": 500,
            "source": "",
            "detail": "'starts_at'",
            "title": "Unknown error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Expected behavior:**
However it should just rename the 1st event.

**Steps to reproduce:**
1. Create the event
2. PATCH it's name , don't give any of the keywords amongst these `starts-at` , `ends-at` or `timezone`.

**Related code:**
The code responsible for this
```
@validates_schema
    def validate_date(self, data):
        if data['starts_at'] >= data['ends_at']:
            raise UnprocessableEntity({'pointer': '/data/attributes/ends-at'}, "ends-at should be after starts-at")

    @validates_schema
    def validate_timezone(self, data):
        if 'timezone' in data['timezone']:
            offset = timezone(data['timezone']).tz.utcoffset(datetime.strptime('2014-12-01', '%Y-%m-%d')).seconds
```

**Other information:**
Possible solutions :
- Either it should be enclosed in `try/catch` block or
- Use proper way to get an object from dict type , like this .

```
    def validate_date(self, data):
        if data.get('starts_at') and data.get('ends_at'):
            if data['starts_at'] >= data['ends_at']:
                raise UnprocessableEntity({'pointer': '/data/attributes/ends-at'}, "ends-at should be after starts-at")

    @validates_schema
    def validate_timezone(self, data):
        if data.get('starts_at') and data.get('ends_at') and data.get('timezone'):
```
**System information:** 

```
Linux  #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
Python 2.7.12
```

**Comment by LuD1161** [comment]
@SaptakS 
There also needs to be a check like if only `starts-at` date is given in PATCH then it should be checked with the corresponding `ends-at` in the database , currently it is not being handled.

I will include it in .
