### ISSUE TITLE
Add paginated responses to api v2

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#385]
API v1 used to have paginated views which would give 20 items per page. 
Is the same needed to be done in API v2 ?
cc @juslee @shivamMg @leto 

EDIT - See https://github.com/fossasia/open-event-orga-server/issues/385#issuecomment-221485640

**Comment by shivamMg** [comment]
@aviaryan :+1: It would be needed. I searched restplus docs for pagination support, but it didn't have it. So we will have to create our own. 20 would be fine I guess.

**Comment by aviaryan** [comment]
I was looking at some pagination styles and how to correctly create paginated APIs. DRF has some ways [here](http://www.django-rest-framework.org/api-guide/pagination/), I like Page Number pagination the most. 
URL - ```https://api.example.org/accounts/?page=4```
Response - 
```
{
   "count: 20,
    "next": "https://api.example.org/accounts/?page=5",
    "previous": "https://api.example.org/accounts/?page=3",
    "results": [
       …
    ]
}
```

Another good one is Limit and offset based. 
```https://api.example.org/accounts/?limit=100&offset=400```
The offset is where to start returning the result from, limit is how many items to return.
This method will give control over the amount of data returned so it can help client apps utilize minimum bandwidth. 
I will first implement the PageNumber pagination, then the LimitOffset pagination.
