### ISSUE TITLE
Clicking "Export CSV" doesn't work

### ISSUE THREAD

**Issue by NinaNC** [fossasia/open-event-orga-server#3860]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
When clicking CSV in "Export CSV", nothing seems to happen. When looking at the logs I see that it tries to reach an API and tries to perform the same tasks over and over again. It results in {state:FAILURE}

**Expected behavior:**
Downloading a CSV file.

**Steps to reproduce:**
Log in, go to Attendees, try to export the CSV.

**Other information:**
PDF export works.

**System information:** 

Using Chromium.

**Comment by SaptakS** [comment]
@NinaNC I am checking into it.

**Comment by SaptakS** [comment]
Closed by mistake as I wrote `Fixed #3860` in PR

**Comment by SaptakS** [comment]
@NinaNC It is working now. Please check and confirm.

**Comment by NinaNC** [comment]
@SaptakS It works indeed! Thanks.

Suggestion: warn that you might need to allow pop up
