### ISSUE TITLE
Talks don't match their real duration on the scheduler

### ISSUE THREAD

**Issue by NinaNC** [fossasia/open-event-orga-server#3877]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Current behavior:**
When trying to schedule talks, they take more space than expected in the scheduler. For instance, if I try to schedule a 5 minutes talk, it is scheduled for a 15 minutes period on the scheduler. Also, they take a 15min slot on the scheduler.

**Expected behavior:**
5 minutes talks should only take a 5 min period on the scheduler, both visually and in terms of timing.

**Steps to reproduce:**
Create a 5 minutes talk. Go to scheduler and try to schedule it.

**Comment by NinaNC** [comment]
Apparently all the talks I try to schedule last 15 min, whether they should last 1 hour or 5 minutes

**Comment by SaptakS** [comment]
So just to get it clear, dragging in the scheduler to increase or decrease duration of a session works, but if you already have a session which is of a particular session type that lasts 30 minutes, it still shows 15 min in the scheduler. Am I correct?

**Comment by NinaNC** [comment]
Whatever the particular session type you have (5 minutes, 30 minutes, 1 hour), dragging it to the scheduler make it last 15 minutes on the scheduler. It doesn't change anything in the session itself, all sessions just appear as 15 minutes sessions on the scheduler.
Let me know if you need more information!

**Comment by NinaNC** [comment]
Hi,
Any news on this? Or any workaround? We would need to publish our schedule and it's difficult to do it with 15-minute sessions only :sweat_smile: 

Thanks!

**Comment by SaptakS** [comment]
@NinaNC there is a workaround. You can drag and drop the session on the scheduler at the beginning time of the session. Then pull the lower boundary of the session, this will automatically increase the time span to whatever span you have selected.

![](https://im3.ezgif.com/tmp/ezgif-3-584e320db9.gif)

**Comment by SaptakS** [comment]
I am working on the fix however.

**Comment by NinaNC** [comment]
@SaptakS thanks, will try that!

**Comment by SaptakS** [comment]
@NinaNC the fix should be done by a day as well.
