### ISSUE TITLE
add tax api to dredd testing

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#3899]
parent issue: #3870

**Comment by niranjan94** [comment]
Also @shubham-padia could you rename and API fields and DB

- `tax-name` -> `name`
- `tax-rate` -> `rate`
- `is-invoice-sent` -> `should-send-invoice`

**Comment by shubham-padia** [comment]
Sure, im afk right now, will have a look later

**Comment by shubham-padia** [comment]
@niranjan94 Can you recheck. All those changes have been already done :)

**Comment by shubham-padia** [comment]
@SaptakS @niranjan94 What is the purpose of `tax_id` in the the tax model, I tried but can't seem to find anywhere.

**Comment by niranjan94** [comment]
@shubham-padia tax ID is something the government issues for a company. Also called as TIN (Tax identification number).
