### ISSUE TITLE
Event can't be created using API

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#3909]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Right now creating an event gives an error `'NoneType' object has no attribute 'seconds'`

**Comment by niranjan94** [comment]
@SaptakS why was this closed ?

**Comment by SaptakS** [comment]
@niranjan94 it was a mistake on my part of testing. I wasn't sending the date in the correct format. 😥

**Comment by niranjan94** [comment]
:smile:
