### ISSUE TITLE
Enhance the discount code API

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3911]
Two different forms of discount code can exist. (Both use the same model). Can be known by using the `used_for` column. Can have two values (`ticket` or `event`)

1. Created by the super admin and can be applied to whole events when creating an event. (this discount is on the total ticket fees that goes to eventyay). 
    1. API should be at `/v1/discount-codes`
    2. Should have a relationship `events` that returns all the events that use this discount code. (can be obtained by using `discount_code_id` field in event model.
2. Created by an event's organizer to be used on that event's tickets
    1. API is already present at `/v1/events/{event_identifier}/discount-codes`
    2. Should have two relationships.
        1. `event` - gives the event that this discount code belongs to (can be obtained by using `event_id` field in discount code model
        2. `orders` - gives all the orders that use this discount code (can be obtained by using `discount_code_id` field in the order table)

**Comment by magdalenesuo** [comment]
@niranjan94 Presently the discount api has this field 
`type = fields.Str(validate=validate.OneOf(choices=["amount", "percent"]), allow_none=True)`

>Two different forms of discount code can exist. (Both use the same model). Can be known by using the type column. Can have two values (ticket or event)

Should I make a different `type` field with a different name in that case to select from 'ticket' and 'event'?

**Comment by niranjan94** [comment]
> Two different forms of discount code can exist. (Both use the same model). Can be known by using the type column. Can have two values (ticket or event)

Sorry .. I meant `used_for` column
