### ISSUE TITLE
POST request for creating a new event results in error code 500

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#3922]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

On following the docs, and trying to create a sample event, it results in this 
![image](https://user-images.githubusercontent.com/17252805/27755652-99c9bb40-5e0e-11e7-8603-49242a422905.png)

**Steps to reproduce:**

The parameters I used for POST request 
URL : `https://open-event-api.herokuapp.com/v1/events`
### Headers 
Content-Type: `application/vnd.api+json`
Authorization:  `JWT <token>`

The sample event in the Docs for body.

**Comment by niranjan94** [comment]
Should work now,.
