### ISSUE TITLE
Events routes not working on heroku instance

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#3935]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

`https://open-event-api.herokuapp.com/v1/events`
results in an 500 error code after recent PR merge

**Comment by shubham-padia** [comment]
@niranjan94 Can you check the logs please :)

**Comment by shubham-padia** [comment]
nvm, the error second time was due to invalid data inputted through flask-admin, fixed by @CosmicCoder96 himself.
