### ISSUE TITLE
Provide a proper error message HTTP Status code when trying to create a user who already exists.

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3942]
Currently, if we try to create a user with an email ID that is already in the database, we get an `Internal Server Error` with a status code of `500`. 

Instead, provide a proper error message along with a status code of `409 Conflict`.

**Comment by shubham-padia** [comment]
@niranjan94 This is specific to users table, right ?
If that's the case I'll simply put a check if the user with the given email exists or not and raise relevant exceptions.

**Comment by niranjan94** [comment]
Yep. Specific to the users table.
