### ISSUE TITLE
Setup a basic ETags implementation for API.

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3950]
> An entity tag (ETag) is an HTTP header used for Web cache validation and conditional requests from browsers for resources.

**References:**

- http://fideloper.com/api-etag-conditional-get
- http://flask.pocoo.org/snippets/95/
- https://stackoverflow.com/a/14690307

**Why do we need this ?**

- Clients can make use of this and request complete data if and only if the data has changed else use their local cache.
- This can be used to ensure concurrency in the case of multiple clients trying to modify the same data at the same time.

**Comment by shubham-padia** [comment]
@niranjan94 I've implemented Etags on the dev branch for now: https://github.com/shubham-padia/flask-rest-jsonapi/commit/9a961e4d145fd6516d1a9e82474efc15e811dc6e

Please see the following points, if these seem okay i'll push to master:
- Use `ETAG` is app config to turn it off and on 
- Using sha1, strict no-collision policy will be overkill here I think
- Return 412 if `If-Match` doesn't match
  ```
  {
    "errors": [
        {
            "status": 412,
            "source": {
                "pointer": ""
            },
            "detail": "Precondition failed",
            "title": "Precondition Failed"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```
- Return 304 not modifed, if tag does not match any tag given in `If-None-Match`

**Comment by niranjan94** [comment]
@shubham-padia can we have a test deployment of the server with ETags ? I'd like to test this ...

**Comment by shubham-padia** [comment]
@niranjan94 can you test with this,
http://orga2.herokuapp.com/v1/image-sizes, my migrate dynos are not running
for some reason

On Tue, Jul 4, 2017 at 1:00 PM, Niranjan Rajendran <notifications@github.com

**Comment by niranjan94** [comment]
@shubham-padia ... You can use `heroku run bash --app=orga2` to run the migration manually. I want to create data and see how the ETags behave.

**Comment by shubham-padia** [comment]
@niranjan94 The deployment is working again, can you check :)

**Comment by niranjan94** [comment]
@shubham-padia works perfect. 👍 Go ahead
