### ISSUE TITLE
Error while opening the psql shell

### ISSUE THREAD

**Issue by kunalchamoli** [fossasia/open-event-orga-server#3965]
**Current behavior:**

psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Related code:**

```
sudo -u postgres psql
```

Your operating system
```
Kali GNU/Linux Rolling 64-bit
```
output of `python --version`
```
Python 2.7.13

**Comment by aviaryan** [comment]
Postgresql service might no be running, that's why you are getting that error.
Please try. 

```sh
sudo service postgresql start
# or
sudo service postgresql restart
```
Also please try to post issues like this on the [Gitter channel](https://gitter.im/fossasia/open-event-orga-server) first. It's more active and you are likely to get a quick solution there.

**Comment by kunalchamoli** [comment]
Thanks @aviaryan.
