### ISSUE TITLE
500 Server error on Heroku

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#3967]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Most of the routes including events are returning a 500 Error on https://open-event-api.herokuapp.com
![image](https://user-images.githubusercontent.com/17252805/27846349-48f08390-6154-11e7-8892-df388f051664.png)
Maybe a migration issue again.

**Steps to reproduce:**

Make a GET/POST request to events route

**Comment by niranjan94** [comment]
Resolved. Migration issue.
