### ISSUE TITLE
Possibility to get ordered tickets informations (ticket_id,event_id) using the API

### ISSUE THREAD

**Issue by lucasruchel** [fossasia/open-event-orga-server#3975]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
API returns User Informations, but don't display tickets that the user ordered.

**Expected behavior:**
Return in API the user ordereds tickets with it's respective event_id

**Comment by shubham-padia** [comment]
Currently user can check which events he/she is attending, thus closing this
