### ISSUE TITLE
[Discussion] Adding endpoints to docs and dredd test

### ISSUE THREAD

**Issue by enigmaeth** [fossasia/open-event-orga-server#3980]
@fossasia/open-event-server-devs 

Shouldn't these endpoints too be added to docs and dredd test?
`/microlocations/<int:microlocation_id>/sessions/`,
`/tracks/<int:track_id>/sessions`,
 `/session_types/<int:session_type_id>/sessions`,
 and the likes. 

In docs for each Resource we have two endpoints [ GET and POST ] for list and `/<resource_type>/<int:resource_id>` 's three endpoint [GET, PATCH, DELETE] but we have many more endpoints implemented. Also what about the relationship endpoints?

**Comment by poush** [comment]
Please correct me I'm wrong anywhere. 
Dredd testing is for API docs and API docs describe the URI for differents resources but the endpoints you mentioned are all related endpoints. Frontend will get to know about this in related attribute in the response object so I guess there is no point of adding them into docs and if we can't add them in docs then no way to add in testing.

**Comment by shubham-padia** [comment]
@enigmaeth Looks like the intention here is adding this for dredd test, which does not make sense, please dont confuse it with unit testing.

@niranjan94 Can you confirm whether this is required by the clients for the docs, what are the general conventions in real world about this, are these type of endpoints documented ??

**Comment by enigmaeth** [comment]
No, I am not asking about adding them to unit tests, but to the docs.
Check comment [here](https://github.com/fossasia/open-event-orga-server/pull/3973#discussion_r125866047). @shubham-padia

**Comment by niranjan94** [comment]
@shubham-padia actually ... we need endpoints like `/session_types/<int:session_type_id>/sessions` in docs. (that's how it is). The relationship endpoints can be skipped.

**Comment by enigmaeth** [comment]
Closing in favor of #4009.
