### ISSUE TITLE
500 Error on Events Route

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#4001]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

![image](https://user-images.githubusercontent.com/17252805/27999441-c15f5e7a-653a-11e7-9adf-014ba8ebfe41.png)

**Steps to reproduce:**

*GET* `https://open-event-api.herokuapp.com/v1/events`

**Comment by niranjan94** [comment]
Resolved. Migration issue.

**Comment by niranjan94** [comment]
Any more such errors with SQL errors in them, please post it on the channel first.
