### ISSUE TITLE
Implement general event analytics API

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#4007]
Implement event analytics API for the event organizer dashboard, 
General bulk data about event should be provided by event id/identifier

@niranjan94 Please suggest Url and required fields for this one issue only, any other issues may follow the same pattern

**Comment by shubham-padia** [comment]
@niranjan94 Can you please have a look at this :smile:

**Comment by iamareebjamal** [comment]
May I suggest some general fields we have to calculate for the Android Orga App?

- Total Tickets per type
- Sold Tickets per type
- Checked in Attendees
- Total Attendees
- Total Sales and by Type
