### ISSUE TITLE
Add inter-related resource endpoints to docs

### ISSUE THREAD

**Issue by enigmaeth** [fossasia/open-event-orga-server#4009]
Add endpoints like 
`/microlocations/<int:microlocation_id>/sessions/`,
`/tracks/<int:track_id>/sessions`,
`/session_types/<int:session_type_id>/sessions`,
to docs. 

Child issues can be opened.

**Comment by shubham-padia** [comment]
This issue is kept on hold due to #4076

**Comment by shubham-padia** [comment]
#4101 is almost complete, only two issues remaining, this can be kept out of hold now

**Comment by enigmaeth** [comment]
@fossasia/open-event-server-devs @niranjan94 All the inter-related endpoints have been added to docs and dredd tests :) , closing this!
Any new endpoint to be added(except relationship endpoints) must have docs and dredd tests added along with it.
