### ISSUE TITLE
Error 500 for events route on nextgen API

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-orga-server#4011]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
The events route returns error 500 on https://open-event-api.herokuapp.com/#events
![screenshot from 2017-07-11 03-22-26](https://user-images.githubusercontent.com/12807846/28041806-69949652-65e8-11e7-82b5-7c18ab2035d4.png)

**Comment by niranjan94** [comment]
Resolved. Migration issues. Post such errors with queries in them to the server channel instead.
