### ISSUE TITLE
Add option to access events organised by authenticated user

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-server#4082]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently, there is no way to access events organized by an authenticated user.

**Expected behavior:**
There should be a relationship with user to the events he manages

**Comment by poush** [comment]
@iamareebjamal This is already there with a get parameter, please try sending the same request **?withRole=1**
