### ISSUE TITLE
Add seperate resourcelist class, docs, permissions for direct  endpoints

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#4101]
Right now most of the direct endpoints which were related give permission denied due to permission manager using view kwargs. A seperate resourcelist class has to be added for endpoints like `/tickets`, and permission functions have to be added to a new file permission_func.py, because decorators cant be used here, the check will be applied in the before post section

**Comment by poush** [comment]
I guess `has_access` method can be used where decorators can't be used. It solves the same purpose.

**Comment by shubham-padia** [comment]
Closing this
