### ISSUE TITLE
Save each session change/update using the API

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#412]
Anytime a session is rescheduled (move or resize) with the scheduling UI, the updated timings and track has to be stored to the database. This can be implemented by making an API Call on each change.

**Comment by rafalkowalski** [comment]
@juslee @SaptakS it can be difficult, because API is changing in master branch(I don't know why @aviaryan ) So we need to make merge ASAP(I've added ticket #415 to milestone 3)

**Comment by SaptakS** [comment]
@rafalkowalski Yes.. So maybe we will need to do this after merging... That is the reason I added milestone 3 to this as well..

**Comment by aviaryan** [comment]
> because API is changing in master branch(I don't know why @aviaryan )

API v2 is made using Flask-restplus. It also auto generates Swagger specification and docs. It is much better suited for our needs. Btw, just so you know, the old API (v1) is still **fully functional**.

**Comment by SaptakS** [comment]
@rafalkowalski @juslee can the branches be merged asap? I can't work on this issue as long as the branches are not merged..
