### ISSUE TITLE
DELETE request for ticket returns 404

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-server#4121]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
DELETE request for a ticket takes about 5 seconds and returns a 404 instead of 200, but successfully deletes the ticket.

**Expected behavior:**
DELETE should return 200 for valid resource

**Steps to reproduce:**
DELETE http://open-event-api.herokuapp.com/v1/tickets/27

Response:
````json
{
    "errors": [
        {
            "source": {
                "source": ""
            },
            "status": 404,
            "title": "Not Found",
            "detail": "Object not found."
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
````

**Comment by poush** [comment]
@iamareebjamal Are you sure ticket exists by going through the GET request to that URL as I'm not able to reproduce this here on nextgen branch.

**Comment by iamareebjamal** [comment]
@poush I'll test again. Though I confirmed for the same the last time I tried

**Comment by iamareebjamal** [comment]
@poush Still happening. Tried on ticket 37 and 38, have created another one -> 

http://open-event-api.herokuapp.com/v1/tickets/39

GET is 200 with correct data
DELETE is 404 in any case

**Comment by poush** [comment]
<img width="1217" alt="screen shot 2017-07-23 at 12 52 14 pm" src="https://user-images.githubusercontent.com/1812082/28497477-cbc109d4-6fa5-11e7-8eb4-15f117a95ce5.png">

**Comment by iamareebjamal** [comment]
Strange. Maybe a bug in Postman. I'll close this

**Comment by poush** [comment]
@iamareebjamal Try run curl
```
curl -X "DELETE" "http://open-event-api.herokuapp.com/v1/tickets/39" \
     -H "Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MDA3MjYyMTcsImV4cCI6MTUwMDgxMjYxNywibmJmIjoxNTAwNzI2MjE3LCJpZGVudGl0eSI6MTE3fQ.mZ4rssHYGfK5VarWoYzNBfiZNm183x5RB7RwUMmalio"
```

**Comment by iamareebjamal** [comment]
Yep. Working correctly. Thanks :+1:
