### ISSUE TITLE
Fix email notifications endpoint

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#4125]
The current email notifications endpoint implementation is completely wrong. It should only have a GET and a PATCH endpoint. To be implemented similar to the settings endpoint.

`GET /v1/email-notifications`
`PATCH /v1/email-notifications`

Accessible only to super admin/admin.

**Comment by SaptakS** [comment]
@niranjan94 but the email notification is a setting for user, right? Any user can set his/her preference of which emails they want and which they don't. Why only super admin and admin?

**Comment by niranjan94** [comment]
Oh yea. My bad.
