### ISSUE TITLE
Unable to update the user info via patch request.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-orga-server#4126]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
I am trying to update the user info of 'email', 'phone' by sending a patch request at 'https://open-event-api.herokuapp.com/users/<user_id>' but it's giving me 'Unknown error'. I also tried to send it by postman with the same access token so that I can override the info, still I am getting the same error. Following are the screenshots:
![patch](https://user-images.githubusercontent.com/17925669/28453862-972563a4-6e16-11e7-889d-236cb472be84.png)
![patch2](https://user-images.githubusercontent.com/17925669/28453867-9976d994-6e16-11e7-9f82-b17d8c3f7aec.png)
![patch3](https://user-images.githubusercontent.com/17925669/28453912-d21cc7cc-6e16-11e7-83ae-e3040c7c898d.png)

URL: https://open-event-api.herokuapp.com/v1/users/110
Request headers: 
```
Content-Type: application/vnd.api+json
Authorization: JWT <Auth Key>
```
Response:
```
{
    "errors": [
        {
            "detail": "Unknown error",
            "source": {
                "pointer": ""
            },
            "status": 500,
            "title": "Unknown error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```
Status code: 500

**Comment by enigmaeth** [comment]
Don't include email in the patch body.

**Comment by niranjan94** [comment]
@enigmaeth email is editable.

**Comment by enigmaeth** [comment]
@niranjan94 Currently, editing email through PATCH requests throws an error. ( [user model](https://github.com/fossasia/open-event-orga-server/blob/nextgen/app/models/user.py#L112) ). Should this be changed to make email editable?

**Comment by sumedh123** [comment]
@enigmaeth Removing email from the request body gives correct response.

**Comment by enigmaeth** [comment]
Yes, that is because email is not editable currently. @niranjan94 Should it be allowed to be editable?

**Comment by enigmaeth** [comment]
@shubham-padia @niranjan94 ^^?

**Comment by niranjan94** [comment]
Yes. It should be allowed. We had the feature in vintage.

**Comment by sumedh123** [comment]
@enigmaeth Let me know once you do the changes.

**Comment by poush** [comment]
@niranjan94 Actually in user model the attribute "email" is defined as getter & setter while setter only sets the value if it null so only works on creating new user. This method is there from vintage.

**Comment by enigmaeth** [comment]
@sumedh123 Issue resolved!
