### ISSUE TITLE
endpoint /notification/<id> and email-notification/<id> gives Access Denied error

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#4127]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

GET `notifications/<id>` and GET `email-notifications/<id>`

**Other information:**

Due to permission checking `user.id = kwargs['id']` for all `is_user_itself` decorator.
**Note:** In this case `id` is notification's id rather than user's id, so check condition is not valid

**Comment by niranjan94** [comment]
Also, email-notification should have a field named event id with which the user can set event-specific notification prefs

**Comment by magdalenesuo** [comment]
@niranjan94 I used relationship to update the event_id field. Should I add in schema too?
