### ISSUE TITLE
Schedule is broken

### ISSUE THREAD

**Issue by NinaNC** [fossasia/open-event-orga-server#4129]
**I'm submitting a ...**  (check one with "x")
- [ X] bug report

**Current behavior:**
Here is what the schedule page looks like at the moment
<a href="http://i.imgur.com/g90Kt6Z.png">
  <img src="http://imgur.com/g90Kt6Zl.png" />
</a>

**Expected behavior:**
I guess it should look better :D

**Steps to reproduce:**
Publish the schedule
Go to the conference page

```
Your operating system
tried on Chromium and FF

**Comment by NinaNC** [comment]
Hi, any news?

**Comment by enigmaeth** [comment]
@NinaNC The issue is fixed :) . Sorry for the late response.
