### ISSUE TITLE
Bugs in API Documentation

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#4130]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Under **settings** the following are incorrect/ have a typo
- awsBucket
- gsBucket
- tw-consumer-secre

**Expected behavior:**

- awsBucketName
- gsBucketName
- tw-consumer-secret

**Comment by S2606** [comment]
@CosmicCoder96 Could you tell where awsBucket and gsBucket is because i couldnt find them in api_blueprint.apib?

**Comment by magdalenesuo** [comment]
@S2606 Its under `settings` description
