### ISSUE TITLE
Fix roles invites API and remove user event role API

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#4131]
Role Invite API should accept a field `role` during creation. The field can accept the following values
- organizer
- coorganizer
- track_organizer
- moderator
- attendee
- registrar

When the status field changes to `accepted` during create or update, proper user event role records have to be created. 

User event role API to be removed completely.

**Comment by magdalenesuo** [comment]
@niranjan94 There is already a field name "role" in model which apparently is the role relationship with role-invite. Can I name the field to `role-name` instead?
