### ISSUE TITLE
Implement a health check endpoint.

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#4151]
Implement a health check endpoint similar to http://api.susi.ai/susi/status.json at `/status` which would check the following things. 

- Connection to the database. (And a few quick select queries using all the sqlalchemy models to ensure the models are inline with the migrations)
- Connection to redis
- Connection to the internet

The endpoint should return a `200` if all checks are okay. Else a `503 Service Unavailable` error to be returned along with information on which check failed. 

**Why is this required ?** 
- This will be used by kuberentes to know when the web instance is ready to receive requests

**Comment by shubham-padia** [comment]
@niranjan94 Since this will be out of version control, should this be json-api compatible or not ?

**Comment by niranjan94** [comment]
Not jsonapi compatible
