### ISSUE TITLE
»Ticket buyer« and »ticket holder« should be the same by default

### ISSUE THREAD

**Issue by jancborchardt** [fossasia/open-event-orga-server#4173]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request

**Current behavior:**
Currently you need to manually put in all the info in the »ticket holder« fields, or check this box »autofill«.
![screenshot from 2017-07-27 13-19-47](https://user-images.githubusercontent.com/925062/28670183-c793b444-72d7-11e7-9577-91a6ef99fdb3.png)
This is quite annoying and in most cases you buy the ticket for yourself.

**Expected behavior:**
There rather should be only one set of fields called »Ticket buyer«. Below that could be a checkbox called »Ticket holder is the same person as ticket buyer« checked by default. (Exactly like in online shopping where »Billing address is same as shipping address«.)

Then if you uncheck it, you get the second set of fields.

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-frontend
