### ISSUE TITLE
If »ticket buyer« and »ticket holder« are the same person with same email, you get 2 emails

### ISSUE THREAD

**Issue by jancborchardt** [fossasia/open-event-orga-server#4174]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**
See title

**Expected behavior:**
You should of course only receive one email. Also it would be cool to attach the ticket to the email or embed it in it so you directly have it offline in case the conference is abroad or there’s bad connection for one reason or another.

**Comment by Siddhinita** [comment]
@jancborchardt  @SaptakS  , Hey , I am new here and I wish to contribute.Could you please tell me which module handles emails?

**Comment by Siddhant2016** [comment]
Can I start to work on this?

**Comment by SaptakS** [comment]
@jancborchardt this has been resolved in the nextgen API version of the project. So closing this. The bug won't be there once the new structure of the project is pushed to production.
