### ISSUE TITLE
Refactor: Raise 404 for draft events with proper permission

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#4193]
**Current behavior:**

Endpoints like /events/id/something do not thrown 404 if event is draft and user is not logged in or does not have the proper permissions.
**Expected behavior:**

 Refactor all such APIs to respect the dev-handbook

**Comment by shubham-padia** [comment]
@niranjan94 If `Authorization` is present in the request headers, should a 401 be thrown if the jwt token is expired or wrong
- If 401 is thrown, it would indicate that the event exists
- If the user is the owner of the event, he/she would keep trying and would be getting a 404

**Comment by shubham-padia** [comment]
@niranjan94 can you have a look at the comment above, so I can make changes accordingly in #4204 :smile:

**Comment by niranjan94** [comment]
If the authorization header is present (but expired) and the event being accessed is not published
- And the user is related to the event (organizer, co-organizer etc) show a 401
- Else show a 404

@shubham-padia

**Comment by shubham-padia** [comment]
> And the user is related to the event (organizer, co-organizer etc) show a 401

This cannot be determined in case of invalid JWT and expired JWT too I think.

**Comment by niranjan94** [comment]
Invalid JWT then show a 404
Expired JWT, you can still get the user ID from the token

**Comment by niranjan94** [comment]
@shubham-padia pseudocode for that 

```
JSON.parse(base64_decode(token.split('.')[1])).identity
```
