### ISSUE TITLE
Add support for openstreetmap

### ISSUE THREAD

**Issue by kittykat** [fossasia/open-event-orga-server#4212]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Maps are shown using Google Maps

**Expected behavior:**
Maps are shown using OpenStreetMap

**Steps to reproduce:**

1. Go to https://eventyay.com/e/de88e486/

1. Look at "Getting there" information

1. Observe a Google map rather than an OSM map

**Other information:**
Google maps provides propitiatory maps which cannot be fixed or updated. OSM provides FOSS compatible maps which can be fixed by anyone and are also better in some parts of the world (e.g. in India).

**System information:** 
https://eventyay.com/

**Comment by shubham-padia** [comment]
@open-event-bot move to fossasia/open-event-frontend
