### ISSUE TITLE
Schedulling bug

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#423]
![screen shot 2016-05-26 at 13 43 27](https://cloud.githubusercontent.com/assets/2479753/15573548/168be566-2348-11e6-8bf4-d05728c84bb5.png)

**Comment by SaptakS** [comment]
@rafalkowalski you need to do `bower install` to install js files.. I guess you missed that.. Please check..

**Comment by SaptakS** [comment]
@rafalkowalski can you confirm whether this is fixed on your side?
