### ISSUE TITLE
Microlocations : GET requests return ERROR 500

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-orga-server#4246]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

Endpoint 
```
GET v1/events/<event_id>/microlocations 
```

Response
```
{
   "errors":[
      {
         "detail":"Unknown error",
         "source":{
            "pointer":""
         },
         "status":500,
         "title":"Unknown error"
      }
   ],
   "jsonapi":{
      "version":"1.0"
   }
}
```

Example URL
```
https://open-event-api.herokuapp.com/v1/events/173/microlocations
```

**Comment by enigmaeth** [comment]
@fossasia/open-event-server-devs  Can you guys take a look at this? The error message is :+1: 
`BuildError: Could not build url for endpoint 'v1.session_list'. Did you forget to specify values ['microlocation_id']` . 
`'v1.session_list'` and the relationships with microlocation and session look fine to me, seems I can't figure out the issue :sweat_smile: !

**Comment by poush** [comment]
I'm having similar issue is Discount Code API's PR :P

**Comment by enigmaeth** [comment]
I think `event_query` method might be causing this. @shubham-padia Can you please check this once?

**Comment by shubham-padia** [comment]
@enigmaeth Nope, it is not due to `event_query`. 
The `self_view_many` in microlocations.py is mentioned as `session_list`, which is causing the error ;). I'm sending a PR for this.
