### ISSUE TITLE
menu attribute missing from pages API

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-orga-server#4251]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Right now the pages API model looks like this : 
```
 {
      "name": "How it works",
      "title": "How it works",
      "url": "/how-it-works",
      "description": "How it works",
      "place": "Use Open Event",
      "language": "English",
      "index": 0
    }
```
**Expected behavior:**
It should also contain attribute field "menu" which can have values like open event or footer menu etc.
Sample : ` 'menu' : 'footer'`
or `menu : 'event'`

**Comment by shubham-padia** [comment]
@harshitagupta30 Can you explain what the `menu` attribute will do and why is it required ?

**Comment by harshitagupta30** [comment]
@shubham-padia We have 2 options where a page can be placed. It can be either footer or an event. So the menu will have 2 fields 'footer' and 'event' which will also help in deciding the place.
@niranjan94 I have a doubt regarding the same. Because in the hard-coded response we didn't have place and were calculating place using menu but since we are already having the place here. So do we actually need to have menu here?

**Comment by geekyd** [comment]
@shubham-padia We have a field `menu` in the form to specify where the page belongs 
![screenshot from 2017-08-12 09-55-36](https://user-images.githubusercontent.com/12807846/29237830-74907150-7f44-11e7-9580-e77e277135b1.png)

We have the same form for eventyay.

**Comment by poush** [comment]
Isn't this field is the "place" one?

**Comment by geekyd** [comment]
@poush Yes, The values in the dropdown are missing `footer` & `event`. It is currently hardcoded. Is it supposed to be hardcoded?

**Comment by MasterSlicer** [comment]
I want to work on this issue. Can you guide me through?

**Comment by shubham-padia** [comment]
@geekyd @harshitagupta30 Yes the values are supposed to be hard-coded in the front-end. There will not be a separate API for getting the options for that drop-down. One of those values has to be provided to the `places` attribute. I'll add the validation at the server side to ensure that no values except `footer` and `event` are accepted :)
Please keep a look at #4303 for more.
