### ISSUE TITLE
Add docs and dredd tests for Orders API

### ISSUE THREAD

**Issue by poush** [fossasia/open-event-orga-server#4264]

**Comment by S2606** [comment]
@poush are you working on this or can i?

**Comment by poush** [comment]
Not yet feel free to give it a shot :)

**Comment by poush** [comment]
@S2606 In case if it helps, you can see more about order flow here https://docs.google.com/document/d/12QFCwYIUEinb9JAwDleBHRQMfjReXEPf_GOX6F_Adhw/edit

**Comment by CosmicCoder96** [comment]
@poush The frontend needs the documentation for this. It'd be great if you can take this up. This is high priority right now.
