### ISSUE TITLE
Add missing roles relationship to events

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-orga-server#4266]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

Add missing roles relationship to events for admin/events
Related issue:
https://github.com/fossasia/open-event-frontend/issues/631

**Comment by poush** [comment]
@geekyd I'm not sure how a Roles resource can be related to a specific event? At Roles API you just manage resources for different roles available in Orga System

**Comment by geekyd** [comment]
@poush How do I get the roles of users for an event, i.e organiser,co-organiser etc. Is it `role-invites`?

**Comment by poush** [comment]
That's the separate entity, user_events_roles which is not yet in API. I guess we can make GET resources for this. @niranjan94 @SaptakS Please confirm.

**Comment by niranjan94** [comment]
user_events_roles is needed.
