### ISSUE TITLE
Ensure payment-url is generated even if payment mode is free and amount is non zero

### ISSUE THREAD

**Issue by poush** [fossasia/open-event-orga-server#4283]
Currently, payment-url can be bypassed if the total amount is non zero and payment mode is set to free

**Comment by niranjan94** [comment]
Why is payment url needed if it is free ?

**Comment by poush** [comment]
But what if user sent the free mode but the actual amount is non-zero ?

**Comment by poush** [comment]
After testing it with some changes I realized we don't need this change as the order will never be able to get into next status if payment is not completed.
