### ISSUE TITLE
Perform a check on the server side for the Current password of a user.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-orga-server#4286]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently, we are having something like:
![password](https://user-images.githubusercontent.com/17925669/29180618-f7842b90-7e15-11e7-912d-53c3671d3556.png)
where the user can update his password. Now since, we are not having the password field in user response(which will never be), we will have to perform a check server side while updating a password.

Expected:
Perform a check and return the response if the check was successful. Else return error.

**Comment by sumedh123** [comment]
@shubham-padia @poush @enigmaeth @magdalenesuo Can you take a look at this? I mean should we have a separate endpoint for this so that the old password can be send in request body and checked on the server side since we cannot check it on client side.

**Comment by poush** [comment]
If you just want to verify if the old password is correct then I guess you can also try hitting the login API.
Say user enters, "123" as password, you hit the login API with email and password and if it success then it is the correct one and then you can compare it with the new password entered.
Although if there is something to be developed in Orga Server then I guess the comparison between old and new password at USER patch request should be the one.
@fossasia/open-event-server-devs  views?

**Comment by shubham-padia** [comment]
> Say user enters, "123" as password, you hit the login API with email and password and if it success then it is the correct one and then you can compare it with the new password entered.

Sounds good :+1: 

> Although if there is something to be developed in Orga Server then I guess the comparison between old and new password at USER patch request should be the one.

@poush Can you elaborate on this, did not quite get it :sweat_smile:

**Comment by sumedh123** [comment]
@poush Yeah I also dint get the later part.

**Comment by poush** [comment]
Was saying that the other option is to send User PATCH request with old password as well in request body and the old and new password will be compared in this same request first before saving new password.

**Comment by SaptakS** [comment]
I feel there can be two different checks in this reset password API. 
- [ ] The hash of the old password entered matches the entry in the db
- [ ] The old password is not same as new password ( Done in most websites )

**Comment by poush** [comment]
@SaptakS Reset password API is for forgot password. This should be done is User PATCH.

**Comment by SaptakS** [comment]
@poush well according to the screenshot if it is for forgot password I don't think there should be a current password field.

**Comment by niranjan94** [comment]
Password change should require old password at a server level. The FE shouldn't handle checking of old password validity. We don't want someone to directly use the API and change a password without knowing the old password. (Lets say some one got hold of a valid auth token for example)

**Comment by poush** [comment]
@niranjan94 Is there will be a separate endpoint or it will be done in USER Patch request?

**Comment by niranjan94** [comment]
Separate endpoint should be better. Something like how we discussed in the `/auth/*` namespace

**Comment by sumedh123** [comment]
@magdalenesuo @SaptakS Can you guys let me know the endpoint with the request body for this one or update the docs?

**Comment by SaptakS** [comment]
@sumedh123 the docs will be updated in this PR: https://github.com/fossasia/open-event-orga-server/pull/4404. The endpoint for change-password is `/v1/auth/change-password`. Example request body will be:

```
"data": {
    "old-password": "abcd",
    "new-password": "abcde"
}
```

You also need to send JWT Auth key because this is when the user is logged in. However when the user isn't logged in and has forgot the password, the endpoint for that is `/v1/auth/reset-password`. I think the docs should be updated by end of day. @poush?

**Comment by sumedh123** [comment]
@SaptakS Is this a JSON spec API or a simple one as celery task?

**Comment by SaptakS** [comment]
`application/json`. not `application/vnd.api+json`

**Comment by sumedh123** [comment]
@SaptakS How will we identify the user then?

**Comment by SaptakS** [comment]
JWT Authentication. The spec is defined by Content-Type header. The authentication is done by Authorization header. So to authenticate, it's same as "Authorization: JWT <auth key>"

**Comment by sumedh123** [comment]
@SaptakS Right now, I am doing the same, sending manual request by Postman to ```https://open-event-api.herokuapp.com/v1/auth/change-password``` with a body like:
```
"data": {
    "old-password": "hithere",
    "new-password": "hellothere"
}
```
Response:
![change-pass](https://user-images.githubusercontent.com/17925669/29509447-f0db9824-8675-11e7-9fbd-0951b65b3e55.png)

**Comment by SaptakS** [comment]
@sumedh123 looks fine to me. Can you share the header?

**Comment by sumedh123** [comment]
@SaptakS 
```
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MDMzODY1OTcsImlkZW50aXR5IjoxMTAsImlhdCI6MTUwMzMwMDE5NywibmJmIjoxNTAzMzAwMTk3fQ.sCgoN0idomO0Iwng3OJXP7CpHjgL21dy1HJHJaiBUhY
```
