### ISSUE TITLE
GET request to v1/orders results in Error 500

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#4290]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

![image](https://user-images.githubusercontent.com/17252805/29205891-06043372-7e9d-11e7-8726-c01f66ee1748.png)

**Comment by poush** [comment]
#4287 solves this.
