### ISSUE TITLE
Creating postman bundle for API testing

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-orga-server#4292]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

Creating a postman bundle for major API operations for easier manual testing

**Comment by niranjan94** [comment]
@S2606 I don't see why this is required. We already have a valid API Blueprint file which can be used with a variety of tools for everything from testing to mocking. 

So, closing this now :)

**Comment by niranjan94** [comment]
And if a postman collection is required for some reason, anyone could use https://github.com/pixelfusion/blueman to convert the blueprint file to it.

**Comment by S2606** [comment]
@niranjan94 Sorry I didnt knew that
