### ISSUE TITLE
Add email to valid types in custom-form

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-orga-server#4309]
**Current**
Currently we are not able to set an email type to the custom-form which leads to `Error: 422`.

**Expected**
email should be a valid type for the custom-form

**Comment by geekyd** [comment]
@niranjan94 It will be good to have an email type for form validations on the frontend. Can you confirm it once?

**Comment by SaptakS** [comment]
Ok. I am not sure this is extremely needed. Because then we should have a url type as well, a contact type as well. I would like a discussion on this before just adding an email type. @niranjan94 @shubham-padia please comment. If we add, we should add all. Else why just add email type?
