### ISSUE TITLE
Add closing date field to Database

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#431]
- [x] Closing date field type:datetime

- [x] add Date Picker
- [x] save to databas(Wizard Draft step)

**Comment by juslee** [comment]
Who owns the API?

**Comment by rafalkowalski** [comment]
@juslee @aviaryan there are only GET Method implemented
I need PUT

I'm able to write it without API but then i will have to rewrite it to API

**Comment by aviaryan** [comment]
@rafalkowalski Which model is closing date field part of ? Is it a new field ?

**Comment by aditya1702** [comment]
@aviaryan its part of the event table
