### ISSUE TITLE
Use event identifier instead of event id for the POST request to Export API.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-orga-server#4313]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently the event export API has endpoint ```/v1/events/{event_id}/export/json``` in which we are using the {event_id} in the request url.

Expected:
I think that should be changed to event identifier since it is the default one on the basis of which we are querying on the frontend.

**Comment by sumedh123** [comment]
@magdalenesuo Please take a look at this.

**Comment by sumedh123** [comment]
Also, even if I am getting a successful response, I am also getting an error in console:
```"Assertion Failed: normalizeResponse must return a valid JSON API document:
	* One or more of the following keys must be present: "data", "errors", "meta"."
```

**Comment by poush** [comment]
@sumedh123 This is not JSON spec based endpoint so if it possible you have to execute this endpoint without JSON API spec check or this error will persist.
