### ISSUE TITLE
User relationship is missing from sessions

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#4323]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Sessions don't have a relationship with the user and vice versa

**Comment by geekyd** [comment]
Related Issue: https://github.com/fossasia/open-event-frontend/issues/694
