### ISSUE TITLE
User relationship is missing from attendees & vice versa

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-orga-server#4324]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Tickets don't have a relationship with the user and vice versa

**Comment by shubham-padia** [comment]
Please always mention the relevant frontend issue so that we have a better understanding :)

**Comment by geekyd** [comment]
Related Issue : https://github.com/fossasia/open-event-frontend/issues/693

**Comment by shubham-padia** [comment]
Here, a relationship between attendee and user is required, rather than user and ticket.

**Comment by SaptakS** [comment]
@shubham-padia, I think both is needed. Because if I recall correctly, we have an option to see all the tickets bought by the user. Like for sessions.
