### ISSUE TITLE
Event relationship is missing from users

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-orga-server#4326]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Events don't have a relationship with the user and vice versa

**Comment by shubham-padia** [comment]
Events have a relationship with the user, the organizers, coorganizers, etc fields are a part of that.

**Comment by geekyd** [comment]
@shubham-padia There is a relationship missing in the payload of users. It is required for https://github.com/fossasia/open-event-frontend/issues/687

**Comment by shubham-padia** [comment]
The relationship with event in Users API is WIP as mentioned in the PR for adding the organizer relationship to the events Api, please change the issue subject please then :smile:

**Comment by geekyd** [comment]
@shubham-padia Done! Thanks for the update.
