### ISSUE TITLE
Order relationship is missing from attendee

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-server#4328]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently, there is no order information related with attendee. An attendee can exist without an order which is undefined behaviour

**Expected behavior:**
As the original workflow was like this:
- Create Order
- Select ticket(s) for the order
- Add attendee(s) for each ticket type
- Set payment method
- Confirm order

Similar flow should be there in the API as well. We should only be able to add attendees with order. Where we reference each attendee with a ticket and 1 order object containing this information.

Furthermore it is impossible to check in through QR code if there is no order related to attendee as we check the order identifier and attendee ID in the QR code

For now, what should be the flow to create an attendee with order?

**Comment by poush** [comment]
@iamareebjamal  Order flow has been changed a little bit now.

**Current Flow**
1. Create Attendee Records without any order assigned
2. Send them in relationship to Order creation
3. Server will add relationship between these attendees and the order created
4. Server will send the payment link based on your payment method
5. You complete the payment and hit the charge API

**Comment by poush** [comment]
I will add the order relationship in the API for attendees.
