### ISSUE TITLE
Allow session elements to be removed from the timeline

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#436]
> ~~Allow the scheduled session elements to be dragged out of the timeline into the unscheduled sessions list.~~

Allow session elements to be removed from the timeline.
This will be helpful when the organizers want to re-organize sessions.

**Comment by SaptakS** [comment]
I guess instead of dragging them out, we can just add a cross on the session. Clicking the cross button removes it from calendar. I think that would be a better UX and also easier to implement.

**Comment by niranjan94** [comment]
@SaptakS Nice idea :smile: . And, yes. Very easy to implement :grin:

**Comment by SaptakS** [comment]
:+1:
