### ISSUE TITLE
Invoice relationship missing from orders and vice versa 

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#4362]
I'm submitting a ... (check one with "x")

[x] bug report
 [ ] feature request
 [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Comment by enigmaeth** [comment]
Closing in favor of https://github.com/fossasia/open-event-orga-server/pull/4367#issuecomment-322993426.
