### ISSUE TITLE
Orders API docs have missing attributes

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#4371]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Not all attributes are enlisted in the docs, there are more of them in the actual response.

**Comment by bhanu1911** [comment]
Can I start working on this?

**Comment by shubham-padia** [comment]
Sure, please go ahead, the api schema can be found at app/api/schema/orders.py.

**Comment by tipsynerd** [comment]
Can I take up this issue?

**Comment by SaptakS** [comment]
@tipsynerd I think @bhanu1911 is already looking into it.

**Comment by tipsynerd** [comment]
Ok, no Problem

**Comment by poush** [comment]
@bhanu1911 can you please update us on the progress?

**Comment by ayushgangrade** [comment]
@poush Can I take this up if no one is working?

**Comment by SaptakS** [comment]
@ayushgangrade seems this issue has been stagnant for quite some time. Go ahead.

**Comment by ayush1999** [comment]
@SaptakS @poush Any work on this? I'd love to take this up if nobody is working on it right now.

**Comment by shubham-padia** [comment]
@ayush1999 please go ahead

**Comment by ayush1999** [comment]
@shubham-padia Thanks! Working on it! :+1:

**Comment by ananyo2012** [comment]
@ayush1999 Are you working on this ?
