### ISSUE TITLE
Event relationship missing from attendees

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-orga-server#4381]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

Events have a relationship with attendees in their response, vice-versa is not true.

**Comment by shubham-padia** [comment]
@CosmicCoder96 attendees already have a relationship with event, https://github.com/fossasia/open-event-orga-server/blob/nextgen/app/api/schema/attendees.py, can you recheck?

**Comment by CosmicCoder96** [comment]
@shubham-padia yes, that seems to be the case. It didn't appear in the GET response of Docs, hence I raised this.
