### ISSUE TITLE
Change color picker [Scheduling UI - Add Track Modal]

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#439]
As pointed out in #433 by Rafał Kowalski, the color picker used can be the one provided along with gentelella (This one: https://colorlib.com/polygon/gentelella/form_advanced.html) so that it would match all the other widgets used.

**Comment by aditya1702** [comment]
@niranjan94 Is this for the step 3 in event creation...adding tracks? Because I am already doing that one in #433

**Comment by niranjan94** [comment]
@aditya1702 No. This is not for that. This is part of the Scheduling UI.
