### ISSUE TITLE
Celery task gives sometimes "FAILURE" response whereas sometimes "SUCCESS" response.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-orga-server#4392]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

The celery task API for gettting the download URL for an event gives 'FAILURE' response sometimes whereas it gives 'SUCCESS' response sometimes for the same event. I have checked on multiple events. I got SUCCESS response for an event yesterday noon and was able to download the event whereas when I tested the same thing later, it is giving the FAILURE response.

**Comment by sumedh123** [comment]
@magdalenesuo @poush @SaptakS Please look into this.

**Comment by SaptakS** [comment]
@sumedh since you said it's working fine right now, so closing.
