### ISSUE TITLE
Change Event Copy API from JSON spec to non-JSON spec

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-orga-server#4393]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently, the POST to event copy is having the request body like:
```
{
  "data": {
    "type": "event-copy"
  }
}
```
which is weird.

Expected:
The request should be a simple POST to ```/v1/events/{identifier}/copy``` without any request body.
Please check the comment here: https://github.com/fossasia/open-event-frontend/issues/742#issuecomment-323535638

**Comment by sumedh123** [comment]
@poush @magdalenesuo @shubham-padia @enigmaeth

**Comment by poush** [comment]
@sumedh123 This API is JSON spec API so the type of object is required to create.

**Comment by sumedh123** [comment]
@niranjan94 Please guide.

**Comment by niranjan94** [comment]
@poush then please make it a plain json endpoint. It really doesn't make
sense to have a body like this. event-copy isn't actually a resource.

Let's stick to json-api spec for proper resources. And for such actions,
we'll go for a plain json endpoint.

**Comment by poush** [comment]
Okay, sure!
