### ISSUE TITLE
Deploy new version to heroku

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#44]

**Comment by mananwason** [comment]
@rafalkowalski The server is not working correctly. I suggest you keep 2 versions : one beta and other stable because both arnav and me are dependent on your server, if it doesn't work, we can't do much work.

**Comment by rafalkowalski** [comment]
@mananwason I had two versions, even i sent to you a link with testing version to test http://glacial-earth-2730.herokuapp.com/admin/
I assumed that you didn't report a bugs through whole weekend so I deployed it to http://open-event.herokuapp.com/admin

Tell me where bug is occured(Test case).

**Comment by mananwason** [comment]
Yeah @rafalkowalski I didn't use the api's from the test version in the app as I would have to change all the url's but I guess you depliyed the new version yesterday and all the data was gone. The session api was showing Internal server error http://open-event.herokuapp.com/get/api/v1/event/2/sessions

**Comment by rafalkowalski** [comment]
@mananwason Thanks for reported a bug, I fixed it :)
