### ISSUE TITLE
Form Validation in Event Creation.

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#440]

**Comment by aditya1702** [comment]
@SaptakS @rafalkowalski Earlier we had wtforms so we could easily validate the forms.But how do we validate request.form?

**Comment by SaptakS** [comment]
We can validate the forms in the frontend itself using jquery validate.

**Comment by rafalkowalski** [comment]
@SaptakS we can also validate it in backend side

**Comment by SaptakS** [comment]
Yes @rafalkowalski . We can do that. The problem is in the modal, the forms are already validated by bootstrap javascript, but it somehow doesn't work for wizard. And we would need to validate in backend, but we need to validate using javascript in the wizard, because at each step we are not submitting the form but would want it to be validated. What do you say?

**Comment by niranjan94** [comment]
I'll work on this now
