### ISSUE TITLE
Broken User Events Relationship

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-server#4415]
**I'm submitting a ...**
- [x] bug report

**Current behavior:**
Created an event. 
It is available using events endpoint - `http://open-event-api.herokuapp.com/v1/events/326`
but events for the user is returning 0 items - `http://open-event-api.herokuapp.com/v1/users/81/events`

**Comment by poush** [comment]
Can you make sure the proper "UsersEventsRole" entries are there because this endpoint is working fine here on my nextgen branch. Ensure that user with ID 81 has any access on any events other than just Attendee
