### ISSUE TITLE
Overflow of table data in manage events page after login in mobile view

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-orga-server#4422]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
In mobile view, table data on manage events page is overflowing outside its container

**Expected behavior:**
The table data should appear inside its container

**Steps to reproduce:**
After login on https://eventyay.com/ , go to manage events page ( in mobile phone )

**System information:** 
on mobile phone

![21057153_1183136475163471_1290166003_o](https://user-images.githubusercontent.com/25428397/29581208-3d82ff5c-8796-11e7-977b-876a30f65fb8.png)

**Comment by shreyanshdwivedi** [comment]
I would like to work on this issue

**Comment by SaptakS** [comment]
@shreyanshdwivedi currently we are moving away from the present development/master architecture to a decoupled architecture. So right now this repo maintains the all the APIs to interact with the backend and manage database entries. This issue will now be handled in [Open Event Frontend repo](https://github.com/fossasia/open-event-frontend). Please have a look in that repository. Thanks.

**Comment by SaptakS** [comment]
@niranjan94 please create a relevant issue in frontend repository if needed. closing here.
