### ISSUE TITLE
Implement faq-types api

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#4433]
In order to group similar FAQs into categories, implement `faq-type` in a similar way as `session-types`

**Comment by magdalenesuo** [comment]
@shubham-padia I do not think a separate api is needed here. Can't you just add a `type`(str) field in the faq api itself? Why do you need to confuse people with another thing as faq-type api? FAQ is simply post question and answer. Session type is understood. It makes a difference. But Why make faq big by making a whole separate api type for it?

**Comment by shubham-padia** [comment]
@magdalenesuo
>  I do not think a separate api is needed here. Can't you just add a type(str) field in the faq api itself?

 What if I want to group multiple questions under different sections. Sure, you can add a type field in the API itself, but if i have 10 questions under 1 section, it is redundant and not good practice to leave it to the user to enter the type all 10 times. 

> Why do you need to confuse people with another thing as faq-type api?

If you are getting confused with the session-type analogy, think of this in terms of more of a `tags` approach. The faq-type relationship will be optional, if the user wants different sections, he/she can add it ,if not, it's the user choice.

> But Why make faq big by making a whole separate api type for it?

Adding a type field is not a feasible option for grouping multiple FAQ sections, it will become uncontrolled over time. Also this does not make the faq API big. If the user does not want to enter a faq-type, it's totally cool.

**Comment by magdalenesuo** [comment]
@shubham-padia Right. Makes sense. Cool then.
