### ISSUE TITLE
Events API: return excluded events and with state published

### ISSUE THREAD

**Issue by lucasruchel** [fossasia/open-event-orga-server#4442]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
API /api/v1/users/me/events  returns excluded events and with state published

**Comment by SaptakS** [comment]
@lucasruchel just to clarify, by excluded you mean deleted, right? Or do you mean private?

**Comment by lucasruchel** [comment]
Yes, I mean deleted. The API response all events create by user, including deleted events with the same state when they was published

**Comment by shubham-padia** [comment]
@lucasruchel This has been resolved in the nextgen API, please refer to the same. Closing this :)
