### ISSUE TITLE
User API: Include a 'status' attribute in the response.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-orga-server#4452]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently, there's no such attribute by which we can track if a user is active or not.

Expected:
Add an attribute called ```status``` which will indicate the user is active or not. We can check the user activeness based on last login, however there may be other ways too.

**Comment by sumedh123** [comment]
@niranjan94 Should this check be done on server side or client? I guess getting a ```status``` attribute in response would be better than getting a ```last-login``` and then checking the activeness in FE?

**Comment by sumedh123** [comment]
Currently we have an attribute called ```last-accessed-at``` in the response.

**Comment by shubham-padia** [comment]
@niranjan94 Can you please confirm this? I personally don't think this attribute is required :smile: , the FE can figure it out themselves via `last-accessed-at`

**Comment by sumedh123** [comment]
@shubham-padia Okay. That can be done. There's no point in having a redundant attribute.

**Comment by shubham-padia** [comment]
@sumedh123 Closing this then :)
