### ISSUE TITLE
Update documentation & docker image to match nextgen branch requirements

### ISSUE THREAD

**Issue by unamuno** [fossasia/open-event-orga-server#4454]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Installation on Google Cloud with Ubuntu 16.4 / Debian 7/8 Crashing 
on docker-compose build 
(Step 10/12)

**Expected behavior:**
Installation running without failure 

**Steps to reproduce:**
Follow the tutorial for Installation on Google Cloud step by step

**Related code:**

/bin/sh: 1: bower: not found
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt && bower install --allow-root && bower cache clean --allow-root' returned a non-zero code: 127

**System information:** 

```
Your operating system
```
Ubuntu stretch/sid

```
output of `python --version`
```
python --version
Python 2.7.12

**Comment by supergr35** [comment]
Interested in this one. I'm guessing that this is coming from bower not being installed. Do we want to install bower in the docker image?

**Comment by niranjan94** [comment]
@supergr35 no. The guide/docker image probably needs to be updated. This project no longer uses bower.

**Comment by tulikavijay** [comment]
can I take this up?

**Comment by poush** [comment]
@tulikavijay Yeah since no one is working on it, you can continue with this issue.
