### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'created_at'

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#4464]
https://sentry.eventyay.com/eventyay/dev-api/issues/99/

```
TypeError: __init__() got an unexpected keyword argument 'created_at'
(8 additional frame(s) were not displayed)
...
  File "app/api/helpers/permissions.py", line 43, in decorator
    return fn(*args, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'created_at'
```

**Comment by ananyo2012** [comment]
I want to claim this issue.

**Comment by poush** [comment]
Don't say it exactly claiming and yeah feel free to work on it. Make sure you have the setup ready.

**Comment by ananyo2012** [comment]
Yes I have the setup ready. I will come back with possible solution.

**Comment by ananyo2012** [comment]
@shubham-padia @poush Can you help me to reproduce this error since `jwt-required` in permissions.py is called in multiple no of cases.

**Comment by shubham-padia** [comment]
@ananyo2012 The error is occurring in the discount codes API.
It maybe a bug in the discount code sqlalchemy model constructor proabably, please check that first.

**Comment by ananyo2012** [comment]
I checked the Discount code model but couldn't find any bug in it. Any other leads in figuring out the error?

**Comment by rahuldecoded** [comment]
@ananyo2012 Are you working in this?

**Comment by ananyo2012** [comment]
Yes I am. But I am unable to figure out the error. Would be great if you can help in reproducing the error !

**Comment by rahuldecoded** [comment]
can I see your request?

**Comment by rahuldecoded** [comment]
@ananyo2012 Still working?

**Comment by ananyo2012** [comment]
Yes I am working on it. I kinda missed your last comment. Will send the request I made in a minute

**Comment by rahuldecoded** [comment]
Working from 20 days?

**Comment by ananyo2012** [comment]
Ok I was finally able to reproduce the error. This is happening when we try to explicitly pass a `created_at` parameter in the Discount Codes request while creating a new discount code. But if we don't give a `created_at` parameter it by default takes the current time.

**Comment by ananyo2012** [comment]
Sorry I was busy with some work in between. And I was working on badgeyay
in the mean time too. I have submitted a PR for the issue yesterday.
