### ISSUE TITLE
KeyError: 'checkin_times'

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#4465]
https://sentry.eventyay.com/eventyay/dev-api/issues/102/

```
KeyError: 'checkin_times'
(9 additional frame(s) were not displayed)
...
  File "app/api/helpers/permissions.py", line 43, in decorator
    return fn(*args, **kwargs)
  File "app/api/attendees.py", line 125, in before_update_object
    if obj.checkin_times and data['checkin_times'] not in obj.checkin_times.split(","):

KeyError: 'checkin_times'
```

**Comment by ananyo2012** [comment]
I have done the Local installation. I would like to work on this. How do we get access to the link mentioned in the issue ?

**Comment by shubham-padia** [comment]
All the info required is mentioned in the issue itself. The link is only for reference purposes for maintainers. Cheers :)

**Comment by ananyo2012** [comment]
@shubham-padia Can you help me to reproduce the error. Currently when a send `PATCH` request at `/v1/attendees/{attendee_id}` it successfully executes.

**Comment by bhaveshtyagi** [comment]
I want to work on this bug

**Comment by shubham-padia** [comment]
@bhaveshtyagi Please look for a different issue to work upon :smile:
@ananyo2012 is already working on this

**Comment by rahuldecoded** [comment]
@shubham-padia Can you please review my PR #4486 ?
