### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#4466]
https://sentry.eventyay.com/eventyay/dev-api/issues/97/

```
TypeError: string indices must be integers
(2 additional frame(s) were not displayed)
...
  File "app/api/auth.py", line 46, in reset_password_post
    email = request.json['data']['email']

TypeError: string indices must be integers
```

**Comment by Kunalgarg2100** [comment]
@shubham-padia can I take up this issue?

**Comment by shubham-padia** [comment]
@Kunalgarg2100 If you've setup the nextgen branch locally, please go ahead.

**Comment by Kunalgarg2100** [comment]
I am facing `password authentication failed` while trying to setup nextgen branch locally.
I by mistake ran
` ` `
CREATE USER kunal WITH PASSWORD 'password@'
` ` `
during installation. Now when I type
` ` `
CREATE USER kunal WITH PASSWORD 'start'
` ` `
I get this error ![Error screenshot](https://drive.google.com/file/d/0B8NBXP-EfPUhM0pYdnY4bThpcHM/view), please tell how to fix it, I tried deleting the entire repo and cloning it again but it resulted in same error

**Comment by shubham-padia** [comment]
@Kunalgarg2100 Please use the gitter channel for general doubts, the issues are specific for discussion related to that topic only. Please help us keep this thread clean :smile:

**Comment by rahuldecoded** [comment]
@shubham-padia I figured out that request.json return a dictionary they why we'll get TypeError? I'm  unable to reproduce the error, can you help me how to proceed?

**Comment by rahuldecoded** [comment]
@shubham-padia Using the below request I'm able to reproduce the error.
![screenshot from 2017-09-22 10-35-07](https://user-images.githubusercontent.com/15686569/30730082-fd5af85e-9f81-11e7-8179-6902cd3f655b.png)
![screenshot from 2017-09-22 10-30-57](https://user-images.githubusercontent.com/15686569/30730110-2f7e2b3a-9f82-11e7-9635-614a0916f39f.png)
So should I handle this error or what to do next?

**Comment by shubham-padia** [comment]
@rahuldecoded can you share the request in a text format on the issue itself or via pastebin? Its hard to figure out from the image :sweat_smile:

**Comment by rahuldecoded** [comment]
@shubham-padia Sure. :smiley: Only the data part or the whole request?

**Comment by shubham-padia** [comment]
The data only

**Comment by rahuldecoded** [comment]
@shubham-padia 
-d '{ 
          "data": " ", 
          "email": "123@gmail.com"
     }'
For the above one I'm able to reproduce the error.

But according to the docs data must be as below
-d '{ 
         "data": {
               "email": "123@gmail.com"
          }
     }'

**Comment by shubham-padia** [comment]
Okay, thanks. Please handle the exception and raise a 400 bad request error
in thus case.
