### ISSUE TITLE
Add upload to docker cloud button

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-orga-server#4471]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
There is no button available for docker cloud deployment

**Expected behavior:**
Button for automatic deployment on docker cloud

**Would you like to work on this issue?**
Yes

**Comment by souravsingh** [comment]
I am interested in taking a stab at the issue.How do I start?

**Comment by S2606** [comment]
@souravsingh Sorry to say but i am working on this.
