### ISSUE TITLE
Call for Speaker not saved

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-orga-server#4472]
The call for papers is not saved and the call is not published.

![screenshot from 2017-09-20 12-00-44](https://user-images.githubusercontent.com/1658742/30638421-ac4b0562-9dfb-11e7-96b1-a806868ebf59.png)

**Comment by vaibhavsingh97** [comment]
@hpdang can i take this issue? Can you please guide me how to reproduce and how can i solve?

**Comment by poush** [comment]
If your setup is ready then feel free to try this. However, since this Urgent one. Try to debug issue and post the bug details here in between your fix.

**Comment by vaibhavsingh97** [comment]
@poush Can you please help me to reproduce this error, so that i can send fix as soon as possible. As it's a crtical bug so need to be fixed faster

**Comment by poush** [comment]
Checkout to development branch, run the server, create the event, try to add call for speakers using account other than of admin and see what you get in error.
