### ISSUE TITLE
Redundant feedback options in the API docs.

### ISSUE THREAD

**Issue by invinciblycool** [fossasia/open-event-orga-server#4473]
**I'm submitting a ...** 
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

There are currently two same feedback options in the API docs even, which are unnecessary and add redundancy to the API.
Check it [here](http://dev.eventyay.com/api/v1).

**Comment by shubham-padia** [comment]
@invinciblycool Can you elaborate on the problem here? Please specify which feedback options you are talking about :)

**Comment by invinciblycool** [comment]
![fossbug](https://user-images.githubusercontent.com/24691797/30649557-2ca1ca42-9e3e-11e7-8ec5-c86501df8fe2.png)
Hope this makes it clear.

**Comment by shubham-padia** [comment]
@invinciblycool Thanks. If you want to work on it, please go ahead.

**Comment by vaibhavsingh97** [comment]
@invinciblycool Are you working on this issue?

**Comment by invinciblycool** [comment]
Yes.
