### ISSUE TITLE
Call for Speakers: Gender not saved when entering speaker information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#4490]
When a user enters Gender information in the call for speakers the information is not saved and the user has to enter it again when he/she edits speaker details.

![screenshot from 2017-09-25 06-49-59](https://user-images.githubusercontent.com/1583873/30792867-fc791a5e-a1bd-11e7-8470-48f7a4f23e3d.png)

**Comment by rahuldecoded** [comment]
I'm taking this issue. @mariobehling

**Comment by ananyo2012** [comment]
Hey @mariobehling @rahuldecoded I just made a PR fixing this issue

**Comment by shubham-padia** [comment]
closed via #4494
