### ISSUE TITLE
Adding a Makefile for checks like pep8 and flake8 inside whole project

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-orga-server#4492]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

***If interested please suggest some other features alongwith pep8/flake8 that can be introduced in Makefile***

**Other information:**

**System information:** 

> Your operating system
```
Linux Ubuntu 16.04 LTS
```
> output of `python --version`
```
Python 2.7.12
```
**Would you like to work on this issue?**
Yes

**Comment by shubham-padia** [comment]
Not needed currently, closing this
