### ISSUE TITLE
Add validations to form 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#45]
I will define, which fields are required

**Comment by leto** [comment]
More details, please!

**Comment by rafalkowalski** [comment]
@leto 
Event(name, email, start_time, end_time, location)
Sponsor(name)
Speaker(Name, Email, Country)
Session(Title, Description, Start_time, End_time)
Track(name, description)
Microlocation(name latitude, longitude)

In email for example i have to check whether contains "@"
