### ISSUE TITLE
Cannot delete ticket type in Wizard Step 1 even though no tickets have been sold

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#4517]
In the wizard step 1 it is not possible to delete an existing ticket type on eventyay.com. This ticket type does not have any tickets that we sold and should be deletable.

**Comment by invinciblycool** [comment]
@mariobehling Unable to reproduce the behaviour.
Tried editing a event but no abnormality on the edit wizard step 1.
Not sure if it was the correct way :confused:

**Comment by ananyo2012** [comment]
I could reproduce the error. This happens in the case of a Paid Ticket. The ticket initially gets removed from the list but after you save the event it still remains. Though it works fine for Free and Donation tickets.

**Comment by ananyo2012** [comment]
I would like to work on this.

**Comment by shubham-padia** [comment]
@ananyo2012 Please go ahead.

**Comment by mariobehling** [comment]
The bug seems to appear only at certain events I set up. I cannot always reproduce it. I resolved it by starting fresh. Closing this for now therefore.
