### ISSUE TITLE
OAuth Link in README are dead

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/open-event-orga-server#4520]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Error 400

**Expected behavior:**
Login Credentials form

**Steps to reproduce:**
Valid links to be added

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:** 

```
Windows 10
```

```
Python 3.4.0
```

**Comment by invinciblycool** [comment]
I guess those links are just for reference, because the API automatically routes to the desired page when actually using the links with the open-event-orga-server API.

**Comment by niranjan94** [comment]
@aashutoshrathi which links are you talking about ?

**Comment by invinciblycool** [comment]
@niranjan94 Here.

![oauth](https://user-images.githubusercontent.com/24691797/32101648-affbcebe-bb36-11e7-9527-e295d7757fc9.png)

**Comment by niranjan94** [comment]
Those links are not dead. They do work. You cannot make a GET request to them. And you'll need to pass in proper parameters too. Not a fault of the README. The links aren't meant to be clicked on. Just given in the read me for a reference. Please check the code for more details :)
