### ISSUE TITLE
Facility to retrieve back the forgotten password

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-orga-server#4534]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently there is no facility to retrieve back the password if forgotten from the open event android app.

**Expected behavior:**
Implement API to provide this facility.

**Comment by shubham-padia** [comment]
@heysadboy there's a rest password API for this purpose, can you have a look at it

**Comment by heysadboy** [comment]
Thanks @shubham-padia . So I am closing this issue.
