### ISSUE TITLE
POST API | Add input validation

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#460]
Currently there is almost no input validation in the POST API . 
For string and integer fields, we can use the min and max length params in flask-restplus.
And for more complex fields (like email and url), we can use custom fields to do the validation.
See #474

@shivamMg views ??

**Comment by aviaryan** [comment]
on it

**Comment by shivamMg** [comment]
@aviaryan We can do validation using existing forms. This can make our validation consistent across the project. So if the validation at the forms is changed, we will not have to update our validators at api. This of course requires forms to be properly defined. 

What do you say?

**Comment by aviaryan** [comment]
Forms (server-side python forms i.e. WTForms) are now not used in our project. See /open_event/forms/admin/event_form.py, it is outdated. Instead client side validation using javascript is being done. 

juslee said https://github.com/fossasia/open-event-orga-server/issues/442#issuecomment-222369265
> @aviaryan every feature you think should be there. You want the REST APIs to be as comprehensive as possible so that your web-app and orga-server can eventually just call the APIs.

The API should be self-sufficient and orga-server will eventually totally call the API so I think we should make it complete with the validation too done by the API. 

And as WTForms are now a thing of the past, it doesn't make sense to go into the trouble of defining and using them just for API validation (we have our api models for that).

**Comment by shivamMg** [comment]
@aviaryan WTForms are not being used right now, but they are being rendered by templates. I've asked the UI guys about this in gitter.

**Comment by aviaryan** [comment]
@shivamMg 
Are you sure that wtforms are being rendered as templates. I did the "Find Usages" option (PyCharm or sublime-anaconda) on each of the forms and found **0 usages** for them (except in testing which is not a use really). 
Also some of these forms (events, tracks, session etc) are highly out-of-date. That being said I think they are not being used (or rendered) anymore. 
The old views did use to use the wtforms but they are now deleted. (see views folder).
The old templates are still there and from there code you can see that they do use to use wtforms.

@rafalkowalski please go through this thread and let us know if there is a plan to use WTForms or not. They are totally not used right now.

**Comment by rafalkowalski** [comment]
If it not used please remove it @aviaryan

**Comment by shivamMg** [comment]
@rafalkowalski Until the server completely moves to API, wtforms should remain. 

On the same note, why aren't we using wtforms for form validation (for forms in gentelella)?

**Comment by rafalkowalski** [comment]
@shivamMg i don't know

**Comment by niranjan94** [comment]
@shivamMg which all parts of the API are functional now ? And how does the API Authorization take place ? 

_I would like to use it for the Scheduling UI. For creation of microlocations_

**Comment by aviaryan** [comment]
@niranjan94 POST API and GET API are functional right now. The only authorization mechanism implemented right now is "Basic authorization" i.e. username:password . You can test the POST API for microlocations at http://open-event.herokuapp.com/api/v2/#!/microlocations/post_microlocation_list
You will need to be login'd for POST request to be successful. 

To add auth to a request, the following link may help assuming you are using Jquery.
http://stackoverflow.com/questions/5507234/how-to-use-basic-auth-with-jquery-and-ajax

**Comment by niranjan94** [comment]
We would need a token based auth soon (a token could be generated when the user logs into the admin panel and used for all further API requests). Because, hardcoding the username/password in javascript is a security risk.

**Comment by aviaryan** [comment]
Yes, we plan to add it too. We can have both authorizations, basic and token based. 

PS - Let's keep this issue on-topic.

**Comment by aviaryan** [comment]
Fixed in #561. closing
