### ISSUE TITLE
Put responses and params under `api.doc` decorator

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#464]
- Specify parameters for `api.doc` instead of using separate <del>response and</del> param decorators. e.g. in [tracks](https://github.com/fossasia/open-event-orga-server/blob/master/open_event/api/tracks.py#L54).
- Add description to parameters. (and type https://github.com/fossasia/open-event-orga-server/issues/472)
- Document "Object not found" error properly (specify object, track, session, etc)
- Specify `make_url_query` at `helpers.py` as private.

**Comment by aviaryan** [comment]
Hi. Can you explain the reason why keeping everything inside `api.doc` will be more helpful ?
Using api.params, api.response, api.header etc helps keep them distinct and makes the code more readable (IMHO).

**Comment by shivamMg** [comment]
@aviaryan To remove duplicate code. For instance to solve https://github.com/fossasia/open-event-orga-server/issues/472 I would have to go to every other service and overwrite:

```python
@api.param('start')
@api.param('limit')
```

to 

```python
@api.param('start': {'description': 'ID to begin from', 'type': int})
@api.param('limit': {'description': 'Number of results to be retrieved', 'type': int})
```

It would be better to just specify a constant and pass it to doc decorator.

```python
@api.doc('unique_id', params=PAGE_PARAMS)
```

I did not do it for the response decorators though, their descriptions had the service names.

**Comment by aviaryan** [comment]
@shivamMg Neat idea :+1: . Thanks for clearing that up.
