### ISSUE TITLE
Add number of days in the event creation page.

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#475]
This functionality will be used to create a dynamic schedule based on the number of days the event is scheduled for.

**Comment by rafalkowalski** [comment]
@mananwason we have two fields, start and end? i think based on this values you are able to count numbers of days isn't it?

**Comment by mananwason** [comment]
@rafalkowalski yes I can do that but this would increase overhead on the android side, which will slow the app, instead of the start and end fields, which are not being used anywhere, number of days should be there

**Comment by rafalkowalski** [comment]
@SaptakS what do you think? is it good idea to count range?

**Comment by SaptakS** [comment]
@rafalkowalski @mananwason I think if you are using API to get the information in the app, we can send the number of days in the json by calculating end-start dynamically rather than storing it in DB. What do you think?
