### ISSUE TITLE
Create dates.json to show event dates

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#476]
@juslee @rafalkowalski @leto @championswimmer for the client apps, we need a list of dates for the schedule which references the session, so that we can sort sessions according to date. Either we can do this on the client side or on the server side. I'm confused on where we should add this functionality. Please comment.

**Comment by mariobehling** [comment]
Please refer to the JSON files provided from the Open Event Scraper currently. All info should be in the JSON files.
