### ISSUE TITLE
double nesting of events[] array in api endpoint

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#48]
there's a little bug here

http://glacial-earth-2730.herokuapp.com/get/api/v1/event

The response has an event[] array inside an object inside another event[] array. 
as per dicussion response should have been 
https://github.com/fossasia/open-event/blob/master/API.md#event

**Comment by rafalkowalski** [comment]
@championswimmer http://open-event.herokuapp.com/get/api/v1/event
