### ISSUE TITLE
Bug When sign in via google 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#491]
Profile site doesn't work
![screen shot 2016-06-01 at 19 44 58](https://cloud.githubusercontent.com/assets/2479753/15719740/8f50492c-2831-11e6-9eee-3e052d0b6146.png)

**Comment by aditya1702** [comment]
@rafalkowalski It is working for me. I did Google sign in

**Comment by rafalkowalski** [comment]
if you go to /admin/profile is it working?

**Comment by aditya1702** [comment]
![profile](https://cloud.githubusercontent.com/assets/15054664/15739440/aed392c6-28cd-11e6-8ba6-988c78138ae5.png)

**Comment by aditya1702** [comment]
@rafalkowalski Ok now I am getting an error..I dont know why earlier I wasnt!
