### ISSUE TITLE
Create Sessions Page

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#501]
- [x] add page with url: admin/sessions/
- [x] only user sessions visible
- [x] Add table with columns Event, Title, Session Type, Start Date, End Date, State

**Comment by SaptakS** [comment]
Table with Event, Title, Start_Date, End_Date, State already present. https://github.com/fossasia/open-event-orga-server/pull/494

**Comment by mariobehling** [comment]
Who is working on this issue? Please assign.

**Comment by SaptakS** [comment]
@rafalkowalski on visiting admin/sessions/ , we need to show the session belonging only the user logged in, right? Thats what you are trying to say?

**Comment by mariobehling** [comment]
@aditya1702 Please align with @SaptakS who is taking care of this and post a screenshot of the outcome. Cheers.

**Comment by aditya1702** [comment]
@mariobehling Yes will do

**Comment by SaptakS** [comment]
@aditya1702 we need to also filter the sessions according to the user_id of the logged in user.

**Comment by SaptakS** [comment]
Already handled in `/mysession` in PR https://github.com/fossasia/open-event-orga-server/pull/721
