### ISSUE TITLE
Add Speakers to a Session

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#502]
Organizer should be able to add speakers to a particular session.

**Comment by rafalkowalski** [comment]
@SaptakS Maybe during scheduling process when organizer click on session, he will be able to edit and add speakers. What do you think?

**Comment by SaptakS** [comment]
Yeah. That can be done. Or while editing session, if the user is organizer, we can give him an option to add speakers maybe.. We can keep both functionalities I think.

**Comment by SaptakS** [comment]
@mariobehling @rafalkowalski This will be handled in https://github.com/fossasia/open-event-orga-server/issues/632 . Thus closing this issue.
