### ISSUE TITLE
[gsoc2016] Fix all js and css codacy issues

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#507]
https://github.com/fossasia/open-event-orga-server/pull/434

**Comment by niranjan94** [comment]
@shivamMg while you're fixing this issue, could you leave the following js/css files untouched ? I'm working on them and it'll be better if there are no conflicts. I'll fix the issues in these files myself.

1. `open_event/static/css/admin/scheduling.css`
2. `open_event/static/js/jquery/jquery.codezero.js`
3. `open_event/static/js/admin/event/scheduling.js`

**Comment by shivamMg** [comment]
@niranjan94 Are these custom generated files?

Also, these are the external libraries in use:

- jscolor
- pnotify (seems to be custom generated, is it?)
- SmartWizard
- google-material-color

Can you confirm? I need to put them as bower dependencies.
