### ISSUE TITLE
Sort unscheduled sessions alphabetically

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#511]
The list of unscheduled sessions can be sorted alphabetically based on the session title so that it's easier for the organizer to find a session.

**Comment by mariobehling** [comment]
Please refer to issue #548

**Comment by niranjan94** [comment]
@mariobehling I'm not talking about the table here. This is the list of the unscheduled sessions that are displayed in the Scheduler UI. So, this is a different issue from #548.

**Comment by mariobehling** [comment]
@niranjan94 Please provide a screenshot. So we can understand this more easily.

**Comment by niranjan94** [comment]
The list of unscheduled sessions that is show here :
![capture](https://cloud.githubusercontent.com/assets/2404372/15805823/93c512d4-2b52-11e6-9c49-841aa10ed77d.PNG)

**Comment by mariobehling** [comment]
Thanks. Where can I test this? Please set it up online to test for us.

* [ ] Please avoid scroll bars inside the page as shown on the right hand side of your page. Just extend the length of the page
