### ISSUE TITLE
Edit a session from the timeline 

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#513]
Allow the organizer to edit a session from the Scheduler UI's timeline itself. The organizer must be able to modify basic aspects of the session (title, description, abstract timings, etc)

(As suggested by @rafalkowalski in #502 )

**Comment by SaptakS** [comment]
Interface: https://github.com/fossasia/open-event-orga-server/issues/515
View: https://github.com/fossasia/open-event-orga-server/issues/516
