### ISSUE TITLE
Option to export timeline as ical

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#514]

**Comment by SaptakS** [comment]
@rafalkowalski @juslee @niranjan94 Needed some suggestion on how to do this. There is a library called [ical.js](https://github.com/nwcell/ics.js) which I think can be used. What do you all think?

**Comment by aviaryan** [comment]
I think it is better if the generation of ical is done from server side. There is an even a basic functioning version available in the orga-server. Go to `event/1/export/ical` .. We can update it and make it more suitable. 
Having the ical export on server side will also mean less load on client's system.

**Comment by mariobehling** [comment]
@aviaryan @SaptakS Yes, we also need an ical file for the web app. So, if it is generated on the server it seems best.

**Comment by SaptakS** [comment]
@mariobehling @aviaryan created an issue to create ical file on the server #549
