### ISSUE TITLE
Interface to edit Session [Schedule UI]

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#515]
- [x] Open modal on clicking edit on a session
- [x] Form in modal to edit session

**Comment by mariobehling** [comment]
Please provide screenshots of the UI. Usually they should be provided beforehand.

**Comment by SaptakS** [comment]
@mariobehling the screenshots of the UI are provided in the Pull Request.

**Comment by SaptakS** [comment]
![screenshot from 2016-06-03 17 27 46](https://cloud.githubusercontent.com/assets/9530293/15798456/dfd03494-2a56-11e6-9093-e1eabfc4d008.png)

@mariobehling @juslee @rafalkowalski here are the screenshots.

**Comment by SaptakS** [comment]
@mariobehling @rafalkowalski @juslee can you verify if this issue is completed?

**Comment by mariobehling** [comment]
@SaptakS Cannot see this completed in the live version. I am moving to testing the live version from now on. Please show it, so we can confirm it is working online here http://open-event.herokuapp.com

**Comment by SaptakS** [comment]
@mariobehling the heroku deployment isn't completed. None of the bower dependencies have been installed. So can't show in the live version. The Scheduling UI isn't functional in the live version.

**Comment by mariobehling** [comment]
@SaptakS If you know how to do it, please help Rafal or feel free to set up the system somewhere else.

**Comment by SaptakS** [comment]
@mariobehling I am already doing it. But I don't understand how this specific issue is related to heroku deployment?

**Comment by mariobehling** [comment]
> I am moving to testing the live version from now on. Please show it, so we can confirm it is working online

Also deploy new features and bugs solved somewhere, where we can test. Apparently a number of team members do not know how to set up the project online and enable people to do it with ease. So, this should be part of the development process then.

Please always provide a link where we can test new development from now on.

**Comment by SaptakS** [comment]
@mariobehling on it.
