### ISSUE TITLE
Save the edit session info to backend[Schedule UI]

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#516]
- [x] Submit form data through ajax. (#673)
- [x] Update info in the schedule UI frontend. (#673)

**Comment by rafalkowalski** [comment]
@SaptakS We need to send an email to speaker that some info was changed

**Comment by SaptakS** [comment]
@rafalkowalski thats a nice idea.

**Comment by mariobehling** [comment]
@rafalkowalski @SaptakS Please implement the main feature first. We can implement "send update to speaker" in a second step. This can be done like at Google Calendar after a user edits the calendar and saves, there is a pop up message "Do you want to inform other participants of changes? | Send Email | Cancel"
