### ISSUE TITLE
Unique constraint for track name

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#52]
@rafalkowalski There can be only one track with a particular name in a given event, So, there should be a unique constraint there.

**Comment by rafalkowalski** [comment]
@mananwason I resolved it You can check it here http://glacial-earth-2730.herokuapp.com/admin

**Comment by mananwason** [comment]
@rafalkowalski I don't have permissions, please give me right to change records.

**Comment by rafalkowalski** [comment]
@mananwason Only owner of event can add tracks ;)

**Comment by mananwason** [comment]
@rafalkowalski then can you add me as a owner for one of the events
