### ISSUE TITLE
Create a model to store the json received from app-generator webpage

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-orga-server#522]
As discussed with @aviaryan, we'll be needing to store the input data received from [here](http://fossasia.github.io/open-event-android/) and then make the json file available for download.
I have already converted the data to json object and need to store them to a database.
For now we need to store only the Email, App's Name and API Link but in future, we will be needing to store 4 more json files if the user chooses to upload them manually instead of providing us with an API.
Cheers.

**Comment by aviaryan** [comment]
We can create a model "CustomApp" with fields email, app_name, api_link and text fields for the json files to store the data. And then make the json response fetchable from `openevent.com/api/v2/customapps/id`. 
The json you get from above url will be like
```js
{
  "email": "a@b.com",
  "app_name": "something",
  "api_link": "http://link.com",
  "speaker_json": "openevent.com/api/v2/customapps/id/speakers.json",  // empty if not applicable
  "session_json": "openevent.com/api/v2/customapps/id/sessions.json"
}
@the-dagger Sounds good ??

**Comment by the-dagger** [comment]
Sounds great. 👍 
@mananwason have a look.

**Comment by the-dagger** [comment]
@aviaryan there are 2 more json files that the user can upload which are `Json for tracks` and `Json for locations`, so please add those fields too in the model.
I have made the edit in your comment.
Cheers.

**Comment by aviaryan** [comment]
@the-dagger I know. I had left them intentionally, was too lazy to write them. :stuck_out_tongue_winking_eye: 
btw, is this issue urgent or can it wait for a day or two. I have planned different things today so might not be able to work on it.

**Comment by mananwason** [comment]
@aviaryan Yes this issue is really urgent. Please implement this asap as we need to resolve this on the android side as well by tomorrow. Thanks

**Comment by aviaryan** [comment]
@mananwason Ok. I will work on it tonight or tomorrow morning after doing #528

**Comment by mariobehling** [comment]
@mananwason @the-dagger I am confused why this is urgent and why this needs to be implemented right away in the server. As far as I can see, it is urgent for the Android app project to have a generator. As @juslee mentioned many times as a first step it is enough to use existing JSON files. Please focus on this.

**Comment by mariobehling** [comment]
> I have already converted the data to json object and need to store them to a database.

@the-dagger Why do we need to store data in a database? Aren't there simpler ways to do this? How about defining a JSON for that as well? A database for a few entries seems overkill.

**Comment by mananwason** [comment]
@mariobehling We are working on setting the app generator on a digital ocean server, we have the script for generating the apk ready but to make it customisable, we need to test it with the inputs from the user. @the-dagger says that we will have to store the data on the server and then make a GET request for the file. The file is then added to the directory and packaged as an apk.
> 
>

**Comment by the-dagger** [comment]
@mariobehling We are storing the object to a db as I had discussed this with @aviaryan and he suggested for the same.
The server will then provide us with a URL in flash for these files so that they can be packaged while building the app on DigitalOcean.

**Comment by mananwason** [comment]
@mariobehling @the-dagger This is working fie with Firebase for now, so closing it.
