### ISSUE TITLE
Deploy to heroku doesn't work

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#523]
- [ ] add node js to heroku

**Comment by aviaryan** [comment]
Is nodejs being used in the project ? What is the exact problem here ?
I was trying to deploy development branch to my heroku but faced issues. Dropping database and re-initializing project didn't work. Thus I opened #528 and am working on it.

**Comment by shivamMg** [comment]
@aviaryan node -> npm -> bower

**Comment by aviaryan** [comment]
@shivamMg LOL :smile: I almost forgot about that. No wonder why the UI looked so blank. So the need in this issue is to run `bower install` on heroku so that frontend dependencies are loaded, right ?

**Comment by aviaryan** [comment]
@rafalkowalski We will need access to the heroku open-event app for this. Do you have access ?
I will like to do this but only tomorrow.

**Comment by rafalkowalski** [comment]
Please give me your email

**Comment by aviaryan** [comment]
avi.aryan123@gmail.com

**Comment by rafalkowalski** [comment]
done

**Comment by aviaryan** [comment]
After fixing this, should I send a PR to development or master ? @rafalkowalski

**Comment by rafalkowalski** [comment]
development

**Comment by niranjan94** [comment]
Fixed now :smile: ... closing !

**Comment by aviaryan** [comment]
@niranjan94 please assign issue to yourself before working on it. I too had the patch ready but was late by about 10 mins. :smile:

**Comment by niranjan94** [comment]
@aviaryan Oh ... I'm sorry ... I noticed this issue only after fixing it. My apologies :sweat_smile:

**Comment by aviaryan** [comment]
@niranjan94 no problem. :smile_cat:
