### ISSUE TITLE
Create branch Development

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#524]
We need this branch, because we need to test everything before we will send changes to master branch.

Once a week someone will be responsible to merge this branch with master(in near future we can do it automatically). 
This solution allows us to make a release! 😄  

What do you think guys @SaptakS @niranjan94 @aditya1702 @juslee @aviaryan @shivamMg  ?

So please make pull request to development branch

**Comment by niranjan94** [comment]
@rafalkowalski good idea :+1:

**Comment by aditya1702** [comment]
@rafalkowalski I think this is nice idea! :+1:

**Comment by aviaryan** [comment]
Good idea. :+1: We can work on week days and have the merge to master done sometime in weekends. 
I have setup https://open-event-test.herokuapp.com to automatically deploy the development branch but encountered an issue (#528) . @rafalkowalski Please see

**Comment by SaptakS** [comment]
@rafalkowalski This is a good idea.
