### ISSUE TITLE
Problem with javascript dependencies

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#525]
#529 
![screen shot 2016-06-04 at 01 01 32](https://cloud.githubusercontent.com/assets/2479753/15795221/02df00da-29f0-11e6-8cba-b336cc04a33f.png)

**Comment by shivamMg** [comment]
@rafalkowalski You need to install bower dependencies. Go to the root where `bower.json` resides and do a `bower install`.

**Comment by SaptakS** [comment]
@shivamMg the problem wasn't in `bower install` . I believe @rafalkowalski had already done that. The problem was that you didn't change the smartWizard.js link in a file.
