### ISSUE TITLE
Frontend (css, js) not working

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#529]
Some of the styling seems to be not working in the master branch. For example, 
- [x] Styling for buttons in create new event is not working.
![screenshot from 2016-06-04 01 29 30](https://cloud.githubusercontent.com/assets/9530293/15798512/a3344410-2a58-11e6-9833-b66bbeea5771.png)

- [x] Styling in edit event seems to be messed up.
![screenshot from 2016-06-04 01 32 01](https://cloud.githubusercontent.com/assets/9530293/15798531/306705e8-2a59-11e6-8e27-03d1f6e6a28a.png)

- [x] Datetimepicker not working in Edit Session  ( [Shown Here]( https://github.com/fossasia/open-event-orga-server/issues/529#issuecomment-223749208) )

**Comment by SaptakS** [comment]
@rafalkowalski @shivamMg The code written in SmartWizard we had locally is different from the one installed through bower.
For example:

Local js file
![screenshot from 2016-06-04 02 28 03](https://cloud.githubusercontent.com/assets/9530293/15798734/e64228c8-2a60-11e6-8047-95330ca2098b.png)

js file installed from bower:
![screenshot from 2016-06-04 02 28 36](https://cloud.githubusercontent.com/assets/9530293/15798737/f2586fa0-2a60-11e6-8424-4c3849f07fd1.png)

Thus this is messing up the styling.

**Comment by SaptakS** [comment]
Updated new.js to add the bootstrap classes to the buttons in PR #533 

Before:
![screenshot from 2016-06-04 01 29 30](https://cloud.githubusercontent.com/assets/9530293/15799098/397283e0-2a6f-11e6-83fe-00b3b06fd5f6.png)

After:
![screenshot from 2016-06-04 04 09 53](https://cloud.githubusercontent.com/assets/9530293/15799099/41242fb2-2a6f-11e6-86ac-b74f20d32ab9.png)

**Comment by rafalkowalski** [comment]
![screen shot 2016-06-04 at 12 46 18](https://cloud.githubusercontent.com/assets/2479753/15799114/6622707a-2a52-11e6-870d-b7b2776a116a.png)

**Comment by SaptakS** [comment]
@rafalkowalski on it.

**Comment by SaptakS** [comment]
@rafalkowalski https://github.com/fossasia/open-event-orga-server/pull/535 fixes the issue.

**Comment by SaptakS** [comment]
@rafalkowalski @aditya1702 @shivamMg I guess this issue can be closed. Please verify.

**Comment by rafalkowalski** [comment]
@SaptakS color-picker has a bug ;p

**Comment by rafalkowalski** [comment]
@SaptakS @shivamMg @niranjan94 
![screen shot 2016-06-04 at 12 46 18](https://cloud.githubusercontent.com/assets/2479753/15799409/ee279ea6-2a5b-11e6-8a7b-3013f994708b.png)

**Comment by shivamMg** [comment]
@rafalkowalski I've fixed the datepicker and moment links here: https://github.com/fossasia/open-event-orga-server/pull/542

**Comment by SaptakS** [comment]
@shivamMg merged. @rafalkowalski can you please check once. It should be fixed now I guess.
