### ISSUE TITLE
Slogan field no longer in Event model

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#534]
The following error comes when trying to POST an event. Travis CI was not able to catch it because the event model was not tested for creating events. (due to issue with SQLite date time)
```
    new_event = EventModel(**self.api.payload)
TypeError: __init__() got an unexpected keyword argument 'slogan'
127.0.0.1 - - [04/Jun/2016 16:20:46] "POST /api/v2/events HTTP/1.1" 500 -
```

**Comment by aviaryan** [comment]
Also url is event_url

**Comment by SaptakS** [comment]
@rafalkowalski @juslee I had the same issue while testing the APIs for iCal export. Should we have the slogan field? And what about the event_url? We need to make the changes accordingly.

**Comment by aditya1702** [comment]
@SaptakS @aviaryan earlier we are not storing any data from the form to the slogan field of the event. So why do we require the slogan field. Also we are using two urls in the form - one for background , for which I created a column and other is event_url which is getting stored in the event_url field
