### ISSUE TITLE
Sign in with Google sends me to localhost

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#546]
http://open-event.herokuapp.com/

http://localhost:8001/gCallback?state=KSWNUPskXcFa92AMQ0NSz5PjPhTWoU&code=4/sLamGaCxmCm5HSPpuZzLNBoX-BPsihmvFc4KaluuHJw#

**Comment by rafalkowalski** [comment]
@mariobehling I will fix it

**Comment by aditya1702** [comment]
@rafalkowalski This is because I have included localhost as the address in my Google Developers Console through which i acquired the client secrets and ids. Let me do this I will add the address for the heroku app

**Comment by rafalkowalski** [comment]
@aditya1702 No! It shouldn't be manually added

**Comment by aditya1702** [comment]
@rafalkowalski I dont think there is any other way. http://stackoverflow.com/questions/23717452/how-to-add-multiple-redirect-uris-for-google-oauth-2

**Comment by aditya1702** [comment]
@rafalkowalski I am not talking about adding it in the code...I am talking about adding it to the list of redirect uris in Google Developers Console. If it is not in that list it wont get redirected even if we add that url to our code.

**Comment by rafalkowalski** [comment]
ok i didn't know
