### ISSUE TITLE
Do not require username, only use email address as login

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#547]
The signup pages requires a username. Not sure why this is necessary. Please compare to sign up procedure of eventbrite for example. Simply use email address.

**Comment by rafalkowalski** [comment]
@aditya1702 Please check

**Comment by aditya1702** [comment]
Ok will do

**Comment by aditya1702** [comment]
@mariobehling The register page will take in the user name just for the data but the login page will have only email and password fields. Is this ok?

**Comment by mariobehling** [comment]
@aditya1702 No need for username. Email is the username. Please keep it simple. Why make it complicated? We referred many times to other service Eventbrite, Eventnook, any social media. Please check there again and keep everything super easy for users in future.

**Comment by aditya1702** [comment]
@mariobehling Ok
