### ISSUE TITLE
Use ColorType field in color field of track model

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#565]
Event model uses a ColorType field `color = db.Column(ColorType)`
Maybe the same should be used for track

@aditya1702 what do you think ?

**Comment by aviaryan** [comment]
anyone willing to work on the issue please assign themselves.

**Comment by aditya1702** [comment]
@aviaryan What is the difference in db.String and db.ColorType? I mean presently the colour is saved to the db

**Comment by aviaryan** [comment]
ColorType takes care of validating the color. It will not accept any random string as color. That's all.. 
I am validating the color fields in the api so any non-color string won't be able to get in the database, atleast from the api side.
Now when I see the docs, I don't see any real advantage of using colortype in our case. 
http://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.color

If you think the same, feel free to close this issue.

**Comment by aditya1702** [comment]
@aviaryan I think that wont be necessary since the color string will be generated by the colorpicker. Hence it will be completely valid.
