### ISSUE TITLE
Wizard line corrections and order

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#566]
![screenshot from 2016-06-05 15 10 42](https://cloud.githubusercontent.com/assets/1583873/15805590/b49da264-2b2f-11e6-9932-e50bbea00a31.png)

I see a number of errors in the text of the green line wizard. Let's keep it simple and avoid mistakes.
* [x] No need for description or menu items (Please take out descriptions of steps, e.g. "Define session types in session")
* [x] Name menu points as follow:
 * Event Details
 * Session Types
 * Tracks
 * Social Media

What about rooms? If they are included in the wizard also add them please as a point:
 * Rooms

**Comment by aditya1702** [comment]
@mariobehling there are some columns in the database for event which we are not using...email and color..Should we remove them?

**Comment by mariobehling** [comment]
@aditya1702 How is this related to this issue? We probably need color and email later. Let Rafal follow up on this later and let's keep the topic in issues.

**Comment by rafalkowalski** [comment]
@mariobehling can we close this?
