### ISSUE TITLE
How do you plan to handle room assignments

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#568]
The question for the rooms is essential for building the schedule. If a track is in a room, there should be an option in the UI "tick here if all tracks run in a dedicated room" or something similar.

If tracks could run across different rooms the schedule should be build according to rooms.

There also should be a wizard point "rooms" or it should appear together with "tracks". Please tell us how shdlr.com and other handle this.

**Comment by niranjan94** [comment]
@mariobehling shdlr.com does the scheduling only based on rooms.

**Comment by mariobehling** [comment]
Yes, we need to go with rooms for practical reason, but should have an option "Track = Rooms". We also need to distinguish sessions with some color.

**Comment by mariobehling** [comment]
@niranjan94 Please provide info how you plan to implement this, if you are working on this.

**Comment by niranjan94** [comment]
The user will be able to schedule the sessions into their respective rooms by drag-dropping the sessions into the rooms.

If there is a clash, the user will be notified. He/she will not be able to drop the session onto another session.

 shdlr.com handles it in a similar fashion.

![capture](https://cloud.githubusercontent.com/assets/2404372/15822141/b0dbfcba-2c11-11e6-921b-9168517c907f.PNG)

**Comment by SaptakS** [comment]
@niranjan94 seems good to me..

**Comment by SaptakS** [comment]
@mariobehling @rafalkowalski can you please confirm if we can move on with this prototype? I and Niranjan would then start working on the Schedule UI based on this prototype. Else we are unable to work on the other Schedule UI features. Please confirm. Thanks.

**Comment by mariobehling** [comment]
@SaptakS Yes, great. Let's do it.
