### ISSUE TITLE
Make Event creation form responsive

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#581]
The map overlaps the form for smaller viewports.

**Comment by mariobehling** [comment]
Please refer to https://github.com/fossasia/open-event-orga-server/issues/324 and have a look like how map stuff works there when you add an event. This is the desired way.

**Comment by shivamMg** [comment]
I'm working on API issues right now, so if anyone's interested please assign yourself the issue.

**Comment by mariobehling** [comment]
Please make the creation form into one column and replicate the behaviour of the map as in Eventbrite.
