### ISSUE TITLE
Add pnotify modules that are in use

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#582]
Add desktop and button modules for pnotify.

**Comment by niranjan94** [comment]
@shivamMg I don't think we need PNotify ... I have a simple SnackBar implementation that I'm using over here https://github.com/fossasia/open-event-orga-server/blob/master/open_event/static/js/jquery/jquery.codezero.js#L157 . It is very lightweight and easy to use. 

AFAIK, PNotify is being used only in two place, `open_event/templates/gentelella/admin/event/details/steps/call_for_papers.html` and `open_event/templates/gentelella/admin/event/details/steps/scheduling.html` ... I can migrate both to the SnackBar implementation without any loss of functionality. After that we can remove PNotify entirely.

**Comment by niranjan94** [comment]
In fact, `open_event/templates/gentelella/admin/event/details/steps/scheduling.html` doesn't use PNotify anymore.

**Comment by SaptakS** [comment]
@niranjan94 if SnackBar is lightweight and is easier to handle, then go for it. I think it is better anyways to have anyone of them. Keeping both doesn't make sense. Lets stick with SnackBar then.

**Comment by niranjan94** [comment]
Alright @SaptakS ... 
@shivamMg ... I'm closing this issue now ...
