### ISSUE TITLE
Check password also while logging in

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#590]
The bug is that if we register an email address and password and then do a login , then there is no check on the password. If the email address is correct then the user can log in irrespective of what password he/she has entered.

**Comment by mariobehling** [comment]
Please describe this bug. What does it mean? Any relevant screenshot?

**Comment by niranjan94** [comment]
@mariobehling it means anyone can log into the administration panel by just typing someone's email address and some random text for the password.
