### ISSUE TITLE
Fix Schedule UI in heroku deployed version

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#594]
The track API gives 500 status error causing interruption in loading of sessions. As a result the Schedule UI doesn't seem to work in the live version

**Comment by aviaryan** [comment]
I think this is because track model was changed recently (track.color added) and the server has not upgraded its database yet .

**Comment by SaptakS** [comment]
@aviaryan I think the same.

**Comment by aviaryan** [comment]
Fixed it by re-creating the database on the server. @SaptakS please check

**Comment by SaptakS** [comment]
Works great @aviaryan.
