### ISSUE TITLE
Add missing fields to Event API

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#598]
Event model contains fields like "state", "closing_datetime", etc. that have not been included in the API.

**Comment by mariobehling** [comment]
Please check that you cover all fields as used in the last OpenTechSummit JSONs
https://github.com/OpenTechSummit/2016.opentechsummit.net/tree/gh-pages/programm/json

The rendered schedule is here: http://opentechsummit.net/programm

**Comment by shivamMg** [comment]
@mariobehling :+1: There were some fields that were included in the database models but were not included in the api models. I've added them now.

**Comment by shivamMg** [comment]
Implemented at: https://github.com/fossasia/open-event-orga-server/issues/605
