### ISSUE TITLE
Validation should be added to models(Speaker, Event etc.)

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#6]
We have to define which columns should be validated

**Comment by rafalkowalski** [comment]
@mariobehling @leto @championswimmer  Could you tell me which columns should be required or optional? 

I have a suggestion which columns should be required, but I don't know that it will be correct.
My proposition:
Event: 
    -name(required)
    -start_time(required)
    -end_time(required) 
    -latitude(optional) 
    -longitude(optional)
    -location_nam(optional)
    -logo(optional)

Session:
    title (required)
    subtitle (optional)
    abstract (optional)
    description (required)
    start_time (required)
    end_time (required)
    type (optional)
    track (optional)
    speakers (optional) 
    level (optional)
    microlocation (optional)
Track:
    name (required)
    description (required)
    session_id (optional)
Speaker:
    name (required)
    photo (optional)
    biography (optional)
    email (required)
    web (optional)
    twitter (optional)
    facebook (optional)
    github (optional)
    linkedin (optional)
    organisation (required)
    position (optional)
    country (required)

Sponsor:
   name (required)
   url(optional)

**Comment by leto** [comment]
Looks good! Let the code flow...

**Comment by rafalkowalski** [comment]
I fixed it
