### ISSUE TITLE
Fix POST API testing of event and session model by using custom DateTime field

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#601]
Both Event and session model includes a datetime field which currently can't be tested because it is not possible to write datetime fields as string from SQLAlchemy in a SQLite database (used in Testing). 

However, this issue can be fixed by a using a custom field for DateTime that returns the DateTime object on POST requests. Using a custom DateTime field will also give more control over the datetime 'format'. 

I am currently think about 'YYYY-MM-DD HH:MM:SS' as the DateTime format to be used in the API . 
@niranjan94 @SaptakS Is the format ok w.r.t UI ?

EDIT - Just found out restplus doesn't actually validate the (inbuilt) DateTime fields. It lets it go and psycopg throws the exception. (https://bpaste.net/show/e332f0095399)

**Comment by niranjan94** [comment]
@aviaryan with respect to the scheduling UI, there's no issue. We're anyway parsing the string into a moment object and using that. So, any recognizable format would be fine. `YYYY-MM-DD HH:MM:SS` is cool :+1:
