### ISSUE TITLE
Add token based authentication in API

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#603]
A (access) token based auth should be added side-by-side with the current basic auth in the API.
Here are my views on it, 

token - will be a random string stored in the User model as field `token`

To get token the user will send a post request with the credentials to the following urls - 
1. The current url for UI login is `\admin\login` . The view function responsible for it can store the token as cookie if username-password is correct. (as is already done in PR #600 by @niranjan94 )
2. To get token using API, we can create a url like `\api\v2\login` where user details and token will be returned in case of right username-password. 

Any request can then use the token to access protected methods by setting the header `Authorization` 
as `Token <token>`. 

Once a token is created for a user, it will be returned as-is in all login requests and not be re-created. (This will allow a user to be login'd from android and serverUI at the same time). 
Only on 'forgot password' will the the access token be re-created. 

@niranjan94 @shivamMg @rafalkowalski views ?

**Comment by niranjan94** [comment]
Seems to be good :+1: 

I have a suggestion for token handling. When a token is generated, it could be stored on a **separate Token model** with reference to the User to whom the token belongs to along with an **expiry time**. This is a bit similar to OAuth and gives us more control over tokens. Also, a single user can have multiple tokens too.

**Comment by aviaryan** [comment]
@niranjan94 Can you please ellaborate why using an expiry time is useful. Sure it is great when someone has gained access to your 'token' but wouldn't it cause problems for the users as they would have to login time and again to fetch the token. 
Also what should be the ideal expiry time ?
Also please have a look at #610

**Comment by niranjan94** [comment]
Ideal expiry time, we could keep it a day maybe. Also, all the GET APIs could be made open without any authentication but with [Throttling](https://api.stackexchange.com/docs/throttle) enabled. So, webapps and android app wouldn't require a token. 

The admin panel, would generate a token on login. So that would be sufficient for his/her entire session.

**Comment by aviaryan** [comment]
> Ideal expiry time, we could keep it a day maybe.

:+1: 

> Also, all the GET APIs could be made open without any authentication but with Throttling enabled. 

GET APIs are totally open right now however no throttling has been set. I looked on the web and found [Flask-Limiter](https://github.com/alisaifee/flask-limiter) to be close to what we need. We can add the rate-limiter feature later in the project, it does no good right now.

**Comment by shivamMg** [comment]
@aviaryan Should I close this one as well?

**Comment by aviaryan** [comment]
Yes
