### ISSUE TITLE
Use JWT for API authentication

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#610]
See #603 for previous version

[GSoC docs](https://github.com/fossasia/open-event/blob/master/docs/GSOC2016/rest-api.md) says we should be using JWT for API authorizations. 

I read about JWT today and it looks really good . The main advantage I find of JWT is that it is self-contained. A JWT contains all information about the user which eliminates the need to look in database for every request.

These links should be useful
Intro to JWT https://jwt.io/introduction/
On using JWT https://auth0.com/learn/json-web-tokens/
Flask-JWT package docs https://pythonhosted.org/Flask-JWT/

I plan to implement jwt based authentication in the API using Flask-JWT. 

Note - This issue is an extension to #603 (token based auth). I didn't want to delete what has been said there so opened a new one.

**Comment by aviaryan** [comment]
@shivamMg I have almost done this issue locally. In it, there is a login endpoint `api/v2/login` where user sends username and password and gets the JWT . 
Should I add it to swagger UI or not ?

**Comment by shivamMg** [comment]
I think it should be included in the Swagger UI.

**Comment by aviaryan** [comment]
@shivamMg Okay. I have included it now.
