### ISSUE TITLE
Creation of duplicate events on creating an event.

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#62]
I created this event and another one with same attributes was created.
![image](https://cloud.githubusercontent.com/assets/10570249/8366062/469cb33a-1baf-11e5-983a-b4af05b2a394.png)

**Comment by rafalkowalski** [comment]
can we solve this unique name?

**Comment by mananwason** [comment]
I think keeping a unique event will solve the issue but there is some bug in the code that needs to be solved. What do you think @leto

**Comment by leto** [comment]
@rafalkowalski yes, there should be a UNIQUE constraint on the name of events and tracks.

**Comment by rafalkowalski** [comment]
@leto I added unique constraint You can see it here :) https://github.com/fossasia/open-event-orga-server/commit/9be0bab1a3f70934a63e1667cff8cf9e3d3f063e
