### ISSUE TITLE
Event Stage 5 name: Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#620]
Project Issue #306 Event Status 5: Event is running
* [ ] Enable user to add more data and media and generate new app versions for last minute changes
* [ ] Enable automatic tweet capabilities (e.g. tweet sessions of schedule according to time)

**Comment by aditya1702** [comment]
@mariobehling I have started work on the live media thing. Do you want it to be displayed here on this page?
![live_media](https://cloud.githubusercontent.com/assets/15054664/16245479/b9009464-381e-11e6-872e-592d8d8973cc.png)

**Comment by mariobehling** [comment]
@aditya1702 Live media is simply a link to youtube at the moment. The link should show up in the schedule.

I am closing this issue as it adds too much complexity at the moment and we have too many bugs.
