### ISSUE TITLE
Make JSON data consistent with current version of Open Event Scraper

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#624]
Please check out Open Event Scraper of the OpenTechSummit. We have added all kinds of data, that should also be reflected in future versions of JSON files and APIs of the orga server.

Are there any questions about this?

Links:
Scraper: https://github.com/OpenTechSummit/open-event-scraper
JSON Files: https://github.com/OpenTechSummit/2016.opentechsummit.net/tree/gh-pages/programm/json

**Comment by shivamMg** [comment]
We need to define the fields at the database models first and reflect the same at the APIs. Models that require changes are Tracks, Sessions and Sponsors. I guess working on one model at a time would be best. I'll be working on sessions.

**Comment by aviaryan** [comment]
@mariobehling I think this issue is complete. 
Missing fields have been added in tracks , session and sponsors. There is one field `header_line` in [OTS tracks json](https://github.com/OpenTechSummit/2016.opentechsummit.net/blob/gh-pages/programm/json/tracks.json) but we don't understand what it is so it has not been added. 

Sessions
```json
{
    "audio": "string",
    "comments": "string",
    "end_time": "2016-06-06 11:22:33",
    "id": 0,
    "language": {
      "id": 0,
      "label_de": "string",
      "label_en": "string"
    },
    "level": {
      "id": 0,
      "label_en": "string"
    },
    "long_abstract": "string",
    "microlocation": {
      "id": 0,
      "name": "string"
    },
    "short_abstract": "string",
    "signup_url": "http://website.com",
    "slides": "string",
    "speakers": [
      {
        "id": 0,
        "name": "string"
      }
    ],
    "start_time": "2016-06-06 11:22:33",
    "subtitle": "string",
    "title": "string",
    "track": {
      "id": 0,
      "name": "string"
    },
    "video": "string"
  }
```

Tracks
```json
 {
    "color": "green",
    "description": "string",
    "id": 0,
    "location": "string",
    "name": "string",
    "sessions": [
      {
        "id": 0,
        "title": "string"
      }
    ],
    "track_image_url": "http://website.com/image.ext"
  }
```

Sponsors
```json
{
    "description": "string",
    "id": 0,
    "level": "string",
    "logo": "http://website.com/image.ext",
    "name": "string",
    "sponsor_type": "string",
    "url": "http://website.com"
  }
```

**Comment by mariobehling** [comment]
Ok, thanks! Looks good.
