### ISSUE TITLE
Set up Continuous Deployment on Testing Server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#625]
Currently, we do not have a server that shows the latest development version in the repository. In order to test early and involve more people, we need to have new features online more quickly.

Please implement Continuous Deployment on the testing server.

**Comment by aviaryan** [comment]
I think the development branch of this project is auto-deployed to http://open-event.herokuapp.com . Isn't that right, @rafalkowalski ?

**Comment by rafalkowalski** [comment]
yes it is, @mariobehling will it be enough ?

**Comment by mariobehling** [comment]
Just realize, that all kinds of data has to be entered to see all features. Is it possible to have a sample data set in the app?
