### ISSUE TITLE
Add missing fields for Sessions

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#627]
Add missing fields to Sessions api and database models.

https://github.com/fossasia/open-event-orga-server/issues/624

**Comment by aviaryan** [comment]
@shivamMg are you working on this ?

**Comment by shivamMg** [comment]
@aviaryan I'm working on other things right now. You can take this up if you like. There are four fields "slides", "video", "signup", "audio". Signup should be URL, rest others must either be uploadable media or urls.

**Comment by SaptakS** [comment]
@aviaryan are you making the changes in the session table as well? I have a similar issue https://github.com/fossasia/open-event-orga-server/issues/631 . So, if you are making changes to table I will wait for the table creation otherwise there will be merge conflicts.

**Comment by aviaryan** [comment]
@SaptakS Ok, I will try to send a PR soon.

**Comment by SaptakS** [comment]
@aviaryan great..
