### ISSUE TITLE
Create Event Wizard Step 1: Event Details

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#634]
Parent issue: https://github.com/fossasia/open-event-orga-server/issues/324

**Step 1. EVENT DETAILS:**
- [x] Event Name
- [x] Location and Map
- [x] Starts/Ends (incl. Timezone Settings)
- [x] Event Image
- [x] Event Logo
- [x] Event Description
- [x] Organizers
- [x] Social Media

About Publishing
- [ ] Publish Button -> Result event is published on a page with basic info, but no Call for Speakers is on the page yet

Please take some inspiration from Eventbrite for example: 

![screenshot-www eventbrite com 2016-06-05 10-26-54](https://cloud.githubusercontent.com/assets/1583873/15805519/7826781c-2b2d-11e6-98d8-cfacaaf80116.jpg)

**Comment by niranjan94** [comment]
@mariobehling This is the UI prototype 

![screencapture-localhost-5000-events-create-1465901260742](https://cloud.githubusercontent.com/assets/2404372/16040159/9d161144-324b-11e6-887b-5f2438cf3433.png)

**Comment by niranjan94** [comment]
**Step 2: Sponsors**

![screencapture-localhost-5000-events-create-1465910922422](https://cloud.githubusercontent.com/assets/2404372/16044461/29b33242-3262-11e6-99e4-f984e49b1154.png)

**Step 3: Session, tracks, rooms:**

![screencapture-localhost-5000-events-create-1465910932338](https://cloud.githubusercontent.com/assets/2404372/16044476/35ba9238-3262-11e6-9b20-30d73c52eb7d.png)

**Step 4: Call for speakers**

![screencapture-localhost-5000-events-create-1465910941235](https://cloud.githubusercontent.com/assets/2404372/16044499/42310ad8-3262-11e6-9d9f-15704c76cf18.png)

@mariobehling please review and let me know if there are any suggestions/improvements

**Comment by mariobehling** [comment]
Ok, good progress. Did you test if this works also on smaller screens and mobile devices? Please do not post other steps in this issue (I deleted it to avoid confusion). Only post Step 1 improvements in this issue.

Please:
* [ ] implement 2 areas for beginning and end of event

I guess we should create separate issues for implementation of more detailed requirements.

Please make the date change, check if it works for mobile and commit.

Cheers.

**Comment by niranjan94** [comment]
@mariobehling alright ... Sorry about that ... I'll post the improvements in their respective issues ..

1. Yes I have tested it on smaller screens. 
1. The date change, it opens a UI like this. So, that's why I had given a single input box
![capture](https://cloud.githubusercontent.com/assets/2404372/16046006/8212273a-3268-11e6-8d22-a64cdcf45bea.PNG) 

I'll make it into two boxes if that's not needed.

**Comment by mariobehling** [comment]
Two boxes please. Just refer to Eventbrite for now if unsure.

**Comment by mariobehling** [comment]
Also, please show the time as well, preferably in a separate box too.

**Comment by niranjan94** [comment]
@mariobehling okay .. Will do
