### ISSUE TITLE
Create Event Wizard Step 2: Session Types

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#635]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/324

Implement "Create Session Types: in this step.

**Comment by SaptakS** [comment]
@mariobehling @rafalkowalski I guess this step is already completed.

**Comment by SaptakS** [comment]
![screenshot from 2016-06-08 13 39 19](https://cloud.githubusercontent.com/assets/9530293/15887176/6ec7656c-2d7e-11e6-911f-2a67bb172c7b.png)

Step 2 of this link: http://open-event.herokuapp.com/admin/events/new/
