### ISSUE TITLE
Create Event Wizard Step 3: Tracks and Rooms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#636]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/324

Implement Step 3 "Tracks and Rooms" in the Create Event Wizard.

**Comment by mariobehling** [comment]
Thanks. Please post screenshots in issues, when tasks are finished. Cheers.

**Comment by niranjan94** [comment]
**A more refined UI:** (tested on small/mobile screens)
 
![screencapture-localhost-5000-events-create-1465910932338](https://cloud.githubusercontent.com/assets/2404372/16046114/e57b3a32-3268-11e6-9c49-178e1a7c7595.png)

**Comment by mariobehling** [comment]
Looks nice, but the colors are usually used for tracks only in the schedule. Please,
* [ ] Only display color choice for tracks
* [ ] Ensure that it is tested on mobile and displays well in mobile screens.

**Comment by mariobehling** [comment]
For Session Types how can we display a time parameter at length? Could we have HH:MM for example?

**Comment by niranjan94** [comment]
@mariobehling 
- Alright. I'll put color only for tracks.
- Will test on mobile once again
- Yes. We can display a `HH:MM` time picker as the length field. I'll do that too
