### ISSUE TITLE
Create Event Wizard Step 5: Speaker Submission Forms (session submission and profile submission)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#638]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/324

Implement Event Create Step: Speaker Submission Forms 

* [x] Implement create form for session submissions of speakers (Compare #631) (PR - #680 )
* [x] Implement create form for profile submissions of speakers (Compare #632) (PR - #680 )

**Comment by SaptakS** [comment]
@mariobehling do you mean by this that the organizer decides what are the fields that are to be there in the session form and speaker_profile form?

**Comment by mariobehling** [comment]
> @mariobehling do you mean by this that the organizer decides what are the fields that are to be there in the session form and speaker_profile form?

Yes. (We might need to make some basic info as required, maybe email address.)
Please compare to #631 and #632

**Comment by SaptakS** [comment]
@mariobehling , This is the prototype:
![screenshot from 2016-06-10 15 17 23](https://cloud.githubusercontent.com/assets/9530293/15960671/827079a4-2f1e-11e6-894a-a50538cae756.png)

**Comment by mariobehling** [comment]
Please implement it in a more readable way. Please check out Eventbrite how they do it for attendees.

![screenshot-www eventbrite com 2016-06-10 18-02-39](https://cloud.githubusercontent.com/assets/1583873/15970747/76de6fc0-2f36-11e6-91d9-0179ecac7a0b.png)

**Comment by SaptakS** [comment]
@mariobehling already on it..

**Comment by mariobehling** [comment]
@SaptakS As you are posting more screenshots, maybe you could actually use a screenshot module to capture web pages. There are tons of plugins available for all browsers.

**Comment by SaptakS** [comment]
@mariobehling thanks for the suggestion. Will try one.

**Comment by mariobehling** [comment]
Please also add:
* [ ] TITLE FOR THE REGISTRATION PAGE
* [ ] INSTRUCTIONS FOR SPEAKERS
* [ ] MESSAGE TO DISPLAY AFTER CALL FOR SPEAKERS CLOSES
* [ ] ALLOW ATTENDEES TO EDIT INFORMATION AFTER REGISTRATION

**Comment by SaptakS** [comment]
@mariobehling "Add more questions" feature will be a great idea for enhancement. But can we add this features at a later enhancement phase after completing all the Stages of Event workflow first? I think we can work on enhancing features at later phases? What do you suggest?

**Comment by SaptakS** [comment]
@mariobehling  the above mentioned tasks will be completed in https://github.com/fossasia/open-event-orga-server/issues/682 . Hence closing.

**Comment by niranjan94** [comment]
**A more refined UI:** (tested on small/mobile screens) 

![screencapture-localhost-5000-events-create-1465926716072](https://cloud.githubusercontent.com/assets/2404372/16053620/2d381994-3287-11e6-8bdb-3c735348454f.png)

**Comment by mariobehling** [comment]
Nice. Please make a PR for the changes. Better are smaller PRs than bigger ones.

**Comment by niranjan94** [comment]
@mariobehling for the wizard, I had to do a lot of internal template changes to remove code repetition. So, the event wizard, I will have to make a single PR with the changes.

**Comment by mariobehling** [comment]
In the Session Form, I do not know what Level and Format are for. Please take them out.

The options we want for the session forms are:
* [ ] Title
* [ ] Subtitle
* [ ] Short Abstract
* [ ] Long Abstract
* [ ] Session Type (this choice depends on the session type defined by organizers, e.g. workshop, talk etc. #635)
* [ ] Track (this choice depends on the tracks defined by organizers #636)
* [ ] Upload Slides
* [ ] Other Comments for Organizers (will not be shown to public)

**Comment by niranjan94** [comment]
ok @mariobehling  .... I think @SaptakS is working on these here (#682).If not I'll work on these additional fields once I'm done with the wizard.
