### ISSUE TITLE
HOME Open-Event main page

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#650]
#622 
- [x] Create event (big button)
- [x] Upcoming events (boxes of events)
- [x] Call for Speakers (boxes of events)

**Comment by mariobehling** [comment]
* [ ] Home page does not use standard top bar and is not functional therefore.
* [ ] Please add "Open Event" on the top left and make it link to `/` itself.

**Comment by mariobehling** [comment]
@rafalkowalski @niranjan94 Feel free to get it fixed, whoever of both of you has time. Cheers.

**Comment by niranjan94** [comment]
@rafalkowalski I'll work on this now
