### ISSUE TITLE
Session version doesn't change

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#68]
If I change the session while editing tracks, tracks version changes but session version doesn't change. So this causes the session data to be stale in the app. @rafalkowalski Please fix this :D

**Comment by leto** [comment]
@mananwason can you describe more fully exactly how to reproduce this problem? I don't understand from your description.

**Comment by mananwason** [comment]
@leto I am sorry if I was not clear earlier. So, While editing any track, if I change the value of session in it, the tracks version  in the version api changes but the session version doesn't change even though the track value in the session api changes.
 So essentially, the session api values changes on changing session value in track api , hence the session version should also change.

**Comment by leto** [comment]
@mananwason can you provide an example with curl? I think I understand, but that would make it easier to debug

**Comment by mananwason** [comment]
@leto  I am not sure what to do. Please explain a bit. Thanks.
