### ISSUE TITLE
Create Event Wizard Step 5: Add more Features for Speaker Submission Forms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#682]
Follow up to https://github.com/fossasia/open-event-orga-server/issues/638

Please add:
* [ ] Button "Add more questions"
* [ ] Subform with more questions

~~Also add form areas:~~
* ~~TITLE FOR THE REGISTRATION PAGE~~ 
* ~~INSTRUCTIONS FOR SPEAKERS~~ 
* ~~MESSAGE TO DISPLAY AFTER CALL FOR SPEAKERS CLOSES~~ 
* ~~ ALLOW ATTENDEES TO EDIT INFORMATION AFTER REGISTRATION~~
Let's do this later. (@mariobehling)

_Added on 14-Jun-2016_

The options we want for the session forms are:
* [x] Title
* [x] Subtitle
* [x] Short Abstract
* [x] Long Abstract
* [x] Session Type (this choice depends on the session type defined by organizers, e.g. workshop, talk etc. #635)
* [x] Track (this choice depends on the tracks defined by organizers #636)
* [x] Upload Slides
* [x] Other Comments for Organizers (will not be shown to public)

**Comment by SaptakS** [comment]
@mariobehling presently "short abstract" is refered as "abstract" and "long abstract" as "description". Should I change that?

**Comment by mariobehling** [comment]
yes, please. Follow up issue with more things to change is here: https://github.com/fossasia/open-event-orga-server/issues/843

**Comment by SaptakS** [comment]
Great

**Comment by mariobehling** [comment]
Current implementation seems ok, but we need to test this in more detail. Please add tests with robotframework https://github.com/fossasia/open-event-orga-server/issues/2233
