### ISSUE TITLE
Add Version Number to Dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#683]
Currently it is not obvious which version of the app is deployed on the test server. Please implement the version info and if possible link to the dashboard.

**Comment by rafalkowalski** [comment]
@SaptakS @niranjan94 @aditya1702 do you know heroku API? I need help because i don't know i only recive 200 releases from heroku You can check it here: http://open-event.herokuapp.com/heroku_releases i don't know how can i get the latest

**Comment by niranjan94** [comment]
@rafalkowalski yes. I'm a bit familiar with it. But I'm out right now. I'll get back to you in an hour or so?

**Comment by rafalkowalski** [comment]
@niranjan94 thanks

**Comment by rafalkowalski** [comment]
@mariobehling Can we close?

**Comment by mariobehling** [comment]
Heroku info is partly false.
![screenshot from 2016-06-13 17 52 07](https://cloud.githubusercontent.com/assets/1583873/16013966/a6cd95e8-318f-11e6-90d5-6f8aec8c822d.png)

**Comment by niranjan94** [comment]
@rafalkowalski @mariobehling That's because the Heroku app seems to be linked to this repo through `mohit.kanwal@gmail.com`'s account. 

We could fetch the latest commit info using the GitHub API and display the person info. The version we can obtain from Heroku.

**Comment by niranjan94** [comment]
@rafalkowalski The current heroku API will give us the commit hash. (eg. `2417c9c`). 

With that, a simple GET request (_no authentication required_) to `https://api.github.com/repos/fossasia/open-event-orga-server/commits/<commit_hash>` gives us the info about the commit and the person responsible for it.  

(Eg. https://api.github.com/repos/fossasia/open-event-orga-server/commits/2417c9c)

**Comment by rafalkowalski** [comment]
@niranjan94 i will fix it

**Comment by rafalkowalski** [comment]
![screen shot 2016-06-14 at 16 04 01](https://cloud.githubusercontent.com/assets/2479753/16045660/b2efea0a-3249-11e6-96f2-d66f6989fdf7.png)
@mariobehling please check if can we close

**Comment by mariobehling** [comment]
Responsible person for last changes: mohit.kanwal@gmail.com ?

I think Mohit is currently not involved.

**Comment by niranjan94** [comment]
@mariobehling @rafalkowalski I'll fix this.

**Comment by niranjan94** [comment]
![capture](https://cloud.githubusercontent.com/assets/2404372/16070721/02b8cede-32f5-11e6-82ff-d8ed80959125.PNG)

- The user name is clickable - will go to the user's github profile
- The commit message and revision is clickable - will go to the commit on GitHub

**Comment by mariobehling** [comment]
Very nice. Let's rename this page to `/admin` and make the future dashboard for admins there. So, we already have one widget :-)
