### ISSUE TITLE
Organizers Admin Page: Create List of My Events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#686]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/622

Events sorted as:
* [x] Live
* [x] Draft
* [x] Past

![screenshot-www eventbrite com 2016-06-10 23-05-12](https://cloud.githubusercontent.com/assets/1583873/15978994/b9e15c30-2f61-11e6-925b-361b3907a04a.png)

**Comment by mariobehling** [comment]
* [ ] Change site to use /event URL - http://open-event.herokuapp.com/admin/events/ -> http://open-event.herokuapp.com/events

![screenshot from 2016-06-11 06 46 23](https://cloud.githubusercontent.com/assets/1583873/15983205/59769e8e-2fa0-11e6-9220-753f911e3fca.png)

* [ ] Change set to use "tabs" (Live, Draft, Past)
![screenshot from 2016-06-11 06 43 43](https://cloud.githubusercontent.com/assets/1583873/15983211/86247992-2fa0-11e6-97ab-4f5ad2108955.png)

**Comment by mariobehling** [comment]
* [ ] Please add "Create Event" on top right as shown on screenshot

**Comment by rafalkowalski** [comment]
@mariobehling do we need change color to blue?
i think it will be more visible
![screen shot 2016-06-12 at 12 54 10](https://cloud.githubusercontent.com/assets/2479753/15990713/ce9ff1b8-309c-11e6-993f-b6109e751c29.png)

**Comment by mariobehling** [comment]
would be nice.

**Comment by SaptakS** [comment]
@mariobehling I think this can be closed?
