### ISSUE TITLE
Create Organizer Profile Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#688]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/622

Create Page as outlined in screenshot below.

![screenshot-www eventbrite com 2016-06-10 23-58-12](https://cloud.githubusercontent.com/assets/1583873/15979949/aa52a368-2f67-11e6-987e-bfc19aa3baac.png)
- [x] upload profile picture

**Comment by SaptakS** [comment]
@rafalkowalski there is already a page for the profile in `/admin/profile/` . I guess you can edit that to make it something like this.

**Comment by mariobehling** [comment]
Feature still missing here is is upload capabilities for pictures.
