### ISSUE TITLE
UI crashed when no user is logged in and root url is opened for the first time

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#695]
This looks because in data_getter , the events list is fetched for the user without checking if he is logged in. 

```python
# line 237
    @staticmethod
    def get_published_events():
        events = Event.query.join(Event.roles, aliased=True).filter_by(user_id=login.current_user.id) \
            .filter(Event.state == 'Call for papers')
        return events

    @staticmethod
    def get_current_events():
        events = Event.query.join(Event.roles, aliased=True).filter_by(user_id=login.current_user.id)\
            .filter(Event.state != 'Completed')
        return events
```

@rafalkowalski @SaptakS please look

![crash](https://cloud.githubusercontent.com/assets/4047597/15983010/a57cec4a-2fb7-11e6-8e38-e35a2c3b3059.png)

**Comment by aviaryan** [comment]
get_completed_events and get_user_events also use a similar code. I don't know which ones to change . @rafalkowalski @SaptakS someone take this issue.

**Comment by niranjan94** [comment]
@aviaryan I'll take this up
