### ISSUE TITLE
Create Event Wizard Step 2: Sponsors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#697]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/324

Sponsors is missing so far from the wizard.

* [x] Implement "Sponsors" under wizard step 2
* [x] Move current "Session Types" to be included in step 3 and rename wizard step to "Sessions, Tracks, Rooms"
* [x] Implement the following fields
	* [x] Sponsor
	* [ ] Upload Image
	* [x] Link
	* [x] Level (this means the sponsorship level and sorting how they will appear on the website)
	* [x] Type (Platinum, Gold etc.)
	* [x] Description

**Comment by mariobehling** [comment]
@SaptakS Actually the Upload function is not implemented yet. So this issue is not finished.

**Comment by mariobehling** [comment]
Please also rename point 3 to: "Sessions, Tracks, Rooms"

**Comment by SaptakS** [comment]
@mariobehling renamed at https://github.com/fossasia/open-event-orga-server/pull/733

**Comment by niranjan94** [comment]
**A more refined UI:** (tested on small/mobile screens)

![screencapture-localhost-5000-events-create-1465910922422](https://cloud.githubusercontent.com/assets/2404372/16046142/fd6ee530-3268-11e6-9c0d-2d44f0dc16cb.png)

**Comment by mariobehling** [comment]
If possible, please implement:
* [ ] Show small version of uploaded image in area of upload button.
* [ ] Dont show "Gold"
* [ ] Implement Level with numbers (e.g. three sponsors in level 1 will show up on the top of sponsorship areas)

**Comment by niranjan94** [comment]
@mariobehling will implement them.
