### ISSUE TITLE
multiple events should be able to belong to a track

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#7]
Right now, if I make a track "X"

And then make session A, with track X, and then make another session B also with track X, then session A's track becomes null. And only session B stays in track X. 

Ideally, multiple events can belong to a particular track.

**Comment by rafalkowalski** [comment]
I resolved it https://github.com/fossasia/open-event-orga-server/commit/c68db02707df1cdc3465ff9749343226d0a84176 . @championswimmer  Could you check it ;) ?
