### ISSUE TITLE
Implement Event Dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#701]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/622

* [x] Implement SPECIFIC EVENT DASHBOARD
    -   [x] `/events/ID/`
    -  [x] It shows an event dashboard with info how many proposals there are, how many speakers are 
accepted and which countries they are from
    -  [x] Propose and implement interesting widgets for the specific event dashboard (Get inspiration from the Eventnook dashboard)
    -  [x] show the stage and dates of an event, e.g. when event it will be in call for papers state

![screenshot from 2016-06-11 07 35 47](https://cloud.githubusercontent.com/assets/1583873/15983546/7dd26ed8-2fab-11e6-9055-e684e426df83.png)

**Comment by SaptakS** [comment]
@mariobehling I have created the dashboard with options on a top menu bar. Here are the screenshots...

![screenshot from 2016-06-11 15 05 57](https://cloud.githubusercontent.com/assets/9530293/15984380/1f8e75d4-2fe6-11e6-993b-56be4820d417.png)
![screenshot from 2016-06-11 15 06 01](https://cloud.githubusercontent.com/assets/9530293/15984381/1fe475ec-2fe6-11e6-9c40-f9b87dc3b897.png)
![screenshot from 2016-06-11 15 06 06](https://cloud.githubusercontent.com/assets/9530293/15984382/1fe65a42-2fe6-11e6-9290-e181a5b6cabd.png)
![screenshot from 2016-06-11 15 06 11](https://cloud.githubusercontent.com/assets/9530293/15984383/1fe7abe0-2fe6-11e6-8100-5003d4691966.png)

**Comment by niranjan94** [comment]
@SaptakS ... Looks cool ! :) ... 

Could you set the `min-height` to 100% to that page extends till the bottom irrespective of the height of the content ?

**Comment by mariobehling** [comment]
Nice, please take out sponsors and see where I added sponsors in the wizard:
https://github.com/fossasia/open-event-orga-server/issues/324 and https://github.com/fossasia/open-event-orga-server/issues/697

**Comment by SaptakS** [comment]
@mariobehling I am already on those Issues.. This Tab is just for displaying the Sponsors for that event that is already in DB.

**Comment by mariobehling** [comment]
@SaptakS On a second thought. Let's keep sponsors in here. Cheers

**Comment by SaptakS** [comment]
@mariobehling great.
