### ISSUE TITLE
Implement "My Sessions" Dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#703]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/622

The URL`/events/mysessions` - shows all sessions the user/speaker has submitted to all "his/her" events. Please implement as shown below.
![screenshot-www eventbrite com 2016-06-11 10-40-20](https://cloud.githubusercontent.com/assets/1583873/15984230/78e2d87c-2fc4-11e6-8391-e86e099512c7.png)

**Comment by niranjan94** [comment]
I'll work on it right away .. :+1:

**Comment by niranjan94** [comment]
@mariobehling this is the UI prototype
![capture](https://cloud.githubusercontent.com/assets/2404372/15985427/3525a9ac-300a-11e6-81ed-95225326bfb3.PNG)

**Comment by mariobehling** [comment]
Looks good. Thanks! Please do not forget to add "Manage Sessions" on the top right dropdown menu.

**Comment by mariobehling** [comment]
One thing here left: Please take out "admin" from the URL.

**Comment by niranjan94** [comment]
@mariobehling so, you want admin to be removed from all URLs ?

**Comment by mariobehling** [comment]
Yes, please. Details here as well https://github.com/fossasia/open-event-orga-server/issues/622

**Comment by niranjan94** [comment]
Alright ... Will do

**Comment by niranjan94** [comment]
Opened a separate issue for that here #724. Working on it now. Closing this issue.
