### ISSUE TITLE
Make scheduler use "rooms" from the "create event" wizard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#713]
It looks like currently the scheduler has an option to add "microlocations". These microlocations should be defined in the "create event" wizard in step 3 (Sessions, Tracks, Rooms).

* [x] Ensure that microlocations are used that are entered in the wizard.

**Comment by niranjan94** [comment]
@mariobehling. Yes. the scheduler already uses the microlocations defined in the "create event" wizard in step 3 (Sessions, Tracks, Rooms).

**Comment by mariobehling** [comment]
Ok, good. Can't test right now as it is not loading on the current deployment.

**Comment by niranjan94** [comment]
@mariobehling the deployment is fixed now. You can check it out at https://open-event.herokuapp.com/admin/events/8/scheduler/ .

**Comment by mariobehling** [comment]
It is confusing in the current UI that you can add a microlocation here. For the moment please make this link go to the wizard maybe. Or will microlocations added here be added in the wizard as well? I cannot check this as I get an internal server error and event 8 does not show up in my list of events.

![screenshot from 2016-06-11 15 03 02](https://cloud.githubusercontent.com/assets/1583873/15985192/c9ea5896-2fe5-11e6-9c69-5723c0e0c857.png)

**Comment by mariobehling** [comment]
Also please make lat/long optional and mark required fields with `*`.

**Comment by mariobehling** [comment]
![screenshot from 2016-06-11 15 11 15](https://cloud.githubusercontent.com/assets/1583873/15985229/c9e617da-2fe6-11e6-988a-9ab11344a32f.png)

**Comment by niranjan94** [comment]
@mariobehling the microlocation added here and added in the wizard go to the same database. Anything add in the wizard will be here. Anything added here will be there. 

But I'm not sure what's causing the Internal Server Error there. @aditya1702 @rafalkowalski could you check that ?

**Comment by rafalkowalski** [comment]
@niranjan94 I will check

**Comment by niranjan94** [comment]
@rafalkowalski thanks :)

**Comment by rafalkowalski** [comment]
@mariobehling @niranjan94 bug's fixed

**Comment by mariobehling** [comment]
@rafalkowalski Yes, error is gone, but "Edit Event" links to the version 1 wizard. This wizard should be out and deleted already.

![screenshot from 2016-06-11 16 39 57](https://cloud.githubusercontent.com/assets/1583873/15985593/3d6e821c-2ff3-11e6-840e-0db202582ad6.png)
