### ISSUE TITLE
Propose and Implement a logging and revision system

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#727]
Questions to answer: 
* [x] What should be logged?
* [ ] What information should we store to revise?
* [ ] What user information can we store (temporarily) after it gets deleted from the account?
* [ ] Can we implement a trash system, where anything that gets deleted by users "lands" for a period of time?
* [ ] What access info can we store?

**Comment by niranjan94** [comment]
- All the CUD (create, update, delete) operations. We'll store the operation type, user_id, and the changed model's ID 
- Revise ? I don't understand. 
- We'll store name and email of user after deletion
- Trash system. It'll need some thinking. We'll have to change our DB codes to make soft deletes on models instead of hard deletes. 
- Access info ? Accessing what ?

**Comment by mariobehling** [comment]
1. Revision, e.g. similar to Google docs and Wordpress: If someone edits the sessions, it would be nice to have a revision history. Example use case: Several speaker of the same session edit the session information and they want to see what has been changed.

2. Storing access info, e.g. log login attempts, logins, IP address etc. Example use case: A user tells us his account was hacked and we need to check if the system is compromised. Storing all logins would be good to find out.

**Comment by niranjan94** [comment]
@mariobehling for revisioning, I came across this extension [SQLAlchemy-Continuum](https://github.com/kvesteri/sqlalchemy-continuum) which we could use.

For starts, we could add revisioning to:
- [ ] Events table
- [ ] Sessions table

**Comment by mariobehling** [comment]
@niranjan94 It looks good to me even though it seems most of the development happen last year, but it is active. I do not know about the feature set. If you are confident that this is really helpful for us, let's proceed.

**Comment by niranjan94** [comment]
@mariobehling I have implemented the backend for revisioning ... Where can we display it ? Can it be a separate tab in the event specific dashboard ?

**Comment by mariobehling** [comment]
Well, revisions should not be integrated into the usual tabs. It is not a main feature, it is more like a subfeature. Can we have the revisions below the current version in a slightly grayed out font style for the moment? and in the options "view" and "restore" buttons?

**Comment by mariobehling** [comment]
In Wordpress they have a simple "Browse Revisions" button. Maybe that would be a good way and can be implemented in the options column.

![screenshot from 2016-06-25 14 56 59](https://cloud.githubusercontent.com/assets/1583873/16356810/4f1921dc-3ae5-11e6-8d9b-d94d2d97420d.png)

**Comment by niranjan94** [comment]
@mariobehling I'll check it out
