### ISSUE TITLE
Implement Import/Export functionality of events with JSON

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#728]
There are a number of data sets - each API - that can be exported as JSON.

**Comment by aviaryan** [comment]
Hi @mariobehling 
What I understand by "import" functionality of events with JSON is that a feature which will allow people to import json (speakers.json, sessions.json) etc and automatically create an open-event from it on our service. 
So the "export" feature is to make the events saveable as a json file.
Is that correct ? @mariobehling @shivamMg 

If the above is correct, should we export an event as a single json (with sessions and everything) or multiple jsons (diff json for each type). Same question for import. 

We can use the `\api\v2\events\import` for import and `api\v2\events\<id>\export` url for export.

**Comment by mariobehling** [comment]
@aviaryan At the moment we are using different JSONs files to generate the web and Android app. We have not defined one big JSON for all. Alternatively we could also generate an .zip file with the different JSON files inside and import/export it.

**Comment by aviaryan** [comment]
@mariobehling Using a zip is a good idea. I will like to work on this issue after finishing with #736 , I will assign myself when I begin working on this.

**Comment by aviaryan** [comment]
After thinking about how to approach this issue, I realized it will not be a small task. So I will create sub-issues for each substantial step involved.

**Comment by shivamMg** [comment]
@mariobehling @aviaryan Feature to export services (in a zip file) related to an event looks cool (https://github.com/fossasia/open-event-orga-server/issues/758). But import feature looks unnecessary. The import feature should be handled by the client developer by make POST requests to the server.

**Comment by mariobehling** [comment]
@shivamMg As a user, I want to be able to save and export my event and then import my event in another installation. Cheers.

**Comment by shivamMg** [comment]
@mariobehling What I meant is that by importing we mean taking in data in a defined schema and creating resources at the server, which is same as using POST APIs.

**Comment by mariobehling** [comment]
@shivamMg @aviaryan The first step is to implement this with JSON. In future we probably also ex/import images and other media.
