### ISSUE TITLE
Error Responses

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#737]
A consistent error response structure would help error handling at the client side. Here's an example of the structure.

```json
{
  "error": {
    "code": 404,
    "message": "Event not found",
    "status": "NOT_FOUND",
    "field": null,
  }
}
```

Error codes in use:

| Code | Status | Field | Description |
| --- | --- | --- | --- |
| 401 | NOT_AUTHORIZED | null | Invalid token or user not authenticated |
| 400 | INVALID_FIELD | "field_name" | Missing or invalid field |
| 400 | INVALID_SERVICE | null | Service ID mentioned in path does not belong to said Event |
| 404 | NOT_FOUND | null | Event or Service not found |
| 403 | PERMISSION_DENIED | null | User role not allowed to perform such action |
| 500 | SERVER_ERROR | null | Internal server error |

Currently we are using a function to return error response with proper structure. This has its limitations. For example the internal server error returns a different structure (default one). To handle these, default handlers for errors must be overridden. 

EDIT:

For validation errors, the execution will be aborted with the first field error encountered. The name of the field would be sent back in the "field" attribute. So if during event creation the event name has not been provided, an example response could be:

```json
{
  "error": {
    "code": 400,
    "message": "Required field",
    "status": "INVALID_FIELD",
    "field": "name",
  }
}
```

**Comment by aviaryan** [comment]
@shivamMg This new schema look good. I was thinking of returning all validation errors at once in POST and PUT API. Is it possible to return many errors (many message+field values) at once using this schema ?

**Comment by shivamMg** [comment]
@aviaryan I think we should stick to a simple structure. I've updated the description.

**Comment by aviaryan** [comment]
@shivamMg OK. No problem. please review #742

**Comment by aviaryan** [comment]
Should this be closed ? @shivamMg

**Comment by shivamMg** [comment]
@aviaryan I've closed it. We can later collect all issues with documentation tag, it will help us in creating docs.

**Comment by aviaryan** [comment]
@shivamMg Good idea.
