### ISSUE TITLE
Propose Administration Implementation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#755]
As a number of functionalities concern super admins we need to consider how we implement these administration functions.

1. There are two concepts e.g. the one that wordpress follows: There is a dedicated login to Wordpress, but users of the site use the "front". On the other hand systems like Drupal have an administration section integrated. What is the best way for Open Event?

2. We also need to make a list of features for super admins, e.g. overview of all events, all sessions, all speakers etc.

**Comment by rafalkowalski** [comment]
1. Firstly i thought about flask-admin library but we need to customize it. the best solution will be second option(like drupal). Now we have a lots of views implemented so it will be very easy to add super admin panel

**Comment by mariobehling** [comment]
@rafalkowalski Ok, in this case we would make an "admin area", e.g. under the `/admin/`URL. Let's take a bit more time to think about the details.

**Comment by SaptakS** [comment]
@mariobehling @rafalkowalski I think drupal option is good. We can make URLs such as `/admin/events/` , `/admin/sessions/` , etc.. to list all the various features.

**Comment by rafalkowalski** [comment]
@SaptakS good
/admin/users (CRUD, block user) maybe we can also shows few charts 
/admin/payments(Monitoring)
/admin/newsletter
