### ISSUE TITLE
error while deploying vagrant on digitalocean

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#76]
```shell
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://vagrantcloud.com/ubuntu/trusty64
==> default: Adding box 'ubuntu/trusty64' (v20150609.0.10) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20150609.0.10/providers/virtualbox.box
==> default: Successfully added box 'ubuntu/trusty64' (v20150609.0.10) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'push'.
```

**Comment by championswimmer** [comment]
ok so 
`vagrant plugin install push` solves the problem.

Umm, is there a way to install the plugins from Vagrantfile ? So we don't need any commands other than `vagrant up`

**Comment by leto** [comment]
Yep! :smiling_imp: 

Here is an example which installs the vagrant-aws plugin if it does not exist.

Also, ```push``` is new and if you have Vagrant 1.7+ that should be there. Which version of vagrant are you using? 

```
# auto-install our required plugins
required_plugins = %w( vagrant-aws )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end
```

**Comment by championswimmer** [comment]
1.4.3, as that's the standard that comes with `apt-get install vagrant` on
Ubuntu LTS

**Comment by championswimmer** [comment]
1.4.3, as that's the standard that comes with `apt-get install vagrant` on Ubuntu LTS

**Comment by leto** [comment]
That is way too old.

Use 1.7 or higher

Duke

**Comment by championswimmer** [comment]
Even with 1.7, `vagrant up` straightaway isn't working because it's right now configured by default to deploy to heroku. 

Gonna test when @rafalkowalski fixes up for generic VPS deployment.

**Comment by rafalkowalski** [comment]
@championswimmer Could you explain me how can I help you?

**Comment by championswimmer** [comment]
Basically the current Vagrantfile defaults to pushing the app to heroku.

I think this shouldn't be the default. By default it should deploy on
localhost on some port (eg 5000) when we do vagrant up

**Comment by leto** [comment]
You must always specific where you are deploying:

vagrant up local
vagrant up dev

If you don't, it defaults. There is no bug ;)
