### ISSUE TITLE
Prepare footer 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#764]
@mariobehling what do you think? Currently it's an empty space 
![screen shot 2016-06-13 at 00 13 30](https://cloud.githubusercontent.com/assets/2479753/15994127/c5bc139c-30fb-11e6-8775-469c18376293.png)

**Comment by mariobehling** [comment]
Yes, very good! So let's think, which links we have:
Column 1: 
* [ ] How it Works
* [ ] Pricing
* [ ] Mobile Apps
* [ ] Sitemap

Column 2:
* [ ] List of Event Categories (automatically generated by our top categories)

Column 3:
* [ ] List of Event Locations (automatically generated by our top locations)

Column 4:
* [ ] Support 
* [ ] Twitter
* [ ] Facebook
* [ ] Google+
* [ ] YouTube
* [ ] GitHub

Footer 1:
* [ ] About
* [ ] Blog
* [ ] Help (directs to Support)
* [ ] Press
* [ ] Security
* [ ] Developers
* [ ] Privacy
* [ ] Cookies

Footer 2:
* [ ] Dropdown menu with Interface Languages

**Comment by rafalkowalski** [comment]
@mariobehling can you tell me what categories mean?

**Comment by mariobehling** [comment]
Good point. Let's better separate categories into a) Types and b) Topics and add "Types" in the Column 2. Also compare with Eventbrite.

![screenshot from 2016-06-14 11 00 53](https://cloud.githubusercontent.com/assets/1583873/16037164/98e238c2-321f-11e6-8031-8fd578f8a1d9.png)

**Comment by mariobehling** [comment]
Unfortunately the footer design is not like in the screenshot, e.g. text is too dark to read and width of bottom footer is different.

**Comment by mariobehling** [comment]
Please check the responsiveness. There are a number of issues with the implementation in smaller resolution.

* [ ] The footer font is too dark and difficult to read
* [ ] At points the country bar overlaps
* [ ] in smaller resolutions are errors (Please compare to Eventbrite, grab the side of your browser and see how the footer of Eventbrite adapts to the size.

Compare medium small resolution
![screenshot from 2016-06-20 11 20 40](https://cloud.githubusercontent.com/assets/1583873/16189198/64f97e1c-36d9-11e6-9b6e-a48d97303fd3.png)

Compare small resolution
![screenshot from 2016-06-20 11 20 08](https://cloud.githubusercontent.com/assets/1583873/16189244/9cf686de-36d9-11e6-84ec-e977e4f465c0.png)

**Comment by SaptakS** [comment]
@rafalkowalski are you working on this?

**Comment by SaptakS** [comment]
@rafalkowalski @mariobehling I am taking this up.

**Comment by mariobehling** [comment]
Well, there are still a few issues.

* [ ] On some pages, e.g. in admin area a line overlaps with the dropbdown

![screenshot from 2016-07-01 08 43 36](https://cloud.githubusercontent.com/assets/1583873/16514318/6176ec76-3f6b-11e6-977d-ed4da4ee5af5.png)

* [ ] In small resolution, the distance between last row of links and dropdown should be larger

![screenshot from 2016-07-01 02 30 31](https://cloud.githubusercontent.com/assets/1583873/16514341/87847cb2-3f6b-11e6-8514-904a95394b70.png)

**Comment by SaptakS** [comment]
The color of the links are same as that of eventbrite. I will check it out..

**Comment by mariobehling** [comment]
Yes, thanks. Please check all resolutions. Still some issues.

![screenshot from 2016-07-01 12 05 31](https://cloud.githubusercontent.com/assets/1583873/16518657/58d38228-3f84-11e6-9f04-d26f3cd0df57.png)

**Comment by SaptakS** [comment]
I checked for all the standard resolutions and seem to be working fine. I will still check for other resolutions to see if there is some error.

**Comment by mariobehling** [comment]
@SaptakS An easy way to check is: Go to eventbrite.com and resize the browser window. Just grab it and move it. Then compare and do the same with open event. You will see the issues.

**Comment by SaptakS** [comment]
Yes.. I did do it.. But maybe missed some of the resolutions.

**Comment by SaptakS** [comment]
@mariobehling done..

**Comment by mariobehling** [comment]
It seems like one things gets solved and another issue comes up.
* [ ] keep width of footer same as width of bottom blocks
* [ ] Reduce size of country box

![screenshot from 2016-07-04 22 41 37](https://cloud.githubusercontent.com/assets/1583873/16569626/df4db84e-4238-11e6-9903-4419dc88a399.png)

**Comment by SaptakS** [comment]
The bottom block had to be increased for making it responsive in smaller devices, otherwise some of the elements went to next line and overlapped. In the process I think the county box was also increased. 
I will increase the width of footer to match the width of bottom blocks.
As of country box, let me see if I can do something about it.

**Comment by mariobehling** [comment]
> I will increase the width of footer to match the width of bottom blocks.

The bottom blocks and footer need to match the width of the upper area with the three columns.

**Comment by SaptakS** [comment]
will get it done today

**Comment by mariobehling** [comment]
![screenshot-open-event herokuapp com 2016-07-08 14-15-17](https://cloud.githubusercontent.com/assets/1583873/16687142/03e9f970-4517-11e6-9f6b-096321d5ea0f.png)

Please see previous comments.

Wow, this issue is 26 days old and we cannot get it closed with all elements working as expected.

**Comment by SaptakS** [comment]
Sorry for the delay.. Will get this done immediately..

**Comment by mariobehling** [comment]
Please also reduce the height of the country box and align the text in the country to the left.
![screenshot from 2016-07-08 18 25 39](https://cloud.githubusercontent.com/assets/1583873/16694259/7d181c42-4539-11e6-8992-8087af04bc9f.png)
