### ISSUE TITLE
Unable to Create New Tables from Models

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#765]
After a certain change in the migration, the python create_db.py is unable to create tables from newly added models. Not sure why this is happening.

**Comment by shivamMg** [comment]
@SaptakS Can you share the traceback of the python create_db.py command, if it had one. It's working at my local repo.

**Comment by aditya1702** [comment]
@shivamMg Are you able to create new table? Please look here I found this. According to this you cant auto detect an entire table. http://stackoverflow.com/questions/12409724/no-changes-detected-in-alembic-autogeneration-of-migrations-with-flask-sqlalchem

**Comment by SaptakS** [comment]
@shivamMg there is no traceback. It executed but then it doesn't create a table from a newly written model. Can you check whether you can create a table from a newly written model?

**Comment by rafalkowalski** [comment]
ok, so problem is because you have to import somewhere this model for example to views.py
