### ISSUE TITLE
Add Button "New" Session into Events Organizer UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#768]
It should be possible to add events in two ways 
a) a potential speakers can click a registration button to answer the call for papers and fill in sessions in that process
b) an event organizer can add sessions in the event session UI, e.g. of VIPs who do not have to sign up in the system

* [ ] The "New Session" Button should go on this page below
![screenshot from 2016-06-13 11 37 31](https://cloud.githubusercontent.com/assets/1583873/16003127/828aad8a-315b-11e6-9a3d-d9ef541ff16d.png)

**Comment by SaptakS** [comment]
![screenshot from 2016-06-13 15 59 21](https://cloud.githubusercontent.com/assets/9530293/16004537/d29eccb0-317f-11e6-989f-702eea86f913.png)

PR https://github.com/fossasia/open-event-orga-server/pull/769
