### ISSUE TITLE
Use same styling in "create" and "edit" event wizard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#777]
Follow up issue to https://github.com/fossasia/open-event-orga-server/issues/773

Please use the same styling as in other headers and top menus in the create and edit event wizard.

* [ ] Use the same top menu across all pages (currently in create/edit wizard the "Open Event" look is different with another font)
* [ ] Use the same styling for heading in gray top area
* [x] Take out ": Stage 1" from create and edit wizard

![screenshot from 2016-06-13 15 58 48](https://cloud.githubusercontent.com/assets/1583873/16010127/1d48c7ca-3180-11e6-82e1-dfdb8ab949af.png)

![screenshot from 2016-06-13 15 58 30](https://cloud.githubusercontent.com/assets/1583873/16010129/21f402f8-3180-11e6-97b7-bd8a01aab085.png)

**Comment by mariobehling** [comment]
Seems unresolved after checking deployment.

**Comment by niranjan94** [comment]
@mariobehling please check again. It seems to be fine. 

![screenshot 50](https://cloud.githubusercontent.com/assets/2404372/16013979/048286a4-31ad-11e6-9515-cfb41268a43e.png)
![screenshot 51](https://cloud.githubusercontent.com/assets/2404372/16013980/0484e67e-31ad-11e6-84fa-56606f66227e.png)

**Comment by mariobehling** [comment]
You are comparing the same page. Please check with "manage events".

**Comment by mariobehling** [comment]
![screenshot from 2016-06-13 19 10 05](https://cloud.githubusercontent.com/assets/1583873/16016276/79f19834-319a-11e6-8ec9-6c8940c36a87.png)

**Comment by niranjan94** [comment]
@mariobehling it still seems to be correct. 
- The same top bar is used. 
- Same styling for heading in gray top area.

![screenshot 52](https://cloud.githubusercontent.com/assets/2404372/16016444/c41bac7e-31b8-11e6-9798-c030d83db085.png)

**Comment by mariobehling** [comment]
Tried with three browsers now. Looking at the css it also looks fine, but still getting the same difference with a fresh browser.

Both have different fonts for "Open Event" and "Create Event" has bolder font.

![screenshot from 2016-06-13 19 49 27](https://cloud.githubusercontent.com/assets/1583873/16017434/1c5e4e1e-31a0-11e6-8a74-cd0a77a78400.png)

**Comment by niranjan94** [comment]
@mariobehling Oh ... that's weird. I'll check everything once again

**Comment by SaptakS** [comment]
@mariobehling @niranjan94 I don't know why this is happening but I tried removing the font-family, and the design looks perfectly same after doing that. However when I apply Helvetica family again, it looks different. And their content size is also different, though the css computed is exactly the same.

**Comment by SaptakS** [comment]
The element had a comma separated list of fallback font-family. In one page `Roboto` font was being loaded while in other page `Arial` was being loaded. Don't know exactly why this difference was happening but this is what was happening. Fixed in https://github.com/fossasia/open-event-orga-server/pull/787 . @mariobehling @niranjan94 please review.
