### ISSUE TITLE
Cannot publish event (immediately)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#785]
There are a number of issues with publishing events.
![screenshot from 2016-06-13 17 38 42](https://cloud.githubusercontent.com/assets/1583873/16013584/4f594024-318e-11e6-93b5-a41aeaea6de8.png)
* [ ] Events currently cannot be set to "Publish". It is not published. Please change this "Publish" into "Make your event live"
![screenshot from 2016-06-13 17 41 30](https://cloud.githubusercontent.com/assets/1583873/16013593/5a861a8a-318e-11e6-8fcc-d8d8e5355e37.png)
* [ ] We should be able to publish an event without going through the whole wizard. Only required fields should prevent a user from making it live.
* [ ] Please implement an option "save", which currently saves the draft only in the last stage, but it should be possible to save the draft in any stage of the wizard.

**Comment by rafalkowalski** [comment]
ok i will do it

**Comment by mariobehling** [comment]
Does not work in deployment. Event cannot be saved and cannot be published. It does not show up in the list.

**Comment by rafalkowalski** [comment]
i think it's working now @mariobehling

**Comment by mariobehling** [comment]
Well, it works publishing it, but it does not show up in the published "Live" category.

![screenshot from 2016-06-13 22 49 14](https://cloud.githubusercontent.com/assets/1583873/16022636/216b73f0-31b9-11e6-9320-c58eb05185fd.png)

**Comment by rafalkowalski** [comment]
@mariobehling ok i will change a filter

**Comment by rafalkowalski** [comment]
@mariobehling I've fixed it
