### ISSUE TITLE
Invite Speakers from Session Wizard

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#792]
Parent Issue #602 

- [x] Invite speakers for a particular session through Mail.
- [x] Speaker accepts/rejects invitation.

**Comment by SaptakS** [comment]
@mariobehling what exactly should be the format of the invitation? What I have thought is:-

- User is sent an invitation mail with a link
- User clicks on the mail and gets an accept/reject invitation.

What do you suggest? Is this the way I should proceed?

**Comment by mariobehling** [comment]
Yes, good idea.

**Comment by SaptakS** [comment]
@mariobehling the first part has been done in the Pull Request in the PR. Can you please review?
