### ISSUE TITLE
timestamps should be shown in ISO8601 format in JSON API

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#8]
Please check http://en.wikipedia.org/wiki/ISO_8601 

That is, timestamps should look exactly like this string
"2015-05-15T13:05:05+00:00"
or
"2015-05-15T13:05:05Z"
(Z stands for 00:00 timezone)

**Comment by mananwason** [comment]
Instead of this we can just put the gmt time and calculate the difference between the device's current time and the GMT at that point to get the difference and add it to the gmt time in the data downloaded.

**Comment by championswimmer** [comment]
Well technically, we can still do that in ISO8061, by only using Zulu time.
The reason I want to stick to a protocol like ISO8061 is because Date and
Timestamps for ISO8061 is defined in all major computer languages. It's
easy to parse, and widely used. (Or we can use RFC3339, which is the most
widespread internet standard, which although is afterall just a profile of
ISO8061).
We could also use epoch milliseconds, though there could be issues in 2038
:P if anywhere we are using 32-bit.

**Comment by mananwason** [comment]
I am sorry I don't know much about time formats but I'd like to point out my concerns about making things complex by following these formats. We can just keep it simple by the method I have written above.

**Comment by championswimmer** [comment]
Well, we have to stick to one format at least.

We cannot have some times like "Sat, 16 May 2015 15:00:00 GMT" and some
like "2015-05-15T13:05:05+00:00"

ISO8061 is the easiest to parse from string to Calendar object, because we
will need that to set up alarms/reminders.
The format is YYYY-MM-DD followed by the letter "T" followed by HH:MM:SS,
followed by "Z" if GMT, or +HH:MM if timezone is needed.

If we want to use all GMT, or we want to specify timezone, is our option :)

**Comment by mananwason** [comment]
Yes I agree to that. We have to finalize a format but without making thing complex and enter the timezone. As it is the event would be in the same timezone. It's the users who'll be in different timezones, so there is no point in specifying the timezone.
As for the format ISO8061 seems just fine.

**Comment by rafalkowalski** [comment]
I fixed it in commit: https://github.com/fossasia/open-event-orga-server/commit/30ed6fee350d060e52f3cf7f581f0fa5a4467392. Is it good?

**Comment by championswimmer** [comment]
Looks perfect :)
