### ISSUE TITLE
Document all API fields, methods and access in API.md

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#801]
Parent: https://github.com/fossasia/open-event-orga-server/issues/799

* [x] Event API https://github.com/fossasia/open-event-orga-server/issues/612
* [x] Speakers API https://github.com/fossasia/open-event-orga-server/issues/618
* [x] Profile API https://github.com/fossasia/open-event-orga-server/issues/617
* [x] Sponsors API https://github.com/fossasia/open-event-orga-server/issues/615
* [x] Track API https://github.com/fossasia/open-event-orga-server/issues/614
* [x] Microlocation API https://github.com/fossasia/open-event-orga-server/issues/616
* [x] Sessions API https://github.com/fossasia/open-event-orga-server/issues/613

**Comment by shivamMg** [comment]
@mariobehling Can you please take a look https://github.com/fossasia/open-event-orga-server/blob/development/docs/API.md

**Comment by mariobehling** [comment]
I still don't understand what kind of APIs you have in there e.g. sponsor type. Please limit the number of APIs as discussed at the beginning of this project.

**Comment by mariobehling** [comment]
Please also put a number in front of the APIs, e.g. 1. Event API.

It is difficult to see which level are the headers.

**Comment by shivamMg** [comment]
@mariobehling :+1: 

I understand the sponsor type issue. Can you take a look here and tell what should we do https://github.com/fossasia/open-event-orga-server/issues/811#issuecomment-225937155.

**Comment by mariobehling** [comment]
Another thing, the sorting is confusing. Please keep related entries together, e.g. longitude, latitude or start time, end time.

**Comment by shivamMg** [comment]
@mariobehling Serializing and sorting done https://github.com/fossasia/open-event-orga-server/blob/development/docs/API.md

**Comment by mariobehling** [comment]
As mentioned in other issues, it is not clear why and what for some of the APIs are necessary and why they are not integrated. 
* Forma: What is it for?
* Levels: Should be part of another API. I don't know what it is for? Sponsorship or location?
* Languages: Is it necessary to make an API for this?

**Comment by shivamMg** [comment]
@mariobehling About Formats and Levels, we are stuck with them because they were already defined in the databases when we started. None of us actually know what they are. https://github.com/fossasia/open-event-orga-server/issues/799#issuecomment-225953808

Languages might need an API, so the event organizer can specify them. OR we can provide with a list of all the languages.

**Comment by mariobehling** [comment]
@shivamMg Please talk to @rafalkowalski how to take formats and levels out or describe why we need them.

We should surely take in a predefined list for languages. There are ready list available.

**Comment by shivamMg** [comment]
@mariobehling Alright.

**Comment by rafalkowalski** [comment]
@shivamMg @mariobehling Last year we decided to base on re-data format API http://data.re-publica.de/doc/api.html#levels, but for now we have different API format so i think we can remove Formats and Levels

**Comment by shivamMg** [comment]
@mariobehling All of these have been documented. https://github.com/fossasia/open-event-orga-server/blob/development/docs/API.md. I think we can close this issue.
