### ISSUE TITLE
Define APIs with fields and methods

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#802]
Parent: https://github.com/fossasia/open-event-orga-server/issues/799

Define API fields and methods

* [ ] Event API https://github.com/fossasia/open-event-orga-server/issues/612
* [ ] Speakers API https://github.com/fossasia/open-event-orga-server/issues/618
* [ ] Profile API https://github.com/fossasia/open-event-orga-server/issues/617
* [ ] Sponsors API https://github.com/fossasia/open-event-orga-server/issues/615
* [ ] Track API https://github.com/fossasia/open-event-orga-server/issues/614
* [ ] Microlocation API https://github.com/fossasia/open-event-orga-server/issues/616
* [ ] Sessions API https://github.com/fossasia/open-event-orga-server/issues/613

**Comment by mariobehling** [comment]
How many issues with the same topic, do you want to open? This topic is already defined in #799 and each API follow up should happen in the links you provided yourself.
