### ISSUE TITLE
Import of Event not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#808]
Download of Event zip works well. If I try to upload/import the same file again, I get an error message.

![screenshot from 2016-06-14 16 26 32](https://cloud.githubusercontent.com/assets/1583873/16046535/126e5194-324d-11e6-93f5-8b855b7d79a0.png)

**Comment by aviaryan** [comment]
@mariobehling I downloaded event45.zip and found that the email used for event is invalid. The API validates all types of data and so returned 400 validation error because of invalid data.

```json
{
    "background_url": "", 
    "closing_datetime": null, 
    "color": "WhiteSmoke", 
    "description": "", 
    "email": "dsads", 
    "end_time": "2016-07-22 00:00:00", 
    "event_url": "", 
    "id": 45, 
    "latitude": 0.0, 
    "location_name": "", 
    "logo": "", 
    "longitude": 0.0, 
    "name": "Andres Event", 
    "organizer_description": null, 
    "organizer_name": null, 
    "start_time": "2016-07-21 00:00:00", 
    "state": "Published"
}
```

**Comment by mariobehling** [comment]
@aviaryan Ok, we need to validate this when the user types into the form then.
