### ISSUE TITLE
Remove sponsor_types API and model

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#811]
<strike>
SponsorTypes URL will change to `events/<id>/sponsors/types/` and it will be under sponsors namespace now. 
All get, post, list, delete functions will be made functionable from that endpoint. 
</strike>
See https://github.com/fossasia/open-event-orga-server/issues/811#issuecomment-226373924

**Comment by shivamMg** [comment]
@aviaryan Does it really matter if it comes under 

```
/events/<event_id>/sponsor_types/<sponsor_type_id>
```

or

```
/events/<event_id>/sponsors/types/<sponsor_type_id>
```

It would still be an API. The real question is if the SponsorType field in the Sponsor API should be a simple string or a choices field. SponsorType API helps us provide the choices field. Let @mariobehling decide. If choices field is not required, I can remove the SponsorType API and specify type in Sponsor API as a simple string.

**Comment by aviaryan** [comment]
@shivamMg 
Well having sponsor_type as choices is the practically correct option. 
Having sponsor_types as `/events/<event_id>/sponsors/types/<sponsor_type_id>` will make it less scary for the new API user as no of API endpoints at the parent level of Swagger UI will be less.
More importantly since **sponsor_types will not exist without sponsors**, adding them inside it is better.

**Comment by mariobehling** [comment]
When is this resolved? The API still shows up here sponsor_types. We have people waiting for the correct API outline to plugin the Web App and Android project. Please proceed.

**Comment by mariobehling** [comment]
Please do not label things discussion, that were already clearly outlined at the beginning of the project. Again, we do not need an API for each field in a form.

**Comment by aviaryan** [comment]
@mariobehling Ok. I will completely remove sponsor_type API and make it a string field in sponsors. Also I will add a **hidden** method that will fetch used sponsor types for an event. This will help to provide a list of choices of already used sponsor types when adding a sponsor.
