### ISSUE TITLE
Remove Format and Level Database models and APIs

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#815]
https://github.com/fossasia/open-event-orga-server/issues/799#issuecomment-225953808

* [x] Format
* [x] Level

**Comment by aviaryan** [comment]
@shivamMg I can work on this issue now if you are busy.

**Comment by mariobehling** [comment]
@aviaryan Yes, please do. Thank you.

**Comment by aviaryan** [comment]
@mariobehling will do

**Comment by mariobehling** [comment]
@aviaryan Documentation should be part of any development.
* [ ] Please update the documentation https://github.com/fossasia/open-event-orga-server/blob/development/docs/API.md

**Comment by aviaryan** [comment]
@mariobehling I agree. Sorry I forgot about it. Opened PR #895 for it.

**Comment by shivamMg** [comment]
@aviaryan So this can be closed now?

**Comment by aviaryan** [comment]
Yes I think
