### ISSUE TITLE
Social links have wrong width when adding new

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#822]
![screen shot 2016-06-15 at 00 20 23](https://cloud.githubusercontent.com/assets/2479753/16061740/173419b0-328f-11e6-892c-fc9beef0a7a2.png)

**Comment by niranjan94** [comment]
Where are these social link fields? Which form?

**Comment by mariobehling** [comment]
It works for me at http://open-event.herokuapp.com/events/22/edit/ (Step 1).
