### ISSUE TITLE
Session Form: Make Title and Name always required

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#828]
In session forms in step 5 of the wizard make "Title" and "Name" always required. Maybe we should make those in another color, so it becomes clear that they cannot be edited or change the UI somehow?

![screenshot from 2016-06-15 08 17 55](https://cloud.githubusercontent.com/assets/1583873/16069896/257ff8d4-32d2-11e6-840d-53ea58adb955.png)

**Comment by niranjan94** [comment]
Okay ... will do.

**Comment by niranjan94** [comment]
![screencapture-localhost-5000-events-create-1465974801755](https://cloud.githubusercontent.com/assets/2404372/16071049/c55ba0fa-32f6-11e6-87e9-fead851830f2.png)

how about like this ? 
The name and title fields will also be disabled, so that the user can't change it.

**Comment by niranjan94** [comment]
I also feel the email field for the speaker should be compulsory. As that's the way we are able to relate speakers with their Open Event accounts,

**Comment by mariobehling** [comment]
Yes, was also thinking about the email, but there is a common use case, where an organizer will fill out the speaker info for VIPs and maybe does not fill in the info. I am unsure, what is the best decision. 

Well, maybe make it compulsory for now and we need to get feedback of other organizers at some point.
