### ISSUE TITLE
Change Session form and add pre-selection

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#843]
Change:
* [x] Rename "Abstract" to "Short Abstract"
* [x] Rename "Description" to "Long Abstract"
* [x] Rename "Web" to "Website"
* [x] Rename "Biography" to "Short Biography"

Take out:
 * [x] Sing up URL -> This url should be automatically generated by Open Event

Preselect Include Only:
* [x] Short Abstract
* [x] Slides
* [x] Photo
* [x] Short Biography
* [x] Web		
* [x] Twitter
* [x] Organisation		
* [x] Position		
* [x] Country

Add and Preselect Include in Session Form:
* [x] Comments -> This is a comment form for a private message to organizers.

Add and Preselect Include in Speaker Form:
* [x] Mobile/Phone
* [x] Short Biography

![screenshot from 2016-06-15 13 17 49](https://cloud.githubusercontent.com/assets/1583873/16077863/a8143d68-32fb-11e6-9e44-f2c52ceef595.png)

**Comment by niranjan94** [comment]
![screencapture-localhost-5000-events-create-1466002723329](https://cloud.githubusercontent.com/assets/2404372/16084843/cd07c7b6-3337-11e6-90c8-115ca97b6dec.png)

@mariobehling this is fine ?

**Comment by mariobehling** [comment]
Photo and Mobile is not preselected. Simply tick the points in this issue, please.

Please also move - Organisation, Position, Country - right after Photo please.

**Comment by mariobehling** [comment]
Rename Biography to Short Biography and Add Long Biography.
Preselect Short Biography.

**Comment by mariobehling** [comment]
When I try to edit events, some events have wrong states, e.g. Required is marked by Include is not. The state also was not saved correctly.

There should not be a "next" button on the last step in the wizard.

![screenshot from 2016-06-15 19 48 31](https://cloud.githubusercontent.com/assets/1583873/16091065/4c91cb2c-3332-11e6-909a-2341e31e2a8c.png)

**Comment by mariobehling** [comment]
Please also rename:
* [ ] Customize Session Form -> Customize Session Registration Form
* [ ] Customize Speaker Form -> Customize Speaker Registration Form

**Comment by mariobehling** [comment]
Add:
* [ ] Session Type
below "Tracks"

**Comment by niranjan94** [comment]
What are the available session types ?
