### ISSUE TITLE
Create Event Wizard Step 4: Increase Width of Call for Papers form a bit more and Make it full width in small screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#845]
This is about wizard step 4. Currently the form does not seem to be full width in small screens.

![screenshot from 2016-06-15 13 42 00](https://cloud.githubusercontent.com/assets/1583873/16078414/18b8ffe2-32ff-11e6-83fa-b619ee956779.png)

**Comment by SaptakS** [comment]
Will do this asap.

**Comment by SaptakS** [comment]
@mariobehling 
![profile](https://cloud.githubusercontent.com/assets/9530293/16078754/32e204bc-331e-11e6-9e52-e1988aced4fb.png)

**Comment by SaptakS** [comment]
@mariobehling  review
![screenshot from 2016-06-15 17 25 24](https://cloud.githubusercontent.com/assets/9530293/16078766/40e13484-331e-11e6-904e-dbd41238cea9.png)

**Comment by mariobehling** [comment]
Looks good.

**Comment by mariobehling** [comment]
Call for papers should be full width in very small screen resolutions, but it is not yet.
![screenshot from 2016-06-15 19 45 25](https://cloud.githubusercontent.com/assets/1583873/16090956/d3c75f7c-3331-11e6-8d56-5bb6d564a03a.png)

**Comment by niranjan94** [comment]
I will do this ...
