### ISSUE TITLE
What are the search pages and categories we have? We need search output pages for events and bottom categories

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#846]
Currently, the location on bottom show up already, but we do not have a structure for search pages. How can we implement something like that?

![screenshot from 2016-06-15 14 04 22](https://cloud.githubusercontent.com/assets/1583873/16079014/2668671a-3302-11e6-944e-1df943865b83.png)

**Comment by rafalkowalski** [comment]
I will work on this

**Comment by rafalkowalski** [comment]
@mariobehling What filters do we need? location, date, categories something else?

**Comment by mariobehling** [comment]
Yes, and also event type.

Search results should also take "Description" into account" and "short/long abstracts", e.g. if a key word shows up there.

I guess you are implementing a simple filter first.

We ultimately need a more advanced location filter, e.g. 20km around Berlin.

Please also consider, that many cities have the same name around the world.

**Comment by mariobehling** [comment]
I also see that past events show up in the search and on the home page list of upcoming events.

Maybe it is nice, if people can also search past events, but we should give the option somewhere "Search Past Events" and "Search Future Events".

**Comment by mariobehling** [comment]
Also seems like events that are in draft mode are showing up. Please take out "Drafts" of public search results.

**Comment by rafalkowalski** [comment]
- [ ] connect location input with map
- [ ] searching by date
- [ ] searching by category
- [ ] add pagination
