### ISSUE TITLE
Add a check list to the specific event dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#848]
How it should work:

**Checklist**
* [x] Each wizard step gets a row.
    * [x] Basic Details
    * [x] Sponsors
    * [x] Session, Tracks, Rooms
    * [x] Call for Speakers
    * [x] Session Forms

**Color Changes and Emoticons**
* [x] If the all essential elements have been filled in the widget background turns green and there is a tick at the end
* [x] If some parts are missing, but some basic information is there, the widget background turns yellow and there must be a small friendly warning element
* [x] If basic information is missing, the widget background turns red
* [x] If form is not getting used, e.g. "Call for papers is turned off", the widget background turns gray

**First step**
* Implement a simple widget without colors and make a row and edit button for each element

**Second step**
* Define for each form, what should be included to make it yellow or green.

**Third step**
* Document it in /docs

**Forth step**
* Implement it

Here an example. No need to do exactly the same, just use our design.

![screenshot from 2016-06-15 14 29 24](https://cloud.githubusercontent.com/assets/1583873/16079819/a77df632-3305-11e6-936a-02bd685e73ab.png)

**Comment by niranjan94** [comment]
@mariobehling so, where should this be displayed ?

**Comment by niranjan94** [comment]
- Where should this be located ? 
>  If the all essential elements have been filled in the widget background turns green and there is a tick at the end
- All the required elements (the ones marked with a *) are the essential ones ?

**Comment by mariobehling** [comment]
Where: Any event dashboard, e.g. http://open-event.herokuapp.com/events/22/
Just add a widget.

> All the required elements (the ones marked with a *) are the essential ones ?
At the moment we only require the event name and have `*`. It does not mean, that the event info is sufficient. We just require very little to get people started and enable them to save the event and continue later. Let's go the first steps and think along the way, how we define an event as red, yellow, green..

**Comment by niranjan94** [comment]
The basic UI prototype. I just added some temporary colors to see how it looks.

![capture](https://cloud.githubusercontent.com/assets/2404372/16109654/9b4da57a-33c7-11e6-9a75-a729d3e41156.PNG)

**Comment by mariobehling** [comment]
Very nice.

**Comment by niranjan94** [comment]
@mariobehling  ... thanks :) ... So, these are the states I have in mind. 

1. Basic details
	- **Yellow** - Event name, start time, end time, description are filled
	- **Green** - (Yellow) + Location + Organizer name + Organizer Description 
1. Sponsor Details
	- **Red** - No sponsors are added
	- **Yellow** - Only one sponsor is added but data is incomplete
	- **Green** - At Least one sponsor with all details has been added
1. Session, Tracks, Rooms
	- **Grey** - If turned off 
	- **Red** - If Either one of session, tracks rooms is missing
	- **Yellow** - if either of session, tracks has incomplete data (either color, title, duration missing)
	- **Green** - At Least One complete track, one complete session type, one complete room
1. Call for speakers
	- **Grey** - If turned off 
	- **Yellow** - if no announcement added  (timings are compulsory )
	- **Green** - Announcement added (timings are compulsory )
1. Create sessions form 
	- **Green** - IMO, this has only one state. As there always is some field force selected

**Comment by mariobehling** [comment]
Very good. We probably need to refine this as we get experience. This is an excellent start to this feature! Thank you.

**Comment by niranjan94** [comment]
@mariobehling Thanks a lot :) . Yes. As we progress and get more input from users, we can start refining this event better.
