### ISSUE TITLE
Create and adapt robots.txt according to site and user policy

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#850]
A robots.txt has to be served at `/robots.txt` to control search-engine crawler behaviour. (As said here #849)

_(For example) unlisted/private events should not come up on search listings_

**Comment by aviaryan** [comment]
I was looking on the [robots.txt spec](http://www.robotstxt.org/robotstxt.html) today and realize that a better way to prevent crawling of private events will be to add permissions check to events display page which will not allow other users entry (401 UNAUTHORIZED) if event is private. Ofcourse it will work for bots too. 

If we want to use robots.txt to prevent unlisted events from being crawled, we will have to update robots.txt file with every event create and edit. I think this is not a good solution and probably enterprises don't do this. Not to mention, the robots.txt file will become gigantic. 

We can use robots.txt to mask other things like `/static/media/` folder (uploads storage directory) to prevent direct links of files from showing up in search. 

@niranjan94 @mariobehling views ?

**Comment by mariobehling** [comment]
I think the option "Private page: do not list this event publicly" just means it is accessible to anyone who has the link but not listed on search engines and our internal search.

The question about the robots.txt is also, if there can be a number of robots.txt to keep the size down. Actually if an event is not listed in the sitemap.xml and is not linked on any public search from us, it should not be possible that a search engine finds it.

So, apart from the robots.txt, please also think about the implementation of a sitemap.xml and possibly open an issue for it.
