### ISSUE TITLE
Create an admin page to see all users and an edit link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#853]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/863

We need an admin page to look into issues of users with their profiles if necessary. Please
* [x] set up a page with all users on `/admin/users/`
* [x] restrict access to super admins
* [x] add a button for edit profiles
* ~~add a button to edit users roles~~ (we can do that in permissions)

See an example below:
![screenshot from 2016-06-15 15 08 49](https://cloud.githubusercontent.com/assets/1583873/16080963/919be1ca-330b-11e6-9394-98740f1f3db7.png)

**Comment by shivamMg** [comment]
@mariobehling The owner (creator) of the event would be the admin of that event, right?

**Comment by mariobehling** [comment]
Yes, correct.

**Comment by mariobehling** [comment]
Fields in the heading that make sense for us are:
* [ ] Name
* [ ] Email
* [ ] Role
* [ ] Member Since
* [ ] Last Access
* [ ] Options

**Comment by mariobehling** [comment]
The system info say "Your event has been deleted". System info should be related to user.
