### ISSUE TITLE
Create an overview of permissions and enable admin to edit specific permissions of roles

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#854]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/863

Please
* [x] add a permissions page at `/admin/permissions/`
* [x] restrict access to super admin only
* [x] enable super admin to edit specific roles to change permissions
* [x] make a list of features and add tickboxes for specific roles

Related to https://github.com/fossasia/open-event-orga-server/issues/853

See an example here:
![screenshot from 2016-06-15 15 06 27](https://cloud.githubusercontent.com/assets/1583873/16081140/81f70b54-330c-11e6-9f2e-667680db1311.png)

**Comment by shivamMg** [comment]
@mariobehling @rafalkowalski What would a complete user mean? Authenticated users are those that are logged into our site, rest are anonymous users.

**Comment by mariobehling** [comment]
The image is just an example. We have our own permission categories/users.

**Comment by shivamMg** [comment]
@mariobehling Alright :+1:

**Comment by shivamMg** [comment]
Add options to edit Event specific roles:

- Organizer
- Track Organizer
- Co-organizer
- Moderator
