### ISSUE TITLE
Screen Height erroneous at different resolutions/browser sizes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#868]
Please try to resize each step of the wizard at different screen sizes. Partly things get cut off e.g. step 5 and at other points there is a hug empty area.

![screenshot from 2016-06-15 20 29 51](https://cloud.githubusercontent.com/assets/1583873/16092425/1fd51426-3338-11e6-8180-5f3f11daf39d.png)
![screenshot from 2016-06-15 20 29 27](https://cloud.githubusercontent.com/assets/1583873/16092423/1fd341b4-3338-11e6-91fd-5d194e670a2c.png)
![screenshot from 2016-06-15 20 28 26](https://cloud.githubusercontent.com/assets/1583873/16092424/1fd36b26-3338-11e6-9dc5-75fb02d06666.png)
i

**Comment by niranjan94** [comment]
@mariobehling the wizard recalculates the screen height **only every time the page is loaded**. So, instead of resizing it, **refresh the page after resizing** to get the correct height.

**Comment by niranjan94** [comment]
So, I don't think this is a bug.

**Comment by SaptakS** [comment]
@mariobehling as suggested by @niranjan94 you need to reload the website after resizing to get the original sizing o f the various parts.. I think the problem will be solved.

**Comment by mariobehling** [comment]
Ok, so I understand why it happens. Thank you. Still, reloading is not a good option. We need to find a solution as this is not the expected behavior. There are other issues, e.g. when you load the page and the top line is gray for a short moment and then changes color. 

Such things just make the user feel the sites are still under development and unfinished. Try out any major site on the web, these kind of thing do not happen. If you do not know a solution yet, we can think about it later, but we need to solve this at some point.

**Comment by mariobehling** [comment]
Unfortunately not entirely solved. I am moving this to a later milestone as we can implement basic functionality and get out such small bugs later.
