### ISSUE TITLE
Create an admin page for reports

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#872]
Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/863

We need an admin page for reports. Please
* [x] set up an empty placeholder page with the heading "Reports" on `/admin/reports/`
* [x] restrict access to super admins

**Comment by rafalkowalski** [comment]
@mariobehling what should be included in reports page?

**Comment by mariobehling** [comment]
For now only the logs.

**Comment by mariobehling** [comment]
How to avoid the scroll bar? Where are the logs saved?

There was a discussion here https://github.com/fossasia/open-event-orga-server/issues/1067#issuecomment-227366258, that there could be two logs tabs a) mails b) other logs.

I expected something more like in our usual style, e.g.
![screenshot from 2016-06-22 14 30 43](https://cloud.githubusercontent.com/assets/1583873/16266625/1e17704a-3886-11e6-97fa-44e774c2bbe1.png)

**Comment by rafalkowalski** [comment]
@mariobehling it's live preview from heroku server, I don't store it

**Comment by mariobehling** [comment]
@rafalkowalski We will probably not run the system on a heroku system but on a normal server. So, getting this from heroku is not so important. 

What we need is all logs of the open event system. What is happening? Who is doing what? E.g. logs of "event has been created". Maybe you could start to make a list of things to collect.

We already have the logs from the mail system.

**Comment by rafalkowalski** [comment]
ok cool i will prepare a list

**Comment by mariobehling** [comment]
Please create a new issue to follow up on reports.
