### ISSUE TITLE
Set up and improve process to add co-organizers etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#873]
This feature is on the dashboard of events at `/events/ID/`

Think of this process like as if someone is invited to be co-admin etc. at a Facebook Page.

* [x] Send Email with Sign up/Acceptance Link
* [x] If user is already in system, show message in dashboard of invited user "You have been invited to event xyz. Wanna accept?"
* [x] Show in dashboard of invitee who has been invited and who has accepted

Enable Event Specific Roles (compare to https://github.com/fossasia/open-event-orga-server/issues/623)
 * [x] ORGANIZER
     - can edit event/remove
 * [x] CO-ORGANIZER
    - can edit event
 * [x] TRACK-ORGANIZER
    - can edit tracks
 * [x] MODERATOR
    - can see tracks before they are published but not edit them

![screenshot from 2016-06-16 01 40 31](https://cloud.githubusercontent.com/assets/1583873/16101189/30346296-3364-11e6-80a9-1bb26ecb55b8.png)

**Comment by shivamMg** [comment]
@mariobehling About the "show message in dashboard of invited user" part, should first implement a notifications area for the user. Sooner or later we will need such an area where we can send updates to the user. These will not be limited to invites, but also messages from Admin, updates about coming (near future) events that the user might have bookmarked, updates about our platform, updates about ticket sales getting started, etc. Kind of what facebook has. We can implement this notification feature before starting up on this issue. What do you think?

**Comment by mariobehling** [comment]
@shivamMg Yes, good idea, but we need to keep it really simple and we do not need a fully fledged messaging system. This is not our core feature. So, please open an issue and describe your idea. Let's follow up on this issue next week and focus on bug hunting and fixing existing stuff first.

**Comment by shivamMg** [comment]
@mariobehling Will focus on existing bugs this week :+1:

**Comment by shivamMg** [comment]
@mariobehling The email invitation part of this has been done [PR](https://github.com/fossasia/open-event-orga-server/issues/1195). Instead of directly creating a role an invitation email is sent to the user. If the user accepts the invitation then that particular role is added to the event. 

Shall I start working on the notifications system so the second point can be worked on?

> If user is already in system, show message in dashboard of invited user "You have been invited to event xyz. Wanna accept?"

**Comment by mariobehling** [comment]
Thank you. Please align with @SaptakS regarding the notifications. We do not need two people to do the same thing, but if there is no overlap, please proceed.

**Comment by shivamMg** [comment]
* [ ] Shift link validation checking to RoleInvite model (will be used to show expired links in templates)

**Comment by shivamMg** [comment]
Closing this now.
