### ISSUE TITLE
Implement Billing Process

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#879]
Process is as follows.

1. User gets an email with bill
2. User pays online through service
3. User is redirected to confirmation page
4. Confirmation page has two links a) View Receipt b) View Billing Details
5. User gets an email with Bill Payment Confirmation and a Bill number

**Comment by niranjan94** [comment]
@mariobehling this billing process would be used for what all functionalities other than ticketing ?

> User pays online through service

which service would we be using for the online payments ?

**Comment by mariobehling** [comment]
@niranjan94 I could imagine that import/export functions and create an Android app are part of a pro-feature.

How do you think this would be best implemented? I was thinking about having products free/pro/biz. How do other sites, e.g. Woocommerce do it?

**Comment by niranjan94** [comment]
Yes. That's a good idea. Import/export, android app, webapp could be a pro feature. So, would pro feature be a subscription or a one-time payment ? Would it be event level or user level ? 

For payment method, Woocommerce uses paypal by and has extensions for other payment services like amazon payment, stripe, etc. We could use [stripe](https://stripe.com/sg) (which is really good) or PayPal.

**Comment by niranjan94** [comment]
Closing in favour of #1848
