### ISSUE TITLE
Create Event Wizard Step 2: Add delete sponsor option 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#880]
Currently sponsorship fields cannot be deleted.
![screenshot from 2016-06-16 08 38 57](https://cloud.githubusercontent.com/assets/1583873/16107641/e5ff7ca8-339d-11e6-932a-baceac724769.png)

**Comment by mariobehling** [comment]
Next step: Please implement same style as other areas in the wizard. E.g.:
![screenshot from 2016-06-17 09 31 02](https://cloud.githubusercontent.com/assets/1583873/16143641/4c8a17f0-346e-11e6-814d-eb4fb2da735c.png)

**Comment by SaptakS** [comment]
You want this style of removing? The red button. Don't you think it will look a little odd in the table display?

**Comment by mariobehling** [comment]
Yeah, maybe right. We need to think about this anyways later, cause on mobile it is not so good yet. But, you are probably right. Just keep it. I was just confused, that there is again a different UI element.

**Comment by SaptakS** [comment]
@mariobehling agreed. I guess a lot of UI need to be modified for mobile.
