### ISSUE TITLE
Add Image upload to the Profile page

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#883]

**Comment by SaptakS** [comment]
![profile](https://cloud.githubusercontent.com/assets/9530293/16109354/f7658f50-33c5-11e6-91b1-f767ebe8ce35.png)

@mariobehling @aditya1702 please review.

**Comment by aditya1702** [comment]
Seems good to me

**Comment by mariobehling** [comment]
Not working on live system.

**Comment by aditya1702** [comment]
@mariobehling This is just the UI. I am working on the backend functioning of it
