### ISSUE TITLE
Complete and update API fields and documentation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#896]
There are a number of API fields, that do not seem to be added yet e.g. Audio and Video. 
* [x] Please check which fields are missing and add them.
* [ ] Document and update the API docs at https://github.com/fossasia/open-event-orga-server/blob/development/docs/API.md
* [x] Provide a full set of sample JSON import/export files using the data of the OpenTechSummit https://github.com/OpenTechSummit/2016.opentechsummit.net/tree/gh-pages/programm/json

**Comment by mariobehling** [comment]
I guess, in this issue you need to go through the wizard and check if really all fields are represented in the API already.

**Comment by aviaryan** [comment]
@mariobehling Ok. I'll see. There is authentication information missing too in the doc, I will add it. 

* [ ] Add Authentication info in API.md
