### ISSUE TITLE
Propose and implement a Tickets API covering

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#904]
* [ ] Make a list of fields
* [ ] Outline Tickets API
* [ ] Implement API
* [ ] Document API

**Comment by shivamMg** [comment]
- Add two new fields to Event db model:
  - `total_tickets`: Number of tickets made available by the Organizer.
  - `ticket_price`: The price of one ticket.
- Create Tickets db model:
  - `event`: Event the ticket is associated to.
  - `user`: The user who has booked tickets.


We can take out Tickets API for an event at:

```
/events/:event_id/tickets
```

To book a ticket the user will specify the quantity of the tickets he needs, and the event. We will check the number of available tickets at the server (`total_tickets` - no of tickets booked) for the event, and give proper response. 

- Tickets not available.
- Only <number> Tickets available. (if user specified higher quantity of tickets)

If tickets are available, they will be created.

**Comment by mariobehling** [comment]
Please have a look at Eventbrite and Eventnook and create a list of all functions we need. This is a parent issue, that cannot be solved in one day. Please create subissues.

**Comment by mariobehling** [comment]
@shivamMg How does your plan today to "start work on the Ticketing API" align with the existing implementation of the ticketing of @niranjan94? What is the goal and next steps with the API now?

**Comment by niranjan94** [comment]
For the API, we could have it like 
1. A `GET` request is made to `/api/v2/events/:event_id/tickets` to get a list of tickets that are available for purchase
2. A `POST` request is made to `/api/v2/events/:event_id/tickets/:ticket_id/purchase` with the quantity, fullname, email, address, country, state, zip, credit/debit card number, cvv, expiry to initiate an order. 
3. We make the transaction with stripe and return the order confirmation ID, a url to view/download the invoice. An email is also sent with the invoice.

**Comment by mariobehling** [comment]
I thought internally we also use APIs for the ticketing, but I did not have the chance to look into this so much.

Let's ask this question now as we have little time: How much effort is it to make API calls and do we really need it at the moment?

An idea for an alternative: If we just add a button "Register" or "Tickets" to external websites. We could call a JS lightbox or popup (though could be a problem because of blockers) to call the ticket box from the server.

See here for the idea:

![screenshot from 2016-07-31 13 25 16](https://cloud.githubusercontent.com/assets/1583873/17276219/9366ab26-5722-11e6-9f7b-c94e3537cbda.png)

On click this:

![screenshot from 2016-07-31 13 25 41](https://cloud.githubusercontent.com/assets/1583873/17276221/9b460328-5722-11e6-9851-ea8bc62db3fb.png)

**Comment by niranjan94** [comment]
@mariobehling IMO, ticketing API is not required at the moment. We don't currently have a requirement for that. We could just have an endpoint to show a list of available tickets. 

The alternative suggested by you seems to be a better option. We could make small javascript library which external services or maybe even the webapp can include to provide a button and a lightbox.

**Comment by mariobehling** [comment]
@niranjan94 Ok, great. Please open an issue and close this issue, when done.

Let's first get more into making the whole ticketing work and let's get an overview ticket page for users going before moving to the external apps. Thank you.

**Comment by niranjan94** [comment]
sure @mariobehling :+1:

**Comment by niranjan94** [comment]
Closing in favor of #2385.
