### ISSUE TITLE
Add session type in API

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#916]
Parent Issue #896 

Session Type is missing in API (Sessions API).

**Comment by aviaryan** [comment]
@shivamMg I am confused about what APIs should we create for session_type . We atleast need create, get list, update and delete APIs.

**Comment by aviaryan** [comment]
As I am not sure whether to create API for session types or not, I will just add session_type in Sessions API for now.

**Comment by mariobehling** [comment]
Yes, good decision. Let's use the existing APIs.
