### ISSUE TITLE
Lower permissions for registered but unverified user

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#921]
Let's take twitter as an example. As long as a user does not verify an account it is not possible to perform different tasks.

And this is what we want: A user should be able to enter email and password, but as long as the email is not confirmed, the user cannot make an event live. Please consider what is required to make this possible.

* [x] Check and change the current sign up process to support this (Currently unconfirmed get a message "check your mail". This message should be a system message after sign up and the user should be directed to the normal page.
* [ ] Do we need a lower role for this kind of user? Or is it implemented differently?

**Comment by aviaryan** [comment]
Right now, registered but unverified user are not stored in the database. Instead their email-password is serialized and set as hash of confirmation link. When they confirm through the link, the hash is de-serialized to get their credentials and the account is created. To proceed this issue, we will need to add a new bool column `is_verified` in the user model and make related changes to registration code. I will open an issue for it and do it.
