### ISSUE TITLE
Document APIs with Additional Information and Response Samples

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#924]
In order to enable other projects to connect with Open Event, let's refine the API documentation even more. There is a similar project, though smaller in scope, of the Drupal community. Please compare to the API documentation example [here](http://connfa.com/api/getspeakers/) and add details to our API.md (no need to separate the document for the moment, keep all in one document).

Please improve, add and fill in:
* [x] Add section and table with Title, Url, Method, Params
* [x] Document Error Responses
* [x] Column Description in Table
* [x] Create Response Models

**Comment by shivamMg** [comment]
Our API documentation can be found at https://open-event.herokuapp.com/api/v2.
