### ISSUE TITLE
Admin: Sessions use admin style table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#949]
In the user space we will adapt the design more and more to make it more suitable for normal users. In the admin area the table design is most suitable. 

Please implement the same table design as in the other sections of the admin area in the sessions section at `/admin/sessions/`.

Instead of "Upcoming/Past" use the following tabs

* [x] All Sessions
* [x] All Pending
* [x] All Accepted
* [x] All Rejected
* ~~Create Session~~

And implement the following table head columns:

* [x] Event
* [x] Title (of Session)
* [x] Speaker
* [x] Date of Submission
* [x] Date of Event
* [x] Organizer
* [x] Options

**Comment by mariobehling** [comment]
I think "Create Session" - we need to take it out as it currently does not fit into the structure with different forms etc. So, let's keep it more simple for now.

**Comment by mariobehling** [comment]
![screenshot from 2016-06-19 16 31 21](https://cloud.githubusercontent.com/assets/1583873/16177954/b9345dce-363b-11e6-8d52-ff9bab459122.png)

* [ ] Please in all views always move "Show xx Sessions" next to tabs
* [ ] Move "Search" on the left in tabs row
* [ ] Show 25 entries as standard

**Comment by mariobehling** [comment]
Unfortunately dropdown menu does not seem to work anymore.
![screenshot from 2016-06-21 11 58 38](https://cloud.githubusercontent.com/assets/1583873/16225594/ae58e33a-37a7-11e6-9b5a-9f510109884e.png)

**Comment by mariobehling** [comment]
Still not working in live system.

**Comment by rafalkowalski** [comment]
@mariobehling it's working now
