### ISSUE TITLE
Admin: Implement Search and Number of Items to show in Admin section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#950]
Please implement search and number of items in following admin sections with the standard table view:
* [x] Events
* [x] Sessions
* [x] Users

Number of items to show
* [x] 25
* [x] 50 (standard choice)
* [x] 100
* [x] 200

Examples:
![screenshot from 2016-06-17 18 30 55](https://cloud.githubusercontent.com/assets/1583873/16157940/17212660-34bb-11e6-8c90-fcdfa059b10c.png)

![screenshot from 2016-06-17 18 35 38](https://cloud.githubusercontent.com/assets/1583873/16157935/0e7c5408-34bb-11e6-991c-af13e5e8c8cf.png)

**Comment by rafalkowalski** [comment]
@niranjan94 @SaptakS I don't kave idea how can i move page length and search to the same level,

Problem which i've met is overlaps others searching and page length.

**Comment by niranjan94** [comment]
@rafalkowalski I'll see if i'm able to move it

**Comment by mariobehling** [comment]
* [ ] Please change the position of "number of sessions" and "search" in sessions section as well.

![screenshot from 2016-06-21 10 06 07](https://cloud.githubusercontent.com/assets/1583873/16222340/cf2dd1fc-3797-11e6-8db9-1b653429c45e.png)

**Comment by mariobehling** [comment]
In manage "all events" the tabs are positioned nicely, but:
* [ ] Events do not show up anymore (but there are events live)

![screenshot from 2016-06-21 10 20 15](https://cloud.githubusercontent.com/assets/1583873/16222699/d07e0692-3799-11e6-8b36-6e2733127710.png)

**Comment by rafalkowalski** [comment]
I will do it

**Comment by mariobehling** [comment]
Please ensure, that users can click on "Show xx entries" and search works.

**Comment by rafalkowalski** [comment]
@mariobehling it's fixed
