### ISSUE TITLE
Where can users see in which event they have which role?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#951]
The model of meetup might be interesting here.

**Comment by shivamMg** [comment]
@mariobehling User's profile could a good place to list his roles in different events.

**Comment by mariobehling** [comment]
Actually, the dashboard is already the place, where all my events are listed. Yes, the profile can provide some info on that in future as well. But, actually we need to consolidate the system at the moment. There are too many bugs and small issues to finish on too many areas. Closing this for now.
