### ISSUE TITLE
Implement Role: Registered User

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#952]
Any user needs to have a role, so we can sort, find and adapt permissions for groups of users easily in the admin section https://open-event.herokuapp.com/admin/users/. Every user who registers should automatically get the role "Registered User".

This is also related to the issue https://github.com/fossasia/open-event-orga-server/issues/921 about unverified registered users.

Please implement the collection of the following data:
* [x] Sign up date
* [x] Last Access Date

**Comment by aviaryan** [comment]
I am working on implementing sign up date and last access time .

**Comment by aviaryan** [comment]
There is no need of a role of "Registered User" as to filter registered users on the site, we can use 
`flask_login.current_user.is_authenticated` . Also registered users which are not part of an event will generally have no previledges except "read". @mariobehling So I think this is not needed.

**Comment by mariobehling** [comment]
@aviaryan The registered user has indeed more rights, than a user, that is "registered but has not confirmed his/her email". 

The goal of having different system roles is to be able to fine-grain permissions a) for event roles and b) for system roles.

As we now have ticket options, we also need the role "attendee", which should be discussed in a separate issue. 

I have opened an issue to follow up on these points and make it clearer: https://github.com/fossasia/open-event-orga-server/issues/1990
