### ISSUE TITLE
Scheduler: Cannot drag and drop items

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#953]
I tried out event: https://open-event.herokuapp.com/events/59/scheduler/

**Comment by mariobehling** [comment]
* [ ] Please only show "accepted" sessions" for the scheduler

**Comment by mariobehling** [comment]
Getting an error message on live system.

![screenshot from 2016-06-18 11 41 38](https://cloud.githubusercontent.com/assets/1583873/16170170/ff21c3dc-3549-11e6-822f-2b0f27d856ab.png)

**Comment by niranjan94** [comment]
@mariobehling which event ? 

(seems to work fine for me here http://open-event.herokuapp.com/events/61/scheduler/ )

**Comment by mariobehling** [comment]
http://open-event.herokuapp.com/events/50/scheduler/

**Comment by mariobehling** [comment]
Maybe related to https://github.com/fossasia/open-event-orga-server/issues/976

**Comment by niranjan94** [comment]
@mariobehling No. it's unrelated to that. It's an issue with the API Validation. API wants Long abstract. But that session doesn't have it. 

@aviaryan @shivamMg the validation for the session and speaker API must be dynamic based on the fields selected by the user.

**Comment by aviaryan** [comment]
@niranjan94 So `long_abstract` field is not compulsary. I thought since in database, `long_abstract` is not nullable, it will be compulsary. 
Never mind, can you give an insight into how custom form is being stored in the database. And how can  we retrieve data from it.

**Comment by niranjan94** [comment]
@aviaryan ... @SaptakS implemented that part. I think he'll be able to assist you better.

**Comment by SaptakS** [comment]
@aviaryan except for the Title of the session, none of the fields are necessarily compulsory.. It is upon organizer to decide whether he wants to make that field required. I believe we will need to make modifications in the database table for these other fields.

**Comment by aviaryan** [comment]
@SaptakS How are you storing custom forms (in session_form and speaker_form fields) in the CustomForm model ? I will need it to validate a speaker or session post/put request according to the event .

**Comment by aviaryan** [comment]
@mariobehling This issue should be fixed now.

**Comment by niranjan94** [comment]
Yes. Fixed.
