### ISSUE TITLE
Scheduler: Only show session times defined in the event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#976]
In the first step of the wizard the user adds a time for the event. Only show the available time in the scheduler, where the session can be entered.

Might be related to https://github.com/fossasia/open-event-orga-server/issues/953#issuecomment-226933080

**Comment by niranjan94** [comment]
@mariobehling This issue might take sometime (probably done by tomorrow) ... I'm having to rewrite parts of the scheduler to accommodate for the timings change across days (Eg. As day 1 may start at noon ... and day 2 would be from morning)

**Comment by mariobehling** [comment]
Please also put this into the a context of Time Zones. We need to offer the choice of timezones in wizard step 1 as well.

**Comment by niranjan94** [comment]
@mariobehling the timezone implementation would require some additional changes. So, I have opened a separate issue for it at #1091
