### ISSUE TITLE
Enable logo/image upload on add event page, sponsor page, speaker pages etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#98]
Uploads of images needs to happen, where the data is collected, e.g. right at the event page, sponsor page etc.

![screenshot from 2015-08-09 14 39 45](https://cloud.githubusercontent.com/assets/1583873/9154903/cf1b574e-3ea4-11e5-863f-4a4268d96888.png)
![screenshot from 2015-08-09 14 25 06](https://cloud.githubusercontent.com/assets/1583873/9154834/89e3c564-3ea2-11e5-86b1-78c6465442df.png)

**Comment by SaptakS** [comment]
I would really like to solve this issue. Should there be provision for only single image upload or multiple upload?

**Comment by leto** [comment]
@SaptakS let's start with just a single image and lets say that the image should be less than 1MB or else it is rejected. Let me know if you have more questions!

**Comment by SaptakS** [comment]
ok, i will start working on it..
