### ISSUE TITLE
Create Placeholder Pages for Organization Pages linked from Botton Areas

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#980]
* [x] How it Works
* [x] Pricing
* [x] Mobile Apps
* [x] Sitemap
* [x] About 
* [x] Blog 
* [x] Help 
* [x] Press 
* [x] Security 
* [x] Developers
* [x] Privacy
* [x] Cookies

**Comment by rafalkowalski** [comment]
@mariobehling can we close it?
