### ISSUE TITLE
Admin: Add Logs tab and implement logs collection

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#984]
Currently, there is no visible way to see what happened on the system.

1. [x]  Make a proposal of what system events and how we can collect them.
2. [x] Implement the system logs at `/admin/logs/` and add a tab into the menu at `/admin/` using the existing design
3. [x] Document what logs you keep and how you collect them

**Comment by aviaryan** [comment]
After some thinking, I think we should mainly collect create scenarios. like - 
- User registers
- Event is created
- Session is proposed

We can skip creations of microlocations, tracks etc.

In addition, we can store logs for --
- When an event goes live
- When an event is completed

In the log, we can store timestamp, actor and the message.
The `actor` will be the user who caused that logged event.
The `message` will include hyperlinks to objects (events, sessions) etc. 

@mariobehling please provide your thoughts

**Comment by mariobehling** [comment]
Yes, excellent. Let's start like that.

Please also take into account: 
* Who created an event
* Who deleted/edited an event
* Who changed/edited email and profile information
* Who provided roles/accepted etc. roles

Such things are important in case there is a dispute, hack of a personal account etc.

**Comment by aviaryan** [comment]
@mariobehling :+1: sounds good . Will do it.

**Comment by mariobehling** [comment]
What is the difference between logs and report?
a) Logs show all system events
b) Status report can show all kinds of things and could show lists and diagrams that help to understand what is going on, e.g.
  * a status report about your site's operation and any detected problems.
  * Available updates
  * Recent hits
  * Top referrers
  * Top pages
  * Top visitors

**Comment by mariobehling** [comment]
Other things to log:
* [ ] User logged in/out with IP, browser, platform etc.
* [ ] User was assigned/unassigned system role by who
* [ ] User changed email address (save what email he had before!)
* [ ] User exported/imported event
* [ ] User published/unpublished event
* [ ] More...

**Comment by mariobehling** [comment]
@aviaryan Please check here https://github.com/fossasia/open-event-orga-server/issues/984#issuecomment-227087765 and here https://github.com/fossasia/open-event-orga-server/issues/984#issuecomment-227994097 which parts are solved and close this issue when all has been implemented. Thank you.
