### ISSUE TITLE
proposal/autocompletion cities

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#988]
@niranjan94 @SaptakS @aviaryan @aditya1702 
First idea:
I've found a json which contains all cities i think it can help us to solve autocompletion.
https://raw.githubusercontent.com/David-Haim/CountriesToCitiesJSON/master/countriesToCities.json

Second: 
we can store all cities to our database then we can easy make a simple query to API,
But to do this we need most advanced location system

Any ideas how we can solve it in the most efficient way?

**Comment by aviaryan** [comment]
We will need to use some indexing and divide-and-rule to speed up searches.. 
For starters, suppose if we are storing these cities in DB, we can make a table ListCities as (prefix, list) . This prefix will range from aa, ab, ac ... az, ba .... zz . 
We will have that column indexed.
Then when time of query comes we will take the first 2 chars from query string and query out its `list` from the db. `list` is a space-separated list of city names. 
As now the entire city list is divided into small parts, query will be faster. 
We can even try prefix of len 3 (aaa, aab, aac, .... zzz) and only store those prefix in DB who have cities in the list. (i.e. not store zzz as there are probably no cities starting with it)

Ofcourse this is assuming that you don't want the auto-complete system to list 'Singapore' if you search for 'gapor'. 

> But to do this we need most advanced location system

I don't understand what you mean here ?

**Comment by rafalkowalski** [comment]
@aviaryan I mean that we need to save more params like address, city, zip/postal

**Comment by aviaryan** [comment]
> I mean that we need to save more params like address, city, zip/postal

I can't understand what has zip and address got to do with auto-completion of cities ? Please explain. 
As far as I get, the need in this issue is to auto-complete/show suggestions for the city field, right ?
Location can be divided into - address, zip, city and country . 
If there is a need to filter cities by country, we can still use the divide-and-rule method to speed up searches.
