### ISSUE TITLE
Validate speaker and session API according to custom forms

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#989]
Custom forms are used by the organizer to define which fields they want and require in their event.
The API should validate payload for sessions and speakers according to that custom form.

@SaptakS Can you please explain how form data is being stored in the customform model.

**Comment by aviaryan** [comment]
The format of custom forms can be seen in this commit by @niranjan94 . https://github.com/fossasia/open-event-orga-server/commit/3b6d07ab5b7b472ba751d1e9a251b1dbdf916c11

**Comment by mariobehling** [comment]
@aviaryan @SaptakS @niranjan94 Could be a good blog post topic.

**Comment by aviaryan** [comment]
@mariobehling Yes. I will write a post on it. :smile: 
Btw, this issue is not fixed yet. We now know the format in which custom forms are stored, the validation of speaker and session forms still needs to be done.

**Comment by SaptakS** [comment]
@aviaryan @mariobehling there is already a blog post on this. https://opev.wordpress.com/2016/06/17/open-event-organizers-server-custom-forms/

**Comment by SaptakS** [comment]
@aviaryan API the PR solves the API validation issue. But the Model shows this fields to be optional whatever the event id maybe. So we might need to deal with that.
