### ISSUE TITLE
Enable map choice and add address of location

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#99]
Organizers should be able to enter the address and choose a map location from the UI.
![screenshot from 2015-08-09 14 40 27](https://cloud.githubusercontent.com/assets/1583873/9154898/9762891c-3ea4-11e5-9427-ab1d4485d619.png)

**Comment by leto** [comment]
Let's use OpenStreetMap

**Comment by rafalkowalski** [comment]
OK @leto

**Comment by leto** [comment]
Let's use this API: http://wiki.openstreetmap.org/wiki/Overpass_API

Let me know how it goes!

**Comment by rafalkowalski** [comment]
@mariobehling @leto I added map to Microlocation view. Map based on @leto solution.
http://springboard.championswimmer.in/admin/event/1/microlocation/1/edit
